### ISSUE TITLE
Delete /binding

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#10043]
Forked from https://github.com/GoogleCloudPlatform/kubernetes/pull/9991#discussion_r32697587

We need to update the scheduler (ours and mesos) to use pods/binding instead of /binding and then we can delete /binding.

**Comment by nikhiljindal** [comment]
cc @bgrant0607 @smarterclayton

**Comment by bgrant0607** [comment]
This is about the top-level resource, not the subresource.

**Comment by nikhiljindal** [comment]
This is where mesos is using binding as top level resource: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/mesos/pkg/executor/executor.go#L470.
We need to change that to Resource("pods").Subresource("bindings")

**Comment by lavalamp** [comment]
@karlkfi @jdef If we turn this off in 1.2, will that be a problem for you?

**Comment by smarterclayton** [comment]
Did we announce we were going to remove this API?  Don't we need to have a process for taking it away?

**Comment by jdef** [comment]
Yes it would be problematic unless our scheduler was updated to use
whatever was replacing it. AFAICT even the core scheduler is still using
/bindings:

```
$ grep bindings plugin/pkg/scheduler/factory/factory.go
        return
b.Post().Namespace(api.NamespaceValue(ctx)).Resource("bindings").Body(binding).Do().Error()
```

**Comment by lavalamp** [comment]
Kicking this can down the road.

**Comment by smarterclayton** [comment]
We should mark this deprecated.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (155/150 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:7427)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGU59-000OoT-0x
	for dev@imwiz.com; Thu, 01 Jun 2017 11:40:23 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=1BHEx8/gp/W1tMlkNeeAqwctJdU=; b=aBn+NG3axTs4RnQA
	fnd2L6Bm/M/wdRTPS2/KVvCxOJoh2b4I1IbBFNGj7LJZpdBuc3cMK9dnLpMBN7wa
	RUMSbS5Hk5+aROvigz9WECBAMBCPryoTuYtXfLCfAvpCQaKQNIiegfBNwiXCWckt
	Cf1iHcdgW0frROyG9unOQ/8yDmY=
Received: by filter0617p1mdw1.sendgrid.net with SMTP id filter0617p1mdw1-24540-59305150-59
        2017-06-01 17:39:28.771314022 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id Ze3rcgD4QvaaP8NMIa6g8Q
	for <dev@imwiz.com>; Thu, 01 Jun 2017 17:39:28.689 +0000 (UTC)
Date: Thu, 01 Jun 2017 10:39:28 -0700

**Comment by k82cn** [comment]
According to https://github.com/kubernetes/kubernetes/pull/44883 , kube-mesos refactor will use HTTPExtender, so it's a not big issue to kube-mesos.

But for k8s, I think scheduler is using `pods/binding` API  now (https://github.com/kubernetes/kubernetes/pull/44482).

**Comment by k82cn** [comment]
/close

I'm going to close this; if any comments, please let me know.

**Comment by smarterclayton** [comment]
We need to actually mark the endpoint deprecated so we can remove it.

**Comment by k82cn** [comment]
OK, got that; need to deprecate it for other user. I think k8s can handle it to use `pods/binding`.

**Comment by k82cn** [comment]
@smarterclayton , can you help to remove `area/platform/mesos`? it's not related with Mesos anymore. I'll create a PR to deprecate `/binding`.

**Comment by nikhiljindal** [comment]
Reopening since that PR just added a deprecation warning. We still need to remove the API.

**Comment by k82cn** [comment]
wow, agree.

@nikhiljindal , would you help to remove milestone? We will not remove API in 1.7 or 1.8; but I'll trace that.

**Comment by nikhiljindal** [comment]
Done

**Comment by vsxen** [comment]
1.18  still have.

**Comment by bavarianbidi** [comment]
1.21 still have the `binding` resource. Is anyone already working on it or is there a reason why the binding resource still get served?

**Comment by bavarianbidi** [comment]
> 1.21 still have the `binding` resource. Is anyone already working on it or is there a reason why the binding resource still get served?

not entirely sure if i'm right, but from my current assumption it seems that there isn't an implementation for the `bindings subresource` for pods (xref: https://github.com/kubernetes/kubernetes/blob/0fe049cb93683e488b9829316ac889bc4c2e42fc/pkg/registry/core/pod/rest/subresources.go) and we still use the generic `binding` resource for pods (https://github.com/kubernetes/kubernetes/blob/0fe049cb93683e488b9829316ac889bc4c2e42fc/pkg/apis/core/validation/validation.go#L4500).

The `Binding` resource is deprecated since 1.7 but i don't see any further progress :thinking: 
> // Binding ties one object to another; for example, a pod is bound to a node by a scheduler.
> // Deprecated in 1.7, please use the bindings subresource of pods instead.
(https://github.com/kubernetes/kubernetes/blob/0fe049cb93683e488b9829316ac889bc4c2e42fc/pkg/apis/core/types.go#L4608-L4609)

**Comment by ialidzhikov** [comment]
@Huang-Wei @ahg-g what is the progress with this issue? Is it a backlog item that is tracked by sig scheduling?

**Comment by Huang-Wei** [comment]
@ialidzhikov I'm not aware of this issue. We will put it into our sig meeting to discuss.

**Comment by ahg-g** [comment]
Is there a summary of why moving this API is necessary given that is has been around for quite sometime now? Is it related to RBAC?

**Comment by Huang-Wei** [comment]
> Is there a summary of why moving this API is necessary

It's more to pay the technical debt. Given the action "binding" is performed against pods, composing a pod/binding instead of v1.Binding makes more sense.

Thanks @liggitt for clarification we cannot _remove_ v1 APIs.

**Comment by ahg-g** [comment]
ok, thanks for the clarification, so this is not enabling a new use case, only a cleanup.

**Comment by liggitt** [comment]
> so this is not enabling a new use case, only a cleanup.

Right, and due to the stable API compatibility guarantees, I don't think it's a cleanup we can do.

/close

**Comment by bavarianbidi** [comment]
Sorry for the late comment on this but i was AFK for a longer time.
I'm not sure if we missed something.

Currently there only exist the `v1.Binding` implementation.
via the [`PodExpansion` interface](https://github.com/kubernetes/kubernetes/blob/a1128e380c2cf1c2d7443694673d9f1dd63eb518/staging/src/k8s.io/client-go/kubernetes/typed/core/v1/pod_expansion.go#L31-L51) the `pods/binding` API endpoint exists but it refers to the only existing `Binding` kind (could be checked via `curl -s localhost:8001/api/v1 | jq '.resources[] | select(.name=="bindings" or .name=="pods\/binding")'`):

```json
{
  "name": "bindings",
  "singularName": "",
  "namespaced": true,
  "kind": "Binding",
  "verbs": [
    "create"
  ]
}
{
  "name": "pods/binding",
  "singularName": "",
  "namespaced": true,
  "kind": "Binding",
  "verbs": [
    "create"
  ]
}
```

As there isn't a seperate implementation for `pods/binding` IMO we should remove the deprecation warning [from the `Binding` type](https://github.com/kubernetes/kubernetes/blob/0ee8fed853eaf1903a55825d9c8359d7038f3ab9/pkg/apis/core/types.go#L4644-L4654) as we don't have an alternative implementation for that in place.

@Huang-Wei / @liggitt WDYT?
