### ISSUE TITLE
Migrating In-tree to CSI results in failed to attach: exceeds size limit: VolumeId: max=128, size=132

### ISSUE THREAD

**Issue by cormachogan** [kubernetes/kubernetes#101153]
#### What happened:

I wanted to test the new CSI migration feature. I followed the [vSphere CSI migration setup instructions](https://vsphere-csi-driver.sigs.k8s.io/features/vsphere_csi_migration.html) but after completing the steps, Pods that were previously using in-tree vSphere Cloud Provider would not come online. There were failing with the error:

```
Events:
  Type     Reason              Age                            From                     Message
  ----     ------              ----                           ----                     -------
  Normal   Scheduled           <invalid>                      default-scheduler        Successfully assigned cassandra/cassandra-2 to k8s-worker-01
  Warning  FailedAttachVolume  <invalid> (x8 over <invalid>)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-f5099bf4-a874-4bdd-9e66-87aba5081057" : rpc error: code = InvalidArgument desc = exceeds size limit: VolumeId: max=128, size=132
```

#### What you expected to happen:

After following the procedure, I would have expected all Pods to have successfully come online with volumes attached.

#### How to reproduce it (as minimally and precisely as possible):

Deploy vanilla K8s - in my case, v1.20.5 - on vSphere infrastructure.
Deploy an application - in my case, a Cassandra StatefulSet with 3 replicas - using the in-tree VCP driver
Deploy CSI driver - in my case vSphere CSI v2.1.0 - along with the steps to implement CSI migration (see link above)
During the step to drain the node, modify the kubelet config, restart the kubelet config and uncordon the node, the issue was observed

#### Anything else we need to know?:

These are the logs from the CSI attacher:

```
I0414 11:24:23.881601       1 controller.go:198] Started VA processing "csi-e0118ca1c84fcf9deb5c56a0a2b6fd8cb48253d046ab674d60f2dc3344a134f8"
I0414 11:24:23.881624       1 csi_handler.go:216] CSIHandler: processing VA "csi-e0118ca1c84fcf9deb5c56a0a2b6fd8cb48253d046ab674d60f2dc3344a134f8"
I0414 11:24:23.881634       1 csi_handler.go:243] Attaching "csi-e0118ca1c84fcf9deb5c56a0a2b6fd8cb48253d046ab674d60f2dc3344a134f8"
I0414 11:24:23.881642       1 csi_handler.go:422] Starting attach operation for "csi-e0118ca1c84fcf9deb5c56a0a2b6fd8cb48253d046ab674d60f2dc3344a134f8"
I0414 11:24:23.881887       1 csi_handler.go:342] Adding finalizer to PV "pvc-f5099bf4-a874-4bdd-9e66-87aba5081057"
I0414 11:24:23.887367       1 csi_handler.go:351] PV finalizer added to "pvc-f5099bf4-a874-4bdd-9e66-87aba5081057"
I0414 11:24:23.887398       1 csi_handler.go:715] Found NodeID k8s-worker-01 in CSINode k8s-worker-01
I0414 11:24:23.887539       1 csi_handler.go:304] VA finalizer added to "csi-e0118ca1c84fcf9deb5c56a0a2b6fd8cb48253d046ab674d60f2dc3344a134f8"
I0414 11:24:23.887558       1 csi_handler.go:318] NodeID annotation added to "csi-e0118ca1c84fcf9deb5c56a0a2b6fd8cb48253d046ab674d60f2dc3344a134f8"
I0414 11:24:23.891866       1 csi_handler.go:585] Saving attach error to "csi-e0118ca1c84fcf9deb5c56a0a2b6fd8cb48253d046ab674d60f2dc3344a134f8"
I0414 11:24:23.894782       1 csi_handler.go:596] Saved attach error to "csi-e0118ca1c84fcf9deb5c56a0a2b6fd8cb48253d046ab674d60f2dc3344a134f8"
I0414 11:24:23.894898       1 csi_handler.go:226] Error processing "csi-e0118ca1c84fcf9deb5c56a0a2b6fd8cb48253d046ab674d60f2dc3344a134f8": failed to attach: rpc error: code = InvalidArgument desc = exceeds size limit: VolumeId: max=128, size=132
```

The error appears pretty straight-forward - the volume size is above 128 chars. This is correct, as can be seen when the volume path is queried from the PV.

```
$ kubectl describe pv pvc-91c5826f-ed8e-4d55-a5bc-c4b31e435f5d
Name:            pvc-91c5826f-ed8e-4d55-a5bc-c4b31e435f5d
Labels:          <none>
Annotations:     kubernetes.io/createdby: vsphere-volume-dynamic-provisioner
                 pv.kubernetes.io/bound-by-controller: yes
                 pv.kubernetes.io/migrated-to: csi.vsphere.vmware.com
                 pv.kubernetes.io/provisioned-by: kubernetes.io/vsphere-volume
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    cass-sc-vcp
Status:          Released
Claim:           cassandra/cassandra-data-cassandra-1
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        1Gi
Node Affinity:   <none>
Message:
Source:
    Type:               vSphereVolume (a Persistent Disk resource in vSphere)
    VolumePath:         [vsanDatastore-OCTO-Cluster-B] d85b7460-17a6-6ea1-4b39-246e962f497c/kubernetes-dynamic-pvc-91c5826f-ed8e-4d55-a5bc-c4b31e435f5d.vmdk
    FSType:             ext4
    StoragePolicyName:  vsan-b
Events:
  Type     Reason              Age                         From                                                                                                 Message
  ----     ------              ----                        ----                                                                                                 -------
  Warning  VolumeFailedDelete  <invalid> (x87 over 6h31m)  csi.vsphere.vmware.com_vsphere-csi-controller-5f66cc9f7b-pzqgx_2a574edd-320b-4f10-a4fe-47a6e2af4892  rpc error: code = InvalidArgument desc = exceeds size limit: VolumeId: max=128, size=132
```

What seems odd is that the volume path seem to be different than previously observed with the in-tree VCP driver. I thought that the VolumePath used to use the "kubevols" folder but it seems that it is now using a uuid. 

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20.5
- Cloud provider or hardware configuration: vSphere 7.0U1
- OS (e.g: `cat /etc/os-release`): Ubuntu 17.10
- Kernel (e.g. `uname -a`): 4.13.0-46-generic #51-Ubuntu SMP

**Comment by pacoxu** [comment]
/sig storage
Same error as https://github.com/container-storage-interface/spec/issues/350#issuecomment-466271722
There is a length limitation that node mount paths exceed the 128 character limit.
/cc @Jiawei0227

**Comment by cormachogan** [comment]
A quick update to say that if I reduce the length of my vSphere datastore name, and the full path to the volume is only 124 characters, then the VCP->CSI migration process now works as expected. I think we need to bump up the number of character count supported in the volume path though. I'm sure many others will hit this issue once CSI migration is fully available.

(works)
    VolumePath:         [vsan-OCTO-Cluster-B] d85b7460-17a6-6ea1-4b39-246e962f497c/kubernetes-dynamic-pvc-920d248d-7e66-451a-a291-c7dfa3458a72.vmdk

(fails)
    VolumePath:         [vsanDatastore-OCTO-Cluster-B] d85b7460-17a6-6ea1-4b39-246e962f497c/kubernetes-dynamic-pvc-91c5826f-ed8e-4d55-a5bc-c4b31e435f5d.vmdk

**Comment by Jiawei0227** [comment]
Thanks for reporting this! This is a known issue and it is in our fix list. The csi spec change has been merged here: https://github.com/container-storage-interface/spec/pull/464
From k8s side, a preparation change in 1.21 is here: https://github.com/kubernetes/kubernetes/pull/98753
We are planning to completely relax the constraint in 1.22.

**Comment by divyenpatel** [comment]
We have a workaround for this issue - https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/801/files

cc: @chethanv28

**Comment by msau42** [comment]
/assign @divyenpatel 
/triage accepted

Is this issue fixed?

**Comment by Jiawei0227** [comment]
The length limit should be fixed in 1.22 in OSS. if you are using GKE, it is also back ported till 1.18
/close

**Comment by ericinfra** [comment]
> [当#101256](https://github.com/kubernetes/kubernetes/pull/101256)被合并时，这应该在 1.22 中得到修复。这目前被 CSI 规范发布阻止，这应该在本周内发布。


I upgraded from k8s 1.22 to 1.24 mount volume and still encounter the CSI 128 characters size limit. Is there a solution?


Events:
  Type     Reason       Age                     From     Message
  ----     ------       ----                    ----     -------
  Warning  FailedMount  38m (x436 over 20h)     kubelet  MountVolume.MountDevice failed for volume "k8s-78b0b52980" : rpc error: code = InvalidArgument desc = exceeds size limit: StagingTargetPath: max=128, size=142
  Warning  FailedMount  23m (x812 over 14h)     kubelet  Unable to attach or mount volumes: unmounted volumes=[nginx-data], unattached volumes=[kube-api-access-7mx4s nginx-data]: error processing PVC ml-infra/model-image-63aabb08af3decee95f96ba9-source-code-volume: failed to fetch PVC from API server: persistentvolumeclaims "model-image-63aabb08af3decee95f96ba9-source-code-volume" not found

**Comment by ericinfra** [comment]
> The length limit should be fixed in 1.22 in OSS. if you are using GKE, it is also back ported till 1.18 /close

I upgraded from k8s 1.22 to 1.24 mount volume and still encounter the CSI 128 characters size limit. Is there a solution?

···
Events:
  Type     Reason       Age                     From     Message
  ----     ------       ----                    ----     -------
  Warning  FailedMount  38m (x436 over 20h)     kubelet  MountVolume.MountDevice failed for volume "k8s-78b0b52980" : rpc error: code = InvalidArgument desc = exceeds size limit: StagingTargetPath: max=128, size=142
  Warning  FailedMount  23m (x812 over 14h)     kubelet  Unable to attach or mount volumes: unmounted volumes=[nginx-data], unattached volumes=[kube-api-access-7mx4s nginx-data]: error processing PVC ml-infra/model-image-63aabb08af3decee95f96ba9-source-code-volume: failed to fetch PVC from API server: persistentvolumeclaims "model-image-63aabb08af3decee95f96ba9-source-code-volume" not found
···
