### ISSUE TITLE
kubectl cp command fails when passing full Windows path such as c:\Temp\foobar.txt

### ISSUE THREAD

**Issue by VladimirKhvostov** [kubernetes/kubernetes#101985]
#### What happened:
The following command fails on Windows:
`kubectl cp c:\Temp\foobar.txt "pod-name:/tmp/forbar.txt" `
reporting the following:
`error: one of src or dest must be a local file specification`

This issue was already reported https://github.com/kubernetes/kubernetes/issues/77310 and fixed, but regression was introduced in kubectl v1.20.
This command copies file successfully in if kubectl version is 1.19, but fails in 1.20 and 1.21

#### What you expected to happen:
c:\Temp\foobar.txt should be copied to the pod.
#### How to reproduce it (as minimally and precisely as possible):
On Windows:
Create c:\Temp\foobar.txt file and try to run 
`kubectl cp c:\Temp\foobar.txt "pod-name:/tmp/forbar.txt" `

I believe, kubectl treats c in c:\Temp\foobar.txt as a pod name.

#### Anything else we need to know?:
Similar issue: https://github.com/kubernetes/kubernetes/issues/77310

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20 and v1.21
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Windows 10
- Kernel (e.g. `uname -a`): N/A
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by soltysh** [comment]
Potentially fixed in https://github.com/kubernetes/kubernetes/pull/94165

**Comment by soltysh** [comment]
This should be fixed in https://github.com/kubernetes/kubernetes/pull/94165
/close

**Comment by aearanky** [comment]
This is not yet resolved or a new regression was introduced. 

kubectl version as installed on my system is as below:
PS C:\Users\aditya.earanky\Bitbucket\my_repo> kubectl version --client
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3

**Error:**
PS C:\Users\aditya.earnky\Bitbucket\my_repo> kubectl cp C:\Users\aditya.earnky\Bitbucket\my_repo\test_files\my_test_file.txt dev/mytestpod-b57cb9b97-s9f6w:/tmp -c test_container
error: one of src or dest must be a local file specification

**Resolution: Using relative path**
PS C:\Users\aditya.earnky\Bitbucket\my_repo> kubectl cp .\test_files\my_test_file.txt dev/mytestpod-b57cb9b97-s9f6w:/tmp -c test_container
PS C:\Users\aditya.earnky\Bitbucket\fleet-simulator-kubernetes\helm>

**Comment by DeepSpace2** [comment]
Can confirm this bug still exists as of 

```
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

**Comment by needleshaped** [comment]
Client Version: v1.30.2 bug confirmed.

**Workaround**: go to path of file, and user relative name. e.g. `kubectl cp filename.ext $POD_NAME:/path`

**Comment by zenonwch** [comment]
Hi @soltysh,
Looks like the issue was not fixed (or appeared again).
Please re-open the issue, or should we create a new one?
Thanks.
