### ISSUE TITLE
Dockerd process leaking handles in K8s Windows worker nodes

### ISSUE THREAD

**Issue by phsys** [kubernetes/kubernetes#104789]
#### What happened:
The dockerd process is leaking handles (~2M) in Kubernetes Windows worker nodes, leading to huge (lot more than usual) memory and cpu consumption.

#### What you expected to happen:
The process is not expected to open so many handles as it is doing now. It's usual inter-process communication is probably expected to open lot less than 2 million handles.

#### How to reproduce it (as minimally and precisely as possible):
Windows server minimal installation with Docker and Kubernetes should be able to reproduce this issue.

#### Anything else we need to know?:
The handle leak goes on increasing with time until and unless the system is rebooted for maintenance, which implies unless the dockerd process is restarted.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19.11
- Cloud provider or hardware configuration: Hyper-V Virtual Machine
- OS : Windows Server 20H2 SAC
- OS Version: 10.0.19042
- Install tools: Docker
- CNI : Calico (Vxlan)

####Other details:

`PS C:\> get-process -Name dockerd

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
1953515      27   145448      78128 250,658.44   2980   0 dockerd
`

**Comment by phsys** [comment]
[dockerd-handle_2.zip](https://github.com/kubernetes/kubernetes/files/7113739/dockerd-handle_2.zip)

The leaking handles are in the file attached. Command (PowerShell) used:
`handle -a -p dockerd`

Dockerd process details:

`PS C:\> get-process -Name dockerd | fl *


Name                       : dockerd
Id                         : 2980
PriorityClass              : Normal
FileVersion                : 20.10.6
HandleCount                : 1953561
WorkingSet                 : 80003072
PagedMemorySize            : 148938752
PrivateMemorySize          : 148938752
VirtualMemorySize          : 315314176
TotalProcessorTime         : 2.21:37:51.9687500
SI                         : 0
Handles                    : 1953561
VM                         : 4610281472
WS                         : 80003072
PM                         : 148938752
NPM                        : 27480
Path                       : C:\Program Files\Docker\dockerd.exe
Company                    :
CPU                        : 250671.96875
ProductVersion             : 20.10.6
Description                :
Product                    : Docker Engine
__NounName                 : Process
BasePriority               : 8
ExitCode                   :
HasExited                  : False
ExitTime                   :
Handle                     : 1448
SafeHandle                 : Microsoft.Win32.SafeHandles.SafeProcessHandle
MachineName                : .
MainWindowHandle           : 0
MainWindowTitle            :
MainModule                 : System.Diagnostics.ProcessModule (dockerd.exe)
MaxWorkingSet              : 1413120
MinWorkingSet              : 204800
Modules                    : {System.Diagnostics.ProcessModule (dockerd.exe), System.Diagnostics.ProcessModule
                             (ntdll.dll), System.Diagnostics.ProcessModule (KERNEL32.DLL),
                             System.Diagnostics.ProcessModule (KERNELBASE.dll)...}
NonpagedSystemMemorySize   : 27480
NonpagedSystemMemorySize64 : 27480
PagedMemorySize64          : 148938752
PagedSystemMemorySize      : 969086728
PagedSystemMemorySize64    : 969086728
PeakPagedMemorySize        : 153571328
PeakPagedMemorySize64      : 153571328
PeakWorkingSet             : 81858560
PeakWorkingSet64           : 81858560
PeakVirtualMemorySize      : 319574016
PeakVirtualMemorySize64    : 4614541312
PriorityBoostEnabled       : False
PrivateMemorySize64        : 148938752
PrivilegedProcessorTime    : 2.17:47:49.9218750
ProcessName                : dockerd
ProcessorAffinity          : 255
Responding                 : True
SessionId                  : 0
StartInfo                  : System.Diagnostics.ProcessStartInfo
StartTime                  : 8/21/2021 2:59:38 AM
SynchronizingObject        :
Threads                    : {2992, 4700, 4704, 4708...}
UserProcessorTime          : 03:50:02.0937500
VirtualMemorySize64        : 4610281472
EnableRaisingEvents        : False
StandardInput              :
StandardOutput             :
StandardError              :
WorkingSet64               : 80003072
Site                       :
Container                  :`

**Comment by SergeyKanzhelev** [comment]
/remove-sig node

removing for now letting sig windows to triage

**Comment by SergeyKanzhelev** [comment]
Also dockershim removal is planned for 1.24, just FYI

**Comment by marosset** [comment]
This issue might be fixed in Docker EE 20.10.8

https://docs.docker.com/engine/release-notes/#20108
https://github.com/moby/moby/pull/42613 fixes a similar issue.

@phsys can you see if Docker EE 20.10.8 exhibits the same behavior?

**Comment by marosset** [comment]
/close

I believe this issue is addressed either Docker EE 20.10.8.

**Comment by phsys** [comment]
Upgraded to Docker EE 20.10.9 and the issue of docker leaking handles still persists. Can we please re-open this issue and try triaging it @marosset ?

**Comment by phsys** [comment]
Attaching a snippet highlighting the extent of handle leak
![dockerd_handle_leak](https://user-images.githubusercontent.com/90021542/152194405-6ee9dcbd-1c19-430a-a169-fc34b897f4e6.PNG)

**Comment by SergeyKanzhelev** [comment]
/reopen

(based on the comment from @phsys)

**Comment by marosset** [comment]
This issue should go to Mirantis for investigation.
@brasmith-ms - What is the best way to loop them in?
