### ISSUE TITLE
StrategicMerge patching null dict entry on empty dict creates the entry with empty string value

### ISSUE THREAD

**Issue by 2uasimojo** [kubernetes/kubernetes#105689]
### What happened?

Note: I'm using OpenShift. s/oc/kubectl/ below if that's how you roll.

I'm using a command similar to the following to idempotently ensure a label is absent on a Namespace object:
```console
$ oc patch namespace hive -p '{"metadata": {"labels": {"EFRIED": null}}}'
```
If the object's `.metadata.labels` contains _anything_ other than `EFRIED`, this works fine: the resulting object has no `EFRIED` key. However, if `.metadata.labels` is initially absent, this command adds it with an `EFRIED` entry with the empty string as a value:
```yaml
  labels:
    EFRIED: ""
```
Running the command again removes the entry and the `labels`.
Using this logic in a controller causes a hot loop as we thrash back and forth between the above and no labels.

### What did you expect to happen?

Using a `null` value in a dict in a StrategicMerge patch should idempotently ensure the key is absent, even if the dict is initially absent/empty.

### How can we reproduce it (as minimally and precisely as possible)?

```console
$ oc create namespace lebug
namespace/lebug created
$ oc get namespace lebug -o json | jq -r .metadata.labels
null
$ oc patch namespace lebug -p '{"metadata": {"labels": {"EFRIED": null}}}'
namespace/lebug patched
$ oc get namespace lebug -o json | jq -r .metadata.labels
{
  "EFRIED": ""
}
$ oc patch namespace lebug -p '{"metadata": {"labels": {"EFRIED": null}}}'
namespace/lebug patched
$ oc get namespace lebug -o json | jq -r .metadata.labels
null
$ oc patch namespace lebug -p '{"metadata": {"labels": {"something": "else"}}}'
namespace/lebug patched
$ oc get namespace lebug -o json | jq -r .metadata.labels
{
  "something": "else"
}
$ oc patch namespace lebug -p '{"metadata": {"labels": {"EFRIED": null}}}'
namespace/lebug patched (no change)
$ oc get namespace lebug -o json | jq -r .metadata.labels
{
  "something": "else"
}
```

### Anything else we need to know?

- I didn't try this on anything other than a Namespace; and I didn't try it on any dict other than `.metadata.labels`.
- Workaround: Add any other label, as seen above.

### Kubernetes version

<details>

```console
[efried@efried hive]$ oc version
Client Version: 4.7.2
Server Version: 4.7.0
Kubernetes Version: v1.20.0+bd9e442
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
[efried@efried hive]$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

I believe the issue is on the server, but...
<details>
	sigs.k8s.io/controller-runtime v0.9.3-0.20210709165254-650ea59f19cc
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ardaguclu** [comment]
It looks that this idempotency problem is fixed in latest releases(after adding ` "kubernetes.io/metadata.name": "lebug"` label as you mentioned).

All responses are legit;
```
$ oc create namespace lebug
namespace/lebug created
$ oc get namespace lebug -o json | jq -r .metadata.labels
{
  "kubernetes.io/metadata.name": "lebug"
}
$ oc patch namespace lebug -p '{"metadata": {"labels": {"EFRIED": null}}}'
namespace/lebug patched (no change)
$ oc get namespace lebug -o json | jq -r .metadata.labels
{
  "kubernetes.io/metadata.name": "lebug"
}
$ oc patch namespace lebug -p '{"metadata": {"labels": {"EFRIED": null}}}'
namespace/lebug patched (no change)
$ oc get namespace lebug -o json | jq -r .metadata.labels
{
  "kubernetes.io/metadata.name": "lebug"
}
$ oc patch namespace lebug -p '{"metadata": {"labels": {"something": "else"}}}'
namespace/lebug patched
$ oc get namespace lebug -o json | jq -r .metadata.labels
{
  "kubernetes.io/metadata.name": "lebug",
  "something": "else"
}
$ oc patch namespace lebug -p '{"metadata": {"labels": {"EFRIED": null}}}'
namespace/lebug patched (no change)
$ oc get namespace lebug -o json | jq -r .metadata.labels
{
  "kubernetes.io/metadata.name": "lebug",
  "something": "else"
}
```
Kubernetes Version

```
$ oc version
Client Version: 4.10.0-0.nightly-2022-01-19-150530
Server Version: 4.10.0-0.nightly-2022-01-19-150530
Kubernetes Version: v1.23.0+60f5a1c
```

**Comment by 2uasimojo** [comment]
@ardaguclu The bug happens when there are no other labels. Are you saying the "fix" was for kubernetes to always add a `kubernetes.io/metadata.name` label to the object?

**Comment by liggitt** [comment]
That was an incidental change specific to namespaces. I'd expect the issue still exists for other types

**Comment by ardaguclu** [comment]
> @ardaguclu The bug happens when there are no other labels. Are you saying the "fix" was for kubernetes to always add a `kubernetes.io/metadata.name` label to the object?

@2uasimojo @liggitt you are both right. This is incidental "fix" for namespaces. I'll look at others to find the actual problem.
