### ISSUE TITLE
Tests on sig-node-containerd#node-kubelet-containerd-eviction are failing

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#107063]
### Which jobs are failing?

containerd eviction tests

### Which tests are failing?

```
E2eNode Suite.[sig-node] LocalStorageEviction [Slow] [Serial] [Disruptive][NodeFeature:Eviction] when we run containers that should cause DiskPressure should eventually evict all of the correct podsE2eNode Suite.[sig-node] LocalStorageSoftEviction [Slow] [Serial] [Disruptive][NodeFeature:Eviction] when we run containers that should cause DiskPressure should eventually evict all of the correct pods
```

### Since when has it been failing?

12/10, seems like since ported from dockershim 

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-eviction

### Relevant SIG(s)

/sig node
/priority important-soon

**Comment by matthyx** [comment]
Funny, when looking at the logs, it seems node fixes itself regarding to disk pressure (from [this](blob:https://prow.k8s.io/0a55fdf0-4b36-4826-87b7-d767e22d75f6) log):
```
ï¿½[1mSTEPï¿½[0m: checking eviction ordering and ensuring important pods don't fail
Feb  2 10:55:22.805: INFO: Node has DiskPressure
Feb  2 10:55:22.843: INFO: Kubelet Metrics: []
Feb  2 10:55:22.862: INFO: imageFsInfo.CapacityBytes: 16684785664, imageFsInfo.AvailableBytes: 11803426816
Feb  2 10:55:22.862: INFO: rootFsInfo.CapacityBytes: 16684785664, rootFsInfo.AvailableBytes: 11803426816
Feb  2 10:55:22.862: INFO: Pod: container-disk-hog-pod
Feb  2 10:55:22.862: INFO: --- summary Container: container-disk-hog-container UsedBytes: 4683079680
Feb  2 10:55:22.862: INFO: Pod: innocent-pod
Feb  2 10:55:22.862: INFO: --- summary Container: innocent-container UsedBytes: 16384
Feb  2 10:55:22.864: INFO: fetching pod container-disk-hog-pod; phase= Running
Feb  2 10:55:22.864: INFO: fetching pod innocent-pod; phase= Running
ï¿½[1mSTEPï¿½[0m: checking eviction ordering and ensuring important pods don't fail
Feb  2 10:55:24.868: INFO: Node has DiskPressure
Feb  2 10:55:24.903: INFO: Kubelet Metrics: []
Feb  2 10:55:24.915: INFO: imageFsInfo.CapacityBytes: 16684785664, imageFsInfo.AvailableBytes: 11803426816
Feb  2 10:55:24.915: INFO: rootFsInfo.CapacityBytes: 16684785664, rootFsInfo.AvailableBytes: 11803426816
Feb  2 10:55:24.915: INFO: Pod: container-disk-hog-pod
Feb  2 10:55:24.915: INFO: --- summary Container: container-disk-hog-container UsedBytes: 4683079680
Feb  2 10:55:24.915: INFO: Pod: innocent-pod
Feb  2 10:55:24.915: INFO: --- summary Container: innocent-container UsedBytes: 16384
Feb  2 10:55:24.918: INFO: fetching pod container-disk-hog-pod; phase= Running
Feb  2 10:55:24.918: INFO: fetching pod innocent-pod; phase= Running
ï¿½[1mSTEPï¿½[0m: checking eviction ordering and ensuring important pods don't fail
Feb  2 10:55:26.923: INFO: Node has DiskPressure
Feb  2 10:55:26.966: INFO: Kubelet Metrics: []
Feb  2 10:55:26.978: INFO: imageFsInfo.CapacityBytes: 16684785664, imageFsInfo.AvailableBytes: 11803426816
Feb  2 10:55:26.978: INFO: rootFsInfo.CapacityBytes: 16684785664, rootFsInfo.AvailableBytes: 11803426816
Feb  2 10:55:26.978: INFO: Pod: container-disk-hog-pod
Feb  2 10:55:26.978: INFO: --- summary Container: container-disk-hog-container UsedBytes: 4683079680
Feb  2 10:55:26.978: INFO: Pod: innocent-pod
Feb  2 10:55:26.978: INFO: --- summary Container: innocent-container UsedBytes: 16384
Feb  2 10:55:26.980: INFO: fetching pod container-disk-hog-pod; phase= Running
Feb  2 10:55:26.980: INFO: fetching pod innocent-pod; phase= Running
ï¿½[1mSTEPï¿½[0m: checking eviction ordering and ensuring important pods don't fail
Feb  2 10:55:28.985: INFO: Node does NOT have DiskPressure
Feb  2 10:55:29.029: INFO: Kubelet Metrics: []
Feb  2 10:55:29.042: INFO: imageFsInfo.CapacityBytes: 16684785664, imageFsInfo.AvailableBytes: 11803426816
Feb  2 10:55:29.042: INFO: rootFsInfo.CapacityBytes: 16684785664, rootFsInfo.AvailableBytes: 11803426816
Feb  2 10:55:29.042: INFO: Pod: container-disk-hog-pod
Feb  2 10:55:29.042: INFO: --- summary Container: container-disk-hog-container UsedBytes: 4683079680
Feb  2 10:55:29.042: INFO: Pod: innocent-pod
Feb  2 10:55:29.042: INFO: --- summary Container: innocent-container UsedBytes: 16384
Feb  2 10:55:29.045: INFO: fetching pod container-disk-hog-pod; phase= Running
Feb  2 10:55:29.045: INFO: fetching pod innocent-pod; phase= Running
ï¿½[1mSTEPï¿½[0m: checking eviction ordering and ensuring important pods don't fail
Feb  2 10:55:31.049: INFO: Node does NOT have DiskPressure
Feb  2 10:55:31.087: INFO: Kubelet Metrics: []
Feb  2 10:55:31.099: INFO: imageFsInfo.CapacityBytes: 16684785664, imageFsInfo.AvailableBytes: 11803426816
Feb  2 10:55:31.099: INFO: rootFsInfo.CapacityBytes: 16684785664, rootFsInfo.AvailableBytes: 11803426816
Feb  2 10:55:31.099: INFO: Pod: innocent-pod
Feb  2 10:55:31.099: INFO: --- summary Container: innocent-container UsedBytes: 16384
Feb  2 10:55:31.099: INFO: Pod: container-disk-hog-pod
Feb  2 10:55:31.099: INFO: --- summary Container: container-disk-hog-container UsedBytes: 4683079680
Feb  2 10:55:31.101: INFO: fetching pod container-disk-hog-pod; phase= Running
Feb  2 10:55:31.101: INFO: fetching pod innocent-pod; phase= Running
```

Basically disk pressure is present from `Feb  2 10:54:47.778` to `Feb  2 10:55:26.923` and then no pressure until test times out waiting for `container-disk-hog-pod` to disappear...

**Comment by matthyx** [comment]
/assign @endocrimes 
Since you're planning on redesigning them.

**Comment by xmcqueen** [comment]
@matthyx yes I see the DiskPressure come and go too.

I've traced the failure in a [job](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-containerd-eviction/1529428981432979456#1:build-log.txt%3A103121) where 2 of 3 passed.  In the fail case the `innocent-pod` really does get evicted due to the expected node condition.  I don't see any disorder in the sequence of events to explain this with misbehaviour.  There is definitely an eviction event:

`W0525 13:51:33.394] [1mSTEP[0m: Waiting for node to have NodeCondition: DiskPressure`
`W0525 13:51:33.555] [1mSTEP[0m: Waiting for evictions to occur`
`W0525 13:51:33.558] [1mSTEP[0m: checking eviction ordering and ensuring important pods don't fail`
*the innocent-pod is still running at this time*
`W0525 13:51:34.347] May 25 12:17:17.041: INFO: --- summary Container: innocent-container inodeUsage: 7`
`W0525 13:51:34.348] [1mSTEP[0m: making sure pressure from test has surfaced before continuing`
`W0525 13:51:34.348] [1mSTEP[0m: Waiting for NodeCondition: DiskPressure to no longer exist on the node`
*its still running here*
`W0525 13:51:34.359] May 25 12:18:01.525: INFO: --- summary Container: innocent-container inodeUsage: 7`
`W0525 13:51:34.362] [1mSTEP[0m: checking for stable, pressure-free condition without unexpected pod failures`
*pod is gone*
`W0525 13:51:34.363] May 25 12:18:13.751: INFO: fetching pod innocent-pod; phase= Failed`

*event shows it was evicted*
`W0525 13:51:34.375] I0525 12:25:35.002047    1041 util.go:233] Event(v1.ObjectReference{Kind:"Pod", Namespace:"inode-eviction-test-5332", Name:"innocent-pod", UID:"8816bb1d-f1d5-4ad3-b7f4-f40352b8af05", APIVersion:"v1", ResourceVersion:"106", FieldPath:""}): type: 'Warning' reason: 'Evicted' The node was low on resource: inodes.`

Here's the [flaking job](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-containerd-eviction/1529428981432979456#1:build-log.txt%3A103121)

The comments in the [code](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/eviction_test.go#L515) say that is `It ensures that evictionPriority 0 pods are not evicted`.  It's probably an inaccurate comment.  The [kubelet config ](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/eviction_test.go#L85) looks like its using **hard eviction**, so I don't know how this test can expect to keep `innocent-pod` safe.  I don't know if hard [eviction excludes priority](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#pod-selection-for-kubelet-eviction) 0, it think it just kills them last.

**Comment by bobbypage** [comment]
Did a bit of debugging of eviction tests focusing on Pid Priority test. 

There's a few issues, starting with https://github.com/kubernetes/test-infra/pull/28462

**Comment by bobbypage** [comment]
Focusing on `PriorityPidEvictionOrdering` tests -

Currently failing with 

```
{ failed [FAILED] Timed out after 120.000s.
Expected
    <*errors.errorString | 0xc00110efb0>: {
        s: "NodeCondition: PIDPressure not encountered",
    }
to be nil
In [It] at: test/e2e_node/eviction_test.go:571 @ 01/19/23 19:39:27.204
}
```

I think this is because the system has a low pids.max default (addressed in https://github.com/kubernetes/test-infra/pull/28462), so the fork bomb pod in the test is being killed too early, before the eviction manager can see the high pid pressure.

**Comment by bobbypage** [comment]
The next issue with Pid eviction tests is that process stats are not currently returned correctly (filed https://github.com/kubernetes/kubernetes/issues/115215) for it.

**Comment by pacoxu** [comment]
This test still failed in https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-eviction.

**Comment by mmiranda96** [comment]
/unassign @endocrimes 

Hi Danielle, I'm unassigning you from this issue so someone else can take a look, feel free to assign it back if you plan to work on it.

**Comment by kannon92** [comment]
/assign

I'm playing around with these tests now.

**Comment by pacoxu** [comment]
https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-eviction
- [sig-node] LocalStorageSoftEviction [Slow] [Serial] [Disruptive] [NodeFeature:Eviction] when we run containers that should cause DiskPressure should eventually evict all of the correct pods 
- [sig-node] LocalStorageEviction [Slow] [Serial] [Disruptive] [NodeFeature:Eviction] when we run containers that should cause DiskPressure should eventually evict all of the correct pods

Both tests are failing in recent runs.

**Comment by kannon92** [comment]
We made progress on this. 

https://github.com/google/cadvisor/pull/3497 should help with PID stats returing 0 which causes flakes for PIDs.

**Comment by HirazawaUi** [comment]
`pull-kubernetes-cos-cgroupv2-containerd-node-e2e-eviction` has been run eleven times since March 7, and different test cases failed each time.
ref: https://testgrid.k8s.io/sig-node-presubmits#pr-cos-cgroupv2-containerd-node-e2e-eviction
