### ISSUE TITLE
[Failing test] capg-conformance-main-ci-artifacts

### ISSUE THREAD

**Issue by Nivedita-coder** [kubernetes/kubernetes#110462]
### Which jobs are failing?
release-master-informing

- capg-conformance-main-ci-artifacts

### Which tests are failing?

Kubernetes e2e suite.BeforeSuite

### Since when has it been failing?

05-25 06:37 IST

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-main-ci-artifacts

### Reason for failure (if possible)

`Failure test/e2e/e2e.go:77
Error waiting for all pods to be running and ready: 3 / 13 pods in namespace kube-system are NOT in RUNNING and READY state in 10m0s`

### Relevant SIG(s)

/sig network
/sig node
cc @kubernetes/ci-signal

**Comment by aojea** [comment]
/remove sig-network
/remove sig-node
/unassign

This seems a deployment problem ... on calico to be precise

```
Jun  9 15:35:58.710: INFO: ==== node wait: 1 out of 3 nodes are ready, max notReady allowed 0.  Need 2 more before starting.
Jun  9 15:36:28.749: INFO: Waiting up to 10m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready
Jun  9 15:36:28.909: INFO: The status of Pod calico-node-gfxkm is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
Jun  9 15:36:28.909: INFO: The status of Pod calico-node-jbh6d is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
Jun  9 15:36:28.909: INFO: The status of Pod calico-node-rg4nj is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
Jun  9 15:36:28.909: INFO: 10 / 13 pods in namespace 'kube-system' are running and ready (0 seconds elapsed)
Jun  9 15:36:28.909: INFO: expected 3 pod replicas in namespace 'kube-system', 3 are Running and Ready.

```

first point of contact for initial triage should be the job/sig owners ... this job also seems to be failing for a long time

/sig cluster-lifecycle
sig-cluster-lifecycle-cluster-api-alerts

**Comment by dims** [comment]
cc @cpanato @richardcase

**Comment by cpanato** [comment]
will take a look
/assign

**Comment by aojea** [comment]
> will take a look /assign

Check the Calico version, there was a similar report that was fixed bumping the version.

As a side not, I'm seeing a lot of problems related to 

> No Secret by default for service account tokens
https://itnext.io/big-change-in-k8s-1-24-about-serviceaccounts-and-their-secrets-4b909a4af4e0

Lots of projects/test/code were assuming the secret was created and is causing a lot of noise in different CIs

**Comment by RinkiyaKeDad** [comment]
Hey @cpanato thanks for the PR! The test still shows [failing](https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-main-ci-artifacts) in the [master-informing dashboard](https://testgrid.k8s.io/sig-release-master-informing) - will it take some time for the changes you made in the PR to reflect?

**Comment by cpanato** [comment]
> Hey @cpanato thanks for the PR! The test still shows [failing](https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-main-ci-artifacts) in the [master-informing dashboard](https://testgrid.k8s.io/sig-release-master-informing) - will it take some time for the changes you made in the PR to reflect?

hello! those are not failures, they are flakys :/ afaik

**Comment by cpanato** [comment]
checking that

**Comment by cpanato** [comment]
the capg conformance failed but now have flakys only
