### ISSUE TITLE
[Failing test] periodic-conformance-main-k8s-main

### ISSUE THREAD

**Issue by Nivedita-coder** [kubernetes/kubernetes#113449]
### Which jobs are failing?

master-informing

- periodic-conformance-main-k8s-main

### Which tests are failing?

- capa-e2e-conformance.AfterSuite
- capa-e2e-conformance.BeforeSuite

### Since when has it been failing?

10-25 22:18 IST

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#periodic-conformance-main-k8s-main

### Reason for failure (if possible)

```
{ Failure /home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/suites/conformance/conformance_suite_test.go:46
Failed to read file "aws" / "/home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/data/infrastructure-aws/withclusterclass/generated/cluster-template-topology.yaml"
Unexpected error:
    <*fs.PathError | 0xc000ada690>: {
        Op: "open",
        Path: "/home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/data/infrastructure-aws/withclusterclass/generated/cluster-template-topology.yaml",
        Err: <syscall.Errno>0x2,
    }
    open /home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/data/infrastructure-aws/withclusterclass/generated/cluster-template-topology.yaml: no such file or directory
occurred
/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.2.2/framework/clusterctl/repository.go:101}
```

### Relevant SIG(s)

/sig cloud-provider
/area provider/aws
cc @kubernetes/ci-signal

**Comment by Ankitasw** [comment]
This is already fixed via https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3800

**Comment by dims** [comment]
thanks @Ankitasw !

**Comment by mehabhalodiya** [comment]
Reopening the issue as this is still failing, please have a look at the [testgrid](https://testgrid.k8s.io/sig-release-master-informing#periodic-conformance-main-k8s-main). Thank you!

/reopen

**Comment by Ankitasw** [comment]
The same set of tests are passing in the other pipeline https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws#periodic-conformance-main
Can this be checked from test-infra side as it seems issue on the prow side?

**Comment by Ankitasw** [comment]
@mehabhalodiya @dims getting below errors in kubelet. Do we need to update containerd versions

> run.go:74] "command failed" err="failed to run Kubelet: validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"

**Comment by aojea** [comment]
sounds like an old version of containerd running there, v1 should be the default

**Comment by bharitwal** [comment]
@aojea @Ankitasw can you please confirm if this is a blocker for the 1.26.0-rc.0 release for tomorrow?

**Comment by Ankitasw** [comment]
The same tests are running fine in other environments, and locally as well, so this should not be a blocker. But we are not able to find out the root cause.

**Comment by bharitwal** [comment]
> The same tests are running fine in other environments, and locally as well, so this should not be a blocker. But we are not able to find out the root cause.

Thanks for confirming.

**Comment by Ankitasw** [comment]
We are facing [similar](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/625) issue while running conformance tests for CAPA. 
cc @richardcase

**Comment by leonardpahlke** [comment]
> sounds like an old version of containerd running there, v1 should be the default

have we followed up on this thought?

**Comment by Ankitasw** [comment]
@leonardpahlke missed the comment, will check on that and get back.

**Comment by Ankitasw** [comment]
The containerd version used is 1.5.11, so that should not be a problem.

**Comment by Ankitasw** [comment]
looks like #image-builder is still using containerd_version as v1.6.2 as default version. So we have all the existing AMIs with this version due to which our conformance tests in k8s main branch is failing. We would focus on fixing the generation of AMIs from CAPA side, and post that we would be able to handle this by generating new AMIs with containerd version >= 1.6.11. Till then, this would be in blocked state.

**Comment by leonardpahlke** [comment]
Ok, thanks. How long will it take approx to upgrade versions?

**Comment by Ankitasw** [comment]
the version upgrade is currently blocked by [PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3829). once this PR is in, we would be generating AMIs within a day or two, and then raise PR with upgraded version in conformance test.

**Comment by leonardpahlke** [comment]
Great, Thank you @Ankitasw!
