### ISSUE TITLE
Empty string in env of container always causes kubectl apply command show configured.

### ISSUE THREAD

**Issue by libinglong** [kubernetes/kubernetes#114777]
### What happened?

kubectl apply -f deploy.yaml always show configured even if there is no change.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerd
  template:
    metadata:
      labels:
        app: dockerd
    spec:
      containers:
        - name: dockerd
          image: harbor.intra.ke.com/appcenter/proxy/docker:20.10.21-dind
          imagePullPolicy: IfNotPresent
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
```

### What did you expect to happen?

deployment.apps/dockerd unchanged

### How can we reproduce it (as minimally and precisely as possible)?

kubectl apply -f the yaml > two times

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:19:24Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:12:04Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by libinglong** [comment]
> @libinglong: There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
> 
> * `/sig <group-name>`
> * `/wg <group-name>`
> * `/committee <group-name>`
> 
> Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.

/sig cli

**Comment by ardaguclu** [comment]
As far as I can recall this problem was fixed in newer versions. Could you please try with latest kubectl?

**Comment by pacoxu** [comment]
> As far as I can recall this problem was fixed in newer versions. Could you please try with latest kubectl?

Just tried in v1.26.0 env, and it still exists.


The request body is like `"env":[{"name":"DOCKER_TLS_CERTDIR", "value": ""}`
```
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
```
The response body is like `"env":[{"name":"DOCKER_TLS_CERTDIR"}`
```
          env:
            - name: DOCKER_TLS_CERTDIR
```

**Comment by ardaguclu** [comment]
`env` field in deployment spec is set as omit if empty https://github.com/kubernetes/kubernetes/blob/57b9656e2ba84f533006fb0536920b1777411d62/staging/src/k8s.io/api/core/v1/types.go#L2027. That's why, it ignores this value as @pacoxu said above ^. 

On client side, strategic merge detects this as difference and sends this patch to apiserver. Just because of this reason, it shows `configured`. Especially considering the move towards server side usage, I think we can say this works as expected.

What do you think @apelisse?

**Comment by apelisse** [comment]
We don't have a good way to do the same thing server-side so yeah, we're probably not going to fix that.

**Comment by apelisse** [comment]
This is more or less working as intended. Clients don't always know how the change is going to be applied by the apiserver, and if it's actually going to resolve to a change. With client-side apply, we could totally check if the resourceVersion has changed between the object we got before applying and the returned object. Is it worth the effort? This "configured/unchanged" shouldn't be construed as an API.
