### ISSUE TITLE
 [Serial] [Disruptive]  Can schedule a pod that requires a device

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#115381]
### Which jobs are failing?

in https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/105271/pull-kubernetes-node-swap-ubuntu-serial/1619275537652387840/build-log.txt

### Which tests are failing?

W0128 10:46:06.683]   [38;5;9m[FAIL][0m [0m[sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] [38;5;9m[1mDevicePlugin [Serial] [Disruptive] [BeforeEach] [0mCan schedule a pod that requires a device[0m

```
W0128 10:46:06.682]   [38;5;9m[FAILED] should have no pod resources
W0128 10:46:06.682]   Expected
W0128 10:46:06.682]       <[]*v1alpha1.PodResources | len:1, cap:1>: 
W0128 10:46:06.682]           - containers:
W0128 10:46:06.682]             - name: burstable2886f5b2-7326-4825-ad46-e48d48e0a161
W0128 10:46:06.682]             name: burstable2886f5b2-7326-4825-ad46-e48d48e0a161
W0128 10:46:06.682]             namespace: kubelet-container-manager-268
W0128 10:46:06.682]   to be empty[0m
```

The pod was left by the test case `burstable container's oom-score-adj should be between`
https://github.com/kubernetes/kubernetes/blob/8e642d3d0deab20a153c740b7af727a10aabf88b/test/e2e_node/container_manager_test.go#L220

```
<system-err>> Enter [BeforeEach] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] - set up framework | framework.go:188 @ 01/28/23 10:44:44.623 STEP: Creating a kubernetes client - test/e2e/framework/framework.go:208 @ 01/28/23 10:44:44.623 STEP: Building a namespace api object, basename device-plugin-errors - test/e2e/framework/framework.go:247 @ 01/28/23 10:44:44.623 Jan 28 10:44:44.629: INFO: Skipping waiting for service account < Exit [BeforeEach] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] - set up framework | framework.go:188 @ 01/28/23 10:44:44.629 (6ms) > Enter [BeforeEach] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] - test/e2e/framework/metrics/init/init.go:33 @ 01/28/23 10:44:44.629 < Exit [BeforeEach] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] - test/e2e/framework/metrics/init/init.go:33 @ 01/28/23 10:44:44.629 (0s) > Enter [BeforeEach] DevicePlugin [Serial] [Disruptive] - test/e2e_node/device_plugin_test.go:100 @ 01/28/23 10:44:44.629 STEP: Wait for node to be ready - test/e2e_node/device_plugin_test.go:101 @ 01/28/23 10:44:44.629 [FAILED] should have no pod resources Expected <[]*v1alpha1.PodResources | len:1, cap:1>: - containers: - name: burstable2886f5b2-7326-4825-ad46-e48d48e0a161 name: burstable2886f5b2-7326-4825-ad46-e48d48e0a161 namespace: kubelet-container-manager-268 to be empty In [BeforeEach] at: test/e2e_node/device_plugin_test.go:117 @ 01/28/23 10:44:44.637 < Exit [BeforeEach] DevicePlugin [Serial] [Disruptive] - test/e2e_node/device_plugin_test.go:100 @ 01/28/23 10:44:44.637 (8ms) > Enter [AfterEach] DevicePlugin [Serial] [Disruptive] - test/e2e_node/device_plugin_test.go:158 @ 01/28/23 10:44:44.637 STEP: Deleting the device plugin pod - test/e2e_node/device_plugin_test.go:159 @ 01/28/23 10:44:44.637 Jan 28 10:44:44.639: INFO: Waiting for pod sample-device-plugin to disappear Jan 28 10:44:44.641: INFO: Pod sample-device-plugin no longer exists STEP: Deleting any Pods created by the test - test/e2e_node/device_plugin_test.go:162 @ 01/28/23 10:44:44.641 Jan 28 10:44:44.677: INFO: Get running kubelet with systemctl: UNIT LOAD ACTIVE SUB DESCRIPTION kubelet-20230128T101655.service loaded active running /tmp/node-e2e-20230128T101655/kubelet --kubeconfig /tmp/node-e2e-20230128T101655/kubeconfig --root-dir /var/lib/kubelet --v 4 --feature-gates NodeSwap=true --hostname-override n1-standard-2-ubuntu-gke-2204-1-24-v20230119-43fc6bf7 --container-runtime-endpoint unix:///run/containerd/containerd.sock --config /tmp/node-e2e-20230128T101655/kubelet-config --kernel-memcg-notification=true --feature-gates=DisableKubeletCloudCredentialProviders=true,KubeletCredentialProviders=true --image-credential-provider-config=/tmp/node-e2e-20230128T101655/credential-provider.yaml --image-credential-provider-bin-dir=/tmp/node-e2e-20230128T101655 --cgroups-per-qos=true --cgroup-root=/ --fail-swap-on=false --runtime-cgroups=/system.slice/containerd.service LOAD = Reflects whether the unit definition was properly loaded. ACTIVE = The high-level unit activation state, i.e. generalization of SUB. SUB = The low-level unit activation state, values depend on unit type. 1 loaded units listed. , kubelet-20230128T101655 STEP: Waiting for devices to become unavailable on the local node - test/e2e_node/device_plugin_test.go:176 @ 01/28/23 10:44:44.8 Jan 28 10:44:44.803: INFO: node "n1-standard-2-ubuntu-gke-2204-1-24-v20230119-43fc6bf7" ready=true schedulable=true STEP: devices now unavailable on the local node - test/e2e_node/device_plugin_test.go:182 @ 01/28/23 10:44:44.803 < Exit [AfterEach] DevicePlugin [Serial] [Disruptive] - test/e2e_node/device_plugin_test.go:158 @ 01/28/23 10:44:44.803 (166ms) > Enter [AfterEach] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] - test/e2e/framework/node/init/init.go:33 @ 01/28/23 10:44:44.803 Jan 28 10:44:44.803: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready < Exit [AfterEach] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] - test/e2e/framework/node/init/init.go:33 @ 01/28/23 10:44:44.81 (7ms) > Enter [DeferCleanup (Each)] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] - test/e2e/framework/metrics/init/init.go:35 @ 01/28/23 10:44:44.81 < Exit [DeferCleanup (Each)] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] - test/e2e/framework/metrics/init/init.go:35 @ 01/28/23 10:44:44.81 (0s) > Enter [DeferCleanup (Each)] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] - dump namespaces | framework.go:206 @ 01/28/23 10:44:44.81 STEP: dump namespace information after failure - test/e2e/framework/framework.go:284 @ 01/28/23 10:44:44.81 STEP: Collecting events from namespace "device-plugin-errors-7882". - test/e2e/framework/debug/dump.go:42 @ 01/28/23 10:44:44.81 STEP: Found 0 events. - test/e2e/framework/debug/dump.go:46 @ 01/28/23 10:44:44.812 Jan 28 10:44:44.815: INFO: POD NODE PHASE GRACE CONDITIONS Jan 28 10:44:44.815: INFO: Jan 28 10:44:44.818: INFO: Logging node info for node n1-standard-2-ubuntu-gke-2204-1-24-v20230119-43fc6bf7 Jan 28 10:44:44.821: INFO: Node Info: &Node{ObjectMeta:{n1-standard-2-ubuntu-gke-2204-1-24-v20230119-43fc6bf7 2b303776-2b52-45b9-9f38-d1e14cd7d874 2055 0 2023-01-28 10:18:14 +0000 UTC <nil> <nil> map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:n1-standard-2-ubuntu-gke-2204-1-24-v20230119-43fc6bf7 kubernetes.io/os:linux] map[volumes.kubernetes.io/controller-managed-attach-detach:true] [] [] [{kubelet Update v1 2023-01-28 10:18:14 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:volumes.kubernetes.io/controller-managed-attach-detach":{}},"f:labels":{".":{},"f:beta.kubernetes.io/arch":{},"f:beta.kubernetes.io/os":{},"f:kubernetes.io/arch":{},"f:kubernetes.io/hostname":{},"f:kubernetes.io/os":{}}}} } {kubelet Update v1 2023-01-28 10:44:39 +0000 UTC FieldsV1 {"f:status":{"f:allocatable":{"f:cpu":{},"f:ephemeral-storage":{},"f:example.com/resource":{},"f:hugepages-2Mi":{},"f:memory":{}},"f:capacity":{"f:example.com/resource":{},"f:hugepages-2Mi":{}},"f:conditions":{"k:{\"type\":\"DiskPressure\"}":{"f:lastHeartbeatTime":{}},"k:{\"type\":\"MemoryPressure\"}":{"f:lastHeartbeatTime":{}},"k:{\"type\":\"PIDPressure\"}":{"f:lastHeartbeatTime":{}},"k:{\"type\":\"Ready\"}":{"f:lastHeartbeatTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{}}},"f:images":{}}} status}]},Spec:NodeSpec{PodCIDR:,DoNotUseExternalID:,ProviderID:,Unschedulable:false,Taints:[]Taint{},ConfigSource:nil,PodCIDRs:[],},Status:NodeStatus{Capacity:ResourceList{cpu: {{2 0} {<nil>} 2 DecimalSI},ephemeral-storage: {{20617822208 0} {<nil>} BinarySI},example.com/resource: {{0 0} {<nil>} 0 DecimalSI},hugepages-1Gi: {{0 0} {<nil>} 0 DecimalSI},hugepages-2Mi: {{0 0} {<nil>} 0 DecimalSI},memory: {{7804325888 0} {<nil>} 7621412Ki BinarySI},pods: {{110 0} {<nil>} 110 DecimalSI},swap: {{1073737728 0} {<nil>} 1048572Ki BinarySI},},Allocatable:ResourceList{cpu: {{2 0} {<nil>} 2 DecimalSI},ephemeral-storage: {{18556039957 0} {<nil>} 18556039957 DecimalSI},example.com/resource: {{0 0} {<nil>} 0 DecimalSI},hugepages-1Gi: {{0 0} {<nil>} 0 DecimalSI},hugepages-2Mi: {{0 0} {<nil>} 0 DecimalSI},memory: {{7542181888 0} {<nil>} 7365412Ki BinarySI},pods: {{110 0} {<nil>} 110 DecimalSI},swap: {{1073737728 0} {<nil>} 1048572Ki BinarySI},},Phase:,Conditions:[]NodeCondition{NodeCondition{Type:MemoryPressure,Status:False,LastHeartbeatTime:2023-01-28 10:44:39 +0000 UTC,LastTransitionTime:2023-01-28 10:18:14 +0000 UTC,Reason:KubeletHasSufficientMemory,Message:kubelet has sufficient memory available,},NodeCondition{Type:DiskPressure,Status:False,LastHeartbeatTime:2023-01-28 10:44:39 +0000 UTC,LastTransitionTime:2023-01-28 10:18:14 +0000 UTC,Reason:KubeletHasNoDiskPressure,Message:kubelet has no disk pressure,},NodeCondition{Type:PIDPressure,Status:False,LastHeartbeatTime:2023-01-28 10:44:39 +0000 UTC,LastTransitionTime:2023-01-28 10:18:14 +0000 UTC,Reason:KubeletHasSufficientPID,Message:kubelet has sufficient PID available,},NodeCondition{Type:Ready,Status:True,LastHeartbeatTime:2023-01-28 10:44:39 +0000 UTC,LastTransitionTime:2023-01-28 10:44:34 +0000 UTC,Reason:KubeletReady,Message:kubelet is posting ready status. AppArmor enabled,},},Addresses:[]NodeAddress{NodeAddress{Type:InternalIP,Address:10.138.0.56,},NodeAddress{Type:Hostname,Address:n1-standard-2-ubuntu-gke-2204-1-24-v20230119-43fc6bf7,},},DaemonEndpoints:NodeDaemonEndpoints{KubeletEndpoint:DaemonEndpoint{Port:10250,},},NodeInfo:NodeSystemInfo{MachineID:d598146f87b7679e73801c5f9ab6bcc9,SystemUUID:d598146f-87b7-679e-7380-1c5f9ab6bcc9,BootID:64ec3f79-2eb9-41a4-a41b-36e701ad36fb,KernelVersion:5.15.0-1024-gke,OSImage:Ubuntu 22.04.1 LTS,ContainerRuntimeVersion:containerd://1.6.12,KubeletVersion:v1.27.0-alpha.1.74+7fd8a1ca629765,KubeProxyVersion:v1.27.0-alpha.1.74+7fd8a1ca629765,OperatingSystem:linux,Architecture:amd64,},Images:[]ContainerImage{ContainerImage{Names:[registry.k8s.io/e2e-test-images/perl@sha256:c613344cdd31c5055961b078f831ef9d9199fc9111efe6e81bea3f00d78bd979 registry.k8s.io/e2e-test-images/perl:5.26],SizeBytes:325397679,},ContainerImage{Names:[registry.k8s.io/e2e-test-images/node-perf/tf-wide-deep@sha256:91ab3b5ee22441c99370944e2e2cb32670db62db433611b4e3780bdee6a8e5a1 registry.k8s.io/e2e-test-images/node-perf/tf-wide-deep:1.3],SizeBytes:213443508,},ContainerImage{Names:[registry.k8s.io/e2e-test-images/volume/gluster@sha256:033a12fe65438751690b519cebd4135a3485771086bcf437212b7b886bb7956c registry.k8s.io/e2e-test-images/volume/gluster:1.3],SizeBytes:115217395,},ContainerImage{Names:[registry.k8s.io/etcd@sha256:dd75ec974b0a2a6f6bb47001ba09207976e625db898d1b16735528c009cb171c registry.k8s.io/etcd:3.5.6-0],SizeBytes:102542580,},ContainerImage{Names:[registry.k8s.io/e2e-test-images/volume/nfs@sha256:3bda73f2428522b0e342af80a0b9679e8594c2126f2b3cca39ed787589741b9e registry.k8s.io/e2e-test-images/volume/nfs:1.3],SizeBytes:95836203,},ContainerImage{Names:[quay.io/kubevirt/device-plugin-kvm@sha256:b44bc0fd6ff8987091bbc7ec630e5ee6683be40d151b4e6635e24afb5807b21a quay.io/kubevirt/device-plugin-kvm:latest],SizeBytes:87743847,},ContainerImage{Names:[docker.io/library/debian@sha256:534da5794e770279c889daa891f46f5a530b0c5de8bfbc5e40394a0164d9fa87 docker.io/library/debian:latest],SizeBytes:55029052,},ContainerImage{Names:[registry.k8s.io/e2e-test-images/agnhost@sha256:16bbf38c463a4223d8cfe4da12bc61010b082a79b4bb003e2d3ba3ece5dd5f9e registry.k8s.io/e2e-test-images/agnhost:2.43],SizeBytes:51706353,},ContainerImage{Names:[registry.k8s.io/node-problem-detector/node-problem-detector@sha256:0ce71ef6d759425d22b10e65b439749fe5d13377a188e2fc060b731cdb4e6901 registry.k8s.io/node-problem-detector/node-problem-detector:v0.8.7],SizeBytes:47786458,},ContainerImage{Names:[registry.k8s.io/e2e-test-images/httpd@sha256:148b022f5c5da426fc2f3c14b5c0867e58ef05961510c84749ac1fddcb0fef22 registry.k8s.io/e2e-test-images/httpd:2.4.38-4],SizeBytes:40764257,},ContainerImage{Names:[registry.k8s.io/e2e-test-images/node-perf/npb-is@sha256:8285539c79625b192a5e33fc3d21edc1a7776fb9afe15fae3b5037a7a8020839 registry.k8s.io/e2e-test-images/node-perf/npb-is:1.2],SizeBytes:39706325,},ContainerImage{Names:[registry.k8s.io/e2e-test-images/node-perf/npb-ep@sha256:90b5cfc5451428aad4dd6af9960640f2506804d35aa05e83c11bf0a46ac318c8 registry.k8s.io/e2e-test-images/node-perf/npb-ep:1.2],SizeBytes:39705373,},ContainerImage{Names:[gcr.io/cadvisor/cadvisor@sha256:89e6137f068ded2e9a3a012ce71260b9afc57a19305842aa1074239841a539a7 gcr.io/cadvisor/cadvisor:v0.43.0],SizeBytes:31056802,},ContainerImage{Names:[registry.k8s.io/e2e-test-images/nonroot@sha256:ee9f50b3c64b174d296d91ca9f69a914ac30e59095dfb462b2b518ad28a63655 registry.k8s.io/e2e-test-images/nonroot:1.4],SizeBytes:17747885,},ContainerImage{Names:[docker.io/nfvpe/sriov-device-plugin@sha256:518499ed631ff84b43153b8f7624c1aaacb75a721038857509fe690abdf62ddb docker.io/nfvpe/sriov-device-plugin:v3.1],SizeBytes:12638340,},ContainerImage{Names:[registry.k8s.io/e2e-test-images/sample-device-plugin@sha256:e84f6ca27c51ddedf812637dd2bcf771ad69fdca1173e5690c372370d0f93c40 registry.k8s.io/e2e-test-images/sample-device-plugin:1.3],SizeBytes:12410396,},ContainerImage{Names:[registry.k8s.io/e2e-test-images/nginx@sha256:5c99cf6a02adda929b10321dbf4ecfa00d87be9ba4fb456006237d530ab4baa1 registry.k8s.io/e2e-test-images/nginx:1.14-4],SizeBytes:6978614,},ContainerImage{Names:[registry.k8s.io/nvidia-gpu-device-plugin@sha256:4b036e8844920336fa48f36edeb7d4398f426d6a934ba022848deed2edbf09aa],SizeBytes:6819465,},ContainerImage{Names:[registry.k8s.io/e2e-test-images/ipc-utils@sha256:647d092bada3b46c449d875adf31d71c1dd29c244e9cca6a04fddf9d6bcac136 registry.k8s.io/e2e-test-images/ipc-utils:1.3],SizeBytes:4013020,},ContainerImage{Names:[registry.k8s.io/e2e-test-images/nonewprivs@sha256:8ac1264691820febacf3aea5d152cbde6d10685731ec14966a9401c6f47a68ac registry.k8s.io/e2e-test-images/nonewprivs:1.3],SizeBytes:3263463,},ContainerImage{Names:[registry.k8s.io/stress:v1],SizeBytes:1558004,},ContainerImage{Names:[registry.k8s.io/e2e-test-images/busybox@sha256:2e0f836850e09b8b7cc937681d6194537a09fbd5f6b9e08f4d646a85128e8937 registry.k8s.io/e2e-test-images/busybox:1.29-4],SizeBytes:731990,},ContainerImage{Names:[registry.k8s.io/busybox@sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff],SizeBytes:676941,},ContainerImage{Names:[registry.k8s.io/pause@sha256:7031c1b283388d2c2e09b57badb803c05ebed362dc88d84b480cc47f72a21097 registry.k8s.io/pause:3.9],SizeBytes:321520,},ContainerImage{Names:[registry.k8s.io/pause@sha256:3d380ca8864549e74af4b29c10f9cb0956236dfb01c40ca076fb6c37253234db registry.k8s.io/pause:3.6],SizeBytes:301773,},ContainerImage{Names:[docker.io/library/gke-nvidia-installer:fixed],SizeBytes:11600,},},VolumesInUse:[],VolumesAttached:[]AttachedVolume{},Config:nil,},} Jan 28 10:44:44.821: INFO: Logging kubelet events for node n1-standard-2-ubuntu-gke-2204-1-24-v20230119-43fc6bf7 Jan 28 10:44:44.823: INFO: Logging pods the kubelet thinks is on node n1-standard-2-ubuntu-gke-2204-1-24-v20230119-43fc6bf7 Jan 28 10:44:44.828: INFO: Unable to retrieve kubelet pods for node n1-standard-2-ubuntu-gke-2204-1-24-v20230119-43fc6bf7: error trying to reach service: dial tcp 10.138.0.56:10250: connect: connection refused END STEP: dump namespace information after failure - test/e2e/framework/framework.go:284 @ 01/28/23 10:44:44.828 (18ms) < Exit [DeferCleanup (Each)] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] - dump namespaces | framework.go:206 @ 01/28/23 10:44:44.828 (18ms) > Enter [DeferCleanup (Each)] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] - tear down framework | framework.go:203 @ 01/28/23 10:44:44.828 STEP: Destroying namespace "device-plugin-errors-7882" for this suite. - test/e2e/framework/framework.go:347 @ 01/28/23 10:44:44.828 < Exit [DeferCleanup (Each)] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] - tear down framework | framework.go:203 @ 01/28/23 10:44:44.832 (3ms) </system-err>
```

### Since when has it been failing?

not sure

### Testgrid link

https://prow.k8s.io/?job=pull-kubernetes-node-swap-ubuntu-serial

### Relevant SIG(s)

/sig node

**Comment by pacoxu** [comment]
/cc @adisky  @SergeyKanzhelev @249043822 
for https://github.com/kubernetes/kubernetes/pull/114981 (revert of https://github.com/kubernetes/kubernetes/pull/108912)

**Comment by adisky** [comment]
@pacoxu these tests started failing after #114981 got merged?

**Comment by pacoxu** [comment]
The test passed after rebasing with latest code.

It should be fixed. Thnaks.

**Comment by pacoxu** [comment]
```
W0130 10:23:30.693]   [38;5;9m[FAILED] should have no pod resources
W0130 10:23:30.694]   Expected
W0130 10:23:30.694]       <[]*v1alpha1.PodResources | len:2, cap:2>: 
W0130 10:23:30.694]           - containers:
W0130 10:23:30.694]             - name: container161e6adc-6078-4009-b275-ee75c8f24211
W0130 10:23:30.694]             name: podc0e9efa5-6e4e-457f-a093-d02f236b1548
W0130 10:23:30.694]             namespace: pids-limit-test-9326
W0130 10:23:30.694]           - containers:
W0130 10:23:30.694]             - name: containerdfae54bc-644f-4872-92ec-936667386e56
W0130 10:23:30.694]             name: pod535238d8-9662-4455-8c9a-3de364af83b1
W0130 10:23:30.694]             namespace: pids-limit-test-9326
W0130 10:23:30.694]   to be empty[0m
```
It failed for some other remaining pods again.

**Comment by bobbypage** [comment]
It is still an issue, see https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial

It seems that some pods are sometimes not being cleaned up after the test finishes...

**Comment by bobbypage** [comment]
Taking a look at https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv2-containerd-node-e2e-serial/1620524893999206400

Test fails with 

```
{ failed [FAILED] should have no pod resources
Expected
    <[]*v1alpha1.PodResources | len:1, cap:1>: 
        - containers:
          - name: test-admit-pod
          name: test-admit-pod
          namespace: localstorage-quota-monitoring-test-4207
to be empty
In [BeforeEach] at: test/e2e_node/device_plugin_test.go:117 @ 01/31/23 21:16:10.999

There were additional failures detected after the initial failure. These are visible in the timeline
}
```

On kubelet side it was deleted here:

```
27990:I0131 21:16:17.332674  126660 kubelet.go:2051] "Pod has been deleted and must be killed" pod="localstorage-quota-monitoring-test-4207/test-admit-pod" podUID=7d2db893-8afb-4092-b872-8b26fe1ec384
27991:I0131 21:16:17.332699  126660 pod_workers.go:625] "Pod is finished processing, no further updates" pod="localstorage-quota-monitoring-test-4207/test-admit-pod" podUID=7d2db893-8afb-4092-b872-8b26fe1ec384
27992:I0131 21:16:17.333026  126660 status_manager.go:757] "Pod fully terminated and removed from etcd" pod="localstorage-quota-monitoring-test-4207/test-admit-pod"
27997:I0131 21:16:17.339866  126660 status_manager.go:690] "Pod does not exist on the server" podUID=7d2db893-8afb-4092-b872-8b26fe1ec384 pod="localstorage-quota-monitoring-test-4207/test-admit-pod"
```

The logs show that API server recorded a delete of the pod at  `21:16:17`

```
7574:  I0131 21:16:17.332688    1590 httplog.go:132] "HTTP" verb="DELETE" URI="/api/v1/namespaces/localstorage-quota-monitoring-test-4207/pods/test-admit-pod" latency="2.777989ms" userAgent="kubelet/v1.27.0 (linux/amd64) kubernetes/c4ebbee" audit-ID="7c19efd7-b32d-4968-8cee-9a2142a5c391" srcIP="127.0.0.1:44980" apf_pl="exempt" apf_fs="exempt" apf_execution_time="2.6279ms" resp=200
```

but the next test was already running at `21:16:10.999`, so it seems like the test that created `localstorage-quota-monitoring-test-4207` (test/e2e_node/eviction_test.go), completed before it deleted all the resources created in the test...

**Comment by bobbypage** [comment]
See related slack thread - https://kubernetes.slack.com/archives/C09QZ4DQB/p1675206504013289

Namespace deletion is async by design and the test needs to account for this. For this case in particular, since `device_plugin_test.go` requires no pods to be left over from other tests, we can adjust the BeforeBegin to wait and poll for a bit while all the resources are cleaned up.
