### ISSUE TITLE
latest files are not being updated properly

### ISSUE THREAD

**Issue by pawbana** [kubernetes/kubernetes#117115]
### What happened?

Files storing latest versions for minors are not updated since `rc.0` infix was added to the version string. Example https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-build-1-26/1643305100510236672/build-log.txt

```
level=info msg="Testing v1.26.3-39+4a7242e481c645 > latest-1.26.txt (published)"
level=info msg="Not updating version, because v1.26.3-39+4a7242e481c645 <= v1.26.3-rc.0.57+e6323abe65c431"
level=info msg="Skipping latest-1.26.txt for v1.26.3-39+4a7242e481c645 because it does not need to be updated"
```
Similar issues can be found in 1.25 and 1.24 builds (last 1.23 build added `rc.0` infix so it has not happened there yet): 
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-build-1-25/1643352413102411776/build-log.txt
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-build-1-24/1643335551438295040/build-log.txt

### What did you expect to happen?

I expect the `latest` files to be overwritten with newer version of the build.

### How can we reproduce it (as minimally and precisely as possible)?

Manually run build job for one of the minors.

### Kubernetes version

Not related.

### Cloud provider

Not related.

**Comment by cici37** [comment]
Thanks for raising the issue! 
/cc @saschagrunert @puerco who is working on https://github.com/kubernetes/release/issues/2972 before

**Comment by saschagrunert** [comment]
I assume this will be fixed automatically with the next patches, because then we would compare `v1.26.4-…` with `v1.26.3-rc.0.57+e6323abe65c431`.

Anyway, I think we should fix that intermediately by manually updating the version markers to match their correct version.

**Comment by xmudrii** [comment]
We had to update the versions markers again, because those were pointing to two commits earlier and didn't include the Go updates. The latest version markers are:

* https://dl.k8s.io/ci/latest-1.24.txt: v1.24.12-35+fac04a736991ff
* https://dl.k8s.io/ci/latest-1.25.txt: v1.25.8-37+92e757b67c79e0
* https://dl.k8s.io/ci/latest-1.26.txt: v1.26.3-41+abad95a0536325

**Comment by xmudrii** [comment]
latest-1.27 has been affected by this as well. I updated it manually to v1.27.0-9+1f69edd9297e87. See this thread for more details: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1681467578993719?thread_ts=1681466986.969079&cid=CJH2GBF7Y

**Comment by saschagrunert** [comment]
This should be fixed now, closing it. Feel free to reopen if we missed anything.

**Comment by xmudrii** [comment]
This issue is still present, see this Slack thread for more details: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1692828891722949?thread_ts=1692794783.631139&cid=CJH2GBF7Y
/reopen

**Comment by xmudrii** [comment]
We have a similar situation with latest-1.28 which is currently pointing to: `v1.28.0-rc.1.9+3fb5377b25ec51`. This is one commit before the release commit:

![image](https://github.com/kubernetes/kubernetes/assets/18719127/62b8628d-4e22-438d-bfbe-da5df1edd279)

It's mostly like that the release step didn't update version markers, we should look into this. As of now, I'm going to manually update this version marker to unblock 1.28.1 patch release.

I'll also take a look into this.
/assign

**Comment by xmudrii** [comment]
The PR that fixed this issue got reverted so this is still relevant: https://github.com/kubernetes/release/pull/3254
/reopen

**Comment by xmudrii** [comment]
We're running into this issue again with stable-1.29 marker. It's currently pointing to `v1.29.0-rc.2.6+fefc8228d13842` which is https://github.com/kubernetes/kubernetes/commit/fefc8228d138424267e95b1d2cf57b0d4d549a32. It should instead point to https://github.com/kubernetes/kubernetes/commit/2991f6e2165003c6fe50fb46a95d7215f9e65179.

I'm going to manually change it following the same procedure as the last time.

**Comment by saschagrunert** [comment]
Same issue for 1.30, where I had to update the version marker manually again.
