### ISSUE TITLE
Mount point will be local volume without calling `NodeStageVolume` if mount point was left over before node rebooting

### ISSUE THREAD

**Issue by cvvz** [kubernetes/kubernetes#117513]
### What happened?

The problem can be reproduced by following steps:
1. Create a cluster with one Node
2. Create a deployment with one replica using Non-attachable volume (for example Azurefile) 
3. Shutdown the Node
4. Delete the Pod with option `--force` (Use force deletion to simulate the situation that mount point was left over while original Pod is not in DSW during reconstruction.)
5. Bring back the Node
6. The new Pod is Running on the same Node but it is actually using local mount point.

### What did you expect to happen?

The new Pod should remount to original remote mount point, instead of local mount point.

### How can we reproduce it (as minimally and precisely as possible)?

As described above.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"dc2f9dc64421983f0f7839da8ab4ab6d4673daad", GitTreeState:"clean", BuildDate:"2023-04-08T13:29:19Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.25) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by cvvz** [comment]
The problem is mainly because during volume reconstruction, the reconstructed volume is no longer exists in DSW(since it was force deleted). And  the volume will be added to ASW as `DeviceGloballyMounted`, which actually is not in that state. And then, there is a new Pod created by deployment which will use the same volume, so the volume will be added to DSW, the result is that kubelet will only call `NodePublishVolume` for the new Pod, which will use the stale global moun point.

**Comment by cvvz** [comment]
This issue is the same situation in this comment: https://github.com/kubernetes/kubernetes/pull/116134#issuecomment-1500757052. cc @jsafrane

**Comment by cvvz** [comment]
cc @andyzhangx

**Comment by andyzhangx** [comment]
so if user does not use force delete pod, it would be safe? @cvvz

**Comment by cvvz** [comment]
I used force delete for simulation, I have no idea whether it can be reproduced in any other way.

**Comment by xing-yang** [comment]
@cvvz Could you please try to reproduce this in the latest K8s version?  We want to know whether this is already fixed.

**Comment by cvvz** [comment]
This issue should still exist in the latest version. 
I don't know whether it can be fixed with `NewVolumeManagerReconstruction` feature enabled. I will test with the feature gate on.

**Comment by boliu83** [comment]
> I used force delete for simulation, I have no idea whether it can be reproduced in any other way. At least if we don't use force deletion, the problem won't happen.

I found another way to reproduce this issue with using `--force` delete is to use pods without controller and pod's restartPolicy is set to  `Never`. 

To reproduce the issue:
1. create cluster with one node
2. create one such pod (no controller & restartPolicy: Never) using azurefile volume
3. reboot the node
4. create another pod with different name using the same azurefile volume while the node is still rebooting
5. the new pod becomes running but using local mount point 

During my test I also found the restartPolicy on the 1st pod is very important. If it's set to `Always`, Kubelet will still call NodeStageVolume to restore the global mount point. however when it's set to `Never`, kubelet skips NodeStageVolume.

**Comment by jiangyouP** [comment]
> I used force delete for simulation, I have no idea whether it can be reproduced in any other way. At least if we don't use force deletion, the problem won't happen.

Hello，I also found other way to reproduce.
Reproduction method1:
1. create a pod using PVC, and deploy the CSI plugin corresponding to the PVC as a pod as well.
2. add a taint A to the node that the pod cannot tolerate, and add a taint B to the node that CSI plugin cannot tolerate.
3. reboot the node
4. fter confirming that both the pod and the CSI plugin are in Terminating state, remove taint A first, and then remove taint B.

Reproduction method2:
1. create a pod using PVC.
2. reboot the node
3. when the kubelet code reaches [this point](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L318), construct an exception that the apiserver cannot access.
4. after the volume is reconstructed by [this point](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconstruct.go#L103), recover the apiserver.

**Comment by jiangyouP** [comment]
If we change the method of [this line](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconstruct.go#L163) to `MarkDeviceAsUncertain`, can it fix the issue without any side effects on the normal functions of kubelet?

**Comment by jsafrane** [comment]
I think it is / will be fixed by https://github.com/kubernetes/enhancements/issues/3756.
Can you try with Kubernetes 1.28? Or with 1.27 + `NewVolumeManagerReconstruction` feature gate enabled? (Beware of https://github.com/kubernetes/kubernetes/issues/117745 then)

**Comment by jsafrane** [comment]
> If we change the method of [this line](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconstruct.go#L163) to MarkDeviceAsUncertain, can it fix the issue without any side effects on the normal functions of kubelet?

IIRC `updateStates` can run while kubelet is already starting Pods and mounting volumes for them. I.e. marking a device as _uncertain_ could overwrite _certain_ mount.  In addition, `markVolumeState` call [above](https://github.com/kubernetes/kubernetes/blob/361e4ff0fac3e5e6c864198e78db4571e2508860/pkg/kubelet/volumemanager/reconciler/reconstruct.go#L149) should be also using uncertain mount. So, it needs to be done smarter and you may end up with `NewVolumeManagerReconstruction` in the end :-). We decided to rework the whole volume reconstruction instead of fixing already brittle code.

**Comment by jiangyouP** [comment]
> I.e. marking a device as _uncertain_ could overwrite _certain_ mount. 

hello @jsafrane  :D 
We found that if we only restart the kubelet without shutdown the node, the [code](https://github.com/kubernetes/kubernetes/blob/361e4ff0fac3e5e6c864198e78db4571e2508860/pkg/volume/util/operationexecutor/operation_generator.go#L647) will still be executed for PVC in normal case.So we think the overwriting is acceptable.

> In addition, `markVolumeState` call [above](https://github.com/kubernetes/kubernetes/blob/361e4ff0fac3e5e6c864198e78db4571e2508860/pkg/kubelet/volumemanager/reconciler/reconstruct.go#L149) should be also using uncertain mount. So, it needs to be done smarter and you may end up with `NewVolumeManagerReconstruction` in the end :-). We decided to rework the whole volume reconstruction instead of fixing already brittle code.

Next year we will upgrade our k8s version. But we have to fix this issue in k8s version 1.25 by ourself first. If we also change `markVolumeState`  to uncertain mount, the other functions of kubelet will be ok ? Hoping to pick your brains. :D

**Comment by jsafrane** [comment]
It might work, but I really cannot guarantee 100% stability. Volume reconstruction is quite error prone.

**Comment by jiangyouP** [comment]
Thank you! We will have a try :D

**Comment by cvvz** [comment]
> @cvvz Weizhi Chen FTE Could you please try to reproduce this in the latest K8s version? We want to know whether this is already fixed.

@xing-yang I've tested that `NewVolumeManagerReconstruction` can fix this issue. And I also fixed it under the old reconstruction implementation, could you pls take a look? @jsafrane

**Comment by cvvz** [comment]
Just found that delete the Pod without "--force" can also trigger this issue intermittently.
Sometimes the DSWP did not add volumes belongs to Pod in Terminating state to DSW.

**Comment by gnufied** [comment]
@cvvz in your original issue description, can you update the reproduction steps when step where the new pod gets created.

**Comment by cvvz** [comment]
@gnufied Sorry that I didn't get it, the new Pod will be created automatically on the same Node since there is only one Node in the cluster. (If it is created on other Node, there will be no issue.)
