### ISSUE TITLE
[klog] internal error during logging when trying to convert a map to a something printable

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#117809]
Please see the following internal error:
```
I0505 14:12:12.827065  190662 kuberuntime_manager.go:1014] "computePodActions got for pod" podActions="<internal error: json: unsupported type: map[container.ContainerID]kuberuntime.containerToKillInfo>" pod="kube-system/coredns-8f5847b64-mzw46"
```

This seems to be coming from:
https://cs.k8s.io/?q=computePodActions%20got%20for%20pod&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes

**Comment by pohly** [comment]
I checked the logs from https://testgrid.k8s.io/sig-instrumentation-tests#kind-json-logging-master and only found this one instance of the problem.

I also tried writing a linter, but got stuck at analyzing the type of a log value: if it was possible to instantiate a null value of a type, then reflect could be used to call `json.Encode` and hopefully that would return the same error also for the null value of a type. That should have worked for `podActions`, but isn't guaranteed (unsupported type might also be in some struct that the value normally points to). But I already got stuck at the first step.

The alternative is to traverse the type definition in the linter and re-implement the checks that the `json` package does - not very appealing.

**Comment by pohly** [comment]
> reflect could be used to call json.Encode

In retrospect it's obvious that this can't work: the type wasn't compiled into the linter, so it would have to be reconstructed there through reflect in its entirety before such a call can be made in the linter.

**Comment by dims** [comment]
@pohly lost track of this, have we fixed this yet?

**Comment by pohly** [comment]
Not fixed. I still would like to get comments on [my prior comment](https://github.com/kubernetes/kubernetes/issues/117809#issuecomment-1540441066) first.

**Comment by pohly** [comment]
That definitely should be done.

But should klog also handle this more gracefully, e.g. by falling back to `fmt.Sprintf`?

**Comment by SergeyKanzhelev** [comment]
does this bug justify the backport https://github.com/kubernetes/kubernetes/pull/120660?

**Comment by fusida** [comment]
> does this bug justify the backport #120660?

we have meet in 1.28.1~1.28.2, and hope to fix in 1.28.3

cc @dims @aojea

**Comment by pohly** [comment]
One particular appearance is solved, general solution still uncertain - see https://github.com/kubernetes/kubernetes/issues/117809#issuecomment-1540441066.

/remove-lifecycle stale

**Comment by pohly** [comment]
/remove-lifecycle stale

Not sure whom to discuss this with :cry: - opinions welcome.

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle rotten

/sig instrumentation
/priority backlog

Maybe sig instrumentation can look into the general solution

**Comment by dgrisonnet** [comment]
@pohly would it make sense to bring this issue to one of our SIG meeting?

/triage accepted
