### ISSUE TITLE
[Failing Test] periodic-conformance-main-k8s-main

### ISSUE THREAD

**Issue by chewong** [kubernetes/kubernetes#119446]
### Which jobs are failing?

periodic-conformance-main-k8s-main

### Which tests are failing?

Kubernetes e2e suite.SynchronizedBeforeSuite

### Since when has it been failing?

07/17 23:52PDT

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#periodic-conformance-main-k8s-main

### Reason for failure (if possible)

```
[38;5;9m[FAILED] Error waiting for all pods to be running and ready: Timed out after 600.001s.
Expected all pods (need at least 0) in namespace "kube-system" to be running and ready (except for 0).
32 / 44 pods were running and ready.
Expected 5 pod replicas, 1 are Running and Ready.
Pods that were neither completed nor running:
...
failed to create containerd task: failed to create shim task:
OCI runtime create failed: runc create failed: unable to start container
process: error during container init: error setting cgroup config for
procHooks process: open /sys/fs/cgroup/memory/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podba502507_31c5_47a1_a781_9041171c1d7a.slice/cri-containerd-38d5597a03cb39d529aae9f004d70ecc1c96874fe1268ed5c38f353cf15f020d.scope/memory.memsw.limit_in_bytes:
```

### Anything else we need to know?

We saw a similar issue in #119403, which was fixed by upgrading the control plane OS from Ubuntu 18.04 to 22.04.

### Relevant SIG(s)

/sig cluster-lifecycle

**Comment by pacoxu** [comment]
/sig node
It seems to be related to SWAP.

**Comment by pacoxu** [comment]
There is a bug in containerd that is fixed in v1.6.14. https://github.com/containerd/containerd/releases/tag/v1.6.14

- The test here is using v1.6.8.

**Comment by chewong** [comment]
Still failing after https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4409 is merged. 

```
Jul 20 10:35:36.743: INFO: At 2023-07-20 10:19:33 +0000 UTC - event for coredns-5dd5756b68-27qk5: {kubelet ip-10-0-199-154.us-west-2.compute.internal} Failed: Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: open /sys/fs/cgroup/memory/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podb23a8d58_bfad_4a09_a0f7_15e8956d42bd.slice/cri-containerd-coredns.scope/memory.memsw.limit_in_bytes: no such file or directory: unknown
```
Have we tried bumping the control plane OS image to ubuntu 22.04, like #119403?

**Comment by chewong** [comment]
Nevermind, the latest testgrid job might have been triggered before the PR was merged. I am observing this and will close this once I see the job passes.

**Comment by pacoxu** [comment]
Containerd version is already v1.6.21 in [last run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e-conformance-with-k8s-ci-artifacts/1682082450357882880)'s log https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e-conformance-with-k8s-ci-artifacts/1682082450357882880/artifacts/clusters/bootstrap/instances/conformance-wkh5oq/conformance-gx29np-md-0-pt5gl/containerd.log. 
> Jul 20 17:58:00 ip-10-0-69-209 containerd[1091]: time="2023-07-20T17:58:00.277214546Z" level=info msg="starting containerd" revision=3dce8eb055cbb6872793272b4f20ed16117344f8 version=v1.6.21

There maybe still other problems.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/pull/119486 can fix a similar failure in `kubernetes-e2e-ubuntu-gce-network-policies`.

**Comment by pacoxu** [comment]
/close

The failure of the swap is fixed by #119486.
The current failure is a flake that is mentioned in https://github.com/kubernetes/kubernetes/issues/118731.
