### ISSUE TITLE
graceful shutdown make pod containerStatuses different

### ISSUE THREAD

**Issue by yylt** [kubernetes/kubernetes#120168]
### What happened?

when node shutdown, and kubelet had enable GracefulShutdown feature. the pods in the node is terminated after, but it is confused that pods has different  containerStatuses,

There are `OOMKilled, Completed and Error` containerStatus

```
cert-manager-cainjector-cc844b5f4-dn4kb         0/1     OOMKilled   3 (44h ago)   45h
cert-manager-istio-csr-795dbf9c7c-wdrfq         1/1     Running     1 (15h ago)   15h
cert-manager-istio-csr-795dbf9c7c-xcx68         0/1     Completed   2             44h
cert-manager-webhook-597b59c797-6rqnl           1/1     Running     0             15h
cert-manager-webhook-597b59c797-qlgwt           0/1     OOMKilled   1             43h
gateway-api-admission-server-58484f8c58-4g4cm   0/1     Error       0             2d21h
gateway-api-admission-server-58484f8c58-586lr   1/1     Running     0             41m
```

and the pod.Status is

```
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-08-24T12:22:03Z"
    message: Pod was terminated in response to imminent node shutdown.
    reason: TerminationByKubelet
    status: "True"
    type: DisruptionTarget
  - lastProbeTime: null
    lastTransitionTime: "2023-08-23T08:05:58Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-08-24T12:21:58Z"
    reason: PodFailed
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-24T12:21:58Z"
    reason: PodFailed
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-08-23T08:05:57Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://588cf8e4024e223cc8d0147a33f07ecc3b2546ba23a007539bead9a2b3867c31
    image: docker.io/library/cert-manager:v1.10.2
    imageID: docker.io/library/cert-manager@sha256:ba536580303440112df3326cf7ccba254635028e3c05f0a1c196d6a2d0578cc1
    lastState: {}
    name: cert-manager-webhook
    ready: false
    restartCount: 1
    started: false
    state:
      terminated:
        containerID: containerd://588cf8e4024e223cc8d0147a33f07ecc3b2546ba23a007539bead9a2b3867c31
        exitCode: 0
        finishedAt: "2023-08-24T12:21:57Z"
        reason: OOMKilled
        startedAt: "2023-08-23T08:17:07Z"
  hostIP: 192.168.0.68
  message: Pod was terminated in response to imminent node shutdown.
  phase: Failed
  podIP: 10.232.2.114
  podIPs:
  - ip: 10.232.2.114
  qosClass: Burstable
  reason: Terminated
  startTime: "2023-08-23T08:05:58Z"
---

  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-08-24T12:22:00Z"
    message: Pod was terminated in response to imminent node shutdown.
    reason: TerminationByKubelet
    status: "True"
    type: DisruptionTarget
  - lastProbeTime: null
    lastTransitionTime: "2023-08-22T06:32:54Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-08-24T12:21:58Z"
    reason: PodFailed
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-24T12:21:58Z"
    reason: PodFailed
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-08-22T06:32:54Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://96cd483859d1c557a974f4ad6c29714b378fc180eb51d9ded40b2cf6dcc6d195
    image: docker.io/library/admission-server:v0.7.1
    imageID: docker.io/library/admission-server@sha256:a32a711e140a85b0bd73b5b4939f412344160d5d7c90c279cbaafc17ebb0703e
    lastState: {}
    name: webhook
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://96cd483859d1c557a974f4ad6c29714b378fc180eb51d9ded40b2cf6dcc6d195
        exitCode: 255
        finishedAt: "2023-08-24T12:21:57Z"
        reason: Error
        startedAt: "2023-08-22T06:41:16Z"
  hostIP: 192.168.0.68
  message: Pod was terminated in response to imminent node shutdown.
  phase: Failed
  podIP: 10.232.2.7
  podIPs:
  - ip: 10.232.2.7
  qosClass: Guaranteed
  reason: Terminated
  startTime: "2023-08-22T06:32:54Z"
``` 

### What did you expect to happen?

the pods which killed by gracefulshutdown node should has only one containerstatus, like only `Completed`

### How can we reproduce it (as minimally and precisely as possible)?

just exceute shutdown now in the node shell

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.4-es", GitCommit:"d9192c2e8ba99fbc7788120e5e79270a50f5e45f", GitTreeState:"clean", BuildDate:"2023-08-08T09:33:21Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.4-es", GitCommit:"d9192c2e8ba99fbc7788120e5e79270a50f5e45f", GitTreeState:"clean", BuildDate:"2023-08-08T09:32:55Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by rphillips** [comment]
This is probably fixed with https://github.com/kubernetes/kubernetes/pull/117019

**Comment by yylt** [comment]
try to backport https://github.com/kubernetes/kubernetes/pull/117019, but issue still existd. and this is only on pod which created by deployments controller. 

try to delete pod, and use `ctr event` can find why status is `Error`
```
# kubectl delete po gateway-api-admission-server-58484f8c58-cbds6
pod "gateway-api-admission-server-58484f8c58-cbds6" deleted

# ctr event   // concurrent start with kubectl delete operato
# ctr event
2023-08-28 09:15:05.41512511 +0000 UTC k8s.io /tasks/exit {"container_id":"770b6fef321635f07e97817473da3d612580ea7156d69825ac6e1d9945df5521","id":"770b6fef321635f07e97817473da3d612580ea7156d69825ac6e1d9945df5521","pid":38465,"exit_status":255,"exited_at":"2023-08-28T09:15:05.415068476Z"}
2023-08-28 09:15:05.438712825 +0000 UTC k8s.io /tasks/delete {"container_id":"770b6fef321635f07e97817473da3d612580ea7156d69825ac6e1d9945df5521","pid":38465,"exit_status":255,"exited_at":"2023-08-28T09:15:05.415068476Z"}
2023-08-28 09:15:05.509704495 +0000 UTC k8s.io /tasks/exit {"container_id":"c093a88f942eac668292047a458c7c1ab30966dce2b015179935bbe8a827d21e","id":"c093a88f942eac668292047a458c7c1ab30966dce2b015179935bbe8a827d21e","pid":38434,"exit_status":137,"exited_at":"2023-08-28T09:15:05.509674309Z"}
2023-08-28 09:15:05.533018388 +0000 UTC k8s.io /tasks/delete {"container_id":"c093a88f942eac668292047a458c7c1ab30966dce2b015179935bbe8a827d21e","pid":38434,"exit_status":137,"exited_at":"2023-08-28T09:15:05.509674309Z"}
```

the exit_status is containerStatus exitcode.

**Comment by yylt** [comment]
the applications not handler signal well. close
