### ISSUE TITLE
6 minute TTL for proxy tunnels is bad experience for long-lived connections

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#12179]
We close tunnels 6 minutes after they are opened (1 minute after the 5 minute refresh). A long-lived connection (e.g. `kubectl exec ... -i -t -- bash`) will be forcibly closed anywhere from 1 to 6 minutes after it is started. The new support for attach in kubectl will also run into this.

**Comment by cjcullen** [comment]
Initial thoughts on how to fix this:

Make the tunnels more on-demand: Let the steady-state of the tunnel list be empty. When Dial() is called on an empty list, open a new tunnel and add it to the list. Subsequent Dial() calls can reuse that tunnel. On dial, start (or restart) a 5 minute timer. When that timer runs out, drop the tunnel from the list (without explicitly calling Close()).

My knee-jerk reaction is that not calling Close() on the underlying conn will probably leak goroutines. It'd be nice to be able to tell when the connection has been closed out from under us. Maybe the fact that unused connections get closed also ensures that go's resources aren't stranded. I'll have to look into this.

The other problem with this approach is hot-spotting, especially as we increase the scale. In a large, heavily used cluster, whichever node is unlucky enough to get hit with the tunnel may see a large amount of unaccounted network traffic and CPU usage. We could mitigate this by sharding over multiple tunnels, but at the cost of Dial() latency (and complexity).

@lavalamp @brendanburns @roberthbailey Thoughts?

**Comment by timothysc** [comment]
cc @jwforres

**Comment by lavalamp** [comment]
This sounds like a good idea. It will be important not to leak these; if
they don't auto-close, then you'll have to find a way to see how many
connections they have, or write code to manually keep counts.

**Comment by pnovotnak** [comment]
bump

**Comment by lavalamp** [comment]
Combining w/ #13360, bumping priority.

**Comment by cjcullen** [comment]
Simpler idea:

Don't TTL tunnels at all. Have the tunnel management code query the kubelet healthz on the node it's tunneling into. This should stop the tunnel from being dropped, and if we can't reach healthz, we can assume we need to reopen the tunnel.

**Comment by ncdc** [comment]
@cjcullen is this GCE/GKE specific, or are you referring to the proxies in the apiserver?

**Comment by roberthbailey** [comment]
@ncdc This is for the SSH tunnels.

**Comment by ncdc** [comment]
@roberthbailey I'm not familiar with SSH tunnels in the context of Kubernetes. Where are they being used?

**Comment by liggitt** [comment]
Alternate method of master->kubelet communication. See server.go for tunneling setup

**Comment by pires** [comment]
I'm having the same behavior by running `kubectl` on my local machine against a GKE cluster.

**Comment by cjcullen** [comment]
#19314 will address this (no more 6-minute drops).

**Comment by cjcullen** [comment]
Fixed by #19314

**Comment by alexcouper** [comment]
I still experience this behaviour (of `kubectl exec -it` dropping out).

Running kubernetes v1.5.6.

**Comment by vncntvandriessche** [comment]
We are getting hard by this issue very often:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

As I've understood it now there's several matters that are influencing this issue:

- kubelet has a TTL for connections it conceives as idle
- tunnels are sent to 1 node's kubelet, and not per-se the node where the target pod is running (if that node fails/gets removed [autoscale!] it breaks the connection)

Is there suggested reliable & simple way to circumvent this issue somehow? I'd rather not loose the simplicity of `kubectl exec -it [...]` but currently our developers can't really use it properly.
