### ISSUE TITLE
node.yaml files can't use environment variables when naming a command to execute

### ISSUE THREAD

**Issue by runningwild** [kubernetes/kubernetes#12435]
From [some reference I found](http://www.freedesktop.org/software/systemd/man/systemd.service.html), 

> The command to execute must an absolute path name. It may contain spaces, but control characters are not allowed.

Currently, on coreos, rkt is downloaded and installed to /opt/rkt/rkt-${RKT_VERSION}.  It either needs to be installed somewhere literal or the binary needs to be symlinked to something literal.

**Comment by runningwild** [comment]
Created [PR 12436](https://github.com/GoogleCloudPlatform/kubernetes/pull/12436) to address this.  This only fixes gce, so someone else that uses aws might want to take care of that one.

Also if anyone has any issues with how I'm fixing this I'm happy to change it, seems simple enough though.

**Comment by a-robinson** [comment]
Fixed by #12436

**Comment by runningwild** [comment]
This is still an issue on aws, right?
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/aws/coreos/node.yaml#L127

**Comment by a-robinson** [comment]
Ah, sorry! I didn't read your second comment.
