### ISSUE TITLE
Kubernetes 1.0.3 does not work with VirtualBox 5.0.0

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#12614]
Kubernetes 1.0.3 does not work with `Virtual Box 5.0.0 r101573` and gives the following error message:

```
kubernetes> echo $KUBERNETES_PROVIDER 
vagrant
kubernetes> ./cluster/kube-up.sh 
Starting cluster using provider: vagrant
... calling verify-prereqs
... calling kube-up
Using credentials: vagrant:vagrant
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
```

Using the `curl` command also gives similar error:

```
 curl -sS https://get.k8s.io | bash
Downloading kubernetes release v1.0.1 to /Users/arungupta/tools/kubernetes.tar.gz
--2015-08-12 15:19:23--  https://storage.googleapis.com/kubernetes-release/release/v1.0.1/kubernetes.tar.gz
Resolving storage.googleapis.com... 216.58.216.176, 2607:f8b0:400a:807::2010
Connecting to storage.googleapis.com|216.58.216.176|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 118107384 (113M) [application/x-tar]
Saving to: 'kubernetes.tar.gz'

kubernetes.tar.gz                   100%[=====================================================================>] 112.64M  6.83MB/s   in 60s    

2015-08-12 15:20:23 (1.88 MB/s) - 'kubernetes.tar.gz' saved [118107384/118107384]

Unpacking kubernetes release v1.0.1
Creating a kubernetes on vagrant...
Starting cluster using provider: vagrant
... calling verify-prereqs
... calling kube-up
Using credentials: vagrant:vagrant
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
```

This is broken!

**Comment by derekwaynecarr** [comment]
What is your host OS?

Does which vagrant and which virtualbox return a result?

**Comment by arun-gupta** [comment]
```
> uname -a
Darwin Aruns-MacBook-Pro.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
> which vagrant
/usr/bin/vagrant
> which virtualbox
/usr/local/bin/virtualbox
```

**Comment by arun-gupta** [comment]
This is blocking from starting up Kubernetes cluster. Any ETA for this fix?

**Comment by arun-gupta** [comment]
Downgraded to Docker 1.7.0 as:

curl -sSL -O https://get.docker.com/builds/Darwin/x86_64/docker-1.7.0 && chmod +x docker-1.7.0 && sudo mv docker-1.7.0 /usr/local/bin/docker

and VirtualBox to 4.3.30.

And now its going beyond this error!

**Comment by derekwaynecarr** [comment]
Can this issue now be closed?

**Comment by arun-gupta** [comment]
Getting stuck in minion validating loop now ...

```
Each machine instance has been created/updated.
  Now waiting for the Salt provisioning process to complete on each machine.
  This can take some time based on your network, disk, and cpu speed.
  It is possible for an error to occur during Salt provision of cluster and this could loop forever.
Validating master
Validating minion-1
......
Waiting for each minion to be registered with cloud provider
.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

Tried shutting down the cluster, untarring the archive, starting again, and same result.

Falling back to something before 1.0.3.

**Comment by arun-gupta** [comment]
Kubernetes 1.0.1 with Virtual Box 4.3.30 works. So the bug is still valid for the following configurations:

- Kubernetes 1.0.3 with Virtual Box 4.3.30
- Kubernetes x.x.x with Virtual Box 5.0.0

**Comment by jonmoter** [comment]
I'm getting the same thing as @arun-gupta, trying to run Kubernetes 1.0.3 with VirtualBox 5.0.2.  FYI, I'm running with Vagrant 1.7.4.  I get stuck at the "Waiting for each minion to be registered with cloud provider" infinite loop.

I believe this is the same issue as #12854, because when I check `master:/var/log/kube-apiserver.log`, I see a lot of:

```
I0818 22:40:29.119244      12 logs.go:41] http: TLS handshake error from 10.245.1.3:55779: remote error: bad certificate
```

**Comment by derekwaynecarr** [comment]
The fix was merged in #12514 and will be available in release 1.0.5

**Comment by arun-gupta** [comment]
@derekwaynecarr is there a CI build available somewhere?

**Comment by creativeux** [comment]
This problem still appears with VirtualBox 5.0.4 and Docker 1.8.

**Comment by Hokutosei** [comment]
same here, no luck

```
-> % ./cluster/kube-up.sh
Starting cluster using provider: vagrant
... calling verify-prereqs
... calling kube-up
Using credentials: vagrant:vagrant
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
```

kubernetes 1.0.6
virtualbox 5.0

**Comment by olalonde** [comment]
FWIW, this works with vbox 5 https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant-single.html
