### ISSUE TITLE
add `matchLabelKeys: ["pod-template-hash"]` in the default `ScheduleAnyway` topology spread

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#129198]
We recently added `matchLabelKeys` feature at [pod topology spread](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/).

Pod topology spread has the [Cluster-level default constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#cluster-level-default-constraints);

```yaml
defaultConstraints:
  - maxSkew: 3
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: ScheduleAnyway
  - maxSkew: 5
    topologyKey: "topology.kubernetes.io/zone"
    whenUnsatisfiable: ScheduleAnyway
```

I was wondering, when it comes to the pods owned by a replicaset controller, would it make sense to consider `matchLabelKeys: ["pod-template-hash"]` there? (I guess such change in the default behavior is allowed, am I right?)

/cc @kubernetes/sig-scheduling-misc @macsko @dom4ha 
/sig scheduling
/kind feature

**Comment by alculquicondor** [comment]
This is more of a question for sig-apps

From sig-scheduling, we provided the capability. But it's up to sig-apps to decide what the behavior should be for a ReplicaSet.

**Comment by sftim** [comment]
It's a shame that `pod-template-hash` is a private label.

Ideally we wouldn't do anything to cement the use of it (I'd prefer to track a public label - see https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ for what _private_ and _public_ mean here).

**Comment by sftim** [comment]
What we could do:
- add a new label, eg `apps.kubernetes.io/pod-template-hash`
- initially, just support it
- the following release sets the `apps.kubernetes.io/pod-template-hash` and `pod-template-hash` labels when a Pod template changes (or is initially created), but doesn't touch existing ReplicaSets etc.
- the minor release after that finally triggers a rollout for any workloads that haven't changed so far, by forcing `apps.kubernetes.io/pod-template-hash` to be set (`pod-template-hash` is still set). We deprecate `pod-template-hash`.
- we are now also free to inject the now-formal label into topology spread `matchLabelKeys` and other places where we care.

It would need a KEP. Anyway, if we don't have the appetite and capacity to do the complex thing, I don't want us to make the existing bodge harder to clean up.

**Comment by sanposhiho** [comment]
anyways cc @kubernetes/sig-apps-feature-requests

**Comment by soltysh** [comment]
Actually that label is being managed by the deployment controller, who uses it to ensure that RCs are only managing the desired set of pods, and not interfere with newer, for example. Those decisions go back to early days of k8s, and aligning them currently seems multiple-release effort, which I don't see we have the capacity to push through. 

The one thing I can't fully understand is how this specific label is affecting the pod topology spread?

**Comment by alculquicondor** [comment]
It's rather the opposite: the absence of pod-template-hash in the default/internal topology spread rules makes it so that pods of a Deployment are evenly distributed, even if they belong to different ReplicaSets, leading to possibly unbalanced pods when the old ReplicaSet is gone, after a rolling upgrade.

**Comment by sftim** [comment]
Spreading based on the `pod-template-hash` can be useful.

> For example, if you are configuring a Deployment, you can use the label keyed with [pod-template-hash](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pod-template-hash-label), which is added automatically by the Deployment controller, to distinguish between different revisions in a single Deployment.
> 
> ```yaml
>     topologySpreadConstraints:
>         - maxSkew: 1
>           topologyKey: kubernetes.io/hostname
>           whenUnsatisfiable: DoNotSchedule
>           labelSelector:
>             matchLabels:
>               app: foo
>           matchLabelKeys:
>             - pod-template-hash
> ```

What that means is that the spreading is _per revision_. Without it, you might happen to find all the new Pods on one node but the set of old and new Pods together are nicely spread across nodes. With it, the old revision gets spread across nodes with a max skew of 1, and the new revision also gets spread across nodes with a max skew of 1.

**Comment by sftim** [comment]
> aligning them currently seems multiple-release effort, which I don't see we have the capacity to push through.

I agree. My point is that, until we find the capacity to fix the `pod-template-hash` label key, we should be reluctant to do anything that makes the eventual cleanup even more difficult, or that tacitly condones the design snag we adopted way back when.

**Comment by sanposhiho** [comment]
> we should be reluctant to do anything that makes the eventual cleanup even more difficult

This Cluster-level default constraints is just that the scheduler internal stuff; if pods don't have any constraints, then the plugin calculates the scores for them as if they have those default constraints. It's not that the constraints are added by default at pod creation, or whatever API level stuff.
So I don't think this proposal would make such a future work more difficult.

**Comment by sanposhiho** [comment]
Why would they have to trigger a rollout after we rename the label?

The long-lived RS does not have a new apps.kubernetes.io/pod-template-hash label, which a new version of the scheduler uses in matchLabelKey in the default constraints.
But, that wouldn't matter, right?
When we need (apps.kubernetes.io/)pod-template-hash is actually only when we rollout the owner deployment. 
Even if the long-lived RS, for example, gets scaled up and new pods are born from it, they are scheduled appropriately, with the default constraints with a new label at matchLabelKeys.
(the scheduler just ignores matchLabelKeys if the label doesn't exist.)

Am I missing some scenarios?

**Comment by sftim** [comment]
I think there is still complexity here @sanposhiho, and I've not been swayed from my view in https://github.com/kubernetes/kubernetes/issues/129198#issuecomment-2557116912

**Comment by alculquicondor** [comment]
I guess there is a bit of complexity, but not one that can't be resolved in a KEP, if @sanposhiho has the time to drive it.

**Comment by sanposhiho** [comment]
Well, I can write a KEP if needed, yes. But, I guess I don't quite get where is the complexity that everyone meant. Especially, I still cannot see a reason why cluster admins might need to trigger rollouts, at all. How would the long-lived RSs behave inappropriately otherwise. 
I can only start KEP after understanding it otherwise I'd just repeat [the same explanation](https://github.com/kubernetes/kubernetes/issues/129198#issuecomment-2557221470) that didn't explain enough, apparently.

@sftim can you elaborate on that?

**Comment by sftim** [comment]
Even if cluster admins don't need to trigger rollouts, the other caveats would apply. Especially that we would be tacitly endorsing a now-poor choice of label key.

What I hope is obvious: `pod-template-hash` is wrong; we should [gradually, carefully] switch to a label that we can add to [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/).

And, once again, if we don't have capacity to do that switch, we shouldn't add the defaulting that this issue calls for. Once we have that capacity, let's use it, and we can add the defaulting that you - @sanposhiho - suggested.

**Comment by sanposhiho** [comment]
I totally understand what you hope, and been asking what's (technical) "other caveats" to make your hope make sense. 

> we would be tacitly endorsing a now-poor choice of label key.

So, right, it's completely internal and done tacitly to users. Then how would it make a hurdle for a renaming?

**Comment by sftim** [comment]
As I see it: this isn't a "it can't work unless we do _x_" problem; it's a "we should prioritize _y_ over _x_" problem.

**Comment by sanposhiho** [comment]
Either is fine. I know it makes sense to block or deprioritize this proposal until the renaming if this could make it harder. And, hence I keep asking how you believe this could make it harder.

If we don't have a clear reasoning of this blocking that, how would the prioritization be made between two in the first place

**Comment by sftim** [comment]
Making this change boosts incorporation of `pod-template-hash` into infrastructure designs, because it makes the existing label more salient and visible.

Every person who changes their code or runbooks to adopt `pod-template-hash` will have to make a change if we eventually deprecate it (well, assuming that they read deprecation notices!)

**Comment by sanposhiho** [comment]
Speaking of the label renaming actually though, are we really going to completely remove the label eventually? If Yes, we'd have to be very sensitive and try not to make users utilize this label, even a bit.
But, taking the recent example https://github.com/kubernetes/kubernetes/issues/113714, apparently they concluded that they would keep the old label forever and just switch k/k code base from the old one to the new one at some point.

**Comment by sftim** [comment]
> are we really going to completely remove the label eventually?

That's a question for the KEP, I think. Once there is one.

**Comment by dom4ha** [comment]
Note that "matchLabelKeys cannot be set when labelSelector isn't set". IIUC one cannot set template hash when a subset of pods wasn't specified by a label. Is that also need to be changed?

**Comment by sanposhiho** [comment]
> matchLabelKeys cannot be set when labelSelector isn't set

Do we really have this limitation? I don't remember though.

**Comment by dom4ha** [comment]
Right, it seems like scheduler ignores matchLabels when labels.Selector is not defined:

https://github.com/kubernetes/kubernetes/blob/adbf234f592f2e8a50060c6f9b12b0cfa52dc283/pkg/scheduler/framework/plugins/podtopologyspread/common.go#L134-L146

**Comment by alculquicondor** [comment]
FWIIW, I am in favor of writing a KEP for this. Ideally, I would like it to include a transition plan for the label name.

But, again, this is something that needs to be approved by SIG Apps.

**Comment by sanposhiho** [comment]
Speaking of the relationship between this and the renaming, the only risk that I admitted is [this one](https://github.com/kubernetes/kubernetes/issues/129198#issuecomment-2559373493); if we start to use pod-template-hash internally, that might enhance people use it similarly in their cluster. 
So, it's not a technical risk like we can start it now, but with a transition plan. But, it's like an all-or-nothing question; whether we're ok to ignore this implicit concern and move on, or we should stop until renaming is done.

**Comment by alculquicondor** [comment]
TBH, people that care about spreading during upgrades are probably already using matchLabelKeys with pod-template-hash, because there isn't a better alternative.
So I don't think using it as a default would encourage the usage of it, rather reduce it (as it would be added implicitly).

**Comment by sanposhiho** [comment]
Yeah, that's also true. Either way, I'd like to follow a decision from SIG-App here.
