### ISSUE TITLE
k8s.io/apiserver/pkg/util: proxy TestStreamTranslator_TTYResizeChannel failing in `pull-kubernetes-unit`

### ISSUE THREAD

**Issue by aramase** [kubernetes/kubernetes#130018]
### Which jobs are flaking?

pull-kubernetes-unit

### Which tests are flaking?

TestStreamTranslator_TTYResizeChannel

### Since when has it been flaking?

Noticed the failure in https://github.com/kubernetes/kubernetes/pull/129993

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/129993/pull-kubernetes-unit/1887599657052278784

### Relevant SIG(s)

/sig api-machinery

**Comment by BenTheElder** [comment]
at https://go.k8s.io/triage this seems to only have one failure: https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestStreamTranslator_TTYResizeChannel&test=k8s.io%2Fapiserver%2Fpkg%2Futil

there is one more failure on the 1-32 branch periodic unit test

**Comment by BenTheElder** [comment]
The failure is the code=400 instead of code=200 right?

@seans3 do you know any reason this would happen? You seem to be the author of this test

The other failure mode is:
>     streamtranslator_test.go:628: error on createHTTPStreams: unable to upgrade: X-Stream-Protocol-Version is required

/triage accepted
/priority backlog

**Comment by BenTheElder** [comment]
I saw this again in the TestStreamTranslator_ErrorStream test case https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/130760/pull-kubernetes-unit/1899936590021529600

https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=X-Stream-Protocol-Version

Smells like a bug.

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/130250/pull-kubernetes-unit/1901691460063858688 

```
=== RUN   TestStreamTranslator_TTYResizeChannel
    streamtranslator_test.go:628: error on createHTTPStreams: unable to upgrade: X-Stream-Protocol-Version is required
E0317 18:12:30.673175   75961 conn.go:339] Error on socket receive: read tcp 127.0.0.1:46057->127.0.0.1:40720: use of closed network connection
--- FAIL: TestStreamTranslator_TTYResizeChannel (0.99s)
```

**Comment by seans3** [comment]
Currently, I have not been able to reproduce this error. The efforts to reproduce include running two of the offending tests for at least 20 minutes continuously (and at least 69k iterations)
```
$ stress ./streamtranslator.test -test.run TestStreamTranslator_ThrottleReadChannels
5s: 256 runs so far, 0 failures
10s: 512 runs so far, 0 failures
15s: 828 runs so far, 0 failures
20s: 1088 runs so far, 0 failures
…
20m15s: 68266 runs so far, 0 failures
20m20s: 68555 runs so far, 0 failures
20m25s: 68832 runs so far, 0 failures
20m30s: 69112 runs so far, 0 failures
```
also
```
$ stress ./streamtranslator.test -test.run TestStreamTranslator_TTYResizeChannel
5s: 346 runs so far, 0 failures
10s: 712 runs so far, 0 failures
15s: 1083 runs so far, 0 failures
20s: 1456 runs so far, 0 failures
…
21m20s: 91793 runs so far, 0 failures
21m25s: 92170 runs so far, 0 failures
21m30s: 92555 runs so far, 0 failures
21m35s: 92936 runs so far, 0 failures
```

More context on the error:

* This error occurs when the handler for the test SPDY server is invoked, and the passed HTTP request for the SPDY upgrade does not have any header specifying the subprotocol (`X-Stream-Protocol-Version`). https://github.com/kubernetes/kubernetes/blob/5639e1fd08dc71ab1c9e759931ecf037721eab90/staging/src/k8s.io/apiserver/pkg/util/proxy/streamtranslator_test.go#L866-L870
https://github.com/kubernetes/kubernetes/blob/5639e1fd08dc71ab1c9e759931ecf037721eab90/staging/src/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go#L168-L171
* There is no obvious reason for the SPDY upgrade request to be missing this header, since the subprotocols are hard-coded, and they are set in the HTTP header directly before calling the SPDY upstream server here: https://github.com/kubernetes/kubernetes/blob/5639e1fd08dc71ab1c9e759931ecf037721eab90/staging/src/k8s.io/client-go/transport/spdy/spdy.go#L94-L97
* This error mostly has occurred for `StreamTranslator` proxy unit tests, but it appears to have also occurred three times of the last year in the `StreamTunnel` proxy unit tests.
* This error appears to have first occurred on May 13, 2024. This does not line up with any stream translator proxy  code submissions (Oct. 23, 2023, Feb. 27, 2024, and Feb 24, 2025).
* The second flake for this error appears to have occurred on July 4, 2024. Again, it does not line up with any stream translator proxy code submissions.
* Since July of 2024, this flake appears to have occurred approximately 4 times during any two week window. 

Hypothesis: there is some rare corruption occurring for the SPDY executor zeroing out the `subprotocols` field, or the SPDY upgrade request removing the `X-Stream-Protocol-Version` header.

I will continue to investigate.

**Comment by pacoxu** [comment]
In #132506, we fixed a flake in the same UT file. 

We can keep watching if this is also fixed after that.

**Comment by BenTheElder** [comment]
TestStreamTranslator_TTYResizeChannel flaked today in some downstream CI unfortunately, so I suspect it's not quite resolved yet. 

Upstream it also flaked on a few PRs, I spot checked and while the periodic failure was on 1.33 and might just need a cherry-pick, at least one was on a PR to master

https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestStreamTranslator_TTYResizeChannel

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/132870/pull-kubernetes-unit/1943333017023942656 for https://github.com/kubernetes/kubernetes/pull/132870

**Comment by BenTheElder** [comment]
downstream I saw:
>     streamtranslator_test.go:628: error on createHTTPStreams: unable to upgrade: X-Stream-Protocol-Version is required

upstream I see:
>          apiserver_stream_translator_requests_total{code="200"} 1
>        -apiserver_stream_translator_requests_total{code="400"} 1

**Comment by BenTheElder** [comment]
> Hypothesis: there is some rare corruption occurring for the SPDY executor zeroing out the subprotocols field, or the SPDY upgrade request removing the X-Stream-Protocol-Version header.

This would also be a production flake then, right? Not just a flaking test.

**Comment by pacoxu** [comment]
Does this still flake? 


https://storage.googleapis.com/k8s-triage/index.html?text=TestStreamTranslator_TTYResizeChannel&job=unit&xjob=1-30
shows last flake is 7/12 which is on ppc64le and `ci-kubernetes-unit` last flake is 07/08. 

This may be fixed by https://github.com/kubernetes/kubernetes/pull/131203.

**Comment by aojea** [comment]
still flakes :(

**Comment by BenTheElder** [comment]
Note that the triage dashboard is stuck at 7/16 as the latest. https://github.com/kubernetes/test-infra/issues/35173

> https://storage.googleapis.com/k8s-triage/index.html?text=TestStreamTranslator_TTYResizeChannel&job=unit&xjob=1-30
shows last flake is 7/12 which is on ppc64le and ci-kubernetes-unit last flake is 07/08.

same link, but enabling PR:
https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestStreamTranslator_TTYResizeChannel&job=unit&xjob=1-30

and ignoring ppc:
https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestStreamTranslator_TTYResizeChannel&job=unit&xjob=1-30%7Cppc

shows failures 7/10, 7/13, 7/14

still flaking

**Comment by BenTheElder** [comment]
I fixed triage so it's up to date again.

This remains as a rare flake:
https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestStreamTranslator_TTYResizeChannel&job=unit&xjob=1-30%7Cppc

**Comment by BenTheElder** [comment]
> unable to upgrade: X-Stream-Protocol-Version is required

This failure mode persists
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/133431/pull-kubernetes-unit/1953613653546635264

**Comment by BenTheElder** [comment]
Similar to the other failure, it happens across various tests in this package https://storage.googleapis.com/k8s-triage/index.html?text=X-Stream-Protocol-Version%20is%20required

**Comment by seans3** [comment]
### Yet more context, and a hypothesis:

It continues to be very difficult to reproduce this bug. After > 21 million sequential runs over 13 hours using `stress`, the bug was not reproduced:
```
$ stress ./proxy.test -test.run TestStreamTranslator_TTYResizeChannel
...
13h5m10s: 21280206 runs so far, 0 failures
13h5m15s: 21282394 runs so far, 0 failures
13h5m20s: 21284515 runs so far, 0 failures
13h5m25s: 21286672 runs so far, 0 failures
13h5m30s: 21288843 runs so far, 0 failures
```

#### Other unsuccessful techniques

1. Ran the unit test in parallel: `$ go test -race -v -count=1 -parallel=100 ./...`
2. Random millisecond-level sleep calls within various stages of the test.
3. Creating a "noisy neighbor" in another terminal using `stress-ng`.
4. Adding a "ready" channel to coordinate the stages of the API server proxy and the mock SPDY server.

### An analysis of the bug

The rare bug occurs in the handler for a mock SPDY server when an `http.Request` does not contain a required sub-protocol `Header`. It is notable that the retrieval of the request `Header` is the first thing that happens within the SPDY handler. There does not appear to be any application/test code which could affect the `http.Request` before this retrieval in the streaming handshake. Since an `http.Request` for a server can be reused from a `sync.Pool`, it seems possible the `http.Request` is not properly cleaned-up from a previous test run.

#### A Hypothesis

The root cause could be a latent bug in Go's `net/http` server, where under specific high-load conditions, a recycled `http.Request` object is handed to the test handler in a "dirty" state. The server's use of **lazy header parsing** is the direct trigger that exposes this dirty state and causes the test to fail.

#### The Detailed Sequence of Events
Here is the step-by-step breakdown of how the failure might occur:

**The High-Churn Environment**: The CI runner executes thousands of tests concurrently. This creates extreme pressure on Go's internal `sync.Pool`, which is used to recycle `http.Request` objects to avoid the performance cost of constant memory allocation.

**The Creation of the "Dirty" Object**: An unrelated test running in the same process terminates its connection uncleanly. A race condition in the `net/http` library's cleanup logic causes the associated `http.Request` object to be returned to the global pool in a "dirty" state. This object's internal state is now inconsistent, specifically concerning its readiness for header parsing.

**The Unlucky Moment**: The `TestStreamTranslator_TTYResizeChannel` test begins. Its client connects to its mock SPDY server.

**Reuse of the Dirty Object**: To handle the new connection, the `net/http` server pulls the "dirty" `http.Request` object from the `sync.Pool` and assigns it to the test's handler.

**The Lazy Parsing Trigger**: Go's server is highly optimized. It performs lazy parsing; it does not parse the full set of HTTP headers from the network connection until the handler code explicitly tries to access them. The `net/http` server hands the SPDY handler the request object before the headers are parsed.

**The Parsing Failure**: The very first action of the handler, inside `createSPDYServerStreams`, is to call `httpstream.Handshake`. This function immediately needs to inspect the request's headers to find `X-Stream-Protocol-Version`. This access forces the lazy parsing mechanism to execute. However, because it is operating on the "dirty" object with its inconsistent internal state, the parsing logic fails silently or incompletely. The `req.Header` map is left empty.

**The Correct Rejection**: The Handshake function inspects the now-empty header map, fails to find the required protocol version, and correctly returns the unable to upgrade error, causing the test to fail.

Possibly related golang issue (from 2017): https://github.com/golang/go/issues/19653

Any feedback on analysis and/or hypothesis appreciated.

**Comment by aojea** [comment]
it seems impacting only 1.34 https://storage.googleapis.com/k8s-triage/index.html?text=TestStreamTranslator_TTYResizeChannel&test=k8s.io%2Fapiserver%2Fpkg%2Futil ?

**Comment by seans3** [comment]
> it seems impacting only 1.34 https://storage.googleapis.com/k8s-triage/index.html?text=TestStreamTranslator_TTYResizeChannel&test=k8s.io%2Fapiserver%2Fpkg%2Futil ?

I think the better search term for this particular error is: `X-Stream-Protocol-Version is required`.

https://storage.googleapis.com/k8s-triage/index.html?text=X-Stream-Protocol-Version%20is%20required&test=k8s.io%2Fapiserver%2Fpkg%2Futil

There are 10 flakes in the last two weeks across multiple k8s versions. The current hypothesis is that a rare condition is causing the `http.Request` to be corrupted for SPDY server handler because of the numerous test server creations/teardowns, since this happens for (almost) every test.

**Comment by Rajalakshmi-Girish** [comment]
Saw this recently again in UT jobs

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit/1971619988334710784
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit-ppc64le/1975028061535473664 with below error:
```
=== RUN   TestStreamTranslator_ErrorStream
E1006 03:17:04.421541   75197 conn.go:339] Error on socket receive: read tcp 127.0.0.1:40325->127.0.0.1:35806: use of closed network connection
    streamtranslator_test.go:364:  # HELP apiserver_stream_translator_requests_total [ALPHA] Total number of requests that were handled by the StreamTranslatorProxy, which processes streaming RemoteCommand/V5
         # TYPE apiserver_stream_translator_requests_total counter
         apiserver_stream_translator_requests_total{code="200"} 1
        -apiserver_stream_translator_requests_total{code="400"} 1
         
--- FAIL: TestStreamTranslator_ErrorStream (0.14s)
```

Below is the error on
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit/1971254828386488320 https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit-1-34/1971985650857021440 
```
error on createHTTPStreams: unable to upgrade: X-Stream-Protocol-Version is required
```

**(Once k8s Triage shows up-to-date information, more recent runs could be got)
Ref: https://kubernetes.slack.com/archives/C09QZ4DQB/p1759588595444979**

@aojea ^^

**Comment by seans3** [comment]
More context -- after adding more logging, we can see that all request headers are missing (not just stream version headers):
```
=== RUN   TestStreamTranslator_MultipleReadChannels
   streamtranslator_test.go:382: error on createHTTPStreams: unable to upgrade: header X-Stream-Protocol-Version does not exist in request with 0 headers
   streamtranslator_test.go:382: error on createHTTPStreams: unable to upgrade: header X-Stream-Protocol-Version does not exist in request with 0 headers
E1006 12:04:07.247316   79151 conn.go:339] Error on socket receive: read tcp 127.0.0.1:33841->127.0.0.1:41112: use of closed network connection
--- FAIL: TestStreamTranslator_MultipleReadChannels (0.23s)
```
