### ISSUE TITLE
[Failing test] [sig-k8s-infra] [sig-scalability] ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2.Overall

### ISSUE THREAD

**Issue by tico88612** [kubernetes/kubernetes#130849]
### Which jobs are failing?

- master-informing
  - ec2-master-scale-performance

### Which tests are failing?

- ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2.Overall
- kubetest2.Up

### Since when has it been failing?

- [2025-03-13 07:03:11 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2/1900079877021765632)

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#ec2-master-scale-performance

### Reason for failure (if possible)

```
Validating cluster scale-5000.periodic.test-cncf-aws.k8s.io
W0313 07:13:05.696714   53503 validate_cluster.go:190] (will retry): unexpected error during validation: error listing nodes: Get "https://api-scale-5000-periodic-t-t14mmj-a9acb5c91d820250.elb.us-east-2.amazonaws.com/api/v1/nodes": dial tcp 3.13.45.182:443: i/o timeout
W0313 07:14:35.697261   53503 validate_cluster.go:190] (will retry): unexpected error during validation: error listing nodes: Get "https://api-scale-5000-periodic-t-t14mmj-a9acb5c91d820250.elb.us-east-2.amazonaws.com/api/v1/nodes": dial tcp 3.13.45.182:443: i/o timeout
W0313 07:15:55.703757   53503 validate_cluster.go:190] (will retry): unexpected error during validation: error listing nodes: Get "https://api-scale-5000-periodic-t-t14mmj-a9acb5c91d820250.elb.us-east-2.amazonaws.com/api/v1/nodes": dial tcp 3.13.45.182:443: i/o timeout
W0313 07:16:55.716249   53503 validate_cluster.go:190] (will retry): unexpected error during validation: error listing nodes: Get "https://api-scale-5000-periodic-t-t14mmj-a9acb5c91d820250.elb.us-east-2.amazonaws.com/api/v1/nodes": dial tcp 3.13.45.182:443: connect: connection refused
W0313 07:17:55.754321   53503 validate_cluster.go:190] (will retry): unexpected error during validation: error listing nodes: Get "https://api-scale-5000-periodic-t-t14mmj-a9acb5c91d820250.elb.us-east-2.amazonaws.com/api/v1/nodes": dial tcp 3.13.45.182:443: connect: connection refused
```

```
2025/03/15 08:09:35 starting to dump 0 nodes fetched through the Kubernetes APIs
2025/03/15 08:09:35 dumping node not registered in kubernetes: 18.191.9.244
2025/03/15 08:09:35 Dumping node 18.191.9.244
2025/03/15 08:09:36 dumping node not registered in kubernetes: 3.144.33.234
2025/03/15 08:09:36 Dumping node 3.144.33.234
2025/03/15 08:09:38 dumping node not registered in kubernetes: 3.142.98.46
2025/03/15 08:09:38 Dumping node 3.142.98.46
2025/03/15 08:09:39 dumping node not registered in kubernetes: 18.119.127.177
2025/03/15 08:09:39 Dumping node 18.119.127.177
2025/03/15 08:09:41 dumping node not registered in kubernetes: 3.143.245.193
2025/03/15 08:09:41 Dumping node 3.143.245.193
```

### Anything else we need to know?

It seems like an infra problem (`connect: connection refused`)
Please correct me if I've made a mistake.

### Relevant SIG(s)

/sig k8s-infra
@kubernetes/release-team-release-signal

**Comment by mengqiy** [comment]
It seems there are some problem during cluster creation. We will investigate it

**Comment by dims** [comment]
fixed with https://github.com/kubernetes/kops/pull/17318

**Comment by tico88612** [comment]
<img width="696" alt="Image" src="https://github.com/user-attachments/assets/1ed1af82-678d-43e0-8d36-7000ae730815" />

The latest test result is still failing.

/reopen

**Comment by stmcginnis** [comment]
@dims is this still an issue, and do you know who might be able to give an update?

**Comment by dims** [comment]
@stmcginnis let's please reach out to @mengqiy and @hakuna-matatah

**Comment by stmcginnis** [comment]
@mengqiy and @hakuna-matatah, if either of you can also confirm whether this is a blocker for tomorrow's (Tuesday April 8) RC 0 cut, that would be appreciated. Thanks!

**Comment by dims** [comment]
@hakuna-matatah thanks and i agree, not a blocker.

**Comment by hakuna-matatah** [comment]
I confirmed from internal tools that we don't have `r6i.24xlarge` currently in `us-east-2a`, capacity constrained on that instance type.

<img width="513" alt="Image" src="https://github.com/user-attachments/assets/5abd0397-7f67-49aa-9d6e-6d449463af93" />

**Comment by mengqiy** [comment]
We should allow the cluster control plane to be brought up with more than 1 instance types. This will reduce the flakiness caused by single instance type capacity issue.

**Comment by dims** [comment]
we have 2 in a row now

![Image](https://github.com/user-attachments/assets/0ea7710f-1d8a-4749-9f25-3ca2b0b5f641)

after https://github.com/kubernetes/test-infra/pull/34648 landed

**Comment by wendy-ha18** [comment]
Hi everyone, this test is currently failing again, with Prow [here](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2/1921822981189799936)

![Image](https://github.com/user-attachments/assets/00c41e09-a44a-4143-9aa9-896eb76126bf)

**Comment by wendy-ha18** [comment]
The release cycle for v1.32 will start soon and since this is still failing, I will carry it over to the latest milestone.

/milestone v1.34

**Comment by hakuna-matatah** [comment]
It looks like the latest [test](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2/1921822981189799936) is failing for a different reason than past.

It seems to be failing because of `insufficient EBS volume capacity` 

```
Error: error running tasks: deadline exceeded executing task EBSVolume/c.etcd-main.scale-5000.periodic.test-cncf-aws.k8s.io. Example error: error creating PersistentVolume: operation error EC2: CreateVolume, exceeded maximum number of attempts, 13, https response error StatusCode: 500, RequestID: 46cd37d5-5b65-441f-9421-8030437166d4, api error InsufficientVolumeCapacity: There is currently insufficient volume capacity to serve the request. Try again at a later time or in a different availability zone
```

**Comment by hakuna-matatah** [comment]
@wendy-ha18 this [PR](https://github.com/kubernetes/kops/pull/17405) should help fix the EBS io2 capacity issue that was resulting in failures. We can monitor for next 3 runs before closing this issue.

**Comment by wendy-ha18** [comment]
That's great, thanks @hakuna-matatah!

**Comment by Rajalakshmi-Girish** [comment]
@hakuna-matatah ^^

**Comment by Swizzmaster** [comment]
Commit here that removed the flag https://github.com/kubernetes/kubernetes/pull/130161

**Comment by hakuna-matatah** [comment]
@Rajalakshmi-Girish I have asked my teammate to follow up on this, @Swizzmaster is digging into this ^^^


@Swizzmaster thank you, that requires a code fix.

**Comment by Swizzmaster** [comment]
merged https://github.com/kubernetes/kops/pull/17412

The merge was slightly after the kick off of the scale tests so they did fail last night however both the kops-aws-arm64 tests kicked off after the merge and both passed after the update.

**Comment by Rajalakshmi-Girish** [comment]
@Swizzmaster @hakuna-matatah Yes I see the job stopped failing. Passed since last five runs.
Thanks!

![Image](https://github.com/user-attachments/assets/122c838a-fdbe-406d-9516-610609b33b46)
