### ISSUE TITLE
Failing test: ProcMount [LinuxOnly] [Feature:ProcMountType] [Feature:UserNamespacesSupport] will unmask proc mounts if requested

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#132501]
##### Error text:
```
[FAILED] Expected
    <int>: 8
to equal
    <int>: 1
In [It] at: k8s.io/kubernetes/test/e2e_node/proc_mount_test.go:119 @ 06/11/25 17:00:30.952

```
#### Recent failures:
[6/23/2025, 12:49:53 PM ci-crio-cgroupv2-userns-e2e-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-crio-cgroupv2-userns-e2e-serial/1937191262461366272)
[6/22/2025, 12:50:03 PM ci-crio-cgroupv2-userns-e2e-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-crio-cgroupv2-userns-e2e-serial/1936828870732812288)
[6/21/2025, 12:49:44 PM ci-crio-cgroupv2-userns-e2e-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-crio-cgroupv2-userns-e2e-serial/1936466479557906432)
[6/20/2025, 12:49:49 PM ci-crio-cgroupv2-userns-e2e-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-crio-cgroupv2-userns-e2e-serial/1936104087573499904)
[6/19/2025, 12:49:49 PM ci-crio-cgroupv2-userns-e2e-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-crio-cgroupv2-userns-e2e-serial/1935741696495063040)

/kind failing-test

/sig node

**Comment by haircommander** [comment]
fixed by https://github.com/cri-o/cri-o/pull/9285

**Comment by kannon92** [comment]
@haircommander is a cri-o bump on your radar so we can completely fix this?

**Comment by kannon92** [comment]
https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv2-userns-e2e-serial

Looks like crio bump didn’t fix this.

**Comment by haircommander** [comment]
crio bump hasn't finished yet, I just did the canary build. I have opened https://github.com/kubernetes/test-infra/pull/35149 as the canary jobs are faliing on some tests that may need more investigation
