### ISSUE TITLE
sessionAffinity lost with GCE LoadBalancer when RC is recreated after service

### ISSUE THREAD

**Issue by FibHeap** [kubernetes/kubernetes#13299]
It seems like the sessionAffinity stops working if the rc is deleted and created again after the service was created.  (Cluster with two machines on GCE)

Steps to reproduce:

 - 1) Used following files:

ServerName.yaml

    apiVersion: v1
    kind: ReplicationController
    metadata:
      name: servername
      labels:
        name: servername
    spec:
      replicas: 10
      selector:
        name: servername
      template:
        metadata:
          labels:
            name: servername
        spec:
          containers:
          - name: app
            image:  fibheap/printhostname
            imagePullPolicy: "Always"
            ports:
                 - containerPort: 80

ServerNameSv.yaml

    apiVersion: v1
    kind: Service
    metadata:
      name: servername
      labels:
        name: servername
    spec:
      ports:
        # the port that this service should serve on
        - port: 80
          targetPort: 80
      selector:
        name: servername
      type: LoadBalancer
      sessionAffinity: ClientIP

Dockerfile

    FROM google/nodejs

    WORKDIR /app

    ADD ./main.js /app/main.js

    EXPOSE 80
    CMD ["node", "--harmony", "./main.js"]

main.js

    // Load the http module to create an http server.
    var http = require('http');
    var os = require('os');

    // Configure our HTTP server to respond with Hello World to all requests.
    var server = http.createServer(function (req, res) {
      res.writeHead(200, {"Content-Type": "text/plain"});
      var ip = req.headers['x-forwarded-for'] ||
         req.connection.remoteAddress ||
         req.socket.remoteAddress ||
         req.connection.socket.remoteAddress;

      res.end("CIP:" + ip + "  Remote Server:" + os.hostname());
    });

    // Listen on port 8000, IP defaults to 127.0.0.1
    server.listen(80);

    // Put a friendly message on the terminal
    console.log("Server running at http://127.0.0.1:80/");

---

- 2) create rc and service (describe service to get IP and assure ClientIP is set) 

- 3) curl multiple times from loadbalancer ip -> pod name should stay the same

- 4) delete rc and create again

- 5) curl again multiple time -> pod name changes

This is in particularly a show stoping bug for us as we cannot recreate the service without loosing the external IP. #10323 

Please let me know if that helps for reproducing. Please feel free to use docker repository fibheap/printhostname directly

**Comment by bprashanth** [comment]
to help with debugging can you confirm that the target pool associated with your loadbalancer has session affinity? (you can do this through the console or gcloud)

**Comment by FibHeap** [comment]
Yes ClientIP is set in the TargetPool. Also let me point out that we have two nodes in the target pool. 

Also it seems to work when doing a roling update but not if the rc is deleted and recreated.

**Comment by bnadim** [comment]
I confirm, we have the same issue on our environnement.

**Comment by spiddy** [comment]
I confirm, I can reproduce the same issue.

**Comment by spiddy** [comment]
Also seems to work when pods are stopped manually (stopped the pod where my IP was sending traffic and the sticky session redirected me consistently to another pod afterwards). Also RC replace is possible without triggering this issue (basically what the rolling update does).

**Comment by thockin** [comment]
I honestly am stumped by this.  I can not reproduce at head:

```
$ k run hostnames --image=gcr.io/google_containers/serve_hostname:1.3 --replicas=5
deployment "hostnames" created

$ k expose deployment hostnames --port=80 --target-port=9376 --type=LoadBalancer --session-affinity=ClientIP
service "hostnames" exposed

$ k get svc hostnames -o yaml | grep loadBalancer -A 4
  loadBalancer:
    ingress:
    - ip: 108.59.82.253

$ for i in `seq 1 100`; do curl -s 108.59.82.253; echo; done | sort | uniq -c
    100 hostnames-3512299341-6jmxk

k scale deployment hostnames --replicas=0
deployment "hostnames" scaled

$ curl 108.59.82.253
curl: (7) Failed to connect to 108.59.82.253 port 80: Connection refused

$ k scale deployment hostnames --replicas=5
deployment "hostnames" scaled

$ for i in `seq 1 100`; do curl -s 108.59.82.253; echo; done | sort | uniq -c
    100 hostnames-3512299341-bvxri
```


So this is either fixed at head or there's SOMETHING else happening.  Can someone who sees this bug try a head cluster (1.2 alpha)?

**Comment by thockin** [comment]
In fact, I will leave the LB up for a while - go ahead and try it against my head cluster.

**Comment by spiddy** [comment]
Well I followed your steps, and I still get the issue. My env is GCE and server is v1.1.8

```
› k version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.8", GitCommit:"a8af33dc07ee08defa2d503f81e7deea32dd1d3b", GitTreeState:"clean"}
```

```
› for i in `seq 1 100`; do curl -s 104.155.87.190; echo; done | sort | uniq -c
  20 hostnames-7h3tu
  20 hostnames-l6c13
  20 hostnames-t8uns
  20 hostnames-wcoq7
  20 hostnames-wlwav
```

**Comment by thockin** [comment]
If you try it against my LB (108.59.82.253) what happens?

Can you also `kubectl get svc -o yaml` and look at the load-balancer in
gcloud and check the affinity?

Can you also tell me which proxy-mode you are in (userspace or iptables)
and/or run `iptables-save` on a node (any node) for me?

**Comment by spiddy** [comment]
I did try your LB back then and it worked fine  (sticking to one instance).

How can I know which proxy-mode I'm using (userspace or iptables)?

**Comment by thockin** [comment]
Simplest answer is to look at logs or iptables-save.  If you see lines like
"KUBE-SVC-F39DEA35866", you're in iptables.

**Comment by spiddy** [comment]
I see "KUBE-SVC-..." lines in my environment, so I'm using iptables. Unfortunately I don't have the previous environment anymore and the current one is production which I can't expose the iptables-save here.

I'll test it with K8S 1.2 to see if the regression disappears and get back to you.

**Comment by thockin** [comment]
If you can still reproduce this, you can send me your iptables-save
privately (my username at google.com) or you can redact the public IPs if
you want.

**Comment by thockin** [comment]
And if you can't reproduce, I'd be happy to see this issues closed :)

**Comment by bnadim** [comment]
I am running a cluster on kubernetes 1.2.1 through google container engine and this isn't fixed

**Comment by bnadim** [comment]
I sent you by email our iptables-save content

**Comment by bnadim** [comment]
Ok, my bad i made some additional test today and it seems to work properly. In days to come i will make more test and confirm that it's now working with kubernetes 1.2 or not.

Thank you

**Comment by thockin** [comment]
Thanks.  I'm relieved because I can not see how this would be happening.  Please reopen if needed.

**Comment by njuicsgz** [comment]
@thockin 
I got similar problem without to use a LB, so I think we can reopen this issue.

**Reproduce steps**
1. create a RC with size=2
2. create a Service with session affinity = ClientIP
==> then you will find session affinity is not work.
```
$for i in `seq 1 100`; do curl -s 10.0.10.239:40001; echo; done | sort | uniq -c
    100 
     50 gkt-content-web-test-8kc59
     50 gkt-content-web-test-lgbmf
```
3. delete the service, and recreate again
===> then session affinity works.
```
$for i in `seq 1 100`; do curl -s 10.0.10.239:40001; echo; done | sort | uniq -c
    100 
    100 gkt-content-web-test-lgbmf

```
4. scale RC down to size=0 and then reset to 2.
===> session affinity is also break

```
# kubectl scale rc gkt-content-web-test --replicas=0 --namespace=gkt-content
replicationcontroller "gkt-content-web-test" scaled

root@paas-185 ~/allen/test/nginx_term
# kubectl scale rc gkt-content-web-test --replicas=2 --namespace=gkt-content
replicationcontroller "gkt-content-web-test" scaled

root@paas-185 ~/allen/test/nginx_term
# for i in `seq 1 100`; do curl -s 10.0.10.239:40001; echo; done | sort | uniq -c
    100 
     50 gkt-content-web-test-fi4tf
     50 gkt-content-web-test-pdcma
```

**Some output**
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}

$ kubectl describe service gkt-content-service --namespace=gkt-content -
Name:                   gkt-content-service
Namespace:              gkt-content
Labels:                 name=gkt-content-service
Selector:               name=gkt-content-web
Type:                   ClusterIP
IP:                     10.0.10.239
Port:                   <unset> 40001/TCP
Endpoints:              10.10.51.10:8080,10.10.56.10:8080
Session Affinity:       ClientIP
No events.

$ kubectl get 
get po --namespace=gkt-content
NAME                         READY     STATUS    RESTARTS   AGE
gkt-content-web-test-5j9o7   1/1       Running   0          10m
gkt-content-web-test-y3lab   1/1       Running   0          10m

**Comment by njuicsgz** [comment]
so we cannot do rolling update with service unchanged, and must create RC before Service.

**Comment by njuicsgz** [comment]
Got something useful.

When I create a Service with no endpoints:
```
I0425 18:47:29.065100   26627 roundrobin.go:99] LoadBalancerRR service "gkt-content/gkt-content-service:" did not exist, created
I0425 18:47:29.081761   26627 config.go:99] Calling handler.OnEndpointsUpdate()
I0425 18:47:29.081850   26627 roundrobin.go:281] LoadBalancerRR: Removing endpoints for gkt-content/gkt-content-service:
```

And when I scale RC size=0 for a Service:
```
I0425 18:53:32.393569   26627 config.go:99] Calling handler.OnEndpointsUpdate()
I0425 18:53:32.393692   26627 roundrobin.go:263] LoadBalancerRR: Setting endpoints for gkt-content/gkt-content-service: to [10.10.56.17:8080]
I0425 18:53:32.393755   26627 roundrobin.go:220] Delete endpoint 10.10.51.15:8080 for service "gkt-content/gkt-content-service:"
I0425 18:53:32.863034   26627 config.go:99] Calling handler.OnEndpointsUpdate()
I0425 18:53:32.863123   26627 roundrobin.go:281] LoadBalancerRR: Removing endpoints for gkt-content/gkt-content-service:
```
It deleted the sessionAffinity service of lb in kube-proxy on above 2 case. At this time, if we increase RC size from 0, new service will be created without sessionAffinity.

So the proposal is that never delete service instance of lb while there is no endpoint for this service.

**Comment by njuicsgz** [comment]
Verified with above 'Reproduce steps'.

**Comment by njuicsgz** [comment]
Could anyone comments on this? Or I need open another issue to trace this problem.
@thockin @bprashanth @bnadim

**Comment by njuicsgz** [comment]
I have opened  a new issue to trace it #25314
