### ISSUE TITLE
AWS Nodes Go NotReady

### ISSUE THREAD

**Issue by barrettclark** [kubernetes/kubernetes#13997]
I'm running k8s on AWS.  `kube-up.sh` works, and I can run a simple Rails app (controller and service).  Everything is great, but when I go back the next day to access the app or load a new version the nodes have degraded and are all `NotReady`

```
$ kubectl get nodes
NAME                                         LABELS                                                              STATUS
ip-172-20-0-196.us-west-2.compute.internal   kubernetes.io/hostname=ip-172-20-0-196.us-west-2.compute.internal   NotReady
ip-172-20-0-197.us-west-2.compute.internal   kubernetes.io/hostname=ip-172-20-0-197.us-west-2.compute.internal   NotReady
ip-172-20-0-198.us-west-2.compute.internal   kubernetes.io/hostname=ip-172-20-0-198.us-west-2.compute.internal   NotReady
ip-172-20-0-199.us-west-2.compute.internal   kubernetes.io/hostname=ip-172-20-0-199.us-west-2.compute.internal   NotReady
```

The pods are `Pending`

```
$ kubectl get pods
NAME                           READY     STATUS    RESTARTS   AGE
chronic-controller-16uic       0/1       Pending   0          6h
chronic-controller-6x025       0/1       Pending   0          1h
chronic-controller-x7owf       0/1       Pending   0          6h
private-registry-pbvdi         0/1       Pending   0          6h
tripplanner-controller-3q6km   0/1       Pending   0          6h
tripplanner-controller-bhwwy   0/1       Pending   0          1h
tripplanner-controller-fdep8   0/1       Pending   0          6h
```

Here are the recent events:
```
$ kubectl get events
FIRSTSEEN                         LASTSEEN                          COUNT     NAME                                         KIND      SUBOBJECT   REASON             SOURCE                                                 MESSAGE
Sat, 12 Sep 2015 22:44:10 -0500   Tue, 15 Sep 2015 15:04:08 -0500   44        ip-172-20-0-199.us-west-2.compute.internal   Node                  NodeNotReady       {kubelet ip-172-20-0-199.us-west-2.compute.internal}   Node ip-172-20-0-199.us-west-2.compute.internal status is now: NodeNotReady
Mon, 14 Sep 2015 09:24:35 -0500   Tue, 15 Sep 2015 15:22:41 -0500   7531      chronic-controller-ljzn6                     Pod                   failedScheduling   {scheduler }                                           no nodes available to schedule pods
Mon, 14 Sep 2015 09:24:35 -0500   Tue, 15 Sep 2015 15:22:41 -0500   7757      private-registry-ysjfj                       Pod                   failedScheduling   {scheduler }                                           no nodes available to schedule pods
Mon, 14 Sep 2015 09:24:35 -0500   Tue, 15 Sep 2015 15:22:42 -0500   7284      tripplanner-controller-7b0yr                 Pod                   failedScheduling   {scheduler }                                           no nodes available to schedule pods
Mon, 14 Sep 2015 09:24:35 -0500   Tue, 15 Sep 2015 15:22:42 -0500   7413      tripplanner-controller-s86wz                 Pod                   failedScheduling   {scheduler }                                           no nodes available to schedule pods
Mon, 14 Sep 2015 09:24:35 -0500   Tue, 15 Sep 2015 15:22:42 -0500   7374      chronic-controller-f2nrx                     Pod                   failedScheduling   {scheduler }                                           no nodes available to schedule pods
Mon, 14 Sep 2015 09:24:35 -0500   Tue, 15 Sep 2015 15:22:42 -0500   7447      chronic-controller-j4538                     Pod                   failedScheduling   {scheduler }                                           no nodes available to schedule pods
Mon, 14 Sep 2015 01:42:38 -0500   Tue, 15 Sep 2015 15:22:42 -0500   9303      tripplanner-controller-04ztj                 Pod                   failedScheduling   {scheduler }                                           no nodes available to schedule pods
```

I logged into the master and one of the minions to look at `/var/log/kubelet.log` but that file doesn't exist on those hosts.  Trying to ssh into one of the AWS instances is also spotty for me, but the EC2 instances all claim to be up and healthy.

I have killed everything with `kube-down.sh` and built it all again.  Everything worked for the afternoon and then was down again the next morning.  I don't know what else to look at or do.  I'm happy to look at things.  I'm @barrettclark in the slack channel.

**Comment by justinsb** [comment]
Sorry about the problem.

We do have an issue where disk space with small machines is very limited, and doubly so with aufs.  If you can get into one of the minions, do you think you could check to see if the disk filled up (`df -h`)?  I have a fix which I believe merged to master but I think I'm going to propose it for a 1.0 cherry-pick, particularly if it was the problem here.

We're using systemd by default, so the logs are in `systemctl status -l kubelet` and `journalctl -u kubelet`

**Comment by barrettclark** [comment]
I just created a new cluster and will keep an eye on it.  CPU usage on the master is really high, but disk space is OK for now.

![screen shot 2015-09-16 at 11 24 28 am](https://cloud.githubusercontent.com/assets/41442/9911088/09abf2d6-5c66-11e5-9040-665531646b4f.png)

**Comment by mikedanese** [comment]
cc @brendandburns

**Comment by barrettclark** [comment]
Perhaps related: I have an app on ElasticBeanstalk, and the 2 most recent updates that I have tried to push have failed.  Prior to that is this warning:

```
The following instances have not responded in the allowed command timeout time (they might still finish eventually on their own): [i-c736b112].
```

I can ssh into the instance, and there is plenty of disk space.  Is k8s using EB for AWS under the covers?

**Comment by barrettclark** [comment]
Everything is still running this morning.  Here is the current dashboard:

![screen shot 2015-09-17 at 7 30 18 am](https://cloud.githubusercontent.com/assets/41442/9933082/072a3682-5d0e-11e5-8aa7-79456c8263ce.png)

I did pull the k8s source again (`wget -q -O - https://get.k8s.io | bash`) before spinning that cluster up in case there had been any updates.

**Comment by barrettclark** [comment]
I've lost access to the master. The EC2 instance is still running, but I can't SSH into it.  The app that I pushed yesterday is still responding. I can't get any info on it though. `kubectl` gets a `TLS handshake timeout`.

**Comment by justinsb** [comment]
Ouch.  Can you see if there is anything in the EC2 console output: http://docs.aws.amazon.com/cli/latest/reference/ec2/get-console-output.html

I am surprising this is happening on the master - that would point away from disk space.  Are you using kube-up or something else?

**Comment by barrettclark** [comment]
The master ran out of memory.  Here is a section of the log from where we think the master tripped offline `cat /var/log/syslog | grep -v level.info | more`:

```
Sep 17 14:00:59 ip-172-20-0-9 dhclient: DHCPREQUEST of 172.20.0.9 on eth0 to 172.20.0.1 port 67 (xid=0x291dfc9c)
Sep 17 14:01:22 ip-172-20-0-9 dhclient: DHCPACK of 172.20.0.9 from 172.20.0.1
Sep 17 14:13:24 ip-172-20-0-9 dhclient: bound to 172.20.0.9 -- renewal in 1136 seconds.
Sep 17 14:40:50 ip-172-20-0-9 dhclient: DHCPREQUEST of 172.20.0.9 on eth0 to 172.20.0.1 port 67 (xid=0x291dfc9c)
Sep 17 14:41:00 ip-172-20-0-9 dhclient: DHCPREQUEST of 172.20.0.9 on eth0 to 172.20.0.1 port 67 (xid=0x291dfc9c)
Sep 17 14:41:25 ip-172-20-0-9 dhclient: DHCPACK of 172.20.0.9 from 172.20.0.1
Sep 17 14:43:35 ip-172-20-0-9 systemd[1]: Starting Cleanup of Temporary Directories...
Sep 17 14:46:51 ip-172-20-0-9 CRON[22101]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Sep 17 14:49:13 ip-172-20-0-9 dhclient: bound to 172.20.0.9 -- renewal in 900 seconds.
Sep 17 14:54:41 ip-172-20-0-9 salt-minion[14007]: [ERROR   ] Unhandled exception running mine.update
Sep 17 14:55:42 ip-172-20-0-9 salt-minion[14007]: Traceback (most recent call last):
Sep 17 14:55:42 ip-172-20-0-9 salt-minion[14007]: File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 421, in handle_func
Sep 17 14:55:42 ip-172-20-0-9 salt-minion[14007]: ret['return'] = self.functions[func]()
Sep 17 14:55:42 ip-172-20-0-9 salt-minion[14007]: File "/usr/lib/python2.7/dist-packages/salt/modules/mine.py", line 99, in update
Sep 17 14:55:42 ip-172-20-0-9 salt-minion[14007]: load['tok'] = _auth().gen_token('salt')
Sep 17 14:55:42 ip-172-20-0-9 salt-minion[14007]: File "/usr/lib/python2.7/dist-packages/salt/modules/mine.py", line 25, in _auth
Sep 17 14:55:42 ip-172-20-0-9 salt-minion[14007]: __context__['auth'] = salt.crypt.SAuth(__opts__)
Sep 17 14:55:42 ip-172-20-0-9 salt-minion[14007]: File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 805, in __init__
Sep 17 14:55:42 ip-172-20-0-9 salt-minion[14007]: self.crypticle = self.__authenticate()
Sep 17 14:55:42 ip-172-20-0-9 salt-minion[14007]: File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 826, in __authenticate
Sep 17 14:55:42 ip-172-20-0-9 salt-minion[14007]: self.opts.get('auth_tries', 1)
Sep 17 14:55:42 ip-172-20-0-9 salt-minion[14007]: File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 644, in sign_in
Sep 17 14:55:42 ip-172-20-0-9 salt-minion[14007]: raise SaltClientError('Attempt to authenticate with the salt master failed')
Sep 17 14:55:42 ip-172-20-0-9 salt-minion[14007]: SaltClientError: Attempt to authenticate with the salt master failed
Sep 17 14:55:49 ip-172-20-0-9 systemd-tmpfiles[22093]: [/usr/lib/tmpfiles.d/var.conf:14] Duplicate line for path "/var/log", ignoring.
Sep 17 14:58:04 ip-172-20-0-9 systemd[1]: Started Cleanup of Temporary Directories.
Sep 17 14:58:47 ip-172-20-0-9 systemd[1]: Time has been changed
Sep 17 14:58:47 ip-172-20-0-9 kubelet[17206]: I0917 13:52:06.106309   17206 kubelet.go:1740] Skipping pod synchronization, network is not configured
Sep 17 15:02:07 ip-172-20-0-9 dhclient: DHCPREQUEST of 172.20.0.9 on eth0 to 172.20.0.1 port 67 (xid=0x291dfc9c)
Sep 17 15:02:27 ip-172-20-0-9 dhclient: DHCPREQUEST of 172.20.0.9 on eth0 to 172.20.0.1 port 67 (xid=0x291dfc9c)
Sep 17 15:02:47 ip-172-20-0-9 dhclient: DHCPACK of 172.20.0.9 from 172.20.0.1
Sep 17 15:14:13 ip-172-20-0-9 dhclient: bound to 172.20.0.9 -- renewal in 811 seconds.
Sep 17 15:21:56 ip-172-20-0-9 CRON[22187]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Sep 17 15:22:31 ip-172-20-0-9 kubelet[17206]: I0917 14:58:50.355545   17206 container.go:369] Failed to update stats for container "/system/system.slice/docker-1d2119f0415897dca023510fb88ba5fc6c894f9f58a0
c773c97d15a38f3b9ffb.scope": du command failed on /var/lib/docker/aufs/diff/1d2119f0415897dca023510fb88ba5fc6c894f9f58a0c773c97d15a38f3b9ffb with output  - fork/exec /usr/bin/du: cannot allocate memory, c
ontinuing to push stats
Sep 17 15:26:43 ip-172-20-0-9 dhclient: DHCPREQUEST of 172.20.0.9 on eth0 to 172.20.0.1 port 67 (xid=0x291dfc9c)
Sep 17 15:27:28 ip-172-20-0-9 dhclient: DHCPREQUEST of 172.20.0.9 on eth0 to 172.20.0.1 port 67 (xid=0x291dfc9c)
Sep 17 15:28:54 ip-172-20-0-9 dhclient: DHCPACK of 172.20.0.9 from 172.20.0.1
Sep 17 15:46:26 ip-172-20-0-9 dhclient: bound to 172.20.0.9 -- renewal in 701 seconds.
Sep 17 15:59:58 ip-172-20-0-9 dhclient: DHCPREQUEST of 172.20.0.9 on eth0 to 172.20.0.1 port 67 (xid=0x291dfc9c)
Sep 17 16:03:54 ip-172-20-0-9 dhclient: DHCPREQUEST of 172.20.0.9 on eth0 to 172.20.0.1 port 67 (xid=0x291dfc9c)
Sep 17 16:08:17 ip-172-20-0-9 dhclient: DHCPACK of 172.20.0.9 from 172.20.0.1
Sep 17 17:17:04 ip-172-20-0-9 rsyslogd: [origin software="rsyslogd" swVersion="7.4.4" x-pid="627" x-info="http://www.rsyslog.com"] start
Sep 17 17:17:04 ip-172-20-0-9 rsyslogd-2307: warning: ~ action is deprecated, consider using the 'stop' statement instead [try http://www.rsyslog.com/e/2307 ]
Sep 17 17:17:04 ip-172-20-0-9 rsyslogd: rsyslogd's groupid changed to 110
Sep 17 17:17:04 ip-172-20-0-9 rsyslogd: rsyslogd's userid changed to 104
Sep 17 17:17:04 ip-172-20-0-9 kernel: [    0.000000] Initializing cgroup subsys cpuset
Sep 17 17:17:04 ip-172-20-0-9 kernel: [    0.000000] Initializing cgroup subsys cpu
```

**Comment by barrettclark** [comment]
I spun up a new cluster using larger instances.  Interesting that the fs on one of minions is now full:

![screen shot 2015-09-18 at 11 34 49 am](https://cloud.githubusercontent.com/assets/41442/9965042/72f782e8-5df9-11e5-8634-0930820e7937.png)

```
ubuntu@ip-172-20-0-205:~$ df -h
Filesystem                            Size  Used Avail Use% Mounted on
udev                                  3.7G     0  3.7G   0% /dev
tmpfs                                 748M   75M  674M  10% /run
/dev/xvda1                            7.8G  1.6G  5.8G  22% /
tmpfs                                 3.7G  584K  3.7G   1% /dev/shm
tmpfs                                 5.0M     0  5.0M   0% /run/lock
tmpfs                                 3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/mapper/vg--ephemeral-docker       30G  2.9G   25G  11% /mnt/ephemeral/docker
/dev/mapper/vg--ephemeral-kubernetes  1.4G  1.4G     0 100% /mnt/ephemeral/kubernetes
tmpfs                                 748M     0  748M   0% /run/user/1000
```

Everything is still responsive (as far as I can tell).

**Comment by justinsb** [comment]
Thanks for confirming ... the full disk is fixed in #13803 but I need to cherry pick it to 1.0.

I was also able to reproduce the memory problems on the master by launching with t2.micros.  I think it might be the salt-master, or at least the salt-master isn't helping things: #14238

**Comment by dchen1107** [comment]
@justinsb I don't think there is memory issue on the node, instead, we are hitting NOFILE limit for kubelet process. I have a pending pr https://github.com/kubernetes/kubernetes/pull/14381 to resolve the issue.

**Comment by harai** [comment]
I have the same problem on my AWS cluster, which consists of t2.micro EC2 instances.

The master and nodes often get unresponsive.  When it happens, over 90% of the CPU time is spent on IO wait and no idle time remains.

The version is 1.0.7.

**Comment by paralin** [comment]
@dchen1107 So would that be a file descriptor limit?

**Comment by rroopreddy** [comment]
Ok, I am running int the same scenario as in this thread. I have been starting the cluster every day from scratch. Some of this has been covered in the thread at : http://stackoverflow.com/questions/33068639/kubernetes-pods-some-die-after-running-for-a-day

As if today one of the Minion went to 'NotReady' state and there is no way to recover it except for restarting the whole cluster from scratch. The following is the data from todays crash

$ ./cluster/kubectl.sh get nodes
      NAME                                         LABELS                                                              STATUS
      ip-xxx-20-0-253.us-west-2.compute.internal   kubernetes.io/hostname=ip-xxx-20-0-253.us-west-2.compute.internal   NotReady
      ip-xxx-20-0-254.us-west-2.compute.internal   kubernetes.io/hostname=ip-xxx-20-0-254.us-west-2.compute.internal   Ready
      ip-xxx-20-0-4.us-west-2.compute.internal     kubernetes.io/hostname=ip-xxx-20-0-4.us-west-2.compute.internal     Ready
      
$ ./cluster/kubectl.sh describe node ip-172-20-0-253.us-west-2.compute.internal
      Name:			ip-172-20-0-253.us-west-2.compute.internal
      Labels:			kubernetes.io/hostname=ip-xxx-20-0-253.us-west-2.compute.internal
      CreationTimestamp:	Sun, 01 Nov 2015 16:03:19 +0000
      Conditions:
        Type		Status	LastHeartbeatTime			LastTransitionTime			Reason					Message
        Ready 	False 	Wed, 04 Nov 2015 17:55:30 +0000 	Wed, 04 Nov 2015 16:25:56 +0000 	network not configured correctly 	
      Addresses:	172.20.0.253,172.20.0.253,52.32.115.34
      Capacity:
       cpu:		2
       memory:	7658424Ki
       pods:		40
      Version:
       Kernel Version:		3.19.0-20-generic
       OS Image:			Ubuntu 15.04
       Container Runtime Version:	docker://1.6.0
       Kubelet Version:		v1.0.7
       Kube-Proxy Version:		v1.0.7
      PodCIDR:			10.244.0.0/24
      ExternalID:			i-5edc6e9a
      Pods:				(0 in total)
        Namespace			Name
      No events.

**Comment by dchen1107** [comment]
@paralin my pr #13997 was merged and will be included in release 1.1. The default value of flag --max-open-files is 1000000.

**Comment by dchen1107** [comment]
@rroopreddy The reason of NotReady is "network not configured correctly". What are the flags for your kubelet? What are the flags for your docker on the node? 

Also I am curious about why you create cluster everyday from scratch?

**Comment by rroopreddy** [comment]
I have to kill and restart the entire cluster because one of the node in the cluster gets into the 'NotReady' state and I could not figure out a way to restart it and reconstitute the pods that were running to it before. I would be interested if there is a way to restore from one minion "NotReady' state

The following are the environment variables I used to start 3-minion cluster on AWS

        export KUBERNETES_PROVIDER=aws
        export KUBE_AWS_ZONE=us-west-2a

        export AWS_S3_REGION=us-west-2a
        export AWS_S3_BUCKET=test-kubernetes-artifacts
        export AWS_DEFAULT_PROFILE=test-kubernetes

        export NUM_MINIONS=3
        export MINION_SIZE=m3.large
        export KUBE_AWS_INSTANCE_PREFIX=clftest-kub
        export ENABLE_CLUSTER_MONITORING=none

        ./cluster/kube-up.sh

**Comment by paralin** [comment]
@rroopreddy You can fix this by sshing into the node and restarting kubelet. That should fix it I think

**Comment by rroopreddy** [comment]
Would that be following on that node? I will try it next time

             systemctl start kublet

**Comment by paralin** [comment]
@rroopreddy Try

```
systemctl restart kubelet
```

Or if you're on Ubuntu server

```
sudo service kubelet restart
```

Should work too. I had a problem earlier with the kubelet crashing instantly that I solved by stopping it and waiting a minute before starting it again.

**Comment by drora** [comment]
just deployed kube release v1.1.1 on t2.medium instances with 32gb ebs
minion-nodes started to fail in less then 24hrs while their EBS was almost full.
this issue is NOT solved in 1.1.1

"NodeNotReady :: OutOfDisk  KubeletHasSufficientDisk  kubelet has sufficient disk space available"
"df -h" ::
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       32G  7.5G   23G  25% /

**Comment by MartinPodval** [comment]
I've have same problem. On vmware machines.

```
core@mpavmcore05 ~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           4.0G     0  4.0G   0% /dev/shm
tmpfs           4.0G  520K  4.0G   1% /run
tmpfs           4.0G     0  4.0G   0% /sys/fs/cgroup
/dev/sda9        27G   11G   15G  43% /
/dev/sda4       985M  515M  420M  56% /usr
/dev/sda1       128M   64M   65M  50% /boot
tmpfs           4.0G     0  4.0G   0% /tmp
tmpfs           4.0G     0  4.0G   0% /media
/dev/sda6       108M  8.8M   91M   9% /usr/share/oem
```

**Comment by brendandburns** [comment]
@MartinPodval can you grab /var/log/kubelet.log (or journalctl -u kubelet.service) and send the gist?

Thanks
(and sorry for the show response)

**Comment by MartinPodval** [comment]
@brendandburns I have never met this issue again. I'll attach the kubelet log in the case of next occurrence.

**Comment by mikedanese** [comment]
From slack today:

> Hey, I've been following the guide at http://kubernetes.io/v1.1/docs/getting-started-guides/aws.html for running k8s on aws, but after a day (happened 3 times already) everything becomes slow and unresponsive. Today I can't even ssh into my minions anymore, kubectl times out, ssh into master still works, kubectl on master just hangs.... and I'm not even deploying anything yet (pods, services), just getting a feel for k8s.  EC2 dashboard says my master and minions are still running and havent been restarted or anything either.

**Comment by mikedanese** [comment]
Is anyone aware of what could have changed to fix this? Do we need to cherry-pick anything into release-1.1?

**Comment by Logician** [comment]
Also (I was the poster to slack) the node status in the kube-ui said (if I remember correctly) "OutOfDiskReady" which I assumed to be a bug with the status messages and it meant to be "Ready".

I've done it about 3-4 times and it always degraded after a day, one of the times it actually never came up correctly and timed out at the salt stage for the master before starting the minions.

**Comment by Logician** [comment]
I have a cluster running t2.small instances (with 2 gb of memory opposed to the 1gb of t2.micro) already up for over 2 full days without issues.

**Comment by justinsb** [comment]
I believe there are a number of problems in here, that cause nodes to go NotReady.

As a tip, when a Node goes not ready, if you determine the AWS instance id by doing `kubectl get nodes <node-name> -ojson` you can then terminate the instance and - because the nodes are in an auto-scaling group - it will be replaced automatically.  I have heard of some people that pre-emptively kill their nodes each night, which should obviously not be required but is an interesting way to pre-empt all these problems (it reminds me of Chaos Monkey).

So why do Nodes go NotReady?  My belief is that the primary cause is that the disk fills up.  A t2.micro (the default) does not get launched with a lot of extra disk space.  Between influxdb & elastic search, the disks backing these fill up very quickly (https://github.com/kubernetes/kubernetes/issues/14274).  There is also a rather bad Docker bug (https://github.com/docker/docker/issues/14506), which will fill the disk, although I have personally only seen this with k8s 1.0, not 1.1.

Next, if the disk does fill up, aufs has a bug where then the filesystem will tend to go corrupted & read-only, and the node goes offline.  It seems to be impractical to recover the node at this point, and so I have always ended up terminating the node through the AWS API.  But if you check `dmesg` in this situation, you should see lots of messages about the filesystem being corrupted.

btrfs also has a famous bug/issue where it will reach a state where files cannot be deleted: https://btrfs.wiki.kernel.org/index.php/FAQ#Help.21_I_ran_out_of_disk_space.21 .  I have sometimes had success by creating a temporary file on the root disk, adding it to the btrfs pool, doing a rebalance, deleting some files, and then removing the temporary file.  But in practice again it is easier just to terminate the node through the AWS API.

But if your node goes offline, and the disk is not full, then please do comment as that is surprising (and if your node goes offline and the disk is full, that's still useful confirmation, particularly if you can track down where the disk space went using du).

When do masters go offline?  The "du - cannot allocate memory” error on the master should have been fixed in #14381.  We’ve also now seen reports that this may be due to exhausting the CPU allowance on a t2 class machine.  You can ‘burst’ on a t2 instance, but once you exceed your allowance the steady-state CPU performance is rather low.  I would like to switch the default to instances with more steady performance.

@drora - your report is the most surprising to me.  I presume you’re running with aufs?  I’m bringing up a test cluster to see if I can reproduce this (and other) problems.  If there are any other non-default settings you’re using, please let me know.

I would like to:

* Switch the defaults to be m3.mediums.  The user-experience with the t2 class is simply not good enough, particularly once the burst allowance is exhausted, and it is hard to test the out-of-quota case.
* Change the default to btrfs.  aufs is no better at keeping the node online when we run out of disk space, but btrfs at least preserves the files.
* Turn off influxdb by default, until they are able to bound the disk space it can consume.  Right now it seems to take down a lot of installations, and I have yet to hear of anyone getting valuable data from it.  Or we could back it with an EBS volume.
* Turn off elasticsearch by default, or back elasticsearch with an EBS volume, or repoint it to use AWS ElasticSearch-aaS.

Also, I'm going to keep an eye on my test cluster to see whether I can reproduce any of these issues.

**Comment by drora** [comment]
thanks for elaborating @justinsb.
as for my report - 
1) I have to say that I had found an internal issue that caused pod errors to overwhelm elasticsearch and influx and probably resulted these crushes extensively.
2) I did use default aufs. will try to move to btrfs asap (no other non-default settings).
3) switching the default instance to m3 is cool, but I will stick to t2.medium (small startups are the best candidates to harness cutting edge tech, but in reasonable prices. m instances are pricy without justification, will increase burn-rate substantially). having said that, I fully understand the cpu burst credit issue you mentioned. choosing the right credit track to fit our needs is my responsibility, and therefore almost never encountered this.   
4) influx addon was already off since the incident.
5) will definitely look into moving to elasticsearch-aaS (or edit kube-system elasticsearch-rc to hold storage and maybe move to a later elasticsearch release). maybe we should doc an example..?

**Comment by davidopp** [comment]
Thanks for the thorough update, @justinsb.
https://aws.amazon.com/ec2/instance-types/
says T2 storage is "EBS-only." How much storage do you actually get? We should definitely set our defaults to something that will work out-of-the-box, and then provide instructions on how people can crank it down to small instance sizes (along with warnings about the corresponding risks). Of course we should also try to optimize the system to run on the smallest instance sizes possible.

**Comment by justinsb** [comment]
So it appears that a t2 does get 32GB of disk, which actually should be plenty (i.e. I think I'm wrong here).  The disk will eventually fill up, but an m3.medium (with which I get good results) should fill up much faster.  Because there's only one volume, we are forced to use aufs also.

I have a cluster of 4 t2.micros and one of them is immediately at 100% CPU - the one with influxdb.  Logging in to the machine, the CPU is about 40% influxdb and 40% kubelet, about 10% rcu_sched with most docker being the most notable of the rest.  CPU steal is at 82%, indicating I think that we've totally exhausted our CPU quota.  This is on a fresh cluster running the guestbook-go example, so not particularly heavily loaded.

I'm going to let this run for a bit and see if anything else breaks.  I do suspect that I need to start pushing some data through the logs, to get ES data to fill up some disks, but we'll see.

I also opened #18944 - the OutOfDiskReady status is just a UI bug in kube-ui I think.

**Comment by justinsb** [comment]
I was able to reproduce the master going offline on a t2.micro - it stopped responding to API requests and I was unable to SSH in, though I was able to recover by rebooting the master.  Tracking this as #18975.  (It did not appear to have exhausted its CPU credits, and the disk was not full)

**Comment by drora** [comment]
Hi,
just to be clear, master is going offline regardless to the instance type after reboot.

just met this issue on v1.1.3
after master node reboot, lost control over the cluster.

(kubectl config was empty, probably lost data on attached ebs storage, wasn't able to re-gain control and recover with etcd, couldn't find more info about how to re-configure master back to existing cluster on aws)

kubectl get nodes :: 
"error: couldn't read version from server: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: connection refused"

from kubelet log :: 
"Unable to write event: 'Post https://{IP}/api/v1/namespaces/default/events: dial tcp {IP}:443: connection refused' (may retry after sleeping)"
"Skipping pod synchronization, network is not configured"

this is a major deal here for production use.
very easy to repro locally (via vagrant).
1) just spin up a cluster using kube up,
2) restart master vm
3) lose cluster.
