### ISSUE TITLE
flaky e2e: Daemon set should launch a daemon pod on every node of the cluster

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#14072]
I've seen two jenkins runs flake due to similar Conflict reasons.  Jeff, are you the best person to dig or is there a Daemon-test owner?  Is this a candidate for promo-to-flaky?

From http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/8734/testReport/junit/(root)/Kubernetes%20e2e%20suite/Daemon_set_should_launch_a_daemon_pod_on_every_node_of_the_cluster/

Kubernetes e2e suite.Daemon set should launch a daemon pod on every node of the cluster (from (junit_04.xml))

Failing for the past 1 build (Since Unstable#8734 )
Took 55 sec.
Stacktrace

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:51
Expected error:
    <*errors.StatusError | 0xc208319780>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "node \"pull-e2e-4-minion-4vb7\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again",
            Reason: "Conflict",
            Details: {
                Name: "pull-e2e-4-minion-4vb7",
                Kind: "node",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    }
    node "pull-e2e-4-minion-4vb7" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
not to have occurred

**Comment by ixdy** [comment]
I do not have the bandwidth to investigate this right now. If it is truly a P0 someone else should take it over.

**Comment by ixdy** [comment]
cc @kubernetes/goog-testing

**Comment by quinton-hoole** [comment]
This is a bug in the test.  It needs to retry updates on version mismatch.  @mikedanese can you do?

**Comment by quinton-hoole** [comment]
PS, there's another failure mode that we see in this test quite frequently.  It might make sense to fix it at the same time, or at least improve the logging:

```
Daemon set should launch a daemon pod on every node of the cluster

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:52
Expected error:
    <*errors.errorString | 0xc208132310>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred

```

**Comment by mikedanese** [comment]
Looking into this now.

**Comment by alex-mohr** [comment]
Thanks @mikedanese for looking.  FWIW, I noticed it seemed to be instantly timing out at < 1 second, when the code appears to have a 5 second poll and 1 minute timeout passed in.  Something odd.

**Comment by brendandburns** [comment]
@mikedanese are you still looking at this one?  If not please un-assign yourself.

**Comment by mikedanese** [comment]
This is hopefully fixed by #14550. I'm going to see if that helps after it's merged. If yes, I'll promote out of flaky. If not I will debug further.

**Comment by goltermann** [comment]
This one is still failing (with the timeout issue) in Jenkins in the latest parallel-flaky run.

**Comment by mikedanese** [comment]
@goltermann see #14909 and #14915

**Comment by mikedanese** [comment]
DaemonSet deploy simple daemon is no longer flaky. See #15559. I'm demoting this to a p1 and moving out of 1.1
