### ISSUE TITLE
Overlay network doesn't work for docker-multinode setup

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#14409]
I have a cluster based on "docker-multinode" getting started guide with some changes that adapts it to systemd OS (i.e. Ubuntu 15.04). I have a problem with flannel-based overlay network:

I have a pod with IP ```10.1.75.2``` (our porter image). I can ping/curl it from a node it runs it:
```
filipg@docker-node1:~$ curl 10.1.75.2:160
foo
```
The same thing does not work on other nodes (master and other nodes):
```
$ curl 10.1.75.2:160
curl: (7) Failed to connect to 10.1.75.2 port 160: No route to host
```
I checked entries in etcd and they look correct:
```
filipg@docker-master:~$ docker -H unix:///var/run/docker-bootstrap.sock exec -t elated_einstein etcdctl ls /coreos.com/network/subnets
/coreos.com/network/subnets/10.1.20.0-24
/coreos.com/network/subnets/10.1.75.0-24
/coreos.com/network/subnets/10.1.61.0-24
/coreos.com/network/subnets/10.1.90.0-24
/coreos.com/network/subnets/10.1.103.0-24
filipg@docker-master:~$ docker -H unix:///var/run/docker-bootstrap.sock exec -t elated_einstein etcdctl get /coreos.com/network/subnets/10.1.75.0-24
{"PublicIP":"10.240.0.2","BackendType":"vxlan","BackendData":{"VtepMAC":"ee:84:9f:f3:57:3e"}}
```
All the nodes seem to be routable:
```
filipg@docker-master:~$ ping 10.240.0.2
PING 10.240.0.2 (10.240.0.2) 56(84) bytes of data.
64 bytes from 10.240.0.2: icmp_seq=1 ttl=64 time=0.938 ms
```

@thockin @bprashanth

**Comment by thockin** [comment]
From the other thread it sounds like this is fixed?

On Wed, Sep 23, 2015 at 2:40 AM, Filip Grzadkowski <notifications@github.com

**Comment by fgrzadkowski** [comment]
Oh, sorry. I forgot to update this bug. It's not fixed yet, but we know the root cause. flannel 0.5.0 has a bug which can break overlay network (see details https://github.com/coreos/flannel/issues/325). I created a separate bug to upgrade version in kubernetes (https://github.com/kubernetes/kubernetes/issues/14426)
