### ISSUE TITLE
hack/verify-godeps.sh fails on master

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kubernetes#14677]
`hack/verify-godeps.sh` is run as part of Shippable and seems to be failing on any PRs that change Godeps.

```
$ hack/verify-godeps.sh
Starting to download all kubernetes godeps. This takes a while
Download finished
Your Godeps.json is different:
--- /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/Godeps.json	2015-09-28 19:28:55.000000000 +0000
+++ /tmp/gopath.bycPi4/src/k8s.io/kubernetes/Godeps/Godeps.json	2015-09-28 19:41:46.681006178 +0000
@@ -578,15 +577,15 @@
 		},
 		{
 			"ImportPath": "golang.org/x/net/context",
-			"Rev": "cbcac7bb8415db9b6cb4d1ebab1dc9afbd688b97"
+			"Rev": "c2528b2dd8352441850638a8bb678c2ad056fd3e"
 		},
 		{
 			"ImportPath": "golang.org/x/net/html",
-			"Rev": "cbcac7bb8415db9b6cb4d1ebab1dc9afbd688b97"
+			"Rev": "c2528b2dd8352441850638a8bb678c2ad056fd3e"
 		},
 		{
 			"ImportPath": "golang.org/x/net/websocket",
-			"Rev": "cbcac7bb8415db9b6cb4d1ebab1dc9afbd688b97"
+			"Rev": "c2528b2dd8352441850638a8bb678c2ad056fd3e"
 		},
 		{
 			"ImportPath": "golang.org/x/oauth2",
Removing /tmp/gopath.bycPi4
```

I was able to reproduce on master by removing the early exit when no Godeps changes are shown by `git diff`: https://github.com/kubernetes/kubernetes/blob/master/hack/verify-godeps.sh#L44-L46

**Comment by ncdc** [comment]
I've stepped through verify-godeps.sh manually line by line. The first time `godep restore` is invoked, I can see the checked out commit for golang.org/x/net change from master to cbcac7b and then back to master by the time the restore finishes. If you run `godep restore` a second time, it ends up with the correct checkout (cbcac7b).

**Comment by karlkfi** [comment]
The `golang.org/x` code is all in the same repo, but their revisions don't agree in our Godeps:

```
{
			"ImportPath": "golang.org/x/crypto/ssh",
			"Rev": "c84e1f8e3a7e322d497cd16c0e8a13c7e127baf3"
		},
		{
			"ImportPath": "golang.org/x/exp/inotify",
			"Rev": "d00e13ec443927751b2bd49e97dea7bf3b6a6487"
		},
		{
			"ImportPath": "golang.org/x/net/context",
			"Rev": "cbcac7bb8415db9b6cb4d1ebab1dc9afbd688b97"
		},
		{
			"ImportPath": "golang.org/x/net/html",
			"Rev": "cbcac7bb8415db9b6cb4d1ebab1dc9afbd688b97"
		},
		{
			"ImportPath": "golang.org/x/net/websocket",
			"Rev": "cbcac7bb8415db9b6cb4d1ebab1dc9afbd688b97"
		},
		{
			"ImportPath": "golang.org/x/oauth2",
			"Rev": "b5adcc2dcdf009d0391547edc6ecbaff889f5bb9"
		},
		{
			"ImportPath": "golang.org/x/tools/go/ast/astutil",
			"Rev": "4f50f44d7a3206e9e28b984e023efce2a4a75369"
		},
		{
			"ImportPath": "golang.org/x/tools/imports",
			"Rev": "4f50f44d7a3206e9e28b984e023efce2a4a75369"
		},
```

**Comment by ncdc** [comment]
x/net is a different git repo from x/crypto and so on, so I don't think that's it.

**Comment by timstclair** [comment]
Possibly related? https://github.com/tools/godep/issues/279

**Comment by karlkfi** [comment]
I doubt it. Otherwise we'd be getting those errors when godep delegates to `go get`.

**Comment by karlkfi** [comment]
I looked at this most of the day today and am not any closer to figuring it out...

**Comment by ncdc** [comment]
Ok, I've tracked this down. What happens in godep is that it runs a loop where, for each dependency, it does this:

- `go get -d <package>`
- `cd <package> && git checkout <ref>` (or other vcs as appropriate)

Unfortunately, if you have something like this:

- `go get -d golang.org/x/net`, checkout ref abcd1234
- `go get -d google.golang.org/api/compute/v1`

The 2nd get (of google.golang.org/api/compute/v1) resets the HEAD of (at least in this case) golang.org/x/net to `master`. I wonder if this is perhaps a bug in `go get` itself (I'm testing with 1.4.2). godep potentially could be modified to run `go get` first for all dependencies, and then do `git checkout` after all the downloads are done.

**Comment by ncdc** [comment]
I hacked up my local copy of godep to do all the downloads in 1 loop, followed by all the vcs checkouts in a 2nd loop, and it appears that the end result is the correct revision for the various repos.

**Comment by karlkfi** [comment]
Yeah, that sounds about what I was expecting: a transitive dependency stomping on the revision in a primary dependency. This is pretty critical to correct dependency management. I think your approach is probably correct; the primary revision should override the transitive one. Tho it's probably a good idea to warn when this is the case, either when restoring or saving or both.

Have you made a Godep PR, @ncdc?

**Comment by ncdc** [comment]
@karlkfi it's not even that there's a transitive revision. It looks like `go get` is always resetting the local ref to `master`.

**Comment by ncdc** [comment]
Godep PR: https://github.com/tools/godep/pull/285 ... not sure if this is the right approach, but it seemed to work on my system.

**Comment by karlkfi** [comment]
`go get -d` checks out transitive dependencies, is what I meant. It looks like it's (now) checking out master even when it's on a detached head.

**Comment by ncdc** [comment]
It looks like it only does it when it's downloading something (google.golang.org/api/compute/v1
 from the example above, which I manually removed prior to testing things). If I run `godep restore` two times in a row, after the first execution, the golang.org/x/net refs will be incorrect (master). After the second execution, they are correct.

**Comment by ncdc** [comment]
So we could modify hack/verify-godeps.sh to call `godep restore` two times in a row as a short term fix.

**Comment by pmorie** [comment]
@ncdc lvl 999 digging :trophy:

**Comment by ncdc** [comment]
@eparis in the immediate term, how do you feel about modifying `hack/verify-godeps.sh` to call `godep restore` twice in a row to try to work around this issue?

**Comment by karlkfi** [comment]
The point of verify-godeps was to validate that it works as expected, not redefine the expectations. I'd rather just update the out of date dependencies.

**Comment by ncdc** [comment]
@karlkfi I don't think it's that simple. Until the `go get`/`godep restore` bug is fixed, that would mean that the only way to guarantee that `godep restore` and `hack/verify-godeps.sh` work correctly 100% of the time is to ensure that `Godeps.json` always contains refs to the tip of every single dependency. If there is a lag in any of them, then you may see this issue crop up again.

**Comment by eparis** [comment]
But the bug isn't that clear, it doesn't happen every time we aren't at HEAD...  there is something special happening...

I can't reproduce it anywhere other than go get -u on google.golang.org/api/compute/v1

**Comment by karlkfi** [comment]
@eparis verify-godeps exits early if git diff doesn't find any Godeps changes. If you remove that condition it breaks on every branch, including master.

**Comment by ncdc** [comment]
From https://golang.org/src/cmd/go/vcs.go, line 388, it will repair a detached head.

**Comment by eparis** [comment]
obviously we don't always get to there...   so why do we hit line 388 sometimes and not others?

**Comment by ncdc** [comment]
Still digging...

**Comment by karlkfi** [comment]
@ndnd That line was added in Aug 14, 2013. I don't think it's the problem. But the following lines (https://github.com/golang/go/blame/master/src/cmd/go/vcs.go#L391-L399) were updated May 6 2015.

My guess is that fixDetachedHead errors in this case and then the downloadCmd `"pull --ff-only` is run instead (https://github.com/golang/go/blame/master/src/cmd/go/vcs.go#L126)

**Comment by ncdc** [comment]
@karlkfi it actually is from fixDetachedHead. See this: https://gist.github.com/ncdc/8e8d8474416f569cc3f2.

**Comment by ncdc** [comment]
Also, if you're on a detached head, `git pull --ff-only` won't switch you back to master.

**Comment by karlkfi** [comment]
Did any of those go commands change behavior in 1.5?

**Comment by ncdc** [comment]
I see this with 1.4 and 1.5.

**Comment by karlkfi** [comment]
It just doesn't make sense that no one has run into this before...

**Comment by karlkfi** [comment]
The May 6 changes added the `git pull --ff-only` after the `git checkout master`... If you did a `go get` and it was on a detached head would it still `git fetch`? If not, then anyone who had checked out the revision when it was master wouldn't have the new revisions fetched. So a a checkout wouldn't change the code.

**Comment by ncdc** [comment]
I have identified what I believe to be the actual root cause. When `go get -d` initially downloads `google.golang.org/api/compute/v1`, its HEAD pulls in `golang.org/x/net/context/ctxhttp`. That directory isn't currently vendored by our copy of `golang.org/x/net` revision cbcac7b. As a result, `go get` pulls down an update for `golang.org/x/net`, fixing its detached head during the process. This is unfortunate, as presumably the rev of `google.golang.org/api/compute/v1` in our Godeps.json is probably compatible with the rev of `golang.org/x/net` in there as well, but because `go get -d` pulls down the HEAD of the former, it's forced to do the same for the latter.

**Comment by karlkfi** [comment]
ok, so it's not just a transitive dependency problem, but a transitive dependency on a sub-package of an outdated direct dependancy. That's much more obscure and make it more reasonable that this hasn't broken everyone using Godep.

**Comment by ncdc** [comment]
Closing as #14747 was merged

**Comment by karlkfi** [comment]
This isn't technically resolved. We just put in a temporary workaround until godeps is patched. It's possible this will crop up again when a dependency updates head.

**Comment by thockin** [comment]
I still get errors from godep on the release branch

**Comment by karlkfi** [comment]
@thockin i doubt the temporary fix got cherry-picked

**Comment by karlkfi** [comment]
oh, you just cherry picked it...

**Comment by thockin** [comment]
that change to verify-godeps?  It did

**Comment by thockin** [comment]
yeah, even with my picks it fails...

**Comment by karlkfi** [comment]
@thockin @ncdc's godep fix was merged upstream. try again on the release branch with the latest godep

**Comment by thockin** [comment]
Trying now.  Still getting some errors.  I cherry picked the 3 PRs that
seem to be needed to make it happy, but it still fails:

```
thockin@freakshow kubernetes
automated-cherry-pick-of-#14245-#14770-#14747-upstream-release-1.1 /$
/tmp/kube-godep/bin/godep restore
package github.com/prometheus/client_golang/extraction: cannot find package
"github.com/prometheus/client_golang/extraction" in any of:
        /usr/lib/google-golang/src/
github.com/prometheus/client_golang/extraction (from $GOROOT)
        /tmp/kube-godep/src/github.com/prometheus/client_golang/extraction
(from $GOPATH)
godep: restore: exit status 1
package github.com/prometheus/client_golang/model: cannot find package "
github.com/prometheus/client_golang/model" in any of:
        /usr/lib/google-golang/src/github.com/prometheus/client_golang/model
(from $GOROOT)
        /tmp/kube-godep/src/github.com/prometheus/client_golang/model (from
$GOPATH)
godep: restore: exit status 1
package github.com/prometheus/client_golang/text: cannot find package "
github.com/prometheus/client_golang/text" in any of:
        /usr/lib/google-golang/src/github.com/prometheus/client_golang/text
(from $GOROOT)
        /tmp/kube-godep/src/github.com/prometheus/client_golang/text (from
$GOPATH)
godep: restore: exit status 1
```

**Comment by timstclair** [comment]
I think https://github.com/kubernetes/kubernetes/pull/14302 should fix those errors. Or are you trying to fix this on the godeps side first?

**Comment by karlkfi** [comment]
godep should be working the way we want now. it will give you exactly the revisions you asked for. if that results in conflicts then it's up to the user to fix it.

**Comment by thockin** [comment]
Ah, I thought it was clean on master, but it's not.  Godep restore still
fails on master, even with the most recent godep binary.
