### ISSUE TITLE
EBS volumes: kubelet does not honor 'partition' attribute

### ISSUE THREAD

**Issue by antoineco** [kubernetes/kubernetes#15077]
Kubernetes 1.9.3

kubelet does not honor the partition number and always mounts the first partition.

```console
$ sudo fdisk -l /dev/xvdf    # disk layout
[...]
Device     Boot   Start       End   Sectors Size Id Type
/dev/xvdf1         2048   2099199   2097152   1G 83 Linux
/dev/xvdf2      2099200 167772159 165672960  79G 83 Linux
```

``` yaml
#pod definition
[...]
  spec:
    containers:
    - name: artifactory-pro
      volumeMounts:
      - mountPath: /etc/opt/jfrog/artifactory
        name: etc
      - mountPath: /var/opt/jfrog/artifactory/data
        name: data
    volumes:
    - awsElasticBlockStore:
        fsType: ext4
        partition: 1
        volumeID: vol-f016833f
      name: etc
    - awsElasticBlockStore:
        fsType: ext4
        partition: 2
        volumeID: vol-f016833f
      name: data
```

Same partition mounted for both volumes:

```console
$ kubectl exec artifactory df
Filesystem     1K-blocks    Used Available Use% Mounted on
[...]
/dev/xvdf1      976M  1.3M  908M   1% /etc/opt/jfrog/artifactory
/dev/xvdf1      976M  1.3M  908M   1% /var/opt/jfrog/artifactory/data
```

**Comment by justinsb** [comment]
Thanks for reporting.  And I was so sure this would work! :-(

**Comment by antoineco** [comment]
Maybe I missed some of your commits? I'm currently testing on k8s 1.1.0 (7d6c8b6) which is 386 commits behind master.

**Comment by justinsb** [comment]
This should be fixed (finally!) by #15938

**Comment by bprashanth** [comment]
@justinsb is this not fixed per https://github.com/kubernetes/kubernetes/issues/15077#issuecomment-149522898 ? please close if it is, or update with status if it isn't

**Comment by thockin** [comment]
I'm going to close this, but I'd love a confirmation if anyone can spare the time.

**Comment by antoineco** [comment]
@thockin @justinsb this is still broken unfortunately, with the same pod description as in my first comment. The first partition is mounted 2 times.

**Comment by antoineco** [comment]
ping @justinsb @thockin, I believe this should be re-opened.

**Comment by thockin** [comment]
@rootfs or @childsb - any free time to investigate?

**Comment by rootfs** [comment]
@antoineco which kube release you are using?

**Comment by antoineco** [comment]
@rootfs 1.2.2, I updated my first comment.

**Comment by childsb** [comment]
I'll have a look at this and update in the next day or so.

**Comment by childsb** [comment]
This is indeed broken.  Using this setup both volumes mounted partition 2:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: ose-busy
  labels:
    name: ose-busy
spec:
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sleep","7d"]  
      volumeMounts:
        - name: vol1
          mountPath: /mnt/pv-1
        - name: vol2
          mountPath: /mnt/pv-2
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: "claim1"
    - name: vol2
      persistentVolumeClaim:
        claimName: "claim2"
```
``` yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1-1gb
  labels:
    type: ebs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-66c417d4
    fsType: xfs
    partition: 1 
```
``` yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2-1gb
  labels:
    type: ebs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-66c417d4
    fsType: xfs
    partition: 2

```

**Comment by childsb** [comment]
@swagiaal

**Comment by swagiaal** [comment]
@childsb thanks for the CC. I was wondering how this is not causing a NoDiskConflict but it is because both volumes are being used within the same pod which should cause no problems.
@childsb I would try to reproduce this using direct volumes as @antoineco did. Not that PV and PVCs could be causing the problem but it just removes a layer of indirection.

**Comment by childsb** [comment]
@swagiaal no need. the bug/code location is pretty obvious. The shared AWS host mount is based only on the volume and not the partition.  So the first partition to mount there is what every POD on the host using that volume will see..

**Comment by swagiaal** [comment]
ah I see

**Comment by erinboyd** [comment]
taking over as @bc doesn't have the time...will validate and present a solution ASAP

**Comment by davidopp** [comment]
I'm going to remove the 1.3 milestone label and move to 1.4 -- this doesn't seem like a release blocker since the problem has been around from the beginning.

**Comment by goltermann** [comment]
@erinboyd @childsb 1.4 is shipping in less than two weeks - anyone looking at this?  Time to move it to the v1.5 milestone?

**Comment by thockin** [comment]
This is certainly not 1.4

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by spiffxp** [comment]
@kubernetes/sig-aws-misc do you want this in v1.7?

**Comment by justinsb** [comment]
Want: yes; time to make it happen: no

**Comment by antoineco** [comment]
@k8s-merge-robot
/kind bug
/priority important-longterm

**Comment by antoineco** [comment]
@k8s-merge-robot
/remove-priority important-longterm

**Comment by dims** [comment]
@justinsb - So, time for that question again. Do we want this in v1.8?

**Comment by dims** [comment]
Folks from @kubernetes/sig-aws-misc , please confirm that this is not a release blocker for 1.8
