### ISSUE TITLE
fieldSelector syntax and usage not documented

### ISSUE THREAD

**Issue by jonmoter** [kubernetes/kubernetes#15128]
In the API docs, several of the endpoints allow you to pass a `fieldSelector` parameter to limit the information returned. When I run `kubectl describe pod <pod_name> --v=8` I see that's used by kubectl to get all the events associated with a pod.

I assumed the syntax of `fieldSelector` uses the same syntax as the [Label Selectors](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/labels.md#label-selectors), as described in the docs.  However, I can't use the set-based syntax, like `involvedObject.name in (pod_1,pod_2)`.

In addition, there are some fields that apparently can't be used.  If I try getting pods with a fieldSelector of `metadata.name = foobar` I get the error "field label not supported: metadata.name"

It would be great to have some documentation on how to use this parameter, and what its constraints are.

**Comment by bgrant0607** [comment]
What would you like to use fieldSelector for?

The lack of documentation is intentional, pending implementation of #1362.

**Comment by jonmoter** [comment]
As context, here's how I came to this issue (please excuse the length of this):

I'm building a Kubernetes integration with Zendesk's [deployment management tool](https://github.com/zendesk/samson). I'd like to be able to communicate through Kubernetes through its API.

I deploy code by creating a ReplicationController. I want to know whether the deploy was successful or if it ran into a problem along the way.  Here's what I did:

1. Subscribe to the output of `/v1/replicationcontrollers/{name}?watch` to track state of RC.
1. Subscribe to the output of `/v1/pods?watch&labelSelector={selector}` to track state of all the pods created by that RC.
2. Realize there are scenarios when Kubernetes can't start the pods, like if there isn't enough RAM in the cluster to schedule the pod. If this happens, the pod stays in a "Pending" phase, and I'm given no indication that happened.
3. Notice that when I do a `kubectl describe pod <pod_name>`, there's an Event there saying it failed to schedule.  Realize I'll have to watch for Events associated with those pods.
4. Unable to figure out how to do that with a `labelSelector`, since the events don't have any labels I could use.
5. Discover that `kubectl` is getting those Events by hitting the Events endpoint, passing in a fieldSelector `involvedObject.name={pod_name}`.  Figure I'll have to do something like that.
6. Experiment with Events endpoint. Discover that I can't say `involvedObject.name IN (pod-1,pod-2,pod-3)`, and feel sad. Play around some more, and get errors saying that certain fields cannot be used for fieldSelector. Finally poke around in the source and find some code that lists the fields that can be used.
7. Realize I'll just have to do something like a fieldSelector of `involvedObject.kind=Pod`, and filter out all the pods I don't care about client-side.

So I guess the *real* thing that I want is to have an easy way to know what's going on with the Pods I'm attempting to deploy, so I can reflect that in my UI and update records in my deploy tool.

I assume that if there are documented parameters in the published API docs of Kubernetes, there would be some explanation on how they're used. Since you described label selectors pretty clearly in the user guide, I'd expect field selectors to be similarly documented.

If you're planning on deprecating that param to clean things up, that's fair. But I think you should then add a note to the API docs saying that param will be deprecated, and not to rely on it.

**Comment by msufa** [comment]
Any progress here? I'd love to see some docs describing `fieldSelector`.

**Comment by krancour** [comment]
+1

**Comment by asifhj** [comment]
+1

**Comment by dragon9783** [comment]
+1

**Comment by wangweihong** [comment]
+1
 I want to know whether fieldSelector support set-based match

**Comment by keglevich3** [comment]
+1

**Comment by dvasilen** [comment]
+1

**Comment by duglin** [comment]
Based on the chat here, and https://github.com/kubernetes/kubernetes/issues/1362, it appears that "fieldSelector" isn't really supported (except in a few cases, like Pods).  Yet http://kubernetes.io/docs/api-reference/v1/operations/ seems to show it as a valid query param whenever "labelSelector" appears in the GET operation. Would it make sense to remove it from the docs to avoid any confusion for users?

**Comment by frankgreco** [comment]
@duglin you say that the "fieldSelector" query param only works on kinds such as Pods. However, it is part of the `v1.ListOptions` struct which is used in multiple api groups included core, extensions, etc. See the GoDoc [here](https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#ListOptions)

**Comment by frankgreco** [comment]
also, I can confirm that it works for more than just pods

**Comment by duglin** [comment]
maybe things have changed - I'll try to remember why I landed on that conclusion (probably from the other threads I referenced).

**Comment by jkinkead** [comment]
This would be incredibly useful to have documented for Events. As mentioned by the original filer, these have no labels for filtering with `labelSelector`.

**Comment by antoniaklja** [comment]
`fieldSelector` in combination with `v1.ListOptions` is quite important and useful, especially if you want list Pods with specific Status using `kubernetes/client-go`

**Comment by ZhangYou0122** [comment]
+1

**Comment by zhihzhang** [comment]
+1

**Comment by olegs-codefresh** [comment]
So nothing for now? 
Was any progress made with this query?

**Comment by dcheney-atlassian** [comment]
```
        list, err := client.CoreV1().Nodes().List(metav1.ListOptions{
                FieldSelector: "status.podIP!=127.0.0.1",
        })
        if err != nil {
                log.Fatalf("error listing nodes: %v", err)
        }
```
Returns 

    2017/08/16 14:57:04 error listing nodes: field label not supported: status.podIP

With the 4.0.0.beta.0 client.

**Comment by furkhat** [comment]
Hey @jonmoter,I was looking at source code and found that you can use `metadata.name` like [here](https://github.com/kubernetes/apimachinery/blob/b317fa7ec8e0e7d1f77ac63bf8c3ec7b29a2a215/pkg/apis/meta/v1/helpers.go#L204).

**Comment by asarkar** [comment]
How'd I select on a field in an array, say if I want to find all pods that are ready? In jq, it'd be `.status.conditions[] | select(.type=="Ready" and .status=="True")`

```
"status": {
	"phase": "Running",
	"conditions": [{
		"type": "Initialized",
		"status": "True",
		"lastProbeTime": null,
		"lastTransitionTime": "2017-11-30T00:50:27Z"
	}, {
		"type": "Ready",
		"status": "True",
		"lastProbeTime": null,
		"lastTransitionTime": "2017-11-30T00:53:27Z"
  }, {
  	"type": "PodScheduled",
  	"status": "True",
  	"lastProbeTime": null,
  	"lastTransitionTime": "2017-11-30T00:50:27Z"
}]
```

**Comment by sdf611097** [comment]
The format is 
```
metadata.name!%3Dnode1,metadata.name!%3Dnode2
```
%3D is '=', Using ',' to add new constraint.

This sample will get nodes which is neither named 'node1' nor 'node2'.

The possible fields are defined in [conversion.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/v1/conversion.go). (see search AddFieldLabelConversionFunc).

**Comment by asarkar** [comment]
@sdf611097 Is what you said meant to be a response to my question, because if yes, you didn't answer my question.

**Comment by ahmetb** [comment]
Consider moving this to kubernetes/website repo. Maybe someone there will be interested in contributing a documentation. 2+ years later docs on this topic and `kubectl get --field-selector` are still lacking.

**Comment by lucperkins** [comment]
Please note that this issue is being addressed in this PR: https://github.com/kubernetes/website/pull/9174

**Comment by ahmetb** [comment]
I think this is fixed now.
/close

**Comment by consideRatio** [comment]
New Issue about the lack of overview of what you can pass to `--fieldSelector` for let's say events: https://github.com/kubernetes/website/issues/9807

**Comment by codersofthedark** [comment]
> I think this is fixed now.
> /close

Not really. Doc still doesn't clarify what all field selectors are available for what kind of resources.

**Comment by romanseidl** [comment]
This seems to be still open. There is no documentation on the available fields.

**Comment by romanseidl** [comment]
There is now many issues with this problem and they keep coming. Just because this simply never gets fixed. For years and years.

**Comment by daxmc99** [comment]
A workaround, for now, would be to observe the actual values in code. 
The `ToSelectTableFields` functions inside the various `strategy.go` files provide some hints. 
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/strategy.go#L233

You can search for them here https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/kubernetes/kubernetes%24+ToSelectableFields&patternType=literal
