### ISSUE TITLE
Pod Disks should schedule a pod w/two RW PDs flake

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#15382]
Failed 2 times in the last 30 runs.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/8824/testReport/junit/%28root%29/Kubernetes%20e2e%20suite/Pod_Disks_should_schedule_a_pod_w_two_RW_PDs_both_mounted_to_one_container__write_to_PD__verify_contents__delete_pod__recreate_pod__verify_contents__and_repeat_in_rapid_succession/

/cc @saad-ali

**Comment by roberthbailey** [comment]
There's another flake for PDs (this time on GKE) on the test `Pod Disks should schedule a pod w/ a RW PD, remove it, then schedule it on another host`: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/8782/testReport/junit/(root)/Kubernetes%20e2e%20suite/Pod_Disks_should_schedule_a_pod_w__a_RW_PD__remove_it__then_schedule_it_on_another_host/

which is preventing the merge bot from merging new PRs.

**Comment by saad-ali** [comment]
The two failures occurred in:
* kubernetes-e2e-gce Jenkins Build 8802 (Oct 7, 2015 7:37:46 AM)
* kubernetes-e2e-gce Jenkins Build 8824 (Oct 8, 2015 3:43:20 PM)

The 1st failure was due to `08:52:07 stderr=cat: can't open '/testpd2/tracker1': No such file or directory`.
This problem was identified in issue #15106 (on Oct 5, 2015, 1:01 PM PDT) and fixed by PR #15258 (on Oct 7, 2015, 7:23 PM PDT).

The 2nd failure was caused by `gave up waiting for pod...`
This is a new issue, and I'll dig into it.

**Comment by saad-ali** [comment]
Regarding the GKE test failure you just posted (`kubernetes-e2e-gke-ci Jenkins Build #8782 (Oct 9, 2015 9:41:27 AM)`): the test failed because the test itself failed to create a PD: `09:56:57   Error creating PD`. Meaning that test failed due to test/environment issue (not a code issue). I'll open a separate (lower priority) issue to track track this.

**Comment by roberthbailey** [comment]
Another similar failure on gke-ci:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/8784/testReport/junit/(root)/Kubernetes%20e2e%20suite/Pod_Disks_should_schedule_a_pod_w__a_readonly_PD_on_two_hosts__then_remove_both_/

**Comment by saad-ali** [comment]
Yep, that is the same issue as tracked by this bug. I'm looking into it. Opened #15417 to track the `Error creating PD` issue.

**Comment by zmerlynn** [comment]
Just logging for frequency, it looks like it flaked through the weekend as well.

**Comment by dchen1107** [comment]
Ok, it is really flaky. Should we tag it as FLAKY_TEST and move it out kubernetes-e2e-gce?

**Comment by saad-ali** [comment]
I'm creating a PR to move the test to flaky while I prepare a fix.

For my own notes, here are more recent repros:
* kubernetes-e2e-gce Jenkins Build 8879 (Oct 11, 2015 4:58:20 PM)
* kubernetes-e2e-gce Jenkins Build 8884 (Oct 11, 2015 11:34:03 PM)

**Comment by ixdy** [comment]
Note that it also appears that this test is leaking PDs.

From http://go/k8s-test/job/kubernetes-e2e-gce-parallel-flaky/7223/console, we have a test failure:
```
Oct 12 16:47:02.251: INFO: Running '/jenkins-master-data/jobs/kubernetes-e2e-gce-parallel-flaky/workspace/kubernetes/platforms/linux/amd64/kubectl kubectl --server=https://104.197.10.197 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce-parallel-flaky/workspace/.kube/config exec --namespace=e2e-tests-pod-disks-bdb2i pd-test-7bf4fb5b-713b-11e5-9d64-42010af01555 -c=mycontainer1 -- /bin/sh -c echo '4466584583794064113' > '/testpd1/tracker0''
Oct 12 16:47:03.394: INFO: Wrote value: "4466584583794064113" to PD "parallel-flaky-7764e7a4-713b-11e5-9d64-42010af01555" from pod "pd-test-7bf4fb5b-713b-11e5-9d64-42010af01555" container "mycontainer1"
...
STEP: cleaning up PD-RW test environment
Oct 12 16:52:06.921: INFO: Error deleting PD: ERROR: (gcloud.compute.disks.delete) Some requests did not succeed:
 - The disk resource 'parallel-flaky-7764e7a4-713b-11e5-9d64-42010af01555' is already being used by 'parallel-flaky-minion-1dm2'

 (exit status 1)
Oct 12 16:52:06.921: INFO: Couldn't delete PD "parallel-flaky-7764e7a4-713b-11e5-9d64-42010af01555". Sleeping 5 seconds (exit status 1)
Oct 12 16:52:12.676: INFO: Error deleting PD: ERROR: (gcloud.compute.disks.delete) Some requests did not succeed:
 - The disk resource 'parallel-flaky-7764e7a4-713b-11e5-9d64-42010af01555' is already being used by 'parallel-flaky-minion-1dm2'

 (exit status 1)
...
Oct 12 16:55:10.289: INFO: event for pd-test-7bf4fb5b-713b-11e5-9d64-42010af01555: {kubelet parallel-flaky-minion-1dm2} FailedMount: Unable to mount volumes for pod "pd-test-7bf4fb5b-713b-11e5-9d64-42010af01555_e2e-tests-pod-disks-bdb2i": Could not attach GCE PD "parallel-flaky-7764e7a4-713b-11e5-9d64-42010af01555". Timeout waiting for mount paths to be created.
Oct 12 16:55:10.289: INFO: event for pd-test-7bf4fb5b-713b-11e5-9d64-42010af01555: {kubelet parallel-flaky-minion-1dm2} FailedSync: Error syncing pod, skipping: Could not attach GCE PD "parallel-flaky-7764e7a4-713b-11e5-9d64-42010af01555". Timeout waiting for mount paths to be created.
...
• Failure [524.880 seconds]
Pod Disks
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:297
  should schedule a pod w/ a RW PD shared between multiple containers, write to PD, delete pod, verify contents, and repeat in rapid succession [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:233

  Expected error:
      <*errors.errorString | 0xc2080e0db0>: {
          s: "gave up waiting for pod 'pd-test-7bf4fb5b-713b-11e5-9d64-42010af01555' to be 'running' after 5m0s",
      }
      gave up waiting for pod 'pd-test-7bf4fb5b-713b-11e5-9d64-42010af01555' to be 'running' after 5m0s
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:207
```

And then at the end, we see that this disk has been leaked:
```
+ diff -sw -U0 '-F^\[.*\]$' /var/lib/jenkins/jobs/kubernetes-e2e-gce-parallel-flaky/workspace/_artifacts/gcp-resources-before.txt /var/lib/jenkins/jobs/kubernetes-e2e-gce-parallel-flaky/workspace/_artifacts/gcp-resources-after.txt
--- /var/lib/jenkins/jobs/kubernetes-e2e-gce-parallel-flaky/workspace/_artifacts/gcp-resources-before.txt	2015-10-12 16:40:43.864818369 -0700
+++ /var/lib/jenkins/jobs/kubernetes-e2e-gce-parallel-flaky/workspace/_artifacts/gcp-resources-after.txt	2015-10-12 17:13:42.062813237 -0700
@@ -170,0 +171 @@ [ disks ]
+parallel-flaky-7764e7a4-713b-11e5-9d64-42010af01555 us-central1-f 10      pd-standard READY
```

**Comment by runningwild** [comment]
I noticed something strange on a small cluster I was running over the weekend.  I had a single minion cluster with a pod that was using a disk in RW mode.  The pod restarted at some point and got stuck in state Waiting, even though the disk it needed was (still?) attached to that node.  I assume that k8s got confused about the state of the disk when it detached/reattached it.  (I should have taken a closer look at some of the logs, but so it goes)

It seems to me like the same bug could cause this behavior and this flaky test.  I just wanted to point this out because the discussion so far has made it sound like the problem is with the test only.

**Comment by saad-ali** [comment]
> The pod restarted at some point and got stuck in state Waiting, even though the disk it needed was (still?) attached to that node

@runningwild If you get a repro, file an issue, I'll take a look at it.

**Comment by jszczepkowski** [comment]
This test is still flaky:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/9144/

**Comment by jszczepkowski** [comment]
Another occurrence:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9175/

**Comment by wojtek-t** [comment]
It seems to be a different problem this time - it seems to be my fault this time.
Hopefully this should be fixed by #16369

**Comment by saad-ali** [comment]
Closing. As @wojtek-t pointed out the flakiness was introduced in https://github.com/kubernetes/kubernetes/pull/16266 and fixed by https://github.com/kubernetes/kubernetes/pull/16369.

**Comment by alex-mohr** [comment]
Still happening as of Oct 31 at least:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9214/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9215/

**Comment by alex-mohr** [comment]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9197/

**Comment by alex-mohr** [comment]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/10696/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/10615/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-release-1.1/393/

**Comment by alex-mohr** [comment]
Upping to P0 given rate of occurrence and blocking submit queue -- either a significant product bug or test issue.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-release-1.1/375/

**Comment by saad-ali** [comment]
I'm looking into it. I suspect a test issue (not product). Will reply with more details.

**Comment by saad-ali** [comment]
Confirmed that this cluster of test failures was not caused by a product issue.

The failures were a result of a temporary increase in latency of GCE PD attach/detach calls. Which resulted in the test cases simply timing out before the operations could complete.

**Example 1:**
* Test: `kubernetes-e2e-gce/9214` `Pod Disks should schedule a pod w/ a RW PD, remove it, then schedule it on another host`
* Failed with: `gave up waiting for pod`
```
18:11:14 Test created PD
18:11:26 Test submitted host0Pod to kubernetes
18:16:25 TEST TIMED OUT Waiting for pod pd-test-79aeae3a-8035-11e5-849d-42010af01555 in namespace 'e2e-tests-pod-disks-3s6z7' status to be 'running'(found phase: "Pending", readiness: false) (4m58.679182278s elapsed)
18:19:39.916942  Node successfully attached GCE PD.
18:25:42.735588  Node successfully detached GCE PD.
```
PD took a little over 8 minutes to attach, the test timed out after 5 minutes.

**Example 2:**
* Test: `kubernetes-e2e-gce/9215` `Pod Disks should schedule a pod w/ a RW PD shared between multiple containers, write to PD, delete pod, verify contents, and repeat in rapid succession`
* Failed with: `gave up waiting for pod`
```
20:37:55 Test Created PD
20:38:08 TEST submitting host0Pod to kubernetes
20:43:07 TEST TIMED OUT Waiting for pod status to be 'running'(found phase: "Pending", readiness: false) (4m59.037900593s elapsed)
20:44:27.050785   Node successfully attached GCE PD.
20:48:06.713982   Node successfully detached GCE PD.
```
PD took a little over 6 minutes to attach, the test timed out after 5 minutes.


Because it is not a product issue, I will lower the priority from P0 to P1. I'll submit a PR in the morning to increase the timeout for these tests.

**Comment by alex-mohr** [comment]
@saad-ali Your comment above showed some great debugging work.  I was wondering if there's documentation use used to figure out where to look to find those logs?  Were you able to pull them all retrospectively from a failed test run, or did you need to e.g. repro and poke at a live cluster?  I've seen a bunch of people trying the latter, so if there's a straightforward debug path, it'd help others.  (And I'd be interested myself, since I currently have no idea how to do the retrospective debug.)  @ihmccreery @ixdy for test debug fyi.

**Comment by saad-ali** [comment]
> Your comment above showed some great debugging work.

Thanks :)

> I was wondering if there's documentation use used to figure out where to look to find those logs?

No documentation that I'm aware of, but the Jenkins UI is pretty intuitive.

> Were you able to pull them all retrospectively from a failed test run, or did you need to e.g. repro and poke at a live cluster? I've seen a bunch of people trying the latter, so if there's a straightforward debug path, it'd help others. (And I'd be interested myself, since I currently have no idea how to do the retrospective debug.) @ihmccreery @ixdy for test debug fyi.

For each failed test run, the kubelet log files for each node involved in the test are uploaded to Google Cloud Storage. To access the logs: login to Jenkins, click on a failed build, select "Google Cloud Storage Upload Report", and there should be a GCS link to the artifacts which contain all the important logs.

Once I have the logs, it's simply a matter of parsing and correlating (grep!) data between test run log with kubelet log (e.g. The test created PD X, so let's pull all the logs for PD X, etc.).
