### ISSUE TITLE
godep restore failing due to Godep issue

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#16238]
The aws-sdk-go library just renamed a package from internal -> private to work around Go's vendoring experiment changes:
https://github.com/aws/aws-sdk-go/commit/c09f1bb2f2270137bd1708d4668dc6beb2fb52f2

But we have a Godep dependency on some of these internal packages (we don't use them directly, but Godeps saves them anyway)

The problem is that godep ignores the branch when first pulling the code because it shells out to `go get`, so it tries to do a fetch on a package that doesn't exist on master: https://github.com/tools/godep/issues/186

I think this combines to mean that `godep restore` is broken right now (or at least returning an exit code; I'm not sure if it actually is OK).  If you have a dirty Godeps tree, `hack/verify-godeps.sh` will also fail (but there is a short-circuit in there when the tree is clean which means that Shippable is still passing).

I don't know really how we should fix this (properly).  A workaround is to manually:

```
rm -rf ${GOPATH}/src/github.com/aws/aws-sdk-go/
go get github.com/aws/aws-sdk-go
pushd ${GOPATH}/src/github.com/aws/aws-sdk-go/
git checkout v0.9.9
popd
godep restore
```

**Comment by justinsb** [comment]
I didn't realize this was actually affecting people other than me.

Pasting the error message from Shippable in, for search purposes:

```
Starting to download all kubernetes godeps. This takes a while
package github.com/aws/aws-sdk-go/internal/endpoints
	imports github.com/aws/aws-sdk-go/internal/endpoints
	imports github.com/aws/aws-sdk-go/internal/endpoints: cannot find package "github.com/aws/aws-sdk-go/internal/endpoints" in any of:
	/root/.gvm/gos/go1.4/src/github.com/aws/aws-sdk-go/internal/endpoints (from $GOROOT)
	/tmp/gopath.N6U4vx/src/github.com/aws/aws-sdk-go/internal/endpoints (from $GOPATH)
godep: restore: exit status 1
package github.com/aws/aws-sdk-go/internal/protocol/ec2query
	imports github.com/aws/aws-sdk-go/internal/protocol/ec2query
	imports github.com/aws/aws-sdk-go/internal/protocol/ec2query: cannot find package "github.com/aws/aws-sdk-go/internal/protocol/ec2query" in any of:
	/root/.gvm/gos/go1.4/src/github.com/aws/aws-sdk-go/internal/protocol/ec2query (from $GOROOT)
	/tmp/gopath.N6U4vx/src/github.com/aws/aws-sdk-go/internal/protocol/ec2query (from $GOPATH)
godep: restore: exit status 1
package github.com/aws/aws-sdk-go/internal/protocol/query
	imports github.com/aws/aws-sdk-go/internal/protocol/query
	imports github.com/aws/aws-sdk-go/internal/protocol/query: cannot find package "github.com/aws/aws-sdk-go/internal/protocol/query" in any of:
	/root/.gvm/gos/go1.4/src/github.com/aws/aws-sdk-go/internal/protocol/query (from $GOROOT)
	/tmp/gopath.N6U4vx/src/github.com/aws/aws-sdk-go/internal/protocol/query (from $GOPATH)
godep: restore: exit status 1
package github.com/aws/aws-sdk-go/internal/protocol/rest
	imports github.com/aws/aws-sdk-go/internal/protocol/rest
	imports github.com/aws/aws-sdk-go/internal/protocol/rest: cannot find package "github.com/aws/aws-sdk-go/internal/protocol/rest" in any of:
	/root/.gvm/gos/go1.4/src/github.com/aws/aws-sdk-go/internal/protocol/rest (from $GOROOT)
	/tmp/gopath.N6U4vx/src/github.com/aws/aws-sdk-go/internal/protocol/rest (from $GOPATH)
godep: restore: exit status 1
package github.com/aws/aws-sdk-go/internal/protocol/xml/xmlutil
	imports github.com/aws/aws-sdk-go/internal/protocol/xml/xmlutil
	imports github.com/aws/aws-sdk-go/internal/protocol/xml/xmlutil: cannot find package "github.com/aws/aws-sdk-go/internal/protocol/xml/xmlutil" in any of:
	/root/.gvm/gos/go1.4/src/github.com/aws/aws-sdk-go/internal/protocol/xml/xmlutil (from $GOROOT)
	/tmp/gopath.N6U4vx/src/github.com/aws/aws-sdk-go/internal/protocol/xml/xmlutil (from $GOPATH)
godep: restore: exit status 1
package github.com/aws/aws-sdk-go/internal/signer/v4
	imports github.com/aws/aws-sdk-go/internal/signer/v4
	imports github.com/aws/aws-sdk-go/internal/signer/v4: cannot find package "github.com/aws/aws-sdk-go/internal/signer/v4" in any of:
	/root/.gvm/gos/go1.4/src/github.com/aws/aws-sdk-go/internal/signer/v4 (from $GOROOT)
	/tmp/gopath.N6U4vx/src/github.com/aws/aws-sdk-go/internal/signer/v4 (from $GOPATH)
godep: restore: exit status 1
```

**Comment by justinsb** [comment]
@dchen1107 @jimmidyson : Should I propose a PR with my above workaround in the shippable.yml file?   Or do you have a different solution in mind?

**Comment by jimmidyson** [comment]
I'm surprised it's not affecting every kubernetes PR & therefore getting more attention...

**Comment by justinsb** [comment]
I think it maybe only affects PRs that change Godeps (?).   My reading is that `hack/verify-godeps.sh` exits almost immediately if there are no changes in a PR to the Godeps dir: https://github.com/kubernetes/kubernetes/blob/master/hack/verify-godeps.sh#L42-L46

An alternative to the workaround I posted would be to fork aws-sdk-go and go back to the version where they didn't rename.  Or we could ask them to revert the change (it happened < 24 hours ago)

**Comment by jimmidyson** [comment]
@justinsb Ah yeah good spot.

**Comment by pmorie** [comment]
I think what will be needed here is to bump the affected package (`aws-sdk-go` in this case).  That is what we have had to do before with Godeps issues like this.  @ncdc, does my memory serve me?

**Comment by justinsb** [comment]
@pmorie that should work - good idea.  It does involve going to an unreleased revision, as this change was made in the last 24 hours so there hasn't been a release with this change.  But it's probably no worse than the alternatives.  Shall I submit a PR?

**Comment by justinsb** [comment]
#16245 has the fix using @pmorie 's suggestion.  It passes shippable (and it looks like shippable did run verify-godeps).  The downside is it isn't using an official release of aws-sdk-go, but it is only 3 commits ahead: one doc change, one comment change, and one huge commit which looks like a straight rename.

**Comment by eparis** [comment]
check out https://github.com/kubernetes/kubernetes/blob/master/hack/verify-godeps.sh#L24 use it around line 64 (right before `godep restore`) to solve this with 1 line in the safest possible way.  Although I think #16238 is the right 'long term' fix. If we need something on a release branch, using godep-restore is safer.

**Comment by dchen1107** [comment]
cc/ @lavalamp this is the issue which blocks us to merge @jimmidyson's pr (#16193) for cAdvisor and libcontainer for 1.1 release.

**Comment by eparis** [comment]
#16259 is the right fix for release-1.1    #16193 is not.....

**Comment by eparis** [comment]
[deleted last comment, but this issue is fixed for release-1.1 in #16259, just can't get clean shippable]

**Comment by karlkfi** [comment]
Godep author claims this is fixed: https://github.com/tools/godep/issues/186#issuecomment-164919677

**Comment by eparis** [comment]
Although one of my co-workers said he's still having problems with this (type of) issue.  We'll if/when verify-godeps throws up again.
