### ISSUE TITLE
[hyperkube:v1.0.6] cAdvisor is unsupported in this build

### ISSUE THREAD

**Issue by ltagliamonte** [kubernetes/kubernetes#16280]
I'm trying to use kubedash with heapster and influxdb, I was able to successfully deploy the apps but the kubedash doesn't have any info in it (except the created namespaces).
Digging into the logs I discovered that kubedash is receiving 500 from heapster, and in the heapster logs i can see:
```
I1026 15:23:05.012446       1 kube_nodes.go:56] Failed to get container stats from Kubelet on node "127.0.0.1"
I1026 15:23:05.012530       1 kubelet.go:96] failed to get stats from kubelet url: http://127.0.0.1:10255/stats/default/k8s-master-127.0.0.1/b178122c-7be8-11e5-92bf-080027c6e57a/controller-manager - request failed - "500 Internal Server Error", response: "Internal Error: cAdvisor is unsupported in this build\n"
I1026 15:23:05.012593       1 kube_pods.go:108] failed to get stats for container "controller-manager" in pod "default"/"k8s-master-127.0.0.1"
I1026 15:23:05.012872       1 kubelet.go:112] about to query kubelet using url: "http://127.0.0.1:10255/stats/default/k8s-master-127.0.0.1/b178122c-7be8-11e5-92bf-080027c6e57a/apiserver"
```
looking into the github issues and in hyperkube logs i see that cAdvisor is still not in the build.
Is there a way to enable it or do I have to wait the next release?
Thanks in advance for the support.

**Comment by vishh** [comment]
I believe this was fixed in HEAD #11727. v1.1 should fix this.

On Mon, Oct 26, 2015 at 9:06 AM, Luigi Tagliamonte <notifications@github.com

**Comment by ltagliamonte** [comment]
@vishh on the 1st of August @mikedanese merged the PR and on the 11th of September there was the stable release 1.0.6 that i'm running, but as I wrote it seems not fixed.

**Comment by luxas** [comment]
Fixed in `v1.1` and newer releases by #11727
