### ISSUE TITLE
Use versioned types in kubectl generators

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#17384]
Per discussion with @nikhiljindal, in generators we use unversioned types to create objects. Therefore we need to set default values manually. We should instead use versioned types.

_Description updated: changed internal/external version to unversioned/versioned types_

cc @bgrant0607

**Comment by nikhiljindal** [comment]
cc @lavalamp @kubernetes/goog-csi

**Comment by nikhiljindal** [comment]
Yes. Will update the title

**Comment by wojtek-t** [comment]
@nikhiljindal @janetkuo - can you explain what "generators" are you talking about here?

**Comment by janetkuo** [comment]
@wojtek-t generators are used to create objects in `kubectl`, see:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L113-L119
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/generate.go
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/run.go

**Comment by wojtek-t** [comment]
@janetkuo - got it. thanks!

**Comment by smarterclayton** [comment]
Done

**Comment by alexandercampbell** [comment]
@smarterclayton 
This issue is still referred to by a [TODO](https://github.com/kubernetes/kubernetes/blob/6bc0b295b59d85ffbd1ee2044d6eb2e2277d5d21/pkg/kubectl/run.go#L104-L105) in `pkg/kubectl/run.go`. Can I remove that TODO?
