### ISSUE TITLE
Override default cAdvisor housekeeping interval

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#18044]
By default cAdvisor currently gathers stats every 1 second. This is much higher than necessary for most use cases, so we should override the *default* value to `10 seconds` in the Kubelet.

The flag which needs to be modified is:
```
--housekeeping-interval=1s: Interval between container housekeepings
```

/cc @kubernetes/goog-node

**Comment by dchen1107** [comment]
cc/ @mwielgus

**Comment by mwielgus** [comment]
Why is it needed? Are we using to much memory or cpu?

**Comment by timstclair** [comment]
> Why is it needed? Are we using to much memory or cpu?

I think both, but this change was more motivated by high CPU usage in cAdvisor

**Comment by vishh** [comment]
AFAIK there is currently no use-case for metrics data with 1 second
granularity. Why store more data when it is not necessary?

**Comment by mwielgus** [comment]
Ok, can we align metrics scraping to full 10 sec? I mean scrape at
12:01:00 - e
12:01:10 - e
12:01:20 - e
where e is a random number from 0 to 1 seconds to prevent scraping all nodes at the exactly same time. So that when Heapster asks for window 12:01:00-12:01:30 at 12:01:32 it gets a sample scrapped at 
12:01:30.

**Comment by vishh** [comment]
Can we avoid using windows? Why not let heapster query every 10 seconds for
the most recent sample? I imagine we will not attempt to query that often
anyways in reality.

**Comment by timstclair** [comment]
Why does it matter if all nodes are scraped at exactly the same time? I don't think aligning the scraping time to an absolute time solves anything anyway, since the clocks are not guaranteed to be in sync.

**Comment by mwielgus** [comment]
Windows - no we cannot get rid of them. With 1000 nodes we cannot query Kubeletes for metrics at the same time - it has to happen gradually over the next 5-10 seconds or so. But we would like the end result   to be as much consistent as possible.

**Comment by vishh** [comment]
As long as heapster queries kubelet's within a 10 second window, it should
get the most recent metric. If the polling duration is much longer, the 10
second housekeeping duration doesn't matter.
Heapster can query every ~30 seconds and still get pretty accurate data.

**Comment by mwielgus** [comment]
Sure, we are not talking about metrics being perfectly in sync. I just don't want the samples to be randomly spread over 10 seconds (or more). 

Lets for a moment suppose that you increase the houskeeping duration to 1 min and we scrape every 1 min. We ask for metrics on regular basis. Every full 1 min. It would be nice if you scrape the metrics just before we ask for so that it is as fresh as possible.

Sure you may not care and scrape just after we query for data and always give us the metrics that are 1 min old instead of 2 seconds old, but why?

**Comment by vishh** [comment]
Wouldn't it be better to ensure that the polling duration of heapster > 2*
polling duration of kubelet?

**Comment by mwielgus** [comment]
Still, I would prefer to get metrics that are 1 sec old instead of polling duration old.

**Comment by yujuhong** [comment]
The metrics would could be as old as cadvisor's housekeeping interval. If you define an acceptable value for the interval, I think it's implied that you are okay with data this old. I am not sure how you're going to avoid that.

**Comment by mwielgus** [comment]
I would assume that it works in this way:

1. At time X cAdvisor starts scraping metrics
2. Once it is done at time X + scrape_time the new values are available in the API.
3. At time X + housekeeping_interval cAdvisor scrapes again.

So if I query at time X + scrape_time  I will get very fresh metrics. If I query at time 
X + housekeepig_interval - 0.5 sec the metrics will be older, but If I wait a bit and query just a second or two later I would get very fresh data again.

Am I correct?

**Comment by timstclair** [comment]
Correct, but I also agree with @yujuhong 's point. If the goal is to get infrequent metrics, but make sure they are as fresh as possible when they're gathered, a different model is needed. Either we need to switch to a push-based (watch) model, or on-demand scraping.

**Comment by vishh** [comment]
That depends on the implementation. If cAdvisor is directly surfacing
metrics data, then `scrape_time` is almost negligible.

**Comment by mwielgus** [comment]
All I want is to make X predictable. And Heapster will query at the right time.

**Comment by vishh** [comment]
`X` will always include a variable delta. Local node issues like scheduling
delays can introduce arbitrary delays.

**Comment by mwielgus** [comment]
Sure but it would be enough to know the approximate time +- 1sec and be right 99%. Then you can increase houskeeping time even to 30 sec.

**Comment by timstclair** [comment]
This sounds like adding unnecessary complexity as a hack to get "approximately" right data with no guarantees on what "approximately" means. Either we care about the freshness of the data, in which case we need a different design, or we don't. Unless I'm completely missing something? Does Kubelet make any promises about clock synchronization?

**Comment by timstclair** [comment]
Sorry, I think that sounded unnecessarily harsh. I'm just unclear on what the higher level goal is here.

**Comment by mwielgus** [comment]
I have two goals:

1) Have metrics scraped more or less a the same time so that load on one pod can be compared to the load on the other pod. With 1 sec housekeeping_interval everything was in sync. But as you are increasing the intervals the things are getting more complicated. 

2) Propagate the change in metrics to the Heapster API consumer (like Horizontal Pod Autoscaler) as fast as possible. 

With 10 sec scraping interval you are significantly increasing the latency in (2) and you are making the metrics less consistent. 

You want to reduce cpu-load and memory footprint - OK. But we can agree on the scraping timing and keep the latency/consistency at the same level as it was with 1 sec housekeeping_interval almost for free. It is just 1-2 lines of code.

**Comment by vishh** [comment]
What is the minimum resolution needed for the HPA use case?

**Comment by timstclair** [comment]
Thank you, that clarified the issue for me.

> It is just 1-2 lines of code.

That assumes node time is synchronized. Do we make any sort of promises that this is the case? Maybe it's OK to say that the issues you raised in (1) and (2) are only promised within the variation of node clocks, but if that's the case we should document that.

**Comment by mwielgus** [comment]
In clusters you usually have network provided time which gives pretty decent accuracy (up to 100ms) and synchronization. See: https://en.wikipedia.org/wiki/Network_Time_Protocol.

**Comment by vishh** [comment]
GCE guarantees time synchronization. If there is a lot of time skew, many
other things will fail including auth.

Housekeeping duration is variable. Scrape latency can be considered to be a
constant for our purposes and is currently negligible.

If we can define the minimum resolution required at the cluster level, then
kubelet can ensure that it meets those requirements with some form of an
SLO.
To make heapster robust, we will still have to deal with with a misbehaving
kubelet, possibly by recording timestamps and avoiding duplicate data.

**Comment by mwielgus** [comment]
How housekeeping duration is variable if it is set to 10 sec?

Heapster code itself doesn't depend on the metric scrape time. If you misbehave everything will still be working just the metrics accuracy will be lower and HPA will react with bigger latency because some metric change will go to the next scraping window.

**Comment by timstclair** [comment]
Ok, so we could implement a special timer for metrics scraping which triggers on `time.Now().Seconds() % housekeepingInterval`. However, if the Kubelet is under load I think the timer could trigger late, which could cause heapster's polling to miss the new metrics. If this is not a concern, I'm OK with syncronizing the scraping time.

**Comment by yujuhong** [comment]
Does heapster have access to the housekeepingInterval used by kubelet (cadvisor)? The interval could be changed by a kubelet flag easily.

I am okay with the approach, but I am not entirely convinced that this is the best way to keep the latency intact because it seems very fragile. As @timstclair pointed out, any delay in cadvisor could cause stale data.

**Comment by vishh** [comment]
IIUC the current heapster model is as follows:
1. Gather multiple metrics from the kubelet and group them into a minutely bucket.
2. Aggregate these buckets across pods.

If we were to poll the kubelet more often, then we could reduce the buckets to be 30 seconds.

Heapster will have to use time stamps and align metrics to be robust. I don't see how we can avoid that.

If heapster is resilient to node latency issues, then why do the nodes have to try to be synchronized. Unless we perform real-time scheduling, the nodes are bound to get out of sync.

**Comment by mwielgus** [comment]
@timstclair Yes, this is exactly what I'm asking for. There is already a function Truncate that does it for you. This would look more or less like this:

```go
next_housekeeping_time := time.Now().Add(housekeep_interval).Truncate(housekeep_interval).Add(small_random). 
```
I'm fine if you occasionally miss the time.

**Comment by timstclair** [comment]
Why `.Add(small_random)`?

I'm still worried that this is just going to lull us into a false sense of security, and we'll end up depending on a fragile mechanism.

**Comment by mwielgus** [comment]
This is not security, no one depends on this functionality. This is only a small tweak so that the scraped values are more useful.

small_random is to prevent all kubelets starting scrape at exactly same moment. So that there is no cluster-wide cpu hiccup at exactly same time. Small_random could be from 0 to 0.5 sec. If cpu overhead for scraping is small you can skip it.

**Comment by jimmidyson** [comment]
CPU overhead for scraping should be negligible - kubelet should be simply serializing in-memory data.

**Comment by mwielgus** [comment]
@jimmidyson  - I agree - in the ideal world it should be negligible for 30 pods. But @timothysc said (at the very beginning of this thread) that this change is driven by high cpu usage.

There is also this custom metrics thing that may require a little more cpu that "regular" metrics.

**Comment by jimmidyson** [comment]
The problem with cadvisor high CPU usage should be alleviated a bit with recent updates, need to get a release out & into kubernetes ASAP - working on it now actually.

But we shouldn't have to work around problems in cadvisor, which is another project totally within our control to fix up.

**Comment by mwielgus** [comment]
If this can be fixed soon and the CPU usage is the only problem then I would rather keep the old interval or change it only a bit (to 2 seconds for instance). Then we won't need any timing fine-tunning.

**Comment by yujuhong** [comment]
> @jimmidyson - I agree - in the ideal world it should be negligible (for 30 pods). But @timothysc said (at the very beginning of this thread) that this change was driven by high cpu usage.

There are two problems: (1) the frequency and cpu usage of stats collecting in cadvisor, and (2) the frequency and cpu usage of data scraping in heapster.
This issue targets (1), but not (2). @jimmidyson, I agree we should fix the resource usage in cadvisor itself, but if k8s doesn't require such fine-grained stats collecting, why couldn't/shouldn't we change the default cadvisor housekeeping interval for a k8s cluster?

**Comment by jimmidyson** [comment]
I wasn't saying we shouldn't change it. I can think of very few uses for second granularity, certainly not a reasonable default. All in favour of changing this interval.

**Comment by timstclair** [comment]
> but if k8s doesn't require such fine-grained stats collecting

+1

I'm still not convinced of the benefits of synchronizing the the stats gathering with 10s intervals. If we were gathering stats at 5 minute intervals (for example) it would make a lot more sense. But with 10s intervals, we're still pretty close to being at the mercy of random timing fluctuations, and still smoothing sample intervals over 60 second intervals.

**Comment by timstclair** [comment]
BTW, I agree we *should* reduce the housekeeping CPU usage, but the reality is it is still very high and increasing the housekeeping interval is a very easy way to dramatically reduce the usage. See my analysis [here](https://docs.google.com/document/d/1VTpmjCn-MDkhfNB_3yuHQK9FvVdbys8SEkCxwE4HP20/edit?usp=sharing)

**Comment by yujuhong** [comment]
BTW, custom metrics (#18295) would probably cause even higher cpu usage for cadvisor.

**Comment by jimmidyson** [comment]
So let's change the housekeeping interval as a quick win.

Can you also share the profile svgs in you analysis doc so we can see where we can improve cadvisor performance?

**Comment by timstclair** [comment]
[pprof profiles](https://drive.google.com/folderview?id=0B_-O9fAr2fafMzYyd0pNWFJQY1k&usp=sharing)

**Comment by mwielgus** [comment]
@timstclair If with 10s we are fluctuating so heavily how could we do anything when the time interval was 1 sec. Do you have data that would indicate so big fluctuations? It may be related to some other problem.

BTW, pprofs are not readable (too low resolution).

**Comment by timstclair** [comment]
The google docs preview is useless. You need to download the pprofs and open them in another viewer (chrome works well).

I don't have any data w.r.t. what kind of fluctuations we might see. The concerns are about misbehaving machines though.

**Comment by gyliu513** [comment]
@timstclair I found that Kubernetes 1.9 do not have the parameter of `--housekeeping-interval`, but Kubernetes master branch has introduced the parameter of `--housekeeping_interval` at https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/globalflags_linux.go#L47 , do you know how I can update the parameter for Kubernetes 1.9? Thanks!

**Comment by tallclair** [comment]
@gyliu513 What component are you looking at? I see the flags there in 1.9:

```shell
$ kubelet --help |& grep housekeeping
      --global-housekeeping-interval duration    Interval between global housekeepings (default 1m0s)
      --housekeeping-interval duration           Interval between container housekeepings (default 10s)
$ kubelet --version
Kubernetes v1.9.2
```
