### ISSUE TITLE
Failed to create DaemonSet using sample yaml file

### ISSUE THREAD

**Issue by dove-young** [kubernetes/kubernetes#18130]
I tried to create daemonset using this yaml sample found from daemonset guide: https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/design/daemon.md  and I've changed apiVersion <code>extensions/v1beta1</code> since <code>v1</code> does not work actually. 

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: datastore
  name: datastore
spec:
  template:
    metadata:
      labels:
        app: datastore-shard
    spec:
      nodeSelector:
        app: datastore-node
      containers:
        name: datastore-shard
        image: kubernetes/sharded
        ports:
          - containerPort: 9042
            name: main
```

But when I try to create it, the error message said

```
kubectl create -f try_daemon.yml  
error validating "try_daemon.yml": error validating data: couldn't find type: v1beta1.DaemonSet; if you choose to ignore these errors, turn validation off with --validate=false
```

Then skip validate and it said
```
kubectl create -f try_daemon.yml  --validate=false
unable to load "try_daemon.yml": json: cannot unmarshal object into Go value of type []v1.Container
```

When I query <code>v1beta1</code> api, 

```
curl http://localhost:8080/apis/extensions/v1beta1                                                                       
{
  "kind": "APIResourceList",
  "groupVersion": "extensions/v1beta1",
  "resources": [
    {
      "name": "daemonsets",
      "namespaced": true
    },
    {
      "name": "daemonsets/status",
      "namespaced": true
    },

 curl http://localhost:8080/apis/extensions/v1beta1/daemonsets
{
  "kind": "DaemonSetList",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "selfLink": "/apis/extensions/v1beta1/daemonsets",
    "resourceVersion": "298771"
  },
  "items": []
}
```

Combin different cases also failed.

```
[root@tivsun01 ~]# kubectl create -f try_daemon.yml  --validate=false                                                                       
unable to recognize "try_daemon.yml": no kind named "DaemonSets" is registered in versions ["" "extensions/v1beta1"]
[root@xxx ~]# vim try_daemon.yml                                                                                                       
[root@txxx ~]# kubectl create -f try_daemon.yml  --validate=false
unable to recognize "try_daemon.yml": no kind named "daemonsets" is registered in versions ["" "extensions/v1beta1"]
[root@xxx ~]# vim try_daemon.yml                                                                                                       
[root@xxx ~]# kubectl create -f try_daemon.yml  --validate=false
unable to recognize "try_daemon.yml": no kind named "daemonset" is registered in versions ["" "extensions/v1beta1"]
[root@xxx ~]# 
```

My environment is <code>v1.1.2</code> and here is my <code>kubernetes</code> image version. 

```
gcr.io/google_containers/kube-apiserver                       c23815ed09d218f0f551444927e84053   33b47e12ce09        2 weeks ago         47.94 MB
gcr.io/google_containers/kube-scheduler                       5b511d642ff308c8a4bd0c5c41b068a4   0c0374138b89        2 weeks ago         20.79 MB
gcr.io/google_containers/kube-controller-manager              94b57c6821892f2fffe19c31eed8cf5c   706c30f908dd        2 weeks ago         40.01 MB
```

**Comment by dove-young** [comment]
Create daemon success from admin/daemon.yaml https://github.com/kubernetes/kubernetes/blob/95b265390e530eb137beac4288ba28d63c1142da/docs/admin/daemon.yaml

So this would be a document problem

```
apiVersion: extensions/v1beta1 
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
spec:
  template:
    metadata:
      name: prometheus-node-exporter
      labels:
        daemon: prom-node-exp
    spec:
      containers:
      - name: c
        image: prom/prometheus
        ports:
        - containerPort: 9090
          hostPort: 9090
          name: serverport
```

**Comment by mml** [comment]
I ran into this as well.  Fixing the docs is one thing, but that error message is useless.  Why should we need --validate=false?

**Comment by mml** [comment]
I was able to get this to work after I did two things.

1. I had to manually clear ~/.kube/schema.  There appears to be a cache invalidation bug there and I had cached an old version of the schema from an api server with *the same version* but without daemonsets enabled, hence the cached schema knew nothing about daemonsets.
2. I had to add `selector: {}` to the spec.  Well, I could add a different selector, but no matter what I set it to, when I later `GET` the daemonset, it always comes back with `selector: {}`.

If I leave out `selector` entirely, I still get this opaque message:

```
Error from server: error when creating "ds.yaml": DaemonSet in version extensions/v1beta1 cannot be handled as a DaemonSet: [pos 219]: json: expect char '"' but got char '{'
```
So, three items: fix the docs (this bug), file a bug about the schema cache, and file a bug about the horrible error message.

Below is a file that worked:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
spec:
  selector: {}                                                                                                                                                                                         
  template:
    metadata:
      name: prometheus-node-exporter
      labels:
        daemon: prom-node-exp
    spec:
      containers:
      - name: c
        image: prom/prometheus
        ports:
        - containerPort: 9090
          hostPort: 9090
          name: serverport
```

**Comment by mml** [comment]
Oh, and file a bug about the daemonset spec.selector getting clobbered.

**Comment by mikedanese** [comment]
It appears that the documentation is wrong in release-1.1 but fixed on master.

**Comment by 2opremio** [comment]
In case it helps anybody else, I had to remove `/tmp/kubectl.schema`, not `~/.kube/schema`

**Comment by mml** [comment]
As @mikedanese said this is fixed at head.

**Comment by davidwalter0** [comment]
GKE: using the same recipe as above and removing the schema [/tmp/kubectl.schema directory] fails with the active version: 1.1.7

Should daemonsets work?

`kubectl create -f sample.yaml`
`error validating "sample.yaml": error validating data: couldn't find type: v1beta1.DaemonSet; if you choose to ignore these errors, turn validation off with --validate=false`

`kubectl create -f sample.yaml --validate=false
Error from server: error when creating "sample.yaml": the server could not find the requested resource`


```Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}```

``` curl localhost/apis/extensions/v1beta1; kubectl version
{
  "kind": "APIResourceList",
  "groupVersion": "extensions/v1beta1",
  "resources": [
    {
      "name": "horizontalpodautoscalers",
      "namespaced": true
    },
    {
      "name": "horizontalpodautoscalers/status",
      "namespaced": true
    },
    {
      "name": "ingresses",
      "namespaced": true
    },
    {
      "name": "ingresses/status",
      "namespaced": true
    },
    {
      "name": "jobs",
      "namespaced": true
    },
    {
      "name": "jobs/status",
      "namespaced": true
    },
    {
      "name": "replicationcontrollers",
      "namespaced": true
    },
    {
      "name": "replicationcontrollers/scale",
      "namespaced": true
    }
  ]
}```

**Comment by Miyurz** [comment]
We are still seeing this on k8s version 1.5.4 

`helm install fluentd*.tgz --name fluentd --namespace kube-system
Error: release fluentd failed: DaemonSet in version "v1beta1" cannot be handled as a DaemonSet: [pos 793]: json: expect char '"' but got char '9'`
