### ISSUE TITLE
Clearer policies for flaky test fixes

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18303]
We need a clearer policy for how people should be prioritizing fixing flaky tests.  Our updated policy (as of this morning) is that, if you have a flaky test assigned to you, that is your _first priority_.

@lavalamp Will you update the email language please?

xref https://github.com/kubernetes/contrib/pull/274

cc @kubernetes/goog-testing @quinton-hoole @zmerlynn @lavalamp

**Comment by ihmccreery** [comment]
(It's been noted that the build cop can't 'crack the whip,' because build cop is a rotating position.)

**Comment by ihmccreery** [comment]
@fabioy mentions that we might want to publish numbers of PRs (and LOC?) merged everyday, so we have a sense of our velocity.

**Comment by ixdy** [comment]
GitHub has some of this, though it's not necessarily the most usable.

https://github.com/kubernetes/kubernetes/graphs/commit-activity is one example.

**Comment by lavalamp** [comment]
The email language has been updated. I agree we should add a carrot to the email (flaky tests fixed in the last week?) I'll leave this open until I find some time to add it.

**Comment by kargakis** [comment]
Pretty sure there is some machinery in test-infra about this but I am going to defer to @kubernetes/sig-testing-misc

**Comment by spiffxp** [comment]
I agree there is some test-infra machinery, but in terms of documented/enforced carrot/stick policy, we're still not there.
