### ISSUE TITLE
EBS volume mount failures due to "... already attached to an instance" are not retried

### ISSUE THREAD

**Issue by erikswanson** [kubernetes/kubernetes#18785]
I'm testing out how Kubernetes handles minion faults with regards to EBS persistent volumes.

## Test Case

*   Create EBS volume with `aws ec2 create-volume ...`
*   Launch a replication controller with replicas=1 that references the volume.
*   Wait for the pod to be successfully started, optionally use it a bit. (In this case I set up a replication controller-based version of the mysql + wordpress example, and did stuff with wordpress.)
*   Discover which ec2 instance (minion) the mysql pod is running on.
*   Terminate that minion (`aws ec2 terminate-instances ...`)

## Expected outcome

*   The new pod successfully starts on a different minion.
*   The volume is attached successfully.
*   Human intervention is never required to allow replicas=1 with an EBS volume to recover when a minion stops working.

## Actual outcome

*   The new pod is scheduled to a different minion
*   The pod is stuck in "Pending" because there was a transient failure attaching the EBS volume and the attachment was never retried.
*   The replication controller keeps waiting on the permanently "Pending" pod. (25 minutes so far)

## Observations

The replication almost certainly happened before the old minion's instance was finished terminating. The volume has shown as "available" for a while now. 

Deleting the pod with `kubectl delete pod mysql-fia7i` resulted in a near-immediate restoration of service, as the new pod successfully mounted the volume.

Note for re-creating this result: The mysql container will fail to launch without enough ram. (It will never succeed with the default t2.micro instance size.) I did this test with `MINION_SIZE=t2.medium`.

#### Output of `kubectl.sh describe pod ...`

    Name:       mysql-fia7i
    Namespace:      default
    Image(s):     mysql:5.6
    Node:       ip-172-20-0-203.us-west-2.compute.internal/172.20.0.203
    Start Time:     Wed, 16 Dec 2015 12:35:42 -0800
    Labels:       name=mysql
    Status:       Pending
    Reason:       
    Message:      
    IP:       
    Replication Controllers:  mysql (1/1 replicas created)
    Containers:
      mysql:
        Container ID: 
        Image:    mysql:5.6
        Image ID:   
        QoS Tier:
          cpu:  Guaranteed
        Limits:
          cpu:  500m
        Requests:
          cpu:    500m
        State:    Waiting
          Reason:   ImageNotReady
        Ready:    False
        Restart Count:  0
        Environment Variables:
          MYSQL_ROOT_PASSWORD:  *redacted*
    Conditions:
      Type    Status
      Ready   False 
    Volumes:
      mysql-persistent-storage:
        Type: AWSElasticBlockStore (a Persistent Disk resource in AWS)
        VolumeID: aws://us-west-2a/vol-5cfc4bab
        FSType: ext4
        Partition:  0
        ReadOnly: false
      default-token-crmj1:
        Type: Secret (a secret that should populate this volume)
        SecretName: default-token-crmj1
    Events:
      FirstSeen LastSeen  Count From              SubobjectPath Reason    Message
      ───────── ────────  ───── ────              ───────────── ──────    ───────
      25m   25m   1 {scheduler }                Scheduled Successfully assigned mysql-fia7i to ip-172-20-0-203.us-west-2.compute.internal
      25m   25m   1 {kubelet ip-172-20-0-203.us-west-2.compute.internal}      FailedMount Unable to mount volumes for pod "mysql-fia7i_default": Error attaching EBS volume: VolumeInUse: vol-5cfc4bab is already attached to an instance
        status code: 400, request id: 
      25m   25m 1 {kubelet ip-172-20-0-203.us-west-2.compute.internal}    FailedSync  Error syncing pod, skipping: Error attaching EBS volume: VolumeInUse: vol-5cfc4bab is already attached to an instance
        status code: 400, request id: 
      25m   25m 2 {kubelet ip-172-20-0-203.us-west-2.compute.internal}    FailedMount Unable to mount volumes for pod "mysql-fia7i_default": Could not attach disk: Timeout after 10s (/dev/xvdf)
      25m   25m 2 {kubelet ip-172-20-0-203.us-west-2.compute.internal}    FailedSync  Error syncing pod, skipping: Could not attach disk: Timeout after 10s (/dev/xvdf)
      24m   12s 24  {kubelet ip-172-20-0-203.us-west-2.compute.internal}    FailedMount Unable to mount volumes for pod "mysql-fia7i_default": Timeout waiting for volume state
      24m   12s 24  {kubelet ip-172-20-0-203.us-west-2.compute.internal}    FailedSync  Error syncing pod, skipping: Timeout waiting for volume state

#### Replication controller yaml

    apiVersion: v1
    kind: ReplicationController
    metadata:
      name: mysql
      labels:
        name: mysql
    spec:
      replicas: 1
      selector:
        name: mysql
      template:
        metadata:
          labels:
            name: mysql
        spec:
          containers:
            - resources:
                limits :
                  cpu: 0.5
              image: mysql:5.6
              name: mysql
              env:
                - name: MYSQL_ROOT_PASSWORD
                  # change this
                  value: *redacted*
              ports:
                - containerPort: 3306
                  name: mysql
              volumeMounts:
                  # name must match the volume name below
                - name: mysql-persistent-storage
                  # mount path within the container
                  mountPath: /var/lib/mysql
          volumes:
            - name: mysql-persistent-storage
              awsElasticBlockStore:
                volumeID: aws://us-west-2a/vol-5cfc4bab
                fsType: ext4

**Comment by jlowdermilk** [comment]
cc @justinsb

**Comment by swagiaal** [comment]
Supporting this requires the Attach/Detach controller which is proposed in #15524. That will solve the issue for all volumes not just EBS

**Comment by sstarcher** [comment]
@jmccarty3 this looks like the issue

**Comment by bgrant0607** [comment]
cc @kubernetes/goog-cluster

**Comment by chbatey** [comment]
Hey @justinsb this happens even if it is already attached to the instance kubelet is trying to attach it to. Would you accept a PR that checks this and succeeds in this scenario? 

This happened when the initial attach timed out but eventually succeeded and then failed on retry due to already being attached.

**Comment by justinsb** [comment]
Fixes very welcome! I've been meaning to get to this but haven't got to it
yet...

**Comment by saad-ali** [comment]
> Hey @justinsb this happens even if it is already attached to the instance kubelet is trying to attach it to. Would you accept a PR that checks this and succeeds in this scenario?

Simply succeeding if disk is already attached may expose nastier bugs: see https://github.com/kubernetes/kubernetes/issues/19953#issuecomment-174876432. The proposed fix, on the GCE side, is a larger redesign that should fix this for all volumes, see https://github.com/kubernetes/kubernetes/issues/21931.

> This happened when the initial attach timed out but eventually succeeded and then failed on retry due to already being attached.

https://github.com/kubernetes/kubernetes/pull/15938 introduced more robust retry logic for AWS EBS. But if the retries fail (because volume is already attached), it's pretty useless. I would be ok with adding logic to selectively succeed in this case--but I'd strongly suggest testing the rapid attach/detach (i.e. rapid pod creation deletion) scenario before/after any proposed fix.

**Comment by saad-ali** [comment]
This is fixed in v1.3 by #26351

**Comment by jeffersongirao** [comment]
Hey @saad-ali, I'm running v1.3 but still facing some issues with EBS volume attachments. At first we get the same error "Error attaching EBS volume: VolumeInUse: vol-xxxxx is already attached to an instance", after that first error pop up, it keeps getting "Timeout waiting for volume state". This happens every time the pod is rescheduled to a different worker and I have to "force dettach" through AWS in order to get it back. Any idea?

**Comment by saad-ali** [comment]
@jeffersongirao What is your scenario exactly? That you have a pod scheduled to node X using an AWS EBS volume, and then you terminate node X? If that is the case, the attach/detach controller [will wait 6 minutes](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/attach_detach_controller.go#L53) for the volume to be safely unmounted before unilaterally detaching the volume making it available to other nodes.

**Comment by jeffersongirao** [comment]
@saad-ali nevermind, I tried to get more data on the issue and in end it was a problem on the AWS side, I had a few borked volumes (perhaps because my "force" detach tentatives), their support helped me. But the case looked like what you described, pod scheduled to node x, pod terminated, pod re-scheduled to node y, ebs volume dettached properly from node x, volume stays in "attaching" state to node y forever and we get "Timeout waiting for volume state". Thanks for following up.

**Comment by saad-ali** [comment]
@jeffersongirao No problem! Glad the issue is resolved.

**Comment by hybmg57** [comment]
I still have this issue. I've stopped one of my EC2 instances using EBS 'StorageClass' and PVC and I get the similar error as @erikswanson  'FailedMount Unable to mount volumes for pod "mysql-fia7i_default": Error attaching EBS volume: VolumeInUse: vol-5cfc4bab is already attached to an instance'

Basically deployment stops and Jenkins is not recovered automatically on another live node with EBS detaching from dead node and attaching on new node

**Comment by propyless** [comment]
I've also seen this in latest 3.6 release as of writing.

**Comment by razvan-miron** [comment]
Same here. 
Running 3.6 release with AWS persistent storage on the monitoring. 

(combined from similar events): Failed to attach volume "pvc-xxxx" on node "ip-xxx-xxx-xxx-xxx.eu-west-1.compute.internal" with: Error attaching EBS volume "vol-xxxxxx" to instance "i-08dd5042d2a91f64a": VolumeInUse: vol-xxxx is already attached to an instance status code: 400, request id: xxxxx. The volume is currently attached to instance "xxxx"
8308 times in the last
