### ISSUE TITLE
Codecgen diff in master

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#18907]
I get a diff when I run hack/update-codecgen in master, and the validation script fails it.  That seems wrong.

Changed files afterward:

```
$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   cmd/libs/go2idl/client-gen/testdata/apis/testgroup/types.generated.go
        modified:   cmd/libs/go2idl/client-gen/testdata/apis/testgroup/v1/types.generated.go
        modified:   pkg/apis/extensions/types.generated.go
        modified:   pkg/apis/extensions/v1beta1/types.generated.go
        modified:   pkg/apiserver/testing/types.generated.go
        modified:   pkg/kubectl/testing/types.generated.go
        modified:   pkg/storage/testing/types.generated.go
```

@ncdc has been able to reproduce something similar, but not exactly equivalent.

I'm running go 1.5.1 on Fedora 22

**Comment by ncdc** [comment]
I just get the 1st 2 files listed above

**Comment by pmorie** [comment]
I've updated to the latest godep version and rebuilt from latest master, same result.

**Comment by pmorie** [comment]
I downgraded to golang 1.4.2, rebuilt stdlib, clean build, regen, and I get no diffs.  So, seems like this points to the output of codecgen being different under golang 1.4 and 1.5.

**Comment by pmorie** [comment]
Okay, seems like this is not an issue, since we don't support 1.5.  I think perhaps we should have codecgen bail out if you're running under 1.5 -- any thoughts about that?

**Comment by brendandburns** [comment]
Yeah, I saw this too, and it seems to change Linux vs OS X also.  This makes me grumpy, I assume it's something to do with the random generator we're using?  We should probably switch to some sort of consistent random number/symbol generator.

--brendan

**Comment by pmorie** [comment]
@brendandburns It's a killer if you're on a stack that happens to not play nice

**Comment by pmorie** [comment]
omg.  I am now seeing the same behavior under go 1.4...

**Comment by smarterclayton** [comment]
I've seen it in 1.5 Mac and 1.4 Linux (although I can double check).

**Comment by smarterclayton** [comment]
Although in my case I got stability on an individual platform.

**Comment by pmorie** [comment]
I _think_ this is resolved now, closing.  I'll reopen if I run into it again.

**Comment by madhusudancs** [comment]
This problem is causing immense pain and has been a huge productivity sink over the last few weeks. So I thought of taking a look at it over the long weekend. 

I think this is due to a bug in our hack/update-codecgen.sh script, not golang version or the OS. #19768 is the proposed fix for this issue.

**Comment by BugRoger** [comment]
I'm sure this is my ignorance but i'm still seeing the bug described here on Linux, Go 1.5.3.

Running hack/update-codecgen generates types which get rejected by hack/verify-codecgen. Obviously also Travis doesn't like them. This is on a branch which does have API changes in it.

Comparing update-codecgen and verify-codecgen leads me to believe that the code generator produces different code depending on whether the generated files already exist or not. Maybe the dependency ordering is still wrong and it uses outdated inputs.

My solution was to comment these 3 lines to make both scripts consistent:
https://github.com/kubernetes/kubernetes/blob/master/hack/update-codecgen.sh#L100-L102

Then regenerate the code, then verify works, build is green. But something does not sit right with this still...

**Comment by madhusudancs** [comment]
@BugRoger Do you have this commit https://github.com/madhusudancs/kubernetes/commit/1511466b9dabaa1f5c089cb6734e63d35cba9116 in your branch?

> Comparing update-codecgen and verify-codecgen leads me to believe that the code generator produces different code depending on whether the generated files already exist or not.

That's a correct.

> Maybe the dependency ordering is still wrong and it uses outdated inputs.

Unlikely, but not impossible.

> My solution was to comment these 3 lines to make both scripts consistent:
https://github.com/kubernetes/kubernetes/blob/master/hack/update-codecgen.sh#L100-L102
> Then regenerate the code, then verify works, build is green. But something does not sit right with this still...

I am afraid this might produce incorrect results depending on where and what types you are introducing/changing, particularly if dependency ordering problem is still not fixed.

Could you please link me to your PR/branch?

**Comment by BugRoger** [comment]
> I am afraid this might produce incorrect results depending on where and what types you are introducing/changing, particularly if dependency ordering problem is still not fixed.
I'm afraid that is true and I'm just deferring the problem to the next person running the generation... Thanks for checking in.

> Could you please link me to your PR/branch?
https://github.com/kubernetes/kubernetes/pull/20069

**Comment by madhusudancs** [comment]
@BugRoger Figured out what the problem and purely by coincidence ;-)

So I think the problem is with your setup. You don't have the Kubernetes source checked out in a directory under k8s.io, do you? ;-)

**Comment by BugRoger** [comment]
@madhusudancs Of course, you are right. I had my code in `/home/bugroger/k8s.io/kubernetes`. I should have taken the note quite literally. Thanks for your help... :blush:

For what it's worth the code generated is the same as with my workaround. Now everything is good. Though this behavior is quite counter-intuitive...

**Comment by madhusudancs** [comment]
@BugRoger No worries. I think it is worth mentioning this as a note or a warning in [development.md](https://github.com/kubernetes/kubernetes/blob/e33b9a9460113c4fe1e41dd9b4fa4c36a973ef9a/docs/devel/development.md#clone-your-fork).
