### ISSUE TITLE
Jenkins unit test failures

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18960]
I've seen a bunch of times Jenkins failures like this:

 > git checkout -f 816f93bdbab33cd1b96c7d5de66b39d214a9c50b
FATAL: Could not checkout 816f93bdbab33cd1b96c7d5de66b39d214a9c50b
hudson.plugins.git.GitException: Could not checkout 816f93bdbab33cd1b96c7d5de66b39d214a9c50b

Maybe we should retry it?

@kubernetes/goog-testing

**Comment by spxtr** [comment]
I'm looking into this.

**Comment by ixdy** [comment]
Not sure of a root cause, but I think this started happening more frequently when I started checking out the release branch (in addition to the PR merge branch) to support #18047.

**Comment by spxtr** [comment]
I reset the PR builder job config to the format recommended [here](https://github.com/jenkinsci/ghprb-plugin). If that doesn't fix this then I'll set it back.

**Comment by spxtr** [comment]
[No  luck](http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-test-unit-integration/6990/console).

```bash
11:38:32 Fetching upstream changes from https://github.com/kubernetes/kubernetes
11:38:32  > git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/*:refs/remotes/origin/pr/* --prune
11:38:35 ERROR: Error fetching remote repo 'origin'
11:38:35 hudson.plugins.git.GitException: Failed to fetch from https://github.com/kubernetes/kubernetes
11:38:35 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:763)
11:38:35 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1012)
11:38:35 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1043)
11:38:35 	at hudson.scm.SCM.checkout(SCM.java:485)
11:38:35 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1276)
11:38:35 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
11:38:35 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
11:38:35 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
11:38:35 	at hudson.model.Run.execute(Run.java:1738)
11:38:35 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
11:38:35 	at hudson.model.ResourceController.execute(ResourceController.java:98)
11:38:35 	at hudson.model.Executor.run(Executor.java:410)
11:38:35 Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/*:refs/remotes/origin/pr/* --prune" returned status code 128:
11:38:35 stdout: 
11:38:35 stderr: error: RPC failed; result=18, HTTP code = 200
11:38:35 fatal: The remote end hung up unexpectedly
11:38:35 
11:38:35 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1640)
11:38:35 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1388)
11:38:35 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:62)
11:38:35 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:313)
11:38:35 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
11:38:35 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
11:38:35 	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
11:38:35 	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
11:38:35 	at hudson.remoting.Request$2.run(Request.java:326)
11:38:35 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
11:38:35 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
11:38:35 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11:38:35 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
11:38:35 	at java.lang.Thread.run(Thread.java:745)
11:38:35 	at ......remote call to builder-1(Native Method)
11:38:35 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
11:38:35 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
11:38:35 	at hudson.remoting.Channel.call(Channel.java:781)
11:38:35 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
11:38:35 	at sun.reflect.GeneratedMethodAccessor294.invoke(Unknown Source)
11:38:35 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:38:35 	at java.lang.reflect.Method.invoke(Method.java:606)
11:38:35 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
11:38:35 	at com.sun.proxy.$Proxy62.execute(Unknown Source)
11:38:35 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:761)
11:38:35 	... 11 more
11:38:35 ERROR: null
```

**Comment by spxtr** [comment]
Waiting for another failure. Please link here if you notice one.

**Comment by spxtr** [comment]
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-test-unit-integration/7016/console

**Comment by wojtek-t** [comment]
I've seen it at least 5-10 times today. One example:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/4aa2121a8e19347b67866cccd5bea738049018d7/kubernetes-pull-test-unit-integration/7063/?debugUI=DEVELOPERS

**Comment by spxtr** [comment]
I set `git config --global http.postBuffer 524288000` as suggested in several places. LMK if it fails again.

**Comment by spxtr** [comment]
Still failing ~1/20

**Comment by gmarek** [comment]
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/1df78a239879db73d6ca831e850c289e38393a8b/kubernetes-pull-test-unit-integration/7533/build-log.txt

From #19142

**Comment by spxtr** [comment]
We had three clone fails this morning coinciding with a github [problem](https://twitter.com/githubstatus/status/681884105533997056). The builds ([7598](http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-test-unit-integration/7598/console), [7599](http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-test-unit-integration/7599/console), [7600](http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-test-unit-integration/7600/console)) clones started failing at 8:58 AM PST until 9:08, github said they're looking into "increased error rates with some git operations" at 9:07 and said it was fixed at 9:24.

I'm starting to think we should start manually cloning the repositories so that we can retry a few times if they fail. I'm also having trouble reproducing this on PR Jenkins.

**Comment by wojtek-t** [comment]
I agree that it's probably more than 5%...

I've seen this problem multiple times during the day, and IIUC there weren't any github issues at that time.
Maybe just retrying on failure from github would help?

**Comment by wojtek-t** [comment]
This has just happened to me:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/baf97c9c5e51b1208e9f8fdaa05f780a636204b0/kubernetes-pull-test-unit-integration/7643/?debugUI=DEVELOPERS

There doesn't seem to be any github issues now...

**Comment by spxtr** [comment]
Set PR Jenkins SCM checkout retry count to 3 (It's under Manage Jenkins > Configure System). I have a feeling this won't work completely since we tend to get bursts of these failures, but it should help.

**Comment by spxtr** [comment]
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-test-unit-integration/7715/console

Tried three times and it worked on the third. I still have no idea why this is happening on this job and not the others, but it should cause fewer red lights with the retries.

**Comment by spxtr** [comment]
Still fails occasionally, as in [7896](http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-test-unit-integration/7896/console), but succeeds with retries often [7891](http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-test-unit-integration/7891/consoleFull). I'll up the retry-count to 5.

**Comment by spxtr** [comment]
I switched on `GIT_CURL_VERBOSE` and got this error:

```
> POST /kubernetes/kubernetes/git-upload-pack HTTP/1.1
User-Agent: git/[IP REMOVED]
Host: github.com
Accept-Encoding: deflate, gzip
Content-Type: application/x-git-upload-pack-request
Accept: application/x-git-upload-pack-result
Content-Encoding: gzip
Content-Length: 343668
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-upload-pack-result
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-GitHub-Request-Id: 17EC3941:448D:348ABA41:568C027A
< 
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* transfer closed with outstanding read data remaining
* Closing connection #0
error: RPC failed; result=18, HTTP code = 200
fatal: The remote end hung up unexpectedly
```
It looks like others have had the same issue. I'll keep trying fixes.

**Comment by caesarxuchao** [comment]
@spxtr, looks like checking out release branch doesn't cause this flake, right? #18047 needs the release branch, so could you please re-enable the checkout, perhaps after you fix this issue?

**Comment by spxtr** [comment]
I switched this back to the old behavior, where we fetch based on a more specific spec than the plugin authors recommend, and I haven't seen this all day. If it's still okay in another couple days I'll re-enable checking out release branches, and if it's still okay after a few days I'll close this.

**Comment by spxtr** [comment]
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-test-unit-integration/8379/console

Here the problem was that it was trying to pull a commit that had been force-pushed away in the PR. Looks like it might be a ghprb bug.

**Comment by spxtr** [comment]
Okay, I think this is fixed.

I set the branch to build to `origin/pr/${ghprbPullId}/merge` instead of `${sha1}` so that we would ignore GitHub Pull Request Builder plugin's attempts at rebuilding previous failed commits that have been overwritten with a force push.

**Comment by caesarxuchao** [comment]
@spxtr, good job! Thanks for fixing the issue. It seems Jenkins still does not fetch the release branch, could you turn that on?

**Comment by spxtr** [comment]
They should be available now. They were previously fetched as `origin/release-1.1`, but I dropped the `origin` part.

**Comment by caesarxuchao** [comment]
@spxtr, I still see `output: fatal: Not a valid object name upstream/release-1.1` in recent Jenkins builds, do you know why? Thanks.

**Comment by spxtr** [comment]
Yes, I was checking them out as just release-1.1, not upstream/release-1.1. I changed it, let me know how it works.

**Comment by caesarxuchao** [comment]
@spxtr Thanks. Is it possible to check them out as upstream/release-1.1? I hope the name can be as specific as possible, because if a user named a local branch as `release-1.1`, it will cause #18047 behave strangely.

**Comment by spxtr** [comment]
Try again. It should work now.
