### ISSUE TITLE
hack/verify-codecgen.sh keeps complaining even after hack/update-codecgen.sh

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#19437]
`hack/verify-codecgen.sh` keeps telling me to run `hack/update-codecgen.sh` even after I did it. 
See https://github.com/kubernetes/kubernetes/pull/19382#issuecomment-170176934

cc @wojtek-t

**Comment by wojtek-t** [comment]
I'm on paternity leave now - I think that "readlinkdashf" may be incorrect. We need to generate files in the order of dependency (the files that depend on others should be generated later).

**Comment by kevin-wangzefeng** [comment]
I met the same problem. And I did a test on the latest master(ce9b117a195a07445e5228003d2fc1038e110db1), just run `hack/update-codecgen.sh` without any other code change, and it results in
```
	modified:   pkg/apis/extensions/types.generated.go
	modified:   pkg/apiserver/testing/types.generated.go
	modified:   pkg/kubectl/testing/types.generated.go
	modified:   pkg/storage/testing/types.generated.go
```
And then `hack/verify-codecgen.sh` tells to run `hack/update-codecgen.sh`

My `GOPATH` is `/root/go_workspace/`, and I'm working under `$GOPATH/src/k8s.io/kubernetes/`

**Comment by janetkuo** [comment]
This issue is now fixed by #19768.

**Comment by kevin-wangzefeng** [comment]
Thanks for the update.

**Comment by BugRoger** [comment]
I'm sure this is my ignorance but i'm still seeing the bug described here.

Running `hack/update-codecgen` generates types which get rejected by `hack/verify-codecgen`. Obviously also Travis doesn't like them. This is on a branch which does have API changes in it.

Comparing `update-codecgen` and `verify-codecgen` leads me to believe that the code generator produces different code depending on whether the generated files already exist or not. Maybe the dependency ordering is still wrong and it uses outdated inputs.

My solution was to comment these 3 lines to make both scripts consistent:
https://github.com/kubernetes/kubernetes/blob/master/hack/update-codecgen.sh#L100-L102

Then regenerate the code, then verify works, build is green. But something does not sit right with this still...
