### ISSUE TITLE
kubelet sets veth hairpin mode regardless of network plugin

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#19766]
From another issue, @shettyg said:

> I connect my pod interface to a Open vSwitch bridge. Since this code does not find a peer interface on a linux bridge,
> it just enabled hairpin mode in every linux bridge on my host. This completely breaks my host where I do not want hair
> pin mode enabled. It took me a good 2 days to figure out why things break in my setup. This feels like a very bad way
> to solve problems.

DockerManager.SyncPod() calls the network Plugin and then sets hairpin mode unilaterally.  This is wrong. We should either pass the `configureCBR0` bool down to here or else we should get rid of the default no-op plugin and use the non-existence of a plugin as a flag to control this.

This should be a relatively easy one for people who want to contribute but don't know where to start.

**Comment by AdoHe** [comment]
@thockin I volunteer myself to do this. Actually I have done something about kubernetes network plugin so guess I can do this. I will start to do this when I am on the office tomorrow.

**Comment by thockin** [comment]
Awesome.  I'd advise starting with a sketch so we can all make sure it is a
good approach, before jumping in with both feet.

**Comment by AdoHe** [comment]
@thockin ok, I will start with a sketch as soon as possible.

**Comment by AdoHe** [comment]
@thockin I thought about this for a while: if we pass the `configureCBR0` bool down to here, of course we can check this flag, if it is set, we should set veth hairpin mode, but problem is that if user set this flag,  but still use a custom network plugin just like you mentioned the ovs plugin, I am afraid we will still enable hairpin mode in all interfaces on this host, since we cannot find a peer interface. Is that correct?

**Comment by thockin** [comment]
Yeah, I think the better fix is to use the existence of a network plugin as
an indicator.  It sort of makes --configure-cbr0 redundant

**Comment by AdoHe** [comment]
@thockin ok, I will try to get rid of the default no-op plugin and use the non-existence of a plugin as a flag to control this.

**Comment by AdoHe** [comment]
@thockin I decided to use the existence of a network plugin as an indicator, also I will get ride of the no-op network plugin, I am not going to add new flag to kubelet structure, if the user don't specify network plugin name, the networkPlugin within kubelet will be `nil` which just means non-existence of a plugin, and also we have to check the existence in the docker manager to avoid nil pointer exception. How about this? Should I open a PR?

**Comment by alex-mohr** [comment]
fyi, saw a hairpin pr #19490 today that might be related.  ymmv.

**Comment by AdoHe** [comment]
@alex-mohr I think this pr can fix this issue more or less, but `it just enabled hairpin mode in every linux bridge on my host.` I think this problem still exists.

**Comment by AdoHe** [comment]
@thockin what do you think about this?

**Comment by thockin** [comment]
What you described sounds right to me.  I think the only way to see if
there is some detail I am missing is to try it and see if anything pops up
that would make this not work.

**Comment by MikaelCluseau** [comment]
I need to check which part is responsible of what, but what if the hairpin package was just a utility package that should be called the plugin if it needs to set this up? As long as it is single and simple function call, doing so would avoid adding extra logic here and fix the issue. This is valid only if the aim is to have a "linux bridge plugin", an "OVS plugin", etc.

**Comment by AdoHe** [comment]
@MikaelCluseau actually kubelet will call `hairpin.SetUpContainer` after `networkPlugin.SetUpPod` get called, I think to make the network plugin can call hairpin package is not that easy, of course, I agree that network plugin should setup hairpin mode if it really needs, kubelet should not set hairpin mode unilaterally. Besides, kubelet is not going to provide an "linux bridge plugin" or "OVS plugin".

**Comment by MikaelCluseau** [comment]
@AdoHe then the validity conditions of my comment are not met, so I see any simpler way. Thanks for checking! :)

**Comment by AdoHe** [comment]
@MikaelCluseau still what do you think about disable hairpin completely and leave this to network plugin?

**Comment by AdoHe** [comment]
@MikaelCluseau or if there is a custom network plugin, we don't setup hairpin mode, only do this in default.

**Comment by MikaelCluseau** [comment]
Completely? It will break my use case (and anyone using Apache Kafka).

**Comment by MikaelCluseau** [comment]
Only by default is what I understood from the previous comments, and LGTM.

**Comment by AdoHe** [comment]
@MikaelCluseau Really sorry about that, but I really want to know are you using a kubelet network plugin in your use case? If no, I think we will still setup hairpin, as in default we will do this.

**Comment by MikaelCluseau** [comment]
I don't use any plugin, so it is ok if hairpin is set up by default.

**Comment by AdoHe** [comment]
@MikaelCluseau ok, I think this will not break your use case.

**Comment by danwinship** [comment]
> I agree that network plugin should setup hairpin mode if it really needs, kubelet should not set hairpin mode unilaterally.

It's not really the network plugin that needs hairpin_mode though, it's the pure-iptables-based kube-proxy code. It's possible the proxying code could change again in the future in such a way that hairpin_mode wouldn't be needed any more. So it seems wrong to put that code into the plugin. #19490 makes it so that we set hairpin_mode on the veth if it's attached to a bridge, but just silently do nothing if it's not.

(Yes, we currently set hairpin_mode even if you're using the userspace proxier, but AFAIK it's not needed in that case.)

**Comment by MikaelCluseau** [comment]
IMHO...

The proxy has the responsibility of service objects, while the kubelet is responsible of pod objects, including their networking. Also, the responsibility of hairpin must be at the same place as the code that creates the network interface, otherwise you have code managing a single object (the pod interface) spread over multiple programs, which will eventually lead to complex problems and a system harder to understand even for the end-user. Thus, it doesn't seems wrong to me that the kubelet does whatever is required to make the pod work in the environment of the cluster.

While its true that the hairpin requirement is only for the proxy in iptables mode, a switch to this mode can happen at any time in the life of the cluster. And when it happens, its probably because the userland proxy becomes unresponsive, which means in a situation where the administrator is in a hurry to find a solution. Currently, you just change the proxy mode and restart the proxies. There's little chance the administrator will think about hairpin or restarting the kubelet in this case, so the kubelet should be reacting to this; which means the proxy and the kubelet of a given host should be able to communicate (AFAIK, this doesn't exist now). And all this is currently only to avoid setting up hairpin on the pod's port of standard Linux bridge.

**Comment by bboreham** [comment]
Feel sure I'm missing something but...

The CNI bridge plugin now has a `hairpinMode` flag, so kubenet can use that.

Having done that, we can set `DockerManager.configureHairpinMode` false when the plugin name is non-blank.

**Comment by thockin** [comment]
Is this fixed now?

**Comment by bboreham** [comment]
I apologise for leaving a somewhat vague answer, but I have been in that code recently. I don't think it's fixed.

**Comment by thockin** [comment]
@freehan @mrhohn

**Comment by freehan** [comment]
Thanks for the PR. 

CNI Bridge plugin is expecting `hairpinMode`. Not `hairpin`. Hence the bridge plugin did not recognize it and set hairpin mode.

**Comment by bboreham** [comment]
I suggest this should be re-opened.  The chain of calls is:

https://github.com/kubernetes/kubernetes/blob/90662534911a3618fe0ccc319e7e731c0f3b7403/pkg/kubelet/kubelet.go#L643 sets `hairpinMode` to `true`, e.g. when using CNI
https://github.com/kubernetes/kubernetes/blob/90662534911a3618fe0ccc319e7e731c0f3b7403/pkg/kubelet/dockertools/docker_manager.go#L2224 calls `SetupContainerPid()`
https://github.com/kubernetes/kubernetes/blob/90662534911a3618fe0ccc319e7e731c0f3b7403/pkg/kubelet/network/hairpin/hairpin.go#L62 something goes wrong and it sets the mode on everything.

An example of "something goes wrong":

    Nov 16 15:41:40 ip-172-20-222-106 kubelet[883]: I1116 15:41:40.366037     883 hairpin.go:61] Unable to find pair interface, setting up all interfaces: exec: "ethtool": executable file not found in $PATH
