### ISSUE TITLE
Deflake and Reenable flaky kube-proxy test (integration)

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#20001]
I disabled a block of code in #20000.
The code was flaky (#19999).  

Suggest one of the following solutions:

1. move this type of test coverage to an e2e, or VM or docker based test, where there are no port conflicts.
1. modify kubectl proxy command to have a mode where it will pick a port for you, trying until it finds one.
1. modify the test loop to allow failure of kubectl proxy command when it exits with a certain error code that means it could not get a port, and retries until it gets one.

**Comment by goltermann** [comment]
Fixed in #20260?

**Comment by lavalamp** [comment]
No, not fixed: https://github.com/kubernetes/kubernetes/blob/master/hack/test-cmd.sh#L252

**Comment by lavalamp** [comment]
We still need to reenable this code. I was unaware that it'd been disabled.

**Comment by lavalamp** [comment]
I made a reversion PR.
