### ISSUE TITLE
Deleting jobs via the API leaves pods

### ISSUE THREAD

**Issue by Fizzadar** [kubernetes/kubernetes#20902]
According to the docs _"Deleting a Job will cleanup the pods it created"_ - this only appears to be true when deleting jobs via `kubectl`. Issuing plain `DELETE` requests via the API removes the job as expected but leaves any (failed) pods it started untouched. Currently I'm just cleaning this up by hand but it'd be nice if this could be integrated into the API.

**Comment by Fizzadar** [comment]
Just located https://github.com/kubernetes/kubernetes/issues/16255 which would imply this has been fixed - regression?

**Comment by Fizzadar** [comment]
Although this goes against the docs - I actually think this is a useful _feature_ of jobs currently. For example if I create a job with dodgy code - the job controller will continuously spawn/respawn pods forever until the job completes. So to prevent this we just delete the job - but, if it were deleting the pods also, it would make it impossible to extract the logs from those failed pods, which is needed to debug the failure.

So having the pods remain after job deletion _is_ useful. Coincidentally it also means jobs behave more like RC's in that respect (which is good?).

**Comment by bgrant0607** [comment]
@Fizzadar Those docs are referring to kubectl delete, not delete via the API.

Server-side cascading deletion is a long-desired feature, but hasn't been implemented yet:
https://github.com/kubernetes/kubernetes/issues/1535#issuecomment-156185924

cc @erictune @soltysh

**Comment by erictune** [comment]
By the way, you can update the job to have 0 parallelism to make it stop spawning pods while you debug.  If it turns out the problem was something external (missing input files on cluster file system, etc) then you can restart it.

**Comment by Fizzadar** [comment]
@bgrant0607 ah that makes sense! @erictune awesome, just what we needed, thanks for the tip!

**Comment by erictune** [comment]
...restart it by increasing parallelism to greater than zero.

**Comment by bgrant0607** [comment]
Ref #12143

**Comment by connec** [comment]
I've also encountered this using `kubectl replace` - not sure whether it's expected to do cascading deletion or not.

**Comment by soltysh** [comment]
This is now fixed with https://github.com/kubernetes/kubernetes/pull/42176

**Comment by soltysh** [comment]
Closing per previous comment.

**Comment by jkinkead** [comment]
I'm still seeing completed, running, and failed pods left around after the owning job is deleted in 1.7.0 (by issuing a `DELETE` against the API).

Did #42176 really fix this?

kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by soltysh** [comment]
@jkinkead it's working just fine, I'm guessing your missing [DeleteOptions](https://github.com/kubernetes/kubernetes/blob/release-1.7/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L374-L402) being send appropriately. Here's a `curl` invocation that does what you want:
```
curl -k -v -XDELETE  -H "Accept: application/json, */*" -H "Content-Type: application/json" \
  --data "{\"kind\":\"DeleteOptions\",\"apiVersion\":\"batch/v1\",\"propagationPolicy\":\"Background\"}" \
  http://127.0.0.1:8080/apis/batch/v1/namespaces/default/jobs/pi
```

**Comment by jkinkead** [comment]
Awesome, thanks for the quick reply! That was absolutely the problem; my quick verification test was too quick.

I take it that `"propagationPolicy": "Background"` is what triggers the orphan deletes?

**Comment by soltysh** [comment]
Yes, there are three [possible values](https://github.com/kubernetes/kubernetes/blob/release-1.7/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L360-L370). `Background` performs the actual cleanup in the background, but there are also options for orphaning (`Orphan`) and blocking delete call until everything is removed (`Foreground`).

**Comment by jkinkead** [comment]
Thanks for clearing that up!

**Comment by roblappcoupa** [comment]
For what it's worth you can see that by default `kubectl` specifies the propagation policy as `Background`. This can be seen running this command: `kubectl delete job my-job --dry-run=server -v=9`. In my case I was using a client library to delete jobs via the REST API but the propagation policy was not getting set. Once I set it to `Background` it started deleting the pod as well.
