### ISSUE TITLE
fluentd image doesn't process the sub-second portion of timestamps for docker logs

### ISSUE THREAD

**Issue by chrisleck** [kubernetes/kubernetes#21480]
For busy pods, this causes out-of-order messages to appear in elasticsearch/kibana.

I believe the fix is to add ".%N" to the end of the time_format field in the kubernetes log source in td-agent.conf.

**Comment by a-robinson** [comment]
Assigning to myself to make sure this gets fixed only because I can't assign to you. Thanks for the report/fix!

**Comment by a-robinson** [comment]
Fixed by #21482, with the images being pushed out in #22074

**Comment by chrisleck** [comment]
Still not fixed.  Looks like some logs are parsed properly (for example, Kibana FE logs come through with sub-second timestamps), but the ones coming from docker are not.

**Comment by a-robinson** [comment]
As @jimmidyson mentioned in https://github.com/kubernetes/kubernetes/pull/22074#issuecomment-189636915, Fluentd doesn't support sub-second time resolution in version 0.12, which is what we're currently on. 0.14 will support it (https://github.com/fluent/fluentd/issues/461), but hasn't been fully released yet.

We're stuck with per-second time resolution from these system logs for now. Our configuration files should automatically start working once we're able to move onto 0.14, though.

**Comment by toidi** [comment]
@a-robinson Fluentd  `v0.14.0` released at May 31.
There is `v0.14.1` version.

Please update `fluentd-es`. Please please please..

**Comment by grpubr** [comment]
Fluentd v0.14.22 has been released
 v0.14.22 is a stable release of v0.14 series
https://www.fluentd.org/blog/fluentd-v0.14.22-has-been-released

please update fluentd-es image

**Comment by crassirostris** [comment]
Contributions will be appreciated :)
