### ISSUE TITLE
Release versions are getting parsed wrong

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#24535]
```
$ gsutil -mq cp gs://kubernetes-release/release/v1.3.0-alpha.1/kubernetes.tar.gz .
$ tar xvf kubernetes.tar.gz
$ cd kubernetes/
$ cat version
v1.3.0-alpha.1.0+12b0a06be147c2
```

Perhaps a bug in https://github.com/kubernetes/release/pull/1?

**Comment by david-mcmahon** [comment]
Thanks for catching this!  I'm surprised it wasn't noticed earlier.  It's an off by 1 (s) error.
We pushed to gs://kubernetes-releases vs gs://kubernetes-release.  The offending s has been removed.  I'll clean up the release itself.

**Comment by ihmccreery** [comment]
@david-mcmahon I thought this was right, but I think this is still an issue.  I'm trying to release `v1.3.0-alpha.3`, and it's building wrong.

I guess there were actually two problems; you caught one, but not the one I meant.  This issue was about: `v1.3.0-alpha.1` should report itself as `v1.3.0-alpha.1`, but instead it reports itself as `v1.3.0-alpha.1.0+12b0a06be147c2`.

**Comment by ihmccreery** [comment]
I'll look into this, since it's blocking alpha releases.

**Comment by ihmccreery** [comment]
This seems contrary to #23148, but #23148 doesn't have enough context for me to know why it was changed.

**Comment by ihmccreery** [comment]
This was fixed by #24825 a long time ago.
