### ISSUE TITLE
default secret token for service account failed to be created (preventing pods from spawning)

### ISSUE THREAD

**Issue by DreadPirateShawn** [kubernetes/kubernetes#25416]
At least twice now, we've created a namespace and seen that the corresponding service account default secret token is never created. (The service account itself is, but not the default secret.)

**Namespace creation + apiserver logs**

**logstash-ingester: namespace creation triggered service account creation but no secret**

```
$ echo "{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"name\":\"logstash-ingester\"}}" | kubectl create -f -

I0504 12:28:33.331396       1 handlers.go:152] POST /api/v1/namespaces: (13.998977ms) 201 [[kubectl/v1.2.2 (linux/amd64) kubernetes/528f879] 192.168.0.16:42612]
I0504 12:28:33.862690       1 handlers.go:152] GET /api/v1/namespaces/logstash-ingester/replicationcontrollers?labelSelector=name%3Dlogstash-ingester: (1.486039ms) 200 [[kubectl/v1.2.2 (linux/amd64) kubernetes/528f879] 192.168.0.16:42615]
I0504 12:28:34.101045       1 handlers.go:152] GET /api/v1/namespaces/logstash-ingester/serviceaccounts/default: (1.178765ms) 404 [[hyperkube/v1.2.2 (linux/amd64) kubernetes/528f879/tokens-controller] 127.0.0.1:45497]
I0504 12:28:34.102937       1 handlers.go:152] POST /api/v1/namespaces/logstash-ingester/serviceaccounts: (15.911881ms) 201 [[hyperkube/v1.2.2 (linux/amd64) kubernetes/528f879/service-account-controller] 127.0.0.1:45495]
...
(never any POST to /api/v1/namespaces/logstash-ingester/secrets)
```

**logstash-broker: namespace creation triggered service account creation and secret creation**

```
$ echo "{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"name\":\"logstash-broker\"}}" | kubectl create -f -

I0504 12:29:01.541478       1 handlers.go:152] POST /api/v1/namespaces: (9.31755ms) 201 [[kubectl/v1.2.2 (linux/amd64) kubernetes/528f879] 192.168.0.16:42675]
I0504 12:29:01.547657       1 handlers.go:152] POST /api/v1/namespaces/logstash-broker/serviceaccounts: (4.763383ms) 201 [[hyperkube/v1.2.2 (linux/amd64) kubernetes/528f879/service-account-controller] 127.0.0.1:45516]
I0504 12:29:01.551010       1 handlers.go:152] GET /api/v1/namespaces/logstash-broker/serviceaccounts/default: (1.304463ms) 200 [[hyperkube/v1.2.2 (linux/amd64) kubernetes/528f879/tokens-controller] 127.0.0.1:45516]
I0504 12:29:01.587075       1 handlers.go:152] GET /api/v1/namespaces/logstash-broker/resourcequotas: (1.294544ms) 200 [[hyperkube/v1.2.2 (linux/amd64) kubernetes/528f879] 127.0.0.1:45384]
I0504 12:29:01.593363       1 handlers.go:152] POST /api/v1/namespaces/logstash-broker/secrets: (8.396083ms) 201 [[hyperkube/v1.2.2 (linux/amd64) kubernetes/528f879/tokens-controller] 127.0.0.1:45516]
I0504 12:29:01.612385       1 handlers.go:152] PUT /api/v1/namespaces/logstash-broker/serviceaccounts/default: (17.334548ms) 200 [[hyperkube/v1.2.2 (linux/amd64) kubernetes/528f879/tokens-controller] 127.0.0.1:45516]
...
```

**Resulting service accounts**

```
$ kubectl get serviceaccounts --all-namespaces
NAMESPACE            NAME      SECRETS   AGE
default              default   1         10h
logstash-broker      default   1         10h
logstash-ingester    default   0         10h
```

**Resulting secrets**

```
$ kubectl get secrets --all-namespaces
NAMESPACE            NAME                  TYPE                                  DATA      AGE
default              default-token-fxpho   kubernetes.io/service-account-token   3         10h
logstash-broker      default-token-3y3el   kubernetes.io/service-account-token   3         10h
```

**Controller-manager logs for broken case**

```
$ kubectl.sh logs kube-controller-manager-m1kmaster2 | grep logstash-ingester | (head -n4; python -c "print '-'*50"; tail -n4)

I0504 12:28:35.215493       1 replication_controller.go:434] Too few "logstash-ingester"/"logstash-ingester-20160504-122831" replicas, need 1, creating 1
I0504 12:28:35.219456       1 replication_controller.go:440] Failed creation, decrementing expectations for controller "logstash-ingester"/"logstash-ingester-20160504-122831"
E0504 12:28:35.219502       1 replication_controller.go:442] unable to create pods: pods "logstash-ingester-20160504-122831-" is forbidden: no API token found for service account logstash-ingester/default, retry after the token is automatically created and added to the service account
I0504 12:28:35.232246       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"logstash-ingester", Name:"logstash-ingester-20160504-122831", UID:"b888278b-11f3-11e6-afb3-00505615bcae", APIVersion:"v1", ResourceVersion:"932", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "logstash-ingester-20160504-122831-" is forbidden: no API token found for service account logstash-ingester/default, retry after the token is automatically created and added to the service account
--------------------------------------------------
I0504 22:45:38.575166       1 replication_controller.go:434] Too few "logstash-ingester"/"logstash-ingester-20160504-122831" replicas, need 1, creating 1
I0504 22:45:38.590631       1 replication_controller.go:440] Failed creation, decrementing expectations for controller "logstash-ingester"/"logstash-ingester-20160504-122831"
E0504 22:45:38.590750       1 replication_controller.go:442] unable to create pods: pods "logstash-ingester-20160504-122831-" is forbidden: no API token found for service account logstash-ingester/default, retry after the token is automatically created and added to the service account
I0504 22:45:38.591223       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"logstash-ingester", Name:"logstash-ingester-20160504-122831", UID:"b888278b-11f3-11e6-afb3-00505615bcae", APIVersion:"v1", ResourceVersion:"934", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "logstash-ingester-20160504-122831-" is forbidden: no API token found for service account logstash-ingester/default, retry after the token is automatically created and added to the service account
```

**Controller-manager logs for working case**

```
$ kubectl.sh logs kube-controller-manager-m1kmaster2 | grep logstash-broker | head -n2

I0504 12:29:03.699793       1 replication_controller.go:434] Too few "logstash-broker"/"logstash-broker-20160504-122858" replicas, need 1, creating 1
I0504 12:29:03.733761       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"logstash-broker", Name:"logstash-broker-20160504-122858", UID:"c97f9a9b-11f3-11e6-afb3-00505615bcae", APIVersion:"v1", ResourceVersion:"982", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: logstash-broker-20160504-122858-vtbky
```

**Version Info:**

```
$ kubectl --server=https://192.168.0.204:6443 --kubeconfig=/highland/config/kubernetes/config   version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
```

**Comment by smarterclayton** [comment]
Dupe of #25139, fixed in #24768

**Comment by smarterclayton** [comment]
Actually, not a dupe.  This may be a consequence of other refactors to controller logic - possibly we are missing / dropping events out of the queue.  I would expect it to get fixed on the sync interval though.

**Comment by AlbertoPeon** [comment]
We are also seeing this happening from time to time.

In our case, it wasn't fixed in the next sync interval but it took actually a little bit more of 24 hours.

**Comment by grodrigues3** [comment]
@smarterclayton can we resolve this and remove it from the 1.6 milestone?

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/23858 in 1.4

**Comment by jdfless** [comment]
We just hit this exact issue running 1.5.2. Maybe the fix didn't get the root cause or there was a regression since 1.4? This should be reopened.

I waited about an hour to see if the sync interval would resolve this but it did not. I fixed by deleting and recreating the namespace. I can share logs, but they are identical to what the OP noted.

**Comment by DreadPirateShawn** [comment]
@liggitt Working with @jdfless, this seems like it's not fixed in v1.5.2 -- what should we do here? We don't have permission to re-open the ticket, but filing the same ticket with the same logs (just fresher dates) seems passive-aggressive. :-) What's your preference?

**Comment by liggitt** [comment]
no problem, just getting back to this. can reopen this issue.

**Comment by liggitt** [comment]
can you recreate with the controller manager running at `--v=4` and include logs from `tokens_controller.go`?

**Comment by DreadPirateShawn** [comment]
Fresh repo, offending namespace "foo96", with "--v=5" since we already have that logging level in place on my dev stack. This took 96 repros of a "create namespace / monitor for token creation / delete namespace" loop.

*Our script's commands, starting just after 16:36:43:*
```
$ kubectl --server=... delete namespace foo96
$ kubectl --server=... create namespace foo96
$ kubectl --server=... --namespace=foo96 get secrets
$ <repeat get secrets for 60 seconds, to no avail>
```

*Controller manager log lines from tokens_controller.go*
The first reference to the offending namespace (foo96) and the one other `tokens_controller.go` entry afterwards:
```
E0412 16:36:46.456959       1 tokens_controller.go:267] error synchronizing serviceaccount foo96/default: serviceaccounts "default" not found
I0412 16:39:11.910958       1 reflector.go:392] pkg/controller/serviceaccount/tokens_controller.go:170: Watch close - *api.ServiceAccount total 185 items received
```

*All controller manager log lines citing the offending namespace:*
```
$ kubectl --server=... --namespace=kube-system log kube-controller-manager-kube-master2 | grep foo96
E0412 16:36:46.456959       1 tokens_controller.go:267] error synchronizing serviceaccount foo96/default: serviceaccounts "default" not found
I0412 16:36:46.689268       1 serviceaccounts_controller.go:191] Finished syncing namespace "foo96" (609.982606ms)
I0412 16:36:51.079585       1 namespace_controller.go:206] Finished syncing namespace "foo96" (742ns)
I0412 16:41:00.866076       1 namespace_controller.go:206] Finished syncing namespace "foo96" (394ns)
```

*For comparison, the previous successfully-created namespace:*
```
$ kubectl --server=... --namespace=kube-system log kube-controller-manager-kube-master2
I0412 16:36:42.214576       1 serviceaccounts_controller.go:191] Finished syncing namespace "foo95" (16.171657ms)
I0412 16:36:47.197782       1 namespace_controller.go:206] Finished syncing namespace "foo95" (886ns)
I0412 16:41:00.865834       1 namespace_controller.go:206] Finished syncing namespace "foo95" (394ns)
```

*Status as of 20 minutes later:*
```
$ kubectl --server=... get namespace foo96
NAME      STATUS    AGE
foo96     Active    18m

$ kubectl --server=... --namespace=foo96 get secrets
No resources found.
```

**Comment by DreadPirateShawn** [comment]
Also, here's the apiserver logs + controller manager logs, for more action/reaction context:

**Namespace: foo96 (problem)**
```
kube-apiserver: I0412 16:36:45.080249       1 panics.go:76] DELETE /api/v1/namespaces/foo96: (1.55618ms) 404 [[kubectl/v1.5.2 (linux/amd64) kubernetes/08e0995] 192.168.0.8:59017]
kube-apiserver: I0412 16:36:45.557960       1 panics.go:76] GET /api/v1/namespaces/foo96: (1.52507ms) 404 [[kubectl/v1.5.2 (linux/amd64) kubernetes/08e0995] 192.168.0.8:59025]
kube-apiserver: I0412 16:36:46.066015       1 panics.go:76] GET /api/v1/namespaces/foo96/serviceaccounts: (1.5536ms) 200 [[kubectl/v1.5.2 (linux/amd64) kubernetes/08e0995] 192.168.0.8:59029]
kube-apiserver: I0412 16:36:46.456565       1 panics.go:76] GET /api/v1/namespaces/foo96/serviceaccounts/default: (1.180633ms) 404 [[hyperkube/v1.5.2 (linux/amd64) kubernetes/08e0995/tokens-controller] 127.0.0.1:38995]
kube-controller-manager: E0412 16:36:46.456959       1 tokens_controller.go:267] error synchronizing serviceaccount foo96/default: serviceaccounts "default" not found
kube-apiserver: I0412 16:36:46.540650       1 panics.go:76] GET /api/v1/namespaces/foo96: (1.657951ms) 200 [[kubectl/v1.5.2 (linux/amd64) kubernetes/08e0995] 192.168.0.8:59034]
kube-apiserver: I0412 16:36:46.688986       1 trace.go:61] Trace "Create /api/v1/namespaces/foo96/serviceaccounts" (started 2017-04-12 16:36:46.079836239 +0000 UTC):
kube-apiserver: I0412 16:36:46.689029       1 panics.go:76] POST /api/v1/namespaces/foo96/serviceaccounts: (609.394382ms) 201 [[hyperkube/v1.5.2 (linux/amd64) kubernetes/08e0995/service-account-controller] 127.0.0.1:38988]
kube-controller-manager: I0412 16:36:46.689268       1 serviceaccounts_controller.go:191] Finished syncing namespace "foo96" (609.982606ms)
kube-apiserver: I0412 16:36:49.170638       1 panics.go:76] GET /api/v1/namespaces/foo96/serviceaccounts/default: (1.645271ms) 200 [[kubectl/v1.5.2 (linux/amd64) kubernetes/08e0995] 192.168.0.8:59072]
kube-apiserver: I0412 16:36:49.646146       1 panics.go:76] GET /api/v1/namespaces/foo96/secrets: (1.770996ms) 200 [[kubectl/v1.5.2 (linux/amd64) kubernetes/08e0995] 192.168.0.8:59076]
kube-controller-manager: I0412 16:36:51.079585       1 namespace_controller.go:206] Finished syncing namespace "foo96" (742ns)
kube-apiserver: I0412 16:36:51.116194       1 panics.go:76] GET /api/v1/namespaces/foo96/secrets: (1.554069ms) 200 [[kubectl/v1.5.2 (linux/amd64) kubernetes/08e0995] 192.168.0.8:59099]
```

**Namespace: foo95 (success)**
```
kube-apiserver: I0412 16:36:41.206663       1 panics.go:76] DELETE /api/v1/namespaces/foo95: (1.214469ms) 404 [[kubectl/v1.5.2 (linux/amd64) kubernetes/08e0995] 192.168.0.8:58964]
kube-apiserver: I0412 16:36:41.685611       1 panics.go:76] GET /api/v1/namespaces/foo95: (1.539852ms) 404 [[kubectl/v1.5.2 (linux/amd64) kubernetes/08e0995] 192.168.0.8:58968]
kube-apiserver: I0412 16:36:42.199260       1 panics.go:76] GET /api/v1/namespaces/foo95/serviceaccounts: (1.602715ms) 200 [[kubectl/v1.5.2 (linux/amd64) kubernetes/08e0995] 192.168.0.8:60074]
kube-apiserver: I0412 16:36:42.213896       1 panics.go:76] POST /api/v1/namespaces/foo95/serviceaccounts: (15.233189ms) 201 [[hyperkube/v1.5.2 (linux/amd64) kubernetes/08e0995/service-account-controller] 127.0.0.1:38988]
kube-controller-manager: I0412 16:36:42.214576       1 serviceaccounts_controller.go:191] Finished syncing namespace "foo95" (16.171657ms)
kube-apiserver: I0412 16:36:42.216236       1 panics.go:76] GET /api/v1/namespaces/foo95/serviceaccounts/default: (1.101061ms) 200 [[hyperkube/v1.5.2 (linux/amd64) kubernetes/08e0995/tokens-controller] 127.0.0.1:38988]
kube-apiserver: I0412 16:36:42.222312       1 panics.go:76] GET /api/v1/namespaces/foo95/resourcequotas: (990.849µs) 200 [[hyperkube/v1.5.2 (linux/amd64) kubernetes/08e0995] 127.0.0.1:54400]
kube-apiserver: I0412 16:36:42.228597       1 panics.go:76] POST /api/v1/namespaces/foo95/secrets: (7.746433ms) 201 [[hyperkube/v1.5.2 (linux/amd64) kubernetes/08e0995/tokens-controller] 127.0.0.1:38988]
kube-apiserver: I0412 16:36:42.238884       1 panics.go:76] PUT /api/v1/namespaces/foo95/serviceaccounts/default: (8.734468ms) 200 [[hyperkube/v1.5.2 (linux/amd64) kubernetes/08e0995/tokens-controller] 127.0.0.1:38988]
kube-apiserver: I0412 16:36:42.659375       1 panics.go:76] GET /api/v1/namespaces/foo95: (5.525344ms) 200 [[kubectl/v1.5.2 (linux/amd64) kubernetes/08e0995] 192.168.0.8:58977]
kube-apiserver: I0412 16:36:43.123770       1 panics.go:76] GET /api/v1/namespaces/foo95/serviceaccounts/default: (1.818523ms) 200 [[kubectl/v1.5.2 (linux/amd64) kubernetes/08e0995] 192.168.0.8:58994]
kube-apiserver: I0412 16:36:43.584926       1 panics.go:76] GET /api/v1/namespaces/foo95/secrets: (1.827239ms) 200 [[kubectl/v1.5.2 (linux/amd64) kubernetes/08e0995] 192.168.0.8:58998]
kube-controller-manager: I0412 16:36:47.197782       1 namespace_controller.go:206] Finished syncing namespace "foo95" (886ns)
```

**Comment by liggitt** [comment]
that's helpful, thanks. it looks like while the token controller is processing the creation event for the service account, it does a live lookup against etcd and fails to find the service account.

what version of etcd are you running with?
are you running HA etcd?
do you have quorum read enabled?

**Comment by jdfless** [comment]
We run etcd version 2.3.7 (previously saw this on 2.2.x as well).
We run etcd HA, with a 3 node cluster.
We do not run the apiserver with the --etcd-quorum-read flag enabled.

**Comment by DreadPirateShawn** [comment]
(Note: My specific logs above from this morning are on etcd 2.2.5, but yeah we've seen repro on 2.3.7 as well.)

**Comment by liggitt** [comment]
yeah, the non-quorum HA etcd config is the issue. I can look into updating the token controller to tolerate that, but I'm positive there are similar issues in many controllers that assume live lookups are reliable

**Comment by DreadPirateShawn** [comment]
Ahh excellent, glad to have an explanation!

So -- now that we know what to google for, we found https://github.com/kubernetes/kubernetes/issues/36791 -- where you and clayton addressed what appears to be this same problem for service accounts, and specifically noted that you wanted to **avoid** recommending quorum reads.

Why is the answer different here? Is it because the downstream impact of non-quorum reads is too diverse to reliably retry every relevant action? (Totally fine if that's the answer, just trying to make sure we understand the reason for what appears to be an entirely opposite conclusion to the same type of problem.)

**Comment by liggitt** [comment]
I still think controllers should be built to tolerate weak reads, and I'm willing to fix the token controller bug here, but three factors make me think this position is a losing battle:
* quorum read got a *lot* cheaper with etcd3
* there are strong opinions that etcd quorum read should be on (https://github.com/kubernetes/kubernetes/issues/37473#issuecomment-265025413) which means that very few people are writing controllers designed to tolerate weak reads
* all the CI tests I'm aware of run with a single etcd or with quorum reads on

**Comment by DreadPirateShawn** [comment]
Perfect, works for us. As for fixing this particular token controller bug, I no longer have skin in that game -- your call entirely. :-)
