### ISSUE TITLE
rkt: Init container support

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#25988]
As per title, init containers do not work with rkt as the container runtime and I didn't see an existing issue to track this.

Ref https://github.com/coreos/rkt/issues/2375 and #23666

**Comment by yifan-gu** [comment]
I think this will be addressed once we switched to CRI

**Comment by euank** [comment]
Yup. It could be addressed sooner too if rkt's app-level operations get resolved prior to CRI being ready for prime-time, or by adding a suitably flexible DAG to rkt's existing pod model, but I think leaving this alone until fixed by the CRI integration makes the most sense.

**Comment by TerraTech** [comment]
@yifan-gu @euank is there any progress on this as I'm having to run a few kubernetes + docker runtimes and push anything needing init containers to them exclusively.

**Comment by mikefedyk** [comment]
How much longer will CRI take before this issue is addressed?

**Comment by euank** [comment]
This issue is both correct and out of date at the same time.

The rktnetes implementation living in-tree for this repository still doesn't support init containers. The CRI implementation (https://github.com/kubernetes-incubator/rktlet) does support init containers today, but isn't as well-tested and isn't in-tree/enabled by default yet.

The resolution for this issue is switching to the CRI rkt implementation.

cc @lucab

**Comment by euank** [comment]
This works in [rktlet](https://github.com/kubernetes-incubator/rktlet/), and the in-tree rkt implementation is being deprecated.

/close
