### ISSUE TITLE
`kubectl apply deployment -f` doesn't accept label/selector changes

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#26202]
I got errors complaining about the selector and labels not matching even if I explicitly specified both. Showed @janetkuo.

**Comment by janetkuo** [comment]
To reproduce:

First create a Deployment via `apply -f` 
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        test: abcd
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

Then remove any of the labels in the file, and `apply -f`
```console
$ kubectl apply -f docs/user-guide/nginx-deployment.yaml 
proto: no encoder for TypeMeta unversioned.TypeMeta [GetProperties]
proto: tag has too few fields: "-"
proto: no coders for struct *reflect.rtype
proto: no encoder for sec int64 [GetProperties]
proto: no encoder for nsec int32 [GetProperties]
proto: no encoder for loc *time.Location [GetProperties]
proto: no encoder for Time time.Time [GetProperties]
proto: no encoder for InitContainers []v1.Container [GetProperties]
proto: no coders for intstr.Type
proto: no encoder for Type intstr.Type [GetProperties]
The Deployment "nginx-deployment" is invalid.
spec.template.metadata.labels: Invalid value: {"test":"abcd"}: `selector` does not match template `labels`
```

@kubernetes/kubectl @AdoHe

**Comment by smarterclayton** [comment]
Is there a bug already open for all that proto crap?  I had not seen that
showing up before - I would not expect it.

On May 24, 2016, at 6:29 PM, Janet Kuo <notifications@github.com> wrote:

To reproduce:

First create a Deployment via apply -f

apiVersion: extensions/v1beta1kind: Deploymentmetadata:
  name: nginx-deploymentspec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        test: abcd
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80

Then remove any of the labels in the file, and apply -f

$ kubectl apply -f docs/user-guide/nginx-deployment.yaml proto: no
encoder for TypeMeta unversioned.TypeMeta [GetProperties]proto: tag
has too few fields: "-"proto: no coders for struct
*reflect.rtypeproto: no encoder for sec int64 [GetProperties]proto: no
encoder for nsec int32 [GetProperties]proto: no encoder for loc
*time.Location [GetProperties]proto: no encoder for Time time.Time
[GetProperties]proto: no encoder for InitContainers []v1.Container
[GetProperties]proto: no coders for intstr.Typeproto: no encoder for
Type intstr.Type [GetProperties]The Deployment "nginx-deployment" is
invalid.spec.template.metadata.labels: Invalid value: {"test":"abcd"}:
`selector` does not match template `labels`

@kubernetes/kubectl <https://github.com/orgs/kubernetes/teams/kubectl>
@AdoHe <https://github.com/AdoHe>

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/26202#issuecomment-221421254>

**Comment by janetkuo** [comment]
The problem is that the `apply` annotation didn't record `.spec.selector` when it's defaulted from `.spec.template.labels` and it caused problems when calculating diff:

`
kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Deployment","apiVersion":"extensions/v1beta1","metadata":{"name":"nginx-deployment","creationTimestamp":null},"spec":{"replicas":3,"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx","test":"abcd"}},"spec":{"containers":[{"name":"nginx","image":"nginx:1.7.9","ports":[{"containerPort":80}],"resources":{}}]}},"strategy":{}},"status":{}}'
`

**Comment by AdoHe** [comment]
That's because the `last-applied-configuration` is just the resource content read from user input when we use apply to create resource. Also the `.spec.selector` is derived from `.spec.template.labels` rule is not used in client side.

**Comment by AdoHe** [comment]
@janetkuo I am considering adding the default `.spec.selector` to `last-applied-configuration` annotation/ WDYT?

**Comment by therc** [comment]
We've been bitten by this for a service:

```
The Service "labeler" is invalid.

* metadata.resourceVersion: Invalid value: "": must be specified for an update
* spec.clusterIP: Invalid value: "": field is immutable
```

I just nuked the `last-applied-configuration` annotation and the change applied successfully.

**Comment by therc** [comment]
And before that error, there was the very same sequence of proto errors.

**Comment by lavalamp** [comment]
Please note if you want to get defaulted stuff, it's *super important* to let the server do the defaulting.

**Comment by AdoHe** [comment]
@lavalamp yes, we should put this in server side.

**Comment by AdoHe** [comment]
@bgrant0607 @janetkuo @lavalamp I thought about this carefully, I think the root cause of both this issue and #24198 is `last-applied-configuration` annotation doesn't include fields which has default value, e.g `spec.selector` and `spec.strategy`. Users may not specify these fields in the original resource file, but we will set in the client side. I have opened a PR #26405 to indicate this problem.

**Comment by bgrant0607** [comment]
@AdoHe We should not add default values to `last-applied-configuration`. Unfortunately the design hasn't been written up yet, but there's some discussion on #1702, I think.

**Comment by bgrant0607** [comment]
Changing selectors has other problems, also. For instance, it's a map, and maps are merged by default.

Also note that a default selector won't be changed automatically when pod template labels are changed.

**Comment by bgrant0607** [comment]
I wrote a brief explanation here: https://github.com/kubernetes/kubernetes/issues/15894#issuecomment-222194015

**Comment by metral** [comment]
Ran into this myself. In the meantime is there a work around that doesn't require blowing away `last-applied-configuration`?

**Comment by bgrant0607** [comment]
Accidental orphaning is another problem: #24888

**Comment by bgrant0607** [comment]
@metral What problem did you encounter?

**Comment by bgrant0607** [comment]
@lavalamp We capture the last-applied-configuration prior to defaulting, so it shouldn't matter whether the defaulting happens in the client or server, though obviously I'd prefer the latter.

**Comment by bgrant0607** [comment]
Controlled pods are identified by labels, not by name. 

In general, changing the labels and selector on a controller isn't expected to work. To do it properly requires a multi-step dance. In any case, controllers don't update running pods -- for the most part, not even Deployment does that.

We should strongly recommend that users shouldn't do that, unless they use `kubectl replace --force`, which does a cascading delete and re-create.

**Comment by metral** [comment]
@bgrant0607 I'm hitting the same issue as @janetkuo described when I try changing a label. In my case it's a label I use for the revision/commit of the current build which gets altered in the deployment manifest upon a successful build so that I can apply the new deployment. 

Oddly enough, this same strategy is working on 2 other projects / deployments that I have in the system just fine, but for some reason on my 3rd one I'm hitting this issue. I'm sure it's something on my end that I haven't caught onto, but strange nevertheless that updating the rev & applying the new deployment works for some and not others

**Comment by bgrant0607** [comment]
@metral Specify a selector that omits the label you plan to change.

**Comment by metral** [comment]
@bgrant0607 that makes sense - I'll give that a shot when I'm back at my computer. 

Just odd that I've never specified the selector in my working deployments, just the labels in the metadata and changing the revs on those has never caused an issue

**Comment by bgrant0607** [comment]
I think the longer-term solution will be to move to a defaulting approach similar to what we use for Job:
https://github.com/kubernetes/kubernetes/blob/master/docs/design/selector-generation.md

**Comment by bgrant0607** [comment]
@therc How did you create the service in the case described by https://github.com/kubernetes/kubernetes/issues/26202#issuecomment-221933023 ? Did you use apply or create?

**Comment by bgrant0607** [comment]
This is basically a dupe of #24888.

**Comment by therc** [comment]
@bgrant0607 I didn't create it myself. I suspect my colleague used apply.

**Comment by therc** [comment]
I think the problem is that in my case I used `kubectl edit` on the service to add a couple of annotations. That seems to have been responsible for persisting `resourceVersion` and `clusterIP` in the `last-applied-configuration` annotation.

**Comment by ghodss** [comment]
@bgrant0607 @janetkuo @lavalamp This is a fundamental issue with apply that I believe is fairly severe, since it took down our cluster today.

To summarize the more general issue, if a field's default value is derived from other provided fields (in this case, deployment.spec.selector is derived from deployment.spec.template.metadata.labels), and there is a change to those other provided fields through `kubectl apply` (in this case, changes made only to the metadata.labels), those changes are *not* propagated to the defaulted values (in this case, the selector). Worse, those changes are left unpropagated silently without any errors.

This resulted in a situation where we `kubectl apply`ed a new label to a deployment, then created another deployment with a different value for that label, but because the label was not propagated to the selector in the original deployment, the two deployments fought over increasing and decreasing the replicasets which resulted in an infinite loop of creating and deleting pods that took down the cluster.

This is a general problem that I think pretty badly hampers the goal of declarative configuration. In the labels specific case, it means that you must know intuitively to always explicitly duplicate the pod labels into the selector labels - you can't rely on the defaulting or you may become out of sync. But there will likely be more use cases as object definitions expand and more defaulting exists.

Is there a way to make defaulting work well with apply?

**Comment by lavalamp** [comment]
> the two deployments fought over increasing and decreasing the overlapping replicaset which resulted in an infinite loop of creating and deleting pods that took down the cluster.

https://github.com/kubernetes/kubernetes/pull/25256 would have saved you, but it didn't make 1.3.

**Comment by AdoHe** [comment]
@lavalamp thanks for pointing this out, would take a look.

**Comment by bgrant0607** [comment]
See also #24433

**Comment by bgrant0607** [comment]
@ghodss Setting one field from another by default is a convenience mechanism. No, it doesn't work with apply. There is no directionality implied, so it is difficult to infer user intent.

An alternative approach is discussed in #17333, and was originally proposed all the way back in #1178, but is unlikely to happen.

Additionally, changing the selector is unlikely to work as intended, since that could easily orphan existing pods. I'm inclined to ban updates to the selector. 

If the selector no longer matches the pod template labels, the apiserver should return an error.

Unfortunately, we don't have anyone available to work on apply and Deployment.

**Comment by AdoHe** [comment]
@bgrant0607 I just get confused, did we already have a final decision about how to fix this? I have seen this in many issues, and it seems there are different approaches to solve this. I am just wondering which one should we adopt, if we really decide, I would like to help with this one.

**Comment by bgrant0607** [comment]
@AdoHe There are multiple problems discussed in this issue. No, we haven't settled on solutions. It's not clear to me that the problem originally reported has been fully debugged and understood.

**Comment by bgrant0607** [comment]
Thanks @AdoHe .

Yes, the user is responsible for updating the selector. That's working as intended. Defaulting only occurs at creation time.

However, selector changes are fraught with pitfalls and perhaps should be disallowed.

We could add add conflict detection (#13576) and apply --force (#16569), to force cascading deletion and re-creation in the case of a selector change.

**Comment by bgrant0607** [comment]
There is some discussion here also:
https://github.com/kubernetes/kubernetes/pull/28949#issuecomment-236640390

**Comment by keglevich3** [comment]
@bgrant0607 Can you please explain what is motivation that he user should maintain labels **and** selectors? As I understand from you they should be assigned with the same content. Is this is a temporary solution or should we except for a better one?
Thanks!

**Comment by ghodss** [comment]
> Defaulting only occurs at creation time.

Personally I think we need to improve apply so any time you delete a field, apply regenerates the defaults for that field. Only if you explicitly set the field to `null` should the field be set to a zero or nil value. In other words, keep the same behavior as creation time.

**Comment by mwielgus** [comment]
@lavalamp Can we prioritize fixing this for 1.4. We have a GKE client who is complaining about this issue.

**Comment by AdoHe** [comment]
@mwielgus @lavalamp what you expect this to be, should we have a better fix in 1.4?

**Comment by janetkuo** [comment]
Had an in-person discussion with @pwittrock and decided we won't fix this in 1.4 because there's no clean fix for this issue yet. Current workaround is to use `kubectl edit` to modify label and selector manually (if the selector is defaulted). cc @lavalamp

**Comment by janetkuo** [comment]
Had another in-person discussion with @lavalamp @pwittrock @bgrant0607, we should prevent people from changing selectors/pod template labels -- they're like names, and it's dangerous to change them. If you want to change them, it's safer to create new controllers instead. I'll create a fix for disallowing people from doing this in `kubectl apply`, and we can do further fix, such as doing this server side, in 1.5.

**Comment by bgrant0607** [comment]
@ghodss If we need to regenerate defaults, it should happen in the server rather than in kubectl.

**Comment by janetkuo** [comment]
It's interesting that the selector/labels update will work if you put the object inside a list:
```yaml
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
...
```

**Comment by lavalamp** [comment]
Yeah, while it's generally a terrible idea to change the label/selector on a deployment, I seem to recall back when I filed this, it failed for strange reasons unrelated to the actual potential problem of unowned/doubly owned pods.

**Comment by pwittrock** [comment]
@janetkuo Thanks Janet.  Please provide daily updates on this issue until it is closed.

**Comment by pwittrock** [comment]
@erictune I do not have the capacity to follow up on this.  Please make sure Janet has whatever she needs to make sure this is fully resolved by the end of this week.

**Comment by janetkuo** [comment]
> Can we prioritize fixing this for 1.4. We have a GKE client who is complaining about this issue.

@mwielgus do you have details on what the client is trying to accomplish? Do they just want to add more labels to their pods (created by deployments)?

**Comment by janetkuo** [comment]
Had an in-person discussion with @erictune. It seems reasonable for clients to add more specific labels to their deployments' pod templates, and preventing users from doing that (#32228) is risky for 1.4 (it may break people). So I'm removing this from 1.4. 

We need to think more about how to handle the case when users want to update template labels / selectors of their deployments. This is tricky to handle correctly, since current design will trigger new rollout and/or orphan the deployment's RSes and pods. A workaround is to first pause the deployments, update the deployment selector/template labels, and the pods' and RSes' labels/selectors manually, and then unpause the deployment, but this change can't be rolled back. Another workaround is to scale the deployment down to 0, make the changes, and then scaled back up, but this has the same risk that the users may not be able to rollback the deployment anymore. 

@mwielgus we'd like to hear more from the users about what they try to achieve, and we'll figure out how to deal with it in 1.5 or 1.6.

**Comment by diclophis** [comment]
@janetkuo it would be preferable for the metadata.labels to be updatable for our use case, because we planned on having the ability to modify a tag named 'TTL' that we would use to limit the lifetime of a resource on a particular kubernetes cluster to achieve high-density per pull-request deployments of our application... see: https://github.com/mavenlink/karousel for details

**Comment by janetkuo** [comment]
@diclophis thanks for the feedback. Updating template labels of deployment is still supported by `kubectl apply` as long as the selector is specified in the config file (not derived from template labels). However, doing this is dangerous since labels are how controllers group and find their sub-resources (as explained above in https://github.com/kubernetes/kubernetes/issues/26202#issuecomment-245747170). 

In your app, TTL labels are used to see if a resource is to be killed. If a deployment's TTL label is updated, it'll trigger a new rollout (any update to templates will trigger a new rollout) -- which means new pods will be created (comparison between pods creationTimestamp and TTL won't be what you expected).

I'd suggest using annotations instead, and use [Reaper](https://github.com/kubernetes/kubernetes/blob/release-1.4/pkg/kubectl/stop.go#L66-L94) to delete sub-resources (e.g. deployment's replica set and pods) cascadingly.

**Comment by erictune** [comment]
I learned yesterday that NetworkPolicy uses labels on pods to control which pods (the packet source, the ones with the labels) can connect to an ingress.  

It is easy to imagine that when people use labels in this way that they will want to change them independently of the image, in order to allow locking down access to an ingress without re-rolling-out the pods of its clients.  @kubernetes/sig-network

**Comment by thockin** [comment]
I just re-read this bug and I find the answer REALLY unsatisfactory.  If
our API allows you to change the field, it really should work correctly.

I've seen issue after issue around corner cases between maps, lists, and
patch/apply.

We simply can not push this back on users - if it doesn't work it is our
problem.

**Comment by smarterclayton** [comment]
Apply and patch are pretty fundamental to what we promote - we do have to
figure out how to force these corner cases to go to zero.

**Comment by AdoHe** [comment]
I believe I need to recheck the code and take a deep look.

**Comment by bgrant0607** [comment]
@thockin Changing the label selector is like changing the object name. With apply, at best it's going to create new resources and cause the old ones to be deleted (once we have --prune/purge).

**Comment by thockin** [comment]
That is fine.  It is mostly unsurprising at least.

**Comment by janetkuo** [comment]
So with regard to changing label selectors:

We talked about not allowing people from updating selector in `kubectl` (see PR #32228). Then we decided not to merge it, because it's too risky at the moment, and it probably won't make users who want to do that any happier. 

We talked about allowing people to update selectors, and we design something in the system which watches for the selector update and do the required operations to make it work. However, that might unnecessarily complicate the system.

**Comment by andronat** [comment]
Hi, I think that a possible way to solve this is by making `apply` producing a diff between the defaulted versions of the old and the new configuration. That means:

1. the api server sound to send (or store in the last-configuration annotation) the currently applied user's configuration with the default values
2. somehow get default values for the new configuration file (maybe a `dry-run` in `POST`)
3. `apply` should diff those 2 defaulted configurations

In this way we solve the problem when the user initially didn't configure selectors and he did on the new configuration.

**Comment by andronat** [comment]
@pwittrock any comments on [this](https://github.com/kubernetes/kubernetes/issues/26202#issuecomment-257051835), I would like to work on it.

**Comment by pwittrock** [comment]
@andronat I think there are 2 pieces to this issue.  I am guessing you are only talking about solving 1.

1. Updating `kubectl apply` label selector and label fields that were defaults from the PodTemplate labels in response to changes PodTemplate labels
  - More generally how to manage fields after they have been defaulted by the server
  - Need to figure out the details here: Do we allow changing server defaults for values.  If so, this would change them.  What happens if a field that would be defaulted has been updated by another source?
  - Does POST support dry-run already?
2. Providing predictable and well understood behavior when label selectors are updated
  - There are a lot of ways the user break themselves here, and often it may not be a 1 step process if using a rolling update strategy.  I would think that the new selector should match *both* the new pod template *and* the old podtemplate labels until the rollout to the new PodTemplate is complete.   (Maybe this is already implemented?)
  - Should we ever allow updating a label selector in a way that orphans pods?

**Comment by andronat** [comment]
Yea I'm referring only to point 1 as my main concern is the stability of `kubectl apply`.

I want to explicitly state that the problem with defaulting is not only affecting selectors but it is more general. We can decide if we want to prohibit selector changes independently from fixing apply and defaulting.

More specifically we will have similar inconsistency problems wherever new defaulted fields are generated based on some user input. To make things concrete here are some examples.

## Simplified Example
Let's assume that sending the following two user configurations **independently** we end up with the following state:
```
U1: { k1: v1 }  -- send to server --> S1: { k1: v1, k2: v2 }
U2: { k1: v2 }  -- send to server --> S2: { k1: v2 }
```

Now, by using apply we would like to transit from `S1: {k1: v1, k2: v2}` to `S2: {k1: v2}`. But if we use apply on our initial configurations we will end up on an invalid configuration file:
```
patch = U2-U1 = { k1: v2 }
But to properly transit state we need: patch = { k1: v2, k2: null }
```

## Our Use Cases

#### Selectors
Issue #26202 is very similar to simplified example with the difference that we have additional values coming from the elderly stored configuration file. More specifically, the `apply` generated patch does **not** include the appropriate label removals in selectors. The results in the api server to merge both new selector labels with old selector labels that create an invalid object. 

#### Strategy
In issue #24198, the `strategy` problem is identical to the simplified example. The `rollingUpdate` field is dependent on the initial value of the strategy field. So when the user comes to change the strategy field without explicitly touching the `rollingUpdate` field, an invalid object is generated.

All these problems root into two things:

1. We generate new fields based on specific values, that we have inter-dependent values (the defaulting process)
2. Not every combination of user data and **dependent** default values is valid (due to validator functions)

## General Case
We can generalize this but understanding exactly what we do in apply as this:
```
The API server accepts as a valid object (by using validators) a user's
configuration (U1), enhanced with default values (D1) explicitly generated
for U1. D1 is not independent from U1.

(NOTE: In case that a user's configuration doesn't not need defaulting, 
or the defaulting values are not dependent on another value, then everything 
works)

Thus any independent submission of object against the API server results in:
U1 + D1 -> valid
U2 + D2 -> valid

Now, using apply and given that the API server has U1 + D1 as its initial stored 
object we have:

client sends: patch = U2 - U1
server gets: patch + U1 + D1 = U2 - U1 + U1 + D1 = U2 + D1       ## Which is an invalid state

Whereas if we use the defaulted configurations:
client sends: patch = (U2 + D2) - (U1 + D1)
server gets: patch + U1 + D1 = (U2 + D2) - (U1 + D1) + U1 + D1 =  
             U2 + D2 - U1 - D1 + U1 + D1 = U2 + D2       ## Which is a valid state
```

## Further considerations
> What happens if a field that would be defaulted has been updated by another source?

I think this is a question about priority of overwrites and the complexity we want to handle. I think our first priority should be the user defined values to be the guaranteed values that will be stored. Then we need to decide: do we want default values to overwrite updated values or the opposite. I think giving priority to defaults over the updated, dramatically decreases complexity. If we decide to place defaults as the weakest, then we need:

 1. to make sure the updated value does not break the object (and if it does failover to the default? or warn the user?)
 2. we need somehow to understand which value is user defined, and which is defaulted (we don't have any notion of this, if we proceed with generated a patch over defaulted configs we lose any track of user defined and defaulted values when the JSON patch is generated) 
 3. when are ready to execute strategicMerge with the currently stored object, we need to understand if a value is a default value, or an updated one. (we just don't have that information)



> What happens if a third field is generated based on some value after the object is defaulted and stored (i.e. from a controller)

I think this questions can be translated as: `U1 + D1 + E -> valid` for every `E`. If yes, then we will never have a problem. If no, then I think one option is to discard such a value as it is not compatible with the user given configuration (or warn and ask for `--force`). Also this rices questions about who added such a value. If it was a controller, then how the controller handles such a removal (maybe it doesn't matter)? Do we have any use cases like this?

## Proposed Solutions

From where I stand I see 2 options:

1. Based on the aforementioned ideas, we should create patches based on the user's configs after they are defaulted, and choose a strategy over conflicts with defaults.
2. Break one of the two conditions that allows this problem to rice. We can't break condition 2 (which is allow any permutation of field values) but we can break condition 1 (having dependent fields). I think it would be very easy for us to say that we allow defaulting to happen only at per field level, without depending on another. If we want to impose a dependency on a field we can explicitly ask the user to define the field (and validate against it). As an example, we shouldn't allow selectors to be generated from labels. We should ask the user to define them explicitly and if he **does not** through a validation error. The same with `strategy`.

## Remarks
I'm not very familiar with every aspect and use case of this problem so I'm might missing something very essential here. Feedback is more than welcomed.

**Comment by pwittrock** [comment]
@andronat 

Thanks for you analysis.  I agree with a lot of what you have written, and had a number of conversations with similar ideas.  One challenge with solving the problem generally instead of for specific cases is that we need to understand all of the ways the system may be used and make sure the approach we take makes sense.  We would probably want to start by auditing more defaulting cases  and how they currently work.  Then understand the impacted of the proposed change.  I suspect there are a lot of hidden edge cases and complexity that we may not be aware of until we encounter them.

Some notes

- We should better understand the scope of the problem.  How many edge cases are impacted by this?  Lets look at the defaulting when are doing and understand the scope better.
- What are the types of cases we are seeing?  For the general "one-of" case, Brian Grant has suggested supporting "Union" types, which is a simpler change.  How many of the cases does this solve?  What are the other types of issues we encounter?
- We may even be able to clear defaulted fields on the client side using something like:
  - Last config
  - Last config with defaults
  - Current config
  - `for field := range (last_config_with_defaults.fields - last_config.fields): if field.value == currentconfig.field.value;  new.field.value = nil`

Would you be interested in putting together a formal proposal with an audit of the cases we are solving with this?

**Comment by andronat** [comment]
@pwittrock I would be very interested in putting together a formal proposal. I'm not very sure though what that includes :/ Do you think you will have some time to chat about this?

**Comment by pwittrock** [comment]
@andronat I am out next week, but we can chat this afternoon on hangouts or something.  why don't you PM me on slack with your email and I will create a calendar event.

**Comment by hjacobs** [comment]
We planned to use labels to "promote" deployments to a new stage, i.e. initially the pods would have label `stage: canary` and later change to `stage: production` (the production service would only select pods with `stage: production`). I think this is a pretty simple and valid use case which should not require rolling pod updates. We would not change the deployment `selector` labels, so the behavior should be deterministic and risk-free.

Any ideas or workarounds to make this use case feasible?

**Comment by pwittrock** [comment]
@hjacobs What you are describing seems like it would be a separate issue.  Is this something you would do with apply?

**Comment by hjacobs** [comment]
@pwittrock yes, maybe the feature "do not terminate/create pods on simple label changes (without selector change)" could be a separate issue (if this is what you were referring to).

**Comment by pwittrock** [comment]
Yes that is what I was referring to.

**Comment by grodrigues3** [comment]
@pwittrock i'll let you decide the milestone/path forward on this one

**Comment by liggitt** [comment]
still an issue, but not a regression, and not release blocking

**Comment by martindariocernadas** [comment]
hi guys. is there a planned release where this "kubectl apply" would be implemented without this issue?

**Comment by adam-sandor** [comment]
I just ran into this one by simple changing labels on a Deployment. I removed one label and added 3 new ones.
I'd say this is a pretty serious issue if it can happen under such simple circumstances and blocks a new deployment completely.

**Comment by thockin** [comment]
@pwittrock @mengqiy

**Comment by martindariocernadas** [comment]
Hi everyone. The solution to passover the issue with "apply" command, is to use "replace". It also works in cascade to replace environment entries. You can see "https://vishh.github.io/docs/user-guide/kubectl/kubectl_replace/" 

Example : "kubectl replace -f myfile.yaml"

**Comment by adam-sandor** [comment]
Thanks @martindariocernadas that workaround is helpful. I still would like `kubectl apply` to work as it's great to not have to worry whether an object already exists on the cluster. This makes building CD pipelines much easier.

**Comment by sheerun** [comment]
it happens with helm so workaround is not possible

**Comment by sheerun** [comment]
The working workaround for me is to explicitly set matchLabels in deployment:

```yaml
spec:
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
      release: "{{ .Release.Revision }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        release: "{{ .Release.Revision }}"

```

**Comment by mengqiy** [comment]
Another workaround is explicitly set the matchLabels you want to clear to nulls. It will clear the defaulted labels.

**Comment by kargakis** [comment]
@adohe @janetkuo what's the status of this issue? Are we going to do anything for 1.7?

**Comment by dennis-bell** [comment]
@pwittrock Any update on this issue, kinda annoying that deployment breaks on a label update
We use it for storing versions, but also changing the behaviour like described by @hjacobs

**Comment by shiywang** [comment]
also cc @mengqiy

**Comment by bgrant0607** [comment]
cc @kow3ns

**Comment by rphillips** [comment]
Is this issue considered fixed with the new spec.selector behavior being released in 1.8? 

Reference: [Draft Release Notes](https://github.com/kubernetes/features/blob/master/release-1.8/release_notes_draft.md#behavioral-changes)

**Comment by liggitt** [comment]
in apps/v1beta2, defaults are no longer set on spec.selector

however, the spec.selector field is also no longer allowed to mutate at all in apps/v1beta2 as of https://github.com/kubernetes/kubernetes/pull/50719

**Comment by tonglil** [comment]
It seems like this is still an issue for me w/ `extensions/v1beta1`, even though it is should work based on the release notes from 50719:

> For Deployment, ReplicaSet, and DaemonSet, selectors are now immutable when updating via the new `apps/v1beta2` API. For backward compatibility, selectors can still be changed when updating via `apps/v1beta1` or `extensions/v1beta1`.

**Comment by kow3ns** [comment]
@tonglil We can't modify the behavior of extensions/v1beta1 without breaking backward compatibility.

**Comment by liggitt** [comment]
This was resolved in apps/v1beta2 and forward by requiring selectors to be explicitly defined, disallowing mutation on those fields

**Comment by ltupin** [comment]
> disallowing mutation on those fields

Why do we want this immutable ?

**Comment by janetkuo** [comment]
@ltupin because it's not safe to mutate a controller's selector. For example, deployment finds its children resources (replicasets) by label/selector. Changing a deployment's selector is dangerous. It could cause the deployment to be unable to find its existing children and therefore cause disruptions to your running workloads. We don't want to encourage that.

**Comment by Sergey80** [comment]
still reproducible in apps/v1beta2

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: $APP_NAME-deployment
  labels:
    app: $APP_NAME-k8s ...

**Comment by liggitt** [comment]
Mutation of label selectors on deployments, replicasets, and daemonsets is not allowed in apps/v1beta2 and forward

**Comment by liggitt** [comment]
See https://github.com/kubernetes/kubernetes/issues/50808 for details

**Comment by quinn** [comment]
All i'm seeing is k8s members saying this is "discouraged". What if i have to do this? In production? I have to allocate downtime to destroy the deployment and replace with a new one?

**Comment by cyrilthank** [comment]
faced this issue in https://github.com/kubeflow/kubeflow/issues/4184

**Comment by damien-roche** [comment]
No need to make a big issue out of it. `apply -f` should Just Work. If it screws up my cluster that's my problem, right? Get out of the way Kube. You're meant to help not hinder.

One alternative I can see is to fire up another deployment with a different selector and update services to apps in that deployment, destroy the old deployment. Bit messy and plenty could go wrong. Hopefully you remove this limitation once the API has solidified more as per the comment in https://github.com/kubernetes/kubernetes/issues/50808. This is primarily the kind of stuff that should be automated - the whole point of Kubernetes.

**Comment by hmtai** [comment]
I encountered the same problem when rollback the chart from the  selector manully added chart to no selector chart:
`
stderr: 'Error: Failed to recreate resource: DaemonSet.apps "internal-management-ingress" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"internal-management-ingress", "chart":"icp-management-ingress", "component":"internal-management-ingress", "heritage":"Tiller", "k8s-app":"internal-management-ingress", "release":"internal-management-ingress"}: `selector` does not match template `labels`'
`

**Comment by Abhinav054** [comment]
Can you post the yaml file you are trying to apply for?

**Comment by hmtai** [comment]
@Abhinav054 This is helm rollback process:
```
helm rollback --debug --tls   --force internal-management-ingress 2
[debug] Created tunnel using local port: '36208'

[debug] SERVER: "127.0.0.1:36208"

[debug] Host="", Key="/root/.helm/key.pem", Cert="/root/.helm/cert.pem", CA="/root/.helm/ca.pem"

Error: failed to create resource: DaemonSet.apps "internal-management-ingress" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"internal-management-ingress", "chart":"icp-management-ingress", "component":"internal-management-ingress", "heritage":"Tiller", "k8s-app":"internal-management-ingress", "release":"internal-management-ingress"}: `selector` does not match template `labels`
```

**Comment by Abhinav054** [comment]
Do you have any app with the given template label running.

**Comment by Bjohnson131** [comment]
> All i'm seeing is k8s members saying this is "discouraged". What if i have to do this? In production? I have to allocate downtime to destroy the deployment and replace with a new one?

So far the answer seems to be a tentative yes?
