### ISSUE TITLE
Make clientset of federation controllers identical

### ISSUE THREAD

**Issue by mfanjie** [kubernetes/kubernetes#26608]
@nikhiljindal there are two controllers in federation for v1.3, however the clientset of cluster controller and service controller are different so I open this issue to discuss with you how to keep them identical.
1. The versioned clientset kept broken before I merged service controller, like watcher always get a unversioned object so the type assertion is always failed, so after checking with caesarxuchao, I changed the clientset and object in service controller to unversioned, but in cluster controller, they are versioned. We need to decide which one we should use.
2. Cluster controller has a go file cluster_client.go to create clientset and the clientset was wrapped as private member of ClusterClient which can not be refered by service controller. In service controller, I  duplicated to origin code of NewClusterClientSet() to create clientset(discoveryClient is not needed however), however NewClusterClientSet was changed, so the right way to make it work is to add a util func to return *clientset.Clientset so that both controller can call.

what do you say?

**Comment by mfanjie** [comment]
@quinton-hoole FYI.

**Comment by nikhiljindal** [comment]
1. Till a month back all controllers were using unversioned clientset. @caesarxuchao is working on moving them to versioned clientset. However, as we are making this change, we are discovering problems with versioned clientset. We are fixing them as we discover new problems and are gradually moving controllers to use them. As we make the change, temporarily some controllers will be using versioned clients while some will still be using unversioned ones. The ultimate aim is for all controllers to use versioned clientsets.
In this particular case, we didnt have an problem in using versioned clientset in cluster controller so thats what we are using. We should move service controller to use them as well, whenever we are able to fix the watch problem you described.

2. Yes reusing code is definitely better :) We can create a new method that creates clusterConfig from Cluster obejct. NewClusterClientSet can first call this method to get the clusterConfig and then we already have functions to get clientset and discovery client from clusterConfig. ServiceController can also use that method to first get clusterConfig from Cluster object and then use the config to get the clientset.

**Comment by nikhiljindal** [comment]
Also the watch problem you were facing should be fixed now that https://github.com/kubernetes/kubernetes/pull/26251 is merged.

**Comment by mfanjie** [comment]
Thanks, I am working on changing service controller clientset to versioned one.

**Comment by mfanjie** [comment]
still see the error with latest build
E0602 17:32:00.429449   17501 reflector.go:374] k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:111: expected type *federation.Cluster, but watch event object had type *v1alpha1.Cluster

**Comment by caesarxuchao** [comment]
The fix for the watch problem is https://github.com/kubernetes/kubernetes/pull/26493. Hopefully it will be merged soon.

**Comment by caesarxuchao** [comment]
Thanks for using the versioned clientset. Feel free to ping me on any friction you have.

**Comment by mfanjie** [comment]
versioned clientset works with #26493 code merged.
I made patch for the discussions in this issue by #26694

**Comment by mfanjie** [comment]
#26694 merged
