### ISSUE TITLE
ERROR: Error fetching remote repo 'origin'

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#26822]
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26820/kubernetes-pull-build-test-e2e-gce/43224/

```

ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/kubernetes/kubernetes
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:810)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1066)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1097)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "/usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/26820/*:refs/remotes/origin/pr/26820/*" returned status code 128:
stdout: 
stderr: error: RPC failed; result=18, HTTP code = 200
fatal: The remote end hung up unexpectedly

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1719)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1463)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:63)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:314)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to agent-pr-2(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
	at hudson.remoting.Channel.call(Channel.java:781)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
	at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
	at com.sun.proxy.$Proxy58.execute(Unknown Source)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:808)
	... 11 more
ERROR: null
```

**Comment by ixdy** [comment]
looks like a dupe of #14074 / #18960. cc @spxtr

**Comment by spxtr** [comment]
oh dear, this again. This one is a real bother. I spent a long time trying to figure out what was going on and didn't figure out much.

**Comment by fejta** [comment]
Please reactive if you see this after June 15.

**Comment by JoshFialkoff** [comment]
I am getting the same error. Are there any other suggestions on how to fix this? Should I contact the hosting company?

**Comment by gmarek** [comment]
@ixdy - happened again in #32070

**Comment by spxtr** [comment]
@gmarek I think that one was slightly different. @rmmh might have already fixed it, but I'm not sure.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/32070/kubernetes-pull-build-test-e2e-gke/11056/

**Comment by rmmh** [comment]
This particular agent was restarted and ended up having a corrupt workspace. This caused by my change to retain `.git` directories to speed up clones and avoid getting ratelimited by github.

I'll look into automatically detecting this case.

**Comment by rmmh** [comment]
Closing for now, will reopen if we see any more workspace corruption.

**Comment by aliser** [comment]
I see it happens again:

ERROR: Timeout after 10 minutes
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/wpmedia/qa.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:803)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1063)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1094)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1278)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: hudson.plugins.git.GitException: Command "git.exe fetch --tags --progress https://github.com/wpmedia/qa.git +refs/heads/*:refs/remotes/origin/*" returned status code -1:
stdout: 
stderr: 
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1784)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1513)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:64)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:315)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:801)
	... 11 more
ERROR: null
Finished: FAILURE

**Comment by rmmh** [comment]
That's not a kubernetes repo. This isn't a generic jenkins bug.

**Comment by yushamariak** [comment]
@aliser I'm having the same problem as you. Was it solved?

**Comment by aliser** [comment]
I believe it was solved by using GitHub SSH authentication

**Comment by SanjanaTailor** [comment]
Hello, I am also facing a same problem can you guide me how does this issue resolved using GitHub SSH authentication ?

**Comment by sachindj** [comment]
Even we are facing same problem. Can someone help us?
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:testuser/testrepo.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:809)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1076)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1107)
	at hudson.scm.SCM.checkout(SCM.java:496)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1278)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)

**Comment by SanjanaTailor** [comment]
yes, it's resolved now. Check first your repository is private ? 
If that's the case go to your github where your project is uploaded. Now go to settings and under Personal settings there's an option says Personal access token and click on it it will asked your github password enter it and it will generate your access token copy it and save it in some file.
Now, if you are working with Jenkins go to your project's configuration and in that go to source code Management under git url there's credentials option add your username and password should be added as access token save it and select your credential from drop down box.
now github urls should be replaced with current repo address as with access token;
https://access token number@github.com/git repo.git/ save it and run it.

**Comment by sachindj** [comment]
seems still issue persists, please suggest further

Fetching changes from the remote Git repository
 > git config remote.origin.url https://cd5dba78a5dfccaae1b5574b09b1ff155a89da49@cto-github.cisco.com/hkona/vmsauto.git # timeout=10
Fetching upstream changes from https://cd5dba78a5dfccaae1b5574b09b1ff155a89da49@cto-github.cisco.com/hkona/vmsauto.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://cd5dba78a5dfccaae1b5574b09b1ff155a89da49@cto-github.cisco.com/hkona/vmsauto.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://cd5dba78a5dfccaae1b5574b09b1ff155a89da49@cto-github.cisco.com/hkona/vmsauto.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:809)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1076)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1107)
	at hudson.scm.SCM.checkout(SCM.java:496)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1278)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://cd5dba78a5dfccaae1b5574b09b1ff155a89da49@cto-github.cisco.com/hkona/vmsauto.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: error: The requested URL returned error: 403 Forbidden while accessing https://cd5dba78a5dfccaae1b5574b09b1ff155a89da49@cto-github.cisco.com/hkona/vmsauto.git/info/refs

fatal: HTTP request failed

**Comment by SanjanaTailor** [comment]
Are you facing an issue for running application or building for Jenkins? have you added credentials under SCM ?

**Comment by sachindj** [comment]
yes, I have added credentials for SCM. I am struggling while building for jenkins

**Comment by SanjanaTailor** [comment]
https://cd5dba78a5dfccaae1b5574b09b1ff155a89da49@cto-github.cisco.com/hkona/vmsauto.git/ did you append '/' end of the file ?

**Comment by sachindj** [comment]
After append '/' I got like this

Building in workspace /var/lib/jenkins/workspace/GUI testsuite
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://cd5dba78a5dfccaae1b5574b09b1ff155a89da49@cto-github.cisco.com/hkona/vmsauto.git/ # timeout=10
Fetching upstream changes from https://cd5dba78a5dfccaae1b5574b09b1ff155a89da49@cto-github.cisco.com/hkona/vmsauto.git/
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://cd5dba78a5dfccaae1b5574b09b1ff155a89da49@cto-github.cisco.com/hkona/vmsauto.git/ +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
 > git rev-parse origin/master^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Finished: FAILURE

**Comment by SanjanaTailor** [comment]
are you using skype ? give me asap

**Comment by sachindj** [comment]
No. we are not using skype.

**Comment by SanjanaTailor** [comment]
![crdentials](https://cloud.githubusercontent.com/assets/4736998/25379946/2aa91dc6-29cc-11e7-8547-6d81bc411f66.PNG)

my url format is as below : https://0da6daa7b1c3ad688381e17b2f42c1b90b1ebefa@github.com/git_hub_reponame.git
make sure you followed correct path

**Comment by sachindj** [comment]
skype name: nagesh.cherukuri2

**Comment by SanjanaTailor** [comment]
Make sure in Jenkins credentials your password must be access token, that's a problem at your end, run Jenkins again after update it

**Comment by spxtr** [comment]
@sachindj, your error is unrelated to the original error in this issue, and also unrelated to kubernetes. Please open an issue in a more relevant repository, perhaps [jenkinsci/git-plugin](https://github.com/jenkinsci/git-plugin)'s [JIRA](https://issues.jenkins-ci.org/secure/Dashboard.jspa).
