### ISSUE TITLE
Don't require a trailing '.' in federation-controller DNS zone

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#28335]
See https://github.com/kubernetes/kubernetes/issues/28324

**Comment by quinton-hoole** [comment]
@madhusudancs FYI :)

**Comment by quinton-hoole** [comment]
This is purely a usability issue (it's confusing that the config doesn't work without the trailing dot).  It's a 1-line, very low risk change affecting only the federation service controller.

**Comment by pwittrock** [comment]
@quinton-hoole I am leaving this in the 1.4 release as a blocking issue.  Please provide daily status updates to this issue or move it out of the release and into v1.4-nonblocking where it will no longer be tracked as a release blocking issue in the burndown meetings.

**Comment by goltermann** [comment]
Moving to v1.5, this is a non-release-blocker.

**Comment by quinton-hoole** [comment]
I'm pretty sure that @justinsb fixed this in one of his PR's. Will check.

**Comment by quinton-hoole** [comment]
Indeed, this is fixed:

https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/federation-controller/service/dns.go#L109

Closing.

**Comment by Smana** [comment]
I still faced the same issue. I had to append a trailing dot to the domain name.
Could you please reopen this issue ?

**Comment by MQasimSarfraz** [comment]
@pwittrock @quinton-hoole I was looking to contribute to kubernetes but seems like this issues has already been resolved. We should close it. Right?

**Comment by madhusudancs** [comment]
@MQasimSarfraz it's not fully resolved. @csbell fixed this in kubefed. We need to fix federation controller manager as well.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#53.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
