### ISSUE TITLE
kube-apiserver and TLS etc: kubectl reports unhealthy cluster

### ISSUE THREAD

**Issue by xgerman** [kubernetes/kubernetes#29330]
I am running v1.3.0-beta.1 and have set up etc, k8 with TLS. Here is the relevant part for the kube-apiserver:
--etcd_servers=https://192.168.200.2:2379 \
--etcd-cafile=/srv/kubernetes/ca.crt \
--etcd-certfile=/srv/kubernetes/kubecfg.crt \
--etcd-keyfile=/srv/kubernetes/kubecfg.key \

I tried it running without those parameters and kube-apiserver didn't start but failed with (from the logs):
etcd cluster is unavailable or misconfigured

So it can do something with those certs.

Now, when I run 
vagrant@k8-master:~$ kubectl get cs
NAME                 STATUS      MESSAGE                                                                ERROR
scheduler            Healthy     ok
controller-manager   Healthy     ok
etcd-0               Unhealthy   Get https://192.168.200.2:2379/health: remote error: bad certificate

But when I run etcdctl using the SAM certificates:
vagrant@k8-master:~$ sudo etcdctl --debug --endpoints https://192.168.200.2:2379 --ca-file /srv/kubernetes/ca.crt --key-file /srv/kubernetes/kubecfg.key --cert-file /srv/kubernetes/kubecfg.crt cluster-health
Cluster-Endpoints: https://192.168.200.2:2379
cURL Command: curl -X GET https://192.168.200.2:2379/v2/members
member ce2a822cea30bfca is healthy: got healthy result from https://192.168.200.2:2379
cluster is healthy

Furthermore:
sudo etcdctl --debug --endpoints https://192.168.200.2:2379 --ca-file /srv/kubernetes/ca.crt --key-file /srv/kubernetes/kubecfg.key --cert-file /srv/kubernetes/kubecfg.crt ls registry
start to sync cluster using endpoints(https://192.168.200.2:2379)
cURL Command: curl -X GET https://192.168.200.2:2379/v2/members
got endpoints(https://192.168.200.2:2379) after sync
Cluster-Endpoints: https://192.168.200.2:2379
cURL Command: curl -X GET https://192.168.200.2:2379/v2/keys/registry?quorum=false&recursive=false&sorted=false
/registry/ranges
/registry/namespaces
/registry/events
/registry/services
/registry/serviceaccounts
/registry/secrets
/registry/deployments
/registry/replicasets
/registry/pods

I suspect that some code path in kube-apiserver isn't aware of the certificates?

**Comment by elcct** [comment]
I have the same issue. 
I am running Kubernetes 1.3.5 with Etcd 2.3.7 on Ubuntu 16.04.

```
root@gc01:/opt/kubernetes/certs# $GOPATH/bin/etcdctl -ca-file=ca.pem -cert-file=client.pem -key-file=client-key.pem -endpoints=https://gc01.xxxxx:2379 ls registry
/registry/ranges
/registry/namespaces
/registry/services
/registry/serviceaccounts
```

```
root@gc01:/opt/kubernetes/certs# $GOPATH/bin/etcdctl -ca-file=ca.pem -cert-file=client.pem -key-file=client-key.pem -endpoints=https://gc01.xxxxx:2379 cluster-health
member 12fabe43e0b7020b is healthy: got healthy result from https://gc01.xxxxx:2379
member 3e9e6038432c0da7 is healthy: got healthy result from https://gc03.xxxxx:2379
member 5223f27d945df07a is healthy: got healthy result from https://gc05.xxxxx:2379
member 6c3dd0c34e4e7bee is healthy: got healthy result from https://gc02.xxxxx:2379
member e32849a38113a4f2 is healthy: got healthy result from https://gc04.xxxxx:2379
cluster is healthy
```

```
root@gc01:/opt/kubernetes/certs# /opt/kubernetes/bin/kubectl get cs
NAME                 STATUS      MESSAGE                                                                         ERROR
controller-manager   Healthy     ok
scheduler            Healthy     ok
etcd-0               Unhealthy   Get https://gc01.xxxxx:2379/health: remote error: bad certificate
etcd-3               Unhealthy   Get https://gc04.xxxxx:2379/health: remote error: bad certificate
etcd-4               Unhealthy   Get https://gc05.xxxxx:2379/health: remote error: bad certificate
etcd-2               Unhealthy   Get https://gc03.xxxxx:2379/health: remote error: bad certificate
etcd-1               Unhealthy   Get https://gc02.xxxxx:2379/health: remote error: bad certificate
```

My etcd part of apiserver configuration is the same is in the post above:

```
  --etcd-cafile=/opt/kubernetes/certs/ca.pem \
  --etcd-certfile=/opt/kubernetes/certs/client.pem \
  --etcd-keyfile=/opt/kubernetes/certs/client-key.pem \
  --etcd-servers=https://gc01.xxxxx:2379,https://gc02.xxxxx:2379,https://gc03.xxxxx:2379,https://gc04.xxxxx:2379,https://gc05.xxxxx:2379 \
```

What to do?

**Comment by elcct** [comment]
It seems like this is the same problem: https://github.com/kubernetes/kubernetes/issues/27343#issuecomment-226095062

**Comment by esayemm** [comment]
@elcct Hello did you ever find a solution to this?

**Comment by elcct** [comment]
@esayemm sadly not. Also tried Kubernetes 1.4.5 - doesn't work :(

**Comment by sergeyfd** [comment]
Still same issue in 1.5.1

**Comment by upolymorph** [comment]
Yes I have the same issue too with 1.5.1 and checked that curl with correct --cacert --cert --key option is able to get from etcd url/heath: {"health": "true"}

**Comment by yawboateng** [comment]
seeing the same issue in 1.5.2

**Comment by elcct** [comment]
It seems like the fix is in the making, there is a pull request:

https://github.com/kubernetes/kubernetes/pull/39716

**Comment by strugglingyouth** [comment]
Yes I have the same issue too .

etcdctl version: 3.1.3
API version: 3.1
Kubernetes v1.6.0-beta.1 (master and  node)

config apiserver as follow:

--etcd-cafile='/var/run/kubernetes/ca.pem' --etcd-certfile='/var/run/kubernetes/client.pem' --etcd-keyfile='/var/run/kubernetes/client-key.pem' --client-ca-file='/var/run/kubernetes/ca.pem'

create deployment and other is right, etcd is ok.

$ kubectl get cs
NAME                 STATUS      MESSAGE                                                                   ERROR
controller-manager   Healthy     ok
scheduler            Healthy     ok
etcd-0               Unhealthy   Get https://xxxx:2379/health: remote error: tls: bad certificate

**Comment by javapapo** [comment]
+1 

Kubernetes : 1.5.3 
Cloud Provider: AWS
Installed with : kube-aws

`etcd-2               Unhealthy   Get https://xxxx.compute.internal:2379/health: remote error: tls: bad certificate
etcd-1               Unhealthy   Get https://xxxxxx.compute.internal:2379/health: remote error: tls: bad certificate
etcd-0               Unhealthy   Get https://xxxxxx.compute.internal:2379/health: remote error: tls: bad certificate

**Comment by kgrvamsi** [comment]
Does Kubectl have a option to provide the etcd key when trying to query the component status?
something like 

```
kubectl --etcd-key key.pem get cs

```

**Comment by VsMaX** [comment]
+1 
Kubernetes : 1.6.4
Cloud Provider: Vagrant - 3 nodes
Installed with : github.com/kelseyhightower/kubernetes-the-hard-way

**Comment by xgerman** [comment]
@kubernetes/sig-ui

**Comment by x1957** [comment]
```
[root@c3-cloudml-srv-ct01 etcd]# kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
[root@c3-cloudml-srv-ct01 etcd]# etcdctl --ca-file=/root/ssl/etcd/ca.pem --cert-file=/root/ssl/etcd/etcd.pem --key-file=/root/ssl/etcd/etcd-key.pem --endpoints=https://xxxx:2379,https://xxxx:2379,https://xxxx:2379 cluster-health
2017-06-16 09:41:36.277313 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
2017-06-16 09:41:36.278113 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
member 269592983f1bbc6c is healthy: got healthy result from https://xxxx:2379
member 961ff05c1312685d is healthy: got healthy result from https://xxxx:2379
member d64dfe4c6ed3bddd is healthy: got healthy result from https://xxxx:2379
cluster is healthy

```

```
[root@c3-cloudml-srv-ct01 etcd]# kubectl get cs
NAME                 STATUS      MESSAGE                                                                    ERROR
controller-manager   Healthy     ok                                                                         
scheduler            Healthy     ok                                                                         
etcd-0               Unhealthy   Get https://xxxx:2379/health: remote error: tls: bad certificate   
etcd-2               Unhealthy   Get https://xxxx:2379/health: remote error: tls: bad certificate   
etcd-1               Unhealthy   Get https://xxxx:2379/health: remote error: tls: bad certificate   
```

**Comment by antoineco** [comment]
Fixed in #39716. Will be in Kubernetes 1.7.

**Comment by avalonzst** [comment]
problem still occurs for kubenetes1.6.0 with etcd 3.3.8
[root@umsk8s-master kubernetes]# etcdctl --version
etcdctl version: 3.3.8
API version: 2
[root@umsk8s-master kubernetes]# kube-apiserver --version
Kubernetes v1.6.0
[root@umsk8s-master kubernetes]# kubectl get cs
NAME                 STATUS      MESSAGE                                                                       ERROR
controller-manager   Healthy     ok                                                                            
scheduler            Healthy     ok                                                                            
etcd-0               Unhealthy   Get https://172.30.251.200:20079/health: remote error: tls: bad certificate   
etcd-1               Unhealthy   Get https://172.30.251.201:20179/health: remote error: tls: bad certificate   
etcd-4               Unhealthy   Get https://172.30.251.204:20479/health: remote error: tls: bad certificate   
etcd-2               Unhealthy   Get https://172.30.251.202:20279/health: remote error: tls: bad certificate   
etcd-3               Unhealthy   Get https://172.30.251.203:20379/health: remote error: tls: bad certificate   
[root@umsk8s-master kubernetes]#
