### ISSUE TITLE
Node E2E: Memory eviction test cause pods in following test being evicted.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#30550]
We need an issue to track this.

Recently we added the memory eviction test https://github.com/kubernetes/kubernetes/pull/28693.
Currently, it is running in the serial test job. However, after adding it all test running after it could not start pod.

They all failed with the reason `Evicted: The node was low on compute resources.`.

Currently, we are not sure that:
* Is this because the memory is not reclaimed?
* Is this because cadvisor probe interval is too long?
* Is this because there is any bug in current memory eviction implementation?

Anyhow, currently all serial node e2e builds are red, we should fix this or disable the test.

@derekwaynecarr @vishh @mtaufen 
/cc @kubernetes/sig-node

**Comment by vishh** [comment]
> Is this because the memory is not reclaimed?

Quite possible. Memory reclamation is typically slower than pod creation and deletion.
We should have the test ensure that memory has been reclaimed before it exits.

**Comment by ronnielai** [comment]
There's also eviction-pressure-transition-period, which determines how fast the node pressure condition can be relieved after the resource is reclaimed. So ideally the test should also check the node's pressure condition is eventually gone after eviction happens.

**Comment by vishh** [comment]
That's a great suggestion!

**Comment by mtaufen** [comment]
/cc @dawnchen

Dawn and I had a chat about this the other day after I had originally put
up a PR to wait for a decent chunk of memory to be available after the
test. My understanding from our conversation is that, because the charge
for the pages in a container's cgroup is re-parented to the root cgroup
when that container is removed, certain kinds of pages can stick around for
quite some time, and we could end up waiting for a long time for more
available memory. I'd have to actually go read some kernel source and know
more about the Go runtime to know whether the pages consumed by @vishh's
stress image are the kind of page that would not be immediately reclaimed
when the container is killed, but this came up as a concern.

We think it might be worth it to just isolate disruptive tests in their own
nodes.

**Comment by vishh** [comment]
> tress image are the kind of page that would not be immediately reclaimed
when the container is killed, but this came up as a concern.

They are RSS pages, and so we can force the kernel to reclaim pages. I can
talk to you offline about this.

**Comment by Random-Liu** [comment]
> We think it might be worth it to just isolate disruptive tests in their own
nodes.

We don't have the infrastructure for disruptive test yet. Marking it as Disruptive doesn't help for now. :)

**Comment by yujuhong** [comment]
The "Disruptive" tests in the cluster e2e suites still restore the environment after the test. They just can't be run in parallel with other tests, and also can't be run in the soak cluster where we test long-running daemons. If we want the nodes to be destroyed after the test, we should come up with a new category.

**Comment by mtaufen** [comment]
"Armageddon" tests? :P

**Comment by yujuhong** [comment]
> "Armageddon" tests? :P

That's a good name, if we ever need one ;)

**Comment by ronnielai** [comment]
"Mount doom" tests. :)

**Comment by Random-Liu** [comment]
We've got several issues caused by this, just track them here so that we can close them all later:
* https://github.com/kubernetes/kubernetes/issues/31011
* https://github.com/kubernetes/kubernetes/issues/30978
* https://github.com/kubernetes/kubernetes/issues/30867
* https://github.com/kubernetes/kubernetes/issues/30862

BTW, can we temporarily disable the memory eviction test https://github.com/kubernetes/kubernetes/pull/30654 or have a quick fix https://github.com/kubernetes/kubernetes/pull/30476? It seems that there are some real issues in performance test, but currently mixed in the "fake" ones. :)

**Comment by yujuhong** [comment]
If we can't get a quick fix in for the eviction test, I'd vote for disabling it now. It's crunch time for the release, and the test has caused quite a lot of noise.

**Comment by Random-Liu** [comment]
After #30476 merged, the following few tests still fail because of cadvisor pod got evicted:
```
19:00:32 • [SLOW TEST:2108.915 seconds]
19:00:32 [k8s.io] MemoryEviction [Slow] [Serial] [Disruptive]
19:00:32 /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:709
19:00:32   When there is memory pressure
19:00:32   /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/memory_eviction_test.go:159
19:00:32     It should evict pods in the correct order (besteffort first, then burstable, then guaranteed)
19:00:32     /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/memory_eviction_test.go:158
19:00:32 ------------------------------
19:00:32 SSSSSSSSSSSSSSSS
19:00:32 ------------------------------
19:00:32 [k8s.io] Density [Serial] [Slow] create a batch of pods 
19:00:32   latency/resource should be within limit when create 10 pods with 0 interval [Benchmark]
19:00:32   /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/density_test.go:151
19:00:32 [BeforeEach] [k8s.io] Density [Serial] [Slow]
19:00:32   /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:126
19:00:32 STEP: Creating a kubernetes client
19:00:32 STEP: Building a namespace api object
19:00:32 Aug 20 01:53:03.325: INFO: Skipping waiting for service account
19:00:32 [BeforeEach] [k8s.io] Density [Serial] [Slow]
19:00:32   /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/density_test.go:74
19:00:32 W0820 01:53:03.337344    1184 request.go:351] Field selector: v1 - pods - metadata.name - cadvisor: need to check if this is versioned correctly.
19:00:32 Aug 20 01:53:03.338: INFO: Unexpected error occurred: pod ran to completion
19:00:32 [AfterEach] [k8s.io] Density [Serial] [Slow]
19:00:32   /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:127
19:00:32 STEP: Collecting events from namespace "e2e-tests-density-test-2s1d9".
19:00:32 Aug 20 01:53:03.341: INFO: At 2016-08-20 01:53:03 +0000 UTC - event for cadvisor: {kubelet tmp-node-e2e-d74fd25a-gci-dev-54-8711-0-0} Evicted: The node was low on compute resources.
19:00:32 Aug 20 01:53:03.344: INFO: POD       NODE                                       PHASE   GRACE  CONDITIONS
19:00:32 Aug 20 01:53:03.344: INFO: cadvisor  tmp-node-e2e-d74fd25a-gci-dev-54-8711-0-0  Failed         []
```
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubelet-serial-gce-e2e-ci/298

**Comment by Random-Liu** [comment]
Besides this, there is another problem in serial suite. Currently, we have a **45min** timeout for node e2e test, which is too short for serial test.
This causes the test got stopped after 45min before finishing:
```
19:00:32 Received interrupt.  Running AfterSuite...
19:00:32 ^C again to terminate immediately
19:00:32 I0820 02:00:31.713755    1184 e2e_node_suite_test.go:156] Tests Finished
19:00:32 
19:00:32 
19:00:32 Summarizing 4 Failures:
19:00:32 
19:00:32 [Fail] [k8s.io] Density [Serial] [Slow] [BeforeEach] create a batch of pods latency/resource should be within limit when create 10 pods with 0 interval [Benchmark] 
19:00:32 /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:57
19:00:32 
19:00:32 [Fail] [k8s.io] Resource-usage [Serial] [Slow] [BeforeEach] regular resource usage tracking resource tracking for 10 pods per node [Benchmark] 
19:00:32 /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:57
19:00:32 
19:00:32 [Fail] [k8s.io] Density [Serial] [Slow] [BeforeEach] create a sequence of pods latency/resource should be within limit when create 30 pods with 50 background pods [Benchmark] 
19:00:32 /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:57
19:00:32 
19:00:32 [Fail] [k8s.io] Density [Serial] [Slow] [BeforeEach] create a sequence of pods latency/resource should be within limit when create 10 pods with 50 background pods [Benchmark] 
19:00:32 /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:57
19:00:32 
19:00:32 Ran 13 of 120 Specs in 2699.614 seconds
19:00:32 FAIL! -- 5 Passed | 4 Failed | 0 Pending | 107 Skipped 
```
I'll send a PR to make the timeout configurable and set it longer for serial test.

**Comment by mikedanese** [comment]
kubernetes-e2e-gce-serial is consistently failing and keeping us from releasing an alpha.

**Comment by Random-Liu** [comment]
Offline discussed with @mikedanese, this is not a release blocker. :)

However, we should fix the test suite, we don't even have a green build till now. :( And there are a bunch of related issues filed.

**Comment by yujuhong** [comment]
This is still happening. Could we skip the test until we can properly fix it? @vishh @dchen1107

**Comment by vishh** [comment]
Why? I thought we ensure that at-least 50% of memory is available..

**Comment by yujuhong** [comment]
@vishh, uh.. I don't know, but we should try to understand/debug it separately without failing the entire suite.

**Comment by Random-Liu** [comment]
Yeah, we could still see:
```
event for cadvisor: {kubelet tmp-node-e2e-0aba0156-coreos-alpha-1122-0-0-v20160727} Evicted: The node was low on compute resources.
```
Could this mean that we have something suspicious in our code?

**Comment by vishh** [comment]
I'm concerned that by disabling the test without understanding the root
cause, we might let important bugs slip by.

**Comment by yujuhong** [comment]
> I'm concerned that by disabling the test without understanding the root
> cause, we might let important bugs slip by.

I am not saying we shouldn't fix this test or understanding the root cause, but I don't get why that couldn't be fixed out of band.
I also don't think that we should sacrifice other tests in the same suite. They could've caught bugs too, if they were running.

**Comment by vishh** [comment]
You say "fix the test". Does that mean that the root cause is the "test
itself" or could there be bugs in kubelet?

**Comment by yujuhong** [comment]
I don't think it matters whether the problem is in the test or kubelet itself. It needs to be fixed, and there is no need to block other tests from running, and potentially catching bugs, in the meantime.
Either we move the eviction (or all disruptive) tests to a new suite, or we disable until we know what's going on.

**Comment by mtaufen** [comment]
I would be in favor of moving disruptive tests to a separate suite. That way they can continue to surface issues without blocking other tests from surfacing issues.

**Comment by dchen1107** [comment]
Here is what I proposed to @mtaufen & @Random-Liu a while back:

1) Move all disruptive tests (OOM, OOD, restart etc.) to a separate jenkins job, so that those disruptive tests won't cause unnecessary flakiness to rest the tests. 
2) Update our test harness by adding the logic to reboot / recreate the node. So that before each discruptive test run, the node can be back to the clean state. 

WDYT?

**Comment by mtaufen** [comment]
I like the idea of clean-slating each disruptive test. We should have a way to write really mean tests without worrying about them interfering with others.

**Comment by vishh** [comment]
My moving the disruptive tests away, I'm concerned that we might not catch
the bugs that get surfaced by combing disruptive tests with non-disruptive
ones.

**Comment by mtaufen** [comment]
Then could we have a non-disruptive-only and a combined disruptive and non-disruptive suite?

**Comment by dchen1107** [comment]
Ok, I am going to root cause the reason then decide what is the next step.

**Comment by yujuhong** [comment]
We already know there is an issue triggered by the test. What good does it do to fail other tests while root causing the issue?...

**Comment by dchen1107** [comment]
I quickly scanned through last couple failure builds, and all are caused by disk eviction test, which I believe it should be fixed by https://github.com/kubernetes/kubernetes/pull/31200

**Comment by dchen1107** [comment]
@yujuhong Here is unknown issue which puzzles me. In one of old builds: http://kubekins.dls.corp.google.com/view/Node/job/kubelet-serial-gce-e2e-ci/409/consoleFull

1) MemoryEviction is running and waiting for the available memory is enough (at least from test log):
```
09:01:32 I0824 15:45:44.137229    2396 memory_eviction_test.go:87] Pod phase: guaranteed: Running, burstable: Failed, besteffort: Failed
09:01:32 I0824 15:45:44.179293    2396 memory_eviction_test.go:107] Waiting for available memory to decrease to a reasonable level before ending the test.
09:01:32 I0824 15:45:44.677025    2396 memory_eviction_test.go:150] Current available memory is: 250871808 bytes. Waiting for at least 1940256768 bytes available.
09:01:32 I0824 15:45:49.709070    2396 memory_eviction_test.go:107] Waiting for available memory to decrease to a reasonable level before ending the test.
09:01:32 I0824 15:45:49.719726    2396 memory_eviction_test.go:150] Current available memory is: 250871808 bytes. Waiting for at least 1940256768 bytes available.
09:01:32 I0824 15:45:54.720007    2396 memory_eviction_test.go:107] Waiting for available memory to decrease to a reasonable level before ending the test.
09:01:32 I0824 15:45:54.731339    2396 memory_eviction_test.go:150] Current available memory is: 250871808 bytes. Waiting for at least 1940256768 bytes available.
09:01:32 I0824 15:45:59.731643    2396 memory_eviction_test.go:107] Waiting for available memory to decrease to a reasonable level before ending the test.
09:01:32 I0824 15:45:59.742181    2396 memory_eviction_test.go:150] Current available memory is: 3653787648 bytes. Waiting for at least 1940256768 bytes available.
09:01:32 [AfterEach] [k8s.io] MemoryEviction [Slow] [Serial] [Disruptive]
09:01:32   /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:132
09:01:32 Aug 24 15:45:59.876: INFO: Waiting up to 1m0s for all nodes to be ready
09:01:32 STEP: Destroying namespace "e2e-tests-eviction-test-1fnrv" for this suite.
```

I think we should improve the memory eviction test itself not only check the available memory, also check the node condition too. @vishh @mtaufen Is it possible the node is not ready yet? 

2) Resource tracking test is start but quickly failed due to cadvisor pod cannot be scheduled. 

```
09:01:32 [k8s.io] Resource-usage [Serial] [Slow] regular resource usage tracking 
09:01:32   resource tracking for 10 pods per node
09:01:32   /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/resource_usage_test.go:89
09:01:32 [BeforeEach] [k8s.io] Resource-usage [Serial] [Slow]
09:01:32   /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:131
09:01:32 STEP: Creating a kubernetes client
09:01:32 STEP: Building a namespace api object
09:01:32 Aug 24 15:46:05.478: INFO: Skipping waiting for service account
09:01:32 [BeforeEach] [k8s.io] Resource-usage [Serial] [Slow]
09:01:32   /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/resource_usage_test.go:57
09:01:32 W0824 15:46:05.511856    2396 metrics_grabber.go:73] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
09:01:32 Aug 24 15:46:06.460: INFO: Unexpected error occurred: pod ran to completion
09:01:32 [AfterEach] [k8s.io] Resource-usage [Serial] [Slow]
09:01:32   /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:132
09:01:32 STEP: Collecting events from namespace "e2e-tests-resource-usage-6255u".
09:01:32 Aug 24 15:46:06.501: INFO: At 2016-08-24 15:46:06 +0000 UTC - event for cadvisor: {kubelet tmp-node-e2e-f170f56a-e2e-node-ubuntu-trusty-docker10-v1-image} Evicted: The node was low on compute resources.
09:01:32 Aug 24 15:46:06.505: INFO: POD       NODE                                                            PHASE   GRACE  CONDITIONS
09:01:32 Aug 24 15:46:06.505: INFO: cadvisor  tmp-node-e2e-f170f56a-e2e-node-ubuntu-trusty-docker10-v1-image  Failed         []
09:01:32 Aug 24 15:46:06.506: INFO: 
09:01:32 Aug 24 15:46:06.507: INFO: 
09:01:32 Logging node info for node tmp-node-e2e-f170f56a-e2e-node-ubuntu-trusty-docker10-v1-image
09:01:32 Aug 24 15:46:06.509: INFO: Node Info: &TypeMeta{Kind:,APIVersion:,}
09:01:32 Aug 24 15:46:06.509: INFO: 
09:01:32 Logging kubelet events for node tmp-node-e2e-f170f56a-e2e-node-ubuntu-trusty-docker10-v1-image
09:01:32 Aug 24 15:46:06.510: INFO: 
09:01:32 Logging pods the kubelet thinks is on node tmp-node-e2e-f170f56a-e2e-node-ubuntu-trusty-docker10-v1-image
09:01:32 Aug 24 15:46:06.617: INFO: cadvisor started at 2016-08-24 15:46:06 +0000 UTC (0+0 container statuses recorded)
09:01:33 W0824 15:46:06.620198    2396 metrics_grabber.go:73] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
09:01:33 Aug 24 15:46:06.724: INFO: 
09:01:33 Latency metrics for node tmp-node-e2e-f170f56a-e2e-node-ubuntu-trusty-docker10-v1-image
09:01:33 STEP: Dumping a list of prepulled images on each node
09:01:33 Aug 24 15:46:06.726: INFO: Waiting up to 1m0s for all nodes to be ready
09:01:33 STEP: Destroying namespace "e2e-tests-resource-usage-6255u" for this suite.
09:01:33 [AfterEach] [k8s.io] Resource-usage [Serial] [Slow]
09:01:33   /var/lib/jenkins/workspace/kubelet-serial-gce-e2e-ci/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/resource_usage_test.go:62
09:01:33 W0824 15:46:11.742804    2396 metrics_grabber.go:73] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
09:01:33 Aug 24 15:46:11.767: INFO: runtime operation error metrics:
09:01:33 node "tmp-node-e2e-f170f56a-e2e-node-ubuntu-trusty-docker10-v1-image" runtime operation error rate:
...
```

**Comment by vishh** [comment]
Yes. it is possible to make the wait for the `MemoryPressure` condition to
be `false`.

**Comment by dchen1107** [comment]
@vishh We should wait for both memory available and MemoryPressure condition in MemoryEviction test. It is possible the rest failure are caused by condition is not set to ready.

**Comment by Random-Liu** [comment]
The following pod is not evicted, they are just not admitted by kubelet because of the `MemoryPressure`:
```
W0818 03:35:27.856107    2658 eviction_manager.go:110] Failed to admit pod cadvisor_e2e-tests-density-test-43bif(ce5092e5-64f4-11e6-b1e0-42010a800007) - node has conditions: %v%!(EXTRA []api.NodeConditionType=[MemoryPressure])
I0818 03:35:27.856536    2658 server.go:680] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-density-test-43bif", Name:"cadvisor", UID:"ce5092e5-64f4-11e6-b1e0-42010a800007", APIVersion:"v1", ResourceVersion:"469", FieldPath:""}): type: 'Warning' reason: 'Evicted' The node was low on compute resources.
```
So https://github.com/kubernetes/kubernetes/pull/31386 should be able to fix this.

**Comment by yujuhong** [comment]
@dchen1107, @Random-Liu, thanks a lot for debugging this (and @mtaufen for uploading a fix)!

> So #31386 should be able to fix this.

Correct me if I'm wrong, in general, it shouldn't be too hard to reproduce or verify the fix by running node e2e tests in one's own cluster. The set of tests to run needs to include the eviction test and and a simple test with pod creation.

**Comment by dchen1107** [comment]
@yujuhong you are right on this. :-)

**Comment by dchen1107** [comment]
Close this one via  #31386

**Comment by yujuhong** [comment]
This is still happening. See #30527 for more failures.

**Comment by dchen1107** [comment]
dup of https://github.com/kubernetes/kubernetes/issues/31676
