### ISSUE TITLE
Heapster cpu/usage_rate returns incorrect cpu/usage_rate caused by overflow? 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#30939]
Forked from https://github.com/kubernetes/kubernetes/issues/27194

@ichekrygin reported a weird cpu/usage_rate issue from heapster

I am running on v1.3.5 and this still seems to be an issue

```
curl http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/namespaces/production/pods/rain-377063289-tz0tq/metrics/cpu/usage_rate
{
  "metrics": [
   {
    "timestamp": "2016-08-18T03:04:00Z",
    "value": 18446744073709551449
   },
   {
    "timestamp": "2016-08-18T03:05:00Z",
    "value": 705
   },
   {
    "timestamp": "2016-08-18T03:06:00Z",
    "value": 18446744073709551028
   },
   {
    "timestamp": "2016-08-18T03:07:00Z",
    "value": 696
   },
   {
    "timestamp": "2016-08-18T03:08:00Z",
    "value": 18446744073709550587
   },
   {
    "timestamp": "2016-08-18T03:09:00Z",
    "value": 0
   },
```

Node version:

```
kubelet --version
Kubernetes v1.3.5
```

@timstclair and I checked his node stats by collecting  `curl -s http://localhost:10255/stats/summary | jq '.node.cpu.usageCoreNanoSeconds'`. usageCoreNanoSeconds is the accumulative cpu usage, and it is only stats used by heapster and HPA. This stat is mapping to heapster's cpu usage, and it is used to calculate cpu/usage_rate together with some timestamps. We noticed that the usageCoreNanoSeconds are sane, but corresponding heapster's cpu/usage_rate is insane as the above. I believe heapster ran into some overflow issue cAdvisor encountered before. Filed this one as a record to make sure the problem is addressed at the proper layer. 

cc/ @mwielgus @fgrzadkowski

**Comment by dchen1107** [comment]
Not sure if we need to patch 1.3 release, but we definitely should address this for 1.4 release.

**Comment by ichekrygin** [comment]
@dchen1107: just to point out - this issue totally breaks HPA, causing to thrash (scaling and killing pods)

**Comment by derekwaynecarr** [comment]
@kubernetes/rh-cluster-infra @DirectXMan12 -- heads up!

**Comment by matchstick** [comment]
@ichekrygin @dchen1107 Just curious,  if this totally breaks HPA how did it not get noticed in the e2e testing for 1.3.0? Can we do something to ensure that if it breaks again or we have other issues like this it can be caught by the HPA testing?

**Comment by ichekrygin** [comment]
@matchstick: I noticed this in `v1.3.4` and was able to repro in `v1.3.5` - I didn't try it on `v1.3.0`

**Comment by dchen1107** [comment]
@ichekrygin Thanks for reporting the issue, and I understand how serious and painful the issue is. We are going to fix the issue as soon as possible, and definitely release a new heapster image with a proper version.

**Comment by matchstick** [comment]
@ichekrygin I apologize if my comment was mistargeted. I I was asking the question to the active HPA team, I don't know if you are a member or a consumer. Mostly I just want to make sure we detect it in the future.

**Comment by ichekrygin** [comment]
@matchstick np at all, and et al thx for looking into this.

**Comment by timstclair** [comment]
> I believe heapster ran into some overflow issue cAdvisor encountered before.

Specifically, I think it's an underflow. There were some examples (I forget where they came from) of the usage showing up as negative, and the odd values (e.g. `18446744073709550587`) are suspiciously close to `MAX_UINT64 - cpu usage`

**Comment by DirectXMan12** [comment]
@timstclair The past issue was caused by cpu/usage, which is supposed to be monotonically increasing, suddenly decreasing drastically.  So your theory makes sense.

**Comment by dchen1107** [comment]
cc/ @kubernetes/autoscaling

**Comment by DirectXMan12** [comment]
I think it would be useful here to see the incoming values that Heapster is seeing from Kubernetes, and also the values of `cpu/usage` (the cumulative value, *not* the rate).  It wouldn't surprise me if that's bouncing around a bit like before.

**Comment by piosz** [comment]
I tried to reproduce the problem. What I did:
```
# install k8s 1.3.6
wget -q -O - https://get.k8s.io | bash

# start proxy
kubectl proxy&

# start consuming container
kubectl run aaa --image=busybox:1.24 --requests=cpu=1000m --limits=cpu=1000m -- /bin/sh -c "while true; do let a=a+1; done"

# print the cpu/usage_rate for the mentioned pod
curl -s http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/namespaces/default/pods/<pod-name>/metrics/cpu/usage_rate | jq '.metrics[(.metrics | length) - 1] | "\(.timestamp)    \(.value)"'
```

I've been running the last command in a loop for >6h and all values are within the range `[982,1015]` which is pretty good accuracy. I'm running version 1.3.6 on GCE. I've also bumped verbosity of Heapster logging to level 6 and I can't see anything suspicious.

Any ideas how can I reproduce?

**Comment by piosz** [comment]
After 17h I still can't see any issue. Could you share more details about your environment?

**Comment by jszczepkowski** [comment]
I run experiments similar to Piotr's. I used kubernetes version from HEAD and generated load by `php-apache` and `hpa-example` images running for nearly one day. Still I couldn't reproduce the problem.

**Comment by ichekrygin** [comment]
I will upgrade to 1.3.6 and try to repro and post the update.

**Comment by piosz** [comment]
The difference between 1.3.5 and 1.3.6 is minor, especially in both cases Heapster is in the same version. I doubt whether the issue was fixed in 1.3.6 in comparison to 1.3.5.

@ichekrygin where do you run your cluster? Which version of Heapster is there? Can you see anything suspicious in Heapster logs? Do you have any specific load in your cluster?

**Comment by ichekrygin** [comment]
@piosz: cluster is on AWS, heapster version: v1.1.0, image: gcr.io/google_containers/heapster:v1.1.0
I can dig into logs in a sec, and no, no specific load on the cluster beyond one manually created to repro this issue.

**Comment by ichekrygin** [comment]
@piosz: since I deleted HPA, there is nothing particularly interesting in the heapster log, perhaps this warning:

**Comment by ichekrygin** [comment]
i can try to repro it again and give you more meaningful data points (logs) if you need it.

**Comment by ichekrygin** [comment]
@piosz: after upgrading to v1.3.6: 
```
curl http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/namespaces/production/pods/rain-2435125386-2094m/metrics/cpu/usage_rate    10:57:44
{
  "metrics": [
   {
    "timestamp": "2016-09-01T17:43:00Z",
    "value": 33
   },
   {
    "timestamp": "2016-09-01T17:44:00Z",
    "value": 18446744073709551591
   },
   {
    "timestamp": "2016-09-01T17:45:00Z",
    "value": 0
   },
   {
    "timestamp": "2016-09-01T17:46:00Z",
    "value": 33
   },
   {
    "timestamp": "2016-09-01T17:47:00Z",
    "value": 18446744073709551579
   },
   {
    "timestamp": "2016-09-01T17:48:00Z",
    "value": 32
   },
   {
    "timestamp": "2016-09-01T17:49:00Z",
    "value": 0
   },
   {
    "timestamp": "2016-09-01T17:50:00Z",
    "value": 18446744073709551591
   },
   {
    "timestamp": "2016-09-01T17:51:00Z",
    "value": 35
   },
   {
    "timestamp": "2016-09-01T17:52:00Z",
    "value": 18446744073709551575
   },
   {
    "timestamp": "2016-09-01T17:53:00Z",
    "value": 18446744073709551608
   },
   {
    "timestamp": "2016-09-01T17:54:00Z",
    "value": 0
   },
   {
    "timestamp": "2016-09-01T17:55:00Z",
    "value": 35
   },
   {
    "timestamp": "2016-09-01T17:56:00Z",
    "value": 18446744073709551581
   },
   {
    "timestamp": "2016-09-01T17:57:00Z",
    "value": 0
   }
  ],
  "latestTimestamp": "2016-09-01T17:57:00Z"
 }⏎                                                        
```

Not entirely sure if related - i see this from HPA

**Comment by ichekrygin** [comment]
after running quick `boom` load test can confirm that HPA is busted (i.e. - not scaling up)

**Comment by ichekrygin** [comment]
Digging into influxdb data, it appears negative values are inserted into inflixdb `k8s.cpu/usage_rate`
```
> select * from "cpu/usage_rate" where pod_name = 'rain-1821827652-yh5yo'
name: cpu/usage_rate
--------------------
time                    container_base_image                            container_name  host_id         hostname                                        labels                                          namespace_idnamespace_name  nodename                                        pod_id                                  pod_name                pod_namespace   type            value
1472774700000000000                                                                     i-fe3b1523      ip-10-72-22-130.us-west-2.compute.internal      pod-template-hash:1821827652,service:rain       932d27fe-f46f-11e5-a28d-060b58a0dba1        production      ip-10-72-22-130.us-west-2.compute.internal      bb5d1e1a-70a0-11e6-8d3d-060a882f6b91    rain-1821827652-yh5yo   production      pod             21
1472774700000000000     hbodp.artifactoryonline.com/rain:0.1.28.ed77b93 rain            i-fe3b1523      ip-10-72-22-130.us-west-2.compute.internal      pod-template-hash:1821827652,service:rain       932d27fe-f46f-11e5-a28d-060b58a0dba1        production      ip-10-72-22-130.us-west-2.compute.internal      bb5d1e1a-70a0-11e6-8d3d-060a882f6b91    rain-1821827652-yh5yo   production      pod_container   21
1472774760000000000                                                                     i-fe3b1523      ip-10-72-22-130.us-west-2.compute.internal      pod-template-hash:1821827652,service:rain       932d27fe-f46f-11e5-a28d-060b58a0dba1        production      ip-10-72-22-130.us-west-2.compute.internal      bb5d1e1a-70a0-11e6-8d3d-060a882f6b91    rain-1821827652-yh5yo   production      pod             -20
1472774760000000000     hbodp.artifactoryonline.com/rain:0.1.28.ed77b93 rain            i-fe3b1523      ip-10-72-22-130.us-west-2.compute.internal      pod-template-hash:1821827652,service:rain       932d27fe-f46f-11e5-a28d-060b58a0dba1        production      ip-10-72-22-130.us-west-2.compute.internal      bb5d1e1a-70a0-11e6-8d3d-060a882f6b91    rain-1821827652-yh5yo   production      pod_container   -20
```

However, it also appears that `k8s.cpu/usage` have different values all together
```

**Comment by ichekrygin** [comment]
Not sure if I am totally off here, but I think the issue could in following

It appears that there are 2 types of cpu usage metrics:
1. `.node.cpu.usageNanoCores` -> `StandardMetrics.MetricCpuUsage` - current cpu usage metric
2. `.node.cpu.usageCoreNanoSecons` -> `RateMetrics.MetricCpuUsageRate` - cumulative cpu usage rate

In `metrics/processors/rate_calculator.go` https://github.com/kubernetes/heapster/blob/master/metrics/processors/rate_calculator.go#L60-L63 - there is a special handling for `core.MetricCpuUsage` which has strong assumption that it operates on cumulative values. However, if somehow, non-cumulative values ended up in `batch.MetricSets` the calculation could easily yield a negative value when new value is smaller than old.
```
newVal := 1000 * (metricValNew.IntValue - metricValOld.IntValue) / (newMs.ScrapeTime.UnixNano() - oldMs.ScrapeTime.UnixNano())
```
This of course should never happen if it operates on cumulative value. But, if somehow, `node.cpu.usageNanoCores` got mixed up with `node.cpu.usageCoreNanoSecons` this would be totally possible.

I hope this helps to narrow it down

**Comment by piosz** [comment]
We ignore `.node.cpu.usageNanoCores` in Heapster. I think the problem might be with timestamps. I'll reach you directly over Slack to debug it.

**Comment by jszczepkowski** [comment]
Bumping priority to P0 as this bug causes P0 bug in HPA (#31928).

**Comment by ichekrygin** [comment]
I think there could be an issue with cadvisor pod cpu usage values. I was running this:

**Comment by piosz** [comment]
After debugging with @ichekrygin it seems that something is broken with summary api, because it tends to report duplicated containers in a single response.

From what @ichekrygin shared with me after querying Kubelet:
```
{
    "podRef": {
     "name": "rain-1821827652-yh5yo",
     "namespace": "production",
     "uid": "bb5d1e1a-70a0-11e6-8d3d-060a882f6b91"
    },
    "startTime": "2016-09-02T00:03:52Z",
    "containers": [
     {
      "name": "rain",
      "startTime": "2016-09-02T00:03:52Z",
      "cpu": {
       "time": "2016-09-02T17:14:42Z",
       "usageNanoCores": 478675,
       "usageCoreNanoSeconds": 35780814376
      },
      "memory": {
       "time": "2016-09-02T17:14:42Z",
       "usageBytes": 0,
       "workingSetBytes": 0,
       "rssBytes": 0,
       "pageFaults": 15,
       "majorPageFaults": 0
      },
      "rootfs": {
       "availableBytes": 484327321600,
       "capacityBytes": 517677649920,
       "usedBytes": 180224
      },
      "logs": {
       "availableBytes": 484327321600,
       "capacityBytes": 517677649920,
       "usedBytes": 5943296
      },
      "userDefinedMetrics": null
     },
     {
      "name": "rain",
      "startTime": "2016-09-02T00:03:52Z",
      "cpu": {
       "time": "2016-09-02T17:14:33Z",
       "usageNanoCores": 0,
       "usageCoreNanoSeconds": 43782
      },
      "memory": {
       "time": "2016-09-02T17:14:33Z",
       "usageBytes": 132460544,
       "workingSetBytes": 132460544,
       "rssBytes": 125931520,
       "pageFaults": 533101,
       "majorPageFaults": 0
      },
      "rootfs": {
       "availableBytes": 484327321600,
       "capacityBytes": 517677649920,
       "usedBytes": 180224
      },
      "logs": {
       "availableBytes": 484327321600,
       "capacityBytes": 517677649920,
       "usedBytes": 5943296
      },
      "userDefinedMetrics": null
     }
    ],
    "network": {
     "time": "2016-09-02T17:14:40Z",
     "rxBytes": 3271684,
     "rxErrors": 0,
     "txBytes": 3200788,
     "txErrors": 0
    },
    "volume": [
     {
      "availableBytes": 84508446720,
      "capacityBytes": 84508459008,
      "usedBytes": 12288,
      "name": "default-token-hwncv"
     }
    ]
   },
```
This seems to be a serious issue. @timstclair @dchen1107  could you please take a look?

**Comment by dchen1107** [comment]
@jszczepkowski @piosz Can you guys share with us the reproduce steps? That would help us debug immediately.

Meanwhile, @timstclair we should add node-e2e test to validate /summary contents, including checking the uniqueness of container.

**Comment by ichekrygin** [comment]
@dchen1107 - this "duplicate" container information appears consistent for pods in `curl -s http://localhost:10255/stats/summary `

**Comment by piosz** [comment]
Me and Jerzy were not able to reproduce it locally. @ichekrygin has a cluster on AWS where the problem occurs.

**Comment by timstclair** [comment]
A dump of the cAdvisor stats on the node would also be helpful:
```
curl -X "POST" -d '{"containerName":"/","subcontainers":true,"num_stats":1}' http://localhost:10255/stats/container
```

One interesting observation is that the first container has almost no memory usage, while the second has almost no CPU usage. Also, the scrape times are different. Is it possible that the memory and CPU cgroups were detected as 2 different containers?

@dchen1107 I'm working on a big overhaul to the summary test in https://github.com/kubernetes/kubernetes/pull/29479, which would catch this.

**Comment by ichekrygin** [comment]
[dump.txt](https://github.com/kubernetes/kubernetes/files/452619/dump.txt)

**Comment by timstclair** [comment]
Based on the cAdvisor stats, it looks like cAdvisor is detecting two different cgroup paths:
```
/init.scope/system.slice/docker-330d448ee4709c6531b2191f7834a16c7c4625736c75aa76b456ae948c194c48.scop
/system.slice/docker-330d448ee4709c6531b2191f7834a16c7c4625736c75aa76b456ae948c194c48.scope
```

Both have the same Docker ID and Kubernetes labels, but the stats are different, and the creation times very slightly different. Also one (init) has a CPU quota, while the other has a cpu mask.

I'm not sure if this is a cAdvisor issue, Kubelet issue, or Docker issue.

**Comment by dchen1107** [comment]
What @timstclair found is very interesting. @ichekrygin could you please give us the following information:

* dump the output of systemd-cgls on the node?
* run command: docker inspect 330d448ee4709c6531b2191f7834a16c7c4625736c75aa76b456ae948c194c48 and find the root pid of that container, then dump the output of 'cat /proc/<pid>/cgroup'? 


Thanks!

**Comment by derekwaynecarr** [comment]
This is a bug in systemd cgroup driver for docker when running in more recent versions of systemd that introduced init.scope.  RHEL/Centos/Fedora<24 are not impacted, but I know CoreOS has a newer systemd.

see the runc fix: https://github.com/opencontainers/runc/pull/966

**Comment by ichekrygin** [comment]
[systemd-cgls.txt](https://github.com/kubernetes/kubernetes/files/452706/systemd-cgls.txt)

**Comment by ichekrygin** [comment]
```
cat /proc/20412/cgroup 
11:devices:/system.slice/docker-330d448ee4709c6531b2191f7834a16c7c4625736c75aa76b456ae948c194c48.scope
10:hugetlb:/system.slice/docker-330d448ee4709c6531b2191f7834a16c7c4625736c75aa76b456ae948c194c48.scope
9:cpuset:/system.slice/docker-330d448ee4709c6531b2191f7834a16c7c4625736c75aa76b456ae948c194c48.scope
8:perf_event:/system.slice/docker-330d448ee4709c6531b2191f7834a16c7c4625736c75aa76b456ae948c194c48.scope
7:blkio:/init.scope/system.slice/docker-330d448ee4709c6531b2191f7834a16c7c4625736c75aa76b456ae948c194c48.scope
6:pids:/init.scope/system.slice/docker-330d448ee4709c6531b2191f7834a16c7c4625736c75aa76b456ae948c194c48.scope
5:memory:/init.scope/system.slice/docker-330d448ee4709c6531b2191f7834a16c7c4625736c75aa76b456ae948c194c48.scope
4:freezer:/system.slice/docker-330d448ee4709c6531b2191f7834a16c7c4625736c75aa76b456ae948c194c48.scope
3:cpu,cpuacct:/system.slice/docker-330d448ee4709c6531b2191f7834a16c7c4625736c75aa76b456ae948c194c48.scope
2:net_cls,net_prio:/system.slice/docker-330d448ee4709c6531b2191f7834a16c7c4625736c75aa76b456ae948c194c48.scope
1:name=systemd:/system.slice/docker-330d448ee4709c6531b2191f7834a16c7c4625736c75aa76b456ae948c194c48.scope
```

**Comment by derekwaynecarr** [comment]
@ichekrygin - yep, thats the problem.  systemd moved pid 1 into init.scope and runc did not yet react.  you either need a systemd prior v226, or a patch to docker with the runc update linked prior.

**Comment by timstclair** [comment]
Thanks @derekwaynecarr , looks like you solved the mystery. That explains why this doesn't show up in any of our tests.

@ichekrygin what distro (+version) are your nodes running?

**Comment by ichekrygin** [comment]
CoreOS-stable-1068

**Comment by dchen1107** [comment]
cc/ @euank from coreos

**Comment by dchen1107** [comment]
@derekwaynecarr & @ichekrygin Thanks for all your help on the debugging. 

@timstclair node-e2e tests are running on coreos image too. Let's  update our summary tests to detect the issue: #31989

@euank I assigned this one to you since so far it only affects coreos image. Please delegate or suggest a plan for the customers on coreos for both 1.3 and 1.4 releases. Thanks!

**Comment by timstclair** [comment]
I don't see this on our coreos node-e2e image. Is that because of this bit in the [coreos-init.json](https://github.com/kubernetes/kubernetes/blob/06c542b4c0e1338634949df6cd4ae2c266aadfd6/test/e2e_node/jenkins/coreos-init.json#L13)?
```
   {
      "name": "docker.service",
      "dropins": [{
        "name": "10-disable-systemd-cgroup-driver.conf",
        "contents": "[Service]\nCPUAccounting=yes\nMemoryAccounting=yes\nEnvironment=\"DOCKER_CGROUPS=\""
      }]
    }]
  },
```

**Comment by ichekrygin** [comment]
After downgrading to `1010.6.0` this is no longer an issue. Thx @derekwaynecarr

**Comment by piosz** [comment]
@dchen1107 could you please update the issue title appropriately and decide about the priority/milestone?

**Comment by dchen1107** [comment]
This is not 1.4 blocker since it only happens on coreos with newer version of systemd. Downgrading coreos image can workaround the issue.  I downgrade the priority and remove the milestone for this.

**Comment by euank** [comment]
Thanks for the ping and sorry for the slightly slow response.

This is a duplicate of https://github.com/google/cadvisor/issues/1344. The root cause was a bug in docker, which all current versions of CoreOS should be avoiding by using the cgroupfs driver. See https://github.com/coreos/bugs/issues/1435#issue-163484274

This affects any nodes that run with a modern systemd (>=226), docker configured to use the systemd cgroup driver, and a docker version before 1.12.

I don't think we have any action items since we've worked around it in CoreOS and updated the node e2e image, fixed the upstream Docker bug, and understand fairly well what's going on.

**Comment by spiddy** [comment]
> After downgrading to `1010.6.0` this is no longer an issue

@ichekrygin  how can you downgrade to specific release number? I only found doc for downgrading channel https://coreos.com/os/docs/latest/manual-rollbacks.html

**Comment by ichekrygin** [comment]
@spiddy: we are running `K8S` on `AWS` so all we had to do was to update to an earlier `AMI`. However, this issue is fixed as of `v1.4.0`, moreover, we are running on `v1.4.4` which also works w/out this problem.

**Comment by danielfm** [comment]
@ichekrygin

> However, this issue is fixed as of v1.4.0, moreover, we are running on v1.4.4 which also works w/out this problem.

That's odd... I just created a test cluster running Kubernetes 1.4.4 in latest CoreOS stable AMI (1122.3.0), and the weird numbers still show up in my graphs:

![image](https://cloud.githubusercontent.com/assets/29534/19705251/38d79b3c-9aea-11e6-88dd-14afbedf3f2a.png)

However, I also tested with latest CoreOS beta AMI (1185.2.0), and it seems to work (the numbers match the ones given by cAdvisor).

In the CoreOS beta version, I noticed a slightly different output for `cat /proc/<pid>/cgroups`:

```
11:perf_event:/docker/8debfa32339ead193274dd62ab39ca7729d499416e86cf02a28363e191f04671
10:memory:/docker/8debfa32339ead193274dd62ab39ca7729d499416e86cf02a28363e191f04671
9:blkio:/docker/8debfa32339ead193274dd62ab39ca7729d499416e86cf02a28363e191f04671
8:hugetlb:/docker/8debfa32339ead193274dd62ab39ca7729d499416e86cf02a28363e191f04671
7:devices:/docker/8debfa32339ead193274dd62ab39ca7729d499416e86cf02a28363e191f04671
6:cpuset:/docker/8debfa32339ead193274dd62ab39ca7729d499416e86cf02a28363e191f04671
5:net_cls,net_prio:/docker/8debfa32339ead193274dd62ab39ca7729d499416e86cf02a28363e191f04671
4:pids:/docker/8debfa32339ead193274dd62ab39ca7729d499416e86cf02a28363e191f04671
3:cpu,cpuacct:/docker/8debfa32339ead193274dd62ab39ca7729d499416e86cf02a28363e191f04671
2:freezer:/docker/8debfa32339ead193274dd62ab39ca7729d499416e86cf02a28363e191f04671
1:name=systemd:/docker/8debfa32339ead193274dd62ab39ca7729d499416e86cf02a28363e191f04671
```

Some context information for each CoreOS image (both running Kubernetes 1.4 created with kube-aws v0.8.3):

- **Stable (1122.3.0)** - systemd v229, docker 1.10.3
- **Beta (1185.2.0)** - systemd v231, docker 1.11.2

**Comment by zihaoyu** [comment]
@danielfm latest stable AMI still does not include the fix. Beta channel is fixed however.

**Comment by euank** [comment]
@dchen1107 mind closing this issue per my [comment above](https://github.com/kubernetes/kubernetes/issues/30939#issuecomment-245774676) since I can't?

**Comment by dchen1107** [comment]
cc/ @justinsb

**Comment by dims** [comment]
closing the issue per @euank 's comment. please reopen if necessary.

**Comment by justinsb** [comment]
Reopening and taking an assignment, so we can make the same changes in our AWS images.

**Comment by dims** [comment]
Ack. thanks @justinsb

**Comment by dims** [comment]
@justinsb is non-release-blocker tag ok? if not please switch it.

**Comment by dims** [comment]
@dchen1107 @justinsb Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by justinsb** [comment]
I believe this is no longer an issue with our 1.5 series AWS images: docker version is >= 1.12, systemctl version < 226, docker not configured with custom option.  Closing.

**Comment by bcorijn** [comment]
For what it's worth, I'm still seeing this behaviour on my cluster running the following configuration:
Kubernetes: 1.5.2 (spawned with kops 1.5.1)
OS: Ubuntu 16.04
Docker: 1.12.3 (and cgroup driver: cgroupfs)
Systemd: 229

Example output:
```
~/R/(master|✚1…) $ curl http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/namespaces/prod/pods/blog-redirector-404703262-21rdx/metrics/cpu/usage_rate
{
  "metrics": [
   {
    "timestamp": "2017-02-14T15:56:00Z",
    "value": 0
   },
   {
    "timestamp": "2017-02-14T15:57:00Z",
    "value": 535
   },
   {
    "timestamp": "2017-02-14T15:58:00Z",
    "value": 18446744073709551182
   },
   {
    "timestamp": "2017-02-14T15:59:00Z",
    "value": 409
   },
   {
    "timestamp": "2017-02-14T16:00:00Z",
    "value": 18446744073709551011
   },
   {
    "timestamp": "2017-02-14T16:01:00Z",
    "value": 442
   }
  ],
  "latestTimestamp": "2017-02-14T16:01:00Z"
 }
```

**Comment by fhaynes** [comment]
I am also still seeing this behavior with 6 clusters setup identically to what @bcorijn has

**Comment by tony612** [comment]
I found a simple way to fix this: set kubelet option `--cgroup-root` to `/docker`.
