### ISSUE TITLE
HPA autoscaling issue. fails to get the cpu utilization from heapster. Unable to marshall heapster response

### ISSUE THREAD

**Issue by spdeshpande** [kubernetes/kubernetes#31708]
Hi All,

My setup: 
K8S v1.3.0
Heapster v1.1.0

HPA complains that it cannot unmarshal heapster's response. 
FailedComputeReplicas   failed to get CPU utilization: failed to get CPU consumption and request: failed to unmarshall heapster response: invalid character 'k' looking for beginning of value

Did a little debugging in the metrics_client.go and found out that the URL that the HPA is hitting could be wrong. It hits this URL which seems off:
https://my_ip/api/v1/proxy/namespaces/kube-system/services/http:heapster:/apis/metrics/v1alpha1/namespaces/my_ns/pods?labelSelector=app=kong

This logs an error in the controller manager "no endpoints available for service \"http:heapster:\""

If I modify the URL to look like the one below, things work. 
https://my_ip/api/v1/proxy/namespaces/kube-system/services/heapster:80/apis/metrics/v1alpha1/namespaces/my_ns/pods?labelSelector=app=kong

What am I missing? Any pointers?

Also is there any way to configure K8S to use a specific heapster namespace and port? I see everything defaulted to kube-system and port ""

Thanks,
Sudeep

**Comment by jim3ma** [comment]
+1
Same issue.

**Comment by unixbhaskar** [comment]
Bumped into the same issue ... :( any clue??

`
bhaskar@Fedora_17:52:26_Wed Aug 31:~>kubectl describe hpa
Name:                           php-apache
Namespace:                      default
Labels:                         <none>
Annotations:                    <none>
CreationTimestamp:              Wed, 31 Aug 2016 17:49:10 +0530
Reference:                      Deployment/php-apache
Target CPU utilization:         50%
Current CPU utilization:        <unset>
Min replicas:                   1
Max replicas:                   10
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  3m            19s             9       {horizontal-pod-autoscaler }                    Warning         FailedGetMetrics        failed to get CPU consumption and request: failed to unmarshall heapster response: invalid character 'k' looking for beginning of value
  3m            19s             9       {horizontal-pod-autoscaler }                    Warning         FailedComputeReplicas   failed to get CPU utilization: failed to get CPU consumption and request: failed to unmarshall heapster response: invalid character 'k' looking for beginning of value

`

**Comment by spdeshpande** [comment]
k8s guys, any updates on this one?

**Comment by nicolasbelanger** [comment]
+1

Same here.  Running the laster k8s version available today, 1.3.7...

```
[root@centos7-server influxdb]# kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:15:30Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:08:43Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
You have new mail in /var/spool/mail/root
[root@centos7-server influxdb]# kubectl describe hpa
Name:				php-apache
Namespace:			default
Labels:				<none>
Annotations:			<none>
CreationTimestamp:		Mon, 19 Sep 2016 14:29:22 -0500
Reference:			Deployment/php-apache
Target CPU utilization:		50%
Current CPU utilization:	<unset>
Min replicas:			1
Max replicas:			10
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  34m		28m		13	{horizontal-pod-autoscaler }			Warning		FailedGetMetrics	failed to get CPU consumption and request: failed to unmarshall heapster response: json: cannot unmarshal object into Go value of type []v1alpha1.PodMetrics
  34m		28m		13	{horizontal-pod-autoscaler }			Warning		FailedComputeReplicas	failed to get CPU utilization: failed to get CPU consumption and request: failed to unmarshall heapster response: json: cannot unmarshal object into Go value of type []v1alpha1.PodMetrics
  36m		21s		62	{horizontal-pod-autoscaler }			Warning		FailedGetMetrics	failed to get CPU consumption and request: failed to unmarshall heapster response: invalid character 'k' looking for beginning of value
  36m		21s		62	{horizontal-pod-autoscaler }			Warning		FailedComputeReplicas	failed to get CPU utilization: failed to get CPU consumption and request: failed to unmarshall heapster response: invalid character 'k' looking for beginning of value
```

**Comment by nicolasbelanger** [comment]
Resolved on my side.  I was using heapster:canary, which most probably (to be verified) uses heapster 1.2.  Then it looks like kube 1.3 requires heapster 1.1 (heapster 1.2 is for kube 1.4).

Resolved by spinning this:

`kubectl create -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/monitoring-standalone/v1.1.0.yaml`

Ref.: https://github.com/kubernetes/kops/blob/master/docs/addons.md

See also:  https://github.com/kubernetes/heapster/issues/1222

**Comment by spdeshpande** [comment]
@nicolasbelanger 
Perfect! That works. Thanks a lot!

**Comment by electromecca** [comment]
I am getting similar issue, but mentioned fix doesn't resolve it for me
Here's describe for one of the hpa's:

```NAME                   REFERENCE                         TARGET    CURRENT   MINPODS   MAXPODS   AGE
circadian-scaler       Deployment/circadian              20%       0%        1         10        3d
facts-scaler           Deployment/facts                  20%       0%        2         10        3d
fallacious-sas-mysql   Deployment/fallacious-sas-mysql   20%       1%        1         6         4d
greetings-scaler       Deployment/greetings              20%       0%        1         10        4d
translation-scaler     Deployment/translation            20%       0%        2         10        3d
users-scaler           Deployment/users                  20%       0%        2         10        3d
Barts-MBP:kubernetes bwalczak$ kubectl describe hpa users-scaler
Name:				users-scaler
Namespace:			default
Labels:				<none>
Annotations:			<none>
CreationTimestamp:		Thu, 24 Nov 2016 13:41:33 +0000
Reference:			Deployment/users
Target CPU utilization:		20%
Current CPU utilization:	0%
Min replicas:			2
Max replicas:			10
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  3d		5s		11322	{horizontal-pod-autoscaler }			Warning		FailedGetMetrics	failed to get CPU consumption and request: some pods do not have request for cpu
  3d		5s		11322	{horizontal-pod-autoscaler }			Warning		FailedComputeReplicas	failed to get CPU utilization: failed to get CPU consumption and request: some pods do not have request for cpu```

kubectl version:
```Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4+3b417cc", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"not a git tree", BuildDate:"2016-10-21T22:34:07Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}```

I've used config files from here ->> https://raw.githubusercontent.com/kubernetes/kops/master/addons/monitoring-standalone/v1.2.0.yaml

**Comment by Leejingforever** [comment]
How can I change  heapster to the version 1.1 ?  Thanks a lot! @nicolasbelanger @spdeshpande
