### ISSUE TITLE
Adding an already deleted node port to service shows already acquired error

### ISSUE THREAD

**Issue by DImuthuUpe** [kubernetes/kubernetes#32987]
**Kubernetes version** (use `kubectl version`): v1.2.6

**Environment**: 
- **Cloud provider or hardware configuration**: Virtual Machine with 4GB physical memory and 2 cpu cores
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04
- **Kernel** (e.g. `uname -a`): Linux ubuntu-m1 3.13.0-95-generic #142-Ubuntu SMP Fri Aug 12 17:00:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Manual (self created ansible scripts)

**What happened**: I created a service as below

```
{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "ultraesbsv-o7dytoto2w",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/services/ultraesbsv-o7dytoto2w",
        "uid": "804fb74a-7cee-11e6-ae64-080027daf78e",
        "resourceVersion": "30063",
        "creationTimestamp": "2016-09-17T15:50:47Z",
        "labels": {
            "app": "ultraesb",
            "cluster": "TestCluster"
        }
    },
    "spec": {
        "ports": [
            {
                "name": "8281",
                "protocol": "TCP",
                "port": 8281,
                "targetPort": 8281,
                "nodePort": 30001
            },
            {
                "name": "8285",
                "protocol": "TCP",
                "port": 8285,
                "targetPort": 8285,
                "nodePort": 30005
            }
        ],
        "selector": {
            "app": "ultraesb",
            "cluster": "TestCluster"
        },
        "clusterIP": "192.168.3.206",
        "type": "NodePort",
        "sessionAffinity": "None"
    },
    "status": {
        "loadBalancer": {}
    }
}
```

Then using the REST API I removed a port entry 

```
http://192.168.1.119:8080/api/v1/namespaces/default/services/ultraesbsv-o7dytoto2w
Content-Type: application/json-patch+json

[
   {
      "op":"remove",
      "path":"/spec/ports/1"
   }
]
```

After executing above HTTP request updated service is as below

```
{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "ultraesbsv-o7dytoto2w",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/services/ultraesbsv-o7dytoto2w",
        "uid": "804fb74a-7cee-11e6-ae64-080027daf78e",
        "resourceVersion": "30396",
        "creationTimestamp": "2016-09-17T15:50:47Z",
        "labels": {
            "app": "ultraesb",
            "cluster": "TestCluster"
        }
    },
    "spec": {
        "ports": [
            {
                "name": "8281",
                "protocol": "TCP",
                "port": 8281,
                "targetPort": 8281,
                "nodePort": 30001
            }
        ],
        "selector": {
            "app": "ultraesb",
            "cluster": "TestCluster"
        },
        "clusterIP": "192.168.3.206",
        "type": "NodePort",
        "sessionAffinity": "None"
    },
    "status": {
        "loadBalancer": {}
    }
}
```

As expected port entry 8285 has been removed. I checked in iptables rules for node port 30005 using command 'sudo iptables-save | grep 30005' and I could see that it was successfully removed from iptables. 
Within few seconds I tried to add it back to the service.

```
http://192.168.1.119:8080/api/v1/namespaces/default/services/ultraesbsv-o7dytoto2w
Content-Type: application/json-patch+json

[
   {
      "op":"add",
      "path":"/spec/ports/1",
      "value":{
         "name":"8285",
         "nodePort":30005,
         "port":8285,
         "protocol":"TCP"
      }
   }
]
```

Then is gave following message 

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Service \"ultraesbsv-o7dytoto2w\" is invalid: spec.ports[1].nodePort: Invalid value: 30005: provided port is already allocated",
  "reason": "Invalid",
  "details": {
    "name": "ultraesbsv-o7dytoto2w",
    "kind": "Service",
    "causes": [
      {
        "reason": "FieldValueInvalid",
        "message": "Invalid value: 30005: provided port is already allocated",
        "field": "spec.ports[1].nodePort"
      }
    ]
  },
  "code": 422
}
```

After few minutes, I tried the same HTTP request then it was successfully executed. It seems like Kubernetes api / proxy is some how caching node port 30005 is acquired for some grace period although it is not. Is this an expected behaviour?

**What you expected to happen**: At the very first HTTP request I send to add port 8285 back into the service, it should be successful. 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by DImuthuUpe** [comment]
Any update on this issue?

**Comment by jkurz** [comment]
This problem is still occurring on `v1.3.10`

Has there been any triage of this issue?

**Comment by bluecamel** [comment]
I just ran into this issue on 1.5.2.

**Comment by thockin** [comment]
This should be fixed in 1.6.

**Comment by akshaymankar** [comment]
I was trying this with 1.7, it is still an issue.

**Comment by everett-toews** [comment]
Confirmed still an issue in 1.7.x. This should be re-opened please.

**Comment by crandles** [comment]
I just hit this error in 1.7.x as well, was able to resolve by restarting the apiserver

**Comment by TristanPeers** [comment]
Please re-open, still an issue in 1.7.2

**Comment by dstockton** [comment]
Still an issue in 1.7.2

**Comment by thockin** [comment]
I can not repro this:

```
thockin@freakshow2:~/src/kubernetes$ date
Tue Nov 14 20:58:53 PST 2017

thockin@freakshow2:~/src/kubernetes$ k get svc hostnames -o go-template="{{.spec.ports}}"; echo
[map[protocol:TCP targetPort:9376 name:a nodePort:32728 port:80] map[nodePort:32001 port:81 protocol:TCP targetPort:9377 name:b]]

thockin@freakshow2:~/src/kubernetes$ k edit svc hostnames # delete b
service "hostnames" edited

thockin@freakshow2:~/src/kubernetes$ k get svc hostnames -o go-template="{{.spec.ports}}"; echo
[map[nodePort:32728 port:80 protocol:TCP targetPort:9376 name:a]]

thockin@freakshow2:~/src/kubernetes$ k edit svc hostnames # add b again
service "hostnames" edited

thockin@freakshow2:~/src/kubernetes$ k get svc hostnames -o go-template="{{.spec.ports}}"; echo
[map[protocol:TCP targetPort:9376 name:a nodePort:32728 port:80] map[name:b nodePort:32001 port:81 protocol:TCP targetPort:9377]]

thockin@freakshow2:~/src/kubernetes$ date
Tue Nov 14 20:59:41 PST 2017
```


What am I doing wrong?  Is your setup HA?

**Comment by TristanPeers** [comment]
@thockin - yes, we are running HA - 3 x masters

**Comment by TristanPeers** [comment]
Have done some more testing, it seems it does finally allow you to re-use the port but it takes up to ~5 minutes:

```
[root@k8s-test ~]# kubectl create -f nginx-pod.yaml
pod "nginx-pod" created
[root@k8s-test ~]# kubectl create -f nginx-nodeport-service.yaml
service "nginx" created
[root@k8s-test ~]# kubectl get svc
NAME         CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
kubernetes   100.64.0.1      <none>        443/TCP                      1d
nginx        100.65.77.214   <nodes>       80:30084/TCP,443:30443/TCP   9s
[root@k8s-test ~]# kubectl delete -f nginx-nodeport-service.yaml
service "nginx" deleted
[root@k8s-test ~]# kubectl get svc
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   100.64.0.1   <none>        443/TCP   1d
[root@k8s-test ~]# kubectl create -f nginx-nodeport-service.yaml
The Service "nginx" is invalid: spec.ports[0].nodePort: Invalid value: 30084: provided port is already allocated
```

**Comment by dry4ng** [comment]
Still having this issue in 1.8.2

**Comment by lostick** [comment]
Can confirm, if you wait some time if you be applied.

**Comment by qiupeng-huacloud** [comment]
I have this issue in v1.9.1. My ENV is 3 master with HA mode. i delete nodeport in master1, and then create nodeport in master2. This issue will happen. Anyone knows the root cause ?

**Comment by abashmakou-ib** [comment]
reproducible in v1.7.4

**Comment by srnfr** [comment]
Still an issue in v1.8.7. Please re-open. Thxs.

**Comment by raviteja22** [comment]
I still see the issue on v1.9.4. 
I am running HA master nodes (3 of them) on my cluster and using nodePort for creating services. 
It takes ~1-3  minutes of time for the ports to be in the reusable state, even though netstat command doesn't show them in LISTEN state during this period of time.

**Comment by jolson490** [comment]
Can this issue please be re-opened? And until this issue is fixed, is there a command I can do to check whether a given port has truly been deleted?

----

More info:

On K8s v1.8.4 I'm using [kube-prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus), which has:
 * a [deploy](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/hack/cluster-monitoring/deploy) script that creates 3 services (prometheus & alertmanager & grafana - each one allocates/uses a NodePort)
 * a [teardown](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/hack/cluster-monitoring/teardown) script, which deletes everything that was created by deploy.

On a cluster that i've run deploy, then if I run teardown and immediately after teardown I run deploy, the deploy sometimes gets an error such as: `The Service "alertmanager-main" is invalid: spec.ports[0].nodePort: Invalid value: 30903: provided port is already allocated`

When I want to re-deploy kube-prometheus, then after running teardown & before running deploy I do the stuff below. But there are times when that `kubectl get svc` command says none of the NodePorts are still in use, but then when I run deploy I still get `provided port is already allocated`, hence my question about a command that shows whether a given NodePort is truly/fully deleted.

Until this issue is resolved, I could simply sleep (after teardown & before deploy) for a plenty long enough amount of time (e.g. 5 minutes), but I'd prefer to only have to wait for precisely however long is necessary.

```
  # If deploy is run immediately after teardown, an error such as the following can occur:
  #   'The Service "prometheus-k8s" is invalid: spec.ports[0].nodePort: Invalid value: 30900: provided port is already allocated'
  # As an extension of the teardown script, wait until all the k-p NodePorts have been freed up
  while true
  do
    # The following command captures any/all k-p NodePorts that are still in use
    kpNodePorts=$(kubectl get svc -n monitoring -o go-template='{{range .items}}{{range.spec.ports}}{{if .nodePort}}{{.nodePort}}{{"\n"}}{{end}}{{end}}{{end}}' | egrep "^3090[023]$")
    if [ -z "$kpNodePorts" ] || [ "$kpNodePorts" == "[]" ]; then
      break
    else
      echo "waiting for k-p NodePorts to be freed up"
      sleep 1
    fi
  done
```

**Comment by brix4dayz** [comment]
Still an issue on OpenShift v3.9.33 running K8s v1.9.1, please reopen. Time can vary between a few seconds up to 2 minutes.

**Comment by dakleine** [comment]
We have this issue on 1.9.8 too!

**Comment by joelbraun** [comment]
This issue occurs on 1.10.6 as well.

**Comment by Vadim-Zenin** [comment]
This issue occurs on AWS EKS 1.10.3 as well.

**Comment by attfarhan** [comment]
I am still seeing this on GKE with Kubernetes v1.917

**Comment by leighyu1983** [comment]
Still occur on Kubernetes v1.11.3 cluster

**Comment by aparamon** [comment]
Reproducible for me on EKS, although wait times are typically < 1 min (seconds), with `kubectl` and programmatically with Kubernetes Client's [delete_namespaced_service](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#delete_namespaced_service) and watching for the `'DELETED'` status.

**Comment by safrmich** [comment]
Since, noone is re-opening this issue, I re-raised it here: https://github.com/kubernetes/kubernetes/issues/73140

**Comment by lakshaykapoor7198** [comment]
Same thing happened with v1.25.11

**Comment by aojea** [comment]
> #73140
