### ISSUE TITLE
Use finalizer to delete-inhibit PVs while bound to a PVC

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#33355]
https://github.com/kubernetes/kubernetes/issues/29033#issuecomment-241055560

If the storage controller put a finalizer on the PV, then we could be relatively assured that nobody will delete the PV while a PVC is bound to it.

@kubernetes/sig-storage

**Comment by jsafrane** [comment]
If I understand it correctly, finalizers are used for cascade deletion of dependent objects, e.g. deletion of a namespace triggers deletion of all pods/services/... inside. Only after that completes the namespace will be deleted. See https://github.com/kubernetes/kubernetes/blob/master/docs/design/namespaces.md#example-openshift-origin-managing-a-kubernetes-namespace

@thockin, do you propose that deletion of a PV triggers deletion of a PVC that's bound to it, i.e. the cascade delete? That sounds odd.

On related note, deletion of a PVC should not be allowed when it's used by (running?) pods.

**Comment by rootfs** [comment]
My reading of is somewhat different. I see `delete-inhibit` an ordering enforcement: dependent resources should wait till their creators exit first. 

Btw, the meaning of `finalizer` is really not straightforward.

**Comment by jsafrane** [comment]
When user deletes a namespace, Kubernetes moves forward and actively does everything that is necessary to delete the namespace by killing pods and clams and services. IMO we want different behavior on PVs.

In addition, what grace period should user set when deleting a PV with finalizers? He has no idea how/when corresponding PVC will be deleted (by another user).

**Comment by thockin** [comment]
finalizer on a PV will prevent the apiserver from deleting the PV until the
finalizer is removed.  This is what we want - the PVC holds a "lien" (would
have been a better name, IMO) on the PV.  The PV is going to be deleted,
once the lien is removed.  You could even argue that PV with cleanup policy
"Delete" should be deleted as soon as the claim is bound and let GC handle
the rest.  when the user deletes the PV, the controller will remove the
finalizer and it will be removed.

```
thockin@freakshow2:~/src/kubernetes$ k get secret foo
Error from server: secrets "foo" not found

thockin@freakshow2:~/src/kubernetes$ k create secret generic foo
secret "foo" created

thockin@freakshow2:~/src/kubernetes$ k edit secret foo # put a finalizer in
metadata
secret "foo" edited

thockin@freakshow2:~/src/kubernetes$ k get secret foo -o yaml | grep -A1
finalizers
  finalizers:
  - example.com/do-not-delete

thockin@freakshow2:~/src/kubernetes$ k delete secret foo
secret "foo" deleted

thockin@freakshow2:~/src/kubernetes$ k get secret foo -o yaml | grep -A1
finalizers
  finalizers:
  - example.com/do-not-delete

thockin@freakshow2:~/src/kubernetes$ k edit secret foo # remove finalizer
secret "foo" edited

thockin@freakshow2:~/src/kubernetes$ k get secret foo -o yaml | grep -A1
finalizers
Error from server: secrets "foo" not found
```

**Comment by thockin** [comment]
It would be nice to also delete-inhibit a PVC when a Pod is using it, but
that's something we don't currently have any logic for.  We do already have
logic between PV and PVC.

wrt grace period, infinite.  As long as the PVC is alive, the PV can't go
away.  If you want to nix a PV you have to either release the claim or
manually clear the finalizer (which indicates an exceptional condition).

We're effectively building a poor-man's referential integrity.  Between
this and Owner references...  @lavalamp..

**Comment by lavalamp** [comment]
A finalizer holds an object in the Terminating phase. Is that really what you want? I mean, it will work, and it's maybe better than nothing. But I think you may actually want a different mechanism, that prevents deletion at all & sends back forbidden status codes. (It doesn't exist.)

Do you really want to block deletion that hard, though? I guess a cluster admin can still take off the lock/finalizer and get it deleted no matter what if they really need to for some reason.

**Comment by thockin** [comment]
"Phase" is a largely undefined thing, and doesn't REALLY exist across
objects.  There is no universal state machine that we have ever
documented.  Yeah, it's not an ideal state, but it's better than where we
are, and I expect that a proposal for delete-inhibition would a) look a lot
like finalizers with a different field name and b) meet with disfavor.

But that's why I looped you in.  You have been an opponent of RI in the
API, but we *are* adding it, just through a dozen different smaller
mechanisms.

**Comment by lavalamp** [comment]
Brian thinks we shouldn't do much more in the way of RI. I don't have a
strong opinion at the moment.

It's true, we're light on documentation. I opened #33390.

**Comment by thockin** [comment]
I think the RI issue overall needs to be revisited.  Lack of it causes a
lot of edge-cases that are at best surprising, and are sometimes really
nefarious.

**Comment by krmayankk** [comment]
@jsafrane @thockin what is the thought process on this. Here are the things i want to understand. Let me know if this already documented somewhere  or if it doesnt work as expected:
- Can a PVC be deleted while its being referenced in a Pod
- Can a PV be deleted while its binded to a PVC ?
- When a Pod is done referencing a PVC and is gone, is there a way to garbage collect PVC's ?
- Is reclaim policy the only way to GC the PV ?

**Comment by thockin** [comment]
On Thu, Mar 30, 2017 at 11:32 PM, krmayankk <notifications@github.com> wrote:
>
> @jsafrane @thockin what is the thought process on this. Here are the things i want to understand. Let me know if this already documented somewhere or if it doesnt work as expected:
>
> Can a PVC be deleted while its being referenced in a Pod

Yes, but it might cause problems if your pod's controller needs that
info (e.g. moving the pod).  we probably should not allow.

> Can a PV be deleted while its binded to a PVC ?

Yes, but we should probably not allow

> When a Pod is done referencing a PVC and is gone, is there a way to garbage collect PVC's ?

No.  PVCs are explicit lifetime bindings.  No auto-removal.

> Is reclaim policy the only way to GC the PV ?

If by GC you mean explicitly clean up when released, yes.

**Comment by ianchakeres** [comment]
Related issue about preventing deletion of PVC's that are actively referenced #45143

**Comment by dixudx** [comment]
@thockin shall we close this since it has been fixed in #55824.

**Comment by pospispa** [comment]
> @thockin shall we close this since it has been fixed in #55824.

https://github.com/kubernetes/kubernetes/pull/55824 doesn't fix this bug. https://github.com/kubernetes/kubernetes/pull/55824 protects only PVCs that are in active use by a pod.

However, this issue is about a deletion of a PV that is bound to a PVC. https://github.com/kubernetes/kubernetes/pull/55824 doesn't protect PVs.

[PV protection](https://github.com/kubernetes/features/issues/499) feature didn't make it into K8s 1.9. To be honest, I've not started working on PV protection and currently I don't know if it would be assigned to me as a priority for the K8s 1.10.
