### ISSUE TITLE
kubeadm: pre-flight checks return false positives

### ISSUE THREAD

**Issue by pires** [kubernetes/kubernetes#34893]
Here's one example:
```
$ netstat -nlt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN

$ kubeadm init
Running pre-flight checks
preflight check errors:
	user is not running as root
	Port 443 is in use
	ebtables not found in system path
	socat not found in system path

$ sudo kubeadm init
Running pre-flight checks
preflight check errors:
	ebtables not found in system path
	socat not found in system path
```

The important part here is that port 443 is not being used but, when the user has no superuser privileges, `kubeadm` can't test bind that port and assumes it's already bound. In this particular case, regular users can't bind port numbers <1024 (it's possible but not by default).

I am not sure if we have other pre-flight checks that suffer from this.

This is low-hanging fruit but fixing it will provide better UX. 

/cc @luxas @dmmcquay @dgoodwin

**Comment by luxas** [comment]
Very soon we will get rid of the 443 :)

I came across it as well, but I think the only "flake" is 443, so soon this is fixed

**Comment by pires** [comment]
Well, for ports, instead of binding (listen) we could just dial as any other client. This would fix it permanently!

**Comment by dgoodwin** [comment]
I actually had it connecting originally and then read that this suffers from failing to handle ports that are in use but still not accepting connections. Attempting to bind appeared to be the most reliable way to determine.

**Comment by pires** [comment]
@dgoodwin it is such case when a TCP listener is established but no acceptor is in place, good point.

**Comment by luxas** [comment]
This is now fixed when we're binding to ports higher than 1000

**Comment by pires** [comment]
We should have code commits referring to issues.

**Comment by luxas** [comment]
We often have, but sometimes issues are forgotten.
I'm doing my best to keep the issue/PR stack clean
