### ISSUE TITLE
Controller manager cannot determine if scheduledjob needs to be started

### ISSUE THREAD

**Issue by peay** [kubernetes/kubernetes#36311]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
`scheduledjob`, `cannot determine`, `too many missed start times`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
````
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+coreos.0", GitCommit:"278a1f7034bdba61cba443722647da1a8204a6fc", GitTreeState:"clean", BuildDate:"2016-09-26T20:48:37Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+coreos.0", GitCommit:"278a1f7034bdba61cba443722647da1a8204a6fc", GitTreeState:"clean", BuildDate:"2016-09-26T20:48:37Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
````

**Environment**:
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): `Debian GNU/Linux 8 (jessie)`
- **Kernel** (e.g. `uname -a`): `4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 GNU/Linux`
- **Install tools**: `quay.io/coreos/hyperkube:v1.4.0_coreos.0`, deployed with `kargo`
- **Others**:

**What happened**:

I am using a scheduledjob with **`concurrencyPolicy: Forbid`**. An instance of my job has taken a long time to finish, thus skipping many start times.

Ever since, the scheduledjob will not schedule anything new.

Controller manager log has:

````
E1106 13:37:12.457445       1 controller.go:163] Cannot determine if default/my-cron-job needs to be started: Too many missed start times to list
````

**What you expected to happen**:

I expect the scheduledjob not to be stuck not scheduling anything anymore. With `concurrencyPolicy: Forbid`, I expect that it should just re-schedule something as soon as the previously running job has completed.

The "Too many missed start times to list" safeguard appears to apply mostly to cases where job concurrency is allowed to avoid creating a lot of jobs in case of timestamp issues.
https://github.com/kubernetes/kubernetes/blob/56bbfd259a6f45dfbcfb6f3c9f61643a787ed067/pkg/controller/scheduledjob/utils.go#L148:

````
		// An object might miss several starts.  For example, if
		// controller gets wedged on friday at 5:01pm when everyone has
		// gone home, and someone comes in on tuesday AM and discovers
		// the problem and restarts the controller, then all the hourly
		// jobs, more than 80 of them for one hourly scheduledJob, should
		// all start running with no further intervention (if the scheduledJob
		// allows concurrency and late starts).
		//

		// However, if there is a bug somewhere, or incorrect clock
		// on controller's server or apiservers (for setting creationTimestamp)
		// then there could be so many missed start times (it could be off
		// by decades or more), that it would eat up all the CPU and memory
		// of this controller. In that case, we want to not try to list
		// all the misseded start times.
````

**How to reproduce it** (as minimally and precisely as possible):

The issue shows up after about 100 minutes of this running.

```
apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  name: my-cron-job
  labels:
    app: my-cron-job
spec:
  schedule: 0/1 * * * ?
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-cron-job
            image: busybox:1.25
            command: ["sleep", "7000"]
          restartPolicy: Never
```

**Anything else do we need to know**:

**Comment by bgrant0607** [comment]
cc @soltysh @janetkuo

**Comment by soltysh** [comment]
@peay sorry for the long delay in response, there were a few issues solved in later versions of ScheduledJob, can you verify this against latest 1.4.x? I've tried cherry-picking all of the crucial ones, like: https://github.com/kubernetes/kubernetes/pull/30451 and https://github.com/kubernetes/kubernetes/pull/35420 I'll try to verify this on my own as well.

**Comment by peay** [comment]
I am still getting the same issue with `Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6+coreos.0", GitCommit:"ec2b52fabadf824a42b66b6729fe4cff2c62af8c", GitTreeState:"clean", BuildDate:"2016-11-14T19:42:00Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by soltysh** [comment]
@peay thanks for the info, will dig deeper into this one.

**Comment by peay** [comment]
Thanks a lot @soltysh, any chance a potential fix could make it in 1.5?

**Comment by soltysh** [comment]
@peay if possible - yes, I'll try to backport it to 1.5

**Comment by peay** [comment]
@soltysh did you look into this? If not, let me know if you want me to pick it up and work on a PR

**Comment by soltysh** [comment]
@peay yeah, go ahead and ping me in the PR.

**Comment by peay** [comment]
@soltysh I just thought of something which might make sense.

We've modified the error message to make it more "actionable", and the user can set a deadline to avoid running into this. However, the error message is still only controller level AFAIK and thus not exposed to the user. From the user's perspective, there is not way to tell why the CronJob is not scheduling the next instance.

For these reasons, maybe we should also emit an event in the corresponding CronJob? I can send a small PR for this modification.
