### ISSUE TITLE
Namespace stuck on terminating on delete

### ISSUE THREAD

**Issue by soudy** [kubernetes/kubernetes#37554]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): namespace terminating 1.4.6

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:45:16Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): 4.4.0-47-generic
- **Install tools**: N.A
- **Others**: N.A

**What happened**:
After upgrading our cluster from 1.4.0 to 1.4.6, when deleting a namespace it gets stuck in Terminating.

**What you expected to happen**:
Have the namespace deleted.

**How to reproduce it** (as minimally and precisely as possible):
Upgrade from 1.4.0 to 1.4.6 and delete a namespace. 

**Anything else do we need to know**:
I found https://github.com/kubernetes/kubernetes/issues/19317 and https://github.com/kubernetes/kubernetes/issues/37278, but one is specific to thirdpartyresources and the other one to openshift. This issue happens on all namespaces with no special finalizer or thirdpartyresource.

**Comment by derekwaynecarr** [comment]
Also see: https://github.com/kubernetes/kubernetes/issues/36069

**Comment by derekwaynecarr** [comment]
@soudy 

I think I have isolated a case where this can happen.

Are you able to attach the YAML for one of the pods that is stuck terminating?

I would like to confirm that the gracePeriodSeconds value is 0, and the deletionTimestamp is not nil.

Thanks!

**Comment by derekwaynecarr** [comment]
@sjenning @smarterclayton @caesarxuchao @ingvagabund -- we have found a problem where pods that have gracePeriodSeconds value is 0, and has a deletionTimestamp not nil, that users are unable to force-delete those pods.  This appears to be caused on a rare race during a deletion, but once the system is in this state, the pod is not deletable.  We are debugging now, and hope to have a fix shortly.

**Comment by derekwaynecarr** [comment]
@saad-ali -- see above ^ , I am able to reproduce this issue on 1.4.x stream, and will check tomorrow if it can be reproduced in 1.5, if so, will think we need a patch for both releases.

**Comment by caesarxuchao** [comment]
Thanks @derekwaynecarr. Looking forward to seeing the root cause.

**Comment by saad-ali** [comment]
Ack thanks @derekwaynecarr. Since the issue existed in 1.4, I'm going to mark it as non-release-blocker for 1.5

**Comment by derekwaynecarr** [comment]
@saad-ali -- its a non-recoverable error.  I think the PR for 1.5 is must have.  The users must go to etcd to actually remove the pod when this happens.

**Comment by saad-ali** [comment]
> @saad-ali -- its a non-recoverable error. I think the PR for 1.5 is must have. The users must go to etcd to actually remove the pod when this happens.

Ack. Marking as release-blocking then. Will keep an eye on it. Please keep this issue updated.

**Comment by saad-ali** [comment]
>> @saad-ali -- its a non-recoverable error. I think the PR for 1.5 is must have. The users must go to etcd to actually remove the pod when this happens.
> 
> Ack. Marking as release-blocking then. Will keep an eye on it. Please keep this issue updated.

@derekwaynecarr any updates on this issue? We're rapidly approaching release day (Thursday).

**Comment by saad-ali** [comment]
> @derekwaynecarr any updates on this issue? We're rapidly approaching release day (Thursday).

We'd have to get any fixes in ASAP and cherry picked to the 1.5 branch so that there is enough time for the fix to bake before release.

**Comment by derekwaynecarr** [comment]
This is fixed via https://github.com/kubernetes/kubernetes/pull/37721

**Comment by hectorj2f** [comment]
As commented in https://github.com/kubernetes/kubernetes/issues/37278#issuecomment-268998857, I still experience this issue when using `v1.5.1` :/

**Comment by sysradium** [comment]
Still reproducible on 1.5.2. This issues looks like kind of critical :(

**Comment by saad-ali** [comment]
Re-opening. Looks like folks are still hitting this.

From slack:
```
askorodumov [6:49 AM] 
@saad-ali should the 1.5.2 resolve the problem with namespaces not being deleted if there is a thirdpartyresource?
https://github.com/kubernetes/kubernetes/issues/37554
GitHub
Namespace stuck on terminating on delete · Issue #37554 · kubernetes/kubernetes · GitHub

[6:50]  
The problem seems kind of critical but still is reproducible on the last commit tagged with release-1.5 :disappointed:  If there is something we could help
```

**Comment by sysradium** [comment]
From what I can tell this may be connected with the issue https://github.com/projectcalico/libcalico-go/issues/297

Basically deleting TPR solves the problem, but breaks calico.

**Comment by hectorj2f** [comment]
I am using `v1.5.2` and the problem seems to be fixed. I am able to delete namespaces.

**Comment by sysradium** [comment]
@hectorj2f did you have any TPR?

**Comment by smarterclayton** [comment]
We're seeing stuck namespaces without TPR, so it's possible it's another
race condition altogether.

**Comment by nikinath** [comment]
This issue seems to be fixed in 1.5.2. Even with TPRs.

Logs:

```
$ kubectl create namespace mynamespace
namespace "mynamespace" created

$ cat resource.yaml
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: cron-tab.stable.example.com
description: "A specification of a Pod to run on a cron style schedule"
versions:
- name: v1

$ kubectl create -f resource.yaml
thirdpartyresource "cron-tab.stable.example.com" created

$ kubectl delete namespace mynamespace
namespace "mynamespace" deleted

$ kubectl get namespace
NAME          STATUS    AGE
default       Active    10h
kube-public   Active    10h
kube-system   Active    10h
```

It is fixed by https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/extensions/thirdpartyresourcedata/codec.go#L367. (PR https://github.com/kubernetes/kubernetes/pull/37328)

When a namespace is deleted, the namespace controller deletes all the deletable resources under that namespace. In case it is a TPR resource, the delete options failed to be decoded by a TPR GVK.

Before, the GVK sent to the delegated codec was a thirdparty one which was not recognized by the delegated codec. So we needed to check the defaulting GVK and send it onwards if it doesn't point to our thirdparty group.

Now, if it points to the TPR group, the GVK is set to nil and then sent to the codec, which it recognizes and hence everything works fine!

**Comment by enisoc** [comment]
This is now re-fixed for TPR via #46736 and a regression test was added as part of fixing #47072. I'm going to close this since it appears to have been reopened mainly for the TPR case.

**Comment by krmayankk** [comment]
what are the things to verify here. I am seeing a similar case in 1.5.3 where the namespace is stuck in terminating state and the pods inside that namespace are in Unknown state or init :0/1 state.

**Comment by enisoc** [comment]
@krmayankk If the namespace is stuck in terminating, usually there should be log entries from the namespace controller in kube-controller-manager.log that indicate why.

**Comment by shean-guangchang** [comment]
I am using v1.8.4 and I am having the same problem that deleted namespace stays at "Terminating" forever.  I did "kubectl delete namespace XXXX" already.

**Comment by Aracki** [comment]
In my case, there are ***ALWAYS*** some objects which were recreated after you have "deleted" your namespace.

With `kubectl api-resources` you can see `KIND` & `APIGROUP` of all available objects.

What I am doing is to go through it and find all k8s objects which were in some use of that specific namespace, and **_delete them manually_**.


  [1]: https://stackoverflow.com/a/52957212/2884309

**Comment by pikvik** [comment]
In my case the finaliser I removed yet its stuck with same termination status .
