### ISSUE TITLE
Custom label on node was lost after vm shut off but not after vm reboot

### ISSUE THREAD

**Issue by xmik** [kubernetes/kubernetes#38988]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
`node label reboot -author:k8s-merge-robot `
`node label lost -author:k8s-merge-robot `
`node label disappear -author:k8s-merge-robot `
Similar issues, but they concern cluster upgrade: https://github.com/kubernetes/kubernetes/issues/18307 , https://github.com/kubernetes/kubernetes/issues/29218

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-beta.3", GitCommit:"35fd1363821b8432ccde55632cf9ead4c79eddbb", GitTreeState:"clean", BuildDate:"2016-12-08T21:58:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-beta.3", GitCommit:"35fd1363821b8432ccde55632cf9ead4c79eddbb", GitTreeState:"clean", BuildDate:"2016-12-08T21:54:19Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Openstack
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): `Linux cluster1-k8s-master-1 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: https://github.com/kubernetes/kubernetes/tree/master/cluster/saltbase but customized
- **Others**:

**What happened**:
Custom label, applied on node, got lost after the vm (virtual machine) was shut off for ~2minutes and then started.

**What you expected to happen**:
I expected custom labels applied on any Kubernetes node to preserve vm reboots and longer shut off states.

**How to reproduce it** (as minimally and precisely as possible):
I have a Kubernetes cluster of 1 master vm and 1 node (worker) vm. I labeled them with `is_master=true` and `is_worker=true` so that:
```
ubuntu@cluster1-k8s-master-1:~/depl$ kubectl get nodes --show-labels
NAME                    STATUS    AGE       LABELS
cluster1-k8s-master-1   Ready     2d        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=RegionOne,failure-domain.beta.kubernetes.io/zone=nova,is_master=true,kubernetes.io/hostname=cluster1-k8s-master-1
cluster1-k8s-node-1     Ready     1h        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=RegionOne,failure-domain.beta.kubernetes.io/zone=nova,is_worker=true,kubernetes.io/hostname=cluster1-k8s-node-1
```
Then, I shut off the node vm. I waited until `kubectl get nodes` stopped listing that node. Then, I started the node vm. In result: the label `is_worker=true` disappeared:
```
ubuntu@cluster1-k8s-master-1:~/depl$ kubectl get nodes --show-labels
NAME                    STATUS    AGE       LABELS
cluster1-k8s-master-1   Ready     2d        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=RegionOne,failure-domain.beta.kubernetes.io/zone=nova,is_master=true,kubernetes.io/hostname=cluster1-k8s-master-1
cluster1-k8s-node-1     Ready     9s        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=RegionOne,failure-domain.beta.kubernetes.io/zone=nova,kubernetes.io/hostname=cluster1-k8s-node-1
```

**Anything else do we need to know**:
This happens each time in the circumstances explained above.
This does not happen when the node vm is rebooted, when `kubectl get nodes` still lists all the nodes.

**Comment by theothermike** [comment]
We get the exact same thing in GCE.  Currently testing 1.5.2.   If I reboot the VM manually to simulate failure, the tags stay.  If i bring it down for a couple of minutes, then back up, all my custom labels are gone.

This is of course bad, since we make extensive use of nodeSelector to place workloads targeting those labels

**Comment by gflarity** [comment]
Could someone please triage this? According to the k8s documentation (https://kubernetes.io/docs/user-guide/node-selection/), labels on nodes are a supported feature.  So these labels should survive the vm getting turned off then coming back online. So this is a bug. What's the priority on fixing it?

**Comment by davidopp** [comment]
The behavior described here is not a bug, but I can understand why it's not what you expect.

When you "reboot" a VM in GCE, the VM does not go away; it's supposed to be like rebooting a regular physical machine. At the GKE/Kubernetes level, that VM still maps to the same Node object.

When you delete a VM and then re-create it, it's a new VM. Due to an implementation detail of GCE Managed Instance Groups, deleting a VM and then immediately creating a VM will usually result in a VM with the same name. But it's not the same VM. If you do it fast enough, GKE/Kubernetes may not notice, but in general GKE/Kubernetes will notice, and will delete the Node object corresponding to the original VM and create a new Node object for the new VM. Because it's a new Node object, any labels you attached to the node using "kubectl label" with disappear.

Labels you attach to the node pool when you create the node pool (using the --node-labels command-line argument) *will* always appear on the Nodes in that node pool, even if you delete/create VMs or resize the node pool.

If you want to ensure that certain nodes always get certain labels, the only mechanism other than specifying them when you create the node pool is to run some kind of daemon in the cluster (you can run it as a Deployment with replicas=1) that watches the API server for new Node objects and sends a REST request to the API server to add appropriate label(s). Of course there will be a brief period when the Node won't have the label.

**Comment by theothermike** [comment]
@davidopp 

You describe 'delete' and 're-create' as losing the labels, which would be understandable.  Are you then suggesting 'stopping' and then 'starting' a VM is the same as 'delete' and 're-create'?  Because that also does not retain labels

I did not realize we could attach labels to nodePools, and have the nodes inherit those labels.  If that works as advertised, that would be sufficient for our use-case

**Comment by davidopp** [comment]
> Are you then suggesting 'stopping' and then 'starting' a VM is the same as 'delete' and 're-create'?

Based on the [documentation](https://cloud.google.com/compute/docs/instances/stopping-or-deleting-an-instance) and what you observed, it seems that it is the same as deleting the VM from the standpoint of the Kubernetes/GKE control plane.

**Comment by gflarity** [comment]
@davidopp 
Trying to wrap my head around what's happening.  Here's what it sounds like to me, could you please fill in the blanks here:

It sounds as if the label data is stored inside the K8s (etcd?) and there's some kind of fingerprint used to associate that the label data with a vm/node. If you stop a VM and then start it again on GCE it the finger print changes and so it looks like a different node and so the labels are gone?

**Comment by davidopp** [comment]
> It sounds as if the label data is stored inside the K8s (etcd?) and there's some kind of fingerprint used to associate that the label data with a vm/node. If you stop a VM and then start it again on GCE it the finger print changes and so it looks like a different node and so the labels are gone?

Yes, the label data is stored in etcd as part of the Node object for the corresponding node. (There's no fingerprint, it's just literally part of the Node object.) If you delete a VM, the Kubernetes NodeController eventually sees that the node is gone and deletes the Node object. If you then create a VM, Kubernetes creates a new Node object. There is no connection between this Node object and the one that was deleted, even if they have the same node name.

The reason labels survive VM reboot is that the VM is never deleted when you reboot. Also, if you delete a VM and then create a new one very quickly and it happens to get the same name as the one you deleted and it gets created before the NodeController notices the deletion, then it is as if the node was never deleted, and it will keep the labels. But this is not an intentional behavior; it's just because the NodeController doesn't do a "watch" on the cloud provider for node deletion, and instead it periodically polls.

**Comment by xmik** [comment]
I would be happy and eager to close this issue once https://github.com/kubernetes/kubernetes/issues/28051 is implemented.

**Comment by resouer** [comment]
Should have been fixed in #46254

**Comment by haoqing0110** [comment]
@resouer How does #46254 fix the "label lost" issue? I didn't find any parameter about node label for  configmap used by "Dynamic Kubelet Configuration". 

I refer to the doc here: https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/

> The subset of the Kubelet’s configuration that can be configured via a file is defined by the KubeletConfiguration struct here (v1beta1).

**Comment by MarkPare** [comment]
I think the original issue here is still not resolved.  When a node goes away / comes back, any manually applied labels on the node are lost.  I'm still unclear if this is a feature or a bug.

**Comment by Amejonah1200** [comment]
@MarkPare due to DaemonSets still not support restart policy of Never, using temporary node labels is a workaround to schedule a thing once after startup of a node (i.e. setting stuff on the host).
