### ISSUE TITLE
GKE network load balancer doesn't get deleted on service deletion

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#39420]
**FEATURE REQUEST**

When deleting a service of type LoadBalancer I would expect the GCE network load balancer to get deleted as well.

**Kubernetes version**

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.6.3
", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3
", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **GKE 1.4.7**:
- **gci image**

**What happened**:
Deleting a service of type LoadBalancer leaves the network load balancer in place leading to unnecessary costs.

**What you expected to happen**:
That the network load balancer gets removed as well.

**Comment by nebril** [comment]
What about other types of LoadBalancers/non-GKE clusters?

It seems to me that deleting objects outside of cluster is out of scope of Kubernetes and should be handled by cluster operator independently.

**Comment by JorritSalverda** [comment]
They're created automatically, so why not delete them automatically? 

Do you know how I can file an issue for the correct 'operator'? I guess it's a GKE application running on the master node?

**Comment by nebril** [comment]
Sorry, I was not aware that they were created automatically, as I don't use GKE too much. If I find a better place for this issue I will let you know.

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-cluster-lifecycle-misc ?

**Comment by MrHohn** [comment]
The network load balancer for k8s service should be deleted by the `service controller` automatically.

Was the LoadBalancer type serivce working normally after you created it? Could you still reproduce it?

As a side note, turning off a cluster with LoadBalancer type services exist may leak the network load balancer resources on GCE.

**Comment by mikedanese** [comment]
@kubernetes/sig-network-misc

**Comment by thockin** [comment]
I have a 1.4.6 cluster and it works for me.  The kube Service is really
gone?  Is this a user-defined Service or a kube-system?  Can you get logs
from kube-controller-manager that span the deletion of the Service and
failed LB removal?

**Comment by roberthbailey** [comment]
@thockin I think this is a GKE cluster so we can access logs if we know the cluster.

**Comment by JorritSalverda** [comment]
I have a forwarding rule with a creationTimestamp of `2017-01-03T12:05:37.785-08:00` that's orphaned in a cluster that's already at version 1.5.1.

It's inedeed a GKE cluster. How can I get you the project, cluster and forwarding rule name safely?

**Comment by thockin** [comment]
You can email me privately thockin@google

**Comment by dstiliadis** [comment]
Have  been seeing the same problem both in GKE and AWS. Its intermittent. Sometimes they get deleted, but not always. Indeed, some of the firewall rules in GKE remain there as well when the LB is not deleted. We are running a CI workload where we bring up the services, test, and shut them down and so we see it rather often.

**Comment by rbtcollins** [comment]
We just had a problem where ELBs and their security groups were not being deleted reliably on AWS: restarting the master node fixed it :(. Don't have much more info for you yet; uptime had been only several weeks before this happened. Similar to @dstiliadis we have a CI workload in this cluster.

**Comment by bgrant0607** [comment]
See also #15203.

**Comment by rbtcollins** [comment]
Yes, #15203 is definitely related; however the problem we had was not due to a restart of the controller; once restarted when we deleted a svc the elb was deleted too - we had to manually cleanup the previously deleted svc objects' elbs.

**Comment by JorritSalverda** [comment]
Haven't seen this issue in our clusters for a while, so closing it.

**Comment by hejix** [comment]
We have encountered this very same issue of leftover ILB components yesterday using the new GKE internal load balancers in 1.7.5. Since we have "Gold" GCP support, I made an issue and was advised to manually cleanup.  Since we are using fixed internal I.P. addresses for access on these ILBs,  I guess we have to automate the cleanup for the e2e regression testing.

**Comment by ensonic** [comment]
I think we also just saw this. We're running on GKE with kubernetes 1.7.8 and we run out of IP addresses. 
https://pantheon.corp.google.com/net-services/loadbalancing/loadBalancers/list shows that all IPs are used by load-balancers. If I run the script below

```shell
PROJECT=${1:-$(gcloud 2>/dev/null config get-value project)}
REGION=$(gcloud 2>/dev/null config  get-value compute/foo)
REGION=${REGION:-europe-west1}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

LIST=$(gcloud --project="${PROJECT}" compute forwarding-rules list --format='value(name)')

for x in ${LIST}; do
  description=$(gcloud compute --project="${PROJECT}" forwarding-rules describe "${x}" --region="${REGION}")
  service=$(echo "$description" | grep "^description:" | cut -d\' -f2 | jq -r '."kubernetes.io/service-name"')
  timestamp=$(echo "$description" | grep "^creationTimestamp:" | cut -d':' -f2-)

  echo "${x} ${timestamp} ${service}"
done
```
I get 8 lines for the same service.

**Comment by lesaux** [comment]
Still seeing this on GKE as well.
In comparison deleting persistent volumes effectively removes the disks from GCP project.

**Comment by sipian** [comment]
Has there been any update to this issue?
I am also using GKE cluster for CI/CD but load balancers don't get deleted automatically.
After some trials, I run out of global IP addresses.

**Comment by roberthbailey** [comment]
@sipian - I believe this was recently fixed. Are you currently seeing repeated creation / deletion leak load balancers?

@k4leung4 fyi

**Comment by sipian** [comment]
@roberthbailey @k4leung4 
My cluster has 3 load-balancer services
I used GKE API [DeleteCluster](https://godoc.org/cloud.google.com/go/container/apiv1#ClusterManagerClient.DeleteCluster) function to delete the cluster.
After the cluster gets deleted, a few instances of the following things still remain 
- In-use IP addresses global 
- Forwarding Rules
- Target Pools
- Health Checks
- Firewall Rules

And on creating & deleting the cluster repeatedly, the number of used instances of these resources kept on piling up.
This is a problem in automating cluster creation and deletion as the resources-quota is reached even when the resource is not being used.

**Comment by k4leung4** [comment]
@sipian 
This does sound like a bug if you are seeing orphaned resources.

Would you be interested in sharing your project ID with me privately, so that I can investigate this, or if you have a support ticket, cc me on the ticket, so that I can dig through the logs and see if I can figure out what is happening.

**Comment by tpoindessous** [comment]
Hi 

I have the same issue : on a dev project, I create and delete cluster and service with ILB, quite often (once a day).

I see that ILB are not deleted and since I use reserved internal IP addresses, new ILB doesn't work.

Maybe, someone should mark this issue as "opened" ?

Thanks !

**Comment by NickScottKortical** [comment]
Yup, i am still seeing this happen as well.

**Comment by lutierigb** [comment]
> @roberthbailey @k4leung4
> My cluster has 3 load-balancer services
> I used GKE API [DeleteCluster](https://godoc.org/cloud.google.com/go/container/apiv1#ClusterManagerClient.DeleteCluster) function to delete the cluster.
> After the cluster gets deleted, a few instances of the following things still remain
> 
> * In-use IP addresses global
> * Forwarding Rules
> * Target Pools
> * Health Checks
> * Firewall Rules
> 
> And on creating & deleting the cluster repeatedly, the number of used instances of these resources kept on piling up.
> This is a problem in automating cluster creation and deletion as the resources-quota is reached even when the resource is not being used.

I was able to repro this. looking at the kube-controller-manager log I see that it actually deletes all those resources by calling ensureExternalLoadBalancerDeleted but it doesn't seem to know that's being shutdown and continues to run the ensureExternalLoadBalancer method which re-creates all that, shortly after the controller is gone and those resources are left behind in you project. confirmed in version 1.14.6-gke.13

**Comment by roberthbailey** [comment]
@lutierigb - it sounds like you've found a race condition. 

Unfortunately, neither @k4leung4 nor I work on this part of the system any longer. @zmerlynn can probably point you in the right direction though.

**Comment by krmayankk** [comment]
Context: sig-architecture subgroup work to search for technical debt
Category: Networking
Reason: Improves adoption in Public Cloud, improves CTS(Cost to Serve),  k8s service is no longer declarative,

**Comment by akhilles** [comment]
can confirm that firewall rules are not being deleted when cluster is destroyed (v 1.14.8-gke.12)

**Comment by bowei** [comment]
@MrHohn I think this has been fixed by the work on finalizers?

**Comment by MrHohn** [comment]
Sorry for the late response. There are some more changes required on GKE side to incorporate the service finalizer feature. So no this is not fixed yet.

**Comment by hasheddan** [comment]
@MrHohn any updates here? Is there opportunity for non-GKE folks to help drive this effort forward?

**Comment by bowei** [comment]
This is more of a platform issue than a K8S issue at this point. The finalizers are sufficient to ensure deletion IF GKE cluster teardown is given sufficient time to allow the controller to run to completion. There are a number of things (longer cluster teardown, faster resource teardown) that will help out here, but they are not really possible in OSS.

One thing that would help is allowing parallel service updates to occur in the service controller at the same time so that operations don't block.
