### ISSUE TITLE
kubelet "soft" crash and node "NotReady"

### ISSUE THREAD

**Issue by sigxcpu76** [kubernetes/kubernetes#40745]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

```NO```

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```1.5.2```

**Environment**:
- **Cloud provider or hardware configuration**:
```Bare metal one node install```
- **OS** (e.g. from /etc/os-release):
```Ubuntu 16.04.1 LTS (Xenial Xerus)```
- **Kernel** (e.g. `uname -a`):
```4.4.0-59-generic```
- **Install tools**:
```kubeadm```
- **Others**:

**What happened**:

kubelet crashed in GC

```
Jan 30 02:37:06 k8s kubelet[1711]: fatal error: scan missed a g
Jan 30 02:37:06 k8s kubelet[1711]: goroutine 51 [running]:
Jan 30 02:37:06 k8s kubelet[1711]: runtime.throw(0x2954e6c, 0xf)
Jan 30 02:37:06 k8s kubelet[1711]:         /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4204686d0 sp=0xc4204686b0
Jan 30 02:37:06 k8s kubelet[1711]: runtime.gcMarkRootCheck()
Jan 30 02:37:06 k8s kubelet[1711]:         /usr/local/go/src/runtime/mgcmark.go:124 +0x275 fp=0xc420468720 sp=0xc4204686d0
Jan 30 02:37:06 k8s kubelet[1711]: runtime.gcMarkDone()
Jan 30 02:37:06 k8s kubelet[1711]:         /usr/local/go/src/runtime/mgc.go:1079 +0xc5 fp=0xc420468748 sp=0xc420468720
Jan 30 02:37:06 k8s kubelet[1711]: runtime.gcBgMarkWorker(0xc420031500)
Jan 30 02:37:06 k8s kubelet[1711]:         /usr/local/go/src/runtime/mgc.go:1497 +0x2c2 fp=0xc4204687b8 sp=0xc420468748
Jan 30 02:37:06 k8s kubelet[1711]: runtime.goexit()
Jan 30 02:37:06 k8s kubelet[1711]:         /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4204687c0 sp=0xc4204687b8
Jan 30 02:37:06 k8s kubelet[1711]: created by runtime.gcBgMarkStartWorkers
```

kubelet was not available after the above crash, but the process didn't crash so the whole node was not available.

**What you expected to happen**:

no crashing or hard crash to be able to be restarted by systemd

**How to reproduce it** (as minimally and precisely as possible):

n/a

**Anything else do we need to know**:

**Comment by resouer** [comment]
@sigxcpu76 Could you please post full version of log so we can find out which line caused crash?

**Comment by sigxcpu76** [comment]
Unfortunately I cannot find the log anymore. It was rotated and deleted, it seems.

**Comment by stregatto** [comment]
This is mine, kube 1.3.6, stop and start of kube performed manually.
No previous significant logs are available.

`Apr 09 12:10:53 prd-node013 kubelet[2145]: I0409 12:10:53.099030    2145 operation_executor.go:795] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/b3f7469b-1ada-11e7-be29-3ca82a136408-confi
g-volume" (spec.Name: "config-volume") pod "b3f7469b-1ada-11e7-be29-3ca82a136408" (UID: "b3f7469b-1ada-11e7-be29-3ca82a136408").
Apr 09 12:11:01 prd-node013 kubelet[2145]: fatal error: scan missed a g
Apr 09 12:11:01 prd-node013 kubelet[2145]: goroutine 25 [running]:
Apr 09 12:11:01 prd-node013 kubelet[2145]: runtime.throw(0x3671550, 0xf)
Apr 09 12:11:01 prd-node013 kubelet[2145]:         /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820064ef8 sp=0xc820064ee0
Apr 09 12:11:01 prd-node013 kubelet[2145]: runtime.gcMarkRootCheck()
Apr 09 12:11:01 prd-node013 kubelet[2145]:         /usr/local/go/src/runtime/mgcmark.go:87 +0x110 fp=0xc820064f20 sp=0xc820064ef8
Apr 09 12:11:01 prd-node013 kubelet[2145]: runtime.gcMarkDone()
Apr 09 12:11:01 prd-node013 kubelet[2145]:         /usr/local/go/src/runtime/mgc.go:1067 +0xcf fp=0xc820064f40 sp=0xc820064f20
Apr 09 12:11:01 prd-node013 kubelet[2145]: runtime.gcBgMarkWorker(0xc82001a000)
Apr 09 12:11:01 prd-node013 kubelet[2145]:         /usr/local/go/src/runtime/mgc.go:1480 +0x488 fp=0xc820064fb8 sp=0xc820064f40
Apr 09 12:11:01 prd-node013 kubelet[2145]: runtime.goexit()
Apr 09 12:11:01 prd-node013 kubelet[2145]:         /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820064fc0 sp=0xc820064fb8
Apr 09 12:11:01 prd-node013 kubelet[2145]: created by runtime.gcBgMarkStartWorkers
Apr 09 12:11:01 prd-node013 kubelet[2145]:         /usr/local/go/src/runtime/mgc.go:1330 +0x92
Apr 09 12:27:26 prd-node013 systemd[1]: Stopping kubernetes.service...
Apr 09 12:27:26 prd-node013 systemd[1]: Stopped kubernetes.service.
Apr 09 12:27:34 prd-node013 systemd[1]: Started kubernetes.service.`

**Comment by gosharplite** [comment]
Same with v1.5.1

Apr 25 12:36:50 worker-5 kubelet[16724]: I0425 12:36:50.930938   16724 operation_executor.go:917] MountVolume.SetUp succeeded for volume
Apr 25 12:36:51 worker-5 kubelet[16724]: fatal error: scan missed a g
Apr 25 12:36:51 worker-5 kubelet[16724]: goroutine 64 [running]:
Apr 25 12:36:51 worker-5 kubelet[16724]: runtime.throw(0x2954e6c, 0xf)
Apr 25 12:36:51 worker-5 kubelet[16724]:         /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4204756d0 sp=0xc4204756b0
Apr 25 12:36:51 worker-5 kubelet[16724]: runtime.gcMarkRootCheck()
Apr 25 12:36:51 worker-5 kubelet[16724]:         /usr/local/go/src/runtime/mgcmark.go:124 +0x275 fp=0xc420475720 sp=0xc4204756d0
Apr 25 12:36:51 worker-5 kubelet[16724]: runtime.gcMarkDone()
Apr 25 12:36:51 worker-5 kubelet[16724]:         /usr/local/go/src/runtime/mgc.go:1079 +0xc5 fp=0xc420475748 sp=0xc420475720
Apr 25 12:36:51 worker-5 kubelet[16724]: runtime.gcBgMarkWorker(0xc420042000)
Apr 25 12:36:51 worker-5 kubelet[16724]:         /usr/local/go/src/runtime/mgc.go:1497 +0x2c2 fp=0xc4204757b8 sp=0xc420475748
Apr 25 12:36:51 worker-5 kubelet[16724]: runtime.goexit()
Apr 25 12:36:51 worker-5 kubelet[16724]:         /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4204757c0 sp=0xc4204757b8
Apr 25 12:36:51 worker-5 kubelet[16724]: created by runtime.gcBgMarkStartWorkers
Apr 25 12:36:51 worker-5 kubelet[16724]:         /usr/local/go/src/runtime/mgc.go:1341 +0x98
Apr 26 02:40:57 worker-5 systemd[1]: Stopping Kubernetes Kubelet...
Apr 26 02:40:57 worker-5 systemd[1]: Stopped Kubernetes Kubelet.
Apr 26 02:41:11 worker-5 systemd[1]: Starting Kubernetes Kubelet...

**Comment by somejfn** [comment]
Same on v1.5.5

```
May 11 15:28:25 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]: I0511 15:28:25.982388    2141 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/5b666bce-1e0f-11e7-a1c2-f8db88162b01-flannel-cfg" (spec.Name: "flannel-cfg") pod "5b666bce-1e0f-11e7-a1c2-f8db88162b01" (UID: "5b666bce-1e0f-11e7-a1c2-f8db88162b01").
May 11 15:28:26 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]: fatal error: scan missed a g
May 11 15:28:26 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]: goroutine 23 [running]:
May 11 15:28:26 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]: runtime.throw(0x3460dd6, 0xf)
May 11 15:28:26 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]:         /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420044ed0 sp=0xc420044eb0
May 11 15:28:26 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]: runtime.gcMarkRootCheck()
May 11 15:28:26 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]:         /usr/local/go/src/runtime/mgcmark.go:124 +0x275 fp=0xc420044f20 sp=0xc420044ed0
May 11 15:28:26 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]: runtime.gcMarkDone()
May 11 15:28:26 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]:         /usr/local/go/src/runtime/mgc.go:1079 +0xc5 fp=0xc420044f48 sp=0xc420044f20
May 11 15:28:26 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]: runtime.gcBgMarkWorker(0xc420026000)
May 11 15:28:26 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]:         /usr/local/go/src/runtime/mgc.go:1497 +0x2c2 fp=0xc420044fb8 sp=0xc420044f48
May 11 15:28:26 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]: runtime.goexit()
May 11 15:28:26 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]:         /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420044fc0 sp=0xc420044fb8
May 11 15:28:26 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]: created by runtime.gcBgMarkStartWorkers
May 11 15:28:26 m62-i123-02-04.k8s.dev1.cloudsys.tmcs kubelet-wrapper[2141]:         /usr/local/go/src/runtime/mgc.go:1341 +0x98
```

**Comment by joshrosso** [comment]
```
kubelet[1711]: fatal error: scan missed a g
```
Possibly race related?

https://github.com/golang/go/issues/16083

**Comment by aclements** [comment]
What version(s) of Go were these seen with? We pushed a mitigation for this crash in Go 1.7.5 and Go 1.8, but I only had a hunch what the problem was, so it's possible this mitigation didn't work.

**Comment by stregatto** [comment]
Problem still remains, no chance to change go version til we are using kubelet from google repos (http://apt.kubernetes.io). kubelet was built using go 1.7.4

**Comment by stregatto** [comment]
Kubelet version v1.5.6

**Comment by sigxcpu76** [comment]
update for kubelet v1.7.8

```
Nov 24 04:48:48 minion-10-04 kubelet[2009]: gp 0xc421c74b60 goid 6922978 status 4100 gcscandone false gcscanvalid false
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: fatal error: scan missed a g
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: goroutine 6 [running]:
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: runtime.throw(0x3a4c23b, 0xf)
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4200886e0 sp=0xc4200886c0
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: runtime.gcMarkRootCheck()
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /usr/local/go/src/runtime/mgcmark.go:162 +0x22e fp=0xc420088730 sp=0xc4200886e0
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: runtime.gcMarkDone()
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /usr/local/go/src/runtime/mgc.go:1164 +0xee fp=0xc420088750 sp=0xc420088730
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: runtime.gcBgMarkWorker(0xc42001e000)
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /usr/local/go/src/runtime/mgc.go:1581 +0x303 fp=0xc4200887d8 sp=0xc420088750
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: runtime.goexit()
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4200887e0 sp=0xc4200887d8
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: created by runtime.gcBgMarkStartWorkers
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /usr/local/go/src/runtime/mgc.go:1412 +0x98
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: goroutine 1 [chan receive, 11654 minutes]:
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: k8s.io/kubernetes/cmd/kubelet/app.run(0xc420b4a000, 0xc4205b46e0, 0xc400000000, 0xc420b2d920)
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:635 +0x4cc
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: k8s.io/kubernetes/cmd/kubelet/app.Run(0xc420b4a000, 0x0, 0x3a9db4a, 0x22)
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:294 +0x39
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: main.main()
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:55 +0x9c
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: goroutine 17 [syscall, 11654 minutes, locked to thread]:
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: runtime.goexit()
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: goroutine 5 [chan receive]:
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x58dd360)
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879 +0x7a
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: created by k8s.io/kubernetes/vendor/github.com/golang/glog.init.1
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:410 +0x21d
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: goroutine 40 [select, 11654 minutes]:
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc420d48000, 0xc420018240, 0xc420efc300, 0xc420d01320, 0xc420efc2a0, 0xc420d48008)
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/reflector.go:268 +0x30c
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: created by k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/reflector.go:285 +0x864
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: goroutine 130 [syscall, 11654 minutes]:
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: os/signal.signal_recv(0x434a58)
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /usr/local/go/src/runtime/sigqueue.go:116 +0x104
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: os/signal.loop()
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
    Nov 24 04:48:48 minion-10-04 kubelet[2009]: created by os/signal.init.1
    Nov 24 04:48:48 minion-10-04 kubelet[2009]:         /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
```
