### ISSUE TITLE
Bad Reqeust log errors when using --cloud-provider=azure

### ISSUE THREAD

**Issue by ahmed-madkour** [kubernetes/kubernetes#41359]
**Kubernetes version** : v.1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04.5 LTS

I have added "--cloud-provider=azure --cloud-config=/etc/kubernetes/azure.json" to the apiserver,  controller-manager and kubelet services but I get a Bad Request in the logs

**Errors from kube-controller-manager.log**
```
E0213 21:17:31.238302   36479 nodecontroller.go:504] Error determining if node kafka-kube-node-1 exists in cloud: autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/{tenant}/oauth2/token?api-version=1.0 failed with 400 Bad Request: StatusCode=400
```

**Errors from kubelet.log**
```
E0213 21:17:46.940103   43024 kubelet_node_status.go:70] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/{tenant}/oauth2/token?api-version=1.0 failed with 400 Bad Request: StatusCode=400
```

**azure.json**
```
{
  "aadClientId": "text",
  "aadClientSecret": "text",
  "tenantId": "text",
  "subscriptionId": "text",
  "resourceGroup": "text",
  "location": "text"
}
```

```
/opt/bin/kubelet --logtostderr=true --v=0 --api-servers=https://kafka-kube-master-1:443 --address=0.0.0.0 --allow-privileged=true --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --config=/etc/kubernetes/manifests --cluster-dns=10.254.0.10 --cluster-domain=cluster.local --cloud-provider=azure --cloud-config=/etc/kubernetes/azure.json
```

kubectl get nodes
```
NAME                STATUS     AGE
kafka-kube-node-1   NotReady   53m
```

**Comment by ahmed-madkour** [comment]
It is solved I was using username & password while I should register an app in the azure active directory and use its id & secret.

**Comment by xqianwang** [comment]
@ahmmadkour Hi , I still have the same issue even I created an app in azure.
