### ISSUE TITLE
GKE master upgrades from 1.4 to 1.6 are failing (kubedns dnsmaq sidecar pods not ready)

### ISSUE THREAD

**Issue by skriss** [kubernetes/kubernetes#42746]
@krousey 

This is happening consistently across all GKE 1.4->1.6 master upgrade jobs. It is not occurring for full-cluster upgrades.

Example log:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.4-container_vm-1.6-upgrade-master/21

**Comment by krousey** [comment]
Config map is failing to mount for some reason.

```
I0308 01:38:36.698] Mar  8 01:38:36.683: INFO: At 2017-03-08 01:06:35 -0800 PST - event for kube-dns-806549836-c3nqq: {default-scheduler } Scheduled: Successfully assigned kube-dns-806549836-c3nqq to gke-bootstrap-e2e-default-pool-a130ab60-hrhd
I0308 01:38:36.698] Mar  8 01:38:36.683: INFO: At 2017-03-08 01:06:35 -0800 PST - event for kube-dns-806549836-c3nqq: {kubelet gke-bootstrap-e2e-default-pool-a130ab60-hrhd} FailedMount: MountVolume.SetUp failed for volume "kubernetes.io/configmap/87d6f245-03de-11e7-9372-42010af0002e-kube-dns-config" (spec.Name: "kube-dns-config") pod "87d6f245-03de-11e7-9372-42010af0002e" (UID: "87d6f245-03de-11e7-9372-42010af0002e") with: configmaps "kube-dns" not found
```

**Comment by krousey** [comment]
@bowei Could you take a look. It seems like the dns pod wants a config map, but for the life of me, I can't find where this config map is created.

https://github.com/kubernetes/kubernetes/blob/release-1.6/cluster/addons/dns/kubedns-controller.yaml.base#L54

**Comment by bowei** [comment]
optional: true for the configmap means that if the configmap does not exist, then the configmap directory should be empty

**Comment by bowei** [comment]
the optional configmap feature was added in 1.6

**Comment by krousey** [comment]
Ah. The kubelet here is 1.4 and doesn't understand optional configmaps. This causes the pod to error and never become ready.

**Comment by krousey** [comment]
cc @liggitt

**Comment by liggitt** [comment]
@MrHohn thanks, just saw this. glad to know the add-on manager support for ensureexists made it in 1.6

**Comment by MrHohn** [comment]
@liggitt Glad to see addon-manager could help out instead of causing problems :)

**Comment by liggitt** [comment]
@MrHohn #42757 merged, is this resolved now?

**Comment by MrHohn** [comment]
Seems like it is still failing in the latest run for the same reason:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.4-container_vm-1.6-upgrade-master/25

Checked the log and found the upgrade is using the beta release binary:
```
I0309 00:10:50.309] Downloading kubernetes release v1.6.0-beta.2
```
So I assume the test will keep failing until that PR got cherry picked into 1.6 branch and released?

**Comment by liggitt** [comment]
at least that, possibly until a new tag is cut

**Comment by ethernetdan** [comment]
This issue appears to be [resolved](https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gke-container_vm-1.4-container_vm-1.6-upgrade-master).

**Comment by skriss** [comment]
@MrHohn  we are now seeing similar-looking errors in the GKE cluster upgrade suites. Can you please take a look ASAP to help triage? Note that this time it is occurring in the full-cluster upgrades, not the master-only upgrades.

Example:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.5-gci-1.6-upgrade-cluster/50?log#log

**Comment by MrHohn** [comment]
Sure, looking into it.

**Comment by skriss** [comment]
@MrHohn FYI @krousey is looking at another issue related to GKE upgrades - not sure if they're related or not (they're reporting different errors)

**Comment by krousey** [comment]
I'm looking into an issue of the master not starting. This looks separate.

**Comment by MrHohn** [comment]
Don't have a theory yet, but saw couple strange errors:
```
I0316 12:10:06.024] E0316 19:05:00.858020       1 reflector.go:199] pkg/dns/dns.go:145: Failed to list *api.Endpoints: Get https://10.99.240.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.99.240.1:443: i/o timeout
I0316 12:10:06.024] E0316 19:05:00.858719       1 reflector.go:199] pkg/dns/dns.go:148: Failed to list *api.Service: Get https://10.99.240.1:443/api/v1/services?resourceVersion=0: dial tcp 10.99.240.1:443: i/o timeout
```
Which likely indicates Apiserver on master was not in a proper state. And seems like this happened before and after upgrade --- both old version and new version kubedns crashed with this error.

**Comment by MrHohn** [comment]
Found kube-proxy hit similar failure (seems like a permission error):
```
I0316 18:33:59.707992       7 healthcheck.go:119] Initializing kube-proxy health checker
E0316 18:33:59.722143       7 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:46: Failed to list *api.Service: User "kube_proxy" cannot list services at the cluster scope.: "No policy matched.\nUnknown user \"kube_proxy\"" (get services)
E0316 18:33:59.722143       7 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:49: Failed to list *api.Endpoints: User "kube_proxy" cannot list endpoints at the cluster scope.: "No policy matched.\nUnknown user \"kube_proxy\"" (get endpoints)
...
E0316 19:15:35.696465       7 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:49: Failed to list *api.Endpoints: User "kube_proxy" cannot list endpoints at the cluster scope.: "No policy matched.\nUnknown user \"kube_proxy\"" (get endpoints)
E0316 19:15:35.711569       7 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:46: Failed to list *api.Service: User "kube_proxy" cannot list services at the cluster scope.: "No policy matched.\nUnknown user \"kube_proxy\"" (get services)
```

**Comment by liggitt** [comment]
@cjcullen related to your ABAC work?

**Comment by krousey** [comment]
I just found this in a healthy master when trying to reproduce my problem. API server is definitely RBAC denying kube_proxy on cluster wide endpoint lists.

**Comment by liggitt** [comment]
@krousey Was this an upgrade or a new install?

**Comment by cjcullen** [comment]
Almost certainly related to what I did. I checked a 1.5->1.6 upgrade, but didn't check 1.4->1.6

**Comment by krousey** [comment]
It was an upgrade.
