### ISSUE TITLE
Kubelet starts pods before CNI is configured

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/kubernetes#43014]
This appears to be a regression since v1.5.x, and should be a blocker for releasing v1.6.

**Kubernetes version** (use `kubectl version`):
Built from master

**Install tools**:

- Seen by @luxas on a cluster created via kubeadm.  
- I've seen this on GCE using cluster/kube-up.sh and NETWORK_PROVIDER=cni.

**What happened**:

The kubelet is starting pods before a CNI config file is present on the node, and thus pods are started without networking.

Specifically, the DNS pod starts up and fails to watch the API, causing its health checks to fail.

**What you expected to happen**:

The kubelet should wait for a CNI network config to be present in the configured `cni-conf-dir`.

**How to reproduce it** (as minimally and precisely as possible):

Launch a cluster built from master using `--network-plugin=cni` on the kubelet and do not install a CNI plugin / config.

**Comment by caseydavenport** [comment]
CC @luxas @whitlockjc @kubernetes/sig-network-bugs

**Comment by luxas** [comment]
cc @kubernetes/sig-network-misc (only on person in @kubernetes/sig-network-bugs)
cc @kubernetes/sig-node-bugs @jbeda 

cc @kubernetes/release-team 
This is really bad and should probably be considered a release blocker.

**Comment by calebamiles** [comment]
ack @luxas

**Comment by yujuhong** [comment]
@caseydavenport @luxas I couldn't reproduce this. When did you observe this problem and could you make sure that #42767 was included in your branch?

**Comment by janwillies** [comment]
I observed it with `v1.6.0-beta.2`, which did not have this patch.

From the dates `v1.6.0-beta.3` should have this patch, I'll try to reproduce tomorrow.

**Comment by yujuhong** [comment]
The fix was included in `v1.6.0-beta.3`.

**Comment by dchen1107** [comment]
We believe the issue is fixed, and am closing it. If you disagreed it, feel free to reopen it.

**Comment by janwillies** [comment]
I can confirm that it's fixed with `v1.6.0-beta.3`

**Comment by djosborne** [comment]
I think I'm still seeing some form of this still in `v1.6.0-beta.3`. 

**Kubernetes version**: `v1.6.0-beta.3`

**Install tools:** `kubeadm` from unstable channel (`kubeadm v1.7.0-alpha.0.1163+5e29e1ee055568`)

**What happened:**

- On a fresh kubeadm cluster with no networking plugin installed yet, kube-dns fails to launch due to missing cni configurations
- Once a networking plugin (calico) is installed, kube-dns remains in the `ContainerCreating` state indefinitely.
- Deleting the kube-dns pod and allowing a new one to launch resolves the issue.

Kubelet logs show that kubelet was unable to stop kube-dns from launching: `Failed to stop sandbox "248726ea9398f1b4a66bc72857447e82638429e1bdd86c9a63ea07b48d862a91" before removing: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "kube-dns-3913472980-npkq9_kube-system" network: cni config uninitialized`

Here are the events from the kubelet:
```
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason          Message
  ---------     --------        -----   ----                            -------------   --------        ------          -------
  14m           14m             1       default-scheduler                               Normal          Scheduled       Successfully assigned kube-dns-3913472980-7gclg to turk-kubeadm-425t
  14m           14m             1       kubelet, turk-kubeadm-425t                      Warning         FailedSync      Error syncing pod, skipping: failed to "CreatePodSandbox" for "kube-dns-3913472980-7gclg_kube-system(f15ad72b-09c8-11e7-94be-42010af00022)" wit
h CreatePodSandboxError: "CreatePodSandbox for pod \"kube-dns-3913472980-7gclg_kube-system(f15ad72b-09c8-11e7-94be-42010af00022)\" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod \"kube-dns-3913472980-7gclg_kube-system\" network: cni con
fig uninitialized"

  14m   2m      57      kubelet, turk-kubeadm-425t              Warning FailedSync      Error syncing pod, skipping: failed to "KillPodSandbox" for "f15ad72b-09c8-11e7-94be-42010af00022" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni fail
ed to teardown pod \"kube-dns-3913472980-7gclg_kube-system\" network: cni config uninitialized"

  14m   12s     67      kubelet, turk-kubeadm-425t              Normal  SandboxChanged  Pod sandbox changed, it will be killed and re-created.
  2m    12s     10      kubelet, turk-kubeadm-425t              Warning FailedSync      Error syncing pod, skipping: failed to "KillPodSandbox" for "f15ad72b-09c8-11e7-94be-42010af00022" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni fail
ed to teardown pod \"kube-dns-3913472980-7gclg_kube-system\" network: resource does not exist: WorkloadEndpoint(node=turk-kubeadm-425t, orchestrator=k8s, workload=kube-system.kube-dns-3913472980-7gclg, name=eth0)"
```

**Comment by yujuhong** [comment]
> NetworkPlugin cni failed to teardown pod \"kube-dns-3913472980-7gclg_kube-system\" network: resource does not exist:

@dcbw @kubernetes/sig-network-bugs how is `TearDown` handled with the cni plugin? Can it be called on a non-existent (or already deleted) resource? With kubenet, we expect TearDown to be a no-op if the resource does not exist. (see #26208 and https://github.com/kubernetes/kubernetes/issues/20379#issuecomment-261693197).

**Comment by jbeda** [comment]
I've tried this with calico, weave and flannel.  In all cases, DNS pod never starts because teardown is the CNI plugin is called on a pod that was never created.  It is clear that none of these expect it to be a no-op.

Here is the flannel config I've put together: https://gist.github.com/jbeda/1953d4e3df6eab91066ba31875eb0c05.

To repro:
```
sudo kubeadm init --pod-network-cidr 10.244.0.0/16
sudo kubectl -n kube-system apply -f https://gist.githubusercontent.com/jbeda/1953d4e3df6eab91066ba31875eb0c05/raw/754d540c892acc0bd6313693713df2eeb7360de8/gistfile1.txt
```

Now find the DNS pod and see it doesn't start up.

**Comment by bowei** [comment]
I'm not very familiar with the CNI spec, but it seems like from the spec that DEL of an misisng resource should be supported:

line 248 in the current version of the spec:
```
Plugins should generally complete a DEL action without error even if some resources are missing. 
```

**Comment by thockin** [comment]
yeah, if plugins fail to delete nothing, we need to be able to know that is the reason for failure so we can absorb it, or else they really need to not fail.  Otherwise stale-state cleanup is effectively impossible innit?

**Comment by feiskyer** [comment]
> Here is the flannel config I've put together: https://gist.github.com/jbeda/1953d4e3df6eab91066ba31875eb0c05.

@jbeda  Flannel plugin failed because it requires write operation now. After authorizing write operations (set verbs to `'*'` for simplify), it works in my environments. 

 Same with calico and weave. See my config at [weave](https://gist.github.com/feiskyer/0b00688584cc7ed9bd9a993adddae5e3), [flannel](https://gist.github.com/feiskyer/1e7a95f27c391a35af47881eb20131d7) and [calico](https://gist.github.com/feiskyer/0f952c7dadbfcefd2ce81ba7ea24a8ca).

By the way, I'm running those daemon sets on both master and nodes for setting up CNI configs.

cc @luxas @caseydavenport @pipejakob Could you check the RBAC config for your environments.

**Comment by jbeda** [comment]
@feiskyer I'll give that a try later today.  But why does it require write?  And is it write to the node or for the pod?  I hesitate to just do '*' here.

**Comment by aaronlevy** [comment]
I turned off RBAC completely to try and validate this, but I'm still getting errors:

```
docker_sandbox.go:234] NetworkPlugin cni failed on the status hook for pod "kube-dns-321336704-d0fs9_kube-system": Unexpected command output nsenter: cannot open : No such file or directory
remote_runtime.go:109] StopPodSandbox "7ce9c426d2da3279540164c134ac61171dadc137ab6cb37e32a4ff44d6111a0d" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "kube-dns-321336704-d0fs9_kube-system" network: open /var/lib/cni/flannel/7ce9c426d2da3279540164c134ac61171dadc137ab
6cb37e32a4ff44d6111a0d: no such file or directory
kuberuntime_manager.go:573] killPodWithSyncResult failed: failed to "KillPodSandbox" for "f794675d-0a6c-11e7-a6fb-080027dbfa4a" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"kube-dns-321336704-d0fs9_kube-system\" network: open /var/lib/cni/flannel/7ce9c426d2da3279540164c134ac61171dadc137ab6cb37e32a4ff44d6111a0d: no such file or directory"
pod_workers.go:182] Error syncing pod f794675d-0a6c-11e7-a6fb-080027dbfa4a ("kube-dns-321336704-d0fs9_kube-system(f794675d-0a6c-11e7-a6fb-080027dbfa4a)"), skipping: failed to "KillPodSandbox" for "f794675d-0a6c-11e7-a6fb-080027dbfa4a" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"kube-dns-321336704-d0fs9_kube-system\" network: open /var/lib/cni/flannel/7ce9c426d2da3279540164c134ac61171dadc137ab6cb37e32a4ff44d6111a0d: no such file or directory"
```

Tried playing with CNI Version as well, but no luck (0.2.0 suggested, then tried 0.3.0 based on the links above).

I'm launching cluster using bootkube & v1.6.0+beta.3 (can provide repo-steps but a little more involved)

**Comment by bowei** [comment]
@aaronlevy -- which CNI plugins are you using?

@jbeda, @feiskyer -- can we split the RBAC issue ticket from this one? It seems to be a separate issue?

**Comment by aaronlevy** [comment]
@bowei flannel

**Comment by jbeda** [comment]
@bowei I'll test with wide open RBAC to rule it out.  The errors I'm seeing look to be separate and not due to RBAC.

**Comment by yujuhong** [comment]
@aaronlevy @jbeda @feiskyer, various cni/RBAC/calico/weave/flannel problems aside, I think this issue is about "tearing down non-existent resources" using the cni network plugin (`--network-plugin=cni`). I agree with @bowei that we should open new bugs for other issues.

**Comment by sameo** [comment]
@yujuhong I confirm that by hacking the flannel `cmdDel()` so that it does not return an error if some resources are missing, kube-dns restarts properly.

```C
diff --git a/plugins/meta/flannel/flannel.go b/plugins/meta/flannel/flannel.go
index e1eb278..f3b5373 100644
--- a/plugins/meta/flannel/flannel.go
+++ b/plugins/meta/flannel/flannel.go
@@ -240,12 +240,12 @@ func cmdAdd(args *skel.CmdArgs) error {
 func cmdDel(args *skel.CmdArgs) error {
        nc, err := loadFlannelNetConf(args.StdinData)
        if err != nil {
-               return err
+               return nil
        }
 
        netconfBytes, err := consumeScratchNetConf(args.ContainerID, nc.DataDir)
        if err != nil {
-               return err
+               return nil
        }
 
        n := &types.NetConf{}
```

**Comment by thockin** [comment]
So, to plugin authors:  Do we

a) fix your plugins to not return error for non-existing (and maybe tighten
the spec)

b) spec a particular error for this, so we can catch it and ignore it
ourselves (and still change all your CNI plugins)

c) try to make kubelet / CRI not call delete in these cases.  I don't know
what the correct signal would be to skip it.


I think (a) is the only real answer.  Even if the netns is gone, things
like the "local" IPAM has a checkpoint that it might need to update.
There's no way kubelet can know that.

**Comment by GheRivero** [comment]
The flannel plugin command (/opt/cni/bin/flannel) is called with several env variables, and reads input from stdin (it's as messy as it sounds)
env variables:
`KUBELET_NETWORK_ARGS="--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin" KUBELET_SYSTEM_PODS_ARGS="--pod-manifest-path=/etc/kuberetes/manifests --allow-privileged=true" KUBELET_DNS_ARGS="--cluster-dns=10.96.0.10 --cluster-domain=cluster.local" CNI_CONTAINERID2=46f1db56b523766bf33d3040594a63cd0c18f02851904b957ced32ea2e034b4a KUBELET_KUBECONFIG_ARGS="--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true" CNI_ARGS=IgnoreUnknown=1;K8S_POD_NAMESPACE=kube-system;K8S_POD_NAME=kube-dns-3913472980-8lp3n;K8S_POD_INFRA_CONTAINER_ID=46f1db56b523766bf33d3040594a63cd0c18f02851904b957ced32ea2e034b4a CNI_COMMAND=DEL CNI_IFNAME=eth0 CNI_NETNS= CNI_PATH=/opt/cni/bin:/opt/flannel/bin`

input json:
`{
"cniVersion": "0.3.0",
"name": "cbr0",
"type": "flannel",
"delegate": {
"isDefaultGateway": true
}
}
`

The result of the command execution is also a json:
`{
    "code": 100,
    "msg": "read /var/lib/cni/flannel: is a directory"
}`

But the return code is hardcoded on containernetworking/cni/pkg/skel.go

Quick dirty fix, regex the error code where @sameo pointed (`Error deleting network: open /var/lib/cni/flannel/0fc728c7494f3d6fffa79abf0e40f8675342c692ffeb446e8bf98f2b1c919d10: no such file or directory`)
Long term fix: patch the cni plugin, so the error code have some real meaning.

**Comment by tomdee** [comment]
@thockin I'm thinking through this now, both options a) and b) sound reasonable (though there might still be some changes required in kubernetes, e.g. around retry behavior).

This CNI issue is probably worth reading - https://github.com/containernetworking/cni/issues/309

**Comment by tomdee** [comment]
My current thinking is that the plugins should be fixed to match the spec that went in recently (saying that plugins shouldn't del). I think Calico almost has a fix ready, I think Weave almost has a fix ready, but someone needs to get the "official" CNI plugins fixed up too.

**Comment by tomdee** [comment]
We can try to get a new CNI release out with updated plugins that confirms to the spec, but do we know which plugins are actually causing problems? Is it just the flannel plugin, or are there others too?

**Comment by aaronlevy** [comment]
FWIW this change (https://github.com/containernetworking/cni/pull/407) resolved the issue with flannel in my tests - but other "official" CNI plugins may still need fixes.

**Comment by luxas** [comment]
Also see https://github.com/kubernetes/kubernetes/issues/43284 -- a potential fix we could (should) include in v1.6 to fix this temporarily. In v1.7, when we have time, we can require the CNI plugins to conform with the v0.3 CNI spec if we want, but hopefully not in v1.6

**Comment by GheRivero** [comment]
I jsut want to remember that the potential fix (#43284) is only tested with the flannel plugin. I'll test with other later today.

**Comment by ethernetdan** [comment]
Let's try to decide by EOD whether we are patching plugins are modifying 1.6 to ignore specific plugin errors.

**Comment by caseydavenport** [comment]
I'd like to see this fixed in the plugins (i.e. @thockin's "option a" above). Patching v1.6 to ignore specific errors is really brittle and scary and likely requires special case code for each plugin.

There is a PR which addresses this for Calico here which is expected to land very soon: https://github.com/projectcalico/cni-plugin/pull/289

**Comment by ethernetdan** [comment]
**Plugin fix PRs**
* flannel - containernetworking/cni#407
* bridge, ipvlan, macvlan, ptp - containernetworking/cni#412

**Comment by bboreham** [comment]
Weave Net 1.9.4, just released, does not error on missing netns or no-such-address during CNI DEL operation.

https://github.com/weaveworks/weave/releases/tag/v1.9.4

**Comment by tomdee** [comment]
It's also fixed in Calico CNI plugin v1.6.1 release - https://github.com/projectcalico/cni-plugin/releases/tag/v1.6.1

I've just merged the flannel CNI plugin fix https://github.com/containernetworking/cni/pull/407
But [my fix](https://github.com/containernetworking/cni/pull/412) for the other plugins probably still needs a little work (such as adding tests).

**Comment by jbeda** [comment]
We need someone to update the docs and identify which plugins are ready for kubeadm 1.6 and have fixes (1) RBAC roles (2) master taints (3) this issue.

Someone want to sign up?

**Comment by cmluciano** [comment]
I can help to test some of these things out. Should I just view the release notes for kubeadm 1.6 to determine what new features need tested?

**Comment by djosborne** [comment]
I've posted yaml to calico's master docs that launches Calico with correct RBAC on kubeadm 1.6: http://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml

This yaml launches master images of Calico. I plan to move it into a pinned Calico release that uses the pinned Calico CNI plugin ASAP.

**Comment by tomdee** [comment]
For 1) and 2) it might be that https://github.com/coreos/flannel/pull/618 and https://github.com/coreos/flannel/pull/614 should be merged. I haven't had a chance to test them yet but if someone else can then I can merge them.

**Comment by yujuhong** [comment]
> We need someone to update the docs and identify which plugins are ready for kubeadm 1.6 and have fixes (1) RBAC roles (2) master taints (3) this issue.

The list of cni plugins that work (or doesn't work) should be documented in the 1.6 release note even if kubeadm is not used to set up the cluster.

**Comment by dcbw** [comment]
Why is fixing the original issue not as simple as:

```
func (plugin *cniNetworkPlugin) Status() error {
	// Can't set up pods if we don't have any CNI network configs yet
	return plugin.checkInitialized()
}
```

**Comment by bowei** [comment]
Hi all -- I made a spreadsheet with the current status so we can track the progress of the plugin fixes. I tried to summarize what is on the sheet. Request edit privileges if you need to edit the sheet, thanks:

https://docs.google.com/spreadsheets/d/1Nqa6y4J3kEE2wW_wNFSwuAuADAl74vdN6jYGmwXRBv8/edit#gid=0

**Comment by yujuhong** [comment]
> Kubelet will basically poll CNI every 30s (its normal sync loop) and block any scheduling on the node until there's a CNI config. Kubenet already does this, but CNI doesn't.

This is a right fix for initialization, but I think the underlying cause (i.e., deletion with partial resources) still needs to be fixed. Otherwise, the problem will show up in other cases.

**Comment by ethernetdan** [comment]
After merging the plugin fixes, we need to build and push a new kube CNI build and update any references to it. Should any of [these](https://github.com/kubernetes/kubernetes/search?utf8=%E2%9C%93&q=07a8a28637e97b22eb8dfe710eeae1344f69d16e) NOT be bumped?

**Comment by dcbw** [comment]
@caseydavenport I think this specific issue is kinda diverging; it was originally about scheduling before ready, but now we've got a lot of talk about CNI plugins not handling DEL correctly in general.

The first is a legit Kube bug; the second is a plugin issue unrelated to kubelet (since this has always been the case with these plugins) but still relevant to the Kube release.  Perhaps that deserves its own separate issue?

**Comment by ethernetdan** [comment]
@dcbw agreed, let's move discussion of fixing DEL in plugins to #43488

**Comment by ethernetdan** [comment]
Fix for this being worked on in kubernetes/kubernetes#43474

**Comment by bboreham** [comment]
> talk about CNI plugins not handling DEL correctly [...]
> this has always been the case with these plugins

That part of the spec was only added three months ago.  I know things move fast around here, but it's not "always".

**Comment by ethernetdan** [comment]
@bboreham please move discussion of DEL to #43488

**Comment by KeithTt** [comment]
Change the network plugin from calico to contiv, and meet the same problem.

**Comment by bboreham** [comment]
@KeithTt this issue was fixed and closed eight months ago; if you are seeing something please file a new issue and follow the instructions to provide full details.
