### ISSUE TITLE
controller-manager: horizontalpodautoscalers.autoscaling the object has been modified

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#43357]
**Kubernetes version** (use `kubectl version`):

HEAD + PR https://github.com/kubernetes/kubernetes/pull/43354 (not affecting this though)

**Environment**:

https://github.com/luxas/kubeadm-workshop

**What happened**:
controller-manager logs:
```
W0319 20:40:46.849143       1 horizontal.go:126] Failed to reconcile my-hpa: failed to update status for my-hpa: Operation cannot be fulfilled on horizontalpodautoscalers.autoscaling "my-hpa": the object has been modified; please apply your changes to the latest version and try again
W0319 20:40:56.849159       1 horizontal.go:126] Failed to reconcile my-hpa: failed to update status for my-hpa: Operation cannot be fulfilled on horizontalpodautoscalers.autoscaling "my-hpa": the object has been modified; please apply your changes to the latest version and try again
W0319 20:41:06.849212       1 horizontal.go:126] Failed to reconcile my-hpa: failed to update status for my-hpa: Operation cannot be fulfilled on horizontalpodautoscalers.autoscaling "my-hpa": the object has been modified; please apply your changes to the latest version and try again
```

Seems like a race condition of some kind. Relevant controller-manager flags:
 - horizontal-pod-autoscaler-use-rest-clients: "true"
 - horizontal-pod-autoscaler-sync-period: "10s"

**What you expected to happen**:

It somehow autoscales the Deployment, but very unreliably:
```
kubectl get hpa
NAME      REFERENCE             TARGETS        MINPODS   MAXPODS   REPLICAS   AGE
my-hpa    Deployment/my-nginx   343200m / 10   2         10        6          5m
```
For instance, I expected the replicas to be 10 when the value is 34x the target (but I haven't read the maths here so I don't know yet)

@DirectXMan12 @piosz Do you know what the issue could be?

**Comment by DirectXMan12** [comment]
not sure, can you get any more detailed logs from the controller manager and API server?  Maybe the deployment controller is interrupting us?

**Comment by calebamiles** [comment]
Is this a release blocker @luxas, @DirectXMan12? We need to move this issue into either the `v1.6` milestone if it is or into the `v1.6.1` or `v1.7` milestones so the release team can move on to other issues.

**cc: @ethernetdan, @kubernetes/kubernetes-release-managers**

**Comment by luxas** [comment]
@calebamiles Not a blocker, moving milestone to v1.6.1 for further triage, but this is nonblocking

**Comment by luxas** [comment]
This is probably fixed at this point in time.

**Comment by Quentin-M** [comment]
Seeing this on endpoints as of now. After an hour, and a controller restart, the issue was not fixed. Removing the endpoint and cycling the pods that backs the endpoint fixed the issue.

Note that 1/ I am using client-go (even tho never on endpoints..) and killed+recovered my etcd cluster entirely for disaster recovery testing.

This is legitimately scary..

**Comment by DirectXMan12** [comment]
please don't piggyback on different issues.  If you're seeing it with a different controller, please file a new bug

**Comment by discordianfish** [comment]
I have the exact same problem on a 1.10.3 cluster:

describe hpa:
```
Warning  FailedUpdateStatus  1m (x2496 over 20h)  horizontal-pod-autoscaler  Operation cannot be fulfilled on horizontalpodautoscalers.autoscaling "xxx": the object has been modified; please apply your changes to the latest version and try again
```

controller manager logs:
```
E0712 16:53:06.949662       1 horizontal.go:189] failed to update status for xxx: Operation cannot be fulfilled on horizontalpodautoscalers.autoscaling "xxx": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by discordianfish** [comment]
I've deleted the HPA but something is still scaling my deployment up and down.

**Comment by discordianfish** [comment]
I think I solved this issue by restarting the apiserver (which I did to enable request logging to figure out what exactly is updating the deployment), which doesn't really make sense..

The day before we observed the issue we had a misbehaving application that send lots of update attempts to a configmap, causing high(er) load on the apiserver. We didn't observe any direct issues due to that but maybe this caused something to get into a bad shape.

I though maybe there is some sort of update queuing in the apiserver that was fixed by a restart but the 'caches' I have metrics for in prometheus (e.g `etcd_helper_cache_entry_count`) seems always to be at zero.

I find it unlikely but possibly something caused delay in the api updates which caused both the hpa versioning conflict as well as the HPA still being active after I've deleted it.

n.b: I've also double checked with kubectl --raw that the HPA was indeed gone and it's not some sort of kubectl displaying issue.

**Comment by MaciekPytel** [comment]
I think a possible explanation for issue reported by @discordianfish could be informer missing a delete event for HPA? My guess would be that restarting apiserver forced informer to re-list resources, which would explain why it solved the issue.

@kubernetes/sig-api-machinery-bugs Does the above make any sense?
@bsalamat That looks similar to the issues with scheduler missing delete events. Have we ever found the root cause of those?
