### ISSUE TITLE
pull-kubernetes-federation-e2e-gce test failed

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#45954]
> error during ./federation/cluster/federation-up.sh: exit status 1from junit_runner.xml

> W0517 05:04:27.446] 2017/05/17 05:04:27 main.go:195: Something went wrong: error starting federation: error during ./federation/cluster/federation-up.sh: exit status 1
W0517 05:04:27.446] +(/workspace/e2e-runner.sh:1): main(): chmod -R o+r /workspace/_artifacts
I0517 05:04:28.366] Starting pull-kubernetes-federation-e2e-gce-5154...
W0517 05:04:28.373] Traceback (most recent call last):
W0517 05:04:28.374]   File "/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 488, in <module>
W0517 05:04:28.374]     main(create_parser().parse_args())
W0517 05:04:28.374]   File "/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 418, in main
W0517 05:04:28.374]     mode.start(runner_args)
W0517 05:04:28.374]   File "/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 307, in start
W0517 05:04:28.374]     check(*cmd)
W0517 05:04:28.375]   File "/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 40, in check
W0517 05:04:28.375]     subprocess.check_call(cmd)
W0517 05:04:28.375]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W0517 05:04:28.375]     raise CalledProcessError(retcode, cmd)
W0517 05:04:28.376] subprocess.CalledProcessError: Command '('docker', 'run', '--rm', '--name=pull-kubernetes-federation-e2e-gce-5154', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/kubernetes/_artifacts:/workspace/_artifacts', '-v', '/etc/localtime:/etc/localtime:ro', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-e', 'HOME=/workspace', '-e', 'WORKSPACE=/workspace', '--env-file', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/../platforms/gce.env', '--env-file', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/../jobs/pull-kubernetes-e2e.env', '--env-file', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/../jobs/pull-kubernetes-federation-e2e-gce.env', '-v', '/home/jenkins/.ssh/google_compute_engine:/workspace/.ssh/google_compute_engine:ro', '-v', '/home/jenkins/.ssh/google_compute_engine.pub:/workspace/.ssh/google_compute_engine.pub:ro', '-e', 'JENKINS_GCE_SSH_PRIVATE_KEY_FILE=/workspace/.ssh/google_compute_engine', '-e', 'JENKINS_GCE_SSH_PUBLIC_KEY_FILE=/workspace/.ssh/google_compute_engine.pub', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce@tmp/secretFiles/f2aa1f10-e5f2-4c06-82c6-9ecf6c537432/kubernetes-jenkins-pull-c67f9519f993.json:/service-account.json:ro', '-e', 'GOOGLE_APPLICATION_CREDENTIALS=/service-account.json', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/kubernetes:/go/src/k8s.io/kubernetes', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/release:/go/src/k8s.io/release', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/release:/go/src/k8s.io/release', '-e', 'JENKINS_HOME=/var/lib/jenkins', '-e', 'BUILD_CAUSE=MANUALTRIGGER', '-e', 'PULL_BASE_REF=master', '-e', 'HUDSON_URL=http://goto.google.com/prkubekins/', '-e', 'BUILD_URL=http://goto.google.com/prkubekins/job/pull-kubernetes-federation-e2e-gce/5154/', '-e', 'BOOTSTRAP_MIGRATION=yes', '-e', 'CLOUDSDK_CONFIG=/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/kubernetes/.config/gcloud', '-e', 'BUILD_TAG=jenkins-pull-kubernetes-federation-e2e-gce-5154', '-e', 'HUDSON_SERVER_COOKIE=32617aabcc4952a0', '-e', 'JENKINS_URL=http://goto.google.com/prkubekins/', '-e', 'LOGNAME=jenkins', '-e', 'USER=jenkins', '-e', 'JOB_NAME=pull-kubernetes-federation-e2e-gce', '-e', 'LANG=en_US.UTF-8', '-e', 'SHELL=/bin/bash', '-e', 'buildId=59b73cbb-3af5-11e7-8413-0a580a6c150a', '-e', 'HUDSON_HOME=/var/lib/jenkins', '-e', 'NODE_LABELS=agent-pr-93 pull', '-e', 'JOB_URL=http://goto.google.com/prkubekins/job/pull-kubernetes-federation-e2e-gce/', '-e', 'ROOT_BUILD_CAUSE_MANUALTRIGGER=true', '-e', 'BUILD_CAUSE_MANUALTRIGGER=true', '-e', 'JENKINS_AWS_CREDENTIALS_FILE=/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce@tmp/secretFiles/cb18732a-4c19-44f2-b278-c649b2b920d6/KubernetesPresubmitTests.txt', '-e', 'ROOT_BUILD_CAUSE=MANUALTRIGGER', '-e', 'SSH_CLIENT=10.240.0.2 56672 22', '-e', 'BUILD_ID=5154', '-e', 'BUILD_NUMBER=5154', '-e', 'HUDSON_COOKIE=94c44bf0-d211-41e5-900c-b7447961bc86', '-e', 'JENKINS_AWS_SSH_PRIVATE_KEY_FILE=/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce@tmp/secretFiles/e163bece-51ab-46cb-8a10-bea83af04525/id_rsa.jenkins', '-e', 'JENKINS_GCE_SSH_PRIVATE_KEY_FILE=/home/jenkins/.ssh/google_compute_engine', '-e', 'JOB_BASE_NAME=pull-kubernetes-federation-e2e-gce', '-e', 'NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat', '-e', 'JENKINS_GCE_SSH_PUBLIC_KEY_FILE=/home/jenkins/.ssh/google_compute_engine.pub', '-e', '_=./test-infra/jenkins/bootstrap.py', '-e', 'JENKINS_AWS_SSH_PUBLIC_KEY_FILE=/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce@tmp/secretFiles/94d9fe8b-32ba-47ea-a7a0-dc8518db3975/id_rsa.jenkins.pub', '-e', 'EXECUTOR_NUMBER=0', '-e', 'NODE_NAME=agent-pr-93', '-e', 'PULL_NUMBER=45950', '-e', 'SHLVL=2', '-e', 'JENKINS_SERVER_COOKIE=32617aabcc4952a0', '-e', 'BUILD_DISPLAY_NAME=#5154', '-e', 'PULL_REFS=master:e401dc749868a00e5bbe6669cf35cfe196f43f28,45950:582fec0495bc1f9068b90df651e1db1c6d0eecc5', '-e', 'XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt', '-e', 'MAIL=/var/mail/jenkins', '-e', 'SSH_CONNECTION=10.240.0.2 56672 10.240.0.95 22', '-e', 'CLOUDSDK_COMPONENT_MANAGER_DISABLE_UPDATE_CHECK=true', '-e', 'CLOUDSDK_EXPERIMENTAL_FAST_COMPONENT_UPDATE=false', '-e', 'E2E_UP=true', '-e', 'E2E_TEST=true', '-e', 'E2E_DOWN=true', '-e', 'E2E_NAME=e2e-gce-agent-pr-93-0', '-e', 'KUBE_AWS_INSTANCE_PREFIX=e2e-gce-agent-pr-93-0', '-e', 'INSTANCE_PREFIX=e2e-gce-agent-pr-93-0', '-e', 'KUBE_GCE_NETWORK=e2e-gce-agent-pr-93-0', '-e', 'KUBE_GCE_INSTANCE_PREFIX=e2e-gce-agent-pr-93-0', '-e', 'CLUSTER_NAME=e2e-gce-agent-pr-93-0', '-e', 'KUBE_GKE_NETWORK=e2e-gce-agent-pr-93-0', 'gcr.io/k8s-testimages/kubekins-e2e:v20170504-79009d67', '--build', '--stage=gs://kubernetes-release-pull/ci/pull-kubernetes-federation-e2e-gce', '--multiple-federations')' returned non-zero exit status 1
E0517 05:04:28.376] Build failed
I0517 05:04:28.376] process 28072 exited with code 1 after 23.5m

**Comment by nikhita** [comment]
xref. #45978.

**Comment by cblecker** [comment]
I believe this is now fixed, per #45978.
/close

**Comment by NickrenREN** [comment]
err still happened : https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46008/pull-kubernetes-federation-e2e-gce/5814/

**Comment by pmichali** [comment]
I think this is what I'm seeing (consistently) with #46138 and #46874.
