### ISSUE TITLE
HPA cannot get metrics from heapster

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#47334]
HPA e2e tests were failing (starting from 2017-06-06 till 2017-06-09) because HPA controller couldn't get CPU from heapster:

```
E0606 11:48:20.696662       5 horizontal.go:205] failed to compute desired number of replicas based on listed metrics for replicaset/e2e-tests-horizontal-pod-autoscaling-38f01/rs: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster
```

Logs: 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1207

The tests started passing again on 2017-06-10:
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gce-serial

**Comment by jszczepkowski** [comment]
CC @dchen1107 @wasylkowski

**Comment by jszczepkowski** [comment]
CC @kubernetes/sig-autoscaling-bugs

**Comment by piosz** [comment]
It seems there was some issue with kube-dns so that the heapster service was not reachable. At the same time a number of other tests failed. Closing as the problem is fixed now.

**Comment by praparn** [comment]
Dear all, 

   According to test HPA on K8S 1.8.0 with enable heapster/influxdb/grafana. We still facing problem from error " the HPA was unable to compute the replica count: unable to get metrics for resource cpu: no metrics returned from heapster". Please kindly suggest for troubleshooting. (Now i'm running this on via gcloud

Br,
Praparn L

=====================================================================

Type                  Status     Reason                              Message
 ScalingActive    False      FailedGetResource          Metric  

Message:
the HPA was unable to compute the replica count: unable to get metrics for resource cpu: no metrics returned from heapster

**Comment by piosz** [comment]
@praparn could you please create a new issue, providing logs from HPA controller and Heapster there, as well any relevant informations for debugging purposes and ccing me?

**Comment by samlyhuang** [comment]
I have the same problem
kubernetes version:1.6.2
heapster version:1.3.0

```
kubectl get deployment                    
NAME                    DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
ceph-pod5-with-secret   2            2                   2                  2           10h
```

```
kubectl get pods                          
NAME                                     READY     STATUS    RESTARTS   AGE
ceph-pod5-with-secret-3074552501-6ffqd   1/1       Running   0          10h
ceph-pod5-with-secret-3074552501-sqq6k   1/1       Running   0          10h
```

```
 kubectl describe hpa ceph-pod5-with-secret
Name:                                                   ceph-pod5-with-secret
Namespace:                                              default
Labels:                                                 <none>
Annotations:                                            <none>
CreationTimestamp:                                      Sat, 04 Nov 2017 21:22:52 +0800
Reference:                                              Deployment/ceph-pod5-with-secret
Metrics:                                                ( current / target )
  resource cpu on pods  (as a percentage of request):   <unknown> / 5%
Min replicas:                                           2
Max replicas:                                           5
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason                          Message
  ---------     --------        -----   ----                            -------------   --------        ------                          -------
  10h           16s             98      horizontal-pod-autoscaler                       Warning         FailedGetResourceMetric         unable to get metrics for resource cpu: no metrics returned from heapster
  10h           16s             98      horizontal-pod-autoscaler                       Warning         FailedComputeMetricsReplicas    failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster
```

**Comment by MPJHorner** [comment]
This get resolved?

**Comment by praparn** [comment]
Dear all,
  
   As check we found that HPA with K8S Version 1.9 and above was switch to use "metric-server". So we had install metric-server for get the performance data to HPA. This work fine

        git clone https://github.com/kubernetes-incubator/metrics-server.git
	cd metrics-server/
	kubectl create -f deploy/1.8+

   *Full my github for this test: https://raw.githubusercontent.com/praparn/kubernetes_20170128/master/WorkShop_2.8_HPA_WorkShop/HPA_Instruction.txt

Br,
Praparn L
