### ISSUE TITLE
kubeadm controller-manager no /etc/fstab when use cloud-provider "openstack" "config-drive"

### ISSUE THREAD

**Issue by ZhenyangZhao** [kubernetes/kubernetes#47392]
Dear All:
I'm not sure if I'm right. When i use `kubeadm init --config=xxxx` whith `openstack provider config-drive`.I found controller-manager logs 
```
E0613 02:17:16.809590       1 mount_linux.go:122] Mount failed: exit status 1
Mounting command: mount
Mounting arguments:  /tmp/configdrive336243194 vfat [ro]
Output: mount: can't read '/etc/fstab': No such file or directory
``` 

#### env
```
kubeadm: 1.6.3
host: ubuntu xenial
network: calico ipip
```

Someone can help me? Thanks a lot.

**Comment by ZhenyangZhao** [comment]
@kubernetes/sig-storage-bugs

**Comment by luxas** [comment]
@ZhenyangZhao Please give more information about your set up
cc @kubernetes/sig-openstack-bugs

**Comment by ZhenyangZhao** [comment]
@luxas Sorry for report later.
#### My /etc/systemd/system/kubelet.service.d/10-kubeadm.conf 
```
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_CLOUD_PROVIDER=--cloud-provider=openstack --cloud-config=/etc/kubernetes/cloud-config"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_EXTRA_ARGS $KUBELET_CLOUD_PROVIDER

```
#### I use kubeadm init --config=kubeadm.config
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: "10.6.2.12"
  bindPort: "8080"
etcd:
  endpoints:
  - "http://192.168.0.18:2379"
  - "http://192.168.0.19:2379"
  - "http://192.168.0.20:2379"
kubernetesVersion: "v1.6.3"
cloudProvider: "openstack"
```
#### /etc/kubernetes/cloud-config
```
[Global]
auth-url=http://10.116.0.100:5000/v2.0
username=*******
password=823575bc28****8ced5eb932104c567249c0
tenant-id=1a60ef7e4b****58aa8521838482d68a
tenant-name=*****
region=RegionOne
```

#### docker info
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 69
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-79-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796 GiB
Name: node1
ID: KRFG:FPD2:O2ZW:E7UT:5MGR:MIUZ:5WFR:FF4N:WL6G:SK6K:DJOC:A7HE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
#### system info
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by luxas** [comment]
Thanks @ZhenyangZhao 
Based on this, I think it's an openstack cloudprovider problem more than a kubeadm problem...

**Comment by ZhenyangZhao** [comment]
@luxas  Thank you for help me. I will change the label.

**Comment by dims** [comment]
Should be fixed with https://github.com/kubernetes/kubernetes/pull/52628 you can specify a search order for metadata and config drive

/close

**Comment by bputt** [comment]
Specifying a search order doesn't really solve the problem, especially if the metadata api isn't available which is what ZhenyangZhao said ```My openstack didn't support metadata service,but support config-drive service```.

I'm getting the same issue and since the config drive is my only option at the moment.

**Comment by bputt** [comment]
Like for this to be
/open

**Comment by dims** [comment]
@bputt can you please provide logs/versions for your problem in your environment?

Thanks,
Dims

**Comment by bputt** [comment]
Let me know if you need anything else

Kubernetes version: 1.8.4
Docker version: 17.09.0-ce
Linux: CentOS 7.4

Looking at the docker container log for the api-server (I don't have problems with the controller-manager):

```
[mount_linux.go:142] Mount failed: exit status 1
Mounting arguments: -t vfat -o ro /tmp/configdrive071298910
Output: mount: can't read '/etc/fstab': No such file or directory
Error mounting configdrive: mount failed
```

**Comment by bputt** [comment]
```/etc/kubernetes/manifests/kube-apiserver.yaml``` and ```/etc/kubernetes/manifests/kube-controller-manager.yaml``` share the following:

```
spec:
  containers:
  - command:
    - --cloud-provider=openstack
    - --cloud-config=/etc/kubernetes/cloud.conf
    ...

volumeMounts:
- mountPath: /etc/kubernetes/cloud.conf
  name: cloud-config
  readOnly: true

volumes:
- hostPath:
    path: /etc/kubernetes/cloud.conf
    type: File
  name: cloud-config
```

```/etc/systemd/system/kubelet.service.d/10-kubeadm.conf```

```
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --cloud-provider=openstack --cloud-config=/etc/kubernetes/cloud.conf"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"
Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=cgroupfs"
Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki"
User=root
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CGROUP_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS
```

**Comment by luxas** [comment]
Hi!

Thank you for filing this issue. We appreciate your interest in Kubernetes and kubeadm.
In order to make the kubernetes/kubernetes issue tracker more usable, we're routing issues to different repositories with different focuses.

I think this issue belongs in the kubeadm repository. Please move this issue to the [kubeadm repo tracker](https://github.com/kubernetes/kubeadm/issues) in order for the kubeadm team to be able to track this efficiently. If you disagree with my assessment of moving this issue, please speak up and/or reopen the issue. Finally, please try to reproduce the bug with the latest Kubernetes version, it might as well already have been fixed :)

Thank you and have a good day!
