### ISSUE TITLE
container metrics missing from kubelet

### ISSUE THREAD

**Issue by moserke** [kubernetes/kubernetes#47744]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:24Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-beta.2", GitCommit:"ceab7f7a6753c20d3be75463b17402fdcea856ba", GitTreeState:"clean", BuildDate:"2017-06-15T16:53:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:  vsphere
- **OS** (e.g. from /etc/os-release):  
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.8.0
VERSION_ID=1353.8.0
BUILD_ID=2017-05-30-2322
PRETTY_NAME="Container Linux by CoreOS 1353.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```
- **Kernel** (e.g. `uname -a`): 4.9.24-coreos
- **Install tools**:
- **Others**:

**What happened**:
After bringing a cluster up, there are no container metrics in the kubelet at /metrics

**What you expected to happen**:
I expect to see the `container_` metrics, but there are none

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

If I try and access the metrics in cAdvisor directly on port 4194 instead of on port 10255 then I see the following type of error for all of the metrics:

```
* collected metric container_tasks_state label:<name:"container_name" value:"zabbix-agent" > label:<name:"id" value:"/kubepods/besteffort/pod7f16ef41-5511-11e7-a4a0-0050569c59e0/d27ce4fc153ece655aba5347f3a3f0062a0d0e9a07f6ec4a0ec15e37af506a43" > label:<name:"image" value:"zabbix/zabbix-agent@sha256:ebaf779e63aadf8b196c7661833cab07e5cb1c71721174dc19f00fe8fb3d23d0" > label:<name:"name" value:"k8s_zabbix-agent_zabbix-agent-3xcqc_kube-system_7f16ef41-5511-11e7-a4a0-0050569c59e0_0" > label:<name:"namespace" value:"kube-system" > label:<name:"pod_name" value:"zabbix-agent-3xcqc" > label:<name:"state" value:"uninterruptible" > gauge:<value:0 >  has label dimensions inconsistent with previously collected metrics in the same metric family
```

**Comment by moserke** [comment]
This appears to be a v1.7 issue.  If I run 1.6.6 I get these metrics.  Seems like something has happened in 1.7.  I'm running the 1.7 beta because I need nodePort for calico, so now I'm stuck.

**Comment by dchen1107** [comment]
@euank Can you triage the issue since?

**Comment by dchen1107** [comment]
cc/ @kubernetes/sig-node-bugs

**Comment by Random-Liu** [comment]
@dchen1107 I've tried this on both cos and cvm in 1.7 cluster, and no container metrics show up.

However, I created a 1.6.4 GKE cluster, and container metrics are there.

This is a regression in 1.7. Will figure out what is wrong here.

**Comment by Random-Liu** [comment]
Here is a corresponding cadvisor issue https://github.com/google/cadvisor/issues/1671.

**Comment by dchen1107** [comment]
Even the user still can get the container metrics / stats from kubelet /summary api (recommended way), but since this is a regression introduced in 1.7 release, and we aren't dropping prometheus support, let's fix this for 1.7. Thanks!

**Comment by Random-Liu** [comment]
Fixed in https://github.com/google/cadvisor/pull/1681.

Will close this issue after building new cadvisor release and cherrypick into 1.7

**Comment by moserke** [comment]
Thanks for the quick find everyone!  I'll be happy to give this a go on the next release!

**Comment by notuscloud** [comment]
I'm still facing this same issue.

My kubernetes cluster is deployed with kubeadm on Centos 7. I run a k8S v1.8.1 cluster.
When I try to fetch containers metrics this way:
* http://localhost:8001/api/v1/proxy/nodes/node1:0/metrics
* http://localhost:8001/api/v1/proxy/nodes/node1:10250/metrics
* http://localhost:8001/api/v1/proxy/nodes/node1:10255/metrics
I find no `container_*` metrics. 
kubelet is started with `--cadvisor-port=0`. 
If I start kubelet with `--cadvisor-port=4194`. `container_*` metrics are available through `http://localhost:8001/api/v1/proxy/nodes/node1:4194/metrics`.
