### ISSUE TITLE
[upgrade test failure] Several network partition test failing 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#47820]
After we fixed upgrade test infra issue (https://github.com/kubernetes/kubernetes/issues/47379#issuecomment-309912047), now we get better signals on real failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1-6-1-7-upgrade-cluster/55 The following Network Partition tests are failed: 

```
[k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [Job] should create new pods when node is partitioned
[k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [ReplicationController] should eagerly create replacement pod during network partition when termination grace is non-zero
[k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [ReplicationController] should recreate pods scheduled on the unreachable node AND allow scheduling of pods on a node after it rejoins the cluster
[k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [StatefulSet] should come back up if node goes down [Slow] [Disruptive]
[k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [StatefulSet] should not reschedule stateful pods if there is a network partition [Slow] [Disruptive]
```

**Comment by janetkuo** [comment]
cc @foxish

**Comment by janetkuo** [comment]
Errors look like this:

```
Node xxx did not become not-ready within 2m0s
```

**Comment by foxish** [comment]
Looking into this

**Comment by foxish** [comment]
Not a real failure.
The upgrade cluster is bootstrapping the kubelet in a different way when compared with other e2e clusters.

```
ramanathana@bootstrap-e2e-minion-group-93zx:~$ sudo cat /var/lib/kubelet/kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca-certificates.crt
    server: https://bootstrap-e2e-master 
  name: default-cluster
contexts:
...
```

The **server** is typically (in every other cluster I inspected) the external IP address of the master in all other clusters. Here, it is using the DNS name, which resolves to the internal IP address.
The iptables rule injections don't take effect due to that difference.

cc @krousey @kubernetes/test-infra-maintainers

**Comment by krousey** [comment]
cc @mikedanese

**Comment by foxish** [comment]
Additionally, this only happens in CVM tests. Looks to me like it's a cluster bootstrapping issue.

**Comment by marun** [comment]
@foxish Should this be closed then?

**Comment by foxish** [comment]
Not a release blocker, but makes sense to keep it open to track when we fix the test setup. The underlying issue is tracked in https://github.com/kubernetes/kubernetes/issues/47882

**Comment by marun** [comment]
We're using 'approved-for-milestone' to indicate an issue is release blocking.   Removing...

**Comment by ericchiang** [comment]
The following tests are still failing on upgrade tests.

```
[k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [ReplicationController] should eagerly create replacement pod during network partition when termination grace is non-zero[k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [ReplicationController] should recreate pods scheduled on the unreachable node AND allow scheduling of pods on a node after it rejoins the cluster[k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [StatefulSet] should come back up if node goes down [Slow] [Disruptive]
```

https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster

Moving this issue to the 1.8 milestone. 

/cc @kubernetes/sig-cluster-lifecycle-bugs

Can someone please fix the test setup?

**Comment by pipejakob** [comment]
I'll try digging into this today.

**Comment by pipejakob** [comment]
I think this code might be causing some issues: 
https://github.com/kubernetes/kubernetes/blob/a755d3e5775defd83a6abc9f7fcad5cbb01d87f3/cluster/gce/gci/configure-helper.sh#L651-L656

In it, the kubeconfig file generated for kubelet to bootstrap with has two entries for `server:` at the same level. I'm not sure if one is supposed to override the other, but it seems wrong to have two entries here. After kubelet bootstraps and creates the new kubeconfig file, one of the entries is dropped, but I'm not sure if the choice is deterministic or not, and might just depend on our yaml implementation.

This was introduced in https://github.com/kubernetes/kubernetes/pull/40050, and might have just been a rebase mistake, so I'm following up with @mtaufen.

**Comment by mtaufen** [comment]
Yeah that looks like a rebase mistake to me. Let me take a look.

**Comment by mtaufen** [comment]
Though I'm surprised the signal for this is the network partition test, I'd expect something to fail much sooner than that if the kubeconfig were wrong...

In any case, I'll post a fix for the duplicate server field.

**Comment by mtaufen** [comment]
Aha, didn't notice this was for upgrade tests. New provisioning on the destination version likely the cause.
Fix in https://github.com/kubernetes/kubernetes/pull/50939

**Comment by pipejakob** [comment]
Even with @mtaufen's fix merged, it looks like we're still seeing upgrade test failures. I believe this has fixed the inconsistency reported in https://github.com/kubernetes/kubernetes/issues/47882, but there is probably a different root cause for the upgrade test failures.

**Comment by pipejakob** [comment]
The kubelet kubeconfig bug has been fixed, and I don't see any other problems with the cluster setup or the upgrade itself. There are still e2e test failures during the upgrade, but I think those should be investigated by the SIGs who own the feature areas.

Were you originally owning this, @foxish?

**Comment by mbohlool** [comment]
Is this the same failure as https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/212

If yes, can we please send a patch to 1.7 and disable this test as it is not a release blocker? I am going to increase the priority of this as it is a release blocker.

**Comment by ericchiang** [comment]
Bumping. These tests are still failing on two of our upgrade suites

https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-cluster-new
https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-cluster

cc @kubernetes/sig-apps-test-failures

**Comment by spiffxp** [comment]
friendly v1.8 release ping, does this issue need to be a release-blocker? does this issue need to be in the v1.8 milestone? is this issue actively being worked on?

**Comment by foxish** [comment]
Triaging and looking into it, will have an update by tomorrow.

**Comment by krzyzacy** [comment]
the wrong num nodes in network tests might be related to https://github.com/kubernetes/kubernetes/issues/50797

**Comment by apelisse** [comment]
Who is responsible for getting this issue resolved? Reading the comments, it looks like it's either @foxish or @krzyzacy 

I'll assign you and remove Janet

**Comment by foxish** [comment]
Most of the incidences of this failure have already been fixed. https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-cluster is the only place I can find this test failure. We should remove this from the 1.8 milestone.

**Comment by foxish** [comment]
Issues were fixed by @krzyzacy in https://github.com/kubernetes/test-infra/pull/4617. Will verify when the upgrade tests are back up and close issue.

**Comment by foxish** [comment]
Verified with one green run (https://k8s-testgrid.appspot.com/release-1.8-upgrade-skew#gke-gci-1.7-gci-1.8-upgrade-cluster-new&include-filter-by-regex=Network%20Partition). Closing.

**Comment by krzyzacy** [comment]
on https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/916 it failed in a different way (but the actual upgrade test failed as well (statefulset-upgrade and hpa-upgrade)which is more worrying)

**Comment by ericchiang** [comment]
Reopening. Adding to 1.8 because it's effecting our 1.8 branch upgrade tests

https://k8s-testgrid.appspot.com/release-1.8-upgrade-skew

Adding to the 1.8 milestone. We need to determine if this is release blocking or not.

**Comment by kow3ns** [comment]
https://k8s-testgrid.appspot.com/release-1.8-upgrade-skew looks like a timeout on heal from the partition 
 https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/916 looks like a cluster of failures not directly related to this issue.

**Comment by ericchiang** [comment]
We're starting to evaluate which test results should be removing from our release-blocking tests for 1.8 https://github.com/kubernetes/kubernetes/issues/53018

https://k8s-testgrid.appspot.com/release-1.8-upgrade-skew

The network partition tests have been red for the entire 1.8 cycle, and we even released 1.7 in the same state. I'm going to propose that we remove this issue from the 1.8 milestone, and skip these tests on our upgrade jobs until they can be made more reliable.

Does this reasonable?

**Comment by foxish** [comment]
These appear to have gone red on the 18th around a week ago. (https://k8s-testgrid.appspot.com/release-1.8-all#gce-1.7-1.8-upgrade-master&include-filter-by-regex=Pods%20should%20return%20to%20running%20and%20ready%20state). I think they were green mostly before that.

**Comment by foxish** [comment]
The failures appear to be correlated with a certain test-infra change - https://github.com/kubernetes/test-infra/compare/815c71336...f2361a2da
PTAL @krzyzacy

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/pull/4621

before that the upgrade did not happen, so you cannot count on those results. cc @krousey

**Comment by foxish** [comment]
Had a conversation with @krzyzacy. @ericchiang, that should be fine - the failures appear to be due to test setup issues.

**Comment by krzyzacy** [comment]
huh the test still have issues?

**Comment by jberkus** [comment]
What's the specific deliverable for these tests for 1.9?  I'm unclear on why this is in the 1.9 milestone.

**Comment by spiffxp** [comment]
@jberkus I added this to v1.9 because these test failures are still occurring in https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.8-master-upgrade-cluster-new

**Comment by kow3ns** [comment]
@spiffxp This should probably still not be a release blocker @foxish do you concur?

**Comment by ericchiang** [comment]
@kow3ns non-blocking, failing tests create a lot of overhead for the release team, particularly the test signal lead. If they're non-blocking, can they be disabled on upgrade tests until someone has a chance to fix them?

**Comment by kow3ns** [comment]
@foxish has WIP on #56416 which it appears this is a dup of. We should close one of these. We will likely remove these tests from Upgrade. They should not block release.

**Comment by jberkus** [comment]
If these tests are non-blocking, can this issue be removed from the milestone?  Thanks.

**Comment by spiffxp** [comment]
@jberkus until the tests are actually made non-blocking, or made passing, this issue must remain in the milestone, as the tests are (still) failing on release-blocking jobs

**Comment by jberkus** [comment]
@kow3ns @foxish Can we have a decision on this issue?  If it's not-blocking, you need to change the status of the tests as mentioned by @spiffxp above.

**Comment by foxish** [comment]
The tests are already disabled on master (https://github.com/kubernetes/kubernetes/pull/56790) and cherrypicked to the 1.8 branch (https://github.com/kubernetes/kubernetes/pull/56900).

**Comment by foxish** [comment]
The issue here is identical to https://github.com/kubernetes/kubernetes/issues/56416.

**Comment by enisoc** [comment]
Since this was classified as not a release-blocker, and we have disabled the tests in blocking jobs, I think we can remove it from the milestone.

**Comment by foxish** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/56787
