### ISSUE TITLE
Experiment run kubelet as docker container

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#4869]
We talked about running as much our components as docker container, but excluding both docker daemon and kubelet. Running kubelet as docker container is hard, especially with mount namespace; but we should experiment it and document what difficulties we have, and eventually work with our partners to solve those issues. 

cc/ @thockin

**Comment by zmerlynn** [comment]
+1!

**Comment by bgrant0607** [comment]
Why not mount the entire host filesystem as a volume inside the Kubelet's mount namespace?

cc @smarterclayton

**Comment by smarterclayton** [comment]
@pmorie is looking at this right - Paul has another issue open to propose a change to the way we mount so that we can do it from inside the container.  I think mounting the host into the Kubelet's namespace is valuable for a set of reasons, but there are some other implications as well.  Will let him respond / link to the relevant issue.

**Comment by vmarmol** [comment]
@bgrant0607 that's what we're thinking as well. All things will need to know to look for their expected paths in the special volume instead of their expected paths.

**Comment by pmorie** [comment]
Yep, I have something in the works now, will post later tonight.

**Comment by pmorie** [comment]
Opened #6848 to describe how we could modify the kubelet to allow mounts in the host mount namespace from a containerized kubelet.

**Comment by ghodss** [comment]
@dchen1107 Can kubelets now be run in a container?

**Comment by smarterclayton** [comment]
We've been running it - there appears to be a bug in boot2docker that causes mounts to be bound several times, and there's also some path fixes I haven't submitted upstream yet.  Also a few glitches with cadvisor.

**Comment by smarterclayton** [comment]
Try the getting started section here: https://github.com/openshift/origin/blob/master/README.md#Getting_Started

My patches are here https://github.com/openshift/origin/commit/f05b1a1e66b0a3aa79058f679389971e633fed89

**Comment by smarterclayton** [comment]
See https://github.com/GoogleCloudPlatform/kubernetes/pull/9976

**Comment by smarterclayton** [comment]
There are still known issues in boot2docker, paul was looking at them.

**Comment by sporkmonger** [comment]
FWIW, on CoreOS, exec-type liveness probes are seriously crippled without being able to run a kubelet in a container. You can't easily install stuff on a CoreOS host and there's an awful lot of utilities (e.g. `dig` or `nslookup`) that you might want to use in your probes that just aren't available when running from a CoreOS context. Running from a docker container solves that because you can set up your environment with whatever utilities you need for your probes.

**Comment by kelseyhightower** [comment]
@sporkmonger Makes a good point. I've been running the Kubelet under Docker for a few weeks now on CoreOS, but I have not push the install that hard. I have enjoyed the ability to drop the Kubelet in a larger OS container with the  extra utilities I find useful. I'm hoping longer term it will a supported use case for running the Kubelet in a container.

**Comment by smarterclayton** [comment]
Right now we've identified a blocker in Docker 1.7 - mount propagation mode
was set to PRIVATE, which means volumes can't be mounted.  At this point
we're considering carrying a patch for RHEL/Fedora/CentOS to allow SHARED,
but that won't help other OSes including boot2docker.

Paul is tracking this for now.

On Jul 1, 2015, at 6:51 PM, Kelsey Hightower <notifications@github.com>
wrote:

@sporkmonger <https://github.com/sporkmonger> Makes a good point. I've been
running the Kubelet under Docker for a few weeks now on CoreOS, but I have
not push the install that hard. I have enjoyed the ability to drop the
Kubelet in a larger OS container with the extra utilities I find useful.
I'm hoping longer term it will a supported use case for running the Kubelet
in a container.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/4869#issuecomment-117844666>
.

**Comment by ghodss** [comment]
@smarterclayton Is there a Docker issue where that issue is discussed/developing?

**Comment by smarterclayton** [comment]
Start here: https://github.com/docker/libcontainer/pull/632

On Jul 1, 2015, at 8:48 PM, Sam Ghods <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> Is there a Docker issue
where that issue is discussed/developing?

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/4869#issuecomment-117863556>
.

**Comment by pmorie** [comment]
There's a libcontainer PR in progress to create a knob that controls mount propagation modes on a container level:

https://github.com/opencontainers/runc/pull/77

However, it's not clear whether runc will be integrating into docker for 1.8.  I'll create an issue for pre-runc docker to cover upstream docker before runc is integrated.

**Comment by pmorie** [comment]
Created https://github.com/docker/docker/issues/14630 to cover this in pre-runc docker.

**Comment by fgrzadkowski** [comment]
I need a clarification here.

It seems that there is some support for running kubelet in a container by using ```nsenter``` to run mounting commands so that they are visible on the host.
@smarterclayton explained that the problem is that with docker 1.7 containers are run with mount propagation set to PRIVATE. However I don't understand why this results in ```nsenter``` mounter not working any more. If we mount something in the host namespace this should still work, right? What am I missing?

I also experimented with running ```mount --make-rshard /``` just before running running kubelet in a container. This fixed the problem with mounting kubernetes volumes. However I'm worried that now all mounts from any pod/container (not only kubelet) will be propagated to host. Or would this require explicitly mounting ```/``` as a docker volume to the container and running as ```--priviliged```? I need to verify that.

Any comments appreciated!

@eparis

**Comment by fgrzadkowski** [comment]
@smarterclayton @pmorie Can you guys please explain why using ```nsenter``` is not sufficient with docker 1.7?

**Comment by smarterclayton** [comment]
My understanding was that docker mounts containers in its own private
special namespace now, so even when you mount on the host, dockers
namespace for containers is a child and doesn't inherit.  I think your fix
made it so that they do.  Is it easy to get that workaround in code and
doesn't have bad side effects (Eric?)?  If so that's something we can
definitely use.

On Aug 25, 2015, at 2:47 PM, Filip Grzadkowski <notifications@github.com>
wrote:

I need a clarification here.

It seems that there is some support for running kubelet in a container by
using nsenter to run mounting commands so that they are visible on the host.
@smarterclayton <https://github.com/smarterclayton> explained that the
problem is that with docker 1.7 containers are run with mount propagation
set to PRIVATE. However I don't understand why this results in nsenter
mounter not working any more. If we mount something in the host namespace
this should still work, right? What am I missing?

I also experimented with running mount --make-rshard / just before running
running kubelet in a container. This fixed the problem with mounting
kubernetes volumes. However I'm worried that now all mounts from any
pod/container (not only kubelet) will be propagated to host. Or would this
require explicitly mounting / as a docker volume to the container and
running as --priviliged? I need to verify that.

Any comments appreciated!

@eparis <https://github.com/eparis>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/4869#issuecomment-134683399>
.

**Comment by fgrzadkowski** [comment]
Unfortunately ```mount --make-rshard /``` did not help :( I didn't check this carefully enough yesterday.

AFAIU namespace is created right before container is started as part of the initialization. If that's the case what namespace does it clone? I'd expect that docker daemon runs in the hosts main namespace and thus the newly created namespace should inherit any mounts from the moment of the namespace creation. What am I missing?

@rootfs Do I understand correctly how mount namespace work?

**Comment by rootfs** [comment]
@fgrzadkowski 

* docker daemon creates a new mount namespace (NEWNS) for containers.
* container's rootfs is [rprivate](https://github.com/opencontainers/runc/blob/master/libcontainer/rootfs_linux.go#L407), [by default] https://github.com/docker/docker/blob/master/daemon/execdriver/driver_unix.go#L40. That's why even you bind mount `/:/host`, you still cannot propagate mount to host namespace.

**Comment by fgrzadkowski** [comment]
@rootfs Let's consider the following scenario:

1. Kubelet (running in container) mounts a device in host mount namespace using ```nsenter``` (does that work with rootfs propagation flag set to rprivate?)
2. Kubelet (running in container) starts another container
3. Docker creates mount namespace using clone(2) with CLONE_NEWNS (right?); all current mounts (including the new one from (1)) are visible in the new namespace
4. New container can use mounted device

Is this something that would work?

**Comment by rootfs** [comment]
@fgrzadkowski that's a very tall test list :) 

If you want to mount a filesystem and have mount helper in **host's** `/sbin/` (because you `nsenter` into host's mount namespace), these steps should work. But if these mount helpers are not on **host**, then you cannot mount the device in the first step.

**Comment by fgrzadkowski** [comment]
@rootfs Thanks a lot for explanations!

@smarterclayton Based on the explanations from @rootfs my understanding is that mounting things like secrets should work (it's just tmpfs, so mount helpers are definitely in host's ```/sbin/```). However when I just run kubelet from the hyperkube (as instructed [here](http://kubernetes.io/v1.0/docs/getting-started-guides/docker.html)) mounting secrets does not work. Is it needed to enable this nsenter mounter somehow?

**Comment by smarterclayton** [comment]
Yes, the Kubelet needs the run containerized flag.

On Wed, Aug 26, 2015 at 4:34 PM, Filip Grzadkowski <notifications@github.com
> wrote:

> @rootfs <https://github.com/rootfs> Thanks a lot for explanations!
>
> @smarterclayton <https://github.com/smarterclayton> Based on the
> explanations from @rootfs <https://github.com/rootfs> my understanding is
> that mounting things like secrets should work (it's just tmpfs, so mount
> helpers are definitely in host's /sbin/). However when I just run kubelet
> from the hyperkube (as instructed here
> <http://kubernetes.io/v1.0/docs/getting-started-guides/docker.html>)
> mounting secrets does not work. Is it needed to enable this nsenter mounter
> somehow?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/4869#issuecomment-135147720>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by fgrzadkowski** [comment]
@dchen1107 @brendandburns This issue is a blocker for fixing docker based setup. My understanding is that we agreed that we should simplify setting up new clusters and that docker based setup is the way to go. If that's the case I believe we should bump the priority for this issue to P1. WDYT?

Also reassigning to myself.

**Comment by pmorie** [comment]
@fgrzadkowski Was combing through issues and just wanted to record for posterity what the outcome was here.  I believe that on your docker distribution, the container's mount namespace has a private propagation mode and so the mount point created by the kubelet doesn't propagate into the kubelet container's mount namespace, and so the kubelet winds up writing the secret data to the wrong mountpoint.  Is that accurate?

**Comment by fgrzadkowski** [comment]
@pmorie Yes, I believe I explained in some other issue. Thanks for summarising it.

@dchen1107 @brendandburns Do you agree with bumping up priority to P1?

**Comment by fgrzadkowski** [comment]
This week I've came up with a relatively simple workaround that should fix the problem with kubelet mounting problem when run in a container.

Until now we've been changing code here and there to use ```nsenter --mount``` in case of ```--containerized``` flag. However we can just run the whole kubelet using the same technique. Instead of running:
```
/kubelet <arguments> --containerized
```
we can have a simple script ```kubelet-runner.sh``` with the following content:
```
#!/bin/bash

# This will run kubelet outside of the container (in host namespaces) and will
# exit when kubelet exits with the same error code.
nsenter --target=1 --mount -- chroot . /kubelet $@
```
That way we change mount namespace to host.

I've checked that this works in a basic scenario. I'll run e2e tests today and if this works I'll send PRs fixing docker based setups.

@brendandburns @dalanlan @roberthbailey @mikedanese

**Comment by luxas** [comment]
@fgrzadkowski Sounds great! How much code is just for `--containerized`? Is it just the `nsenter` code?

@pmorie Is this issue fixed in `docker 1.9.1` (to specify propagation mode)

**Comment by fgrzadkowski** [comment]
@luxas There are at least few classes (so probably few hundreds of lines with tests), but I never managed to fix all the problems. Regarding ```docker 1.9.1``` and mount propagation mode it is not fixed yet. They moved it to docker 1.10.

**Comment by luxas** [comment]
@fgrzadkowski OK, thanks. Just say if there is something I can do to help

**Comment by pmorie** [comment]
I will post something here when we have a date for when the mount propagation control will be released in docker.

**Comment by luxas** [comment]
@pmorie As I understand it, docker has merged the required code for this and will be available in `1.10`
Ref: #18776 
So this will be easier in the future

**Comment by gravis** [comment]
@pmorie Docker 1.10 is out

**Comment by zreigz** [comment]
I have been using Ubuntu 15.10 with docker 1.10.2. I've tested docker-multinode solution and I did't notice any mount problem. I checked logs from my journalctl and doesn't show errors for docker. I've created some pods from example directory and I added kubernetes dashboard to cluster and everything works fine.

**Comment by fgrzadkowski** [comment]
Can you post command that you've used to start kubelet in docker?

**Comment by fgrzadkowski** [comment]
How did you verify mounts? What kind of volumes have you used for this?

**Comment by zreigz** [comment]
I've just execute this script: https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/master.sh without any modification. When master was created I started adding pods and checked journalctl logs if there are errors for docker

**Comment by fgrzadkowski** [comment]
In your example some volumes doesn't work, e.g. Downward API (and many others). We hacked some volumes (e.g. Secrets and Service Accounts), but not all of them.

You need to:
1. Remove `--containerized` flag to disable hack that we introduced
2. Add `:slave` (or some other option) to docker volumes mounted to kubelet container - you need at least `/var/log/kubelet` (and maybe more)
3. Remove `/rootfs` docker volume

Once you start the cluster you need to try different volume types and see if you can use them from inside a pod.

**Comment by zreigz** [comment]
Thanks for comments. I will try this. To be 100% sure (because I am rookie in this subject )
After modification which you mentioned I should create some pod with volume.
For example:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    # This GCE PD must already exist.
    gcePersistentDisk:
      pdName: my-data-disk
      fsType: ext4
```
 Description about it I can find probably here: http://kubernetes.io/v1.0/docs/user-guide/volumes.html
Am I right?

**Comment by fgrzadkowski** [comment]
Looks good. Please also test other volumes (e.g. Downard API, Secrets, EmptyDir).

**Comment by zreigz** [comment]
Thanks for explanation. Now everything is clear for me. No more questions.

**Comment by zreigz** [comment]
I've made all necessary modifications. It looks like this
```
    # Start kubelet and then start master components as pods
    docker run \
        --net=host \
        --pid=host \
        --privileged \
        --restart=on-failure \
        -d \
        -v /sys:/sys:ro \
        -v /var/run:/var/run:rw \
        -v /var/lib/docker/:/var/lib/docker:rw \
        -v /var/lib/kubelet/:/var/lib/kubelet:slave \
        gcr.io/google_containers/hyperkube-${ARCH}:v${K8S_VERSION} \
        /hyperkube kubelet \
            --address=0.0.0.0 \
            --allow-privileged=true \
            --enable-server \
            --api-servers=http://localhost:8080 \
            --config=/etc/kubernetes/manifests-multi \
            --cluster-dns=10.0.0.10 \
            --cluster-domain=cluster.local \
            --v=2
```
I've tested few types of volumes. The result is:
emptyDir - works
hostPath - works
Downward API - fails (kubectl shows pod but container doesn't exist after command *docker ps*)
Secrets - fails (kubectl shows creating status all the time and container not created in docker)

**Comment by mikedanese** [comment]
/var/lib/kubelet should probably not be slave. I think it should be shared or rshared.

**Comment by pmorie** [comment]
@mikedanese is right, it should be shared, rshared shouldn't be necessary.

**Comment by zreigz** [comment]
When I make it shared or rshared then I have error:
```
docker: Error response from daemon: Cannot start container a6c3c3d5bee8296fe224c04f74a3fe549bed2d29bd361b61f6f4480bbc9d9669: Path /var/lib/kubelet is mounted on / but it is not a shared mount. 
```
and master is not started

**Comment by mikedanese** [comment]
Before running the docker command run:
```
mount --bind /var/lib/kubelet /var/lib/kubelet
mount --make-shared /var/lib/kubelet
```

**Comment by zreigz** [comment]
Ok thanks. I will try it

**Comment by zreigz** [comment]
I also have error
```
docker: Error response from daemon: Cannot start container 631a120c97a5f402853c02c21742c405e472d049d1e6bb63440631aae8cdf411: Path /var/lib/kubelet is mounted on /var/lib/kubelet but it is not a shared mount..
```
When I execute command:
```
mount | column -t
```
I have
```
/dev/mapper/ubuntu--vg-root  on  /var/lib/kubelet                 type  ext4             (rw,relatime,errors=remount-ro,data=ordered)
```

It looks like a error ```errors=remount-ro```

**Comment by luxas** [comment]
See here why we need a `shared` mount: https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt
I have this working on my Pis as well.

@zreigz You need to reset `MountFlags=` if you're using `systemd`. Then it'll work.
openshift/origin#3072

**Comment by zreigz** [comment]
Good news. It started working when I left empty ```MountFlags=``` for docker service  I've tested:
hostPath - works
Downward API - works
Secrets - works

**Comment by luxas** [comment]
Yeah, I haven't hit any issues so far either

**Comment by smarterclayton** [comment]
We've done a fair amount of testing as well in different modes.  Haven't
hit anything yet.

**Comment by tdeheurles** [comment]
To be up to date, the latest is:
```console
$ ARCH="amd64"
$ K8S_VERSION="1.2.0-alpha.8"
$ mount --bind /var/lib/kubelet /var/lib/kubelet
$ mount --make-shared /var/lib/kubelet
$ docker run -d \
        --net=host \
        --pid=host \
        --privileged \
        -v /sys:/sys:ro \
        -v /var/run:/var/run:rw \
        -v /var/lib/docker/:/var/lib/docker:rw \
        -v /var/lib/kubelet/:/var/lib/kubelet:rshared \
        gcr.io/google_containers/hyperkube-${ARCH}:v${K8S_VERSION} \
        /hyperkube kubelet \
            --address=0.0.0.0 \
            --allow-privileged=true \
            --enable-server \
            --api-servers=http://localhost:8080 \
            --config=/etc/kubernetes/manifests-multi \ 
            --cluster-dns=10.0.0.10 \
            --cluster-domain=cluster.local \
            --v=2
```

- The `1.2*` hyperkube have etcd and kube-proxy in the manifests folder, so they are automatically started. 
- We then need to manually starts the different addon manually.

**Comment by huggsboson** [comment]
@tdeheurles I had to do the following to get it working
```bash
mount --make-rshared /var/lib/kubelet
```
Note: rshared

**Comment by tdeheurles** [comment]
@mikedanese was pointing to `mount --make-shared /var/lib/kubelet`.

Kubernetes seems to start well with the command I resumed from the other post but I didn't have time to test the cluster ... I don't really understand that part sorry ...

**Comment by luxas** [comment]
`rshared` isn't required. It works with just `-v /var/lib/kubelet:/var/lib/kubelet:shared` and `mount --make-shared /var/lib/kubelet`. 
@tdeheurles Please update your previous comment and note that when using systemd, `docker.service` should reset `MountFlags=` (defaults to `shared`, but docker sets it by default to `MountFlags=slave` [here](https://github.com/docker/docker/blob/master/contrib/init/systemd/docker.service))

**Comment by tdeheurles** [comment]
@luxas it's done. 

I propose to add a readme in the [hyperkube folder](https://github.com/kubernetes/kubernetes/tree/master/cluster/images/hyperkube) in order to have the comment up to date. 
I'll add a link to this issue in it too.

**Comment by luxas** [comment]
It should be mostly documented elsewhere: `docker.md` in the docs is a good place to put that in. There is also a `turnup.sh` script.

**Comment by huggsboson** [comment]
I notice that the turnup script and docs still have: /:/rootfs:ro and --containerized.  I assume we're good getting rid of these.

**Comment by pmorie** [comment]
@huggsboson the mount to /rootfs is also used by cadvisor, but --containerized is only relevant for switching the mounter impl.

**Comment by luxas** [comment]
... and we have to keep backwards-compability. Sadly.

**Comment by pmorie** [comment]
@luxas always :)

**Comment by huggsboson** [comment]
So we should keep /:/rootfs in there?  Or do we not run cadvisor as part of the containerized kubelet?  Sorry I'm not as familiar with cadvisor as I should be.

**Comment by luxas** [comment]
`cAdvisor` is a must, but I haven't encountered any problems although I removed `/:/rootfs`.
@pmorie Do you have any code I could look at for curiousity?

**Comment by pmorie** [comment]
@luxas I don't readily, but I could be mistaken.  Let me do a little digging and get back to you.

**Comment by deromka** [comment]
If the things are working properly now, could you please push your changes, so we all can enjoy it?
I do not know, if it is related, but I cannot make the SkyDNS work, I have opened a new issue here:https://github.com/kubernetes/kubernetes/issues/23111

**Comment by tdeheurles** [comment]
I can't confirm that everything is working (volume sharing in mind) but the core services and dns are fine on docker with v1.2.0. I'm using [this setup](https://github.com/kubernetes/kubernetes/issues/4869#issuecomment-194149162) on top of a docker-toolbox on windows.

**Comment by huggsboson** [comment]
This is the setup that I've been using with Docker 1.10.3 via docker-machine on a macbook.  Note I've been using --containerized and the /var/lib/kubelet:rw instead of doing all of the bind mounts and make-shareds.  https://github.com/huggsboson/docker-compose-kubernetes

**Comment by luxas** [comment]
@huggsboson `--containerized` works for the most things thanks to @fgrzadkowski. I'm using it too in kubernetes-on-arm. However, it's a hack and has limitations, so it's best to migrate if you're lucky enough to have `docker-1.10`

**Comment by huggsboson** [comment]
Now that I have a reproducible up and down script I just changed it to do the mounting and the /var/lib/kubelet:shared and everything seems to be working correctly.   My test run is usually stop it, start it, start a debian image with curl, then do:
curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes/

Then repeat the pattern a few times.

**Comment by fgrzadkowski** [comment]
@huggsboson I assume you don't pass `--containerized` flag? Can you also test other APIs? Downard API might be a good example as it shouldn't work with `--containerized` and should work with shared docker volumes.

**Comment by huggsboson** [comment]
@fgrzadkowski I have it so I can run with either --containerized (and /var/lib/kubelet:rw) or without --containerized (and /var/lib/kubelet:shared).  I did a test of --containerized first with docker 1.10.3 and kube 1.2 with the downward api, like so:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: downward-api
  namespace: default
spec:
  containers:
  - name: debian
    image: tutum/curl:trusty
    command:
      - sleep
      - "3600"
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  restartPolicy: Always
```

env produced:
```
$ kubectl exec downward-api -ti -- bash -il
HOSTNAME=downward-api
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT=tcp://10.0.0.1:443
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_HOST=10.0.0.1
MY_POD_NAMESPACE=default
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MY_POD_NAME=downward-api
PWD=/
MY_POD_IP=172.17.0.3
SHLVL=1
HOME=/
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1
KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443
_=/usr/bin/env
```

**Comment by fgrzadkowski** [comment]
Sweet! We need to document this in docker.md and multinode instructions.

**Comment by huggsboson** [comment]
@fgrzadkowski  I'll work on updating the docks, but I still haven't found a test case where --containerized fails and mount --make-shared doesn't.  Downward API worked for --containerized.  Do you have any other cases that are likely to fail?

**Comment by batikanu** [comment]
I was experimenting the docker provisioning and encountered a problem with heapster. The heapster works properly and collects the metrics for pods with --containerized flag solution. Without containerized flag it has only node metrics but not pod metrics. I tested the both options on the same environment. Is there anyone who has already checked heapster without --containerized flag (shared volumes) solution?

**Comment by luxas** [comment]
Kubernetes on ARM (https://github.com/luxas/kubernetes-on-arm) is using shared volumes, and heapster does collect stats for pods.
I think you should change `--source=kubernetes.summary_api:''` to `--source=kubernetes`. 
Maybe it's summary api that isn't working?

**Comment by fgrzadkowski** [comment]
@luxas I'd be surprised if one API works and the other doesn't as they are using exactly the same solution underneath. @timstclair

**Comment by batikanu** [comment]
I'm using this https://github.com/kubernetes/heapster/tree/master/deploy/kube-config/standalone
I removed http part of the parameter like --source=kubernetes still doesn't work with shared volumes but works with --containerized. I can only see cluster metrics but not for pods. If it is the api , then I shouldn't see any metrics at all right? Perhaps, kubelet just doesn't receive or send  pod metrics. I don't see any error log (in heapster and kubelet) though. Cadvisor is working properly. I tested in docker v1.11, v.1.10 and v1.9.1 with base image centos7 no change.

**Comment by fgrzadkowski** [comment]
@batikanu Please call summary/cadvisor API directly from the command line and check what is being reported there. If you see something wrong there, let's continue the discussion here. Otherwise please file a separate issue as it'd be a heapster bug.

**Comment by charleschen** [comment]
im using the kubernetes configuration above and i get this error when the pod is trying to mount

**Comment by charleschen** [comment]
im using the kubernetes configuration above and i get this error when the node is trying to mount a volume for the pod:

  4s	4s	1	{kubelet cdg}		Warning	FailedSync	Error syncing pod, skipping: Mount failed: exit status 127
Mounting arguments: 172.16.1.3:/scratch/kubernetes/redis /var/lib/kubelet/pods/58bf6b90-074c-11e6-851b-80ee73a91f54/volumes/kubernetes.io~nfs/nfs nfs []
Output: /sbin/mount.nfs: error while loading shared libraries: libtirpc.so.1: cannot open shared object file: No such file or directory

anyone else ran into the same issue?

**Comment by charleschen** [comment]
so if i install nfs-common from apt-get in container running kublete, the mount will go through.  This isn't ideal, am i doing something wrong in the setup?

im using K8S_VERSION="1.2.2"

**Comment by batikanu** [comment]
One update, I managed to make it work with docker v1.10.3. The problem is caused by the new docker version v1.11.0. In this version cadvisor summary returns correct list but  kubelet_api/stats/summary can't retrieve pod list. I think the problem might be in kubelet since the v.1.11.0 is not yet supported by k8s.

**Comment by timstclair** [comment]
@batikanu FYI, that should be fixed by https://github.com/kubernetes/kubernetes/pull/24113.

**Comment by luxas** [comment]
@charleschen That's expected, because the `hyperkube` image hasn't all things installed, and only supports `emptyDir`, `hostPath`, `gitRepo` and maybe some other volume plugin.
However, if we think it's worth it, we could add `nfs-common` to the list of packages to install
cc @vishh

**Comment by vishh** [comment]
IIRC, @pmorie was looking into dynamically pulling in volume dependencies on-demand..

**Comment by pmorie** [comment]
What I would like to be able to do is containerize all mount operations so we can package fs drivers as containers and avoid dependencies on the host at all

**Comment by colemickens** [comment]
When is `--containerized` no longer needed to be passed to `kubelet`? Can it be removed when `/var/lib/kubelet` is mounted as `shared`? Just making sure it doesn't require a specific version of `docker` or anything else.

**Comment by huggsboson** [comment]
I've been running 1.2 with var lib kubelet mounted shared for a while.  configMap doesn't work with --containerized in docker 1.10.3.  I'm not sure how things look in 1.3.

**Comment by smarterclayton** [comment]
What's the failure with config map?

**Comment by huggsboson** [comment]
I didn't dig in to deeply, just that the expected files didn't appear.  This is docker 1.10.3 via docker-machine on os x.

**Comment by huang195** [comment]
Is it correct to summarize that if I'm using Kube 1.3+ with Docker 1.10, I can run a kubelet inside of a container without passing the `--containerized` flag?

**Comment by huggsboson** [comment]
I was doing it with 1.2 with docker 1.10.3, but you need to make sure you're running kubelet with /var/lib/kubelet mounted as shared.  With 1.3 I think a lot of things have changed with the hyperkube image so I'm less sure about things.

**Comment by chenzhiwei** [comment]
@huggsboson @huang195  Hi I am using Kubelet in `Kubernetes on Mesos` cluster. I create some PodSpec files of k8s/Mesos components and Kubelet acts as these Pods' supervisor. (Kubelet only start/monitor the Pods, it does not provide service)

In this case, I started Kubelet in container by using following command:

```
docker run -d --privileged --net=host --pid=host \
    -v /:/rootfs:ro \
    -v /sys:/sys:ro \
    -v /var/run:/var/run \
    -v /var/lib/kubelet:/var/lib/kubelet \
    -v /etc/kubernetes:/etc/kubernetes \
    gcr.io/google_containers/hyperkube-amd64:v1.3.0 /hyperkube kubelet \
    --allow-privileged=true \
    --enable-server=false \
    --hostname-override=127.0.0.1 \
    --config=/etc/kubernetes/pods \
    --containerized \
    --v=2 \
    --healthz-port=0 \
    --read-only-port=0 \
    --cadvisor-port=0
```

The directory `/etc/kubernetes/pods` contains PodSpec files such as k8s-apiserver, k8s-scheduler...

It works well, and I also tested start Kubelet as a bare process, they have almost the same CPU/Memory usage.

Do you know if there are some potential issues? Is it ok to use Kubelet only as Pod's supervisor?

Thanks.

**Comment by huang195** [comment]
@chenzhiwei you need to create pods that attach to different types of storage volumes to fully test this out. I don't think you will be using docker earlier than 1.10, so my understanding is you shouldn't need to pass in the `--containerized` flag. BTW, `--containerized` is not the same as `--containerized=true`, as the default value of this flag is actually `false`. 

@pmorie @fgrzadkowski can you help confirm if this is correct in the current state of the code?

**Comment by chenzhiwei** [comment]
@huang195 Actually `--containerized` and `--containerized=true` are same. My docker version is 1.11.2.

**Comment by cheld** [comment]
What is the status of this issue?

In my understanding:
- shared mounting is working 
- fs driver is still a problem. Maybe containerizing https://github.com/kubernetes/kubernetes/issues/4869#issuecomment-213581040. Is there a separate issue or PR?
- garbage collection is open (I have not checked myself) https://github.com/kubernetes/kubernetes/issues/14403


Anything else?

**Comment by philips** [comment]
cc @aaronlevy @derekparker @pbx0

**Comment by pbx0** [comment]
CoreOS ships with a script for running the kubelet inside a rkt-fly container (chroot isolation only).  Similarly, we mount in the needed folders required to work with the container runtime installed on the host.

You can see our script here: https://github.com/coreos/coreos-overlay/blob/master/app-admin/kubelet-wrapper/files/kubelet-wrapper

While this works for us now, this isn't a perfect solution to the larger problem where say you want a privileged container that:
1) Carries it own dependancies when possible
2) Can still shell out to on host binaries

The reason for this is that on-host binaries often depend on dynamic libraries or folders inside the host view of the filesystem while the container binaries depend on libraries or folders inside the chroot. So you have to bind-mount in all the dependancies and hope you don't end up bind-mounting over something inside the chroot that was needed for something else.

As a result, we are interested in making the kubelet a stand-alone container as much as possible and depend on the host filesystem as little as possible. One next step we'd like to experiment with is shipping docker inside the kubelet container itself. Ideally, it would be some kind of side-car container concept so someone could select which runtime version to use. We are also interested in efforts such as: https://github.com/kubernetes/kubernetes/issues/26093

**Comment by philips** [comment]
See the kubelet chroot proposal https://github.com/kubernetes/community/pull/131
