### ISSUE TITLE
kubelet stops posting NodeOutOfDisk condition while scheduler is still checking

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#50058]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: 

Scheduler is still [checking `NodeOutOfDisk` condition](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L796-L822), which was already deprecated and removed from kubelet in #48846.

**What you expected to happen**: Scheduler should check `NodeDiskPressure` condition instead, or kubelet should keep posting `NodeOutOfDisk` condition.

**How to reproduce it (as minimally and precisely as possible)**:

From [ci-kubernetes-e2e-gce-etcd3](https://k8s-testgrid.appspot.com/google-gce#gce-etcd3&width=5&sort-by-flakiness=), many tests (especially "Networking [k8s.io] Granular Checks: XXX") flake a lot because of [test pods couldn't be scheduled](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-etcd3/13400?log#log):
```
I0802 14:16:38.670] Aug  2 14:16:15.621: INFO: At 2017-08-02 14:10:47 +0000 UTC - event for netserver-2: {default-scheduler } FailedScheduling: No nodes are available that match all of the following predicates: MatchNodeSelector (2).
```

Checked [the scheduler logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-etcd3/13400/artifacts/bootstrap-e2e-master/kube-scheduler.log) and found scheduler kept ignoring node with `OutOfDiskCondition=Unknown`:
```
I0802 14:10:20.033375       5 factory.go:786] About to try and schedule pod ss2-2
I0802 14:10:20.033406       5 scheduler.go:255] Attempting to schedule pod: e2e-tests-statefulset-hq416/ss2-2
I0802 14:10:20.035150       5 factory.go:808] Ignoring node bootstrap-e2e-minion-group-5734 with OutOfDisk condition status Unknown
I0802 14:10:20.035177       5 factory.go:817] Ignoring node bootstrap-e2e-master since it is unschedulable
I0802 14:10:20.038957       5 factory.go:1000] Attempting to bind ss2-2 to bootstrap-e2e-minion-group-8l5l
I0802 14:10:20.050075       5 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-statefulset-hq416", Name:"ss2-2", UID:"513edd40-778c-11e7-8879-42010a800002", APIVersion:"v1", ResourceVersion:"11216", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned ss2-2 to bootstrap-e2e-minion-group-8l5l
I0802 14:10:20.461063       5 leaderelection.go:199] successfully renewed lease kube-system/kube-scheduler
I0802 14:10:22.285111       5 factory.go:786] About to try and schedule pod redis-master-w47l3
I0802 14:10:22.285164       5 scheduler.go:255] Attempting to schedule pod: e2e-tests-kubectl-vbz9w/redis-master-w47l3
I0802 14:10:22.285185       5 factory.go:817] Ignoring node bootstrap-e2e-master since it is unschedulable
I0802 14:10:22.285193       5 factory.go:808] Ignoring node bootstrap-e2e-minion-group-5734 with OutOfDisk condition status Unknown
I0802 14:10:22.287388       5 factory.go:1000] Attempting to bind redis-master-w47l3 to bootstrap-e2e-minion-group-c2c0
I0802 14:10:22.299202       5 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-kubectl-vbz9w", Name:"redis-master-w47l3", UID:"52967b38-778c-11e7-8879-42010a800002", APIVersion:"v1", ResourceVersion:"11237", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned redis-master-w47l3 to bootstrap-e2e-minion-group-c2c0
I0802 14:10:22.475869       5 leaderelection.go:199] successfully renewed lease kube-system/kube-scheduler
I0802 14:10:22.522684       5 factory.go:786] About to try and schedule pod pd-client
I0802 14:10:22.522710       5 scheduler.go:255] Attempting to schedule pod: e2e-tests-volume-l5kf0/pd-client
I0802 14:10:22.522729       5 factory.go:808] Ignoring node bootstrap-e2e-minion-group-5734 with OutOfDisk condition status Unknown
I0802 14:10:22.522755       5 factory.go:817] Ignoring node bootstrap-e2e-master since it is unschedulable
...
I0802 14:13:52.962378       5 factory.go:786] About to try and schedule pod ss2-2
I0802 14:13:52.962425       5 scheduler.go:255] Attempting to schedule pod: e2e-tests-statefulset-llw0r/ss2-2
I0802 14:13:52.962445       5 factory.go:817] Ignoring node bootstrap-e2e-master since it is unschedulable
I0802 14:13:52.962453       5 factory.go:808] Ignoring node bootstrap-e2e-minion-group-5734 with OutOfDisk condition status Unknown
I0802 14:13:52.965084       5 factory.go:1000] Attempting to bind ss2-2 to bootstrap-e2e-minion-group-c2c0
I0802 14:13:52.983876       5 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-statefulset-llw0r", Name:"ss2-2", UID:"d02945f2-778c-11e7-8879-42010a800002", APIVersion:"v1", ResourceVersion:"14604", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned ss2-2 to bootstrap-e2e-minion-group-c2c0
I0802 14:13:53.681980       5 factory.go:786] About to try and schedule pod netserver-2
I0802 14:13:53.682007       5 scheduler.go:255] Attempting to schedule pod: e2e-tests-pod-network-test-l1hrr/netserver-2
I0802 14:13:53.682028       5 factory.go:817] Ignoring node bootstrap-e2e-master since it is unschedulable
I0802 14:13:53.682036       5 factory.go:808] Ignoring node bootstrap-e2e-minion-group-5734 with OutOfDisk condition status Unknown
I0802 14:13:53.682195       5 scheduler.go:167] Failed to schedule pod: e2e-tests-pod-network-test-l1hrr/netserver-2
I0802 14:13:53.682245       5 factory.go:932] Unable to schedule e2e-tests-pod-network-test-l1hrr netserver-2: no fit: No nodes are available that match all of the following predicates: MatchNodeSelector (2).; waiting
I0802 14:13:53.682289       5 factory.go:1009] Updating pod condition for e2e-tests-pod-network-test-l1hrr/netserver-2 to (PodScheduled==False)
I0802 14:13:53.682338       5 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-pod-network-test-l1hrr", Name:"netserver-2", UID:"61a8b960-778c-11e7-8879-42010a800002", APIVersion:"v1", ResourceVersion:"11659", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' No nodes are available that match all of the following predicates: MatchNodeSelector (2).
I0802 14:13:53.683567       5 backoff_utils.go:78] Backing off 1m0s
```

Haven't traced down why this `OutOfDisk=Unknown` only appeared on part of the nodes && in the middle of test, but it seems certainly problematic.

**Anything else we need to know?**:

This seems to be one of the causes that increase `pull-kubernetes-e2e-gce-etcd3`'s flakyness.

/sig node

@dashpole @fejta

**Comment by dashpole** [comment]
fixed via #49841

**Comment by MrHohn** [comment]
@dashpole Awesome, thanks!

**Comment by dims** [comment]
@dashpole @MrHohn - i still see this problem, for example from a run this morning in:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/39587/pull-kubernetes-e2e-gce-etcd3/44825/artifacts/e2e-44825-master/kube-scheduler.log

Found that when looking at failed "Granular Check" problem in:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49501/pull-kubernetes-e2e-gce-etcd3/44858#k8sio-networking-k8sio-granular-checks-pods-should-function-for-intra-pod-communication-udp-conformance

```
I0803 13:23:50.076190       5 factory.go:808] Ignoring node e2e-44858-minion-group-chqj with OutOfDisk condition status Unknown
I0803 13:23:50.076608       5 scheduler.go:167] Failed to schedule pod: e2e-tests-pod-network-test-331ck/netserver-3
```

**Comment by dashpole** [comment]
From the kube-controller-manager logs: 
`node e2e-44858-minion-group-chqj hasn't been updated for 40.355367156s. Last OutOfDisk is: &NodeCondition{Type:OutOfDisk,Status:False,LastHeartbeatTime:2017-08-03 13:13:30 +0000 UTC,LastTransitionTime:2017-08-03 13:07:03 +0000 UTC,Reason:KubeletHasSufficientDisk,Message:kubelet has sufficient disk space available,}`

It looks like my fix #49841 does not correctly update timestamps.  Ill see if I can figure out why.

**Comment by dashpole** [comment]
But it also stopped posting MemoryPressure condition?
`node e2e-44858-minion-group-chqj hasn't been updated for 47.760436543s. Last MemoryPressure is: &NodeCondition{Type:MemoryPressure,Status:Unknown,LastHeartbeatTime:2017-08-03 13:13:30 +0000 UTC,LastTransitionTime:2017-08-03 13:14:15 +0000 UTC,Reason:NodeStatusUnknown,Message:Kubelet stopped posting node status.,}`
`node e2e-44858-minion-group-chqj hasn't been updated for 47.76046591s. Last DiskPressure is: &NodeConditiom`

Possibly a panic or something?

**Comment by sjenning** [comment]
This is the more general "node fails to report status" issue yes?  The node doesn't report status within `node-monitor-grace-period` and the node controller changes all the node conditions to Unknown.

@dashpole are you working to remove the `OutOfDisk` condition from the scheduler?

**Comment by dashpole** [comment]
Yes.   I will remove the OutOfDisk condition from the scheduler.  The node should still report the OutOfDisk condition for two releases (to accommodate version skew), so this problem is with reporting.

**Comment by dashpole** [comment]
Found the bug.  In my original fix: #49841, I [created a new NodeCondition object](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L869), and then assigned the LastHeartbeatTime of that new object.  However, changes to this new object were never reflected in the underlying list of nodes, so no update was made.  #50103 fixes this.
