### ISSUE TITLE
Nodes with DiskPressure=True while using low disk space/inodes

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kubernetes#52336]
/kind bug

**What happened**:
Kubernetes getting into state DiskPressure=True and evicting pods but I can't identify high usage of nodefs, neither disk space or inodes:

```
Conditions:
  Type			Status	LastHeartbeatTime			LastTransitionTime			ReasonMessage
  ----			------	-----------------			------------------			-------------
  NetworkUnavailable 	False 	Mon, 11 Sep 2017 16:53:09 -0300 	Mon, 11 Sep 2017 16:53:09 -0300 	RouteCreated 			RouteController created a route
  OutOfDisk 		False 	Tue, 12 Sep 2017 09:03:34 -0300 	Mon, 11 Sep 2017 16:53:07 -0300 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Tue, 12 Sep 2017 09:03:34 -0300 	Mon, 11 Sep 2017 16:53:07 -0300 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  DiskPressure 		True 	Tue, 12 Sep 2017 09:03:34 -0300 	Tue, 12 Sep 2017 09:01:13 -0300 	KubeletHasDiskPressure 		kubelet has disk pressure
  Ready 		True 	Tue, 12 Sep 2017 09:03:34 -0300 	Mon, 11 Sep 2017 16:53:27 -0300 	KubeletReady 			kubelet is posting ready status
```

```
admin@ip-172-22-xx-xx:~$ df -H
Filesystem      Size  Used Avail Use% Mounted on
udev             11M     0   11M   0% /dev
tmpfs           3.2G  2.7M  3.2G   1% /run
/dev/xvda1       41G  5.2G   34G  14% /
tmpfs           7.9G     0  7.9G   0% /dev/shm
tmpfs           5.3M     0  5.3M   0% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
admin@ip-172-22-xx-xx:~$ df -Hi
Filesystem     Inodes IUsed IFree IUse% Mounted on
udev             2.0M   308  2.0M    1% /dev
tmpfs            2.0M  1.5k  2.0M    1% /run
/dev/xvda1        11M  365k   11M    4% /
tmpfs            2.0M     1  2.0M    1% /dev/shm
tmpfs            2.0M     4  2.0M    1% /run/lock
tmpfs            2.0M    15  2.0M    1% /sys/fs/cgroup
```

node had ~30 pods on it, 25 of them using the same image that has approximately 2GB.

**What you expected to happen**:
Node stop evicting pods.

**How to reproduce it (as minimally and precisely as possible)**:
I've created a cluster in ap-northeast-1 (Tokyo) in AWS using Kops and created a lot of pods with the same image on it.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.5
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): Debian Jessie
- Kernel (e.g. `uname -a`): Linux ip-172-22-44-11 4.4.78-k8s #1 SMP Fri Jul 28 01:28:39 UTC 2017 x86_64 GNU/Linux
- Install tools: Kops
- Others: c4.2xlarge instances with 40GB EBS as root disk

**Comment by thomas-riccardi** [comment]
I have the same symptoms with a GCE (setup with kube-up) 1.7.7 kubernetes cluster: Nodes having DiskPressure, with low disk space and inode usage.

I have restarted a kubelet with verbose logs, and here is what I found:
```
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.095238   21251 status_manager.go:410] Status Manager: syncPod in syncbatch. pod UID: "7b4731a0-a83e-11e7-b1c1-42010a84001e"
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.220058   21251 config.go:101] Looking for [api file], have seen map[file:{} api:{}]
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.220763   21251 kubelet.go:1954] SyncLoop (housekeeping)
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.267478   21251 helpers.go:812] eviction manager: observations: signal=allocatableMemory.available, available: 12611480Ki, capacity: 30887036Ki
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.269428   21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: -9112137624, capacity: 200765316Ki
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.269456   21251 helpers.go:810] eviction manager: observations: signal=memory.available, available: 12053380Ki, capacity: 30887036Ki, time: 2017-10-05 12:14:29
.033015273 +0000 UTC
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.269477   21251 helpers.go:810] eviction manager: observations: signal=nodefs.available, available: 180255088Ki, capacity: 200765316Ki, time: 2017-10-05 12:14:
29.033015273 +0000 UTC
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.269487   21251 helpers.go:810] eviction manager: observations: signal=nodefs.inodesFree, available: 51235777, capacity: 51535232, time: 2017-10-05 12:14:29.033015273 +0000 UTC
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.269497   21251 helpers.go:810] eviction manager: observations: signal=imagefs.available, available: 180255088Ki, capacity: 200765316Ki, time: 2017-10-05 12:14:29.033015273 +0000 UTC
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.269507   21251 helpers.go:810] eviction manager: observations: signal=imagefs.inodesFree, available: 51235777, capacity: 51535232, time: 2017-10-05 12:14:29.033015273 +0000 UTC
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.271771   21251 helpers.go:826] eviction manager: thresholds - ignoring grace period: threshold [signal=allocatableNodeFs.available, quantity=0] observed -9112137624
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.271885   21251 helpers.go:826] eviction manager: thresholds - reclaim not satisfied: threshold [signal=allocatableNodeFs.available, quantity=0] observed -9112137624
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.271904   21251 helpers.go:826] eviction manager: thresholds - updated stats: threshold [signal=allocatableNodeFs.available, quantity=0] observed -9112137624
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.271976   21251 eviction_manager.go:288] eviction manager: node conditions - observed: [DiskPressure]
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.272023   21251 eviction_manager.go:297] eviction manager: node conditions - transition period not met: [DiskPressure]
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: I1005 12:14:37.272037   21251 helpers.go:826] eviction manager: thresholds - grace periods satisified: threshold [signal=allocatableNodeFs.available, quantity=0] observed -9112137624
Oct 05 12:14:37 gpu-europe-west-1-v177-minion-1 kubelet[21251]: W1005 12:14:37.272061   21251 eviction_manager.go:331] eviction manager: attempting to reclaim nodefs
```

More logs about `allocatableNodeFs` or `thresholds`:
```
I1005 12:14:37.269428 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: -9112137624, capacity: 200765316Ki
I1005 12:14:37.271771 21251 helpers.go:826] eviction manager: thresholds - ignoring grace period: threshold [signal=allocatableNodeFs.available, quantity=0] observed -9112137624
I1005 12:14:37.271885 21251 helpers.go:826] eviction manager: thresholds - reclaim not satisfied: threshold [signal=allocatableNodeFs.available, quantity=0] observed -9112137624
I1005 12:14:37.271904 21251 helpers.go:826] eviction manager: thresholds - updated stats: threshold [signal=allocatableNodeFs.available, quantity=0] observed -9112137624
I1005 12:14:37.272037 21251 helpers.go:826] eviction manager: thresholds - grace periods satisified: threshold [signal=allocatableNodeFs.available, quantity=0] observed -9112137624
I1005 12:15:09.667283 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 1996427368, capacity: 200765316Ki
I1005 12:15:43.702234 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 3167957096, capacity: 200765316Ki
I1005 12:15:53.843772 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 3167953000, capacity: 200765316Ki
I1005 12:16:14.139642 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 3157327976, capacity: 200765316Ki
I1005 12:16:24.281939 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 3157327976, capacity: 200765316Ki
I1005 12:17:14.997016 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 3157344360, capacity: 200765316Ki
I1005 12:17:45.462437 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 3179933800, capacity: 200765316Ki
I1005 12:19:16.530737 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 3163791464, capacity: 200765316Ki
I1005 12:19:47.000063 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 3163115624, capacity: 200765316Ki
I1005 12:20:17.305009 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 3163115624, capacity: 200765316Ki
I1005 12:20:27.447534 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 3151057000, capacity: 200765316Ki
I1005 12:21:13.631903 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: -3560320920, capacity: 200765316Ki
I1005 12:21:13.631911 21251 helpers.go:826] eviction manager: thresholds - ignoring grace period: threshold [signal=allocatableNodeFs.available, quantity=0] observed -3560320920
I1005 12:21:13.631915 21251 helpers.go:826] eviction manager: thresholds - reclaim not satisfied: threshold [signal=allocatableNodeFs.available, quantity=0] observed -3560320920
I1005 12:21:13.631920 21251 helpers.go:826] eviction manager: thresholds - updated stats: threshold [signal=allocatableNodeFs.available, quantity=0] observed -3560320920
I1005 12:21:13.631949 21251 helpers.go:826] eviction manager: thresholds - grace periods satisified: threshold [signal=allocatableNodeFs.available, quantity=0] observed -3560320920
I1005 12:21:18.245923 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 1992749160, capacity: 200765316Ki
I1005 12:22:11.620306 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4049150056, capacity: 200765316Ki
I1005 12:22:21.753106 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4049150056, capacity: 200765316Ki
I1005 12:22:42.076576 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4037087336, capacity: 200765316Ki
I1005 12:22:52.222248 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4037087336, capacity: 200765316Ki
I1005 12:23:12.499198 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4037087336, capacity: 200765316Ki
I1005 12:23:43.026278 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4058579048, capacity: 200765316Ki
I1005 12:24:13.457347 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4058574952, capacity: 200765316Ki
I1005 12:24:23.599822 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4058574952, capacity: 200765316Ki
I1005 12:24:43.885060 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4058574952, capacity: 200765316Ki
I1005 12:24:54.041446 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4058574952, capacity: 200765316Ki
I1005 12:25:14.328999 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4053835880, capacity: 200765316Ki
I1005 12:25:24.475951 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4053835880, capacity: 200765316Ki
I1005 12:25:44.763145 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4065898600, capacity: 200765316Ki
I1005 12:26:15.211012 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4062892136, capacity: 200765316Ki
I1005 12:26:25.367390 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4062892136, capacity: 200765316Ki
I1005 12:26:45.661135 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4062892136, capacity: 200765316Ki
I1005 12:27:43.762611 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 702451816, capacity: 200765316Ki
I1005 12:27:53.917059 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 702451816, capacity: 200765316Ki
I1005 12:28:14.206805 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 690385000, capacity: 200765316Ki
I1005 12:28:24.345565 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: -404959128, capacity: 200765316Ki
I1005 12:28:24.345593 21251 helpers.go:826] eviction manager: thresholds - ignoring grace period: threshold [signal=allocatableNodeFs.available, quantity=0] observed -404959128
I1005 12:28:24.345598 21251 helpers.go:826] eviction manager: thresholds - reclaim not satisfied: threshold [signal=allocatableNodeFs.available, quantity=0] observed -404959128
I1005 12:28:24.345603 21251 helpers.go:826] eviction manager: thresholds - updated stats: threshold [signal=allocatableNodeFs.available, quantity=0] observed -404959128
I1005 12:28:24.345631 21251 helpers.go:826] eviction manager: thresholds - grace periods satisified: threshold [signal=allocatableNodeFs.available, quantity=0] observed -404959128
I1005 12:29:18.630279 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4053045352, capacity: 200765316Ki
I1005 12:29:49.070994 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4053041256, capacity: 200765316Ki
I1005 12:30:39.717549 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4053037160, capacity: 200765316Ki
I1005 12:30:49.877318 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4053037160, capacity: 200765316Ki
I1005 12:31:10.045800 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4053037160, capacity: 200765316Ki
I1005 12:31:20.187970 21251 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: 4053037160, capacity: 200765316Ki
```

The pattern goes on and on.

Remarks:
- a negative value is most certainly wrong, and probably triggers the threshold check, which marks the node with DiskPressure
- the value has no unit, whereas `capacity` has one, and `nodefs.available` `available` and `capacity` too

I restarted a node: it did not fix anything.

Nodes are evicting pods in loop, the cluster is unstable.

**Environment:**

- Kubernetes version (use kubectl version): 1.7.7
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release): ID=coreos VERSION=1465.8.0
- Kernel (e.g. uname -a): Linux gpu-europe-west-1-v177-minion-1 4.12.14-coreos #1 SMP Wed Sep 20 22:20:05 UTC 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.60GHz GenuineIntel GNU/Linux
- Install tools: kubernetes/cluster/gce/container-linux kube-up.sh

**Comment by thomas-riccardi** [comment]
cc @kubernetes/sig-node-bugs

**Comment by thomas-riccardi** [comment]
@kubernetes/sig-node-bugs

**Comment by thomas-riccardi** [comment]
@kubernetes/sig-node-bugs

**Comment by thomas-riccardi** [comment]
I tried to work around the issue by disabling the default hard eviction threshold (`allocatableNodeFs.available<0`) using `--eviction-hard`, but the option parser refuses (negative or zero) values; nor does it provides a way to disable individual resource signals eviction mechanisms.

**Comment by dashpole** [comment]
cc @jingxu97

**Comment by dashpole** [comment]
As a work-around, you should be able to disable the local storage feature gate when starting the kubelet.  `--feature-gates=LocalStorageCapacityIsolation=false`

**Comment by jingxu97** [comment]
@thomas-riccardi We are trying to debug this issue. Is that possible you share your full log with us? Also in your system, did you try to set hard eviction threshold or reserve disk resources for kubelet?
https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#hard-eviction-thresholds. https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#kube-reserved

Also did you use hostpath in your pods?

The negative value means the disk usage crossed the threshold, but it seems confusing.

**Comment by thomas-riccardi** [comment]
I'm restarting the deployments on this cluster to reproduce the issue again. Then I'll test `--feature-gates=LocalStorageCapacityIsolation=false`, but I believe it won't help because the pods are not evicted by `m.localStorageEviction`, but by the general pod eviction (log: `must evict pod(s) to reclaim nodefs`).

@jingxu97 :
* what logs do you need? will kubelet verbose=20 on one node be enough? How do I transmit you the logs?
* I did not change the kubelet options, except when adding more logs:

**Comment by thomas-riccardi** [comment]
I reproduced the issue again, and restarted kubelet with `--feature-gates=LocalStorageCapacityIsolation=false`, and the issue happened again : 
```

I1010 15:58:22.017896   30523 helpers.go:812] eviction manager: observations: signal=allocatableMemory.available, available: 14939044Ki, capacity: 30887036Ki
I1010 15:58:22.017901   30523 helpers.go:812] eviction manager: observations: signal=allocatableNodeFs.available, available: -273735576, capacity: 200765316Ki
I1010 15:58:22.017905   30523 helpers.go:810] eviction manager: observations: signal=memory.available, available: 12434784Ki, capacity: 30887036Ki, time: 2017-10-10 15:58:07.7144282 +0000 UTC
I1010 15:58:22.017911   30523 helpers.go:810] eviction manager: observations: signal=nodefs.available, available: 172420564Ki, capacity: 200765316Ki, time: 2017-10-10 15:58:07.7144282 +0000 UTC
I1010 15:58:22.017919   30523 helpers.go:826] eviction manager: thresholds - ignoring grace period: threshold [signal=allocatableNodeFs.available, quantity=0] observed -273735576
I1010 15:58:22.017923   30523 helpers.go:826] eviction manager: thresholds - reclaim not satisfied: threshold [signal=allocatableNodeFs.available, quantity=0] observed -273735576
I1010 15:58:22.017928   30523 helpers.go:826] eviction manager: thresholds - updated stats: threshold [signal=allocatableNodeFs.available, quantity=0] observed -273735576
I1010 15:58:22.017940   30523 eviction_manager.go:288] eviction manager: node conditions - observed: [DiskPressure]
I1010 15:58:22.017951   30523 eviction_manager.go:297] eviction manager: node conditions - transition period not met: [DiskPressure]
```

I did not reproduce the issue with ~50 pods in 3h, and finally reproduced with ~200 pods in 15min.

**Comment by dchen1107** [comment]
cc/ @dnardo This is disk accounting issue I mentioned earlier.

**Comment by dnardo** [comment]
cc/ @caseydavenport

**Comment by dashpole** [comment]
Based on my testing (using overlay2 on COS), we are not correctly accounting container disk usage.  I ran a disk eviction test, and as DiskPressure was triggered, these were the values reported by the summary API:
`imageFsInfo.CapacityBytes: 16.68 GB, imageFsInfo.AvailableBytes: 6.67 GB`
`rootFsInfo.CapacityBytes: 16.68 GB, rootFsInfo.AvailableBytes: 6.67 GB`
`Pod: container-disk-hog-pod`
`--- summary Container: container-disk-hog-container UsedBytes: 16.5 GB`
`Pod: innocent-pod`
`--- summary Container: innocent-container UsedBytes: 1.2 MB`

We can see that we are clearly not measuring disk space correctly during my testing.

On a separate note, the node should not be exposing Local Storage Capacity from the node object if the feature gate is disabled.
@jingxu97 can we make sure this is feature gated?  We should try and get this into the previous releases ASAP while I figure out what the root cause of this is.

**Comment by dashpole** [comment]
Another takeaway from this bug is that it is confusing to have some eviction signals and thresholds be in the format:
`Signal < eviction threshold`
and have the allocatable signals be
`Signal - eviction threshold < 0`

I plan to change this for future releases.

**Comment by dchen1107** [comment]
This is a serious regression in 1.7 for disk management. We should patch both 1.7 and 1.8 to disable the feature through: LocalStorageCapacityIsolation first.

**Comment by dchen1107** [comment]
@dashpole Can we reproduce the issue with Overlay?

**Comment by dashpole** [comment]
I am currently testing with aufs, since that was the first alternate image I could find.  I can test with overlay soon.

**Comment by dashpole** [comment]
It appears to work correctly on aufs on ubuntu xenial:
`imageFsInfo.CapacityBytes: 20.7 GB, imageFsInfo.AvailableBytes: 1.91 GB`
`rootFsInfo.CapacityBytes: 20.7 GB, rootFsInfo.AvailableBytes: 1.91 GB`
`Pod: container-disk-hog-pod`
`--- summary Container: container-disk-hog-container UsedBytes: 16.9 GB`
`Pod: innocent-pod`
`--- summary Container: innocent-container UsedBytes: 12 KB`

**Comment by dashpole** [comment]
Looks like overlay on COS 59 (docker 1.11) is fine as well:
`imageFsInfo.CapacityBytes: 16.7 GB, imageFsInfo.AvailableBytes: 1.62 GB`
`rootFsInfo.CapacityBytes: 16.7 GB, rootFsInfo.AvailableBytes: 1.62 GB`
`Pod: container-disk-hog-pod`
`--- summary Container: container-disk-hog-container UsedBytes: 13.8 GB`
`Pod: innocent-pod`
`--- summary Container: innocent-container UsedBytes: 49 KB`

**Comment by dashpole** [comment]
My best guess is that this is an issue with docker 1.13, or an issue with overlay2.  Ill do some more testing tomorrow.
@felipejfc @thomas-riccardi can you share your docker storage driver and docker version?

**Comment by thomas-riccardi** [comment]
> Another takeaway from this bug is that it is confusing to have some eviction signals and thresholds be in the format:
Signal < eviction threshold
and have the allocatable signals be
Signal - eviction threshold < 0

This is indeed confusing, and incoherent with kubelet cli parameters to control eviction, as explained in a previous comment.

As for my docker version and info (I did not change anything from the default there):
```
$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.6
 Git commit:   a82d35e
 Built:        Wed Sep 20 22:27:13 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.6
 Git commit:   a82d35e
 Built:        Wed Sep 20 22:27:13 2017
 OS/Arch:      linux/amd64
```
```
$ docker info
Containers: 51
 Running: 37
 Paused: 0
 Stopped: 14
Images: 16
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.12.14-coreos
Operating System: Container Linux by CoreOS 1465.8.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 29.46 GiB
Name: gpu-europe-west-1-v177-minion-1
ID: 4JER:JG7I:KIYV:D36C:HCK3:QVCD:OPST:WX3H:EVGV:VB5F:BDIO:KDKL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by jingxu97** [comment]
@dashpole I think we can get the feature gate at here to avoid allocatable feature for local storage 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/container_manager_linux.go#L597

**Comment by dchen1107** [comment]
Re: https://github.com/kubernetes/kubernetes/issues/52336#issuecomment-335649899

That is what I guess. We had the issue accounting overlay 2's disk usage in cAdvisor. But that doesn't explain overlay issue on container-linux (core os) image reported by @thomas-riccardi above.

**Comment by dashpole** [comment]
@thomas-riccardi strange, I cannot reproduce this on our testing coreos image: 
coreos-alpha-1122-0-0-v20160727

**Comment by dashpole** [comment]
I believe this is an issue with stats collection on overlay2

**Comment by dashpole** [comment]
I have tested a fix, and can confirm that it fixes issues found in my testing.  However, the cause of @thomas-riccardi's issues is still unknown.

**Comment by jingxu97** [comment]
@davidopp, which @thomas-riccardi's issue you are referring in you last comment? Thanks!

**Comment by thomas-riccardi** [comment]
Maybe reopen for other impacted storage drivers? 
See https://github.com/google/cadvisor/pull/1770#issuecomment-336259929

**Comment by thomas-riccardi** [comment]
@dashpole @derekwaynecarr ping: shouldn't we reopen this issue for other impacted storage drivers? cf https://github.com/google/cadvisor/pull/1770#issuecomment-336259929

**Comment by dashpole** [comment]
@thomas-riccardi I need to take a closer look at `overlay`, but at first glance it looks like both overlay and aufs report correct disk stats.  See [my earlier comment](https://github.com/kubernetes/kubernetes/issues/52336#issuecomment-335649899)

**Comment by warmchang** [comment]
👍

**Comment by KeithTt** [comment]
same problem...

```
The node was low on resource: nodefs
The node was low on resource: [DiskPressure].
```

kube version: 1.8.5
docker version: 17.06.2-ce

**Comment by dashpole** [comment]
@KeithTt can you open a new issue?  This particular issue was fixed in 1.8.5, but you may have run into something different.

**Comment by quasiben** [comment]
Will this issue also be patched into the 1.7.X branch ?

**Comment by KeithTt** [comment]
@dashpole I am sorry I missed your message, I have opened a new issue and cc you.

**Comment by dashpole** [comment]
@quasiben this was fixed by https://github.com/kubernetes/kubernetes/pull/54958 in 1.7.11

**Comment by kavyabgowda** [comment]
Is there any fix for this issue. Still facing the same issue with Kubernetes v1.20.4.
"Kubectl is evicting pods throwing  failed to release ephemeral-storage and node is under disk pressure."
