### ISSUE TITLE
Ephemeral Containers: Allow setting security context

### ISSUE THREAD

**Issue by verb** [kubernetes/kubernetes#53188]
Ephemeral containers are required to have an empty `securityContext`. We've received some requests to allow the security context to be configured:

- https://github.com/kubernetes/kubernetes/issues/53188#issuecomment-540951404: Using `NET_ADMIN` with ephemeral containers
- https://github.com/kubernetes/enhancements/pull/1272#issuecomment-542149026: More permissive security profile for ephemeral containers (ptrace, apparmor, seccomp)

**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**Comment by liggitt** [comment]
Can probably close this, addressed by https://github.com/kubernetes/community/pull/1269

**Comment by YangKeao** [comment]
As mentioned in doc, security context is still not configurable. Every ephemeral container runs with `CAP_SYS_ADMIN` and `CAP_SYS_PTRACE`, but I need to set up an EphemeralContainer with `CAP_NET_ADMIN`.

Will this feature (configurable security context) be added into EphemeralContainer? Or how could I create an ephemeral container with `CAP_NET_ADMIN`?

**Comment by verb** [comment]
I've forgotten what prompted us to close this, but that's correct. The design that landed does not have a configurable security context. I'll reopen this as a feature request and update the description.

**Comment by verb** [comment]
FYI @pjbgf reopened this issue to track your request

**Comment by verb** [comment]
Haven't scheduled work here yet, but this is still relevant.

/remove-lifecycle stale

**Comment by verb** [comment]
I'm pondering how to make this configurable via `PodSecurityPolicy`. The idea is that we'd allow ephemeral containers to set security context but allow the behavior to be constrained by policy.

It's not clear to me how configurable this should be. The simplest implementation would be a boolean controlling whether security context may be set for ephemeral containers and then applying the existing constraints (i.e. `AllowedCapabilities`, etc).

Since ephemeral containers access control is separate from container creation, I could see a use case where an admin may want to grant broader capabilities to an ephemeral container for debugging purposes,  though.

I'd welcome any suggestions here. I'll probably start by updating the KEP with the simplest implementation and going from there.

cc @liggitt @pjbgf

**Comment by pjbgf** [comment]
@verb I would concur with your suggested implementation, as it would allow cluster admins to have some control over what capabilities can be used within the cluster. 

In terms of usage, I think that once that flag is enabled, a cluster admin would need to temporarily assign a less restrictive PSP to the service account that is being used in the pod. At the end of the debugging session, the ephemeral container would be deleted and the cluster admin would revert the PSP assignment.

For all purposes, any containers within that pod would be able to exercise the same capabilities, but would also be limited by whatever is defined on that given PSP.

**Comment by pjbgf** [comment]
This issue is still relevant.

/remove-lifecycle stale

**Comment by mradmila** [comment]
Hi @verb, I am running Kubernetes 1.18.6, and I've tried to use the "alpha debug" feature to debug my distroless container. However, contrary to what @YangKeao mentioned above, I am not getting CAP_SYS_PTRACE capability by default, nor there is a way to set it. Needless to say, I need this capability in order to attach the debugger. Am I missing something obvious?

kubectl alpha debug -it debug-demo-hang --image=<debug_image> --target=debug-demo
 
root@debug-demo-hang:/# capsh --print
Current: = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap+eip
Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap
Securebits: 00/0x0/1'b0
secure-noroot: no (unlocked)
secure-no-suid-fixup: no (unlocked)
secure-keep-caps: no (unlocked)
uid=0(root)
gid=0(root)
groups=

**Comment by verb** [comment]
Hi @mradmila, 

That's correct, there is currently no way to set CAP_SYS_PTRACE. We're hoping to add the ability to configure capabilities for Ephemeral Containers in the 1.21 cycle and take the feature to beta.
