### ISSUE TITLE
controller-manager wrongly warns about empty service-account-private-key-file

### ISSUE THREAD

**Issue by antoineco** [kubernetes/kubernetes#53291]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

During startup `controller-manager` shows the following warning:

`controllermanager.go:138] --use-service-account-credentials was specified without providing a --service-account-private-key-file`

However `--service-account-private-key-file` is set and refers to a valid X.509 private key file.

All service accounts seem to be created despite the warning.

**How to reproduce it (as minimally and precisely as possible)**:

start controller-manager with
```json
        "name": "kube-controller-manager",
        "image": "quay.io/coreos/hyperkube:v1.8.0_coreos.0",
        "command": [
          "kube-controller-manager",
          "--address=127.0.0.1",
          "--allocate-node-cidrs",
          "--cluster-cidr=172.17.0.0/16",
          "--cluster-signing-cert-file=/etc/kubernetes/tls/ca.pem",
          "--cluster-signing-key-file=/etc/kubernetes/tls/ca.key",
          "--kubeconfig=/etc/kubernetes/kubeconfig",
          "--root-ca-file=/etc/kubernetes/tls/ca.pem",
          "--service-account-private-key-file=/etc/kubernetes/tls/host.key",
          "--service-cluster-ip-range=10.0.0.0/16",
          "--use-service-account-credentials"
        ],
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.0
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)

**Comment by liggitt** [comment]
Thanks for the report. The condition for printing the warning is backwards, but has no effect on behavior. 

Fixed in #51034

**Comment by redbaron** [comment]
Still present in 1.8.3 , can it be backported to 1.8 branch please?

**Comment by dims** [comment]
@redbaron See https://github.com/kubernetes/kubernetes/pull/55878 for proposed cherry-pick
