### ISSUE TITLE
[job failure] gce-scale-correctness

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#55194]
/priority critical-urgent
/priority failing-test
/kind bug
/status approved-for-milestone
@kubernetes/sig-scalability-test-failures

This job has been failing for as far back as I can see on testgrid.  It's on the [sig-release-master-blocking dashboard](https://k8s-testgrid.appspot.com/sig-release-master-blocking), and prevents us from cutting [v1.9.0-alpha.3](https://github.com/kubernetes/sig-release/issues/27). Is there work ongoing to bring this job back to green?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-correctness

/assign @shyamjvs 
I suspect there's another umbrella issue for this out there, but I'm making one for the v1.9 release for consistency's sake

**Comment by spiffxp** [comment]
some test case refs:
- https://github.com/kubernetes/kubernetes/issues/54636
- https://github.com/kubernetes/kubernetes/issues/52495

**Comment by shyamjvs** [comment]
I've linked all currently open issues I've filed for the failing tests. And bumped priority for all those issues based on this one and at this point there's no active work required from our side.
It's now on the individual SIGs to fix the issues.

**Comment by shyamjvs** [comment]
I'm going to co-own this bug with @porridge who'll take this further while I'd be on vacation during december.

/assign @porridge

**Comment by shyamjvs** [comment]
All the issues under this umbrella have been fixed. There's more stuff to be done under #52495, but that's not causing redness in this job anymore.
The latest run is super green (except for one e2e which seems like a flake so far) - https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-correctness

Closing this issue.. we can reopen if new failures pop up.
/close

**Comment by spiffxp** [comment]
/reopen
@shyamjvs I'd rather take testgrid's word than have to interpret the results here. I agree we've worked out the individual test failures. But, the job is still failing. I need to see a green run to consider this closed.

**Comment by porridge** [comment]
*sigh*, the HPA failures are back, and we have two new ones in the latest
run:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/28

**Comment by shyamjvs** [comment]
Seems like the latest run (no. 29) failed with only the HPA e2es failing - https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-correctness
With https://github.com/kubernetes/kubernetes/pull/55798 merged, those shouldn't be run anymore at scale. I'll kick the job manually now (silently hoping to have a green run).

**Comment by spiffxp** [comment]
We cut v1.9.0-alpha.3 (https://github.com/kubernetes/sig-release/issues/27) despite the continued failure of this job.  Now tracking this against v1.9.0-beta.1 (https://github.com/kubernetes/sig-release/issues/34)

**Comment by jeffvance** [comment]
looking at this too...

**Comment by porridge** [comment]
ACK. In progress
ETA: None
Risks: Multiple flakes across several SIGs need fixing.

**Comment by porridge** [comment]
ACK. In progress, 1 new subordinate issue opened, 3 closed
No ETA
Risks: Multiple flakes across several SIGs need fixing.

**Comment by porridge** [comment]
ACK. In progress, total of 15 subordinate issues, 7 still open
No ETA
Risks: Multiple flakes across several SIGs need fixing.

**Comment by porridge** [comment]
FWIW, we got a [first ever green run of gce-scale-correctness](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/37).
I wouldn't close this bug yet, though, one swallow does not a summer make.

**Comment by spiffxp** [comment]
>FWIW, we got a first ever green run of gce-scale-correctness.

Commenting here for posterity's sake.  I agree that we got a green run.  Annoyingly, testgrid's summary tab still shows the job as failing.  This is because it's looking back [`num_columns_recent: 10`](https://github.com/kubernetes/test-infra/blob/master/testgrid/config/config.yaml#L20) to determine if a previously failing test has passed.  There doesn't appear to be any way to tell testgrid to count "test no longer runs" as a pass.

I think it might be a good idea to tune down `num_columns_recent` for slow jobs like this one, not sure what the right place/value is though.

**Comment by porridge** [comment]
This is strange, why does it look at individual tests, and not just the overall status?

**Comment by spiffxp** [comment]
The way it was explained to me in #sig-testing is that testgrid as a tool doesn't really understand hierarchy; Overall is just another fake test

**Comment by porridge** [comment]
ACK.  In progress, causes for recent flakes fixed, ginko flake flake auto-retry swithched on, waiting for next run tomorrow
ETA: 01/12/2017

**Comment by porridge** [comment]
ACK. In progress
ETA: 03/12/2017
Risks: Apparently new regression: #56683

**Comment by spiffxp** [comment]
Now tracking against v1.9.0-beta.2 (kubernetes/sig-release#39)

**Comment by porridge** [comment]
ACK.  In progress
ETA: 06/12/2017
Risks: newly introduced audit tests still unfixed: #56683

**Comment by porridge** [comment]
ACK. In progress, known regression #56683 fixed. Next job run tomorrow.
ETA: 06/12/2017

**Comment by porridge** [comment]
Ack. [Run 42](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/42) was green. Let's keep this around until next green.
ETA: 08/12/2017

**Comment by spiffxp** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/43 also green

I'm OK closing this if you are @porridge
