### ISSUE TITLE
Cadvisor unable to find data for container /

### ISSUE THREAD

**Issue by discolt** [kubernetes/kubernetes#55386]
/kind bug

Cadvisor can't collect container metrics

```
curl http://localhost:10255/stats/summary

Internal Error: failed to get root cgroup stats: failed to get cgroup stats for "/": failed to get container info for "/": partial failures: ["/": RecentStats: unable to find data for container /]
```
**Environment**:
- Kubernetes version:  v1.8.1
- Docker version:  v1.2.6
- Kernel：Kernel version is 3.10.0-327.ali2010.rc7.alios7.x86_64.

Removed cadvisor-port=0 in kubeadm 

```
cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=cgroupfs"
Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CGROUP_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS
```

--------

```curl http://127.0.0.1:4194/validate/
cAdvisor version:

OS version: Alibaba Group Enterprise Linux Server 7.2 (Paladin)

Kernel version: [Supported and recommended]
    Kernel version is 3.10.0-327.ali2010.rc7.alios7.x86_64. Versions >= 2.6 are supported. 3.0+ are recommended.


Cgroup setup: [Supported and recommended]
    Available cgroups: map[perf_event:1 hugetlb:1 cpuacct:1 memory:1 devices:1 freezer:1 net_cls:1 blkio:1 intel_rdt:0 cpuset:1 cpu:1]
    Following cgroups are required: [cpu cpuacct]
    Following other cgroups are recommended: [memory blkio cpuset devices freezer]
    Hierarchical memory accounting enabled. Reported memory usage includes memory used by child containers.

Cgroup mount setup: [Supported and recommended]
    Cgroups are mounted at /sys/fs/cgroup.
    Cgroup mount directories: blkio cpu cpuacct cpuset cpuset,cpu,cpuacct devices freezer hugetlb memory net_cls perf_event systemd
    Any cgroup mount point that is detectible and accessible is supported. /sys/fs/cgroup is recommended as a standard location.
    Cgroup mounts:
    cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
    ...

Docker version: [Supported and recommended]
    Docker version is 1.12.6. Versions >= 1.0 are supported. 1.2+ are recommended.

Docker driver setup: [Supported and recommended]
    Docker exec driver is . Storage driver is devicemapper.

Block device setup: [Supported, but not recommended]
    None of the devices support 'cfq' I/O scheduler. No disk stats can be reported.
     Disk "dm-27" Scheduler type "none".
     ...
Inotify watches:

Managed containers:
    ...
```

/sig cadvisor

**Comment by discolt** [comment]
kubelet logs

```
sudo kubelet logs
I1109 17:56:16.564626  234564 feature_gate.go:156] feature gates: map[]
I1109 17:56:16.564702  234564 controller.go:114] kubelet config controller: starting controller
I1109 17:56:16.564715  234564 controller.go:118] kubelet config controller: validating combination of defaults and flags
I1109 17:56:16.569190  234564 client.go:75] Connecting to docker on unix:///var/run/docker.sock
I1109 17:56:16.569228  234564 client.go:95] Start docker client with request timeout=2m0s
I1109 17:56:16.574438  234564 feature_gate.go:156] feature gates: map[]
W1109 17:56:16.574582  234564 server.go:289] --cloud-provider=auto-detect is deprecated. The desired cloud provider should be set explicitly
W1109 17:56:16.574620  234564 server.go:324] standalone mode, no API client
I1109 17:56:16.574932  234564 manager.go:149] cAdvisor running in container: "/sys/fs/cgroup/cpuset,cpu,cpuacct/system.slice/sshd.service"
W1109 17:56:16.587007  234564 manager.go:157] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
W1109 17:56:16.587170  234564 manager.go:166] unable to connect to CRI-O api service: Get http://%2Fvar%2Frun%2Fcrio.sock/info: dial unix /var/run/crio.sock: connect: no such file or directory
...
W1109 17:56:16.606977  234564 server.go:232] No api server defined - no events will be sent to API server.
I1109 17:56:16.607070  234564 cadvisor_linux.go:170] Failed to register cAdvisor on port 4194, retrying. Error: listen tcp 0.0.0.0:4194: bind: address already in use
I1109 17:56:16.607093  234564 server.go:422] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
I1109 17:56:16.609040  234564 container_manager_linux.go:252] container manager verified user specified cgroup-root exists: /
I1109 17:56:16.609076  234564 container_manager_linux.go:257] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>}]} ExperimentalQOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s}
I1109 17:56:16.609230  234564 container_manager_linux.go:288] Creating device plugin handler: false
W1109 17:56:16.612309  234564 kubelet_network.go:69] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
I1109 17:56:16.612373  234564 kubelet.go:517] Hairpin mode set to "hairpin-veth"
I1109 17:56:16.619161  234564 docker_service.go:207] Docker cri networking managed by kubernetes.io/no-op
I1109 17:56:16.629805  234564 docker_service.go:224] Setting cgroupDriver to cgroupfs
I1109 17:56:16.654484  234564 remote_runtime.go:43] Connecting to runtime service unix:///var/run/dockershim.sock
I1109 17:56:16.655610  234564 kuberuntime_manager.go:177] Container runtime docker initialized, version: 1.12.6, apiVersion: 1.24.0
I1109 17:56:16.656720  234564 server.go:718] Started kubelet v1.8.1
E1109 17:56:16.656775  234564 kubelet.go:1234] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data for container /
I1109 17:56:16.656770  234564 server.go:128] Starting to listen on 0.0.0.0:10250
W1109 17:56:16.656745  234564 kubelet.go:1318] No api server defined - no node status update will be sent.
E1109 17:56:16.656828  234564 server.go:504] Starting health server failed: listen tcp 127.0.0.1:10248: bind: address already in use
F1109 17:56:16.657819  234564 server.go:156] listen tcp 0.0.0.0:10255: bind: address already in use
I1109 17:56:16.658772  234564 kubelet_node_status.go:276] Setting node annotation to enable volume controller attach/detach
I1109 17:56:16.658806  234564 server.go:296] Adding debug handlers to kubelet server.
```

**Comment by discolt** [comment]
Bug at:

cadvisor/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpuacct.go

```
      data, err := ioutil.ReadFile(filepath.Join(path, cgroupCpuacctStat))
    if err != nil {
        return 0, 0, err
    }
    fields := strings.Fields(string(data))
    if len(fields) != 4 {
        return 0, 0, fmt.Errorf("failure - %s is expected to have 4 fields", filepath.Join(path, cgroupCpuacctStat))
    }
```

inside my cAdvisor container,  cat  .....xxx/cpuacct.stat, Actually lenght is 6

```
user 0
system 0
nr_migrations 0
```

**Comment by kron4eg** [comment]
I think I observer that issue too:

I see that over time (days) kubelet gradually increasing CPU consumption, here is pprof I've pulled off kubelet:

```
(pprof) top
Showing nodes accounting for 3.10s, 25.41% of 12.20s total
Dropped 560 nodes (cum <= 0.06s)
Showing top 10 nodes out of 209
      flat  flat%   sum%        cum   cum%
         0     0%     0%      4.89s 40.08%  k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*containerData).housekeeping
         0     0%     0%      4.79s 39.26%  k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*containerData).housekeepingTick
         0     0%     0%      4.77s 39.10%  k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*containerData).updateStats
     0.01s 0.082% 0.082%      4.66s 38.20%  k8s.io/kubernetes/vendor/github.com/google/cadvisor/container/libcontainer.GetStats
     0.01s 0.082%  0.16%      4.61s 37.79%  k8s.io/kubernetes/vendor/github.com/google/cadvisor/container/raw.(*rawContainerHandler).GetStats
     0.03s  0.25%  0.41%      4.60s 37.70%  k8s.io/kubernetes/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs.(*Manager).GetStats
     0.01s 0.082%  0.49%      3.59s 29.43%  io/ioutil.ReadFile
     3.04s 24.92% 25.41%      3.23s 26.48%  syscall.Syscall
         0     0% 25.41%      2.80s 22.95%  os.Open
         0     0% 25.41%      2.80s 22.95%  os.OpenFile
```

whole pprof
[pprof.kubelet.samples.cpu.002.pb.gz](https://github.com/kubernetes/kubernetes/files/1737190/pprof.kubelet.samples.cpu.002.pb.gz)

**Comment by dims** [comment]
should be fixed in v1.11, there have been several changes in cadvisor including
- limiting the number of concurrent `du`
- running `du` with `ionice`

etc.

**Comment by lingyueling** [comment]
> /kind bug
> 
> Cadvisor can't collect container metrics
> 
> ```
> curl http://localhost:10255/stats/summary
> 
> Internal Error: failed to get root cgroup stats: failed to get cgroup stats for "/": failed to get container info for "/": partial failures: ["/": RecentStats: unable to find data for container /]
> ```
> **Environment**:
> 
> * Kubernetes version:  v1.8.1
> * Docker version:  v1.2.6
> * Kernel：Kernel version is 3.10.0-327.ali2010.rc7.alios7.x86_64.
> 
> Removed cadvisor-port=0 in kubeadm
> 
> ```
> cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
> [Service]
> Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
> Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
> Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
> Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
> Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
> Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=cgroupfs"
> Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki"
> ExecStart=
> ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CGROUP_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS
> ```
> ```
> cAdvisor version:
> 
> OS version: Alibaba Group Enterprise Linux Server 7.2 (Paladin)
> 
> Kernel version: [Supported and recommended]
>     Kernel version is 3.10.0-327.ali2010.rc7.alios7.x86_64. Versions >= 2.6 are supported. 3.0+ are recommended.
> 
> 
> Cgroup setup: [Supported and recommended]
>     Available cgroups: map[perf_event:1 hugetlb:1 cpuacct:1 memory:1 devices:1 freezer:1 net_cls:1 blkio:1 intel_rdt:0 cpuset:1 cpu:1]
>     Following cgroups are required: [cpu cpuacct]
>     Following other cgroups are recommended: [memory blkio cpuset devices freezer]
>     Hierarchical memory accounting enabled. Reported memory usage includes memory used by child containers.
> 
> Cgroup mount setup: [Supported and recommended]
>     Cgroups are mounted at /sys/fs/cgroup.
>     Cgroup mount directories: blkio cpu cpuacct cpuset cpuset,cpu,cpuacct devices freezer hugetlb memory net_cls perf_event systemd
>     Any cgroup mount point that is detectible and accessible is supported. /sys/fs/cgroup is recommended as a standard location.
>     Cgroup mounts:
>     cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
>     ...
> 
> Docker version: [Supported and recommended]
>     Docker version is 1.12.6. Versions >= 1.0 are supported. 1.2+ are recommended.
> 
> Docker driver setup: [Supported and recommended]
>     Docker exec driver is . Storage driver is devicemapper.
> 
> Block device setup: [Supported, but not recommended]
>     None of the devices support 'cfq' I/O scheduler. No disk stats can be reported.
>      Disk "dm-27" Scheduler type "none".
>      ...
> Inotify watches:
> 
> Managed containers:
>     ...
> ```
> /sig cadvisor

so how to remove the nr_migrations ?

**Comment by xuzhenglun** [comment]
This problem is still there.  any update？

related issue: https://github.com/opencontainers/runc/issues/1844

**Comment by Hellovolcanoofficial** [comment]
I met that problem too? Any solutions?

**Comment by Letme** [comment]
problem still existing in 1.21.7
