### ISSUE TITLE
[job failure] gke-device-plugin-gpu-p100

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#56090]
/priority critical-urgent
/priority failing-test
/area platform/gke
/kind bug
/status approved-for-milestone
@kubernetes/sig-gcp-test-failures 

This job has been failing since 2017-11-18.  It's on the [sig-release-master-blocking dashboard](https://k8s-testgrid.appspot.com/sig-release-master-blocking),
and prevents us from cutting [v1.9.0-beta.1] (kubernetes/sig-release#34). Is there work ongoing to bring this job back to green?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gke-device-plugin-gpu-p100

- last good: k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-device-plugin-gpu-p100/21
- first bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-device-plugin-gpu-p100/22
- latest bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-device-plugin-gpu-p100/25

**Comment by abgworrall** [comment]
/assign @mindprince 

Rohit, is this related to the other failing suite ?

**Comment by mindprince** [comment]
Yes. This is the same issue as https://github.com/kubernetes/kubernetes/issues/56078 and should be fixed soon.

**Comment by spiffxp** [comment]
FYI this is still failing, it may be that I haven't seen a run yet since you've rolled out the GKE-related change

**Comment by mindprince** [comment]
Yes, it's an expensive test and runs only every 12 hours. It should pass in the next run.

**Comment by mindprince** [comment]
/close
Latest run passed.
