### ISSUE TITLE
Something calls /version with incorrect user agent "Go 1.1 package http"

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#5672]
I believe

```
I0319 21:39:15.483696   12583 server.go:676] GET /api/v1beta1/nodeInfo: (23.815us) 0 [[Go 1.1 package http] 127.0.0.1:37845]
```

is coming from the master client, but the standard Kubernetes user-agent that comes out of client.Config is not present.  We should be using client config and making requests that way (so at a minimum the agent is correct).  This is probably a prereq for proper master->node auth, so @liggitt

**Comment by erictune** [comment]
We are very close to having the master ever be a client of the node anymore.

**Comment by lavalamp** [comment]
Work item here is to delete that node client entirely. It should be unused now.

**Comment by roberthbailey** [comment]
@erictune Do we have a burn-down list somewhere for the remaining places where the master contacts the node?

**Comment by bgrant0607** [comment]
@kubernetes/sig-api-machinery Anyone know whether this is still an issue or can be closed?

**Comment by smarterclayton** [comment]
I have not seen this in the most recent dumps from metrics (which makes me think this is fixed).

**Comment by lavalamp** [comment]
I just searched a random e2e apiserver log and found two instances, both to the /version endpoint. So something is still failing to set this, but probably not the master itself . What calls /version? I'll change the bug title.

```
I0517 12:27:51.383585       6 handlers.go:161] GET /version: (424.511µs) 200 [[Go 1.1 package http] 10.180.2.6:34266]
```

**Comment by smarterclayton** [comment]
I'm pretty sure that would be the default Go client, possibly the e2e tests
themselves checking the version at the beginning of the test?

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
