### ISSUE TITLE
namespace still exists in ETCD after it was deleted using kubectl

### ISSUE THREAD

**Issue by AvTiMp** [kubernetes/kubernetes#57029]
> /kind bug

**What happened**:
create a namespacenamed "test", create some pods, then delete this namespace

but the directory  /kubernetes.io/pods/test  in ETCD will not be deleted after a very long time

**What you expected to happen**:

it should be deleted

**How to reproduce it (as minimally and precisely as possible)**:

1. create a namespace, create some pods 
2. delete namespace
3. find it in ETCD ( /kubernetes.io/pods/<namespace>)

**Environment**:
- Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+5115d708d7", GitCommit:"fff65cf", GitTreeState:"clean", BuildDate:"2017-08-03T14:24:07Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
- Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+5115d708d7", GitCommit:"fff65cf", GitTreeState:"clean", BuildDate:"2017-08-03T14:24:07Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by AvTiMp** [comment]
@kubernetes/sig-etcd-bugs

**Comment by liggitt** [comment]
Namespace deletion is delayed until the namespace controller cleans up all resources inside the namespace. If there are pods running in the namespace, they must terminate, and be cleaned up by the kubelets running them before the namespace will be deleted from the API.

While that process is ongoing, the namespace API object will show status as terminating.

**Comment by AvTiMp** [comment]
i know this, i mean that this namespace is not deleted after a very long time.  in etcd, the /namesapces/<name> is deleted, but /pods/<namespace name>will never be deleted, this shouldnt happen

**Comment by liggitt** [comment]
ah. sounds like a duplicate of https://github.com/kubernetes/kubernetes/issues/36891, though we haven't had success recreating this

**Comment by AvTiMp** [comment]
here are steps to reproduce this:
1. create a namespace called test
2. create a simple pod whatever it is , then delete it
3. wait enough time then delete namespace test

in etcd,  /namespaces/test is deleted, but /pods/test/ directory is not, this shouldn;t happen

**Comment by liggitt** [comment]
Are you referring to the empty namespace directory node? If so, that's a known issue in etcd2, resolved in etcd3

**Comment by AvTiMp** [comment]
my etcd verison is:
```
    etcdctl version: 3.1.9
    API version: 2
```
i means namespaces directory under /pod in etcd still exists after the corresponding namespace was deleted

**Comment by liggitt** [comment]
that is expected using etcd API version 2
