### ISSUE TITLE
vSphere cloud provider broken with controller-manager v1.9.0

### ISSUE THREAD

**Issue by ceason** [kubernetes/kubernetes#57279]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
`controller-manager` crashes with error `client_builder.go:273] ServiceAccount "vSphere-cloud-provider" is invalid: metadata.name: Invalid value: "vSphere-cloud-provider": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

**What you expected to happen**:
I expected the controller-manager to launch without issue.

**How to reproduce it (as minimally and precisely as possible)**:
Launch a controller-manager with a cloud-config per [VMware documentation](https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html#step-5-create-the-vsphere-cloud-config-file-vsphereconf).

**Anything else we need to know?**:
Root cause appears to be [here](https://github.com/kubernetes/kubernetes/blob/94b45a9e847a002bb6f6e43a11dcf83782e103df/pkg/cloudprovider/providers/vsphere/vsphere.go#L220). Perhaps lowercasing the 'S' will solve this?

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.0
- Cloud provider or hardware configuration: vsphere
- OS (e.g. from /etc/os-release): Ubuntu 17.10
- Kernel (e.g. `uname -a`): Linux 4.9.61
- Install tools: 
- Others:

**Comment by liggitt** [comment]
Added in https://github.com/kubernetes/kubernetes/pull/55845
/assign @rohitjogvmw

**Comment by rohitjogvmw** [comment]
Hi @liggitt,

I will work on it as soon as possible.
Thanks for reporting the issue.

/Rohit

**Comment by rohitjogvmw** [comment]
Hi @liggitt 

I have created an image with fix. Can you give it a try?
I have pushed the image as "docker.io/rohitjogvmw/hyperkube-amd64:ctlr-mgr-fix"
If you are using kubeadm, use can specify this image in kubeadm config file.

**Comment by liggitt** [comment]
Can you open a PR for review as well?

**Comment by rohitjogvmw** [comment]
sure

**Comment by rohitjogvmw** [comment]
Hi @liggitt,
We were not able to reproduce the issue inhouse.
Can you please let us know
1. How did you run into issue? Which deployement method was used etc.
2. Is above provided hyperkube image solving the issue? Did you get a chance to try it?

Thanks,
Rohit

**Comment by ceason** [comment]
@rohitjogvmw still not working,

Now I get `1 reflector.go:205] k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go:227: Failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:kube-system:vsphere-cloud-provider" cannot list nodes at the cluster scope`

I created a ClusterRoleBinding for that user to `cluster-admin` to see if that would fix things, but then I got a lot of....
```
E1219 01:42:34.419331       1 datacenter.go:78] Unable to find VM by UUID. VM UUID: dd501542-e4d6-6bd1-aef0-60a8657e397c
E1219 01:42:34.419371       1 vsphere.go:466] Cannot find node "k8s-kubetest-master0" in cache. Node not found!!!
E1219 01:42:34.419399       1 node_controller.go:765] Error determining if node k8s-kubetest-master0 exists in cloud: No VM found
```

**Comment by rohitjogvmw** [comment]
Hi @ceason,

Can you please provide more details on how did you deploy your cluster and what is the configuration of the cluster?
Please provide detailed steps and logs to analyze.

At least controller manager crash is not happening with the change.

Thanks,
Rohit

**Comment by ceason** [comment]
I am..
- Running on **Ubuntu 17.10** VMs
- Installed **kubelet v1.9.0-00** via http://apt.kubernetes.io
- Control-plane nodes are run as static pods using images from `gcr.io/google_containers/kube-<component>-amd64:v1.9.0` (except for controller-manager, where I'm using "docker.io/rohitjogvmw/hyperkube-amd64:ctlr-mgr-fix" instead)

Is that enough info? I can provide more specifics if there's something else you need.

Thanks,

-Chris

**Comment by maehld** [comment]
Hi,

I've encoutered the same error. Our deployment was via kubeadm 1.9.0 directly from the binary downloads on github on a clean minimal PhotonOS 2 install.

I'm happy to provide more info if needed.

**Comment by rohitjogvmw** [comment]
Hi @maehld,

How did you enabled vSphere Cloud Provider (VCP)?
Did you use kubeadm itself to deploy cluster with VCP enabled?

**Comment by maehld** [comment]
@rohitjogvmw I've used kubeadm with a config file to set the provider, config file and the extra args for the API server and controller manager. So yes, I've deployed VCP directly with kubeadm.

**Comment by rohitjogvmw** [comment]
Thanks.
Will you be able to share kubeadm config file. We will internally use it to re-produce the issue.

**Comment by maehld** [comment]
Sure. I'll be back at work tomorrow and will post the config file.

**Comment by maehld** [comment]
Hi. Here is the kubeadm config file.

I've tried it again just a few seconds ago and the error remains. If needed I can provide everything from this test server except our vsphere credentials :-)

**Comment by maehld** [comment]
[kubeadm-config.txt](https://github.com/kubernetes/kubernetes/files/1575739/kubeadm-config.txt)

**Comment by andremarianiello** [comment]
@rohitjogvmw docker.io/rohitjogvmw/hyperkube-amd64:ctlr-mgr-fix fixed this issue for me. I believe that any deployment using vsphere cloud-provider will have this issue, but I specifically ran into it while using kubeadm 1.9.0

**Comment by jingxu97** [comment]
@rohitjogvmw is this issue solved?

**Comment by rohitjogvmw** [comment]
Hi Jing,

Issue is resolved in master branch.

**Comment by praseodym** [comment]
I'm still seeing the following error with kube-controller-manager v1.9.2:
```
E0121 20:07:19.616506       1 reflector.go:205] k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go:227: Failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:kube-system:vsphere-cloud-provider" cannot list nodes at the cluster scope
``` 
Furthermore, volume attachments do not work. Downgrading the kube-controller-manager to v1.8.7 fixes the problem.

Any idea on what the problem could be?

**Comment by liggitt** [comment]
@praseodym in 1.9, https://github.com/kubernetes/kubernetes/pull/55845 switched to creating a service account specific to vsphere to run the cloud controller loop.

There was a bug in the name it attempted to create (an upper-case S) that meant it could never succeed. That was what this issue was for, and was fixed in https://github.com/kubernetes/kubernetes/pull/57286 and https://github.com/kubernetes/kubernetes/pull/57774

The issue you are seeing is that the service account has not been given API permissions. How you would do that would depend on what authorization method your deployment set up. @rohitjogvmw might be able to provide more details

**Comment by vijaykatam** [comment]
This worked for me on a 1.9.2 cluster
```
cat <<EOF | kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: vsphere-cloud-provider
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vsphere-cloud-provider
  namespace: kube-system
roleRef:  
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vsphere-cloud-provider
subjects:
- kind: ServiceAccount
  name: vsphere-cloud-provider
  namespace: kube-system
EOF 

```
