### ISSUE TITLE
Kubeadm/Kubelet 1.7.x versions no longer in Centos Repo

### ISSUE THREAD

**Issue by stevenmccord** [kubernetes/kubernetes#57910]
It looks like kubernetes 1.7.2 RPM for CentOS are missing at the repository https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/filelists.xml

This is just like #49500, but I think with the release of 1.9.1 it might have got removed?  

Will you be putting that back in the centos repo?

/sig release
@kubernetes/sig-release

Thanks!

**Comment by strouja** [comment]
Hi, We are severely adversely affected as well. It's even worse than that.  At this time, every version of Kubernetes except 1.9.1 is no longer in the repository.

**Comment by chen23** [comment]
me too.  https://github.com/kubernetes/kubernetes/issues/57913#issuecomment-355680356

**Comment by Secretions** [comment]
me three. Been doing work with 1.8.x and now it's gone. :(

**Comment by mbohlool** [comment]
It has been fixed.

**Comment by Passpes** [comment]
It's not fixed still have same error:

`yum install -y kubelet kubeadm kubectl
Loaded plugins: fastestmirror
base                                                                                                                                                                                     | 3.6 kB  00:00:00
epel/x86_64/metalink                                                                                                                                                                     |  25 kB  00:00:00
extras                                                                                                                                                                                   | 3.4 kB  00:00:00
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] curl#60 - "Peer's Certificate has expired."
Trying other mirror.
It was impossible to connect to the CentOS servers.
This could mean a connectivity issue in your environment, such as the requirement to configure a proxy,
or a transparent proxy that tampers with TLS security, or an incorrect system clock.
You can try to solve this issue by using the instructions on https://wiki.centos.org/yum-errors
If above article doesn't help to resolve this issue please use https://bugs.centos.org/.



 One of the configured repositories failed (Kubernetes),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=kubernetes ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable kubernetes
        or
            subscription-manager repos --disable=kubernetes

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=kubernetes.skip_if_unavailable=true

failure: repodata/repomd.xml from kubernetes: [Errno 256] No more mirrors to try.
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] curl#60 - "Peer's Certificate has expired."
`

**Comment by zud0ku** [comment]
Guys, I had the problem, It happened to be a wrong clock setting. Check your hosts's date and time. 
Problem solved setting correct time and date.
