### ISSUE TITLE
After update docker, the pod lose mounted glusterfs volume

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/kubernetes#58788]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
1. create a rc, and its pod mounted a glusterfs volume by PV and PVC;
2. update docker and do not restart container with ` live-restore: true`
3. the container and pod are normal, but the glusterfs volume can not be accessed any more from container. but the glusterfs volume is normal.
4. restarting pod could resolve this problem.

**What you epected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.9
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`): centOS 7.3
- Install tools: Manual
- Others: docker version 1.12.6

**Comment by zhangxiaoyu-zidif** [comment]
```shell
E0124 18:31:10.050365   27829 glusterfs.go:145] glusterfs: failed to get endpoints 7443a51e-cb9e-416c-8fb1-4251b0e39a2c[an empty namespace may not be set when a resource name is provided]
E0124 18:31:10.050426   27829 reconciler.go:449] Could not construct volume information: MountVolume.NewMounter failed for volume "kubernetes.io/glusterfs/f622d169-00e2-11e8-ad1b-fa163efcd889-7443a51e-cb9e-416c-8fb1-4251b0e39a2c" (spec.Name: "7443a51e-cb9e-416c-8fb1-4251b0e39a2c") pod "f622d169-00e2-11e8-ad1b-fa163efcd889" (UID: "f622d169-00e2-11e8-ad1b-fa163efcd889") with: an empty namespace may not be set when a resource name is provided
```

**Comment by zhangxiaoyu-zidif** [comment]
the log show that we could not find the ep, but in fact the ep is still there, I think I find the reason. it may relate to service and endpoint. we create endpoint without service. so the error message is misunderstanding.
/cc @MrHohn

**Comment by zhangxiaoyu-zidif** [comment]
https://github.com/kubernetes/kubernetes/blob/dd272ea3fd04d41fc95572572a19bf704ab7b062/pkg/volume/glusterfs/glusterfs.go#L154
this code check the service not the endpoint.

**Comment by zhangxiaoyu-zidif** [comment]
https://github.com/kubernetes/kubernetes/blob/dd272ea3fd04d41fc95572572a19bf704ab7b062/staging/src/k8s.io/client-go/rest/request.go#L630

this code show that namespaces is not existed, but it really exists.

**Comment by jsafrane** [comment]
@humblec, does it ring a bell?

**Comment by zhangxiaoyu-zidif** [comment]
```shell
[root@node-4:/home/ubuntu]$ kubectl get pv -n tcfs
NAME                                   CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM            STORAGECLASS   REASON    AGE
5f82ff07-ce69-4348-8bed-d7fa7bf352b5   512Mi      RWX           Retain          Bound     tcfs/test-ok                              23h
7443a51e-cb9e-416c-8fb1-4251b0e39a2c   1Gi        RWX           Retain          Bound     tcfs/pv-docs                              1d
81ff8924-65a5-45cf-b9a7-3faa6aeeb599   512Mi      RWX           Retain          Bound     tcfs/pvcvolume       
```

**Comment by zhangxiaoyu-zidif** [comment]
this may be a bug that, why ep was replaced with pv.

**Comment by zhangxiaoyu-zidif** [comment]
I had checked this issue again, in fact, it has nothing to do with docker update. When I set /etc/docker/daemon.json `live-restore` to true, and restart kubelet, the container could not access to the glusterfs volume.
So I think， container non-restart -> pod -non-restart， but kubelet restart -> mount again;
And mount again failed, so container could not access to volume.
=)

**Comment by zhangxiaoyu-zidif** [comment]
cc @kubernetes/sig-storage-bugs 
I am not sure if other storages have the same problem.

**Comment by zhangxiaoyu-zidif** [comment]
one should be pointed out that:
we create endpoint without service. I guess and am not sure  endpoint name = service name or some prefix + pv name.

**Comment by humblec** [comment]
@zhangxiaoyu-zidif give me some time to go through this, I will get back on this soon.

**Comment by humblec** [comment]
Few observations here:  the issue description says you are using kube 1.6 release. Can you reproduce this issue with kube `1.8 or kube 1.9`?

Why I am asking is below error scenario has been fixed in these versions.

```
E0124 18:31:10.050365   27829 glusterfs.go:145] glusterfs: failed to get endpoints 7443a51e-cb9e-416c-8fb1-4251b0e39a2c[an empty namespace may not be set when a resource name is provided]
E0124 18:31:10.050426   27829 reconciler.go:449] Could not construct volume information: MountVolume.NewMounter failed for volume "kubernetes.io/glusterfs/f622d169-00e2-11e8-ad1b-fa163efcd889-7443a51e-cb9e-416c-8fb1-
```

These errors wont pop in kube 1.8 or 1.9 and also there is a fix for kubelet mount in these latest versions. so if you hit this issue with kube 1.8 or 1.9, please let me know. Because kube `1.6` looks old to me :)

**Comment by zhangxiaoyu-zidif** [comment]
OK， thanks. I will test it recently.

**Comment by zhangxiaoyu-zidif** [comment]
@humblec 
sorry to response this issue for a long time.
After i test this case in kubernetes 1.8.5, the issued bug does not exist any more.
so I think it may relate with kubelet remount...
thanks for your help. =)

**Comment by humblec** [comment]
@zhangxiaoyu-zidif Awesome! Thanks for confirming!

**Comment by zhangxiaoyu-zidif** [comment]
Again checked, no matter whether we set docker's live-restore, the bug occurs. =)

**Comment by foxyriver** [comment]
This should be fixed by #55796

**Comment by adampl** [comment]
I have just experienced this issue with Kubernetes 1.10.1 (Rancher 2.0) on the latest Docker CE.

**Comment by shubb30** [comment]
I am also still experiencing this issue.  I am using Rancher 2.1.8 to manage my clusters, and the clusters were created using RKE.  When I upgraded a cluster from 1.13.4 to 1.13.5 using RKE, the volumes that were mounted as GlusterFS disconnect, whereas the volumes mounted by Longhorn and CEPH remain mounted.

**Comment by adampl** [comment]
@zhangxiaoyu-zidif please reopen
