### ISSUE TITLE
Pod stuck in terminating status

### ISSUE THREAD

**Issue by Alger7w** [kubernetes/kubernetes#59564]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG
> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
Pod stuck in terminating status with corresponding  containers were deleted. Using 'journalctl -u kubelet, see repeated logs:

Feb 08 17:34:12 xxx kubelet[1460]: E0208 17:34:12.136804    1460 kuberuntime_container.go:411] ContainerStatus for 5cb4f3b5c6c93001e60d0ba81b0252306df341308c6bce36ed8c7ad45099b714 error: rpc error: code = 2 desc = unable to inspect docker image "sha256:f32dd44d6009457fc821daff6559518fea48026f5be16c73d71b84a2a471d374" while inspecting docker container "5cb4f3b5c6c93001e60d0ba81b0252306df341308c6bce36ed8c7ad45099b714": no such image: "sha256:f32dd44d6009457fc821daff6559518fea48026f5be16c73d71b84a2a471d374"
Feb 08 17:34:12 xxx kubelet[1460]: E0208 17:34:12.136817    1460 kuberuntime_manager.go:857] getPodContainerStatuses for pod "xxxxx(f82ae8e5-0b1f-11e8-8db6-00163e04c92a)" failed: rpc error: code = 2 desc = unable to inspect docker image "sha256:f32dd44d6009457fc821daff6559518fea48026f5be16c73d71b84a2a471d374" while inspecting docker container "5cb4f3b5c6c93001e60d0ba81b0252306df341308c6bce36ed8c7ad45099b714": no such image: "sha256:f32dd44d6009457fc821daff6559518fea48026f5be16c73d71b84a2a471d374"

**What you expected to happen**:
pod get deleted successfully
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
none
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
kubeadm
- Others:

**Comment by Alger7w** [comment]
Use 'docker ps -a|grep xxx' to see the exited container and delete it, this problem is solved. It seems to be a docker's bug.

**Comment by KeepTheBeats** [comment]
It seems that, delete pod if the image is not exist kubelet will be stuck in this status

**Comment by istaveren** [comment]
This is still an issue.
Start a pod.
Delete the image that is used in the pod with docker rmi -f <image id>
Then delete the pod. 
Kube will hang with 

Warning  FailedSync  73s (x19 over 4m58s)  kubelet, minikube  error determining status: rpc error: code = Unknown desc = unable to inspect docker image "sha256:89a159cee9ae628420377dbcc3963e35a30e1a61ef0b549928b97bdcab260f91" while inspecting docker container "53d42a3262d38b4ac26e3d1e95bf65be38bdf35fe285164a7183ae4e5d8f5941": no such image: "sha256:89a159cee9ae628420377dbcc3963e35a30e1a61ef0b549928b97bdcab260f91

**Comment by invertigo** [comment]
What worked for me (kubernetes provided by docker desktop on windows) was running `docker container prune`.  This allowed the pod to finish terminating.
