### ISSUE TITLE
HPA is refuses to autoscale if DesiredReplicas > MaxReplicas (but I want it to scale up to MaxReplicas)

### ISSUE THREAD

**Issue by huguesalary** [kubernetes/kubernetes#59888]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I have a horizontalPodAutoscaler like this:

```
# irrelevant YAML ommited
spec:
  maxReplicas: 200
  minReplicas: 50
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: production-magento
  targetCPUUtilizationPercentage: 80
status:
  currentCPUUtilizationPercentage: 62
  currentReplicas: 50
  desiredReplicas: 50
```

However, for the past few days, I haven't seen the autoscaler scaling up my pods, even though *I know* it should have: I am watching (with `watch`) my HPA and have noticed multiple time the `80% CPU percentage` limit was crossed.

What I do keep seeing is the following message ` the desired replica count is increasing faster than the maximum scale rate`, when I actually would have expected to see my pods scale up.

```
Name:                                                  production-magento
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Wed, 07 Feb 2018 09:04:52 -0800
Reference:                                             Deployment/production-magento
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  62% (99m) / 80%
Min replicas:                                          50
Max replicas:                                          200
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  the last scale time was sufficiently old as to warrant a new scale
  ScalingActive   True    ValidMetricFound  the HPA was able to succesfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  True    TooFewReplicas    the desired replica count is increasing faster than the maximum scale rate
Events:           <none>
```

**What you expected to happen**:

I would expect the HPA to scale up my pods (up to `MaxReplicas`)

**How to reproduce it (as minimally and precisely as possible)**:

I think (but have not been able to verify) the issue is that my `MaxReplicas` is set to `200` and the HPA currently calculates that it needs to autoscale over `200` replicas. 

One way to reproduce is to modify the code in charge of HPA and artificially inflate the `DesiredReplicas` to always be over `MaxReplicas`. This should prevent the autoscaler from ever scaling up, even if it has room to do so.

**Anything else we need to know?**:

I searched the github issues and found issue #53670 which states:

> Since upgrading to Kube 1.7.6, I'm seeing my HPAs scale above it's maxReplicas. Because of this, it's rapidly creating pods, then terminating them, and repeat.

This issue was fixed with PR #53690.

And reading the code I believe PR #53690 might be what is causing my issue; specifically this: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L526

The condition flat out denies the autoscaler from autoscaling `if scaleUpLimit > hpa.Spec.MaxReplicas`. 

I think the condition should be relaxed and the autoscaler should be allowed to scale all the way **up to** `MaxReplicas`, that is, if the desired amount of replicas **is bigger than** `MaxReplicas`, the autoscaler should scale **all the way to** `MaxReplicas`.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.2-gke.1", GitCommit:"4ce7af72d8d343ea2f7680348852db641ff573af", GitTreeState:"clean", BuildDate:"2018-01-31T22:30:55Z", GoVersion:"go1.9.2b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): mac os
- Kernel (e.g. `uname -a`): high sierra

**Comment by huguesalary** [comment]
@kubernetes/sig-autoscaling-bugs

**Comment by huguesalary** [comment]
Re-reading the code, I realize that the HPA *does* scale *up to* `MaxReplicas` (https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L543). However, for some reason, when I `kubectl describe` my HPA, all I see is `ScalingLimited  True    TooFewReplicas    the desired replica count is increasing faster than the maximum scale rate` which makes me think it didn't autoscale.

I might be mistaken, and my pods might have been autoscaled, however, doing a `kubectl get pods` and looking at the their `Age` (which currently is over 19 hours), makes me think they weren't: all my pods are 19 hours old.
I would expect `kubectl get pods` to show both old pods and younger pods, after a scaleUp/scaleDown.

**Comment by DirectXMan12** [comment]
`is increasing faster than the maximum scale rate` means that we've rate limited the size of the scale that happens at once (it's a percentage of the current replicas) so that you don't go directly from `5 -> 500` pods.

**Comment by huguesalary** [comment]
@DirectXMan12 yes the message makes sense. But I haven't noticed more pods being added.

**Comment by huguesalary** [comment]
As a test, I increased my "MaxReplica" from 200 to 400. I was finally able to see my pods scale up and obvious messages indicating so when I run `kubectl describe hpa` (in the `events` section):

```
Name:                                                  production-magento
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Wed, 07 Feb 2018 09:04:52 -0800
Reference:                                             Deployment/production-magento
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  65% (104m) / 80%
Min replicas:                                          50
Max replicas:                                          400
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  the last scale time was sufficiently old as to warrant a new scale
  ScalingActive   True    ValidMetricFound  the HPA was able to succesfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  True    TooFewReplicas    the desired replica count is increasing faster than the maximum scale rate
Events:
  Type    Reason             Age               From                       Message
  ----    ------             ----              ----                       -------
  Normal  SuccessfulRescale  43m (x2 over 1h)  horizontal-pod-autoscaler  New size: 60; reason: cpu resource utilization (percentage of request) above target
  Normal  SuccessfulRescale  37m (x6 over 4d)  horizontal-pod-autoscaler  New size: 50; reason: All metrics below target
```

This indicates to me that it is likely that the autoscaler isn't autoscaling up to MaxReplica when `the desired replica count is increasing faster than the maximum scale rate`.

**Comment by mattjmcnaughton** [comment]
Hi @huguesalary - thanks for reaching out about this :)

I'm surprised to see the reason `TooFewReplicas` matched with the message `the desired replica count is increasing faster than than the maximum scale rate`. It should say "the desired replica count is less than the minimum replica count" - and I think that its a bug that it does not. Does what your saying make more sense if we replace the `"desired replica count is increasing faster..."` message with the `"the desired replica count is less than the minimum replica count"` message?

Regardless, I'll fix the improper message and my apologies for the confusion.

**Comment by huguesalary** [comment]
Hi @mattjmcnaughton 

I'm not convinced the issue is _only_ with the messaging, and supporting this intuition is my previous comment (https://github.com/kubernetes/kubernetes/issues/59888#issuecomment-365783845): until I set my `MaxReplicas` to a higher number than 200, my pods would not scale up even though they needed to. I'll see if I can confirm that.

**Comment by jberkus** [comment]
oops, missing priority was my fault, moving back into milestone:

/priority critical-urgent
/remove-priority important-soon

**Comment by huguesalary** [comment]
Glad to see it made it to the milestone! 

Does that mean you guys managed to reproduces this?

**Comment by DirectXMan12** [comment]
I have not had time to personally reproduce (I'm going to attempt to do so Monday and find a fix), but from your description, it definitely *seems* like a serious issue, and I'd prefer not to release with it in place.  I want it on my radar unless we find we can't repro.

**Comment by DirectXMan12** [comment]
/status in-progress

In progress, attempting to reproduce.  Hope to reproduce today or tomorrow, expect fix to not be terribly complicated

**Comment by DirectXMan12** [comment]
Unable to reproduce on either the given Kubernetes version (1.9.2) or master.  Considering that we're decently into code freeze, I'm going to pull this from the milestone.  If we can get a reproducer, we'll work on it for 1.11.

**Comment by DirectXMan12** [comment]
For future reference, my attempt went as follows:

1. Deploy https://github.com/DirectXMan12/fake-metrics-server, and register it as providing metrics.k8s.io
2. Create a ReplicaSet which calls `sleep 1000m`, with a CPU request of `1m`
3. Make kubelet take 300 pods at once
3. Create an HPA targetting 1% usage, with min 50, max 200

**Comment by squarelover** [comment]
I'm experiencing these messages. I'm not understanding if the message means that it's trying to scale the service but is unable to because of the rate of scaling or will scale than my max, or if the values want to scale below my minimum value. Has this been fixed in later versions?

**Comment by slashr** [comment]
I'm facing this problem too. Tried increasing and decreasing the number of "Max replicas" but to no avail.

**Comment by AlexLast** [comment]
Also seeing the same issue in `1.10`

**Comment by bpownow** [comment]
Seeing the same issue in `1.14`

**Comment by premsonbaby** [comment]
Same issue in 1.15, either there is a bug in the HPA, or there is some type of understanding mistake due to the message.

**In simple terms my** 
  minReplicas: 1
  maxReplicas: 10

**based on** 
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50

My expectation is HPA will increase or decrease the number of pods between the range of 1 to 10 to keep the average CPU utilization across all pods 50%. (even after creating 10 pods CPU utilization is going up then HPA can give up that's fine). I don't think this is what happening at the moment. 
What is the rate of scale? and if that's higher than max replicas then whats the point of setting max Replicas?  

I am using "virtual-node-aci-linux"

**Comment by omerlh** [comment]
Also seeing similar issue with nginx ingress, hpa on memory and Kubernetes 1.12.

**Comment by FloraSaysGoodmorning** [comment]
same thing in v1.13
```
- lastTransitionTime: "2019-11-12T03:26:22Z"
      message: the desired replica count is increasing faster than the maximum scale
        rate
      reason: TooFewReplicas
      status: "True"
      type: ScalingLimited
    currentMetrics:
    - external:
        currentAverageValue: "0"
        currentValue: "0"
        metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
        metricSelector:
          matchLabels:
            resource.labels.subscription_id: <some subscription>
      type: External
    currentReplicas: 1
    desiredReplicas: 1
```

**Comment by Binyamse** [comment]
same thing in v1.14

`ScalingLimited  True    TooFewReplicas    the desired replica count is increasing faster than the maximum scale rate
Events:           <none>`

**Comment by IzekChen** [comment]
Same in v1.14
ScalingLimited  True    TooFewReplicas    the desired replica count is increasing faster than the maximum scale rate

How did you guys solve the issue? Recreate the HPA or?

**Comment by lli-hiya** [comment]
This should be fixed in v1.16 with this PR:  https://github.com/kubernetes/kubernetes/commit/d55f037b7d84e61c81a6b8c20606bb06b6eb20f2.  More specifically, this part: https://github.com/kubernetes/kubernetes/blob/d55f037b7d84e61c81a6b8c20606bb06b6eb20f2/pkg/controller/podautoscaler/horizontal.go#L711-L747

**Comment by pslobo** [comment]
I'm still seeing a similar issue and I'm running 1.16.9 on GKE.

```
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  recommended size matches current size
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  True    TooFewReplicas    the desired replica count is increasing faster than the maximum scale rate
Events:           <none>


❯ k version --short
Client Version: v1.18.3
Server Version: v1.16.9-gke.6
```

**Comment by saralpa** [comment]
Is this issue resolved?

**Comment by teebu** [comment]
I'm seeing the same message, I scale based on service bus topic and sent 1000 messages. 

```
 conditions:
    - type: AbleToScale
      status: 'True'
      lastTransitionTime: '2022-08-22T20:30:40Z'
      reason: SucceededRescale
      message: the HPA controller was able to update the target scale to 4
    - type: ScalingActive
      status: 'True'
      lastTransitionTime: '2022-08-22T20:30:40Z'
      reason: ValidMetricFound
      message: >-
        the HPA was able to successfully calculate a replica count from external
        metric
        s0-azure-servicebus-eventing-helloworld-topic-cypher(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name:
        hello-world,},MatchExpressions:[]LabelSelectorRequirement{},})
    - type: ScalingLimited
      status: 'True'
      lastTransitionTime: '2022-08-22T20:31:27Z'
      reason: ScaleUpLimit
      message: >-
        the desired replica count is increasing faster than the maximum scale
        rate
```

The pods spawn, but immediately get terminated.

**Comment by sushruth13** [comment]
This issue still exists in 
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.25.0

  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    SucceededRescale  the HPA controller was able to update the target scale to 10
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  True    ScaleUpLimit      the desired replica count is increasing faster than the maximum scale rate

The scaler creates new replicas and then it for some inexplicable reason terminates it all
