### ISSUE TITLE
Service hangs when endpoints are not available

### ISSUE THREAD

**Issue by tirumaraiselvan** [kubernetes/kubernetes#60124]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig network

**What happened**:

If we access a service which has no endpoints ( say underlying pods are not ready or replicas are 0) from within a pod, it times out. If the same service is accessed directly from a node, it terminates immediately with a connection refused message as expected.

@thockin (in mailing list) said: For traffic from within a pod, it traverses neither filter's INPUT nor OUTPUT chains, only FORWARD.
https://groups.google.com/forum/#!msg/kubernetes-dev/qa2rwGp_DVo/wSMdB-ShBgAJ

**What you expected to happen**:

Expected the connection to terminate immediately from within the pod as well so we can retry quickly.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a Deployment (www) with replicas 0
- Create a Service (www) with that deployment
- curl {www-service-ip} (from a pod inside the cluster) - times out
- ssh into a node
- curl {www-service-ip} - terminates immediately

**Anything else we need to know?**:

An e2e test should include checks for this behaviour.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.2 and prior
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tirumaraiselvan** [comment]
Potentially resolved by https://github.com/kubernetes/kubernetes/pull/57461

**Comment by thockin** [comment]
I turned up a cluster from head, and it still exists.

I added a REJECT rule to the FORWARD chain, and it works.  BUT there are issues.

a) @danwinship who just spent time optimizing for paths here

b) @caseydavenport - calico's rule explicitly ALLOWs anything from cali-* interfaces and it seems to force itself to the front of the queue.

How can we make these pieces coordinate?  Do we need a KUBE-FORWARD-FIRST and KUBE-FORWARD-LAST split?  Should Calico (and everyone) be responsible for REJECTing services with no endpoints?  Do we just define this as an implementation detail and ignore it?

**Comment by caseydavenport** [comment]
> calico's rule explicitly ALLOWs anything from cali-* interfaces and it seems to force itself to the front of the queue

Yeah, Calico is by default pretty aggressive in making sure it's policy isn't preempted - it will try to keep its rules at the top.

My first thought is:
- that this is a Services implementation detail
- we should fix this in the iptables proxy because rejecting the connections seems desirable. 

As for Calico compatibility, there is an option to use RETURN jumps instead of ACCEPT which seems like it could help in this scenario, so long as kube-proxy is programming the ACCEPT rules for traffic sourced within the cluster cidr.
