### ISSUE TITLE
[test failed] [1.10 upgrade] Proxy version v1

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#60769]
the tests are failing in http://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-master

/sig network
/priority failing-test
/priority critical-urgent
/kind bug
/status approved-for-milestone

cc @jdumars @jberkus
/assign @thockin @dcbw @caseydavenport

**Comment by liggitt** [comment]
getting a 404 on the request. is there any chance these are 1.9 e2e tests running on a 1.10 master?

**Comment by liggitt** [comment]
appears to be... `404; 17.489542ms): path /api/v1/proxy/namespaces/e2e-tests-proxy-6gpj9`

the deprecated `/api/v1/proxy/...` paths were removed in https://github.com/kubernetes/kubernetes/pull/59884

do we need to go back and conditionally disable these tests in the 1.9 branch?

/assign @mikedanese

**Comment by jdumars** [comment]
@mikedanese any update on this?

**Comment by liggitt** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/61135

**Comment by krzyzacy** [comment]
looks like http://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-cluster-parallel is still failing on this, which should have the 1.9 fix in

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/61289 to correctly skip those tests

**Comment by liggitt** [comment]
Green run of http://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-cluster-parallel

Properly skipped these tests

/close
