### ISSUE TITLE
./hack/local-up-cluster.sh fails on Fedora rawhide

### ISSUE THREAD

**Issue by adelton** [kubernetes/kubernetes#61474]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I attempted to start all-on-one testing environment with

```
ENABLE_DAEMON=true PATH='$(pwd)/kubernetes/third_party/etcd:${PATH}' ./hack/local-up-cluster.sh
```

on Fedora rawhide, the way it works just fine on Fedora 27. The node never becomes `Ready`.

**What you expected to happen**:

The `./hack/local-up-cluster.sh` finishing and the node `127.0.0.1` becoming `Ready` shortly after.

**How to reproduce it (as minimally and precisely as possible)**:

```
git clone https://github.com/kubernetes/kubernetes.git
( cd kubernetes && ./hack/install-etcd.sh )
( cd kubernetes && ENABLE_DAEMON=true PATH='$(pwd)/kubernetes/third_party/etcd:${PATH}' ./hack/local-up-cluster.sh )
kubectl get nodes
```

**Anything else we need to know?**:

On Fedora 27, these steps give me working setup.

The `kubectl describe node 127.0.0.1` says (among others)
```
Conditions:
  Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason                    Message
  ----             ------    -----------------                 ------------------                ------                    -------
  OutOfDisk        Unknown   Wed, 21 Mar 2018 09:23:21 -0400   Wed, 21 Mar 2018 09:24:04 -0400   NodeStatusUnknown         Kubelet stopped posting node status.
  MemoryPressure   Unknown   Wed, 21 Mar 2018 09:23:21 -0400   Wed, 21 Mar 2018 09:24:04 -0400   NodeStatusUnknown         Kubelet stopped posting node status.
  DiskPressure     Unknown   Wed, 21 Mar 2018 09:23:21 -0400   Wed, 21 Mar 2018 09:24:04 -0400   NodeStatusUnknown         Kubelet stopped posting node status.
  PIDPressure      False     Wed, 21 Mar 2018 09:23:21 -0400   Wed, 21 Mar 2018 09:23:21 -0400   KubeletHasSufficientPID   kubelet has sufficient PID available
  Ready            Unknown   Wed, 21 Mar 2018 09:23:21 -0400   Wed, 21 Mar 2018 09:24:04 -0400   NodeStatusUnknown         Kubelet stopped posting node status.
```

The `/tmp/kubelet.log` ends with
```
I0321 09:23:23.492042   27717 factory.go:110] Factory "systemd" can handle container "/system.slice/dev-hugepages.mount", but ignoring.
I0321 09:23:23.492059   27717 factory.go:110] Factory "systemd" can handle container "/system.slice/tmp.mount", but ignoring.
I0321 09:23:23.496752   27717 cpu_manager.go:155] [cpumanager] starting with none policy
I0321 09:23:23.496810   27717 cpu_manager.go:156] [cpumanager] reconciling every 10s
I0321 09:23:23.496830   27717 policy_none.go:42] [cpumanager] none policy: Start
I0321 09:23:23.517797   27717 factory.go:113] Using factory "raw" for container "/libcontainer_27717_systemd_test_default.slice"
I0321 09:23:23.518259   27717 manager.go:997] Added container: "/libcontainer_27717_systemd_test_default.slice" (aliases: [], namespace: "")
I0321 09:23:23.518614   27717 container.go:448] Start housekeeping for container "/libcontainer_27717_systemd_test_default.slice"
I0321 09:23:23.521188   27717 manager.go:1054] Destroyed container: "/libcontainer_27717_systemd_test_default.slice" (aliases: [], namespace: "")
E0321 09:23:23.527391   27717 node_container_manager.go:52] Failed to create "/kubepods" cgroup
F0321 09:23:23.527441   27717 kubelet.go:1363] Failed to start ContainerManager Delegation not available for unit type
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-alpha.0.1341+c5d4a032d73f90", GitCommit:"c5d4a032d73f90f286fde1a7ca3e782538c47f58", GitTreeState:"clean", BuildDate:"2018-03-21T13:21:57Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-alpha.0.1341+c5d4a032d73f90", GitCommit:"c5d4a032d73f90f286fde1a7ca3e782538c47f58", GitTreeState:"clean", BuildDate:"2018-03-21T13:21:57Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
I0321 09:23:21.140790   27717 manager.go:227] Machine: {NumCores:8 CpuFrequency:2412325 MemoryCapacity:16817651712 HugePages:[{PageSize:2048 NumPages:0}] MachineID:f72669acdc2840be9a3ca8a2019e3fdb SystemUUID:00020003-0004-0005-0006-000700080009 BootID:39dff605-2d5a-4abc-9cc8-c26c44c0c601 Filesystems:[{Device:tmpfs DeviceMajor:0 DeviceMinor:20 Capacity:8408825856 Type:vfs Inodes:2052936 HasInodes:true} {Device:/dev/mapper/fedora-root DeviceMajor:253 DeviceMinor:0 Capacity:16095641600 Type:vfs Inodes:7864320 HasInodes:true} {Device:/dev/sda1 DeviceMajor:8 DeviceMinor:1 Capacity:1023303680 Type:vfs Inodes:65536 HasInodes:true}] DiskMap:map[253:1:{Name:dm-1 Major:253 Minor:1 Size:8476688384 Scheduler:none} 253:2:{Name:dm-2 Major:253 Minor:2 Size:897581056 Scheduler:none} 253:3:{Name:dm-3 Major:253 Minor:3 Size:346738917376 Scheduler:none} 253:4:{Name:dm-4 Major:253 Minor:4 Size:346738917376 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:896998047744 Scheduler:cfq} 253:0:{Name:dm-0 Major:253 Minor:0 Size:16106127360 Scheduler:none}] NetworkDevices:[{Name:enp2s0 MacAddress:00:d0:68:10:03:66 Speed:1000 Mtu:1500} {Name:enp3s0 MacAddress:00:d0:68:10:03:67 Speed:-1 Mtu:1500}] Topology:[{Id:0 Memory:4159594496 Cores:[{Id:0 Threads:[0] Caches:[{Size:65536 Type:Data Level:1} {Size:65536 Type:Instruction Level:1} {Size:1048576 Type:Unified Level:2}]} {Id:1 Threads:[1] Caches:[{Size:65536 Type:Data Level:1} {Size:65536 Type:Instruction Level:1} {Size:1048576 Type:Unified Level:2}]}] Caches:[]} {Id:1 Memory:4227317760 Cores:[{Id:0 Threads:[2] Caches:[{Size:65536 Type:Data Level:1} {Size:65536 Type:Instruction Level:1} {Size:1048576 Type:Unified Level:2}]} {Id:1 Threads:[3] Caches:[{Size:65536 Type:Data Level:1} {Size:65536 Type:Instruction Level:1} {Size:1048576 Type:Unified Level:2}]}] Caches:[]} {Id:2 Memory:4203909120 Cores:[{Id:0 Threads:[4] Caches:[{Size:65536 Type:Data Level:1} {Size:65536 Type:Instruction Level:1} {Size:1048576 Type:Unified Level:2}]} {Id:1 Threads:[5] Caches:[{Size:65536 Type:Data Level:1} {Size:65536 Type:Instruction Level:1} {Size:1048576 Type:Unified Level:2}]}] Caches:[]} {Id:3 Memory:4226830336 Cores:[{Id:0 Threads:[6] Caches:[{Size:65536 Type:Data Level:1} {Size:65536 Type:Instruction Level:1} {Size:1048576 Type:Unified Level:2}]} {Id:1 Threads:[7] Caches:[{Size:65536 Type:Data Level:1} {Size:65536 Type:Instruction Level:1} {Size:1048576 Type:Unified Level:2}]}] Caches:[]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
```
- OS (e.g. from /etc/os-release):
```
NAME=Fedora
VERSION="29 (Rawhide)"
ID=fedora
VERSION_ID=29
PRETTY_NAME="Fedora 29 (Rawhide)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=rawhide
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=rawhide
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
```
- Kernel (e.g. `uname -a`):
```
Linux redacted.example.com 4.16.0-0.rc5.git3.1.fc29.x86_64 #1 SMP Fri Mar 16 15:28:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

```
systemd-238-4.fc29.x86_64
```

**Comment by dims** [comment]
@adelton can you bump LOG_LEVEL env variable to say 10 before you run local-up-cluster.sh and see if we catch any other logs? (looks like we are hitting something deep in systemd - https://github.com/systemd/systemd/blob/master/src/core/dbus-cgroup.c#L355)

**Comment by adelton** [comment]
Now the `kubelet.log` ends with

```
I0321 10:22:51.143239   22943 container.go:448] Start housekeeping for container "/libcontainer_22943_systemd_test_default.slice"
W0321 10:22:51.144407   22943 container.go:406] Failed to get RecentStats("/libcontainer_22943_systemd_test_default.slice") while determining the next housekeeping: unable to find data for container /libcontainer_22943_systemd_test_default.slice
I0321 10:22:51.144413   22943 manager.go:1054] Destroyed container: "/libcontainer_22943_systemd_test_default.slice" (aliases: [], namespace: "")
I0321 10:22:51.144473   22943 handler.go:325] Added event &{/libcontainer_22943_systemd_test_default.slice 2018-03-21 10:22:51.144455959 -0400 EDT m=+3.030844677 containerDeletion {<nil>}}
E0321 10:22:51.152560   22943 node_container_manager.go:52] Failed to create "/kubepods" cgroup
F0321 10:22:51.152602   22943 kubelet.go:1363] Failed to start ContainerManager Delegation not available for unit type
```

**Comment by adelton** [comment]
By the way, I see the same situation on Fedora 28 nightly composes, with `systemd-238-3.fc28.x86_64`.

**Comment by jmontleon** [comment]
I updated my system from F27 to F28 and hit the same issue.

`dnf downgrade systemd --releasever=27` brought me down from systemd 238 to 234 and I am able to successfully run `oc cluster up` now

**Comment by jmontleon** [comment]
@dims it looks like that line was added as part of a PR that removed permission to delegate from most unit types,

https://github.com/systemd/systemd/commit/1d9cc8768f173b25757c01aa0d4c7be7cd7116bc

That would makes sense of the error we're seeing, "Failed to start ContainerManager Delegation not available for unit type"

I don't know which unit type is being denied based on the message, and short of patching systemd, I don't see a way to configure which unit types are permitted to delegate.

**Comment by dims** [comment]
@jmontleon no clues in the system logs?

**Comment by jmontleon** [comment]
@dims I was able to get a little help with this in #systemd on freenode.

```
<dreisner> jmontleon: "failed to start ContainerManager" <- ContainerManager is likely the the value of the Description field in one of your units.
<zdzichu>   libcontainerSystemd libcontainerCgroupManagerType = "systemd"
<zdzichu>  // systemdSuffix is the cgroup name suffix for systemd
<zdzichu>  systemdSuffix string = ".slice"
<zdzichu> let me guess... ContainerManager.slice ?
<dreisner> https://github.com/kubernetes/kubernetes/issues/61474
<zdzichu> dreisner: yep, we're going in circles here
<zdzichu> it's up to discussion between kubernetes people and lennart: why he limited ability to delegate and why they need to delegate .slice control
```
It looks like it's here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cgroup_manager_linux.go#L43-L50

I added `.can_delegate = true` at https://github.com/systemd/systemd/blob/master/src/core/slice.c#L376 and rebuilt/reinstalled systemd and after that I was able run oc cluster up successfully.

**Comment by zdzichu** [comment]
and @poettering, I suppose

**Comment by filbranden** [comment]
I believe systemd/systemd#8573 might fix this... I need to test that, though. Will do and ping back here.

**Comment by jmontleon** [comment]
@filbranden thanks! I just rebuilt the systemd package with this Patch, installed, retried and I can run oc cluster up successfully.

@dims ^

**Comment by filbranden** [comment]
@jmontleon Thanks for testing, that's awesome!

**Comment by filbranden** [comment]
@adelton, @jmontleon Can you please check that opencontainers/runc#1776 fixes your problem? You'd have to apply that on top of Kubernetes vendored opencontainers/runc... I guess you know how that works, right? I'd appreciate if you can do that, since I don't have a Kubernetes on Rawhide environment right now, so I guess you're better positioned to confirm that that works as expected... Thanks!

**Comment by filbranden** [comment]
Hi @adelton , so PR #61926 should close the loop here bringing all the changes to libcontainer into our vendored copy... Once we merge that into head, I'll take a look at doing the same on 1.10 and 1.9 release branches.

Cheers!
Filipe

**Comment by adelton** [comment]
I've tested now with `git clone -b cgroupdriver10 https://github.com/filbranden/kubernetes` on Fedora rawhide and the node becomes `Ready`, so that's good.

However, subsequent attempt to create simple pod with

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
```

results in

```Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"No such device or address\""
```

Is that expected? Should I file separate issue or wait for https://github.com/kubernetes/kubernetes/pull/61926 merge?

**Comment by filbranden** [comment]
@adelton That error says `Error response from daemon:` so I'm almost certain it's coming from Docker/containerd/cri-o and the runc they're using...

The packages for those components in Fedora Rawhide will also need the fixes in runc/libcontainer, particularly opencontainers/runc#1776, otherwise they will fail in similar ways too.

I think we still need to address opencontainers/runc#1781 and get that pushed everywhere as well... Otherwise if the timeout in libcontainer is triggered (if systemd creation of cgroups and/or D-Bus response takes longer than 1s) then libcontainer will get stuck and deadlocked...

But, in any case, if you could try to rebuild docker + runc with latest libcontainer and see if that fixes the bug you're seeing, that would be very helpful!

Cheers,
Filipe

**Comment by filbranden** [comment]
@adelton The problem is when using the `--cpu-shares` argument:

```shell
$ sudo docker run --cpu-shares 2 --rm -ti fedora:27 date
/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"No such device or address\"".
```

For the record, `"No such device or address"` is from systemd returning ENXIO error when starting the transient unit.

(Today I learned: `dbus-monitor`! :smile:)

I'm still unsure why this started failing now... But I have a reproducer now and I'll keep investigating. We can probably use this bug, since it's essentially about running Kubelet on Fedora Rawhide, so that's probably part of it as well...

Cheers,
Filipe

**Comment by filbranden** [comment]
@adelton This is fixed (at least the minimal reproducer of `docker run --cpu-shares 2`) with projectatomic/runc#10, but there might be more stuff broken later on...

The problem now is really between docker and systemd in Fedora Rawhide...

I think we can close this one since this has already been sorted out from Kubernetes side... Agreed?

**Comment by adelton** [comment]
I confirm that the

```
docker run --cpu-shares 2 --rm -ti fedora:27 date
```

regressed between Fedora 27 with

```
systemd-234-10.git5f8984e.fc27.x86_64
docker-1.13.1-51.git4032bd5.fc27.x86_64
```

and Fedora rawhide with

```
systemd-238-7.fc29.x86_64
docker-1.13.1-52.git89b0e65.fc29.x86_64
```

Is that something we should filed bugzilla against Fedora? Or how do we want to report and track it?

**Comment by filbranden** [comment]
@adelton See my last comment, projectatomic/runc#10 should fix that.

The problem is that runc/libcontainer is sending this information to systemd as an int64, while systemd expects it as a uint64. It turns out D-Bus is really strong typed and will refuse to convert between those.

I believe systemd switched from signed to unsigned but I think this was really long ago (haven't really checked.)

Backporting projectatomic/runc#10 and rebuilding the RPM on Rawhide fixed it to me, but there might be other places that need fixing. In particular, the upstream of that PR had many follow ups later on.

I think Red Hat bugzilla is the best way to track this, since it's definitely not a Kubernetes issue...

We still need this one Issue here in Kubernetes until PR #61926 gets merged... But that one is still missing one fix in upstream libcontainer: opencontainers/runc#1781, which I'm having trouble getting traction to have reviewed... If you could take a look?

Cheers,
Filipe

**Comment by adelton** [comment]
> I think Red Hat bugzilla is the best way to track this, since it's definitely not a Kubernetes issue...

I've filed https://bugzilla.redhat.com/show_bug.cgi?id=1571736 now.

**Comment by adelton** [comment]
> which at the moment should works around kubernetes/systemd interaction

Which interaction do you have in mind? Starting the Kubernetes cluster, or running the pod? Even with that version, running the pod still fails with

```
Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"No such device or address\""
```

**Comment by adelton** [comment]
> Backporting projectatomic/runc#10 and rebuilding the RPM on Rawhide fixed it to me, but there might be other places that need fixing. In particular, the upstream of that PR had many follow ups later on.

This is backporting into which rpm? `kubernetes`? `docker`? Have you got a link to a scratch build?

**Comment by adelton** [comment]
@filbranden, sorry for not being able to help with the review at the moment, currently I don't have the capacity to untangle which pull request fixes which issue and how it relates to the test results I can see internally.

My running theory is that https://bugzilla.redhat.com/show_bug.cgi?id=1571736 is a blocker to move forward on Fedora rawhide (which has systemd 238). Is that correct? Is that the only blocker that we are aware of?

**Comment by zdzichu** [comment]
@adelton Starting the Kubernetes, as this very issue is about `Failed to start ContainerManager Delegation not available for unit type`. Running the pod should be in another issue.

**Comment by adelton** [comment]
Ah, ok, thanks. So with `systemd-238-7.fc29.1.x86_64`, it is no longer necessary to use the https://github.com/kubernetes/kubernetes/pull/61926 / https://github.com/filbranden/kubernetes/tree/cgroupdriver10 to make the cluster start work.

**Comment by soltysh** [comment]
On a recent systemd (`238-8.git0e0aa59.fc28`) on F28 the problem is back with latest [master](https://github.com/kubernetes/kubernetes/commit/1635393bd1cb21e82fbc899ce7fd6a997194abe2).

**Comment by jmontleon** [comment]
It's a new bug. Similar workaround is possible.

https://bugzilla.redhat.com/show_bug.cgi?id=1584909

**Comment by filbranden** [comment]
Please see projectatomic/runc#10, which apparently hasn't been given attention yet...

But actually, I think you need to pull more from upstream runc into that repository (as that one commit seemed to be part of a larger overhaul there.)

Should we close this one again?

Cheers,
Filipe

**Comment by adelton** [comment]
The same issue is happening with OpenShift packaged in Fedora rawhide as origin-node-3.9.0-2.fc29.x86_64.

**Comment by jdoss** [comment]
/remove-lifecycle rotten

I believe this still impacts Fedora 29 when trying to install OKD 3.11. 

systemd-239-6.git9f3aed1.fc29.x86_64

```
# cat /etc/redhat-release 
Fedora release 29 (Twenty Nine)
```

**Comment by coveritytest** [comment]
Still a problem on Fedora 29 (Server Edition), Kubelet won't start on node with this error:

`Nov 13 10:29:35 fed-node1 kubelet[4597]: I1113 10:29:35.241311    4597 volume_manager.go:247] Starting Kubelet Volume Manager
Nov 13 10:29:35 fed-node1 kubelet[4597]: I1113 10:29:35.243027    4597 server.go:945] Started kubelet
Nov 13 10:29:35 fed-node1 kubelet[4597]: I1113 10:29:35.243167    4597 desired_state_of_world_populator.go:129] Desired state populator starts to run
Nov 13 10:29:35 fed-node1 kubelet[4597]: I1113 10:29:35.339142    4597 kubelet.go:1799] skipping pod synchronization - [container runtime is down]
Nov 13 10:29:35 fed-node1 kubelet[4597]: I1113 10:29:35.341614    4597 kubelet_node_status.go:271] Setting node annotation to enable volume controller attach/detach
Nov 13 10:29:35 fed-node1 kubelet[4597]: I1113 10:29:35.349112    4597 kubelet_node_status.go:82] Attempting to register node fed-node1
Nov 13 10:29:35 fed-node1 kubelet[4597]: I1113 10:29:35.368355    4597 kubelet_node_status.go:127] Node fed-node1 was previously registered
Nov 13 10:29:35 fed-node1 kubelet[4597]: I1113 10:29:35.368699    4597 kubelet_node_status.go:85] Successfully registered node fed-node1
Nov 13 10:29:35 fed-node1 kubelet[4597]: I1113 10:29:35.539567    4597 kubelet.go:1799] skipping pod synchronization - [container runtime is down]
Nov 13 10:29:35 fed-node1 kubelet[4597]: I1113 10:29:35.940217    4597 kubelet.go:1799] skipping pod synchronization - [container runtime is down]
Nov 13 10:29:36 fed-node1 kubelet[4597]: I1113 10:29:36.740533    4597 kubelet.go:1799] skipping pod synchronization - [container runtime is down]
Nov 13 10:29:37 fed-node1 kubelet[4597]: I1113 10:29:37.631403    4597 cpu_manager.go:155] [cpumanager] starting with none policy
Nov 13 10:29:37 fed-node1 kubelet[4597]: I1113 10:29:37.631711    4597 cpu_manager.go:156] [cpumanager] reconciling every 10s
Nov 13 10:29:37 fed-node1 kubelet[4597]: I1113 10:29:37.631818    4597 policy_none.go:42] [cpumanager] none policy: Start
Nov 13 10:29:37 fed-node1 kubelet[4597]: E1113 10:29:37.736002    4597 node_container_manager.go:52] Failed to create "/kubepods" cgroup
Nov 13 10:29:37 fed-node1 kubelet[4597]: F1113 10:29:37.736181    4597 kubelet.go:1359] Failed to start ContainerManager Delegation not available for unit type
`

**Comment by adelton** [comment]
Interesting, on my Fedora 29 with `systemd-239-6.git9f3aed1.fc29.x86_64`

```
cd kubernetes && ENABLE_DAEMON=true SERVICE_CLUSTER_IP_RANGE=10.254.0.0/16  PATH='/mnt/tests/kubernetes/install/local-cluster-up/kubernetes/third_party/etcd:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/root/bin' ./hack/local-up-cluster.sh
```

works fine, as it did on Fedora 28. In `/tmp/kubelet.log`, I see

```
I1113 03:53:54.268217    4715 server.go:999] Started kubelet
I1113 03:53:54.268322    4715 server.go:133] Starting to listen on 127.0.0.1:10250
E1113 03:53:54.268522    4715 kubelet.go:1295] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data in memory cache
I1113 03:53:54.268562    4715 server.go:153] Starting to listen read-only on 127.0.0.1:10255
I1113 03:53:54.268774    4715 server.go:459] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"127.0.0.1", UID:"127.0.0.1", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'Starting' Starting kubelet.
I1113 03:53:54.270541    4715 server.go:318] Adding debug handlers to kubelet server.
I1113 03:53:54.273388    4715 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
I1113 03:53:54.273422    4715 status_manager.go:152] Starting to sync pod status with apiserver
I1113 03:53:54.273439    4715 kubelet.go:1812] Starting kubelet main sync loop.
I1113 03:53:54.273461    4715 kubelet.go:1829] skipping pod synchronization - [container runtime status check may not have completed yet PLEG is not healthy: pleg has yet to be successful]
I1113 03:53:54.273761    4715 volume_manager.go:246] The desired_state_of_world populator starts
I1113 03:53:54.273776    4715 volume_manager.go:248] Starting Kubelet Volume Manager
I1113 03:53:54.273809    4715 desired_state_of_world_populator.go:130] Desired state populator starts to run
I1113 03:53:54.370274    4715 factory.go:356] Registering Docker factory
I1113 03:53:54.371536    4715 factory.go:54] Registering systemd factory
I1113 03:53:54.371800    4715 factory.go:97] Registering Raw factory
I1113 03:53:54.372039    4715 manager.go:1222] Started watching for new ooms in manager
I1113 03:53:54.373568    4715 kubelet.go:1829] skipping pod synchronization - [container runtime status check may not have completed yet]
E1113 03:53:54.374076    4715 kubelet.go:2244] node "127.0.0.1" not found
I1113 03:53:54.374784    4715 factory.go:116] Using factory "raw" for container "/"
I1113 03:53:54.375474    4715 manager.go:1011] Added container: "/" (aliases: [], namespace: "")
I1113 03:53:54.375946    4715 manager.go:365] Starting recovery of all containers
I1113 03:53:54.376238    4715 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
I1113 03:53:54.376239    4715 container.go:464] Start housekeeping for container "/"
I1113 03:53:54.381513    4715 kubelet_node_status.go:446] Recording NodeHasSufficientMemory event message for node 127.0.0.1
I1113 03:53:54.381550    4715 kubelet_node_status.go:446] Recording NodeHasNoDiskPressure event message for node 127.0.0.1
I1113 03:53:54.381568    4715 kubelet_node_status.go:446] Recording NodeHasSufficientPID event message for node 127.0.0.1
I1113 03:53:54.381595    4715 kubelet_node_status.go:72] Attempting to register node 127.0.0.1
I1113 03:53:54.381706    4715 server.go:459] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"127.0.0.1", UID:"127.0.0.1", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasSufficientMemory' Node 127.0.0.1 status is now: NodeHasSufficientMemory
I1113 03:53:54.381742    4715 server.go:459] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"127.0.0.1", UID:"127.0.0.1", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasNoDiskPressure' Node 127.0.0.1 status is now: NodeHasNoDiskPressure
I1113 03:53:54.381757    4715 server.go:459] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"127.0.0.1", UID:"127.0.0.1", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasSufficientPID' Node 127.0.0.1 status is now: NodeHasSufficientPID
I1113 03:53:54.384189    4715 factory.go:113] Factory "systemd" can handle container "/system.slice/sys-kernel-config.mount", but ignoring.
I1113 03:53:54.384234    4715 factory.go:116] Using factory "raw" for container "/user.slice/user-0.slice/session-c2.scope"
I1113 03:53:54.384639    4715 manager.go:1011] Added container: "/user.slice/user-0.slice/session-c2.scope" (aliases: [], namespace: "")
I1113 03:53:54.384945    4715 factory.go:116] Using factory "raw" for container "/user.slice"
I1113 03:53:54.385010    4715 container.go:464] Start housekeeping for container "/user.slice/user-0.slice/session-c2.scope"
I1113 03:53:54.385348    4715 manager.go:1011] Added container: "/user.slice" (aliases: [], namespace: "")
I1113 03:53:54.385611    4715 factory.go:116] Using factory "raw" for container "/system.slice/systemd-tmpfiles-setup.service"
I1113 03:53:54.385699    4715 container.go:464] Start housekeeping for container "/user.slice"
I1113 03:53:54.385981    4715 manager.go:1011] Added container: "/system.slice/systemd-tmpfiles-setup.service" (aliases: [], namespace: "")
I1113 03:53:54.386001    4715 kubelet_node_status.go:75] Successfully registered node 127.0.0.1
[...]
```

On the other hand, Kubernetes installed from `kubernetes-node-1.10.3-1.fc29.x86_64` fails for me with 
```
kubele[12585]: I1113 03:49:24.965325   12585 kubelet.go:558] Hairpin mode set to "hairpin-veth"
kubele[12585]: I1113 03:49:24.967900   12585 client.go:75] Connecting to docker on unix:///var/run/docker.sock
kubele[12585]: I1113 03:49:24.967931   12585 client.go:104] Start docker client with request timeout=2m0s
kubele[12585]: W1113 03:49:24.973143   12585 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
kubele[12585]: I1113 03:49:24.978540   12585 docker_service.go:244] Docker cri networking managed by kubernetes.io/no-op
kubele[12585]: I1113 03:49:24.990584   12585 docker_service.go:249] Docker Info: &{ID:GRDH:BZ2R:GUV5:ADW4:2V7Y:G7IR:SASZ:3FW6:WWF2:Y3KE:YSZO:LUI3 Containers:0 ContainersRunning:0 ContainersPaused:0 ContainersStopped:0 Images:0 Driver:overlay2 DriverStatus:[[Backing Filesystem xfs] [Supports d_type true] [Native Overlay Diff true]] SystemStatus:[] Plugins:{Volume:[local] Network:[bridge host macvlan null overlay] Authorization:[rhel-push-plugin] Log:[]} MemoryLimit:true SwapLimit:true KernelMemory:true CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6tables:true Debug:false NFd:18 OomKillDisable:true NGoroutines:22 SystemTime:2018-11-13T03:49:24.981272841-05:00 LoggingDriver:journald CgroupDriver:systemd NEventsListener:0 KernelVersion:4.18.17-300.fc29.x86_64 OperatingSystem:Fedora 29 (Twenty Nine) OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:0xc0003f2620 NCPU:8 MemTotal:33729044480 GenericResources:[] DockerRootDir:/var/lib/docker HTTPProxy: HTTPSProxy: NoProxy: Name:master.example.test Labels:[] ExperimentalBuild:false ServerVersion:1.13.1 ClusterStore: ClusterAdvertise: Runtimes:map[runc:{Path:docker-runc Args:[]} oci:{Path:/usr/libexec/docker/docker-runc-current Args:[]}] DefaultRuntime:oci Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:[] Nodes:0 Managers:0 Cluster:0xc0003172c0} LiveRestoreEnabled:true Isolation: InitBinary:/usr/libexec/docker/docker-init-current ContainerdCommit:{ID:accfe55885ee1ff20e0479d2db23743d470c6b7e Expected:aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1} RuncCommit:{ID:accfe55885ee1ff20e0479d2db23743d470c6b7e-dirty Expected:9df8b306d01f59d3a8029be411de015b7304dd8f} InitCommit:{ID:N/A Expected:949e6facb77383876aeff8a6944dde66b3089574} SecurityOptions:[name=seccomp,profile=/etc/docker/seccomp.json name=selinux]}
kubele[12585]: I1113 03:49:24.992389   12585 docker_service.go:262] Setting cgroupDriver to systemd
kubele[12585]: I1113 03:49:25.005647   12585 remote_runtime.go:43] Connecting to runtime service unix:///var/run/dockershim.sock
kubele[12585]: I1113 03:49:25.008768   12585 kuberuntime_manager.go:186] Container runtime docker initialized, version: 1.13.1, apiVersion: 1.26.0
kubele[12585]: W1113 03:49:25.009484   12585 probe.go:215] Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ does not exist. Recreating.
kubele[12585]: I1113 03:49:25.010143   12585 csi_plugin.go:61] kubernetes.io/csi: plugin initializing...
kubele[12585]: I1113 03:49:25.012461   12585 server.go:129] Starting to listen on 127.0.0.1:10250
kubele[12585]: I1113 03:49:25.012527   12585 server.go:945] Started kubelet
kubele[12585]: E1113 03:49:25.012495   12585 kubelet.go:1282] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data for container /
kubele[12585]: I1113 03:49:25.013564   12585 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
kubele[12585]: I1113 03:49:25.013609   12585 status_manager.go:140] Starting to sync pod status with apiserver
kubele[12585]: I1113 03:49:25.013637   12585 kubelet.go:1782] Starting kubelet main sync loop.
kubele[12585]: I1113 03:49:25.013676   12585 kubelet.go:1799] skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]
kubele[12585]: I1113 03:49:25.013741   12585 server.go:299] Adding debug handlers to kubelet server.
kubele[12585]: I1113 03:49:25.013938   12585 volume_manager.go:247] Starting Kubelet Volume Manager
kubele[12585]: I1113 03:49:25.014002   12585 desired_state_of_world_populator.go:129] Desired state populator starts to run
kubele[12585]: I1113 03:49:25.113896   12585 kubelet.go:1799] skipping pod synchronization - [container runtime is down]
kubele[12585]: I1113 03:49:25.114726   12585 kubelet_node_status.go:271] Setting node annotation to enable volume controller attach/detach
kubele[12585]: I1113 03:49:25.120252   12585 kubelet_node_status.go:82] Attempting to register node 127.0.0.1
kubele[12585]: I1113 03:49:25.124217   12585 kubelet_node_status.go:85] Successfully registered node 127.0.0.1
kubele[12585]: I1113 03:49:25.314064   12585 kubelet.go:1799] skipping pod synchronization - [container runtime is down]
kubele[12585]: I1113 03:49:25.714212   12585 kubelet.go:1799] skipping pod synchronization - [container runtime is down]
kubele[12585]: I1113 03:49:26.514378   12585 kubelet.go:1799] skipping pod synchronization - [container runtime is down]
kubele[12585]: I1113 03:49:27.343074   12585 cpu_manager.go:155] [cpumanager] starting with none policy
kubele[12585]: I1113 03:49:27.343121   12585 cpu_manager.go:156] [cpumanager] reconciling every 10s
```

and I've got 
```
# kubectl get nodes
NAME        STATUS     ROLES     AGE       VERSION
127.0.0.1   NotReady   <none>    2h        v1.10.3
```

@coveritytest, is your situation with `local-up-cluster.sh` from master or with packaged Kubernetes?

**Comment by coveritytest** [comment]
It's the packaged Kubernetes, I was following [this guide](https://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/).

**Comment by adelton** [comment]
For Kubernetes installed from Fedora packages, I've filed https://bugzilla.redhat.com/show_bug.cgi?id=1649330.

**Comment by CMajeri** [comment]
Hello,

I hit this head on.
It doesn't seem to be an issue with docker.
I'm using kubernetes 1.10.3

I've had a look inside the code and it looks like runc is trying to set "Delegate" on a slice.
In the "Create" call ( https://github.com/kubernetes/kubernetes/blob/v1.10.3/pkg/kubelet/cm/cgroup_manager_linux.go#L468 )

kubelet "adapt"s the name to fit systemd's nomenclature, resulting in this call :
https://github.com/kubernetes/kubernetes/blob/v1.10.3/pkg/kubelet/cm/cgroup_manager_linux.go#L93

Which adds "systemdSuffix" to the cgroup name. This is a const set to 1
https://github.com/kubernetes/kubernetes/blob/v1.10.3/pkg/kubelet/cm/cgroup_manager_linux.go#L49

When this is passed to runc, the "UseSystemd()" call works because it tests "hasDelegate" only on scope units (in lower versions of runc, before commit 0e16bd9b53eb3c57ea6fe59fc6d9385c2edb9fd9) https://github.com/opencontainers/runc/blob/3cbb2fa3c4e8f307817317c455268c6e58703e0b/libcontainer/cgroups/systemd/apply_systemd.go#L153 and doesn't check for slice.

And then during the Apply() call from the ContainerManager's Create(), since the "slice" suffix is set on the cgroup name, everything breaks and the ContainerManager can't be created anymore.

So I guess we need to "not use" that version of kubernetes, and instead find one that's been built with a more recent runc library. So, update kubernetes would be my best guess for a fix.
