### ISSUE TITLE
REST api - getting a single resource without namespace returns 404

### ISSUE THREAD

**Issue by abonas** [kubernetes/kubernetes#6153]
Getting a single resource without specifying namespace in the url returns 404 which is misleading.

For example,

http://localhost:8080/api/v1beta3/services
works, but if the user tries
http://localhost:8080/api/v1beta3/services/kubernetes-ro
(instead of http://localhost:8080/api/v1beta3/namespaces/default/services/kubernetes-ro)
it returns 404 which is confusing.
It's better to return "namespace should be specified" etc.

**Comment by bgrant0607** [comment]
404 is correct, but we could return additional info in the Status return object.

However, returning something more specific is gated on getting support from the handler library we use -- see #4347.

**Comment by nikhiljindal** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/4347 is fixed now. This is what we return:
```
HTTP/1.1 404 Not Found
Content-Type: application/json
Date: Thu, 23 Apr 2015 07:19:25 GMT
Content-Length: 211

{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}
```

**Comment by abonas** [comment]
@nikhiljindal , the above error message is still not clear enough in regards to the fact that user needs to understand that a namespace should be specified. it's not that the resource doesn't exist at all, it just needs to be retrieved via the namespace.p ls see my initial comment in this issue above
https://github.com/GoogleCloudPlatform/kubernetes/issues/6153#issue-65174022

**Comment by liggitt** [comment]
That is the standard response from an invalid endpoint (same response as requesting a nonsense endpoint like /foo/bar/baz). Requesting a valid endpoint gives more details about the resource type that wasn’t found.
