### ISSUE TITLE
Failing Test : [sig-storage] PersistentVolumes-local Local volume provisioner [Serial] should create and recreate local persistent volume

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#62705]
## Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=storage&test=should%20create%20and%20recreate%20local%20persistent%20volum

This test is currently failing in sig-release master-upgrade suite, This could potentially become release blocking if not addressed sooner. @msau42  can you please triage this failure?

/kind bug
/priority failing-test
/priority important-soon
/sig storage
@kubernetes/sig-storage-bugs 

cc @jberkus @tpepper 

/assign @msau42

**Comment by AishSundar** [comment]
This test also fails in
https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster

https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster&test=should%20create%20and%20recreate%20local%20persistent%20volum

**Comment by msau42** [comment]
Problem is 1.10 e2e tests uses provisioner version 2.0.0 which only uses alpha node affinity annotation, but the alpha annotation support has been removed in 1.11

**Comment by msau42** [comment]
/close
Test is fixed now

**Comment by AishSundar** [comment]
Thanks for the fix @msau42, however I still see the test failing @ https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-master. Is it because the latest run results are not refreshed? The PR seems to have merged a couple of days ago, so curious if the test runs since then have the fixes.

I am re-opening the bug for tracking. Will close once testgrid turns green

/reopen
