### ISSUE TITLE
Failing Test: [sig-cluster-lifecycle] Upgrade [Feature:Upgrade] cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#62710]
### [ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel&test=%5C%5Bsig%5C-cluster%5C-lifecycle%5C%5D%5C%20Upgrade%5C%20%5C%5BFeature%3AUpgrade%5C%5D%5C%20cluster%5C%20upgrade%5C%20should%5C%20maintain%5C%20a%5C%20functioning%5C%20cluster%5C%20%5C%5BFeature%3AClusterUpgrade%5C%5D)

This test is currently failing in sig-release master-upgrade suite, This could potentially become release blocking if not addressed sooner. @timothysc    can you please triage this failure?

/kind bug
/priority failing-test
/priority important-soon
/sig cluster-lifecycle
@kubernetes/sig-cluster-lifecycle-bugs 

cc @jberkus @tpepper 

/assign @timothysc

**Comment by timothysc** [comment]
@BenTheElder Do you have some time to chat this week so we can work on fixing these tests.  I know what is wrong and it will be a band-aide but generally we need to re-write a these tests with cluster-api once it enters into beta.

**Comment by timothysc** [comment]
```
    resources after ingress upgrade were different:
     Pre-Upgrade: ([]*compute.TargetHttpsProxy)[<*>{CreationTimestamp:(string)2018-04-16T20:54:43.996-07:00 Description:(string) Id:(uint64)3775768819435884268 Kind:(string)compute#targetHttpsProxy Name:(string)k8s-tps-e2e-tests-ingress-upgrade-5z5dq-static-ip--1cb82e21a530 SelfLink:(string)https://www.googleapis.com/compute/v1/projects/kubernetes-gci-gke-ingress-1-3/global/targetHttpsProxies/k8s-tps-e2e-tests-ingress-upgrade-5z5dq-static-ip--1cb82e21a530 SslCertificates:([]string)[https://www.googleapis.com/compute/v1/projects/kubernetes-gci-gke-ingress-1-3/global/sslCertificates/k8s-ssl-e2e-tests-ingress-upgrade-5z5dq-static-ip--1cb82e21a530] UrlMap:(string)https://www.googleapis.com/compute/v1/projects/kubernetes-gci-gke-ingress-1-3/global/urlMaps/k8s-um-e2e-tests-ingress-upgrade-5z5dq-static-ip--1cb82e21a53a0 ServerResponse:(googleapi.ServerResponse){HTTPStatusCode:(int)0 Header:(http.Header)<nil>} ForceSendFields:([]string)<nil> NullFields:([]string)<nil>}]
     Post-Upgrade: ([]*compute.TargetHttpsProxy)[<*>{CreationTimestamp:(string)2018-04-16T20:54:43.996-07:00 Description:(string) Id:(uint64)3775768819435884268 Kind:(string)compute#targetHttpsProxy Name:(string)k8s-tps-e2e-tests-ingress-upgrade-5z5dq-static-ip--1cb82e21a530 SelfLink:(string)https://www.googleapis.com/compute/v1/projects/kubernetes-gci-gke-ingress-1-3/global/targetHttpsProxies/k8s-tps-e2e-tests-ingress-upgrade-5z5dq-static-ip--1cb82e21a530 SslCertificates:([]string)[https://www.googleapis.com/compute/v1/projects/kubernetes-gci-gke-ingress-1-3/global/sslCertificates/k8s-ssl-30347317bd258db9-96ef87348053c357--1cb82e21a53ac1ff] UrlMap:(string)https://www.googleapis.com/compute/v1/projects/kubernetes-gci-gke-ingress-1-3/global/urlMaps/k8s-um-e2e-tests-ingress-upgrade-5z5dq-static-ip--1cb82e21a53a0 ServerResponse:(googleapi.ServerResponse){HTTPStatusCode:(int)0 Header:(http.Header)<nil>} ForceSendFields:([]string)<nil> NullFields:([]string)<nil>}]
not to have occurred
```

What's changed with ingress?  /cc @kubernetes/sig-network-bugs

**Comment by timothysc** [comment]
The upgrade test is exposing a change on ingress SSL certs from the looks of it.  
/unassign @timothysc  
/assign @AishSundar  for re-routing.

**Comment by MrHohn** [comment]
cc @rramkumar1

**Comment by AishSundar** [comment]
Since this is a test issue, I am applying label status/approved-for-milestone to avoid this issue from being removed from the milestone. @kubernetes/sig-network-bugs @kubernetes/sig-network-misc plz ping me if you have any ques.

**Comment by AishSundar** [comment]
status/approved-for-milestone

**Comment by AishSundar** [comment]
@MrHohn @rramkumar1  is there an ETA on fixing this test failure? This is currently on of the few tests failing our sig-release upgrade blocking suite. If this is not fixed we will have to delay beta for 1.11.

@tpepper @jberkus as FYI

**Comment by MrHohn** [comment]
Checked on the latest runs, both `should maintain a functioning cluster` and `ingress-upgrade` are no longer failing. The only remaining red test is `[sig-apps] Deployment RollingUpdateDeployment should delete old pods and create new ones`, which is tracked on https://github.com/kubernetes/kubernetes/issues/62703.
/close

**Comment by MrHohn** [comment]
/reopen
speak too soon. Test is failing on gce but not gke.

**Comment by MrHohn** [comment]
From the test logs (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1422?log#log):
```
resources after ingress upgrade were different:
     Pre-Upgrade: ([]*compute.InstanceGroup)[<*>{CreationTimestamp:(string)2018-05-05T14:31:37.611-07:00 Description:(string) Fingerprint:(string)dP14g5oqO7k= Id:(uint64)4457922184245124182 Kind:(string)compute#instanceGroup Name:(string)k8s-ig--6ef0ad3597db531f NamedPorts:([]*compute.NamedPort)[<*>{Name:(string)port30644 Port:(int64)30644 ForceSendFields:([]string)<nil> NullFields:([]string)<nil>} <*>{Name:(string)port30455 Port:(int64)30455 ForceSendFields:([]string)<nil> NullFields:([]string)<nil>}] Network:(string)https://www.googleapis.com/compute/v1/projects/k8s-jkns-gce-slow-1-4/global/networks/bootstrap-e2e Region:(string) SelfLink:(string)https://www.googleapis.com/compute/v1/projects/k8s-jkns-gce-slow-1-4/zones/us-central1-f/instanceGroups/k8s-ig--6ef0ad3597db531f Size:(int64)3 Subnetwork:(string)https://www.googleapis.com/compute/v1/projects/k8s-jkns-gce-slow-1-4/regions/us-central1/subnetworks/bootstrap-e2e Zone:(string)https://www.googleapis.com/compute/v1/projects/k8s-jkns-gce-slow-1-4/zones/us-central1-f ServerResponse:(googleapi.ServerResponse){HTTPStatusCode:(int)0 Header:(http.Header)<nil>} ForceSendFields:([]string)<nil> NullFields:([]string)<nil>}]
     Post-Upgrade: ([]*compute.InstanceGroup)[<*>{CreationTimestamp:(string)2018-05-05T14:31:37.611-07:00 Description:(string) Fingerprint:(string)dP14g5oqO7k= Id:(uint64)4457922184245124182 Kind:(string)compute#instanceGroup Name:(string)k8s-ig--6ef0ad3597db531f NamedPorts:([]*compute.NamedPort)[<*>{Name:(string)port30644 Port:(int64)30644 ForceSendFields:([]string)<nil> NullFields:([]string)<nil>} <*>{Name:(string)port30455 Port:(int64)30455 ForceSendFields:([]string)<nil> NullFields:([]string)<nil>}] Network:(string)https://www.googleapis.com/compute/v1/projects/k8s-jkns-gce-slow-1-4/global/networks/bootstrap-e2e Region:(string) SelfLink:(string)https://www.googleapis.com/compute/v1/projects/k8s-jkns-gce-slow-1-4/zones/us-central1-f/instanceGroups/k8s-ig--6ef0ad3597db531f Size:(int64)1 Subnetwork:(string)https://www.googleapis.com/compute/v1/projects/k8s-jkns-gce-slow-1-4/regions/us-central1/subnetworks/bootstrap-e2e Zone:(string)https://www.googleapis.com/compute/v1/projects/k8s-jkns-gce-slow-1-4/zones/us-central1-f ServerResponse:(googleapi.ServerResponse){HTTPStatusCode:(int)0 Header:(http.Header)<nil>} ForceSendFields:([]string)<nil> NullFields:([]string)<nil>}]
```

Turned out after upgrade, the number of nodes in instance group (managed by ingress) was different  (before upgrade there was 3 but after upgrade there was 1), probably because nodes were being upgraded as well and not yet added back to the instance group.
```
...instanceGroups/k8s-ig--6ef0ad3597db531f Size:(int64)3...
...instanceGroups/k8s-ig--6ef0ad3597db531f Size:(int64)1...
```

**Comment by MrHohn** [comment]
Sending out a quick fix on #63519.

**Comment by mohammedzee1000** [comment]
@MrHohn @rramkumar1 This issue has been fixed then?

**Comment by MrHohn** [comment]
@mohammedzee1000 Nope, I believe `cluster upgrade should maintain a functioning cluster` is still broken and needs an owner. #63519 was only fixing `ingress-upgrade`.

**Comment by krousey** [comment]
For the parallel job, the upgrade succeeds. The framework seems to be having trouble with namespace deletion that runs before each test.
 https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster-parallel&include-filter-by-regex=cluster-upgrade

For the serial suite, the upgrade also seems to succeed, but the tests that follow time out. https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster-new&include-filter-by-regex=cluster-upgrade

Is it weird that the row shows up as red when all the recent results are green? https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster-new&sort-by-failures=&width=20&include-filter-by-regex=upgrade

**Comment by AishSundar** [comment]
@krousey are you actively investigating the Timeouts? if not let me know if this needs triaging and reassignment. As you pointed out I see almost all gke cluster upgrade/downgrade tests timeout today

https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster-parallel
https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster
https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-master-gci-1.10-downgrade-cluster
https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-master-gci-1.10-downgrade-cluster-parallel

@MrHohn @BenTheElder as FYI

**Comment by krousey** [comment]
I am not actively investigating timeouts. I was merely commenting that the
upgrade steps look to be working.

**Comment by BenTheElder** [comment]
@AishSundar that sounds like some bug in the API server. I will not have time to debug this at the moment, but an owning sig should take this on anyhow.

**Comment by cjwagner** [comment]
There is also this error: `I0508 17:13:14.164] May  8 17:13:14.163: INFO: Failed to list network endpoint group: googleapi: Error 403: Required 'Alpha Access' permission for 'Compute API', forbidden`. 
I'm not sure if that is related.

The main error appears to be `May 8 10:22:06.860: INFO: discovery error for unexpected group: schema.GroupVersion{Group:"metrics.k8s.io", Version:"v1beta1"}
May 8 10:22:06.860: INFO: Error discoverying server preferred namespaced resources: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request, retrying in 2s.` as Aish noted.

According to @Q-Lee this smells like an instrumentation problem.
/sig instrumentation

**Comment by MrHohn** [comment]
> I0508 17:13:14.164] May 8 17:13:14.163: INFO: Failed to list network endpoint group: googleapi: Error 403: Required 'Alpha Access' permission for 'Compute API', forbidden.

Quick clarification, that log entry is benign and isn't related. During resource cleanup we attempt to list network endpoint group regardless whether the project has enabled the API or not.

**Comment by cezarygerard** [comment]
/remove-sig instrumentation

this is actually not connected to metric server. Deleting the namespace fails and @liggitt has a workaround PR 
https://github.com/kubernetes/kubernetes/pull/63597

**Comment by AishSundar** [comment]
We have had further discussion on this. @liggitt and @yliaog are looking into this - https://github.com/kubernetes/kubernetes/pull/63597

**Comment by AishSundar** [comment]
cc @liggitt @yliaog

**Comment by yliaog** [comment]
this is a CL to rollback the GKE test env change, it should fix the failures like below:

May 8 10:22:06.860: INFO: discovery error for unexpected group: schema.GroupVersion{Group:"metrics.k8s.io", Version:"v1beta1"}

**Comment by cezarygerard** [comment]
@yliaog which CL you mean? Did you forgot to link?

**Comment by AishSundar** [comment]
Its an internal GKE CL. Its now checked in all tests are beginning to turn green.

https://k8s-testgrid.appspot.com/sig-cli-master#gke

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke

**Comment by cezarygerard** [comment]
wasn't it fix by this: https://github.com/kubernetes/kubernetes/pull/63597#issuecomment-387781812 ?

**Comment by AishSundar** [comment]
That just fixed the e2e tests to ignore the discoverability error. That PR exposed other GKE specific test issues that were fixed by an internal PR.

That said, I still see the e2e test originally tracked by this issue still failing.

[[sig-cluster-lifecycle] Upgrade [Feature:Upgrade] cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new/1998)

Will wait for more latest runs before I followup here further.

**Comment by cezarygerard** [comment]
so this wasn't needed: https://github.com/kubernetes/kubernetes/pull/63597

**Comment by AishSundar** [comment]
Tests are passing now. Closing this issue :) Thanks all.

* [sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster-new](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster-new&include-filter-by-regex=cluster%20upgrade%20should%20maintain%20a%20functioning%20cluster)
* [sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster-parallel&include-filter-by-regex=cluster%20upgrade%20should%20maintain%20a%20functioning%20cluster)

/close
