### ISSUE TITLE
Failing Test: [sig-aws] Up failing in ci-kubernetes-e2e-kops-aws and pull-kubernetes-e2e-kops-aws

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#63024]
## Failing Job
[sig-release-master-blocking: aws](https://k8s-testgrid.appspot.com/sig-release-master-blocking#aws)

## Failing Test
[Up](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/26962)

## Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-kops-aws&test=Up

Synced offline and this is due to a known leak issue (fix being deployed), where we are running out of VPCs.

/kind bug
/priority failing-test
/priority important-soon
/sig testing
/milestone 1.11
@kubernetes/sig-testing-bugs 

cc @timothysc @justinsb 

/assign @justinsb

**Comment by justinsb** [comment]
Should be addressed by https://github.com/kubernetes/test-infra/pull/7829

**Comment by krousey** [comment]
I'm still seeing this test fail.

**Comment by AishSundar** [comment]
I am still seeing this to be our top flake 
* http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1
* TestGrid
    * [pull-kubernetes-e2e-kops-aws](https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kops-aws)
    * [sig-release-master-blocking#aws](https://k8s-testgrid.appspot.com/sig-release-master-blocking#aws)
* Triage
    * [pull-kubernetes-e2e-kops-aws](https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&job=pull-kubernetes-e2e-kops-aws&test=Up)
    * [ci-kubernetes-e2e-kops-aws](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-kops-aws&test=Up)

**Comment by AishSundar** [comment]
/sig aws
@kubernetes/sig-aws-misc

**Comment by AishSundar** [comment]
/close 

test is fixed now !

**Comment by AishSundar** [comment]
/reopen

I am seeing this test flake again in https://k8s-testgrid.appspot.com/presubmits-kops#e2e 

Log: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kops/5148/pull-kops-e2e-kubernetes-aws/6384

@justinsb do you mind taking a look please

/assign @justinsb

**Comment by juanvallejo** [comment]
I am also seeing this test flake in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-sig-cli/2489

**Comment by AishSundar** [comment]
/status in-progress
@BenTheElder Is this flake related to the quota issue you were tracking for AWS?

**Comment by AishSundar** [comment]
This is still one of the top flakes in Presubmits affecting 93 PRs in the last week alone. http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1

Is there a active ongoing investigation for this?

**Comment by AishSundar** [comment]
Thanks to some low hanging fix ([#8164](https://github.com/kubernetes/test-infra/pull/8164)) we see some improvement in the flake rate. But this one still seems to be the top flake affecting [17 jobs](http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1) last week alone.

@justinsb I know you were looking into some experiments to get more insights into the quota strains across diff regions. Anything conclusive to help us here?

**Comment by guineveresaenger** [comment]
@fejta @timothysc this is a 1.12 know issue. Should this be in the milestone?

**Comment by dims** [comment]
seems to be green.

/close
