### ISSUE TITLE
Bug: ResourceExhausted desc = grpc: received message larger than max (4195017 vs. 4194304)

### ISSUE THREAD

**Issue by KIVagant** [kubernetes/kubernetes#63858]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

- Nodes in `NotReady` status
- Pods in `Unknown` status

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Debian 8 (jessie)
- Kernel (e.g. `uname -a`): `Linux ... 4.4.115-k8s #1 SMP Thu Feb 8 15:37:40 UTC 2018 x86_64 GNU/Linux`
- Install tools: kops
- Others:
    - Logs:

```
==> /var/log/daemon.log <==
May 15 12:02:19 ip-10-133-93-99 kubelet[2524]: E0515 12:02:19.150508    2524 remote_runtime.go:262] ListContainers with filter &ContainerFilter{Id:,State:nil,PodSandboxId:,LabelSelector:map[string]string{},} from runtime service failed: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4195017 vs. 4194304)

May 15 12:02:19 ip-10-133-93-99 kubelet[2524]: E0515 12:02:19.150586    2524 kuberuntime_container.go:323] getKubeletContainers failed: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4195017 vs. 4194304)

May 15 12:02:19 ip-10-133-93-99 kubelet[2524]: E0515 12:02:19.150613    2524 generic.go:197] GenericPLEG: Unable to retrieve pods: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4195017 vs. 4194304)


==> /var/log/syslog <==
May 15 12:02:21 ip-10-133-93-99 kubelet[2524]: E0515 12:02:21.554728    2524 remote_runtime.go:262] ListContainers with filter &ContainerFilter{Id:,State:nil,PodSandboxId:,LabelSelector:map[string]string{},} from runtime service failed: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4195017 vs. 4194304)

May 15 12:02:21 ip-10-133-93-99 kubelet[2524]: E0515 12:02:21.554842    2524 kuberuntime_container.go:323] getKubeletContainers failed: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4195017 vs. 4194304)

May 15 12:02:21 ip-10-133-93-99 kubelet[2524]: E0515 12:02:21.554873    2524 generic.go:197] GenericPLEG: Unable to retrieve pods: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4195017 vs. 4194304)

May 15 12:02:21 ip-10-133-93-99 kubelet[2524]: I0515 12:02:21.788754    2524 kubelet.go:1794] skipping pod synchronization - [PLEG is not healthy: pleg was last seen active 1h3m27.338264092s ago; threshold is 3m0s]
```

- Possible prerequisites: a lot of jobs (1657) that failed (state: Error) because of internal problems
- Cluster size: 3 masters, 4 worker nodes
- **Workaround:** how to get the node back

```
docker system prune
...
service docker restart && service kubelet restart
```

- Possible related to https://github.com/kubernetes/kubernetes/issues/51099

**Comment by ceshihao** [comment]
It is `max message size` limitation on grpc.

The default value is `1024 * 1024 * 4` (i.e. `4194304` in error message)
https://github.com/grpc/grpc-go/blob/master/clientconn.go#L118

**Comment by KIVagant** [comment]
@ceshihao do you know if it possible to configure the value with environment variable or maybe in some config file?

**Comment by mcluseau** [comment]
Hitting the same bug here (Kubernetes 1.10.2 with docker 17.12.1). The node has 8309 containers, most of them exited, created by failing jobs.

**Comment by mcluseau** [comment]
I'll try to change kubelet's ContainerGC so that, when there are more than say 5000 containers it reclaims the oldest ones. Unless someone thinks it's not the right think to do.

**Comment by mcluseau** [comment]
thanks @dims I'll try to reproduce but it will take time (I had to clean the host).

**Comment by KIVagant** [comment]
@dims I don't have free infrastructure to install there K8s from some branch and don't have experience to do this at all. I have used only stable releases.

**Comment by mcluseau** [comment]
@dims I can already tell that it probably won't solve the problem (with containerd at least):

```
# ctr -n k8s.io c ls
ctr: grpc: trying to send message larger than max (925727095 vs. 16777216): unknown
```

**Comment by dims** [comment]
@mcluseau given what you are seeing `defaultMaxMessageSize = 1024 * 1024 * 16` won't help but `defaultMaxMessageSize = 1024 * 1024 * 1024` will help. right? (note that default in grpc is `defaultMaxMessageSize = 1024 * 1024 * 4`

**Comment by mcluseau** [comment]
@dims yes it would work but it's 1GB so we are in a runaway situation here; have 1GB today and you'll need 2GB tomorrow. 16MB is definitely an improvement and your change to 16MB is LGTM (thanks!), but the root problem still remains. The 2 solutions I can imagine are (1) an API change to include paging (or streaming), or (2) make the kubelet ensure there's less than a total number of containers (running+exited).

Since the issue also impacts `ctr` I'm participating in the following upstream issue: https://github.com/containerd/containerd/issues/2320.

**Comment by mcluseau** [comment]
Just discovered the way of the stream seems to be the target: https://github.com/containerd/containerd/pull/2347

**Comment by mcluseau** [comment]
@k8s-merge-robot #63894 improves the situation but doesn't completely fix this issue ;-) Should I open another one?

**Comment by 2rs2ts** [comment]
@mcluseau k8s-merge-robot is a bot user; I think you need to open a new issue

**Comment by mcluseau** [comment]
@2rs2ts it was a humoristic remark ;-) I'm waiting for the improvement in containerd. It seems they're even gonna hide the details about List vs Stream in the client, so we may just have to bump de client version at some point here.

**Comment by kjelle** [comment]
> @dims yes it would work but it's 1GB so we are in a runaway situation here; have 1GB today and you'll need 2GB tomorrow. 16MB is definitely an improvement and your change to 16MB is LGTM (thanks!), but the root problem still remains. The 2 solutions I can imagine are (1) an API change to include paging (or streaming), or (2) make the kubelet ensure there's less than a total number of containers (running+exited).
> 
> Since the issue also impacts `ctr` I'm participating in the following upstream issue: [containerd/containerd#2320](https://github.com/containerd/containerd/issues/2320).

Exactly! We just downed a docker swarm mode cluster with mere 80 services with 1 container each.

**Comment by Ehekatl** [comment]
run into this issue as well, gc not removed dead container, this functionality seems deprecated in recent k8s release,  no sure why.

**Comment by MIBc** [comment]
I met the problem for k8s 1.13.2 .Do you have any solutions except clear dead container manually? @Ehekatl @mcluseau

**Comment by drew-512** [comment]
> @dims yes it would work but it's 1GB so we are in a runaway situation here; have 1GB today and you'll need 2GB tomorrow. 16MB is definitely an improvement and your change to 16MB is LGTM (thanks!), but the root problem still remains. The 2 solutions I can imagine are (1) an API change to include paging (or streaming), or (2) make the kubelet ensure there's less than a total number of containers (running+exited).
> 
> Since the issue also impacts `ctr` I'm participating in the following upstream issue: [containerd/containerd#2320](https://github.com/containerd/containerd/issues/2320).


Really?  There's an absolute universe more information in 1GB  that 4MB,, just as it made sense to not make the limit 4096.  Although the above is true, can we agree there is huge difference, in human terms, between 4MB and say 1GB.  

Pretty please change the limit to a round 1GB or something that is configurable at run-time by the service publisher or as a connection option.   Maybe an option flag that waves this limit at runtime?

This is a scary issue for us b/c now we have to write a segmenter/desegmenter in our client?  Fear.  Please let consumers of pb tech not have to do this.  Everyone will just have to write their own segmenter/desegmenter hurting the pb's rep as the one stop shop for interoperabilty.

**Comment by mcluseau** [comment]
@drew-512 streaming is native in protobuf...

**Comment by drew-512** [comment]
> @drew-512 streaming is native in protobuf...

Sure... but we're hitting this limit and we're already in a stream call.  :\

**Comment by mcluseau** [comment]
On Jul 21, 2019 17:36, drew-512 <notifications@github.com> wrote:
Sure... but we're hitting this limit and we're already in a stream call.  :\Sounds weird, you're talking about the limit of the Kubernetes' kubelet gRPC client talking to the CRI runtime? We never got this bug again and it's an old one.

**Comment by mcluseau** [comment]
On Jul 22, 2019 18:31, Dave Augustus <notifications@github.com> wrote:`docker --version
Docker version 18.09.8, build 0dd43dd87f
kubelet --version
Kubernetes v1.12.7
`
So is there a way of dealing with this error other than deleting/creating the namespace?
Some cleanup process? or parameter adjustment?AFAIK using docker does not go through the same interface as containerd. You should probably be able to recover the situation by removing containers (ie: docker system prune).

**Comment by MG2R** [comment]
For anyone operating a k8s cluster, running into this error and not being sure what the actual problem is... If you run this `docker inspect $(docker ps -a  | cut -d ' ' -f1 | tail -n+2) | wc -c`, you'll see that a message describing all containers currently known to docker is bigger than the limit the Kubelet has set for gRPC messages (16MB at the time of writing). 

This either means you have a LOT of (possibly dead) containers, or there's a LOT of metadata attached to your containers. This metadata probably comes in the form of custom labels attached to the container image by whatever tool you're using to create the container images. Check out `docker describe` for a couple of your containers and the issue should become apparent.

**Comment by anencore94** [comment]
@judexzhu  Thanks for sharing! :+1:

**Comment by oldthreefeng** [comment]
My case was caused by too many tekton dead pod (over 5000 dead containers). 
to solve this issue. 
first , add  `--maximum-dead-containers=1000 ` to kubelet comand line . 
```
$ vi /etc/systemd/system/kubelet.service.d/10-kubeadm.conf 
Environment="KUBELET_EXTRA_ARGS=--maximum-dead-containers=1000
...
```
second . restart kubelet
```
$ systemctl daemon-reload 
$ systemctl restart kubelet 
```

third. recheck

```
$ ps -ef |grep kubelet |grep cgrou
root     1141581       1 17 19:24 ?        00:00:02 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --pod-manifest-path=/etc/kubernetes/manifests --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --dynamic-config-dir=/etc/kubernetes/kubelet-config --v=3 --enable-controller-attach-detach=false --cluster-dns=10.125.0.10 --pod-infra-container-image=registry-vpc.cn-hangzhou.aliyuncs.com/acs/pause:3.2 --enable-load-reader --cluster-domain=cluster.local --cloud-provider=external --hostname-override=cn-hangzhou.172.16.16.53 --provider-id=cn-hangzhou.i-bp1iuo7tqytcqoohgot5 --authorization-mode=Webhook --authentication-token-webhook=true --anonymous-auth=false --client-ca-file=/etc/kubernetes/pki/ca.crt --cgroup-driver=systemd --maximum-dead-containers=1000 --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256 --tls-cert-file=/var/lib/kubelet/pki/kubelet.crt --tls-private-key-file=/var/lib/kubelet/pki/kubelet.key --rotate-certificates=true --cert-dir=/var/lib/kubelet/pki --node-labels=component=tekton-backend,pool_type=component,alibabacloud.com/nodepool-id=npe7f8da0b2c76435b94f07ba9007b7a40,ack.aliyun.com=c0c1705d7510d4fe586f165aee7c1eb0f --register-with-taints=component=tekton-backend:NoSchedule --eviction-hard=imagefs.available<15%,memory.available<300Mi,nodefs.available<10%,nodefs.inodesFree<5% --system-reserved=memory=300Mi --kube-reserved=memory=400Mi --kube-reserved=pid=1000 --system-reserved=pid=1000
```
and problem is solved. thanks to @judexzhu

**Comment by judexzhu** [comment]
@oldthreefeng I'm glad it helped.

In my case, after adding `--maximum-dead-containers=1000`, it still happened once after.

So I have to add a docker-prune service for double insurance.

Just for reference 

/etc/systemd/system/docker-prune.service
```
[Unit]
Description=Docker System prune everything

[Service]
Type=oneshot
ExecStart=/usr/bin/sh -c '/usr/bin/docker system prune -a --force'

[Install]
WantedBy=multi-user.target
```

/etc/systemd/system/docker-prune.timer
```
[Unit]
Description=Run docker-prune Weekly on Sunday

[Timer]
OnCalendar=Sun

[Install]
WantedBy=multi-user.target
```
It will run once a week on Sunday
Using systemctl enable and start both. check the status with `systemctl list-timers`.

**Comment by tleerai** [comment]
The solution here for me:

```
sudo nerdctl -n k8s.io container prune
sudo systemctl restart containerd
```

Once containers are pruned, you need to restart containerd for the node to show ready again.
