### ISSUE TITLE
ClusterIPs are not accessible from the host when kube-proxy runs in IPVS mode

### ISSUE THREAD

**Issue by lbernail** [kubernetes/kubernetes#65158]
/kind bug
/sig network

(I'm not sure this is actually a bug but it is definitely a behavior that is different from iptables and some applications rely on this)

**What happened**:
From the host network namespace accessing a ClusterIP when using IPVS does not work (it only works when traffic is sent to a local pod)

**What you expected to happen**:
To be able to use ClusterIPs from the host network namespace

**How to reproduce it (as minimally and precisely as possible)**:

- Configure kube-proxy in IPVS mode
- Create a deployment and the associated service
- Try to access the ClusterIP from the host

**Anything else we need to know?**:
This does not work due to how routing is set up when using IPVS
If we create a service with ClusterIP ```10.200.10.10```, kube-proxy will add this IP to the kube-ivps0 dummy interface:
```
ip addr show dev kube-ipvs0
3: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default
    link/ether da:08:05:49:16:56 brd ff:ff:ff:ff:ff:ff
    inet 10.200.10.10/32 brd 10.200.10.10 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
```
which will add the IP to the local route table:
```
ip route show table local
local 10.0.0.5 dev ens4 proto kernel scope host src 10.0.0.5
local 10.200.10.10 dev kube-ipvs0 proto kernel scope host src 10.200.10.10
```
(where 10.0.0.5 is the main interface for the instance)
So when accessing the ClusterIP from the host, the source IP will default to the ClusterIP:
```
ip route get 10.200.10.10
local 10.200.10.10 de lo src 10.200.10.10 uid 1001
```
After IPVS, the destination will be changed to a pod IP but the source will still be ClusterIP. Since ClusterIPs are not routable the answer will be lost.
A workaround would be to modify the local route to use the IP of the main interface as source:
```
ip route replace local 10.200.10.10 dev kube-ipvs0 proto kernel scope host src 10.0.0.5 table local
```
I tested this and it seems to work fine.

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.10.3`
- Cloud provider or hardware configuration: `GCE`
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 4.15.0-1008-gcp

**Comment by zq-david-wang** [comment]
Don't you have MASQUERADE rule somewhere? My clusters use flannel to create MASQUERADE rule and I guess it could also be done in kube-proxy with --masquerade-all=true option.

**Comment by lbernail** [comment]
I don't have any specific masquerade configuration:
- kubelet is run without `non-masquerade-cidr` so it uses the default `10.0.0.0/8` (both my pod and service CIDRs are in this range)
- kube-proxy is run without `cluster-cidr`

So I have the following masquerading rules:
- `MASQUERADE  all  --  anywhere            !10.0.0.0/8           /* kubenet: SNAT for outbound traffic from cluster */ ADDRTYPE match dst-type !LOCAL` (from kubelet)
- `MASQUERADE  all  --  anywhere             anywhere             match-set KUBE-LOOP-BACK dst,dst,src` from kube-proxy for hairpin traffic

My instances are also configured to NAT on KUBE-MARK-MASQ mark but in IPVS mode this chain is not referenced in the default configuration.

I confirm that running kube-proxy with `--masquerade-all` works but it feels like a workaround: if we do that we also masquerade pod-to-service traffic which seems unnecessary (and we lose the source pod IP)

**Comment by zq-david-wang** [comment]
Is it possible to have pod ip and service ip configured in same range?  Guess I am just familiar with my own cluster setup which use cluster-cidr.... Hope others can help you.

**Comment by lbernail** [comment]
Sorry, I meant both are in `10.0.0.0/8` but they are different (`10.100.0.0/16` and `10.200.0.0/16`)

**Comment by m1093782566** [comment]
cc @Lion-Wei 

I assume this bug has already been fixed?

**Comment by m1093782566** [comment]
ttps://github.com/kubernetes/kubernetes/pull/63319?

**Comment by m1093782566** [comment]
I am going to close this issue since it should be fixed by https://github.com/kubernetes/kubernetes/pull/63319, please re-open if you still have troubles after picking https://github.com/kubernetes/kubernetes/pull/63319

**Comment by lbernail** [comment]
I just tested and it does not seem to work
I updated kube-proxy to `v1.11.0-rc.1` but I still have the problem

Looking at the code, it looks like the KUBE-MARK-MASQ is not added to the service chain because the `KUBE-CLUSTER-IP` ipset is empty (which should not be the case because I actually have some services deployed)

Did I miss something?

**Comment by m1093782566** [comment]
Did you configure the --cluster-cidr?

**Comment by m1093782566** [comment]
cc @rtreffer, any comments?

**Comment by lbernail** [comment]
No I did not
I just realized this was the source of the problem here: https://github.com/kubernetes/kubernetes/blob/v1.11.0-rc.1/pkg/proxy/ipvs/proxier.go#L793

We usually don't configure it because we have no need for it:
- we don't advertise service cidr externally
- we would rather have pods using loadbalancer IP actually hit the load-balancer (easier to understand and debug if we have similar routing for hosts outside the cluster and pods for the same "host")

**Comment by m1093782566** [comment]
Yeah, seems you find the root cause. clusterIPSet should not be empty.
