### ISSUE TITLE
kubelet needs restart after granting sp access to azure acr

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#65225]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
after granting sp access to azure ACR , pull image from ACR would fail, and after wait about 15-30min, pull image would success. Root cause is that `servicePrincipalToken` needs to be refreshed when doing `registryClient.List`, otherwise it will always return empty registry list.

Related issue:
https://github.com/Azure/AKS/issues/442

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7 - v1.11
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/assign
@khenidak @brendandburns @feiskyer @karataliu 

I will implement that function.

**Comment by khenidak** [comment]
Thanks @andyzhangx -- can we add a milestone label?

**Comment by feiskyer** [comment]
+1. We should fix this within v1.12 release and cherry pick to old releases.

/priority critical-urgent
/milestone v1.12

**Comment by andyzhangx** [comment]
@j03wang this is not related, original issue is that after granting sp access to azure acr, pull image still fails with `unauthorized: authentication required`.

After my repro and investigation(really spent a lot of time...), I found the issue lies here, `registryClient.List(ctx) ` would return empty even after granting sp access to azure acr, and after around 15min, it returns correct loginServer list:
https://github.com/kubernetes/kubernetes/blob/b005f2fba340e2a9a3111b499f4f0eaf1ceed3eb/pkg/credentialprovider/azure/azure_credentials.go#L180-L186

Looks like it's a SDK or acr list with specific sp issue, workaround is wait around 15min or more time, it could recover by itself.

Paste my investigation logs here, I grant sp access to acr in around `Jul 19 13:07:11`, you could see it returns empty registry list first and then after a few more minutes, it returns the correct list with loginServer:
```
$ cat kubelet3.log | grep "listing reg"
Jul 19 13:04:17 aks-agentpool-46531270-1 kubelet[5761]: I0719 13:04:17.888563    5761 azure_credentials.go:192] listing registries
Jul 19 13:04:19 aks-agentpool-46531270-1 kubelet[5761]: I0719 13:04:19.212301    5761 azure_credentials.go:200] listing registries: empty registry list...
Jul 19 13:05:41 aks-agentpool-46531270-1 kubelet[5761]: I0719 13:05:41.986781    5761 azure_credentials.go:192] listing registries
Jul 19 13:05:42 aks-agentpool-46531270-1 kubelet[5761]: I0719 13:05:42.384276    5761 azure_credentials.go:200] listing registries: empty registry list...
Jul 19 13:07:11 aks-agentpool-46531270-1 kubelet[5761]: I0719 13:07:11.985251    5761 azure_credentials.go:192] listing registries
Jul 19 13:07:12 aks-agentpool-46531270-1 kubelet[5761]: I0719 13:07:12.539829    5761 azure_credentials.go:200] listing registries: empty registry list...
Jul 19 13:15:09 aks-agentpool-46531270-1 kubelet[5761]: I0719 13:15:09.983633    5761 azure_credentials.go:192] listing registries
Jul 19 13:15:10 aks-agentpool-46531270-1 kubelet[5761]: I0719 13:15:10.668403    5761 azure_credentials.go:200] listing registries: empty registry list...
Jul 19 13:20:11 aks-agentpool-46531270-1 kubelet[5761]: I0719 13:20:11.983974    5761 azure_credentials.go:192] listing registries
Jul 19 13:20:12 aks-agentpool-46531270-1 kubelet[5761]: I0719 13:20:12.625305    5761 azure_credentials.go:205] loginServer:andyacr.azurecr.io
```

**Comment by andyzhangx** [comment]
BTW, in v1.12, acr list(`registryClient.List`) uses new API, I will check whether in v1.12 would have same issue. Acutally I have already implemented LazyProvide func(check here: https://github.com/andyzhangx/kubernetes/commit/60292a793addd008328f4f143a0e3f9f9d642d67), while it won't fix the original issue.

**Comment by andyzhangx** [comment]
Update:
After a few more tries, I found it's related to this code snippet, before `registryClient.List`, we need to generate a new ServicePrincipalToken every time:
https://github.com/kubernetes/kubernetes/blob/b005f2fba340e2a9a3111b499f4f0eaf1ceed3eb/pkg/credentialprovider/azure/azure_credentials.go#L164-L170

I will move this code snippet into Provide() func, and send out a PR!
