### ISSUE TITLE
vsphere cloud provider vcp stopped working after update to kubernetes 1.11.0

### ISSUE THREAD

**Issue by shahbour** [kubernetes/kubernetes#65933]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig cloud-provider
**What happened**:
I had vcp working perfectly on kubernetes v1.9.6 . I had the installation done using kubeadm on our vsphere/vcenter environment .

Yesterday i did update from 1.9.6 -> 1.10.4 -> 1.11.0 , but after the update I am not able to put vcp back to work. I tried complete reinstall but still it is not working . It is complaining about VM Not Found as below
**What you expected to happen**:
VCP to work as it was on v1.9.6
**How to reproduce it (as minimally and precisely as possible)**:
Not sure, this is a production environment so I can't a lot of tries

**Anything else we need to know?**:
```
Jul  7 05:08:41 localhost journal: E0707 05:08:41.853267       1 datacenter.go:78] Unable to find VM by UUID. VM UUID: 
Jul  7 05:08:41 localhost journal: E0707 05:08:41.853374       1 nodemanager.go:414] Error "No VM found" node info for node "engine01" not found
Jul  7 05:08:41 localhost journal: E0707 05:08:41.853416       1 vsphere_util.go:134] Error while obtaining Kubernetes node nodeVmDetail details. error : No VM found
Jul  7 05:08:41 localhost journal: E0707 05:08:41.853444       1 vsphere.go:1160] Failed to get shared datastore: No VM found
Jul  7 05:08:41 localhost journal: I0707 05:08:41.854301       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-disk", UID:"a7c88c13-813d-11e8-aa8c-0050568166d0", APIVersion:"v1", ResourceVersion:"31538424", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass "thin-disk": No VM found
Jul  7 05:08:43 localhost journal: I0707 05:08:43.768259       1 reconciler.go:291] attacherDetacher.AttachVolume started for volume "pvc-a3091746-6a16-11e8-87de-0050568166d0" (UniqueName: "kubernetes.io/vsphere-volume/[3PAR_Datastore06] kubevols/kubernetes-dynamic-pvc-a3091746-6a16-11e8-87de-0050568166d0.vmdk") from node "engine02" 
Jul  7 05:08:43 localhost journal: E0707 05:08:43.785846       1 datacenter.go:78] Unable to find VM by UUID. VM UUID: 
Jul  7 05:08:43 localhost journal: E0707 05:08:43.785913       1 nodemanager.go:282] Error "No VM found" node info for node "engine02" not found
Jul  7 05:08:43 localhost journal: E0707 05:08:43.785938       1 vsphere.go:550] Cannot find node "engine02" in cache. Node not found!!!
Jul  7 05:08:43 localhost journal: E0707 05:08:43.786012       1 attacher.go:80] Error attaching volume "[3PAR_Datastore06] kubevols/kubernetes-dynamic-pvc-a3091746-6a16-11e8-87de-0050568166d0.vmdk" to node "engine02": No VM found
```
```

Jul  7 05:31:40 localhost journal: E0707 05:31:40.976785       1 datacenter.go:78] Unable to find VM by UUID. VM UUID: 
Jul  7 05:31:40 localhost journal: E0707 05:31:40.976856       1 nodemanager.go:414] Error "No VM found" node info for node "engine01" not found
Jul  7 05:31:40 localhost journal: E0707 05:31:40.976883       1 vsphere_util.go:134] Error while obtaining Kubernetes node nodeVmDetail details. error : No VM found
Jul  7 05:31:40 localhost journal: E0707 05:31:40.976900       1 vsphere.go:1160] Failed to get shared datastore: No VM found
Jul  7 05:31:40 localhost journal: I0707 05:31:40.977444       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-disk", UID:"a7c88c13-813d-11e8-aa8c-0050568166d0", APIVersion:"v1", ResourceVersion:"31538424", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass "thin-disk": No VM found
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
vsphere
- OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
Linux engine03 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by shahbour** [comment]
checking the UUID I seems to have it

```
[root@kube-master ~]# cat /sys/class/dmi/id/product_serial
VMware-42 01 b1 65 56 78 30 b8-28 f4 c4 41 fe db 7a e9
[root@kube-master ~]# cat /sys/class/dmi/id/product_uuid
4201B165-5678-30B8-28F4-C441FEDB7AE9
kubectl describe node kube-master | grep  "System UUID"
 System UUID:                4201B165-5678-30B8-28F4-C441FEDB7AE9
```
But the log says 
```
Jul  8 06:25:29 localhost journal: E0708 06:25:29.433320       1 datacenter.go:78] Unable to find VM by UUID. VM UUID:
```
Looks like VM UUID is empty ? , can it be a permission issue that vcp is not able to read the node System UUID ?

**Comment by dkirrane** [comment]
Same issue with VCP manually enabled with required control plane flags (not using vcp-uxi scripts)

`kubectl -n kube-system logs kube-controller-manager-master1 -f`
```
E0709 14:23:08.298645       1 datacenter.go:78] Unable to find VM by UUID. VM UUID:
E0709 14:23:08.298681       1 nodemanager.go:414] Error "No VM found" node info for node "minion1" not found
E0709 14:23:08.298701       1 vsphere_util.go:134] Error while obtaining Kubernetes node nodeVmDetail details. error : No VM found
E0709 14:23:08.298708       1 vsphere.go:1160] Failed to get shared datastore: No VM found
I0709 14:23:08.298945       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"monitoring", Name:"kube-prometheus-grafana", UID:"ff4d1349-7fc0-11e8-94b0-00505680d7f5", APIVersion:"v1", ResourceVersion:"1920", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass "thin-disk": No VM found
E0709 14:23:08.316762       1 datacenter.go:78] Unable to find VM by UUID. VM UUID:
E0709 14:23:08.316815       1 nodemanager.go:414] Error "No VM found" node info for node "minion1" not found
E0709 14:23:08.316829       1 vsphere_util.go:134] Error while obtaining Kubernetes node nodeVmDetail details. error : No VM found
E0709 14:23:08.316836       1 vsphere.go:1160] Failed to get shared datastore: No VM found
I0709 14:23:08.316917       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"monitoring", Name:"alertmanager-kube-prometheus-db-alertmanager-kube-prometheus-0", UID:"ff8a7be0-7fc0-11e8-94b0-00505680d7f5", APIVersion:"v1", ResourceVersion:"1921", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass "thin-disk": No VM found
E0709 14:23:08.334448       1 datacenter.go:78] Unable to find VM by UUID. VM UUID:
E0709 14:23:08.334477       1 nodemanager.go:414] Error "No VM found" node info for node "minion3" not found
E0709 14:23:08.334489       1 vsphere_util.go:134] Error while obtaining Kubernetes node nodeVmDetail details. error : No VM found
E0709 14:23:08.334496       1 vsphere.go:1160] Failed to get shared datastore: No VM found
I0709 14:23:08.334609       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"monitoring", Name:"prometheus-kube-prometheus-db-prometheus-kube-prometheus-0", UID:"ffafd3c2-7fc0-11e8-94b0-00505680d7f5", APIVersion:"v1", ResourceVersion:"1922", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass "thin-disk": No VM found
```

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

I also checked the `vsphere.conf` on one of the worker nodes 'minion1'. It has the key `vm-uuid=4200ea21-067b-885f-dd8b-692790feaf2d` and can confirm with govc that the uuid is correct
```
# govc version
govc 0.18.0


# govc vm.info -vm.uuid=4200ea21-067b-885f-dd8b-692790feaf2d
Name:           minion1
  Path:         /SAN-A1/vm/minion1
  UUID:         4200ea21-067b-885f-dd8b-692790feaf2d
  Guest name:   CentOS 4/5 or later (64-bit)
  Memory:       16384MB
  CPU:          4 vCPU(s)
  Power state:  poweredOn
  Boot time:    2018-07-04 19:22:55.970183 +0000 UTC
  IP address:   10.123.1.1
  Host:         10.123.47.1
```

**Comment by w-leads** [comment]
I linked my PR to this issue, but sorry, it seems to be a different issue.
Would you please  provide a whole controller-managers log with log level(-v) 4?

**Comment by neolit123** [comment]
AFAIK, dumping the flags suggests an invalid flag being passed.

**Comment by shahbour** [comment]
can you please point me about the flags where are they dumped ?

**Comment by w-leads** [comment]
@shahbour thanks for providing the log
```
I0711 07:09:07.014065       1 nodemanager.go:88] Discovering node engine01 with uuid
...
I0711 07:09:07.143029       1 nodemanager.go:88] Discovering node engine02 with uuid
...
I0711 07:09:07.153932       1 nodemanager.go:88] Discovering node engine03 with uuid
...
I0711 07:09:07.170145       1 nodemanager.go:88] Discovering node kube-master with uuid 4201b165-5678-30b8-28f4-c441fedb7ae9
```

kube-master has proper uuid, but others don't. Would you please check followings?
1.  the uuid file ("/sys/class/dmi/id/product_serial") for worker nodes
2. kubernetes nodename and providerID which is generated using uuid. If uuid is properly read by vsphere cloud provider, it's set to like "vsphere://\<uuid\>"
```
kubectl get nodes -o json | jq '.items[]|[.metadata.name, .spec.providerID]'
```

**Comment by shahbour** [comment]
@w-leads thanks, I see something wrong here for 
```
engine03  cat /sys/class/dmi/id/product_serial
VMware-42 01 da 8e d1 e5 c3 56-d1 14 d9 e1 af 60 80 ef
engine02 cat /sys/class/dmi/id/product_serial
VMware-42 01 fd d5 32 da e7 06-a6 e7 3c 6a 82 f7 2e 1d
engine01 cat /sys/class/dmi/id/product_serial
VMware-42 01 28 8e d6 95 a4 bc-14 a4 60 1c cd 17 d9 a2
```

```
(⎈ |production:default)➜  decoder kubectl get nodes -o json | jq '.items[]|[.metadata.name, .spec.providerID]'
[
  "engine01.teltacworldwide.co",
  null
]
[
  "engine02.teltacworldwide.co",
  null
]
[
  "engine03",
  null
]
[
  "kube-master",
  "vsphere://4201b165-5678-30b8-28f4-c441fedb7ae9"
]
(⎈ |production:default)➜  decoder kubectl get nodes -o json | jq '.items[]|[.metadata.name, .spec.externalID]'
[
  "engine01.teltacworldwide.co",
  "engine01.teltacworldwide.co"
]
[
  "engine02.teltacworldwide.co",
  "engine02.teltacworldwide.co"
]
[
  "engine03",
  "engine03"
]
[
  "kube-master",
  "4201b165-5678-30b8-28f4-c441fedb7ae9"
]

```

I just noticed also that externalID for the nodes is different from master

**Comment by shahbour** [comment]
@w-leads  great news for me 👍  , after updating the node info everything worked perfectly.  I don't know if it is correct to set it manually as i did not do that first time but now it is working 

```
(⎈ |production:kube-system)➜  ~ kubectl get nodes -o json | jq '.items[]|[.metadata.name, .spec.externalID, .spec.providerID]'
[
  "engine01",
  "engine01",
  "vsphere://4201288E-D695-A4BC-14A4-601CCD17D9A2"
]
[
  "engine02",
  "engine02",
  "vsphere://4201FDD5-32DA-E706-A6E7-3C6A82F72E1D"
]
[
  "engine03",
  "engine03",
  "vsphere://4201da8e-d1e5-c356-d114-d9e1af6080ef"
]
[
  "kube-master",
  "4201b165-5678-30b8-28f4-c441fedb7ae9",
  "vsphere://4201b165-5678-30b8-28f4-c441fedb7ae9"
]
```

One thing I noticed while updating kubernetes through kubeadm , is that on master it worked perfectly without any issue while on nodes the kubelet did not start and I had to manually create the file `/var/lib/kubelet/kubeadm-flags.env` with `KUBELET_KUBEADM_ARGS=--cgroup-driver=systemd --cni-bin-dir=/opt/cni/bin --cni-conf-dir=/etc/cni/net.d --network-plugin=cni`

Thanks for your help

**Comment by jd485057** [comment]
Similar issue in my case.
vsphere.conf set
```
--cloud-config=/etc/kubernetes/pki/cloud-config/vsphere.conf
```
UUIDs returned bu `cat /sys/class/dmi/id/product_serial` look correct on each node.
But both externalID and providerID are null for all nodes:
```
kubectl get nodes -o json | jq '.items[]|[.metadata.name, .spec.externalID, .spec.providerID]'
[
  "master1",
  null,
  null
]
[
  "minion1-finbar",
  null,
  null
]
[
  "minion2",
  null,
  null
]
[
  "minion3",
  null,
  null
]
```

How do I enable verbose logging for controller manager?
Default log level shows entries like this for every node:
```
E0717 16:05:40.601950       1 datacenter.go:78] Unable to find VM by UUID. VM UUID: 
E0717 16:05:40.601987       1 nodemanager.go:414] Error "No VM found" node info for node "minion2" not found
E0717 16:05:40.602009       1 vsphere_util.go:134] Error while obtaining Kubernetes node nodeVmDetail details. error : No VM found
E0717 16:05:40.602021       1 vsphere.go:1160] Failed to get shared datastore: No VM found
```

**Comment by shahbour** [comment]
edit file vi `/etc/kubernetes/manifests/kube-controller-manager.yaml` and add - --v=4 as below

```
    - --cloud-provider=vsphere
    - --cloud-config=/etc/vsphereconf/vsphere.conf
    - --v=4
```

**Comment by Bondeau** [comment]
Hello, I have the same problem as @jd485057.

The VCP plugin works well with kubernetes 1.10.5 but doesn't work with kubernetes 1.11.x. The OS is CentOS 7.

I tried to install the VM with hardware version 11 and 13.

Both product_serial and product_uuid are the same uuid but the VCP plugin don't find VM by UUID. 
```sh
sudo cat /sys/class/dmi/id/product_serial
VMware-42 07 a2 ca 50 01 33 4d-62 de 30 00 8b 60 90 06
sudo cat /sys/class/dmi/id/product_uuid
4207A2CA-5001-334D-62DE-30008B609006
```

I don't know why the VCP plugin doesn't work with kubernetes 1.11.x. To configure VCP, I followed the procedure [Enabling vSphere Cloud Provider](https://github.com/vmware/kubernetes/tree/enable-vcp-uxi)

**Comment by shahbour** [comment]
you need to update the provide id in node info , you can do that manually

**Comment by Bondeau** [comment]
Thank you @shahbour.

Is it be safe ?

How can I update manualy this provider id ? I'm not familiar with json request sorry.

**Comment by shahbour** [comment]
You can do kubectl edit node ...

**Comment by Bondeau** [comment]
Okay I will try this.
Thank you.

**Comment by Bondeau** [comment]
Hello.

After updating node ExternalID everything worked perfectly.

To update this info, I used this command : 
```sh
kubectl patch node <Node name> -p '{"spec":{"providerID":"vsphere://<vm uuid>"}}'
```

**Comment by shahbour** [comment]
You mean after updating providerId

**Comment by Bondeau** [comment]
Yes sorry.
I fixed it.

**Comment by domcar** [comment]
I also encountered the same Bug and I could solve it by using the workaround suggested by @shahbour (tnx).
Is anyone working on solving it?

**Comment by Vislor** [comment]
I also encountered the same bug when standing up an HA cluster and was able to apply the same workaround (manually adding providerIds for worker nodes).  

It seems that kubeadm properly assigns providerIds to the master nodes (all 3 in my case) but doesn't assign them to worker nodes with the join command.

**Comment by yktsubo** [comment]
Faced the same issue.
Deleting node and restarting kubelet on the node updated spec.providerID in my case.
Note: Mine causes service outage due to removing node.

**Comment by phspies** [comment]
Any idea what the dummy VMDK is about?

```
I0821 18:34:01.502036       1 event.go:221] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"default", Name:"mysqldb", UID:"c564e3bc-a570-11e8-9538-00505689ef47", APIVersion:"apps/v1", ResourceVersion:"20508", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set mysqldb-54b5c898f7 to 1
I0821 18:34:01.970932       1 event.go:221] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"default", Name:"mysqldb-54b5c898f7", UID:"c5c03574-a570-11e8-9538-00505689ef47", APIVersion:"apps/v1", ResourceVersion:"20509", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: mysqldb-54b5c898f7-44hhv
I0821 18:34:02.318793       1 reconciler.go:291] attacherDetacher.AttachVolume started for volume "mysql-pv" (UniqueName: "kubernetes.io/vsphere-volume/[datastore1] kubevols/mysql") from node "kubeworker01" 
I0821 18:34:23.529892       1 operation_generator.go:335] AttachVolume.Attach succeeded for volume "mysql-pv" (UniqueName: "kubernetes.io/vsphere-volume/[datastore1] kubevols/mysql") from node "kubeworker01" 
I0821 18:34:23.549935       1 event.go:221] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"mysqldb-54b5c898f7-44hhv", UID:"c651b3db-a570-11e8-9538-00505689ef47", APIVersion:"v1", ResourceVersion:"20521", FieldPath:""}): type: 'Normal' reason: 'SuccessfulAttachVolume' AttachVolume.Attach succeeded for volume "mysql-pv" 
W0821 18:34:52.835232       1 datacenter.go:214] QueryVirtualDiskUuid failed for diskPath: "[datastore1] kubevols/kube-dummyDisk.vmdk". err: ServerFaultCode: File [datastore1] kubevols/kube-dummyDisk.vmdk was not found

```

**Comment by ReSearchITEng** [comment]
Besides the workaround to manually patch each node, was there a fix for newer versions?
Just tried k8s 1.11.3 is still still facing this issue (with same vsphere settings which work perfectly on 1.10.x)
I think only vmware experts like @divyenpatel can help.

**Comment by dbason** [comment]
Is there any update for @ReSearchITEng 's comment?  Is this fixed in 1.12 or a version later that 1.11.3?  The work around is not really ideal.

**Comment by ReSearchITEng** [comment]
@dbason 1.12 looks fine to me.

**Comment by dkirrane** [comment]
Still hitting this in kubeadm created cluster `1.12.3`
PVC won't provision
`persistentvolume-controller Failed to provision volume with StorageClass "thin-disk": No VM found`

kube-controller-manager pod shows:
`E1207 20:14:34.655991       1 datacenter.go:78] Unable to find VM by UUID. VM UUID:`

**Comment by naveenmprakash** [comment]
> Still hitting this in kubeadm created cluster `1.12.3`.
> `.spec.providerID` still null
> 
> PVC won't provision
> `persistentvolume-controller Failed to provision volume with StorageClass "thin-disk": No VM found`
> 
> kube-controller-manager pod shows:
> `E1207 20:14:34.655991 1 datacenter.go:78] Unable to find VM by UUID. VM UUID:`

Is patching the nodes with the providerID the only way to make this work? I faced the same issue with v1.11.3 and was planning to upgrade to 1.12.x hoping that this was solved in 1.12.

**Comment by umair-akram** [comment]
I lost my External etcd during the upgrade from 1.10.12 to 1.11.6  due to this issue and I have tried patching the the providerId but same error persists also tried to restarting the kubelet services on respective nodes doesn't help.

**Comment by Vislor** [comment]
I just stood up a cluster in Kubernetes 1.13.2 using kubeadm and this appears to be working in this Kubernetes version.  All of my nodes (3 master, 3 worker) had the proper provider id from vSphere.

**Comment by divyenpatel** [comment]
@Vislor 

Did you enable vsphere cloud provider after the K8S cluster deployed using kubeadm? Or did you specify some config file while deploying cluster using kubeadm, which enabled VCP before node registration?

Does restarting `kubelet`, sets provider id on the node with 1.13.2?

**Comment by Vislor** [comment]
@divyenpatel ,

I specified the configuration before running `kubeadm`, the config file I passed to `kubeadm` looked something like this:

```apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.13.2
networking:
  podSubnet: 10.32.0.0/12
apiServer:
  certSANs:
  - "<loadbalancer>"
  extraArgs:
    cloud-provider: vsphere
    cloud-config: /etc/kubernetes/pki/vsphere.conf
controlPlaneEndpoint: "<loadbalancer>:6443"
controllerManager:
  extraArgs:
    cloud-config: /etc/kubernetes/pki/vsphere.conf
    cloud-provider: vsphere```

I also specified the following in `/etc/sysconfig/kublet`:

```KUBELET_EXTRA_ARGS=--cloud-provider=vsphere --cloud-config=/etc/kubernetes/pki/vsphere.conf```

I ran `kubeadm init` on the first master node, and then used `kubeadm join` with the proper arguments on the remaining two master nodes and the three worker nodes (per the current 1.13 documentation on kubernetes.io).  When I checked the provider ids of all the nodes via `kubectl` they all had the proper provider id that matched the machine's UUID.

**Comment by divyenpatel** [comment]
@Vislor

In this case kubelet is already running with cloud-provider vsphere enabled.
and node registration is happening after that, which is setting provider id correctly.

But if you already have kubernetes cluster deployed with kubeadm, without VCP enabled, and later when you try to enable VCP, i think node does not get provider id. and we have to patch nodes manually, or remove nodes from API servers and register them back with restarting kubelet on nodes.

**Comment by umair-akram** [comment]
So In my case after I patched **providerId** plus manually stoped kub-control-manager on the leader node and waited for a new leader to be elected everything started to work fine.

**Comment by mylesagray** [comment]
@divyenpatel Experiencing the same problem with a vanilla install of 1.13.3 using kubeadm.

kubeadm config.yaml:

```yml
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: "vsphere"
    cloud-config: "/etc/kubernetes/vsphere.conf"
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.13.0
apiServer:
  extraArgs:
    cloud-provider: "vsphere"
    cloud-config: "/etc/kubernetes/vsphere.conf"
  extraVolumes:
  - name: cloud
    hostPath: "/etc/kubernetes/vsphere.conf"
    mountPath: "/etc/kubernetes/vsphere.conf"
controllerManager:
  extraArgs:
    cloud-provider: "vsphere"
    cloud-config: "/etc/kubernetes/vsphere.conf"
  extraVolumes:
  - name: cloud
    hostPath: "/etc/kubernetes/vsphere.conf"
    mountPath: "/etc/kubernetes/vsphere.conf"
networking:
  podSubnet: "10.244.0.0/16"
```

Output of `providerID` after kubeadm init and join:

```sh
ubuntu@k8s-master:~$ kubectl get nodes -o json | jq '.items[]|[.metadata.name, .spec.providerID, .status.nodeInfo.systemUUID]'
[
  "k8s-master",
  "vsphere://42029181-1b2d-36cb-5f9f-447c461ff4ef",
  "42029181-1B2D-36CB-5F9F-447C461FF4EF"
]
[
  "k8s-worker1",
  null,
  "4202384A-C7B2-D4C8-6C0E-A111F3827945"
]
[
  "k8s-worker2",
  null,
  "4202ED19-DCDC-61F0-BD25-4537912337A3"
]
[
  "k8s-worker3",
  null,
  "4202AD89-589C-5BA0-2EFE-52A3B63F440D"
]
ubuntu@k8s-master:~$
```

Environment flags from kubeadm are set correctly on the master:

```sh
ubuntu@k8s-master:~$ sudo cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS=--cloud-config=/etc/kubernetes/vsphere.conf --cloud-provider=vsphere --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1 --resolv-conf=/run/systemd/resolve/resolv.conf
```

But not on the workers:

```sh
ubuntu@k8s-worker1:~$ sudo cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS=--cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1 --resolv-conf=/run/systemd/resolve/resolv.conf
ubuntu@k8s-worker1:~$
```

Is this a bug in kubeadm?

And is the only way to fix it after a cluster is created by removing and re-adding a node?

**Comment by lucasslima** [comment]
Hi guys,

I'm a bit late to the party, but I just had to deal with this again, and the process to update the UUID on kubernetes can be a bit annoying, so I made a small script that gets the information from vSphere and patches the Kubernetes nodes. It requires the [govc](https://github.com/vmware/govmomi/tree/master/govc) binary, as well as [jq](https://stedolan.github.io/jq/).
```

**Comment by jesstruck** [comment]
Let me suggest a small fix to the above script that supports spaces in  FOLDER path

```bash
#!/bin/bash

export GOVC_USERNAME='IntegrationstestSVC@intra.coop'
export GOVC_INSECURE=1
export GOVC_PASSWORD='SX7&z#vKH3!4'
export GOVC_URL='dalbvman170201.intra.coop'
DATACENTER='Coop'
FOLDER='PROD/Rancher PROD/Integrationsplatform/Dev'
# In my case I'm using a prefix for the VM's, so grep'ing is necessary.
# You can remove it if the folder you are using only contains the machines you need.
VM_PREFIX='integration-'
IFS=$'\n'
for vm in $(./govc ls "/$DATACENTER/vm/$FOLDER" | grep $VM_PREFIX); do
  MACHINE_INFO=$(./govc vm.info -json -dc=$DATACENTER -vm.ipath="/$vm" -e=true)
  # My VMs are created on vmware with upper case names, so I need to edit the names with awk
  VM_NAME=$(jq -r ' .VirtualMachines[] | .Name' <<< $MACHINE_INFO | awk '{print tolower($0)}')
  # UUIDs come in lowercase, upper case then
  VM_UUID=$( jq -r ' .VirtualMachines[] | .Config.Uuid' <<< $MACHINE_INFO | awk '{print toupper($0)}')
  echo "Patching $VM_NAME with UUID:$VM_UUID"
  # This is done using dry-run to avoid possible mistakes, remove when you are confident you got everything right.
  kubectl patch node $VM_NAME -p "{\"spec\":{\"providerID\":\"vsphere://$VM_UUID\"}}"
done
```

**Comment by jesstruck** [comment]
Let me suggest a small fix to the above script that supports spaces in FOLDER path
```bash
#!/bin/bash

export GOVC_USERNAME='<user>'
export GOVC_INSECURE=1
export GOVC_PASSWORD='<password>'
export GOVC_URL='<server>'
DATACENTER='Coop'
FOLDER='<path>'
# In my case I'm using a prefix for the VM's, so grep'ing is necessary.
# You can remove it if the folder you are using only contains the machines you need.
VM_PREFIX='<prefix>'
IFS=$'\n'
for vm in $(./govc ls "/$DATACENTER/vm/$FOLDER" | grep $VM_PREFIX); do
  MACHINE_INFO=$(./govc vm.info -json -dc=$DATACENTER -vm.ipath="/$vm" -e=true)
  # My VMs are created on vmware with upper case names, so I need to edit the names with awk
  VM_NAME=$(jq -r ' .VirtualMachines[] | .Name' <<< $MACHINE_INFO | awk '{print tolower($0)}')
  # UUIDs come in lowercase, upper case then
  VM_UUID=$( jq -r ' .VirtualMachines[] | .Config.Uuid' <<< $MACHINE_INFO | awk '{print toupper($0)}')
  echo "Patching $VM_NAME with UUID:$VM_UUID"
  # This is done using dry-run to avoid possible mistakes, remove when you are confident you got everything right.
  kubectl patch node $VM_NAME -p "{\"spec\":{\"providerID\":\"vsphere://$VM_UUID\"}}"
done
```

**Comment by ranjujohn** [comment]
Hello @divyenpatel I was trying to setup vsphere cloud provider with K8s 1.14.1. This is a fresh cluster and the provider ID is updated as below. Default storage class is also available. I created a test PVC and it always shows pending. But on the VMware side I can see that the kubevols folder gets created in the specific datastore and the dynamic vmdk file is also created. Any help will be appreciated.

![image](https://user-images.githubusercontent.com/10082696/59278163-cb2dbf00-8c61-11e9-8df1-5c03f999f74d.png)

[root@k8s-1m ~]# kubectl get sc
NAME                     PROVISIONER                    AGE
vsphere-disk (default)   kubernetes.io/vsphere-volume   13d

[root@k8s-1m ~]# kubectl describe pvc/pvc0001
Name:          pvc0001
Namespace:     default
StorageClass:  vsphere-disk
Status:        Pending
Volume:
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"pvc0001","namespace":"default"},"spec":{"accessMode...
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/vsphere-volume
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Events:        <none>
Mounted By:    <none>

[root@k8s-1m ~]# kubectl get nodes -o json | jq '.items[]|[.metadata.name, .spec.providerID, .status.nodeInfo.systemUUID]'
[
  "k8s-1m",
  "vsphere://4205c028-0057-a311-1d79-2b0f0a0d6bf3",
  "4205C028-0057-A311-1D79-2B0F0A0D6BF3"
]
[
  "k8s-1w",
  "vsphere://42051525-c9a3-db23-55ad-4a9e3b4deb9e",
  "42051525-C9A3-DB23-55AD-4A9E3B4DEB9E"
]
[
  "k8s-2m",
  "vsphere://42055538-a961-80b2-bb50-35244f9f57fd",
  "42055538-A961-80B2-BB50-35244F9F57FD"
]
[
  "k8s-2w",
  "vsphere://4205c159-e627-9806-b3b0-69d15204132e",
  "4205C159-E627-9806-B3B0-69D15204132E"
]
[
  "k8s-3m",
  "vsphere://4205a198-fa72-7a2c-3cca-b380af0ee1f4",
  "4205A198-FA72-7A2C-3CCA-B380AF0EE1F4"
]
[
  "k8s-3w",
  "vsphere://42053e29-bcb9-00e4-974c-2fcba8ae7b1d",
  "42053E29-BCB9-00E4-974C-2FCBA8AE7B1D"
]

On Worker:  cat /etc/sysconfig/kubelet
KUBELET_EXTRA_ARGS=--cloud-provider=vsphere

Logs from the Controller Manager:

I0611 13:59:34.945784       1 pv_controller_base.go:407] resyncing PV controller
I0611 13:59:34.945821       1 pv_controller_base.go:170] enqueued "default/pvc0001" for sync
I0611 13:59:34.945859       1 pv_controller_base.go:356] claimWorker[default/pvc0001]
I0611 13:59:34.945872       1 pv_controller_base.go:518] storeObjectUpdate updating claim "default/pvc0001" with version 4753
I0611 13:59:34.945891       1 pv_controller.go:247] synchronizing PersistentVolumeClaim[default/pvc0001]: phase: Pending, bound to: "", bindCompleted: false, boundByController: false
I0611 13:59:34.945910       1 pv_controller.go:334] synchronizing unbound PersistentVolumeClaim[default/pvc0001]: no volume found
I0611 13:59:34.945937       1 pv_controller.go:1342] provisionClaim[default/pvc0001]: started
I0611 13:59:34.945945       1 pv_controller.go:1614] scheduleOperation[provision-default/pvc0001[efef6a4f-815c-11e9-918c-00505685e1c0]]
I0611 13:59:34.945950       1 pv_controller.go:1625] operation "provision-default/pvc0001[efef6a4f-815c-11e9-918c-00505685e1c0]" is already running, skipping

**Comment by mylesagray** [comment]
@ranjujohn are there no logs in the `kubectl describe pvc` output?

**Comment by ranjujohn** [comment]
@mylesagray Please find the screenshot below. Between I actually went through your blog too (https://blah.cloud/kubernetes/setting-up-k8s-and-the-vsphere-cloud-provider-using-kubeadm/). 

![image](https://user-images.githubusercontent.com/10082696/59291073-55821d00-8c7a-11e9-992b-deabc05451b2.png)

**Comment by mylesagray** [comment]
@ranjujohn - are there no items in the “Events” output just under your screenshot of the command? That should list the actual failure cause.

VCP is deprecated but as are all in tree cloud providers from every vendor, it is recommended you keep using this until CSI and CCM for vsphere GA, but the depreciation notice is there as advice, it will take be removed for another few (yet to be decided) K8S versions.

**Comment by ranjujohn** [comment]
@mylesagray - There are no messages or errors under the events section. What you can see in the screenshot is the whole output of describe command. Not sure why is it so. As I mentioned, volume gets created as given in the screenshot above. I will recreate the cluster tomorrow with K8s 1.14.3 and get back.

**Comment by ranjujohn** [comment]
@mylesagray I tried with a fresh cluster but still the pvc shows pending. Below is the error I got in the controller logs. I also found another ticket (https://github.com/kubernetes/kubernetes/issues/72905) for similar issue.

goroutinemap.go:150] Operation for "provision-default/test-claim[ee798e76-8dd4-11e9-9e8b-005056858582]" failed. No retries permitted until 2019-06-13 12:15:29.021689773 +0000 UTC m=+151.946011736 (durationBeforeRetry 500ms). Error: "Operation cannot be fulfilled on persistentvolumeclaims \"test-claim\": the object has been modified; please apply your changes to the latest version and try again"

**Comment by mylesagray** [comment]
@ranjujohn - Can you post the output of `kubectl describe pv`?

**Comment by ranjujohn** [comment]
@mylesagray PV is not created. So obviously nothing to describe. It gets created at the VMware side.

[root@k8s-1m ~]# kubectl get pv
No resources found.
[root@k8s-1m ~]#

[root@k8s-1m ~]# kubectl describe pv
[root@k8s-1m ~]#

**Comment by eohtake** [comment]
I'm also getting "Unable to find VM by UUID"
In my case I have the providerID filled in the node, but with some differences from the system id. Any idea why or how to fix it? It seems I can't patch the node after the value is already there. Getting 

`kubectl get nodes -o json | jq '.items[]|[.metadata.name, .spec.providerID, .status.nodeInfo.systemUUID]'`

```
[
  "kmaster-01",
  "vsphere://e5e91442-4bcd-dae9-5fe2-70842bf2059c",
  "E5E91442-4BCD-DAE9-5FE2-70842BF2059C"
]
```
`
cat /sys/class/dmi/id/product_serial
`
```
4214E9E5-CD4B-E9DA-5FE2-70842BF2059C
VMware-42 14 b0 2a 4c 18 44 af-52 47 37 50 e7 cb b5 3a
```

Log from the controller:
datacenter.go:78] Unable to find VM by UUID. VM UUID: e5e91442-4bcd-dae9-5fe2-70842bf2059c

**Comment by feered** [comment]
Running Kubernetes 1.16 and running into similar issues as OP.

`kubectl get nodes -o json | jq '.items[]|[.metadata.name, .spec.providerID, .status.nodeInfo.systemUUID]'`
```
[
  "k8s-master-node-1",                                                                                                                                                                                                                          "vsphere://422E6B23-8EA7-9224-0C8E-38CA51FD82ED",                                                                                                                                                                                             "236B2E42-A78E-2492-0C8E-38CA51FD82ED"                                                                                                                                                                                                      ]
[                                                                                                                                                                                                                                               "k8s-slave-node-2",                                                                                                                                                                                                                           "vsphere://422EEEAA-E258-AD4F-7F60-C3F028DAC133",                                                                                                                                                                                             "AAEE2E42-58E2-4FAD-7F60-C3F028DAC133"                                                                                                                                                                                                      ]
[                                                                                                                                                                                                                                               "k8s-slave-node-3",                                                                                                                                                                                                                           "vsphere://422EE17E-0EAE-478A-4FC3-CF277FADCFAB",                                                                                                                                                                                             "7EE12E42-AE0E-8A47-4FC3-CF277FADCFAB"                                                                                                                                                                                                      ]
```

The UUID matches across the board. The log from control-manager is giving me this:

```
E0927 15:08:15.330894       1 datacenter.go:78] Unable to find VM by UUID. VM UUID:
E0927 15:08:15.330948       1 nodemanager.go:434] Error "No VM found" node info for node "k8s-master-node-1" not found
E0927 15:08:15.330967       1 vsphere_util.go:132] Error while obtaining Kubernetes node nodeVmDetail details. error : No VM found
E0927 15:08:15.330979       1 vsphere.go:1317] Failed to get shared datastore: No VM found
```

Note the empty `VM UUID:`.

**Comment by hashdelta** [comment]
I am experiencing the same problems. I am running K8s 1.16, I can see the volumes created and initialized with the requested disk size but the PVC remains as pending. Is it safe to assume vsphere integration is completely broken at this point?

**Comment by SandeepPissay** [comment]
@BaluDontu Can you look into this?

**Comment by Vislor** [comment]
I was experiencing the exact same thing as @hashdelta as well -- I could see the volumes created successfully in the vSphere data store but the PVC's never came out of pending.  I fixed it (in our case) by correcting the permissions on the account used by Kubernetes to access vSphere.  

Since our installation had been working since at least 1.9 with no changes in our vSphere installation I assume that something changed in the vSphere Cloud Provider and the permissions it needs.

I can't remember which permission was missing but updating to the current list for Dynamic Provisioning (located [here](https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html)) fixed the issue for us.
