### ISSUE TITLE
Resizing a persistent volume is partially broken on openstack (cinder)

### ISSUE THREAD

**Issue by dguendisch** [kubernetes/kubernetes#66687]
Resizing a persistent volume is partially broken on openstack (cinder) with k8s v1.11.1.
Partially in the sense that static resizing (requiring a pod restart) works, but the newly introduced online resizing (not requiring a pod restart) fails.

Upon resizing a pvc it remains in the Resizing condition forever (see the warning event) until I delete the pod that has this pvc mounted:
```
kubectl describe pvc my-pvc

Name:          my-pvc
Namespace:     default
StorageClass:  default
Status:        Bound
Volume:        pvc-f9a62b59-9109-11e8-bd53-2ea0478be355
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/cinder
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
Conditions:
  Type       Status  LastProbeTime                     LastTransitionTime                Reason  Message
  ----       ------  -----------------                 ------------------                ------  -------
  Resizing   True    Mon, 01 Jan 0001 00:00:00 +0000   Thu, 26 Jul 2018 21:32:38 +0200
Events:
  Type     Reason                 Age               From                         Message
  ----     ------                 ----              ----                         -------
  Normal   ProvisioningSucceeded  7m                persistentvolume-controller  Successfully provisioned volume pvc-f9a62b59-9109-11e8-bd53-2ea0478be355 using kubernetes.io/cinder
  Warning  VolumeResizeFailed     32s (x3 over 2m)  volume_expand                Error expanding volume "default/my-pvc" of plugin kubernetes.io/cinder : volume status is not available
```
After pod deletion it notifies me (correctly) that it's now waiting for the pod to come up to finish resizing:
```
FileSystemResizePending   True    Mon, 01 Jan 0001 00:00:00 +0000   Thu, 26 Jul 2018 22:03:02 +0200           Waiting for user to (re-)start a pod to finish file system resize of volume on node.
```
So far the warning event does not break the ExpandPersistentVolumes feature, as this one anyhow requires a pod restart.

However it breaks the newly introduced ExpandInUsePersistentVolumes feature (alpha with k8s v1.11; doesn't require a pod restart for resizing to finish), as the pvc will remain in "Resizing" condition forever (or until the pod is restarted but this defeats the purpose of ExpandInUsePersistentVolumes).

I'm not sure whether this is fully related but upon digging around I found https://bugzilla.redhat.com/show_bug.cgi?id=1535314 and a consecutive fix with https://github.com/kubernetes/kubernetes/pull/58685 which was merged on Jan 23.
However a few days later this fix seems to be (probably accidentally) overwritten with this commit: https://github.com/kubernetes/kubernetes/commit/9326e845e48e2cc61f57094bd7561e37fb831ce5#diff-c6603a39b8f63223075a6ac640bd6ef9R235

/kind bug
/sig storage
/sig openstack

**Comment by xiaoxubeii** [comment]
It is already fixed. So I will close it.

**Comment by Wade201801** [comment]
@xiaoxubeii 

I am trying cinder online pvc resizing on kubernetes1.12.2.  I noticed this kubernetes version has include your fix, but I still failed to resize pvc online.

The error log has no change:
`Warning    VolumeResizeFailed     45s (x2 over 66s)  volume_expand                Error expanding volume "default/myclaim-expend" of plugin kubernetes.io/cinder : volume status is not available
`

The error log is reported  below code line "volume.Status != volumeAvailableStatus"
pkg/cloudprovider/providers/openstack/openstack_volumes.go
`// ExpandVolume expands the size of specific cinder volume (in GiB)
func (os *OpenStack) ExpandVolume(volumeID string, oldSize resource.Quantity, newSize resource.Quantity) (resource.Quantity, error) {
	volume, err := os.getVolume(volumeID)
	if err != nil {
		return oldSize, err
	}
	if volume.Status != volumeAvailableStatus {
		// cinder volume can not be expanded if its status is not available
		return oldSize, fmt.Errorf("volume status is not available")
	}`

One point confused me, once cinder volume is used  by pod, it's status is "in-use", how the online pvc resizing pass the code check "volume.Status != volumeAvailableStatus"? 

There's where the online pvc resizing fails.

**Comment by gnufied** [comment]
It looks like Cinder can not support online volume expansion - https://bugzilla.redhat.com/show_bug.cgi?id=1184786 which is what is happening here. Even if online expansion is enabled, I think to actually perform resizing of Cinder volumes - you must bring the pod down.
