### ISSUE TITLE
[failing test] [sig-instrumentation] Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster.

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#66833]
This test is failing for 1.9 branch and blocking the 1.9.10 release.

dashboard link: https://k8s-testgrid.appspot.com/sig-release-1.9-blocking#soak-gci-gce-1.9

Example failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-soak-gci-gce-stable2/560

log:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/monitoring/influxdb.go:45
Jul 29 14:01:40.887: monitoring using heapster and influxdb test failed
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/monitoring/influxdb.go:308
```

/sig instrumentation

**Comment by DirectXMan12** [comment]
cc @loburm, who seemed to have an interest in the state of this test.

**Comment by coffeepac** [comment]
this should be resolved now.  @mbohlool can you confirm this issue is no longer blocking the release?

**Comment by mbohlool** [comment]
White it is not blocking the release, the test is still failing. look here: https://k8s-testgrid.appspot.com/sig-release-1.9-blocking#soak-gci-gce-1.9

**Comment by jberkus** [comment]
Closing, because we simply don't care about 1.9 anymore.

/close
