### ISSUE TITLE
init error: "kubelet cannot pull or find the following control plane images"

### ISSUE THREAD

**Issue by printfcoder** [kubernetes/kubernetes#68671]
> /sig bug 

**What happened**:

```bash
$ kubeadm init

/****

This error is likely caused by:
			- The kubelet is not running
			- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
			- No internet connection is available so the kubelet cannot pull or find the following control plane images:
				- k8s.gcr.io/kube-apiserver-amd64:v1.11.3
				- k8s.gcr.io/kube-controller-manager-amd64:v1.11.3
				- k8s.gcr.io/kube-scheduler-amd64:v1.11.3
				- k8s.gcr.io/etcd-amd64:3.2.18
				- You can check or miligate this in beforehand with "kubeadm config images pull" to make sure the images
				  are downloaded locally and cached.
```
**My images: **:

```bash
root@u-s-1:/tmp# kubeadm config images pull
[config/images] Pulled k8s.gcr.io/kube-apiserver-amd64:v1.11.3
[config/images] Pulled k8s.gcr.io/kube-controller-manager-amd64:v1.11.3
[config/images] Pulled k8s.gcr.io/kube-scheduler-amd64:v1.11.3
[config/images] Pulled k8s.gcr.io/kube-proxy-amd64:v1.11.3
[config/images] Pulled k8s.gcr.io/pause:3.1
[config/images] Pulled k8s.gcr.io/etcd-amd64:3.2.18
[config/images] Pulled k8s.gcr.io/coredns:1.1.3
```
 
- Kubernetes version (use `kubectl version`):

```text
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```
root@u-s-1:/tmp# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):

```
Linux u-s-1 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by neolit123** [comment]
@printfcoder 
hi, please try passing `--kubernetes-version=1.11.3` to `kubeadm init .... `

if this doesn't work for you, please re-open the issue.
this is fixed in `1.12.0` which will be released 25th september.

/sig cluster-lifecycle
/close

**Comment by printfcoder** [comment]
@neolit123 
Thks for your replication.
Certainly the kb version I used was 1.11.3. Now, I pass the version `--kubernetes-version=1.11.3` explicitly.

```bash
root@u-s-1:~# kubeadm init --kubernetes-version=1.11.3
[init] using Kubernetes version: v1.11.3
....
[init] this might take a minute or longer if the control plane images have to be pulled
....
		Unfortunately, an error has occurred:
			timed out waiting for the condition

		This error is likely caused by:
			- The kubelet is not running
			- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
			- No internet connection is available so the kubelet cannot pull or find the following control plane images:
				- k8s.gcr.io/kube-apiserver-amd64:v1.11.3
				- k8s.gcr.io/kube-controller-manager-amd64:v1.11.3
				- k8s.gcr.io/kube-scheduler-amd64:v1.11.3
				- k8s.gcr.io/etcd-amd64:3.2.18
				- You can check or miligate this in beforehand with "kubeadm config images pull" to make sure the images
				  are downloaded locally and cached.
...
```

So, the error is still here.

**Comment by neolit123** [comment]
@printfcoder 
can your try pre-pulling the images:
`kubeadm config images list --kubernetes-version=1.11.3`
`kubeadm config images pull --kubernetes-version=1.11.3`

but it could be a different error.

**Comment by neolit123** [comment]
@printfcoder 
we have better errors reports in 1.12, but my guess here is that you don't have internet connectivity to `k8s.gcr.io`.

does this work:
`docker pull k8s.gcr.io/kube-apiserver-amd64:v1.11.3`
?

**Comment by printfcoder** [comment]
@neolit123 
Yes，it works via a proxy server.

I have tried  both `docker pull k8s.gcr.io/**` and `kubeadm config images list`, and the images pulled fine. When cmd `docker pull` pulled OK then I removed all the images then tried `kubeadm config images list`, both of them two method to get images work very good although very slow.

**Comment by printfcoder** [comment]
@neolit123 
So, this issue will be fixed?

**Comment by neolit123** [comment]
@printfcoder 

>I have tried both docker pull k8s.gcr.io/** and kubeadm config images list, and the images pulled fine. When cmd docker pull pulled OK then I removed all the images then tried kubeadm config images list, both of them two method to get images work very good although very slow.

from your last comment i understood that this is working now for you.
could you explain again?

**Comment by printfcoder** [comment]
@neolit123 

Oh, you misunderstood. Images were always pulled successfully. The problem was the images existed, but  ERROR:
`No internet connection is available so the kubelet cannot pull or find the following control plane images
...
`
appeared every time ran `init`

**Comment by neolit123** [comment]
ok, i see.

that error has more possible causes...
```
This error is likely caused by:
			- The kubelet is not running
			- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
			- No internet connection is available so the kubelet cannot pull or find the following control plane images:
```

`No internet connection is available so the kubelet cannot pull or find the following control plane images`
is only one of them and given you have the images that's not it.

/reopen

can you provide the output of these two commands?
1.
```
systemctl status kubelet
```

2.
```
journalctl -xeu kubelet
```

**Comment by printfcoder** [comment]
@neolit123  Please:

```bash
root@u-s-1:~# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Sat 2018-09-15 07:25:19 UTC; 4 days ago
     Docs: https://kubernetes.io/docs/home/
 Main PID: 19063 (kubelet)
    Tasks: 19 (limit: 4571)
   CGroup: /system.slice/kubelet.service
           └─19063 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=cgroupfs --cni-bin-dir=/op

Sep 20 02:49:12 u-s-1 kubelet[19063]: W0920 02:49:12.648090   19063 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
 
```

```bash
root@u-s-1:~# journalctl -xeu kubelet
Sep 20 02:48:32 u-s-1 kubelet[19063]: E0920 02:48:32.628096   19063 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni c
Sep 20 02:48:37 u-s-1 kubelet[19063]: W0920 02:48:37.629942   19063 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
```

**Comment by neolit123** [comment]
```
Sep 20 02:48:32 u-s-1 kubelet[19063]: E0920 02:48:32.628096   19063 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni c
Sep 20 02:48:37 u-s-1 kubelet[19063]: W0920 02:48:37.629942   19063 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
```

is there more in the log?

**Comment by printfcoder** [comment]
yes, but repeated:

```bash
Sep 20 11:11:04 u-s-1 kubelet[19063]: W0920 11:11:04.169046   19063 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Sep 20 11:11:04 u-s-1 kubelet[19063]: E0920 11:11:04.169349   19063 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni c
Sep 20 11:11:09 u-s-1 kubelet[19063]: W0920 11:11:09.171868   19063 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Sep 20 11:11:09 u-s-1 kubelet[19063]: E0920 11:11:09.172049   19063 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni c
Sep 20 11:11:14 u-s-1 kubelet[19063]: W0920 11:11:14.174900   19063 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Sep 20 11:11:14 u-s-1 kubelet[19063]: E0920 11:11:14.176055   19063 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni c
Sep 20 11:11:19 u-s-1 kubelet[19063]: W0920 11:11:19.180511   19063 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Sep 20 11:11:19 u-s-1 kubelet[19063]: E0920 11:11:19.181632   19063 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni c
Sep 20 11:11:24 u-s-1 kubelet[19063]: W0920 11:11:24.185471   19063 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Sep 20 11:11:24 u-s-1 kubelet[19063]: E0920 11:11:24.186078   19063 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni c
Sep 20 11:11:29 u-s-1 kubelet[19063]: W0920 11:11:29.188977   19063 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Sep 20 11:11:29 u-s-1 kubelet[19063]: E0920 11:11:29.189731   19063 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni c
Sep 20 11:11:34 u-s-1 kubelet[19063]: W0920 11:11:34.191497   19063 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
```

**Comment by neolit123** [comment]
sorry but i cannot help further without more logs from the kubelet.
```
No networks found in /etc/cni/net.d
```
this is message that is not important for that phase.
kubeadm fails before the step of installing CNI, so the issue is something else.

**Comment by printfcoder** [comment]
OK, I will try other way. Thank you very much.

**Comment by neolit123** [comment]
/close
please re-open the ticket in the kubernetes/kubeadm if you are still having problems.
thanks.
