### ISSUE TITLE
Flannel won't start (kubeadm installation)

### ISSUE THREAD

**Issue by waldauf** [kubernetes/kubernetes#68818]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig Network

**What happened**:
I have installed Kubernetes cluster on 3 nodes (via `kubeadm init` where ETCD is running standalone in docker container). Everything works fine but before a few days all Kubernetes went down. I found out that problem is in Flannel. Flannel pods won't start and broke Kubernetes.

```
$ kubectl --namespace=kube-system get pod -o wide
NAME                                   READY     STATUS              RESTARTS   AGE       IP            NODE
kube-apiserver-vncub0625               1/1       Running             3          19h       10.96.22.11   vncub0625
kube-apiserver-vncub0626               1/1       Running             2          19h       10.96.22.14   vncub0626
kube-controller-manager-vncub0625      1/1       Running             10         109d      10.96.22.11   vncub0625
kube-controller-manager-vncub0626      1/1       Running             9          109d      10.96.22.14   vncub0626
kube-dns-6f4fd4bdf-99kh9               0/3       ContainerCreating   0          1h        <none>        vncub0625
kube-flannel-ds-297x5                  0/1       CrashLoopBackOff    27         16h       10.96.22.14   vncub0626
kube-flannel-ds-wdhg7                  0/1       Error               33         16h       10.96.22.11   vncub0625
kube-proxy-6nbnd                       1/1       Running             8          109d      10.96.22.11   vncub0625
kube-proxy-rlpk2                       1/1       Running             7          109d      10.96.22.14   vncub0626
kube-scheduler-vncub0625               1/1       Running             12         109d      10.96.22.11   vncub0625
kube-scheduler-vncub0626               1/1       Running             8          109d      10.96.22.14   vncub0626
kubernetes-dashboard-7f6988888-nhkss   0/1       Error               0          4d        <none>        vncub0626
rbd-provisioner-788846b794-9ft8w       0/1       Error               5          83d       <none>        vncub0626
tiller-deploy-77f668b986-flwhs         0/1       Error               3          90d       <none>        vncub0626
```

Flannel log:
```
$ kubectl --namespace=kube-system logs kube-flannel-ds-wdhg7
I0919 07:00:31.799180       1 main.go:475] Determining IP address of default interface
I0919 07:00:31.799532       1 main.go:488] Using interface with name eth0 and address 10.96.22.11
I0919 07:00:31.799551       1 main.go:505] Defaulting external address to interface address (10.96.22.11)
E0919 07:00:31.813322       1 main.go:232] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-wdhg7': Get https://10.6.142.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-wdhg7: dial tcp 10.6.142.1:443: getsockopt: connection refused
```
I tried remove/install Flannel, stop kubelet and docker and remove docker NI and reboot servers... and nothing helped.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure what is root cause. It happend from one day to anohter. Maybe there was some reboot of servers.

**Anything else we need to know?**:
- Kubeadm-init
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: v1.9.2
api:
  advertiseAddress: 10.96.22.11
  bindPort: 6443
networking:
  podSubnet: 192.168.0.0/16
  serviceSubnet: 10.6.142.0/24
apiServerCertSANs:
- master01
- master02
- master03
- 10.96.22.11
- 10.96.22.14
- 10.96.22.9
- 172.17.0.1
etcd:
  caFile: /appl/kubeadm/etcd/certs/ca.pem
  certFile: /appl/kubeadm/etcd/certs/client.pem
  keyFile: /appl/kubeadm/etcd/certs/client.key
  endpoints:
  - https://10.96.22.11:2379
  - https://10.96.22.14:2379
  - https://10.96.22.9:2379
```

**Environment**:
- Kubernetes version: v1.9.2
- Cloud provider or hardware configuration:  OpenStack
- OS:Ubuntu 16.04.5 LTS run on
- Kernel: `Linux vncub0625 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`
- Install tools: 
  - Docker: 18.03.0-ce-dev
- Others: list docker images:
```
$ sudo docker images
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
quay.io/external_storage/rbd-provisioner                 latest              86c42ec9ebb0        2 months ago        404MB                                                                                                                  
nexus3:18444/k8s/tiller                                  v2.9.1              6253045f26c6        4 months ago        36.1MB
gcr.io/google_containers/kubernetes-dashboard-amd64      v1.8.3              0c60bcf89900        7 months ago        102MB
gcr.io/google_containers/etcd-amd64                      3.2.14              f3c015c2d7bb        7 months ago        229MB
quay.io/coreos/flannel                                   v0.10.0-amd64       f0fad859c909        7 months ago        44.6MB
nexus3.kb.cz:18444/k8s_infra/etcd                        v3.3                29cd12af0082        7 months ago        39.4MB
gcr.io/google_containers/kube-proxy-amd64                v1.9.2              e6754bb0a529        8 months ago        109MB
gcr.io/google_containers/kube-apiserver-amd64            v1.9.2              7109112be2c7        8 months ago        210MB
gcr.io/google_containers/kube-controller-manager-amd64   v1.9.2              769d889083b6        8 months ago        138MB
gcr.io/google_containers/kube-scheduler-amd64            v1.9.2              2bf081517538        8 months ago        62.7MB
gcr.io/google_containers/k8s-dns-sidecar-amd64           1.14.7              db76ee297b85        11 months ago       42MB
gcr.io/google_containers/k8s-dns-kube-dns-amd64          1.14.7              5d049a8c4eec        11 months ago       50.3MB
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64     1.14.7              5feec37454f4        11 months ago       41MB
gcr.io/google_containers/heapster-influxdb-amd64         v1.3.3              577260d221db        12 months ago       12.5MB
gcr.io/google_containers/pause-amd64                     3.0                 99e59f495ffa        2 years ago         747kB
```

**Comment by waldauf** [comment]
In kubelet log I often see these lines:
```
Sep 19 10:47:17 vncub0625 kubelet[6018]: E0919 10:47:17.553716    6018 cni.go:259] Error adding network: open /run/flannel/subnet.env: no such file or directory
Sep 19 10:47:17 vncub0625 kubelet[6018]: E0919 10:47:17.554348    6018 cni.go:227] Error while adding to cni network: open /run/flannel/subnet.env: no such file or directory
```

There is not created _cni0_ network bridge:
```
$ brctl show
bridge name	bridge id		STP enabled	interfaces
docker0		8000.0242128f4509	no		veth7a470b4
							vethffa89d4
```

**Comment by tanshanshan** [comment]
> kube-dns-6f4fd4bdf-99kh9               0/3       ContainerCreating   0          1h        <none>        vncub0625

dns not start ,maybe you can check it firstly

**Comment by waldauf** [comment]
Kube-dns cannot run without Flannel:
```
Sep 21 12:02:34 vncub0625 kubelet[8477]: E0921 12:02:34.715898    8477 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "kube-dns-6f4fd4bdf-b7qw8_kube-system(5783d699-bcb3-11e8-9112-fa163eeb8c30)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "kube-dns-6f4fd4bdf-b7qw8_kube-system" network: open /run/flannel/subnet.env: no such file or directory
Sep 21 12:02:34 vncub0625 kubelet[8477]: E0921 12:02:34.715913    8477 kuberuntime_manager.go:647] createPodSandbox for pod "kube-dns-6f4fd4bdf-b7qw8_kube-system(5783d699-bcb3-11e8-9112-fa163eeb8c30)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "kube-dns-6f4fd4bdf-b7qw8_kube-system" network: open /run/flannel/subnet.env: no such file or directory
Sep 21 12:02:34 vncub0625 kubelet[8477]: E0921 12:02:34.715978    8477 pod_workers.go:186] Error syncing pod 5783d699-bcb3-11e8-9112-fa163eeb8c30 ("kube-dns-6f4fd4bdf-b7qw8_kube-system(5783d699-bcb3-11e8-9112-fa163eeb8c30)"), skipping: failed to "CreatePodSandbox" for "kube-dns-6f4fd4bdf-b7qw8_kube-system(5783d699-bcb3-11e8-9112-fa163eeb8c30)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-dns-6f4fd4bdf-b7qw8_kube-system(5783d699-bcb3-11e8-9112-fa163eeb8c30)\" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod \"kube-dns-6f4fd4bdf-b7qw8_kube-system\" network: open /run/flannel/subnet.env: no such file or directory"
Sep 21 12:02:34 vncub0625 kubelet[8477]: I0921 12:02:34.716249    8477 server.go:231] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-dns-6f4fd4bdf-b7qw8", UID:"5783d699-bcb3-11e8-9112-fa163eeb8c30", APIVersion:"v1", ResourceVersion:"14985971", FieldPath:""}): type: 'Warning' reason: 'FailedCreatePodSandBox' Failed create pod sandbox.
```

There is some problem with CNI and Flannel. But I cannot find it.

**Comment by mjrb** [comment]
+1 i have a similar issue where i tried to use kubeadm to make a cluster for the first time. the only config i applied were these: 
- https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
- https://raw.githubusercontent.com/coreos/flannel/c5d10c8/Documentation/kube-flannel.yml
i found them from the documentation https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

**Comment by fabiand** [comment]
It's a cyclic dependency - I think!

coredns can only be scheduled if networking is configured.
This is done by the network plugin whatever it is - AFTER kubeadm is done.

BUT, during kubeadm, [kube proxy configures iptables to not permit any DNS traffic if no dns endpoints are configured](https://github.com/kubernetes/kubernetes/blob/d25e6a6f62311ecffc1fce472e4c936b13291a85/pkg/proxy/iptables/proxier.go#L837). There are no endpoints, because no dns plugin is running (coredns or kube-dns), because it is wiating for the networking to be configured.

Summary: dns is not comming up, because it waits for networking, but networking can not be done, because DNS is not working anymore, because it's node wide configured to use kubes dns.

Workaround: Prefetch kubeadm images AND the network provider images.

**Comment by fabiand** [comment]
Actually, to me it was that the undercloud hat the same ip ranges as the services.

**Comment by waldauf** [comment]
@fabiand I checked docker images and everything was prefetched (at least I think). 

@kaizhaokover unfortunately no. I had to reset K8s cluster and create new one. After new initialization was flannel alright.

**Comment by fabiand** [comment]
Sorry for the noise. For me it was an overlap in IP ranges between my undercloud and Kube overlay.
This caused connection issues (aka DNS resolution failed) and this caused this bug for me. Thus for me it was myself who did it.

**Comment by hongjyan** [comment]
@fabiand can you explain details? 
I see service subnet: "serviceSubnet: 10.6.142.0/24" do not mix with your undercloud subnet which should be 10.96.22.0/24. 
I met this same problem, how you fix it?

**Comment by waldauf** [comment]
@hongjyan Yes, I fixed it - by reinstalling all K8s cluster. There wasn't another way how to fix it in short time.
If you format your code it will be better readable than just paste it in. ;]

**Comment by hongjyan** [comment]
@waldauf sorry, start do formatting from now on.

I think this problem may be related to openstack particular networking.
In my case, multi kubernetes masters deployed on different openstack clouds,  the IP of endpoint of kubernetes service is 192.168.0.x, it is internal.  So, theoretically, endpoints IP address could be overlapping. I wanted to use floating IP as endpoints but errors like "can not bind to address 10.183.x.x" occured, so i was forced to use internal IPs.

```
[root@81-k8s-1 ~]# kubectl describe svc kubernetes   
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                10.96.0.1
Port:              https  443/TCP
TargetPort:        6443/TCP
Endpoints:         192.168.0.13:6443,192.168.0.18:6443,192.168.0.31:6443
Session Affinity:  None
Events:            <none>
```
I delete the kube-apiserver pods on the host where "curl 10.96.0.1:443" runs ok to force kubernetes serive switch to another pod. Then on the new host where kubernetes service selects,  do "curl 10.96.0.1:443",  it works as following but if curl on the previous working host, it won't work. 
```
[root@81-k8s-1~]# curl 10.96.0.1:443

```

And i also found cni interface only be created on hosts where "curl 10.96.0.1:443" works.

@waldauf , which type undercloud your HA kubernetes cluster are running on? the single openstack cloud or mutli openstack clouds?

**Comment by hongjyan** [comment]
I setup one-host k8s cluster and this problem still exist, so it should not concern mutli clouds.
```
[root@81-k8s-1 ~]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                         READY   STATUS              RESTARTS   AGE   IP             NODE                 NOMINATED NODE
kube-system   coredns-576cbf47c7-6qkmh                     0/1     ContainerCreating   0          19m   <none>         81-k8s-1.novalocal   <none>
kube-system   coredns-576cbf47c7-wdhjv                     0/1     ContainerCreating   0          19m   <none>         81-k8s-1.novalocal   <none>
kube-system   kube-apiserver-81-k8s-1.novalocal            1/1     Running             0          16m   192.168.0.18   81-k8s-1.novalocal   <none>
kube-system   kube-controller-manager-81-k8s-1.novalocal   1/1     Running             0          16m   192.168.0.18   81-k8s-1.novalocal   <none>
kube-system   kube-flannel-ds-amd64-8djcl                  0/1     CrashLoopBackOff    5          13m   192.168.0.18   81-k8s-1.novalocal   <none>
kube-system   kube-proxy-gfg9b                             1/1     Running             0          16m   192.168.0.18   81-k8s-1.novalocal   <none>
kube-system   kube-scheduler-81-k8s-1.novalocal            1/1     Running             0          16m   192.168.0.18   81-k8s-1.novalocal   <none>

[root@81-k8s-1 ~]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                         READY   STATUS              RESTARTS   AGE   IP             NODE                 NOMINATED NODE
kube-system   coredns-576cbf47c7-6qkmh                     0/1     ContainerCreating   0          19m   <none>         81-k8s-1.novalocal   <none>
kube-system   coredns-576cbf47c7-wdhjv                     0/1     ContainerCreating   0          19m   <none>         81-k8s-1.novalocal   <none>
kube-system   kube-apiserver-81-k8s-1.novalocal            1/1     Running             0          16m   192.168.0.18   81-k8s-1.novalocal   <none>
kube-system   kube-controller-manager-81-k8s-1.novalocal   1/1     Running             0          16m   192.168.0.18   81-k8s-1.novalocal   <none>
kube-system   kube-flannel-ds-amd64-8djcl                  0/1     CrashLoopBackOff    5          13m   192.168.0.18   81-k8s-1.novalocal   <none>
kube-system   kube-proxy-gfg9b                             1/1     Running             0          16m   192.168.0.18   81-k8s-1.novalocal   <none>
kube-system   kube-scheduler-81-k8s-1.novalocal            1/1     Running             0          16m   192.168.0.18   81-k8s-1.novalocal   <none>
[root@81-k8s-1 ~]# curl  --cert /etc/kubernetes/ssl/kubernetes.pem --key /etc/kubernetes/ssl/kubernetes-key.pem --cacert /etc/kubernetes/ssl/ca.pem https://10.96.0.1:6443    
curl: (7) Failed connect to 10.96.0.1:6443; Connection refused
[root@81-k8s-1 ~]# curl  --cert /etc/kubernetes/ssl/kubernetes.pem --key /etc/kubernetes/ssl/kubernetes-key.pem --cacert /etc/kubernetes/ssl/ca.pem https://192.168.0.18:6443
curl: (60) Peer's Certificate issuer is not recognized.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
[root@81-k8s-1 ~]# curl  --cert /etc/kubernetes/ssl/kubernetes.pem --key /etc/kubernetes/ssl/kubernetes-key.pem --cacert /etc/kubernetes/ssl/ca.pem https://10.181.131.226:6443
curl: (60) Peer's Certificate issuer is not recognized.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
[root@81-k8s-1 ~]# curl  --cert /etc/kubernetes/ssl/kubernetes.pem --key /etc/kubernetes/ssl/kubernetes-key.pem --cacert /etc/kubernetes/ssl/ca.pem https://10.96.0.1:443      
curl: (7) Failed connect to 10.96.0.1:443; Connection refused
[root@81-k8s-1 ~]# 
```

this kubernetes service:10.96.0.1:443  is bonded to 192.168.0.18:6443, is this caused by lacking of dns or some iptables rules missing?

**Comment by waldauf** [comment]
@hongjyan My K8s is running on the single OpenStack cloud. But I'm not administrator of OpenStack and cannot say more information. :/

**Comment by hongjyan** [comment]
I give up kubeadm, it is too hard to debug for HA cluster on multihost openstack clouds, and setup it successfully by hard way accroding to experience from:
 [hardway](https://github.com/kelseyhightower/kubernetes-the-hard-way) 
[hardway chinese edition on metal centos](https://jimmysong.io/kubernetes-handbook/practice/install-kubernetes-on-centos.html)
[how flannel work](https://tonybai.com/2017/01/17/understanding-flannel-network-for-kubernetes/)
