### ISSUE TITLE
Pods stuck terminating (MountVolume.SetUp failed)

### ISSUE THREAD

**Issue by hyperbolic2346** [kubernetes/kubernetes#70044]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Updating ingress and deleted service, daemon set, service account, cluster role binding, and config map in that order. I then deployed the ingress pods into a new namespace. The new pods never could start because the old pods got stuck in terminating and have been for hours now.
**What you expected to happen**:
Old pods to die and new pods to take their place, with some downtime.
**How to reproduce it (as minimally and precisely as possible)**:
I can provide yaml if valuable, but I'm using juju to deploy so I just did the following:
```
juju deploy canonical-kubernetes
juju config kubernetes-worker ingress=false
kubectl deploy k8s_1.12_ingress.yaml
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.1
- Cloud provider or hardware configuration: gce and aws
- OS (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS
- Kernel (e.g. `uname -a`): 4.15.0-1021-gcp
- Install tools: juju
- Others:

```
$ kubectl get po --all-namespaces
NAMESPACE                         NAME                                                      READY   STATUS        RESTARTS   AGE
default                           microbot-66cb4987b7-h4wkd                                 1/1     Running       0          8m7s
default                           microbot-66cb4987b7-sn6dm                                 1/1     Running       0          8m7s
default                           microbot-66cb4987b7-tgrmc                                 1/1     Running       0          8m7s
default                           nginx-ingress-kubernetes-worker-controller-9rp7h          0/1     Terminating   0          45m
default                           nginx-ingress-kubernetes-worker-controller-b2qn2          0/1     Terminating   0          44m
default                           nginx-ingress-kubernetes-worker-controller-mnhgq          0/1     Terminating   0          42m
ingress-nginx-kubernetes-worker   default-http-backend-kubernetes-worker-5d9bb77bc5-g8lcz   1/1     Running       0          22m
ingress-nginx-kubernetes-worker   nginx-ingress-controller-kubernetes-worker-6gzw8          0/1     Pending       0          22m
ingress-nginx-kubernetes-worker   nginx-ingress-controller-kubernetes-worker-sksm6          0/1     Pending       0          22m
ingress-nginx-kubernetes-worker   nginx-ingress-controller-kubernetes-worker-tmjzv          0/1     Pending       0          22m
kube-system                       heapster-v1.6.0-beta.1-6db4b87d-c5cws                     4/4     Running       0          42m
kube-system                       kube-dns-596fbb8fbd-dr692                                 3/3     Running       0          46m
kube-system                       kubernetes-dashboard-67d4c89764-bgt6k                     1/1     Running       0          46m
kube-system                       metrics-server-v0.3.1-67bb5c8d7-t7lh7                     2/2     Running       0          44m
kube-system                       monitoring-influxdb-grafana-v4-65cc9bb8c8-pfsxn           2/2     Running       0          46m
$ kubectl describe po/nginx-ingress-kubernetes-worker-controller-9rp7h
Name:                      nginx-ingress-kubernetes-worker-controller-9rp7h
Namespace:                 default
Node:                      juju-fdbd8c-7/252.0.112.1
Start Time:                Fri, 19 Oct 2018 17:16:17 -0400
Labels:                    controller-revision-hash=5dc6fb876
                           name=nginx-ingress-kubernetes-worker
                           pod-template-generation=1
Annotations:               <none>
Status:                    Terminating (lasts <invalid>)
Termination Grace Period:  60s
IP:                        252.0.112.1
Controlled By:             DaemonSet/nginx-ingress-kubernetes-worker-controller
Containers:
  nginx-ingress-kubernetes-worker:
    Container ID:  docker://42a947b16172b00f53a8655e03e4d979ef810c851ddc146e8855583632330ea3
    Image:         quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.16.1
    Image ID:      docker-pullable://quay.io/kubernetes-ingress-controller/nginx-ingress-controller@sha256:2fa84bfa338fbc84672521c443074f0b2ab30ad0b6bea50c4c29ee2d012fbcba
    Ports:         80/TCP, 443/TCP
    Host Ports:    80/TCP, 443/TCP
    Args:
      /nginx-ingress-controller
      --default-backend-service=$(POD_NAMESPACE)/default-http-backend
      --configmap=$(POD_NAMESPACE)/nginx-load-balancer-conf
      --enable-ssl-chain-completion=False
    State:          Terminated
      Exit Code:    0
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:10254/healthz delay=30s timeout=5s period=10s #success=1 #failure=3
    Environment:
      POD_NAME:       nginx-ingress-kubernetes-worker-controller-9rp7h (v1:metadata.name)
      POD_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from nginx-ingress-kubernetes-worker-serviceaccount-token-w7kcw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  nginx-ingress-kubernetes-worker-serviceaccount-token-w7kcw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  nginx-ingress-kubernetes-worker-serviceaccount-token-w7kcw
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  juju-application=kubernetes-worker
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason       Age                From                    Message
  ----     ------       ----               ----                    -------
  Normal   Scheduled    45m                default-scheduler       Successfully assigned default/nginx-ingress-kubernetes-worker-controller-9rp7h to juju-fdbd8c-7
  Normal   Pulling      45m                kubelet, juju-fdbd8c-7  pulling image "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.16.1"
  Normal   Pulled       45m                kubelet, juju-fdbd8c-7  Successfully pulled image "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.16.1"
  Normal   Created      45m                kubelet, juju-fdbd8c-7  Created container
  Normal   Started      45m                kubelet, juju-fdbd8c-7  Started container
  Warning  FailedMount  44m (x4 over 45m)  kubelet, juju-fdbd8c-7  MountVolume.SetUp failed for volume "nginx-ingress-kubernetes-worker-serviceaccount-token-w7kcw" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount  22m (x4 over 22m)  kubelet, juju-fdbd8c-7  MountVolume.SetUp failed for volume "nginx-ingress-kubernetes-worker-serviceaccount-token-w7kcw" : secret "nginx-ingress-kubernetes-worker-serviceaccount-token-w7kcw" not found
  Normal   Killing      22m                kubelet, juju-fdbd8c-7  Killing container with id docker://nginx-ingress-kubernetes-worker:Need to kill Pod
```
Waited a few hours and then
```
$ kubectl get po
NAME                                               READY   STATUS        RESTARTS   AGE
microbot-66cb4987b7-h4wkd                          1/1     Running       0          4h3m
microbot-66cb4987b7-sn6dm                          1/1     Running       0          4h3m
microbot-66cb4987b7-tgrmc                          1/1     Running       0          4h3m
nginx-ingress-kubernetes-worker-controller-9rp7h   0/1     Terminating   0          4h40m
nginx-ingress-kubernetes-worker-controller-b2qn2   0/1     Terminating   0          4h39m
nginx-ingress-kubernetes-worker-controller-mnhgq   0/1     Terminating   0          4h37m
...
$ kubectl describe po/nginx-ingress-kubernetes-worker-controller-9rp7h
Name:                      nginx-ingress-kubernetes-worker-controller-9rp7h
Namespace:                 default
Node:                      juju-fdbd8c-7/252.0.112.1
Start Time:                Fri, 19 Oct 2018 17:16:17 -0400
Labels:                    controller-revision-hash=5dc6fb876
                           name=nginx-ingress-kubernetes-worker
                           pod-template-generation=1
Annotations:               <none>
Status:                    Terminating (lasts <invalid>)
Termination Grace Period:  60s
IP:                        252.0.112.1
Controlled By:             DaemonSet/nginx-ingress-kubernetes-worker-controller
Containers:
  nginx-ingress-kubernetes-worker:
    Container ID:  docker://42a947b16172b00f53a8655e03e4d979ef810c851ddc146e8855583632330ea3
    Image:         quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.16.1
    Image ID:      docker-pullable://quay.io/kubernetes-ingress-controller/nginx-ingress-controller@sha256:2fa84bfa338fbc84672521c443074f0b2ab30ad0b6bea50c4c29ee2d012fbcba
    Ports:         80/TCP, 443/TCP
    Host Ports:    80/TCP, 443/TCP
    Args:
      /nginx-ingress-controller
      --default-backend-service=$(POD_NAMESPACE)/default-http-backend
      --configmap=$(POD_NAMESPACE)/nginx-load-balancer-conf
      --enable-ssl-chain-completion=False
    State:          Terminated
      Exit Code:    0
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:10254/healthz delay=30s timeout=5s period=10s #success=1 #failure=3
    Environment:
      POD_NAME:       nginx-ingress-kubernetes-worker-controller-9rp7h (v1:metadata.name)
      POD_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from nginx-ingress-kubernetes-worker-serviceaccount-token-w7kcw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  nginx-ingress-kubernetes-worker-serviceaccount-token-w7kcw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  nginx-ingress-kubernetes-worker-serviceaccount-token-w7kcw
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  juju-application=kubernetes-worker
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:          <none>
```

**Comment by hyperbolic2346** [comment]
I'm not sure what sig to label on this issue. The sig list is a helpful link, but it doesn't give any information about who would be responsible for what. Further, I'm not even sure where the problem lies so if there were good descriptions of the types of bugs each sig took, I wouldn't be able to classify it. Might I suggest the bot give some more information and add "if unsure, reply with /sig firefighters" or something?

**Comment by hyperbolic2346** [comment]
Thanks for the help, @fntlnz!

**Comment by fntlnz** [comment]
This is happening in CI too.
See: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/66211/pull-kubernetes-local-e2e-containerized/3108/

```
Oct 20 12:49:07.861: INFO: At 2018-10-20 12:44:00 +0000 UTC - event for wrapped-volume-race-d08a4a59-d465-11e8-9b52-0a580a3c8fc3-777md: {kubelet 172.17.0.1} FailedMount: MountVolume.SetUp failed for volume "racey-configmap-0" : couldn't propagate object cache: timed out waiting for the condition
Oct 20 12:49:07.861: INFO: At 2018-10-20 12:44:00 +0000 UTC - event for wrapped-volume-race-d08a4a59-d465-11e8-9b52-0a580a3c8fc3-777md: {kubelet 172.17.0.1} FailedMount: MountVolume.SetUp failed for volume "racey-configmap-38" : couldn't propagate object cache: timed out waiting for the condition
Oct 20 12:49:07.861: INFO: At 2018-10-20 12:44:00 +0000 UTC - event for wrapped-volume-race-d08a4a59-d465-11e8-9b52-0a580a3c8fc3-777md: {kubelet 172.17.0.1} FailedMount: MountVolume.SetUp failed for volume "racey-configmap-11" : couldn't propagate object cache: timed out waiting for the condition
Oct 20 12:49:07.861: INFO: At 2018-10-20 12:44:00 +0000 UTC - event for wrapped-volume-race-d08a4a59-d465-11e8-9b52-0a580a3c8fc3-777md: {kubelet 172.17.0.1} FailedMount: MountVolume.SetUp failed for volume "racey-configmap-47" : couldn't propagate object cache: timed out waiting for the condition
Oct 20 12:49:07.861: INFO: At 2018-10-20 12:44:00 +0000 UTC - event for wrapped-volume-race-d08a4a59-d465-11e8-9b52-0a580a3c8fc3-7rh7s: {kubelet 172.17.0.1} FailedMount: MountVolume.SetUp failed for volume "racey-configmap-4" : couldn't propagate object cache: timed out waiting for the condition
Oct 20 12:49:07.861: INFO: At 2018-10-20 12:44:00 +0000 UTC - event for wrapped-volume-race-d08a4a59-d465-11e8-9b52-0a580a3c8fc3-7rh7s: {kubelet 172.17.0.1} FailedMount: MountVolume.SetUp failed for volume "racey-configmap-46" : couldn't propagate object cache: timed out waiting for the condition
Oct 20 12:49:07.861: INFO: At 2018-10-20 12:44:00 +0000 UTC - event for wrapped-volume-race-d08a4a59-d465-11e8-9b52-0a580a3c8fc3-7rh7s: {kubelet 172.17.0.1} FailedMount: MountVolume.SetUp failed for volume "racey-configmap-37" : couldn't propagate object cache: timed out waiting for the condition
Oct 20 12:49:07.861: INFO: At 2018-10-20 12:44:00 +0000 UTC - event for wrapped-volume-race-d08a4a59-d465-11e8-9b52-0a580a3c8fc3-7rh7s: {kubelet 172.17.0.1} FailedMount: MountVolume.SetUp failed for volume "racey-configmap-11" : couldn't propagate object cache: timed out waiting for the condition
```

**Comment by fntlnz** [comment]
I'm investigating to fix this, the error is being reported here: https://github.com/kubernetes/kubernetes/blob/a6e273214b99d25a3261b3c59573055e4cda7c4d/pkg/kubelet/util/manager/watch_based_manager.go#L169

**Comment by ijumps** [comment]
/remove-lifecycle rotten

> couldn't propagate object cache: timed out waiting for the condition

I noticed this can happen when apiserver is on high load, but should retry and mount volume successful.

> Pods stuck terminating

In my case, pod stuck terminating because wrong status reported by docker daemon. kubelet try to stop then kill and delete container, but docker report the container is live even with stop or kill. kubelet only call `docker rm container_id`, but in this situation, container can only be deleted by `docker rm -f container_id` (and yes this is a docker bug)

```
[root@node-192-168-134-14 ~]$ docker ps | grep 9cbf95577c3d
9cbf95577c3d        test.caicloudprivatetest.com/release/alert-notifier@sha256:ab92f98591e1e389e428ed27390482785e4ea9b8fec3cadd2de623e69aa4116d                                            "./notifier -confi..."   17 hours ago        Up 17 hours                             k8s_c0_alerting-notifier-notifier-v1-0-b95989757-fg9lr_default_45dd72af-3e42-11e9-a0d4-525400183fcd_118
[root@node-192-168-134-14 ~]$ docker inspect 9cbf95577c3d | grep -i pid
            "Pid": 802661,
            "PidMode": "",
            "PidsLimit": 0,
[root@node-192-168-134-14 ~]$ ps aux | grep 802661
root     1478718  0.0  0.0   9088   672 pts/0    S+   20:06   0:00 grep --color=auto 802661

[root@node-192-168-134-14 ~]$ docker stop 9cbf95577c3d
9cbf95577c3d
[root@node-192-168-134-14 ~]$ docker ps | grep 9cbf95577c3d
9cbf95577c3d        test.caicloudprivatetest.com/release/alert-notifier@sha256:ab92f98591e1e389e428ed27390482785e4ea9b8fec3cadd2de623e69aa4116d                                            "./notifier -confi..."   17 hours ago        Up 17 hours                             k8s_c0_alerting-notifier-notifier-v1-0-b95989757-fg9lr_default_45dd72af-3e42-11e9-a0d4-525400183fcd_118

```

kubelet logs on this node should always helpful for explaining why pod stuck terminating in my experience

**Comment by ZhiqinYang** [comment]
i got this

**Comment by wenma** [comment]
I also faced this problem, then I restart the docker daemon, and it reocverd.
error log:
```
Apr 15 18:40:29 127.0.0.1 kubelet[21367]: E0415 18:40:29.470694   21367 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/configmap/ae9a95a8-4c4c-11e9-84f6-48df372143e4-config-log-volume\" (\"ae9a95a8-4c4c-11e9-84f6-48df372143e4\")" failed. No retries permitted until 2019-04-15 18:40:33.470675668 +0800 CST m=+14.172206337 (durationBeforeRetry 4s). Error: "MountVolume.SetUp failed for volume \"config-log-volume\" (UniqueName: \"kubernetes.io/configmap/ae9a95a8-4c4c-11e9-84f6-48df372143e4-config-log-volume\") pod \"xxxx-211-b897f9989\" (UID: \"ae9a95a8-4c4c-11e9-84f6-48df372143e4\") : couldn't propagate object cache: timed out waiting for the condition"
```
then reocverd with:
```
systemctl  restart docker
```

**Comment by zaneclaes** [comment]
I'm also getting this issue, and nothing is fixing it. I've tried:
- Rebooting
- Restarting the docker daemon
- Deleting and re-applying all Kubernetes resources
I'm running `microk8s` on `Ubuntu 18.04` with all packages up-to-date.

**Comment by qqzeng** [comment]
> I'm also getting this issue, and nothing is fixing it. Everything was working fine until the last week or so, and I've made no changes to any of my configs. Literally the only thing I've done on the affected machine is `apt-get update` for the latest packages on `Ubuntu 18.04`.
> 
> I've tried:
> 
>     * Rebooting
> 
>     * Restarting the docker daemon
> 
>     * Deleting and re-applying all Kubernetes resources

the same situation with me.

**Comment by bluven** [comment]
Same problem:
```
Name:               rfs-redisfailover-88d84bcbb-vr2x7
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               bluven-k8s-2.novalocal/10.20.9.3
Start Time:         Thu, 18 Jul 2019 10:24:07 +0800
Labels:             app.kubernetes.io/component=sentinel
                    app.kubernetes.io/managed-by=redis-operator
                    app.kubernetes.io/name=redisfailover
                    app.kubernetes.io/part-of=redis-failover
                    mono_rev=test
                    pod-template-hash=88d84bcbb
                    redisfailovers.databases.spotahome.com/name=redisfailover
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      ReplicaSet/rfs-redisfailover-88d84bcbb
Init Containers:
  sentinel-config-copy:
    Container ID:  
    Image:         redis:5.0-alpine
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
      /redis/sentinel.conf
      /redis-writable/sentinel.conf
    State:          Waiting
      Reason:       RunContainerError
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused \"read init-p: connection reset by peer\"": unknown
      Exit Code:    128
      Started:      Thu, 18 Jul 2019 10:25:25 +0800
      Finished:     Thu, 18 Jul 2019 10:25:25 +0800
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /redis from sentinel-config (rw)
      /redis-writable from sentinel-config-writable (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-dndgt (ro)
Containers:
  sentinel:
    Container ID:  
    Image:         redis:5.0-alpine
    Image ID:      
    Port:          26379/TCP
    Host Port:     0/TCP
    Command:
      redis-server
      /redis/sentinel.conf
      --sentinel
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     10m
      memory:  20Mi
    Requests:
      cpu:        10m
      memory:     20Mi
    Liveness:     exec [sh -c redis-cli -h $(hostname) -p 26379 ping] delay=30s timeout=5s period=10s #success=1 #failure=3
    Readiness:    exec [sh -c redis-cli -h $(hostname) -p 26379 ping] delay=30s timeout=5s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /redis from sentinel-config-writable (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-dndgt (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  sentinel-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rfs-redisfailover
    Optional:  false
  sentinel-config-writable:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  default-token-dndgt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-dndgt
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age               From                             Message
  ----     ------                  ----              ----                             -------
  Normal   Scheduled               2m                default-scheduler                Successfully assigned default/rfs-redisfailover-88d84bcbb-vr2x7 to bluven-k8s-2.novalocal
  Warning  FailedMount             2m                kubelet, bluven-k8s-2.novalocal  MountVolume.SetUp failed for volume "sentinel-config" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount             2m                kubelet, bluven-k8s-2.novalocal  MountVolume.SetUp failed for volume "default-token-dndgt" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedCreatePodSandBox  2m (x2 over 2m)   kubelet, bluven-k8s-2.novalocal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "rfs-redisfailover-88d84bcbb-vr2x7": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused \"EOF\"": unknown
  Warning  FailedCreatePodSandBox  1m                kubelet, bluven-k8s-2.novalocal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "rfs-redisfailover-88d84bcbb-vr2x7": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:340: sending config to init process caused \"write init-p: broken pipe\"": unknown
  Normal   Pulled                  1m (x2 over 1m)   kubelet, bluven-k8s-2.novalocal  Container image "redis:5.0-alpine" already present on machine
  Normal   Created                 1m (x2 over 1m)   kubelet, bluven-k8s-2.novalocal  Created container
  Warning  Failed                  50s (x2 over 1m)  kubelet, bluven-k8s-2.novalocal  Error: failed to start container "sentinel-config-copy": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused \"read init-p: connection reset by peer\"": unknown
  Warning  FailedCreatePodSandBox  42s               kubelet, bluven-k8s-2.novalocal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "rfs-redisfailover-88d84bcbb-vr2x7": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"read init-p: connection reset by peer\"": unknown
  Normal   SandboxChanged          17s (x9 over 2m)  kubelet, bluven-k8s-2.novalocal  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  2s (x4 over 35s)  kubelet, bluven-k8s-2.novalocal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "rfs-redisfailover-88d84bcbb-vr2x7": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused \"read init-p: connection reset by peer\"": unknown

```

**Comment by umitseremet** [comment]
is there any progress about that?

**Comment by MohammedFadin** [comment]
Any progress on this team?

**Comment by sfxworks** [comment]
![image](https://user-images.githubusercontent.com/5921035/63911848-c4f5e600-c9f9-11e9-8042-56ece2f2ebb4.png)
I am receiving these errors on v1.15.3 with a fresh kubeadm install /w --cloud-provider=openstack.

**Comment by JuergenKindler** [comment]
Have the same problem on minikube version: v1.3.1 (commit: ca60a424ce69a4d79f502650199ca2b52f29e631) on Ubuntu 18, Kubernetes v1.15.2 on Docker 18.09.8

**Comment by srflaxu40** [comment]
Same I am seeing this trying to get "anything" to work on minikube.  I did a fresh delete and start of minikube and still I get the same errors,

```
108s        Warning   FailedScheduling          pod/prime-elasticsearch-es-default-0                                        pod has unbound immediate PersistentVolumeClaims
108s        Warning   FailedScheduling          pod/prime-elasticsearch-es-default-0                                        skip schedule deleting pod: default/prime-elasticsearch-es-default-0
108s        Normal    Scheduled                 pod/prime-elasticsearch-es-default-0                                        Successfully assigned default/prime-elasticsearch-es-default-0 to minikube
107s        Normal    Pulling                   pod/prime-elasticsearch-es-default-0                                        Pulling image "docker.elastic.co/elasticsearch/elasticsearch:7.4.0"
34s         Warning   FailedScheduling          pod/prime-elasticsearch-es-default-0                                        pod has unbound immediate PersistentVolumeClaims
32s         Normal    Scheduled                 pod/prime-elasticsearch-es-default-0                                        Successfully assigned default/prime-elasticsearch-es-default-0 to minikube
8s          Normal    Pulled                    pod/prime-elasticsearch-es-default-0                                        Container image "prime-elasticsearch:latest" already present on machine
5s          Normal    Created                   pod/prime-elasticsearch-es-default-0                                        Created container elastic-internal-init-filesystem
5s          Normal    Started                   pod/prime-elasticsearch-es-default-0                                        Started container elastic-internal-init-filesystem
3s          Warning   BackOff                   pod/prime-elasticsearch-es-default-0                                        Back-off restarting failed container
108s        Normal    SuccessfulCreate          statefulset/prime-elasticsearch-es-default                                  create Claim elasticsearch-data-prime-elasticsearch-es-default-0 Pod prime-elasticsearch-es-default-0 in StatefulSet prime-elasticsearch-es-default success
108s        Normal    SuccessfulCreate          statefulset/prime-elasticsearch-es-default                                  create Pod prime-elasticsearch-es-default-0 in StatefulSet prime-elasticsearch-es-default successful
108s        Normal    NoPods                    poddisruptionbudget/prime-elasticsearch-es-default                          No matching pods found
34s         Normal    NoPods                    poddisruptionbudget/prime-elasticsearch-es-default                          No matching pods found
34s         Normal    SuccessfulCreate          statefulset/prime-elasticsearch-es-default                                  create Claim elasticsearch-data-prime-elasticsearch-es-default-0 Pod prime-elasticsearch-es-default-0 in StatefulSet prime-elasticsearch-es-default success
34s         Normal    SuccessfulCreate          statefulset/prime-elasticsearch-es-default                                  create Pod prime-elasticsearch-es-default-0 in StatefulSet prime-elasticsearch-es-default successful
1s          Warning   Unexpected                elasticsearch/prime-elasticsearch                                           Unsupported distribution
```

```
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  69s (x2 over 69s)  default-scheduler  pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         67s                default-scheduler  Successfully assigned default/prime-elasticsearch-es-default-0 to minikube
  Normal   Pulled            11s (x4 over 63s)  kubelet, minikube  Container image "prime-elasticsearch:latest" already present on machine
  Normal   Created           8s (x4 over 62s)   kubelet, minikube  Created container elastic-internal-init-filesystem
  Normal   Started           8s (x4 over 62s)   kubelet, minikube  Started container elastic-internal-init-filesystem
  Warning  BackOff           7s (x7 over 58s)   kubelet, minikube  Back-off restarting failed container
```

```
knepper@Johns-MacBook-Pro [~/radiant-solutions/datahub/prime-elasticsearch/helm/prime-elasticsearch]kgp
NAME                               READY   STATUS                  RESTARTS   AGE
jenkins-64576f7bf8-wct9k           1/1     Running                 0          10m
prime-elasticsearch-es-default-0   0/1     Init:CrashLoopBackOff   3          84s
```

**Comment by insider89** [comment]
Same for me on AWS ELS 1.15. I've just upgraded from 1.14 and running `sonobuoy run --plugin e2e`, in result got the same errror
`{kubelet ip-10-6-100-106.eu-west-1.compute.internal} FailedMount: MountVolume.SetUp
  failed for volume \"racey-configmap-6\" : couldn't propagate object cache:
  timed out waiting for the condition\nMar 30 17:41:44.553: INFO: At 2020-03-30
  17:35:49 +0000 UTC - event for wrapped-volume-race-5ab9e062-bdaa-4b4c-90fe-c807a0efe90a-r2559:
  {kubelet ip-10-6-100-106.eu-west-1.compute.internal} FailedMount: MountVolume.SetUp
  failed for volume \"racey-configmap-31\" : couldn't propagate object cache:
  timed out waiting for the condition\nMar 30 17:41:44.553: INFO: At 2020-03-30
  17:35:49 +0000 UTC - event for wrapped-volume-race-5ab9e062-bdaa-4b4c-90fe-c807a0efe90a-r2559:
  {kubelet ip-10-6-100-106.eu-west-1.compute.internal} FailedMount: MountVolume.SetUp
  failed for volume \"racey-configmap-45\" : couldn't propagate object cache:
  timed out waiting for the condition\nMar 30 17:41:44.553: INFO: At 2020-03-30
  17:35:49 +0000 UTC - event for wrapped-volume-race-5ab9e062-bdaa-4b4c-90fe-c807a0efe90a-r2559:
  {kubelet ip-10-6-100-106.eu-west-1.compute.internal} FailedMount: (combined
  from similar events): MountVolume.SetUp failed for volume \"racey-configmap-37\"
  : couldn't propagate object cache: timed out waiting for the condition\nMar
  30 17:41:44.553: INFO: At 2020-03-30 17:35:49 +0000 UTC - event for wrapped-volume-race-5ab9e062-bdaa-4b4c-90fe-c807a0efe90a-r2559:
  {kubelet ip-10-6-100-106.eu-west-1.compute.internal} FailedMount: MountVolume.SetUp
  failed for volume \"racey-configmap-4\" : couldn't propagate object cache:
  timed out waiting for the condition\nMar 30 17:41:44.553: INFO: At 2020-03-30
  17:35:49 +0000 UTC - event for wrapped-volume-race-5ab9e062-bdaa-4b4c-90fe-c807a0efe90a-r2559:
  {kubelet ip-10-6-100-106.eu-west-1.compute.internal} FailedMount: MountVolume.SetUp
  failed for volume \"racey-configmap-8\" : couldn't propagate object cache:
  timed out waiting for the condition\nMar 30 17:41:44.553: INFO: At 2020-03-30
  17:35:49 +0000 UTC - event for wrapped-volume-race-5ab9e062-bdaa-4b4c-90fe-c807a0efe90a-r2559:
  {kubelet ip-10-6-100-106.eu-west-1.compute.internal} FailedMount: MountVolume.SetUp
  failed for volume \"racey-configmap-47\" : couldn't propagate object cache:
  timed out waiting for the condition\nMar 30 17:41:44.553: INFO: At 2020-03-30
  17:35:49 +0000 UTC - event for wrapped-volume-race-5ab9e062-bdaa-4b4c-90fe-c807a0efe90a-r2559:
  {kubelet ip-10-6-100-106.eu-west-1.compute.internal} FailedMount: MountVolume.SetUp
  failed for volume \"racey-configmap-46\" : couldn't propagate object cache:`

**Comment by cliffburdick** [comment]
/remove-lifecycle rotten

Saw this randomly when deleting a deployment on 1.16.7. Describe pod reported:

```
  Warning  FailedMount  8m57s (x4 over 9m1s)   kubelet, fi-comp007  MountVolume.SetUp failed for volume "ctos-config-volume" : configmap "ctos-config" not found
  Warning  FailedMount  8m53s (x5 over 9m1s)   kubelet, fi-comp007  MountVolume.SetUp failed for volume "ctos-rap-volume" : configmap "ctos-rap" not found
  Warning  FailedMount  2m49s (x11 over 9m1s)  kubelet, fi-comp007  MountVolume.SetUp failed for volume "store-proxy-config-map" : configmap "ctos-store-proxy-config-map" not found
```

**Comment by ruchikaguptaa** [comment]
Is there any update on this? I'm seeing the same problem. It retries and gets fixed sometimes but it ends up taking longer for the cluster. 

Oct 17 01:04:37 k8s-agent-1-3l38utey3n53p000002 kubelet[23963]: E1017 01:04:37.194802   23963 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/secret/042136cb-99c2-4b6c-aeed-63f4dc93f0f7-kubeconfig\" (\"042136cb-99c2-4b6c-aeed-63f4dc93f0f7\")" failed. No retries permitted until 2020-10-17 01:04:37.694740476 +0000 UTC m=+151083.427973627 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"kubeconfig\" (UniqueName: \"kubernetes.io/secret/042136cb-99c2-4b6c-aeed-63f4dc93f0f7-kubeconfig\") pod \"kube-apiserver-785d4dfcbf-b62mt\" (UID: \"042136cb-99c2-4b6c-aeed-63f4dc93f0f7\") : couldn't propagate object cache: timed out waiting for the condition
Oct 17 01:05:51 k8s-agent-1-3l38utey3n53p000002 kubelet[23963]: , failed to "StartContainer" for "node-labels" with CreateContainerConfigError: "cannot find volume \"kubeconfig\" to mount into container \"node-labels\""

**Comment by xsoheilalizadeh** [comment]
I'm facing this issue, is there any progress on this?

**Comment by h0jeZvgoxFepBQ2C** [comment]
We also have the same problem sometimes... Dunno why :(

**Comment by thernstig** [comment]
Upvote the original issue is a good idea to show you also have this problem.

**Comment by Oats87** [comment]
I've been spending quite a large amount of time attempting to debug/understand why pods can get stuck in a terminating state like this (https://github.com/longhorn/longhorn/issues/2629 for reference, the fundamental issue is the same but has a different cause)

I believe I've identified one path that gets to this state, but it specifically deals with a restarted kubelet due to a mismatch between desired and actual state. It's quite rare that someone would hit this but it's extremely reproducible if manipulated properly.

Essentially, if a pod is created and uses a secret that is deleted after the pod is created/running, then the `kubelet` is restarted, the `kubelet` will emit the `MountVolume.SetUp` error messages as it attempts to reconcile desired state against the contents on disk. 

The reconciler has a `syncStates` function: https://github.com/kubernetes/kubernetes/blob/v1.21.1/pkg/kubelet/volumemanager/reconciler/reconciler.go#L385 that inspects the kubelet directory, and attempts to reconcile the desired/actual state of the world with it. If you look at https://github.com/kubernetes/kubernetes/blob/v1.21.1/pkg/kubelet/volumemanager/reconciler/reconciler.go#L415-L424 you can see that if the volume exists in the desired state of the world (which it should, because the pod is there and is using the volume), then it marks the volume `InUse`, and the `kubelet` will then attempt to `MountVolume.SetUp` the volume again. The issue is, if the secret was deleted, then the `MountVolume.SetUp` will fail and the `Actual State of the World` will never be populated with the secret volume. 

The issue with this is, on termination of a pod, when the `kubelet` is determining what volumes to remove in order to finish terminating the pod, it doesn't attempt to unmount the secret because the secret isn't in the actual state of the world: https://github.com/kubernetes/kubernetes/blob/v1.21.1/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L281-L289

Interestingly, if I `umount` the `tmpfs` mount of the secret that it is complaining about, the `kubelet` will terminate the pod as it considers it "orphaned" i.e.
```
I0603 02:13:36.816846   13556 kubelet_volumes.go:70] "Pod found, but volumes are still mounted on disk" podUID=45446e4b-dd76-4339-96fa-0d6881250103 paths=[/var/lib/kubelet/pods/45446e4b-dd76-4339-96fa-0d6881250103/volumes/kubernetes.io~secret/rke2-ingress-nginx-v3-token-6m4fk]
I0603 02:13:36.816858   13556 kubelet_pods.go:2014] "Orphaned pod found, but volumes not yet removed.  Reducing cpu to minimum" podUID=45446e4b-dd76-4339-96fa-0d6881250103
```

then, `umount /var/lib/kubelet/pods/45446e4b-dd76-4339-96fa-0d6881250103/volumes/kubernetes.io~secret/rke2-ingress-nginx-v3-token-6m4fk` results in:

```
I0603 02:13:38.815434   13556 kubelet_pods.go:2020] "Orphaned pod found, removing pod cgroups" podUID=45446e4b-dd76-4339-96fa-0d6881250103
I0603 02:13:38.817361   13556 noop.go:30] No-op Destroy function called
I0603 02:13:38.817370   13556 manager.go:1044] Destroyed container: "/kubepods/burstable/pod45446e4b-dd76-4339-96fa-0d6881250103" (aliases: [], namespace: "")
I0603 02:13:38.817379   13556 handler.go:325] Added event &{/kubepods/burstable/pod45446e4b-dd76-4339-96fa-0d6881250103 2021-06-03 02:13:38.817374768 +0000 UTC m=+1973.569615324 containerDeletion {<nil>}}
--
I0603 02:13:42.815109   13556 kubelet_volumes.go:170] "Orphaned pod found, removing" podUID=45446e4b-dd76-4339-96fa-0d6881250103
```

and the pod disappears.

**Comment by brandond** [comment]
I think it has to do with pod teardown and BoundServiceAccountTokenVolume. The token controller sees that the pod has the deletion timestamp set, and deletes the bound token secret. The kubelet comes back online and tries to remount everything to properly sequence the pod teardown, but can't because the token has disappeared out from under it.

Ref: https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume

**Comment by joshimoo** [comment]
These issues might have some additional insights when following the trail that might be worth to look at:
https://github.com/kubernetes/kubernetes/issues/101911#issuecomment-842830788
https://github.com/kubernetes/kubernetes/pull/64610#discussion_r193556014
https://github.com/kubernetes/kubernetes/issues/96759

**Comment by ehashman** [comment]
/sig storage

We have some PRs that landed recently that touch similar issues with volume teardown on pod deletion (see e.g. https://github.com/kubernetes/kubernetes/pull/101524 https://github.com/kubernetes/kubernetes/pull/100183) but it's hard to say what the root cause is from the description in the issue.

To debug this, we will need full kubelet logs, and container runtime logs as well if available to try to pinpoint if this is a dockershim-specific issue.

/triage needs-information

**Comment by brandond** [comment]
We're seeing in on containerd, so definitely not limited to dockershim.

**Comment by ssubramanian123** [comment]
@Oats87 I am seeing exactly same issue as you described above. I recently upgraded my cluster to k8s 1.21.2. Is there any fix available for this issue?
@brandond  @ehashman

**Comment by fragaLY** [comment]
Hello, faced the same problem. Could you please tell me where to look the sources related to the direct problem to try to solve it?

**Comment by brandond** [comment]
FYI we are still seeing this on a regular basis. All you need to do to reproduce it is restart the kubelet + containerd while a pod is terminating.

**Comment by rajivml** [comment]
After the recent 1.21.4 upgrade, In the last one week, we have seen this issue of 3 of our environments and as @brandond mentioned, the repro is simple, delete a pod which takes a bit of time to terminate and at the same time restart kubelet + containerd.

We are using kubernetes (RKE2) bundled by rancher and longhorn for storage abstraction and I tried deleting couple of pods which usually takes bit longer as the associated pvc also has to get detached and at the same time, I restarted rke2-server (i.e. kubelet + containerd) and the new pod which spins just get stuck in Init state unable to attach the PVC mount

And the only solution that's working in this scenario is to reboot the machine which is not a good solution as other workloads which are running on that node will also get impacted with this action

**Comment by cjellick** [comment]
@krishnakc1 what distro of k8s are you seeing this with?

**Comment by brandond** [comment]
Here are steps to reproduce. Note that you need a two-node cluster so that the control-plane remains up while the kubelet and containerd restart on the node in order to trigger this bug. All commands should be run as root for simplicity's sake.

1. ```bash
    # on node 1
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-taint=node-role.kubernetes.io/control-plane=:NoSchedule --token=token" bash -
    ```
1. ```bash
    # on node 2
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server=https://node1.domain:6443 --token=token" bash -
    ```
1. ```bash
    # on node 2
    mkdir -p /etc/rancher/k3s
    scp root@node1.domain:/etc/rancher/k3s/k3s.yaml /etc/rancher/k3s/
    sed -i 's/:6443/:6444/' /etc/rancher/k3s/k3s.yaml
    ln -sf k3s /usr/local/bin/kubectl
    export PATH="/usr/local/bin:$PATH"
    ```
1. ```bash
    # on node 2
    export SLEEP=https://gist.githubusercontent.com/brandond/8b81bd9e607bdc18464774a4b1ad20f3/raw/sleep.yaml
    kubectl delete -f $SLEEP --force  # just to clean up from prior runs; can be skipped on initial run
    kubectl apply -f $SLEEP
    sleep 60
    kubectl delete -f $SLEEP --wait=false
    sleep 25
    pkill --full 'k3s agent'
    pkill -9 --full 'sleep 9999'
    ```
1. ```bash
    # on node 2
    kubectl get events -w
    ```
    
### results
```
Events:
  Type     Reason         Age                 From               Message
  ----     ------         ----                ----               -------
  Normal   Scheduled      20m                 default-scheduler  Successfully assigned default/sleep to ubuntu02.lan.khaus
  Normal   Pulled         20m                 kubelet            Container image "bash" already present on machine
  Normal   Created        20m                 kubelet            Created container sleep-a
  Normal   Started        20m                 kubelet            Started container sleep-a
  Normal   Pulled         20m                 kubelet            Container image "bash" already present on machine
  Normal   Created        20m                 kubelet            Created container sleep-b
  Normal   Started        20m                 kubelet            Started container sleep-b
  Normal   Killing        19m                 kubelet            Stopping container sleep-a
  Normal   Killing        19m                 kubelet            Stopping container sleep-b
  Warning  FailedKillPod  18m                 kubelet            error killing pod: [failed to "KillContainer" for "sleep-b" with KillContainerError: "rpc error: code = Unavailable desc = transport is closing", failed to "KillContainer" for "sleep-a" with KillContainerError: "rpc error: code = Unavailable desc = transport is closing", failed to "KillPodSandbox" for "47a31354-b39d-435a-a84d-fc7c92d1c912" with KillPodSandboxError: "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: no such file or directory\""]
  Normal   Killing        18m                 kubelet            Stopping container sleep-b
  Warning  FailedMount    18m (x6 over 18m)   kubelet            MountVolume.SetUp failed for volume "sleep-volume" : secret "sleep" not found
  Warning  FailedMount    18s (x11 over 18m)  kubelet            MountVolume.SetUp failed for volume "sleep-volume" : object "default"/"sleep" not registered
```

cc @cjellick @Oats87 @ibuildthecloud

**Comment by cjellick** [comment]
@brandond you mean this bit from @Oats87 ? This is the simplest repro?

> Essentially, if a pod is created and uses a secret that is deleted after the pod is created/running, then the kubelet is restarted, the kubelet will emit the MountVolume.SetUp error messages as it attempts to reconcile desired state against the contents on disk.

**Comment by brandond** [comment]
Yes, that seems to be a minimal reproduction. There are other ways to get into a state where it is stuck trying to remount things that obviously can't ever succeed but that's the easiest.

**Comment by brandond** [comment]
@ehashman can we unstale this?

**Comment by gnufied** [comment]
I can confirm that this bug is essentially a duplicate of https://github.com/kubernetes/kubernetes/issues/96635 . We can keep this open for now since it has some excellent steps to reproduce etc by @Oats87 and @brandond above. I have posted my findings here - https://github.com/kubernetes/kubernetes/issues/96635#issuecomment-1145286675 and taking a stab at fixing it.

/assign

**Comment by thernstig** [comment]
@gnufied to be fair, https://github.com/kubernetes/kubernetes/issues/96635 is a duplicate of this one. This one existed almost 2 years earlier.

**Comment by gnufied** [comment]
This should be fixed via https://github.com/kubernetes/kubernetes/pull/110670 now. 

/close
