### ISSUE TITLE
Scheduler - Scheduling throughput drop

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#71659]
There is a significant drop in scheduling throughput in ci-kubernetes-e2e-gce-scale-performance test.

![scheduling_throughput](https://user-images.githubusercontent.com/25119199/49374898-0ecbcd00-f703-11e8-8788-e6803220ca9f.png)

It looks like change that cause this issue was introduced between 05/11/2018 (run 249) and 06/11/2018 (run 250)

/kind bug
/sig scheduling

**Comment by wojtek-t** [comment]
I supposed this one may be related: https://github.com/kubernetes/kubernetes/pull/70274
It does a bunch of unnecessary memory allocations...

**Comment by krzysied** [comment]
![allocations](https://user-images.githubusercontent.com/25119199/49443011-7cdbc700-f7cb-11e8-8b67-851d4cd8ed21.png)

It "hacked" perfdash to get some older results of scheduler benchmark:
- Point 1 is version from commit you pointed out. You are right is cause some additional allocations. It looks like it also cause some problem with performance.
- Point 2 is https://github.com/kubernetes/kubernetes/commit/62c3ec969d7a59a69fe7c45039e4379096870891#diff-c237cdd9e4cb201118ca380732d7f361 which is from 10/11/2018 and it looks like it fixed that issue.

I can be wrong, but could this issue be because of changing `for i := range tab` to `for i, object := range tab`? Because `PriorityConfig` is a struct it creates copies of `priorityConfigs` for every node.

**Comment by wojtek-t** [comment]
Yes - that was what I had on my mind.

But you're saying that it was fixed? Then the regression must be something different, right? But there weren't any other changes in the original range in scheduler that look suspicious.

**Comment by krzysied** [comment]
Ok. I see I created misunderstanding, so I will clarify.

IMHO there were two problem:
- Upfront it allocated array of size #nodes for each config.
`results[i] = make(schedulerapi.HostPriorityList, len(nodes))`
This was fix.
Btw, I though that's what you meant by "unnecessary memory allocations".
- Iterating over copies
`for i, priorityConfig := range priorityConfigs`
I'm not sure whether this will create additional allocations. Compilers are quite smart so it will allocated additional memory of one structure size, but copying each table element takes time.
This one is not fixed.

I haven't found any other suspicious lines.

**Comment by bsalamat** [comment]
@wojtek-t as @krzysied mentioned, part of the code is changed, but another part is still the same. https://github.com/kubernetes/kubernetes/pull/70892 is the change submitted later to fix a race introduced in the first PR.
I will send a PR to change the loop and avoid copies. Let's see if it addresses the problem.

**Comment by krzysied** [comment]
@bsalamat Thanks for the PR! I see it is merged now.
 
I guess this will fix the issue. However let's keep this issue open. I will post update on this after few days - the impact will be clearly visible in 5k nodes test which runs once per day.

**Comment by krzysied** [comment]
Btw, I was thinking about current benchmark for scheduler. IIUC it runs [scheduler_bench_test.go](https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler_perf/scheduler_bench_test.go), which has tests for 100, 500 and 1000 nodes. Maybe we should add 5k node tests - for example the one you used to measure PR impact `BenchmarkScheduling/5000Nodes/1000Pods-12`?
Assuming that it will consume more time to run the tests I would also suggest to decrease [scheduler benchmark ci job frequency](https://github.com/kubernetes/test-infra/blob/ea22e5d80ed0f6ff4431777a31348ce8ea6f72f0/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L670) from every hour to every two hours.

@bsalamat  @wojtek-t Wdyt?

**Comment by bsalamat** [comment]
@krzysied I like the idea of having a benchmark test for running 5K node clusters. The test does not take much to run on my machine. As you can see in the results it takes about 2 minutes to run when it schedules 10,000 pods after an initial warm-up of scheduling 1,000 pod. So, every two hours sounds very reasonable to me.

**Comment by krzysied** [comment]
@bsalamat I've created PR #71849 with 5k nodes test case.

**Comment by krzysied** [comment]
Update:
![scheduling_throughput_fixed png](https://user-images.githubusercontent.com/25119199/50082138-819f7280-01f0-11e9-962e-29d9e25e8b09.png)
Scheduling throughput is fixed. I'm going to close this issue. Thanks @bsalamat!
