### ISSUE TITLE
Storage protection feature does not integrate well with StatefulSet pod recreation

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#74374]
**What happened**:
The storage protection feature prevents PVC deletion until all Pods referencing it are deleted.  This doesn't work well with Statefulsets when you want to delete the PVC and have the StatefulSet controller recreate it.  The StatefulSet controller only [creates missing PVCs when creating a new Pod](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/controller/statefulset/stateful_pod_control.go#L75).  So you could have a sequence like this:

1. Try to delete PVC. Deletion is pending due to the storage protection finalizer.
2. Delete the Pod.
3. StatefulSet controller notices that the pod is deleted and creates the replacement pod.  But the PVC already exists, so a new one is not created.
4. Storage protection controller removes the finalizer and the PVC is deleted
5. New pod is pending. First because PVC deletion is pending, and then 2nd because PVC is deleted.

Nothing tries to recreate the PVC again and the Pod is stuck in pending forever.

**What you expected to happen**:
We could potentially add logic in the statefulset controller to check if the PVC is terminating [here](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/controller/statefulset/stateful_pod_control.go#L182).  However, it uses an informer so the race may still exist.

Another option is to make the StatefulSet controller actively reconcile PVC creation. This would probably require more substantial changes to the controller.

@kubernetes/sig-storage-bugs 
@kubernetes/sig-apps-bugs

**Comment by msau42** [comment]
A workaround in the meantime is to delete the StatefulSet pod a second time if it's stuck in pending due to missing PVC.

**Comment by cscetbon** [comment]
Hey @msau42 thank you for having opened the issue and the temporary workaround

any news on that bug ?

**Comment by KevinTHU** [comment]
I think this need to be fixed, but not just workaround. a second delete of pod is not a graceful operation.

**Comment by msau42** [comment]
I would be happy to help guide someone to come up with a possible design and implementation for a fix.

/help

**Comment by zhangxiaoyu-zidif** [comment]
when recreate pod, check if the PVC was label with deletion. maybe we could delete the PVC immediately by force  and create a new PVC before Pod creation.

**Comment by mucahitkurt** [comment]
Hey @msau42, 

I would like to work on this issue. As far as I understand StatefulSetController [check the different state of the pods](https://github.com/kubernetes/kubernetes/blob/12ff2fe3f50aa4f2c2c8adbc8d8636820a15830c/pkg/controller/statefulset/stateful_set_control.go#L372) and take some action according to pod states when syncing statefulset.

May be I add the pod `Pending` state here and then check if the pod's pvc exist or not, if not then create the missing pvc.

wdyt?

**Comment by KevinTHU** [comment]
the most hard part is that finding the status of pvc(creating pod process), and the deletion of pvc(pvc-protection finalizer) is in different goroutines. there will be concourrent problem.

**Comment by cwdsuzhou** [comment]
@msau42 @kow3ns I have sent a PR   https://github.com/kubernetes/kubernetes/pull/79164.
I have ran it in my cluster, it works.

**Comment by mucahitkurt** [comment]
> Hey @msau42,
> 
> I would like to work on this issue. As far as I understand StatefulSetController [check the different state of the pods](https://github.com/kubernetes/kubernetes/blob/12ff2fe3f50aa4f2c2c8adbc8d8636820a15830c/pkg/controller/statefulset/stateful_set_control.go#L372) and take some action according to pod states when syncing statefulset.
> 
> May be I add the pod `Pending` state here and then check if the pod's pvc exist or not, if not then create the missing pvc.
> 
> wdyt?

Alternative solution might be like https://github.com/mucahitkurt/kubernetes/tree/fix/enable-statefulset-pvc-recreation-for-pending-pod

**Comment by cscetbon** [comment]
I think you mean https://github.com/mucahitkurt/kubernetes/commit/1ab4b97b8b63228ea25fc541233df15eb0e3d598

**Comment by cscetbon** [comment]
@mucahitkurt if I understand your code well, a Pod would be in `PodPending` state only if it's not the first time it starts, and in that case, you recreate the PVC. What if a Pod is just restarted on the same host ?

**Comment by cscetbon** [comment]
@mucahitkurt if I understand your code well, if a Pod is in `PodPending` state you try to recreate the PVC. What if a Pod is just restarted by k8s on the same host ? would the recreate just fail ? what if the previous PVC is still in terminating (same name in our case) ?

**Comment by cwdsuzhou** [comment]
@mucahitkurt  we may need know if the pod keeps in pending or just pending transitorily. 
1. If it keeps in pending, we need try to recreate the pvc ( there also may be many other reasons lead to pending)
2. If it is pending transitorily, we should do nothing

**Comment by mucahitkurt** [comment]
> @mucahitkurt if I understand your code well, if a Pod is in `PodPending` state you try to recreate the PVC. What if a Pod is just restarted by k8s on the same host ? would the recreate just fail ? what if the previous PVC is still in terminating (same name in our case) ?

@cscetbon  I'll test these scenarios on my local cluster, but `CreatePersistentVolumeClaims` does not directly create the PVC, firstly it checks the pod's pvc is missing or not, if the pvc is not found then it tries to create the pvc. So If a statefulset pod is restarting and there is no missing pvc this solution won't do anything.

If the previous PVC is still terminating, I expect that pvc lister returns this pvc and `CreatePersistentVolumeClaims` won't try to recreate the pvc.

@cwdsuzhou actualy `CreatePersistentVolumeClaims` try to create the PVC if it's missing, if the pod is in pending state and reason is another thing other than missing PVC, this solution's cost will be querying the same pvcs again and again (`spc.pvcLister.PersistentVolumeClaims(claim.Namespace).Get(claim.Name)`). So if a pod in pending state and there is no missing pvc the solution won't do anything that has side effect.

**Comment by msau42** [comment]
I wonder if we actually need to check pod state?  Regardless of pod state, can we just check if any of its pvcs are missing?

**Comment by cscetbon** [comment]
@msau42 what if we check that it exists and it does in deleting state ?

**Comment by mucahitkurt** [comment]
> I wonder if we actually need to check pod state? Regardless of pod state, can we just check if any of its pvcs are missing?
@msau42 ,

Most probably there won't be any side effect checking the missing PVCs with `CreatePersistentVolumeClaims` method regarless of pod state, because as far as I understand this method works in a idempotent way.

Checking pod's PVCs existence at every sync operation can create some performance effect.

I don't know about the different scenarios that we need to check the existence of pod's PVCs at every statefulset sync. Do you have any scenario?

**Comment by janetkuo** [comment]
> We could potentially add logic in the statefulset controller to check if the PVC is terminating. However, it uses an informer so the race may still exist.

An alternative is to get PVC directly from API server instead of cache to avoid the race. The logic would be straightforward and the code change is small. 

We'll only do this when creating a Pod with an existing PVC. Therefore, the chance of hitting this case should be pretty low, and the impact to API server should be small too.

**Comment by mucahitkurt** [comment]
> > We could potentially add logic in the statefulset controller to check if the PVC is terminating. However, it uses an informer so the race may still exist.
> 
> An alternative is to get PVC directly from API server instead of cache to avoid the race. The logic would be straightforward and the code change is small.
> 
> We'll only do this when creating a Pod with an existing PVC. Therefore, the chance of hitting this case would be pretty low, and the impact to API server would be small too.

@janetkuo 
Do you have any concern with [my solution alternative](https://github.com/mucahitkurt/kubernetes/commit/1ab4b97b8b63228ea25fc541233df15eb0e3d598) that has no race condition I think?

**Comment by smileusd** [comment]
> A workaround in the meantime is to delete the StatefulSet pod a second time if it's stuck in pending due to missing PVC.

Ac

> A workaround in the meantime is to delete the StatefulSet pod a second time if it's stuck in pending due to missing PVC.

My concern is that pod could be any status even pod could be "Running". Because after user delete pod, pod recreate and then user delete pvc but user don't know pod has been recreate. So the pvc finalizer will not be removed. It is dangerous for user data if pod evicted, pvc also deleted.

**Comment by smileusd** [comment]
@msau42 The problem is not create pvc or create pod, the problem is when delete pod, the finalizer is not removed. I think finalizer add and remove should finish by kubelet not controller-manager. It will produces gap between pod and pvc. If pod deleted and pvc's protection also need to removed immediatly before pod cleaned by apiserver.

**Comment by karolinepauls** [comment]
```
kubectl get pod -l release=<RELEASE>,app=<APP> -ojsonpath='{range .items[*]}{.metadata.name}{" "}{.status.conditions[*].message}{"\n"}{end}' | grep 'persistentvolumeclaim ".*" not found' | awk '{ print $1 }' | xargs -t --no-run-if-empty kubectl delete pod
```
This in a CronJob.

I'm finding that currently, as a Kubernetes admin, correcting this problem is easier than mitigating it.

**Comment by msau42** [comment]
Sorry I missed the questions earlier.

> My concern is that pod could be any status even pod could be "Running". Because after user delete pod, pod recreate and then user delete pvc

If a PVC has a deletion timestamp, then a new Pod cannot start using it. Does that address your concern?

> I think finalizer add and remove should be finished by kubelet not controller-manager.

The challenge is a PVC can be shared by multiple Pods on multiple nodes.

**Comment by smileusd** [comment]
> If a PVC has a deletion timestamp, then a new Pod cannot start using it. Does that address your concern?
> 
@msau42  Yes, i agree. We need also add checking pvc deletion timestamp logic for pod creation, so this [pr](https://github.com/kubernetes/kubernetes/pull/89643) is worked. But we need also combine with pending pod check and delete it or recreate pvc like this [solution](https://github.com/mucahitkurt/kubernetes/commit/1ab4b97b8b63228ea25fc541233df15eb0e3d598) ? I think it will cover lots of cases.

**Comment by cofyc** [comment]
> We could potentially add logic in the statefulset controller to check if the PVC is terminating here. However, it uses an informer so the race may still exist.

This solution with [the improvement](https://github.com/kubernetes/kubernetes/issues/74374#issuecomment-504610721) suggested by @janetkuo is acceptable for me. 
 
In theory, it's possible the PVC is deleted just before the pod is created, e.g. 

- (statefulset controller) check the PVC is not in terminating state from the apiserver, so try to create the pod
  - if it's in terminating state, the controller will wait until the PVC is gone and recreate it. as for users, they must delete the pod too, otherwise, the PVC cann't be deleted physically
- (async, user) users delete the PVC
- (async case A, PVC protection controller) remove the finalizer and PVC object is gone
- (statefulset controller) create the pod
- (async case B, PVC protection controller) [finds the pod from the apiserver](https://github.com/kubernetes/kubernetes/blob/e19964183377d0ec2052d1f1fa930c4d7575bd50/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L277-L293), the PVC will be stuck at terminating state

1) as for case B, the PVC is not deleted by PVC protection controller before the statefulset controller creates the pod, so the PVC will be stuck at terminating state

I think this state is **correct**. Because the statefulset controller will always create the pod if the pod does not exist. There is no solution. This is by design.

- (user) deletes the pod
- (statefulset controller) always tries to reconcile the pod, so the pod may be created before the user deletes the PVC
- (user) deletes the PVC and the PVC may be stuck at the terminating state

If this case happens, the user must delete the newly created pod again.

2) if the case A happens, we have a problem

But the chance of hitting this issue is pretty low, and users can simply avoid this issue by deleting the PVC first.

IMO, this is a bugfix for the current statefulset design. Under current statefulset design, it's recommended for the users to delete the PVC(s) first. This can avoid the case B too, and don't need to delete the newly created pod again.

> Another option is to make the StatefulSet controller actively reconcile PVC creation. This would probably require more substantial changes to the controller.

Having a reconciliation logic is good. But as for [the scenario described in the issue body](https://github.com/kubernetes/kubernetes/issues/74374#issue-413151492)(PVC is deleted before the pod), this is not necessary.

@msau42 @janetkuo What do you think? If you agree, I can submit a PR for the first solution.

The second solution can be used if we want to avoid the issue which may happen if users delete the pod before the PVC (or maybe it's better to recommend users to always delete the PVC first when they want to discard a member).

**Comment by msau42** [comment]
I believe this PR is trying to fix this issue: https://github.com/kubernetes/kubernetes/pull/93457

**Comment by cofyc** [comment]
@NickrenREN pointed out that PVC can be deleted successfully if the newly created pod is not scheduled.

https://github.com/kubernetes/kubernetes/blob/24ec90d23ceec048c8d5a695b4b1b65ce1942b61/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L295-L309  

If the user deletes the PVC after the statefulset controller checks the PVC's state, the chance of hitting this issue is very high. The delay of scheduling pods is uncertain and the scheduler [will skip the pod if associated PVCs are in the terminating state](https://github.com/kubernetes/kubernetes/blob/a04f1b8d59c8c8dd34ba347391cf970cd8149989/pkg/scheduler/core/generic_scheduler.go#L588-L625).

@NickrenREN and I think the PVC reconciliation is necessary too.

What do you think?

If the PVC reconciliation logic will be added, IMO checking the API server in #93457 is not necessary anymore.  Checking the `DeletionTimestamp` of the PVC in the informer cache is good as it has no cost.

**Comment by cofyc** [comment]
cc @tnozicka

**Comment by ymmt2005** [comment]
#93457 has been merged.  It addresses this issue at least partially.

**Comment by NickrenREN** [comment]
@ymmt2005 Your PR can partially solve the problem, actually, if we delete PVC first and then Pod, PV, i think it is ok.
But if the deletion order is : Pod -> PVC -> PV,  that PR is not enough.
For example:
1. Pod is deleted;
2. Statefulset controller recreate the Pod and PVC now is not deleted, so controller will just create the new Pod;
3. New Pod is not scheduled, and PVC is deleted now;
4. PVC can be deleted, and pod can not be scheduled then.

**Comment by msau42** [comment]
/remove-lifecycle rotten

@cofyc @NickrenREN can you clarify if there is still a race?

**Comment by cofyc** [comment]
> /remove-lifecycle rotten
> 
> @cofyc @NickrenREN can you clarify if there is still a race?

To avoid the broken state completely, PVC reconciliation is still needed.  As illustrated [here](https://github.com/kubernetes/kubernetes/issues/74374#issuecomment-686226682), when users delete the pod before the PVC to ask for the statefulset controller to recreate them. There is a chance that the pod will be recreated but the PVC will not.

- user deletes the Pod
- [the statefulset controller] recreates the pod because the PVC exists
- user deletes the PVC
- [the scheduler] tries to schedule the pod
- [the PVC protection controller] deletes the PVC [because the pod is not scheduled yet](https://github.com/kubernetes/kubernetes/blob/24ec90d23ceec048c8d5a695b4b1b65ce1942b61/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L295-L309) (I guess the chance is high cuz the delay of scheduling pods is uncertain and the scheduler [will skip the pod if associated PVCs are in the terminating state](https://github.com/kubernetes/kubernetes/blob/a04f1b8d59c8c8dd34ba347391cf970cd8149989/pkg/scheduler/core/generic_scheduler.go#L588-L625))
- [the statefulset controller] cannot recover from this broken state

**Comment by santhoshs123** [comment]
Is this issue fixed in k8s version 1.20? I used to hit this issue 100% of the times in 1.19, in 1.20 pod remains in pending until the pvc gets recreated, without any PVC not found events, once the pvc is recreated pod goes to running.

**Comment by jingxu97** [comment]
@cofyc Is this issue completely resolved or still need some fixes after your change?

**Comment by cofyc** [comment]
/remove-lifecycle rotten
not resolved completely, but the impact is minor (I guess).
