### ISSUE TITLE
proxy protocol support in kube-apiserver

### ISSUE THREAD

**Issue by michalschott** [kubernetes/kubernetes#76928]
**What would you like to be added**:
Proxy Protocol support for kube-apiserver

**Why is this needed**:
When inspecting audit logs I've noticed load balancer private address is passed to the API - this makes bit harder to inspect API usage. Currently when enabling audit logs and enabling proxy-protocol on AWS ELB results in:
```
➜  ~ k cluster-info                                                                                                                                                

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: remote error: tls: record overflow
```

I'd like to see real-user-IP address in audit logs.

**Comment by michalschott** [comment]
@kubernetes/sig-api-machinery

**Comment by lavalamp** [comment]
If the LB obscures the source IP, I'm not sure how we could possibly know it? Is there any possible way of fixing this? I'm inclined to close this as "not feasible".

**Comment by mikedanese** [comment]
Proxy protocol seeks to solve this: https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt
It's essentially X-Forwarded-For at L4. It's not an IETF standard (although even if it was...) and usually forwarded attributes are not authenticated.

This would be implemented with a custom listener that:
* does a read-ahead on incoming TCP connections to check for the proxy protocol header
* parses the proxy header
* wraps the conn to mask the true source address as reported by the OS
* and passes the wrapped conn to net/http.Server.

Both GCP and AWS have load balancers that preserve source IP:

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html
https://cloud.google.com/load-balancing/docs/network/

We already respect x-forwarded-for in audit logs, which most L7 reverse proxies past by default nowadays.

Given the availability of alternatives, I am not convinced the benefit is worth increasing the surface area of the kube-apiserver at the lowest layer.

**Comment by ghouscht** [comment]
/remove-lifecycle rotten
This is also a problem on our on-prem clusters, with L4 loadbalancers in front of the apiserver.

**Comment by joonghyunlee** [comment]
Unlike AWS Network Load Balancer, HAProxy can't preserve client IP without proxy-protocol. I also have tried to find a solution to inject "X-Forwarded-For" into HTTPS requests using HAProxy. But it looks impossible.

**Comment by adammw** [comment]
> We already respect x-forwarded-for in audit logs, which most L7 reverse proxies past by default nowadays.

> Given the availability of alternatives, I am not convinced the benefit is worth increasing the surface area of the kube-apiserver at the lowest layer.

I'm not sure `x-forward-for` is a solid alternative considering anything that does L7 proxying breaks mTLS, which can be used for client authentication. Having a L4 solution means that the TLS traffic is not tampered with and can continue to function correctly while still maintaining source IP information in audit logs.

**Comment by oz123** [comment]
I believe this is also a problem for openstack users who use Octavia loadbalancers in front of the kube-api-server.
The linked PR does specify this too.

**Comment by christoph-buente** [comment]
/remove-lifecycle rotten
I think this problem has not been addressed appropriately. I like the fact that i can see which users did what API call on the API endpoints. But it is a fairly important information what the callers IP address was. It is not really helpful to find either `127.0.0.1` or the private IP of the load balancer like `10.200.x.x` in the logs. We're using an AWS classic loadbalancer in front of the 3 masters. the `x-forwarded-for` header is being populated by the load balancer. What is the best way to get this header show up in the logs?

**Comment by igcherkaev** [comment]
It's 2021 and Kubernetes has no support for proxy protocol? It's a standard feature with so many load balancers now, kube apiserver should definitely support it. 

https://pkg.go.dev/github.com/pires/go-proxyproto - there seems to be many libraries that implement it.

**Comment by fnkr** [comment]
> It's a standard feature in so many load balancers now

Agreed. I can't think of any load balancer that doesn't support it. HAProxy, nginx, traefik, Caddy, Istio, Envoy, OpenStack (Octavia) as well as any other popular open source load balancer / reverse proxy / web server - even database servers such as MariaDB and of course any major cloud platform supports it. Hardware solutions such as BIG-IP support it too. It's THE (only) standard for forwarding client info to the backend when doing TCP proxying.

**Comment by oz123** [comment]
This is PR is practically ready, all it needs is a loving review.
@kubernetes/sig-api-machinery ?

**Comment by tallclair** [comment]
From an audit API perspective, I'm not happy with the current approach of appending different IP sources together (https://github.com/kubernetes/kubernetes/pull/93438). If we implement this, I'd like to see the current `SourceIPs` field marked as  deprecated, and replaced with labeled data (probably a map), something like:
```json
{
  "x-forwarded-for": ["192.0.2.1", "192.0.2.2"],
  "x-real-id": ["192.0.2.2"],
  "proxy-protocol": ["192.0.2.3"],
  "remote-addr": ["192.0.2.4"]
}
```

**Comment by tallclair** [comment]
/reopen

If anyone wants to drive this forward, it will need a KEP.

**Comment by tallclair** [comment]
From https://www.haproxy.org/download/1.9/doc/proxy-protocol.txt:

> The receiver MUST be configured to only receive the protocol described in this
specification and MUST not try to guess whether the protocol header is present
or not. This means that the protocol explicitly prevents port sharing between
public and private access. Otherwise it would open a major security breach by
allowing untrusted parties to spoof their connection addresses. The receiver
SHOULD ensure proper access filtering so that only trusted proxies are allowed
to use this protocol.

So I think this would prevent Mike's suggestion in https://github.com/kubernetes/kubernetes/issues/76928#issuecomment-573278361 to "read-ahead on incoming TCP connections to check for the proxy protocol header". We could _maybe_ disregard this if we surface the proxy-protocol IP address independently (per https://github.com/kubernetes/kubernetes/issues/76928#issuecomment-1039361541), but explicitly listening on a separate port seems preferable.

(Credit to @dberkov for pointing this out)

**Comment by cici37** [comment]
/help wanted
Like mentioned above, the effort would need a review from sig-auth as well and a proper KEP would be needed. 

/triage accepted

**Comment by liggitt** [comment]
I don't really think this should remain an accepted open issue and keep going stale and getting retriaged / reaccepted.

I don't think there is any intent to add or expand this at this time.

@jpbetz @deads2k should this be closed?

**Comment by cici37** [comment]
/remove-triage accepted

I am in SIG apimachinery bug triage meeting. Remove the triage accepted label as of now. Will see if the issue should be closed or not in the next meeting. Thank you for the input!

**Comment by aojea** [comment]
I'm -1 on adding this complexity to the apiserver, this is part of the network infrastructure and will make network infrastructure problems apiserver problems

**Comment by jtherin** [comment]
In term of complexity, this is nothing. Just adding a flag and 

```if s.ProxyProtocol {
	s.Listener = &proxyproto.Listener{Listener: s.Listener}
}```

into serving.go :/

**Comment by kmala** [comment]
If using EKS this shouldn't be a problem and audit will have the correct client IP.

**Comment by dims** [comment]
as @kmala said we can close this out. If anyone else ends up here that uses EKS and sees this problem, please do not ask to reopen this issue, open a ticket with EKS support.

**Comment by jtherin** [comment]
There is not only EKS on the life...

**Comment by rmb938** [comment]
Thanks @jtherin was just about to post that, had it all typed out as well haha. 

There ton's of other K8s distro's including vanilla kubernetes that could benefit from this support. Just because it's not a problem in EKS doesn't mean it's not a problem other places...

**Comment by dims** [comment]
@jtherin @rmb938 original issue was about `AWS ELB`, you see the responses from @liggitt and @aojea about general update to apiserver. So given their pushback, what remains here was about AWS/EKS/ELB which i addressed and closed.

please follow up with sig-api-machinery that owns kube-apiserver as you see fit:
https://github.com/kubernetes/community/blob/master/sig-api-machinery/README.md

**Comment by jtherin** [comment]
AWS ELB was an example, but this apply to all loadbalancers of cloud providers, I don't think you want one issue per provider, this issue still valid.

**Comment by rmb938** [comment]
Using AWS ELB does not mean someone is using EKS though, I don't think generalizing it to EKS makes sense here. 

I would at least want wait until the next SIG apimachinery meeting like @cici37 mentioned instead of deciding that EKS has it so then AWS ELB support is also solved.

**Comment by aojea** [comment]
> if s.ProxyProtocol {
> 	s.Listener = &proxyproto.Listener{Listener: s.Listener}
> }

until it fails and you need to debug something that reads on the socket buffer before the listener to interpret some added network header bits ...
