### ISSUE TITLE
AWS not updating security group for loadBalancerSourceRanges

### ISSUE THREAD

**Issue by shankar-bala** [kubernetes/kubernetes#77557]
Updating "loadBalancerSourceRanges" in the kubernetes service definition doesnt update the AWS security group

AWS security group must be in sync when we update the service definitions.

Create service.yaml file
kind: Service
apiVersion: v1
metadata:
  name: proxy-service-external
    namespace: test
  labels:
    app: test
    component: proxy
spec:
  selector:
    app: test
    component: proxy
  ports:
  - port: 9200
    targetPort: 9200
  type: LoadBalancer
  loadBalancerSourceRanges:
  - a.b.c.d/32

Apply the service.yaml - kubectl apply -f service.yaml (Able to see a.b.c.d/32 in the ELB security groups)

Update the file and add another IP as below
  loadBalancerSourceRanges:
  - a.b.c.d/32
 - e.f.g.h/32
Applying this file again doesnt update the security group.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): CoreOS

**Comment by shankar-bala** [comment]
@kubernetes/sig-aws-misc

**Comment by Martynas-P** [comment]
I would like to work on this, if there are no objections from anyone.

**Comment by twalla** [comment]
Can confirm similar behavior on 1.12.7, AWS with kops debian image. Creating the loadbalancer initially modifies the security groups but any changes to loadBalancerSourceRanges after the service has been created isn't reflected in the security groups.

**Comment by schahal** [comment]
Same issue (editing Service to add extra load balancer source ranges don't update the node's SG) in the following environment as well:
k8s version: v1.13.8
cloudprovider: AWS
provisioner: EKS

**Comment by sysC0D** [comment]
Same issue, NLB doesn't update security groups.
K8s version: v1.13.10
CloudProvider: AWS
Provisioner: EKS

**Comment by clalbus** [comment]
Workaround, that doesn't involve deleting existing NLB.

`spec.loadBalancerSourceRanges` updates Security Group Inbound Rules on Worker Nodes. Locate entries created by NLB Service (with comments `kubernetes.io/rule/nlb/client=<your_nlb_name>`).

**MAKE BACKUPS** of said entries and delete them. So that you can restore them in case step below fails. I didn't delete `kubernetes.io/rule/nlb/health` or `kubernetes.io/rule/nlb/mtu` rules, just `kubernetes.io/rule/nlb/client` ones.

Update your NLB Service and confirm that new entries appear in Security Group of Worker Nodes.

This approach worked for me. Hope it saves someone from having to delete NLB.

**Comment by kireledan** [comment]
I'm interested in taking a shot at this bug fix. I'll look into this today.

**Comment by kireledan** [comment]
I was able to replicate this in 1.13.13.
I was not able to replicate it in the latest version. 

K8s version:  v1.13.13-beta.0-dirty
controllermanager.go:115] Version: v1.13.13-beta.0-dirty

I started off with the 1.2.3.4 rule and added the 4.3.2.1 rule. That failed. When I deleted and re-created with both these rules. It worked. 
```
W1217 08:57:17.450448   22508 aws.go:2854] Error authorizing security group ingress "InvalidPermission.Duplicate: the specified rule \"peer: 1.2.3.4/32, TCP, from port: 32715, to port: 32715, ALLOW\" already exists\n\tstatus code: 400, request id: 721e1644-2940-46b7-afd6-6c3fff1571c1"
W1217 08:57:17.450509   22508 aws.go:3407] Error opening ingress rules for the load balancer to the instances: "error authorizing security group ingress: \"InvalidPermission.Duplicate: the specified rule \\\"peer: 1.2.3.4/32, TCP, from port: 32715, to port: 32715, ALLOW\\\" already exists\\n\\tstatus code: 400, request id: 721e1644-2940-46b7-afd6-6c3fff1571c1\""
E1217 08:57:17.450550   22508 service_controller.go:219] error processing service default/argocd-server (will retry): failed to ensure load balancer for service default/argocd-server: error authorizing security group ingress: "InvalidPermission.Duplicate: the specified rule \"peer: 1.2.3.4/32, TCP, from port: 32715, to port: 32715, ALLOW\" already exists\n\tstatus code: 400, request id: 721e1644-2940-46b7-afd6-6c3fff1571c1"
I1217 08:57:17.450778   22508 event.go:221] Event(v1.ObjectReference{Kind:"Service", Namespace:"default", Name:"argocd-server", UID:"f052f0f5-20aa-11ea-8e17-02e91a091ec0", APIVersion:"v1", ResourceVersion:"406", FieldPath:""}): type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): failed to ensure load balancer for service default/argocd-server: error authorizing security group ingress: "InvalidPermission.Duplicate: the specified rule \"peer: 1.2.3.4/32, TCP, from port: 32715, to port: 32715, ALLOW\" already exists\n\tstatus code: 400, request id: 721e1644-2940-46b7-afd6-6c3fff1571c1"
```

**Comment by arangamani** [comment]
@kireledan What version weren't you able to replicate it in?

**Comment by kireledan** [comment]
@arangamani 
I wasnt able to replicate this in the following version branches either. 

` Version: v1.17`
` Version: v1.16`
` Version: v1.15`
` Version: v.1.14`

**Comment by bhagwat070919** [comment]
Yes,  I also verified it with EKS cluster with 1.14.

And I don't see any issues in updating.

```
bash-5.0$ kubectl get services -n argocd
NAME            TYPE           CLUSTER-IP    EXTERNAL-IP                                                                     PORT(S)                      AGE
argocd-server   LoadBalancer   10.100.53.3   xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.elb.us-west-2.amazonaws.com   80:30664/TCP,443:30826/TCP   3m58s
bash-5.0$ kubectl describe service argocd-server -n argocd
Name:                        argocd-server
Namespace:                   argocd
Labels:                      app.kubernetes.io/component=server
                             app.kubernetes.io/name=argocd-server
                             app.kubernetes.io/part-of=argocd
Annotations:                 external-dns.alpha.kubernetes.io/hostname: argocd.example.com
                             kubectl.kubernetes.io/last-applied-configuration:
                               {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"external-dns.alpha.kubernetes.io/hostname":"argocd.example.com","service.b...
                             service.beta.kubernetes.io/aws-load-balancer-type: nlb
Selector:                    app.kubernetes.io/name=argocd-server
Type:                        LoadBalancer
IP:                          10.100.53.3
LoadBalancer Ingress:        xxxxxxxxxxxxxxxxxxxxxxxx.elb.us-west-2.amazonaws.com
Port:                        http  80/TCP
TargetPort:                  8080/TCP
NodePort:                    http  30664/TCP
Endpoints:                   <none>
Port:                        https  443/TCP
TargetPort:                  8080/TCP
NodePort:                    https  30826/TCP
Endpoints:                   <none>
Session Affinity:            None
External Traffic Policy:     Cluster
LoadBalancer Source Ranges:  1.2.3.4/32,4.3.2.1/32
Events:
  Type     Reason                      Age                  From                Message
  ----     ------                      ----                 ----                -------
  Warning  CreatingLoadBalancerFailed  4m5s                 service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service argocd/argocd-server: Error creating listener: "Error registering targets for load balancer: \"TargetGroupNotFound: Target groups 'arn:aws:elasticloadbalancing:us-west-2:Account_ID:targetgroup/k8s-tg-UUID/SomeUUID' not found\\n\\tstatus code: 400, request id: e0f7d9d4-ca6c-491c-826f-510b3f6c320c\""
  Warning  CreatingLoadBalancerFailed  3m59s                service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service argocd/argocd-server: Error adding tags after modifying load balancer targets: "ValidationError: Only one resource can be tagged at a time\n\tstatus code: 400, request id: f654506d-fa9f-4f90-90e2-54a48b241ef0"
  Normal   EnsuringLoadBalancer        30s (x4 over 4m6s)   service-controller  Ensuring load balancer
  Normal   EnsuredLoadBalancer         30s (x2 over 3m48s)  service-controller  Ensured load balancer
  Normal   LoadBalancerSourceRanges    30s                  service-controller  [1.2.3.4/32] -> [1.2.3.4/32 4.3.2.1/32]
bash-5.0$ 

```

So if we see the last statement if successfully updated: 
```
  Normal   LoadBalancerSourceRanges    30s                  service-controller  [1.2.3.4/32] -> [1.2.3.4/32 4.3.2.1/32]
bash-5.0$ 

```

**Comment by bhagwat070919** [comment]
I believe we should close this issue if we don't see this happen.

**Comment by karan-wahie03** [comment]
I am facing the same issue with eks version 1.14, though when I describe the service it says the loadbalancer is ensured but the same is not reflected on the node security groups.

`Events:
  Type    Reason                    Age                From                Message
  ----    ------                    ----               ----                -------
  Normal  EnsuringLoadBalancer      11m (x2 over 46h)  service-controller  Ensuring load balancer
  Normal  LoadBalancerSourceRanges  11m                service-controller  [1.2.3.4/32 5.6.7.8/32 9.10.11.12/24] -> [1.2.3.4/28 5.6.7.8/28 9.10.11.12/24 13.14.15.16/28 17.18.19.20/27]
  Normal  EnsuredLoadBalancer       11m (x2 over 46h)  service-controller  Ensured load balancer`

**Comment by bhagwat070919** [comment]
@karan-wahie03 ,

Could you share your yaml ?

I can try with eks 1.14.

**Comment by karan-wahie03** [comment]
@bhagwat070919 Thanks for the prompt reply.

I was deploying my application using helm charts and I updated the IP source ranges in the resource file and used helm upgrade --install command, the ips in service object were updated but security groups were not updated. I am attaching the yaml for your reference.

TIA

`apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  creationTimestamp: "2020-02-24T12:17:33Z"
  labels:
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-ingress-nginx-ingress
    helm.sh/chart: nginx-ingress-0.4.2
  name: nginx-ingress-nginx-ingress
  namespace: default
spec:
  clusterIP: 172.20.37.12
  externalTrafficPolicy: Local
  healthCheckNodePort: 32363
  loadBalancerSourceRanges:
  - 1.2.3.4/28
  - 5.6.7.8/28
  - 9.10.11.12/24
  - 13.14.15.16/28
  - 17.18.19.20/27
  ports:
  - name: http
    nodePort: 30772
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30683
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-ingress-nginx-ingress
  sessionAffinity: None
  type: LoadBalancer`

**Comment by bhagwat070919** [comment]
Just one quick question and thought:

NLBs do not have Security Groups. The current NLB controller opens up the nodePort on the nodes' security group to 0.0.0.0/0 in order to allow traffic. When a user defines loadBalancerSourceRanges, it should respect the IP CIDRs they specify.

You can look at #57212 for reference.

If you are saying its not updating the SG of nodes then we need to look .

**Comment by karan-wahie03** [comment]
@bhagwat070919 yes the node security groups were not updated.

**Comment by bhagwat070919** [comment]
ohk , I will take a look and update.

BTW we would welcome any PR's solving this if you have already identified the bug in the code.

**Comment by njgibbon** [comment]
Hello,

@clalbus  Your [comment](https://github.com/kubernetes/kubernetes/issues/77557#issuecomment-557786174)) was very useful! And is indeed a good workaround to avoid the deletion and re-creation of an NLB resulting in new static IPs or manually adding the rules that are required. 

I can confirm that I am experiencing the same issue on AWS EKS (v1.14.9-eks-502bfb). 

When applied at the point of creation the NLB LoadBalancer Service NodePort inbound rules are added to the worker nodes security group as expected. 

However, when updating the Service Object they do not actually update.

E.g 
```
kubectl -n <namespace> edit svc <nlb-svc>

# add in loadBalancerSourceRanges block

kubectl -n <namespace> describe svc <nlb-svc>

  Type    Reason                    Age                  From                Message
  ----    ------                    ----                 ----                -------
  Normal  EnsuringLoadBalancer      57m (x2 over 2d15h)  service-controller  Ensuring load balancer
  Normal  LoadBalancerSourceRanges  57m                  service-controller  [] -> [11.11.11.11/32 22.22.22.22/32 33.33.33.33/32]
  Normal  EnsuredLoadBalancer       57m (x2 over 2d15h)  service-controller  Ensured load balancer
```
Then checking via AWS console there has been no change to the worker node rules.

As mentioned, currently using workaround described at beginning of post.

**Comment by bhagwat070919** [comment]
Hi @njgibbon ,

When I am verifying the same , I was able to see the worker SG rules updated the same range when I updated the source ranges in service yaml.
I would be happy to verify the same for your cluster.

**Comment by rverma-jm** [comment]
We are kind of facing the issue other way around, i.e. kubernetes automatically add rules to allow traffice from 0.0.0.0 on port 80 and 443 in the provided security group. I think when security group is provided it shouldn't modify the rules inside. Seems like a bug.

**Comment by bhagwat070919** [comment]
Hi @rverma-jm ,

Yes , there was that issue which recently got fixed by 
https://github.com/kubernetes/kubernetes/pull/83446

Thanks

**Comment by 0xlen** [comment]
Refer to https://github.com/kubernetes/kubernetes/pull/74692

**Comment by vampirismtrueblood** [comment]
I think this issue needs to be re-opened, issue still exists with EKS v1.25,
loadBalancerSourceRanges works when creating the NLB, but updating still does not work.
Can we have this re-opened please

**Comment by donovanrost** [comment]
I also ran into this on EKS v1.25

**Comment by jonathan-hosmer** [comment]
This is still an issue in EKS `v1.24.17` (`v1.24.17-eks-508b6b3`).

**Comment by scardena** [comment]
this might not be helpful to everyone, but I was running into this problem because I was using this:
```
 service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
```
targeting a pod ip. this is not supported, I believe. you need to use target type instance:
```
 service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
```
