### ISSUE TITLE
code-generator: deepcopy-gen invalid type for invalid type

### ISSUE THREAD

**Issue by mattysweeps** [kubernetes/kubernetes#79149]
**What happened**:
Executing the script `$GOPATH/src/k8s.io/code-generator/hack/update-codegen.sh` from the directory `$GOPATH/src/k8s.io/code-generator/` failed.

**What you expected to happen**:
The script should have executed normally.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ rm -fr $GOPATH/src/k8s.io/code-generator
$ git clone https://github.com/kubernetes/code-generator $GOPATH/src/k8s.io/code-generator
$ cd $GOPATH/src/k8s.io/code-generator
$ rm -fr $GOPATH/bin/*
$ ./hack/update-codegen.sh

Generating deepcopy funcs
F0618 15:31:03.882214   20632 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from k8s.io/code-generator/_examples/apiserver/apis/example/v1.TestType
```

**Anything else we need to know?**:
This error happened on my personal repo AND on the code-generator repo itself.

I believe this is the line where error is logged: https://github.com/kubernetes/gengo/blob/bc9033e9ec9e0cec1552e9af7c079cb878dfc511/examples/deepcopy-gen/generators/deepcopy.go#L885

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.6", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-05-18T01:21:01Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
gcp
- OS (e.g: `cat /etc/os-release`):
linux (ChromOS linux app)
- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux penguin 4.19.34-04457-g5b63d4390e96 #1 SMP PREEMPT Mon May 13 14:30:19 PDT 2019 x86_64 GNU/Linux
```
- Install tools:
asdf: https://github.com/asdf-vm/asdf
(A teammate who also used asdf did not run into this problem)

- Network plugin and version (if this is a network-related bug):
- Others:
```
$ gcc --version
gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ --version
g++ (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by mattysweeps** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by yue9944882** [comment]
can you paste your code about `TestType`?

**Comment by mattysweeps** [comment]
> can you paste your code about `TestType`?

It's not my code, but example code in the code-generator package:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/code-generator/_examples/crd/apis/example/v1/types.go#L25

I cloned the synced version though:
https://github.com/kubernetes/code-generator/blob/master/_examples/crd/apis/example/v1/types.go#L25

**Comment by poy** [comment]
I'm also bumping into this. I'm using linux.

**Comment by wuqiany2** [comment]
I hit this problem trying to explore CRDs and customer controllers yesterday. Managed to get it solved by moving the code-generator package under $GOPATH.

Refer to https://github.com/kubernetes/code-generator/issues/21

**Comment by mattysweeps** [comment]
Thanks @wuqiany2, your comment helped me figure out my issue. You nailed it: all dependency packages of any fields in the type struct must in the GOPATH. No module support yet.

For a note to whoever else gets stuck here, add `-v 5` to your call of `generate-groups.sh`. This will spam logs, but I found it was the only way to know which packages I was missing.

**Comment by myshkin5** [comment]
@mattysweeps
> No module support yet.

Isn't this a bug then? It still appears to be broken today.

**Comment by mattysweeps** [comment]
> Isn't this a bug then? It still appears to be broken today.

@myshkin5 I'm not sure it's a bug, but some form of improvement would be nice. I've requested that https://github.com/kubernetes/code-generator/issues/21, originally referred in https://github.com/kubernetes/kubernetes/issues/79149#issuecomment-504128650, be reopened. See [my comment on the issue ](https://github.com/kubernetes/code-generator/issues/21#issuecomment-1004487336).
