### ISSUE TITLE
High system load/CPU utilization with trivial liveness and readiness probes

### ISSUE THREAD

**Issue by danbeaulieu** [kubernetes/kubernetes#82440]
**What happened**:
Using trivial probes significantly contributes to CPU/system load.

**What you expected to happen**:
Trivial probes should be performant

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a cluster (minimal reproduction done on an m5.large ec2 instance, creating a single node cluster via kubeadm with a deployment specifying a 2 pod replica scheduled on the single node. Reproduction steps are available for more complex setups)
2. Measure system load/CPU utilization
3. Deploy the following deployment
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: diagnostic
  name: diagnostic
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: diagnostic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: diagnostic
    spec:
      containers:
      - name: diagnostic
        image: ubuntu:18.04 
        command:
        - /bin/bash
        - -c
        - touch /tmp/healthy; sleep 3600
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command:
              - cat
              - /tmp/healthy
          initialDelaySeconds: 10
          periodSeconds: 2
          failureThreshold: 120

        livenessProbe:
          exec:
            command:
              - cat
              - /tmp/healthy
          initialDelaySeconds: 10
          periodSeconds: 2 
          failureThreshold: 120
      restartPolicy: Always
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - operator: "Exists"
```
4. Remeasure system load/CPU utilization

**Anything else we need to know?**:
Included is a screenshot. The beginning shows the node in "steady state" without the deployment running. This is at about 10% utilization. The first blip is deploying a similar deployment with no probes specified, still at 10%. The second blip is deploying a similar deployment but with just the livenessprobe specified, this is about 17%. The third blip is deploying the provided deployment with both liveness and readiness probes specified, this is about 34%. 

![probe-cpu-util](https://user-images.githubusercontent.com/902943/64458045-4a485d00-d0c2-11e9-81ab-70b8ae5ca0b9.png)

Further testing shows that CPU utilization is maxed out and system load extremely high with 4 pods in the deployment.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.3
- Cloud provider or hardware configuration: AWS (m5.large)
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.3
- Kernel (e.g. `uname -a`): 5.0.0-25-generic
- Install tools: kubeadm 1.15.3
- Network plugin and version (if this is a network-related bug): VPC CNI v1.5.3 (reproduced with kuberouter as well)
- Others: Docker 18.09.2

**Comment by danbeaulieu** [comment]
@kubernetes/sig-node-bugs

**Comment by YangYongZhi** [comment]
I think the kubelet will consume some CPU resources, I think it's OK.
And you should check that your liveness and readiness probe logic if they are too complex to be used just as a probe.

**Comment by zjj2wry** [comment]
Setting periodSeconds to 2s is too short

**Comment by Nowaker** [comment]
This is affecting me too. In my case periodSeconds for readiness and liveness is 10s. However, I can see in `pstree` that a `runc` process is **constantly** spawned in any container that has probes defined. With a liveness probe period of 30 seconds, and readiness probe period of 5 seconds, we should NOT see this happen this often.

```
root@node-4:~# for i in `seq 1 5`; do pstree -lspT 54321; sleep 1; done
systemd(1)───containerd(2508)───containerd-shim(54321)─┬─mysqld(57045)
                                                       └─runc(48816)
systemd(1)───containerd(2508)───containerd-shim(54321)─┬─mysqld(57045)
                                                       └─runc(49991)
systemd(1)───containerd(2508)───containerd-shim(54321)─┬─mysqld(57045)
                                                       └─runc(49991)
systemd(1)───containerd(2508)───containerd-shim(54321)─┬─mysqld(57045)
                                                       └─runc(52122)
systemd(1)───containerd(2508)───containerd-shim(54321)─┬─mysqld(57045)
                                                       └─runc(53442)
```

Describe:

```
    Liveness:   exec [sh -c mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}] delay=30s timeout=5s period=10s #success=1 #failure=3
    Readiness:  exec [sh -c mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}] delay=5s timeout=1s period=10s #success=1 #failure=3
```

Difference in CPU idle between running these probes and disabling them on a 16-core 64-thread on `AMD EPYC 7281 16-Core Processor`:

![image](https://user-images.githubusercontent.com/611746/65468648-60784c00-de2a-11e9-92e5-de281cfc9ed6.png)
(Note: this is CPU **idle %**, not CPU usage)

**Comment by neolit123** [comment]
@kubernetes/sig-node-bugs

**Comment by Nowaker** [comment]
Update: I replaced `mysqladmin`-based liveness/readiness probe with `/bin/true`, and increased delaySeconds to 30 seconds and 10 seconds for readiness and liveness respectively, to show it's not due to `mysladmin` usage but the liveness declaration itself. I also increased the number of workloads to show the extent of the slowdown caused by the probes.

```
    Liveness:   exec [/bin/true] delay=30s timeout=5s period=30s #success=1 #failure=3
    Readiness:  exec [/bin/true] delay=5s timeout=1s period=10s #success=1 #failure=3
```

Results:

- 100 pods running without probes: CPU idle 93%
- 100 pods running with probes: CPU idle 60%
  - Conclusion: probes take 33% CPU, everything else takes 7% CPU

![image](https://user-images.githubusercontent.com/611746/65470874-98838d00-de32-11e9-8b2d-e54f17c2f0c4.png)

Now the readiness period is 10 seconds. Still seeing more `runc` processes spawned under `containerd-shim(46819)` that belongs to one of the pods. Seeing at least 10 runc per second.

```
root@node-4:~# for in in `seq 1 10`; do pstree -lspT 46819; sleep 1; done
systemd(1)───containerd(2508)───containerd-shim(46819)─┬─mysqld(46916)
                                                       └─runc(33605)
systemd(1)───containerd(2508)───containerd-shim(46819)─┬─mysqld(46916)
                                                       └─runc(34487)
systemd(1)───containerd(2508)───containerd-shim(46819)─┬─mysqld(46916)
                                                       └─runc(36218)
systemd(1)───containerd(2508)───containerd-shim(46819)─┬─mysqld(46916)
                                                       └─runc(36986)
systemd(1)───containerd(2508)───containerd-shim(46819)─┬─mysqld(46916)
                                                       └─runc(38939)
systemd(1)───containerd(2508)───containerd-shim(46819)─┬─mysqld(46916)
                                                       └─runc(40584)
systemd(1)───containerd(2508)───containerd-shim(46819)─┬─mysqld(46916)
                                                       └─runc(41982)
systemd(1)───containerd(2508)───containerd-shim(46819)─┬─mysqld(46916)
                                                       └─runc(43137)
systemd(1)───containerd(2508)───containerd-shim(46819)─┬─mysqld(46916)
                                                       └─runc(45313)
systemd(1)───containerd(2508)───containerd-shim(46819)─┬─mysqld(46916)
                                                       └─runc(46126)
```

Is there any chance that Kubernetes runs `exec` probes incorrectly?


My cluster info:
```
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

(Unfortunately, I can't test on 1.15 because I use RKE to set up the cluster and their newest versions don't setup the networking correctly - https://github.com/rancher/rke/issues/1606)

**Comment by danbeaulieu** [comment]
@Nowaker I believe the root cause is an inefficiency in moby when exec'ing in to a namespace. https://github.com/moby/moby/issues/39102
I did some testing to confirm by running the exec command via `docker exec` with the same period and then another test just running the same command directly on the host. Kubelet did add some overhead but very little compared to docker/moby. 

I haven't tried other container runtimes, and it seems like best practices are to avoid exec probes...

**Comment by Nowaker** [comment]
Quick update: @chancez pointed out on Kubernetes Slack https://github.com/opencontainers/runc/commit/0a8e4117e7f715d5fbeef398405813ce8e88558b might be the reason why `docker exec` is slow in general. However, this probably doesn't explain why we're seeing a new `runc` spawned *at least* once a second when probe period is 10 seconds.

**Comment by Nowaker** [comment]
Can someone from @kubernetes/sig-node-bugs take a look? I think all provided information is very precise and would be nice to have a Kubernetes dev take a look at this. Thanks in advance. CC @zouyee

**Comment by danfitch** [comment]
We are also seeing high CPU on 1.14 1.13 but not 1.12.  Once we removed the exec based liveliness probes which were simple `nc` and  `pgrep` commands then CPU went back to normal levels.  The runc commands we saw executing are similar to below
```runc --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v1.linux/moby/be.../log.json --log-format json state be2...```

It appears that the runc state command is referencing a log.json from within the overlay filesystem. 
 And from the perf command we ran it appears that the spike in CPU is related to overlay filesystem access but I cannot confirm that.  But once we removed the liveliness probes(running every 10 seconds)(30 pods) the show_mountinfo -> ovl_show_options stopped showing up and CPU went back to a reasonable utilization.

<img width="933" alt="perf HighCPU" src="https://user-images.githubusercontent.com/21924/66056574-f41ddc80-e4fc-11e9-8f8d-eaf9704e0850.png">

**Comment by Random-Liu** [comment]
I think this should fix this https://github.com/containerd/containerd/pull/3711.

Please note **we expect Docker 18.09 to have more resource usage than Docker 17.03**. One reason is that Docker 18.09 starts using containerd 1.2, and compared to the old containerd 0.2.x used by Docker 17.03, containerd 1.2 is expected to use more resource, because it is a full container runtime now.

However, the good thing is that with Docker 18.09, **you can configure Kubernetes to use the underlying containerd 1.2 directly, which should significantly reduce the resource consumption**.

Anyway, exec in containerd shouldn't spawn 8 `runc state` processes. :P 

/cc @kubernetes/sig-node-bugs

**Comment by Nowaker** [comment]
@Random-Liu Thanks!

**Comment by Nowaker** [comment]
The issue still persists on patched containerd. CPU usage over time is similar. This is likely a sole Kubernetes problem.

**Comment by goireu** [comment]
Hi there! (TL;DR: command probes don't scale)

We faced a similar issue and tracked it down. The problem is your probe is a command probe.

To execute the command probes, `containerd` queries `containerd-shim` ~12-15 times. `containerd-shim` has to run `runc` for performing the required action (most of them are `runc state` commands).

Everything works as designed but, as you may know, process forking comes with a terrible cost. In our setup, we had around 1k forks total per second for ~60 pods.

Moving to a TCP probe should solve the problem, it usually isn't complex to design a sidecar probe which opens a port only when your system up alive/ready.

Cheers,

PS: Kudos to @brendangregg for his amazing `execsnoop`

**Comment by Nowaker** [comment]
@goireu Yeah, I know it's the exec probes. However, I wouldn't say it's "my problem", at least not at its core. It's a bug to me that so many of these processes is spawned to execute a single command. I could literally write my own script that probes my pods using kubectl exec every 30 seconds and have zero load comparable to Kubernetes exec probes! Why does Kubernetes/containerd constantly execute something, when it should execute it only every time interval specified in the probe?

**Comment by goireu** [comment]
@Nowaker I said "the problem is", not "your problem is" 😄 

It's not a Kubernetes problem, it is the interface between containerd-shim and runc which was not designed with performance in mind.

There is no bug here, everything works as intended by the developers, we face a design choice that doesn't fit our use case. Life is tough 😆

**Comment by Nowaker** [comment]
> he problem is", not "your problem is" 😄

@goireu Ha ha. :) I read it like that for some reason!

> Edit: BTW, doing a `kubectl exec` every 30 seconds would spawn the same amount of processes, both the exec probe and `kubectl exec` most probably follow the same code path. The problem really is exec'ing 1 process in 1 container will end up spawning about 15 processes.

Is it really true? Please take a look at my findings. ^F `for in in `seq 1 10`; do pstree -lspT 46819; sleep 1; done` in my comments above. As you can see in there, there's *at least* one `runc` process spawned every second (that was the highest granularity I could achieve with `pstree`), and my probes were not configured to `interval=1s`! They were at 10 seconds each (liveness and readiness), so we'd expect to see some runc process spawning less often than every single second. And note I'm focusing on PID=46819, which is a containerd-shim of one specific pod.

I simply cannot wrap my head around the fact that a probe with 10 seconds interval spawns a runs process at least every second. It feels like it spawns runc processes constantly, no matter the interval is 10s or 30s. Same CPU load, so I assume, sam runc spam. Can you explain that? What am I overlooking?

The worst thing is my team has given on a high-scalability goal project that **had to** use `exec` probes, and the testing environment is gone. We weren't aware of `execsnoop` at a time, this would provide some better analytics. sleep+pstree definitely sucks but it's *something*.

**Comment by goireu** [comment]
> Same CPU load, so I assume, sam runc spam. Can you explain that?
For each process you execute in your container, containerd-shim will run a `runc exec` and multiple `runc state` commands, most probably because containerd asks it to do so to follow task state. Here is the runc spam.

**Comment by Nowaker** [comment]
Well, if the number of spawned runc processes doesn't change between interval=10s and interval=30s probes, that means `kubectl exec` mimicking a probe would help reduce the load immensely, because it wouldn't constantly spam with `runc` processes every second (or more frequently, but my pstree+sleep couldn't catch more), correct?

**Comment by goireu** [comment]
To my understanding, `kubectl exec` and exec probes at the same interval should generate the same amount of runc "spam".
Give a try to execsnoop (or execsnoop-proc if your kernel doesn't provide the features required by execsnoop), you'll be able to confirm/infirm this.

**Comment by Nowaker** [comment]
OK. That's not my experience.

On the micro level, no matter what a probe interval was, I always saw a new `runc` process every second (pstree+sleep approach).

On a macro level, the CPU usage of a beefy server with 100 pods with exec probes caused the same CPU load regardless of probe interval.

Due to how bad the solution was, we no longer have the test env, the hardware, and time allocation for this project. But I'll check if there's any remnants of this laying around somewhere. With execsnoop, we will no longer have to fill up a server with pods to start seeing runc spam in pstree  (in low-load situations pstree can't spot these processes - it's visible only under heavy load). And that should make a retest simpler and faster. I'll see what I can do.

Thanks for your input @goireu.

**Comment by dims** [comment]
Can someone please kick the tires with containerd 1.3.2 / 1.2.11 to confirm if things are better for exec based probes?

**Comment by Nowaker** [comment]
@dims My team tested around November 14th on this version of containerd:

```containerd --version
containerd github.com/containerd/containerd v1.3.0-113-gd7ec45b1 d7ec45b172d956575dbd195d809172095bc74bbb```

Have there been any changes related to execing since then, other than https://github.com/containerd/containerd/pull/3711?

**Comment by dims** [comment]
@Nowaker https://github.com/containerd/containerd/compare/v1.3.0...v1.3.2

**Comment by Nowaker** [comment]
Doesn't like there's anything that relates to `exec` apart from https://github.com/containerd/containerd/pull/3711 which my team already tested against, and there was no visible change in CPU usage.

**Comment by Nowaker** [comment]
Not rotten please.

**Comment by axot** [comment]
I think this may related to `mount` syscall as I mentioned above.  opencontainers/runc#2532

**Comment by axot** [comment]
@Nowaker Could you share the result of `cat /proc/1/mountinfo | wc -l` on these problematic Pods?

**Comment by Nowaker** [comment]
@axot Unfortunately, our infrastructure for this project is gone, as Kubernetes wasn't able to offer any reasonable capacity increase for our workloads compared to KVM VMs due to how much CPU was wasted on exec probes.

However, if you really think it's going to be a big help in figuring this issue out, I can look into redeploying it elsewhere and checking this for you.

**Comment by cyphar** [comment]
Taking a quick look, https://github.com/kubernetes/kubernetes/issues/82440#issuecomment-534332237 is describing Kubernetes effectively spamming `runc status` (the output of which is the JSON blob described). I don't think it's directly related to opencontainers/runc#2532 (we don't do any mounts in `runc status`), but I'm also not sure why Kubernetes (or I guess containerd) is requesting the status so many times.

**Comment by axot** [comment]
@Nowaker I just want to confirm is this a same situation against your case. I can reproduce in my environment.

**Comment by Nowaker** [comment]
Thanks for clarifying, @cyphar. Sounds like this one is solely on Kubernetes. And yeah, I now recall it's `runc status` specifically that gets spammed - instead of being executed according to the probe period.

@axot Do you see the same behavior as me, that is, runc spam regardless of probe period?

**Comment by axot** [comment]
@Nowaker I can see many runc state process. Here is the output.

```
# for in in `seq 1 10`; do date; pstree -alspT 3398632; sleep 1; done
Wed Sep 30 05:58:00 UTC 2020
systemd,1
  `-containerd,936
      `-containerd-shim,3398632 -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
          |-nutcracker,3398703 -c /etc/nutcracker.yml -v 1 -o /dev/stdout
          `-runc,938524 --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v1.linux/moby/d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4/log.json --log-format json exec --process /tmp/runc-process093900714 --detach --pid-file /run/containerd/io.containerd.runtime.v1.linux/moby/d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4/f5ea0f6c12b53a00b59ff974f7e716dd4901113a8179b1649b11cc19bacd15fe.pid d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4
Wed Sep 30 05:58:01 UTC 2020
systemd,1
  `-containerd,936
      `-containerd-shim,3398632 -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
          |-containerd,938664 --address /run/containerd/containerd.sock publish --topic /tasks/exit --namespace moby
          |-nutcracker,3398703 -c /etc/nutcracker.yml -v 1 -o /dev/stdout
          `-runc,938665 --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v1.linux/moby/d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4/log.json --log-format json state d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4
Wed Sep 30 05:58:02 UTC 2020
systemd,1
  `-containerd,936
      `-containerd-shim,3398632 -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
          |-containerd,938664 --address /run/containerd/containerd.sock publish --topic /tasks/exit --namespace moby
          `-nutcracker,3398703 -c /etc/nutcracker.yml -v 1 -o /dev/stdout
Wed Sep 30 05:58:03 UTC 2020
systemd,1
  `-containerd,936
      `-containerd-shim,3398632 -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
          |-nutcracker,3398703 -c /etc/nutcracker.yml -v 1 -o /dev/stdout
          `-runc,938947 --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v1.linux/moby/d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4/log.json --log-format json state d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4
Wed Sep 30 05:58:04 UTC 2020
systemd,1
  `-containerd,936
      `-containerd-shim,3398632 -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
          |-nutcracker,3398703 -c /etc/nutcracker.yml -v 1 -o /dev/stdout
          |-runc,939006 --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v1.linux/moby/d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4/log.json --log-format json state d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4
          `-runc,939007 --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v1.linux/moby/d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4/log.json --log-format json exec --process /tmp/runc-process484539649 --detach --pid-file /run/containerd/io.containerd.runtime.v1.linux/moby/d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4/10164867c2759e36580215d3775bbd868d95f8802ceb51d95af49ab420a67346.pid d7d4b2cb0949caa5b9360decb39926654fcae2db5c9e425744045de62d9327d4
```

**Comment by Nowaker** [comment]
Thanks a ton, @axot. We finally have a second person to confirm the `runc status` spam that is way too frequent for a given exec probe period.

Dear @kubernetes/sig-node-bugs team, may I ask you to reevaluate this issue? There's strong evidence the issue is not about inefficiencies in runc for exec even though these were suggested multiple times.

**Comment by williamsbdev** [comment]
I've experienced the same issue using `/bin/true` in our pod `liveness` and `readiness` probes.

Additionally, I noticed this request for more information:

> @Nowaker Could you share the result of `cat /proc/1/mountinfo | wc -l` on these problematic Pods and vm node?

Here is the output in our environment:

```
37
```

**Environment:**

Kubernetes version (use kubectl version): 1.17.13-gke.2001
Cloud provider or hardware configuration: GKE (n1-standard-4)
OS (e.g: cat /etc/os-release): Container-Optimized OS (cos)

**Comment by Nowaker** [comment]
Reping after half a year:

> Dear @kubernetes/sig-node-bugs team, may I ask you to reevaluate this issue? There's strong evidence the issue is not about inefficiencies in runc for exec even though these were suggested multiple times. Kubernetes is spamming runc state for any pod with an exec probe defined, regardless of its period.

**Comment by dims** [comment]
long-term-issue (note to self)

cc @adisky

**Comment by Nowaker** [comment]
Not stale.

**Comment by pigletfly** [comment]
How many services in your single namespace?I have many services in the same namespace,so there are many service environments.If I unset all service environments before readiness exec command execution,the CPU utilization seems better than before.

**Comment by ehashman** [comment]
/lifecycle frozen
:skier:

**Comment by adisky** [comment]
/assign 
will try to reproduce first on latest containerd+runc+k/k

**Comment by adisky** [comment]
@Nowaker Can you confirm which containerd version you are using? I tried to reproduce on containerd-1.5 and k8s 1.22 and I can see containerd spawning only one runc process to exec.
```
[pid 2944697]      0.000000 execve("/usr/local/sbin/runc", ["runc", "--root", "/run/containerd/runc/k8s.io", "--log", "/run/containerd/io.containerd.ru"..., "--log-format", "json", "exec", "--process", "/tmp/runc-process857817035", "--detach", "--pid-file", "/run/containerd/io.containerd.ru"..., "4816f4e3840dae576d16ced72a912721"...], 0xc000246180 /* 7 vars */) = 0
```

I have seen spike in cpu utilisation with 50 pods and liveness and readiness probes with the interval of 10 seconds, but not forking of multiple runc processes by containerd for single exec.

**Comment by Nowaker** [comment]
@adisky We don't have that environment any more because of how highly inefficient running Kubernetes for our use case was, so I can't tell if containerd 1.5 and Kubernetes 1.22 resolved the problem. I can however give it a test on some spare hardware we have around.

How did you get your exec output? Does it show all execs discovered on the machine?

So far all I've done is use `pstree` to somewhat track the problem. And it only becomes visible when I deploy hundreds of pods. A more reliable method that will log every single exec would be helpful.

>> I also have a strace of runc process. I actually had hundreds of straces but catching a process that is very shortlived red-handed is very hard, so I was scanning for a runc process in a loop, outputting the strace to a file, and after a while picked the largest file.

```
while true; do XPID=$(pstree -lspT 64055 | grep runc | sed 's/[^0-9]*//g'); if [ -z "$XPID" ]; then continue; fi;  echo "$XPID: "; strace -p "$XPID" -s 128 -o /tmp/strace-$XPID; sleep 1; done
```

**Comment by ehashman** [comment]
/retitle High system load/CPU utilization with trivial liveness and readiness exec probes

This issue does not appear to affect HTTP probes.

This will be easier to fix if someone can provide a working minimal repro (i.e. a barebones pod specification, perhaps using a pause container).

My suggestion for debugging this once someone has a repro is to dump kubelet perf data and stare at it to try to determine what's taking CPU time. Wider bars on a flame graph = more CPU. I don't think there are any live recordings of me doing such a walkthrough, but here are some examples from other bugs:

- https://bugzilla.redhat.com/show_bug.cgi?id=1953102#c7
- https://github.com/kubernetes/kubernetes/issues/101989#issuecomment-882799530
- https://github.com/kubernetes/kubernetes/issues/104459#issuecomment-925411730

**Comment by Nowaker** [comment]
@alex-koturanov Since it sounds like you have this environment running, could you plot the CPU usage on a graph like mine? I'd love to see the CPU usage for each case:

1. exec health probes + `enableServiceLinks: true`
2. exec health probes + `enableServiceLinks: false`
3. httpGet health probes + `enableServiceLinks: true`
4. httpGet health probes + `enableServiceLinks: true`

**Comment by Nowaker** [comment]
> I'd advice you to plot CPU usage by usage type.

Or simply plot CPU idle time.

**Comment by lucca** [comment]
@ehashman I seem to have a repro using `busybox` as a container:

- Minikube v1.25 (configured at 4 cpus, 4Gi memory)
- Kubernetes v1.23.3
- containerd v1.6.1 (everything else came out of the box with minikube. I updated just this from v1.4)
- [Pod spec](https://gist.github.com/lucca/0456d3e0edacd0e51e8d9015c38e9176): `busybox` container, 10 replicas, using `cat` as a liveness/readiness probe
- [Service spec](https://gist.github.com/lucca/be6360328cff9f49f8424a4683989fe2): I used a script to put 3380 dummy ports into this file, which creates ~16900 env variables total in each pod.

Here's my CPU usage before and after configuring `enableServiceLinks=false`.

![Screen Shot 2022-03-08 at 4 10 06 PM](https://user-images.githubusercontent.com/34192044/157343817-73f9d1c6-00a3-40e7-82a6-d0c89259a2a4.png)

<details closed>
<summary>pstree</summary>
<br>

```
docker@minikube:~$ top
top - 23:43:29 up 10:28,  0 users,  load average: 9.21, 6.68, 5.48
Tasks: 119 total,   7 running, 112 sleeping,   0 stopped,   0 zombie
%Cpu(s): 54.9 us, 12.9 sy,  0.0 ni, 32.1 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
MiB Mem :   3933.9 total,    689.2 free,   2021.5 used,   1223.3 buff/cache
MiB Swap:   1024.0 total,    576.3 free,    447.7 used.   1573.4 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
2993933 root      20   0 1308760  18908   7068 R  34.7   0.5   0:01.04 runc:[2:INIT]
2993922 root      20   0 1160916  18680   7276 R  34.3   0.5   0:01.03 runc:[2:INIT]
2993957 root      20   0 1160444  18936   7304 R  33.7   0.5   0:01.01 runc:[2:INIT]
2993964 root      20   0 1087184  18292   7240 R  30.3   0.5   0:00.91 runc:[2:INIT]
   1798 root      20   0 3675248 176700  37296 S  20.3   4.4  71:46.72 kubelet
    383 root      20   0 6646336 692132  14592 S  19.3  17.2  58:49.29 dockerd
    109 root      20   0 2315408  53280  20344 S  13.0   1.3  35:04.23 containerd
   1585 root      20   0 1182284 326848  52384 S  10.3   8.1  72:35.60 kube-apiserver
2993992 root      20   0 1233184  15904   6988 R   7.0   0.4   0:00.21 runc:[2:INIT]
2994005 root      20   0 1087396  15832   7148 R   6.0   0.4   0:00.18 runc:[2:INIT]
```

</details>

<details closed>
<summary>top</summary>
<br>

```
docker@minikube:~$ pstree
systemd-+-containerd---20*[{containerd}]
        |-7*[containerd-shim-+-pause]
        |                    `-10*[{containerd-shim}]]
        |-13*[containerd-shim-+-pause]
        |                     `-11*[{containerd-shim}]]
        |-containerd-shim-+-kube-controller---17*[{kube-controller}]
        |                 `-11*[{containerd-shim}]
        |-containerd-shim-+-etcd---15*[{etcd}]
        |                 `-11*[{containerd-shim}]
        |-containerd-shim-+-kube-apiserver---20*[{kube-apiserver}]
        |                 `-10*[{containerd-shim}]
        |-containerd-shim-+-kube-scheduler---11*[{kube-scheduler}]
        |                 `-11*[{containerd-shim}]
        |-containerd-shim-+-kube-proxy---10*[{kube-proxy}]
        |                 `-11*[{containerd-shim}]
        |-containerd-shim-+-coredns---12*[{coredns}]
        |                 `-10*[{containerd-shim}]
        |-containerd-shim---10*[{containerd-shim}]
        |-containerd-shim-+-storage-provisi---8*[{storage-provisi}]
        |                 `-11*[{containerd-shim}]
        |-containerd-shim-+-metrics-server---12*[{metrics-server}]
        |                 `-11*[{containerd-shim}]
        |-containerd-shim-+-dashboard---9*[{dashboard}]
        |                 `-10*[{containerd-shim}]
        |-containerd-shim-+-metrics-sidecar---14*[{metrics-sidecar}]
        |                 `-11*[{containerd-shim}]
        |-6*[containerd-shim-+-sh---sleep]
        |                    `-11*[{containerd-shim}]]
        |-containerd-shim-+-runc-+-runc:[2:INIT]---7*[{runc:[2:INIT]}]
        |                 |      `-8*[{runc}]
        |                 |-sh---sleep
        |                 `-11*[{containerd-shim}]
        |-2*[containerd-shim-+-sh---sleep]
        |                    `-10*[{containerd-shim}]]
        |-containerd-shim-+-sh---sleep
        |                 `-9*[{containerd-shim}]
        |-dbus-daemon
        |-dockerd---212*[{dockerd}]
        |-kubelet---32*[{kubelet}]
        |-sshd-+-2*[sshd---sshd]
        |      `-sshd---sshd---bash---pstree
        |-systemd-journal
        `-systemd-logind
```

</details>

**Comment by ak2766** [comment]
I've just hit this issue.  Adding an horizontal pod autoscaler to my deployment pushes it to >1000% CPU causing it to immediately hit the maxreplicas.  Turning off liveness probe and CPU usage drops to the nominal 15%.

I'm going to have to rely on my external icinga2 monitoring system for my production environment until this issue is resolved.

If there's anything I can do to help isolate the issue, let me know which commands you'd like me to run.

**Comment by goireu** [comment]
> If there's anything I can do to help isolate the issue, let me know which commands you'd like me to run.

If you are using an exec probe, try using an HTTP probe. Here our problem was our cluster was down on his knees because each exec probe summons 10-15 processes and the system couldn't handle what looked like a fork() bomb.

**Comment by Nowaker** [comment]
If exec probes kill clusters, isn't it about time to redesign the probes and come up with a totally different approach if forking is too expensive? For example, have Kubernetes exec into a container once and have a script/binary running there more like a cron that executed probes locally? Daemon-approach for probes. Is this something that could be discussed during `sig-node` meeting?

**Comment by eldada** [comment]
Just to share our story... we moved to `exec` probes also to deal with https://github.com/kubernetes/kubernetes/issues/89898. There are also other internal considerations, but with this issue, we feel we are holding a double edged sword. 

So I guess it's a delicate balancing act now...

**Comment by goireu** [comment]
Here we got rid of the problem by writing an HTTP-probable sidecar for our app.

**Comment by Nowaker** [comment]
> Well I'd argue you are going to have problems with exec probes with large pod count, but not everyone runs hundreds of pods on each node, so it's perfectly fine using exec probes in lots of use cases.

One of the core goals of Kubernetes, as per the homepage, is:

> Designed on the same principles that allow Google to run billions of containers a week, Kubernetes can scale without increasing your operations team.

Except you can't run billions of containers a week with exec probes as that basically kills big clusters.

**Comment by liguangcheng** [comment]
@Nowaker In fact, not only the probing will lead to a sharp increase in the cpu usage, but I also encountered a similar problem when using the exec method of node.js in the container to parse a certificate. It took 3 seconds to parse a certificate, and the cpu usage increased significantly, and I don't know the reason

**Comment by ak2766** [comment]
@goireu - Only ever used HTTP probes.

**Comment by gazandic** [comment]
Configuring `enableServiceLinks=false` able to reduce our usages. In our case, exec probe running a script that utilize memory.

Here's my Memory & CPU utilization before and after configuring `enableServiceLinks=false`. Memory utilization decreases from about 40% to 10%. CPU also decreased but not noticeable in my case.

<img width="486" alt="Screen Shot 2023-02-08 at 11 23 14" src="https://user-images.githubusercontent.com/9495683/217433901-e3653c3b-d80f-460d-a3c4-1b0200a939d1.png">

Thanks  @alex-koturanov @Nowaker @lucca , you’re the best.

**Comment by SergeyKanzhelev** [comment]
/priority backlog

reflecting reality as it is very old standing issue

**Comment by AadiDev005** [comment]
I'm seeing something similar in our production clusters - exec probes with `cat /tmp/healthy` causing way more CPU overhead than expected.

@danbeaulieu's analysis pointing to the moby issue makes sense, but @Nowaker's observation about runc processes spawning every second (instead of every 10s per the probe period) is really concerning. That suggests something's broken in the probe execution pipeline.

Has anyone tested this with containerd/cri-o instead of Docker to see if it's specifically a Docker/moby problem? Would be good to isolate whether this is a container runtime issue or something in kubelet's probe handling.

The fact that 100 pods with trivial probes can consume 33% CPU is pretty brutal for production workloads. Most folks probably don't realize their health checks are eating that much resource.

@kannon92 since you just moved this back to triaged - any chance someone can take a fresh look at the probe execution path? This feels like it should be higher priority given the production impact.

**Comment by 2rs2ts** [comment]
> Has anyone tested this with containerd/cri-o instead of Docker to see if it's specifically a Docker/moby problem?

It is a problem at my company with containerd. We advised our users to turn their exec probes into an HTTP endpoint that 403s unless the connection is coming from our intranet, and otherwise spawns a subprocess to run what would have been the exec probe's command. Since doing so, we saw a decent performance improvement, but since it's a large organization, it's not like we were able to completely make a switch. Still, just reducing exec probe use by ~25% reduced the amount of resources used by the system by a fair amount, and we have far fewer incidents of nodes becoming unresponsive due to CPU starvation (it went from a couple times a week to about once a month.)

**Comment by cyphar** [comment]
Note that runc 1.2 has effectively solved the performance issues with `runc exec` (rather than creating a global read-only mount or a memfd we create an internal overlayfs with `fsopen(2)`, which avoids most of the global VFS locks).

**Comment by Nowaker** [comment]
> It is a problem at my company with containerd

> Note that runc 1.2 has effectively solved the performance issues with runc exec 

For the record, exec probes may be expensive to call but looking at it logically, **it is a Kubernetes problem** - a probe that's supposed to run every 30 seconds cannot spawn runc processes constantly. Even if runc 1.2 introduces performance improvements, the bloat of spamming processes still exists and shouldn't be ignored.

I can't believe it's been 6 years since this was first reported, with clear evidence of runc processes being spammed, and no willingness to resolve the issue that drains resources so heavily. Reduction of CPU usage by 50% is massive.

**Comment by cyphar** [comment]
Sure, I just wanted to include an update that we have done the best we can on the runc side to reduce the impact of this issue (as well as other similar issues). As you say, any further improvements would need to come from the k8s side imho.

**Comment by Nowaker** [comment]
@cyphar Absolutely, not questioning the intention. It's just frustrating that this is clearly an issue that causes so much damage, and it continues to be ignored. Sometimes, there's no other way than to have an exec probe.
