### ISSUE TITLE
[Failing Job] pull-kubernetes-kubemark-e2e-gce-big

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#82676]
**Which jobs are failing**:
pull-kubernetes-kubemark-e2e-gce-big

**Since when has it been failing**:
As per triage, https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&job=pull-kubernetes-kubemark-e2e-gce-big , this job has flaked 647 times in the last 15 days.

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-kubemark-e2e-gce-big

**Reason for failure**:
Some recent flakes seem to be related to Prometheus:
```
W0912 21:16:26.968] I0912 21:16:26.968598  100578 prometheus.go:266] Waiting for Prometheus stack to become healthy...
W0912 21:16:57.007] W0912 21:16:57.007420  100578 util.go:59] error while calling prometheus api: the server is currently unable to handle the request (get services http:prometheus-k8s:9090)
W0912 21:17:27.014] I0912 21:17:27.014565  100578 util.go:85] 7/8 targets are ready
W0912 21:17:57.014] I0912 21:17:57.014242  100578 util.go:88] All 8 expected targets are ready
W0912 21:17:57.056] I0912 21:17:57.055801  100578 util.go:85] 0/1 targets are ready
...
W0912 21:31:27.183] F0912 21:31:27.175941  100578 clusterloader.go:245] Error while setting up prometheus stack: timed out waiting for the condition
```
This was taken from https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/82650/pull-kubernetes-kubemark-e2e-gce-big/1172250383477641216/#0:build-log.txt%3A2219

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/82658/pull-kubernetes-kubemark-e2e-gce-big/1172231629049958400/ is another example with thesame failure.

/priority important-soon
/kind flake
/milestone v1.17
/sig scalability
/cc @kubernetes/sig-scalability-test-failures 
/cc @alenkacz

**Comment by alejandrox1** [comment]
@wojtek-t Opened https://github.com/kubernetes/perf-tests/issues/797 as a follow up how we can avoid that in the future.
this looks to be resolved though.
/close

**Comment by liggitt** [comment]
/reopen

the hard failure was fixed on the 1.16 release branch but the job overall is still very flaky

**Comment by alejandrox1** [comment]
The job does still have a good amount of failures but these seem to be different that the failure raised in this issue. 
Will mark this one as done and open up a new issue to investigate and see what else can be done to reduce flakiness for this job.

For future reference: https://github.com/kubernetes/kubernetes/issues/78701 was the previous flake issue related to this job.

/close
