### ISSUE TITLE
Flip pod's ready condition when node is unreachable

### ISSUE THREAD

**Issue by bnprss** [kubernetes/kubernetes#8335]
Getting hit by the new policy on skydns I shut down the host where it was running and waited for an automatic relocation.
After a while (~1h) I manually stopped the pod and it was launched on a new one, as expected.

If host status is NotReady pods should be moved.

Here is the pod status when host was down : 
```
{
    "kind": "Pod",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "kube-dns-787nc",
        "generateName": "kube-dns-",
        "namespace": "default",
        "selfLink": "/api/v1beta1/pods/kube-dns-787nc?namespace=default",
        "uid": "c32c0c6f-fb0a-11e4-83a8-42010af0b423",
        "resourceVersion": "36141",
        "creationTimestamp": "2015-05-15T14:00:37Z",
        "labels": {
            "k8s-app": "kube-dns",
            "kubernetes.io/cluster-service": "true"
        },
        "annotations": {
            "kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1beta3\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"default\",\"name\":\"kube-dns\",\"uid\":\"c3274113-fb0a-11e4-83a8-42010af0b423\",\"apiVersion\":\"v1beta3\",\"resourceVersion\":\"136\"}}"
        }
    },
    "spec": {
        "volumes": [
            {
                "name": "dns-token",
                "hostPath": null,
                "emptyDir": null,
                "gcePersistentDisk": null,
                "awsElasticBlockStore": null,
                "gitRepo": null,
                "secret": {
                    "secretName": "token-system-dns"
                },
                "nfs": null,
                "iscsi": null,
                "glusterfs": null
            }
        ],
        "containers": [
            {
                "name": "etcd",
                "image": "gcr.io/google_containers/etcd:2.0.9",
                "command": [
                    "/usr/local/bin/etcd",
                    "-listen-client-urls",
                    "http://127.0.0.1:2379,http://127.0.0.1:4001",
                    "-advertise-client-urls",
                    "http://127.0.0.1:2379,http://127.0.0.1:4001",
                    "-initial-cluster-token",
                    "skydns-etcd"
                ],
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "IfNotPresent",
                "capabilities": {}
            },
            {
                "name": "kube2sky",
                "image": "gcr.io/google_containers/kube2sky:1.4",
                "args": [
                    "-domain=kubernetes.local",
                    "-kubecfg_file=/etc/dns_token/kubeconfig"
                ],
                "resources": {},
                "volumeMounts": [
                    {
                        "name": "dns-token",
                        "readOnly": true,
                        "mountPath": "/etc/dns_token"
                    }
                ],
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "IfNotPresent",
                "capabilities": {}
            },
            {
                "name": "skydns",
                "image": "gcr.io/google_containers/skydns:2015-03-11-001",
                "args": [
                    "-machines=http://localhost:4001",
                    "-addr=0.0.0.0:53",
                    "-domain=kubernetes.local."
                ],
                "ports": [
                    {
                        "name": "dns",
                        "containerPort": 53,
                        "protocol": "UDP"
                    },
                    {
                        "name": "dns-tcp",
                        "containerPort": 53,
                        "protocol": "TCP"
                    }
                ],
                "resources": {},
                "livenessProbe": {
                    "exec": {
                        "command": [
                            "/bin/sh",
                            "-c",
                            "nslookup foobar 127.0.0.1 \u0026\u003e /dev/null; echo ok"
                        ]
                    },
                    "initialDelaySeconds": 30,
                    "timeoutSeconds": 5
                },
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "IfNotPresent",
                "capabilities": {}
            }
        ],
        "restartPolicy": "Always",
        "dnsPolicy": "Default",
        "host": "internal-changecommerce-minion-006"
    },
    "status": {
        "phase": "Running",
        "Condition": [
            {
                "type": "Ready",
                "status": "False"
            }
        ],
        "hostIP": "104.155.83.214",
        "podIP": "10.244.6.2",
        "containerStatuses": [
            {
                "name": "etcd",
                "state": {
                    "running": {
                        "startedAt": "2015-05-15T18:25:16Z"
                    }
                },
                "lastState": {
                    "termination": {
                        "exitCode": 0,
                        "startedAt": "2015-05-15T15:12:48Z",
                        "finishedAt": "2015-05-15T18:23:57Z",
                        "containerID": "docker://1519a9ff8807f84ce55df761164460c66ba4a0e3f2eec0da7c650c9d121f4956"
                    }
                },
                "ready": true,
                "restartCount": 1,
                "image": "gcr.io/google_containers/etcd:2.0.9",
                "imageID": "docker://b6b9a86dc06aa1361357ca1b105feba961f6a4145adca6c54e142c0be0fe87b0",
                "containerID": "docker://43ab1b874434e97b868ed3e79437dd5dd0225a504b24e31a9490edb11f70cbfd"
            },
            {
                "name": "kube2sky",
                "state": {
                    "running": {
                        "startedAt": "2015-05-15T18:36:15Z"
                    }
                },
                "lastState": {
                    "termination": {
                        "exitCode": 255,
                        "startedAt": "2015-05-15T18:36:05Z",
                        "finishedAt": "2015-05-15T18:36:06Z",
                        "containerID": "docker://d58e3371d512551275314f45417a0ac0cb98897aa7296a7d132280e080e3b3d3"
                    }
                },
                "ready": false,
                "restartCount": 15,
                "image": "gcr.io/google_containers/kube2sky:1.4",
                "imageID": "docker://3df83f1bccbf18ab59cd64da32cda26b4f56ae0cd6bb6e374477a60468f04232",
                "containerID": "docker://919a5faa8a89dba0e975165995d32ba60b873d2b4e96a590fe840dee1b28a122"
            },
            {
                "name": "skydns",
                "state": {
                    "running": {
                        "startedAt": "2015-05-15T18:25:20Z"
                    }
                },
                "lastState": {
                    "termination": {
                        "exitCode": 2,
                        "startedAt": "2015-05-15T18:00:20Z",
                        "finishedAt": "2015-05-15T18:23:57Z",
                        "containerID": "docker://40a68db359a90b3aedcefbd960f51347841f21d65773140509dc045664b1a714"
                    }
                },
                "ready": true,
                "restartCount": 9,
                "image": "gcr.io/google_containers/skydns:2015-03-11-001",
                "imageID": "docker://791ddf327076e0fd35a1125568a56c05ee1f1dfd7a165c74f4d489d8a5e65ac5",
                "containerID": "docker://dd53be5827169136e55d768ac7d05a5c3664a2d1ba4c4b377b1d862f78993ca1"
            }
        ]
    }
}
```

**Comment by bprashanth** [comment]
If a node stays down the nodecontroller should notice and delete pods on it (within ~10m), after which the rc will create new pods and the scheduler will assign them to nodes. @bnprss how recent is you code?

**Comment by bprashanth** [comment]
Can you also confirm that the pod was never deleted? (if the pod was created via rc, and the node controller did delelete, the new pod will have a different name). I'm trying to isolate which of the components misbehaved.

**Comment by brendandburns** [comment]
I think if you're using an RC you should get pods back faster.  The pod should go to 'Unknown' and I don't think that we should count 'Unknown' state pods as being part of the set.

**Comment by bprashanth** [comment]
It will take ~5m for the nodecontroller to delete the pod from a bad host, and ~40s for it to declare the host as bad

**Comment by bprashanth** [comment]
The rc only currently cares about failed and succeeded. @brendanburns does it make sense to teach it about unknown? still thinking about it

**Comment by dchen1107** [comment]
I couldn't reproduce the issue with HEAD. Which version are you running?

**Comment by bprashanth** [comment]
It'll stay on a dead node for 5.40 seconds by default (expected), quite a bit longer if you run into: https://github.com/GoogleCloudPlatform/kubernetes/issues/8382.
 
I think this issue is more about the pod staying `Running` while the node goes to `Unknown`, and if we can be more clear about the pod status in this period (also flip to unknow in 40s?). 

As an implementation detail, it was mentioned that this might need plumbing in the kubelet (the kubelet won't notice the pod is unknown when the partition recovers?).

**Comment by davidopp** [comment]
We don't want RCs to create replacement pods just because the machine becomes unreachable; that's why we have the longer timeout for evicting pods than for stopping scheduling (and reporting the problem, i.e. Unknown).  If 5 minutes is too long we can certainly reduce the timeout, but it's 5 minutes in Borg IIRC and that seems to have worked well.

Changing the PodStatus to Unknown when the node goes to Unknown might be useful, though as @yujuhong pointed out today, that would mean NodeController and Kubelet would share writing to PodStatus, since NodeController is what determines the node is not responsive. (Which isn't the end of the world, as we already do this for NodeStatus, but it's ugly.)

**Comment by yujuhong** [comment]
We'd need to modify the [status manager](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/status_manager.go) (kubelet's status cache) to check against the pod (and its status) from the watch, and send the update if they are not the same. Kubelet may send the same update to the API server a couple of times until it finally sees the latest pod from watch, but I think it's tolerable. The implementation is not be as bad as I expected after refreshing my memory from looking at the code.

**Comment by bprashanth** [comment]
I would argue that the kubelet should do this anyway (rectify a corrupt pod phase based on observed state)

**Comment by yujuhong** [comment]
Agreed. I will send a PR to do that.

**Comment by bgrant0607** [comment]
We should not change pod phase to Unknown. We used to do that, and it was a nightmare. Additionally. that's not consistent with the model for phase. See #7856 for more details.

We should change the pod's Ready condition to false if the node is unreachable. That has the additional benefit of removing it from the set of endpoints targeted by the service. This is discussed in #8674.

That would mean that the application availability would be gated by kubelet availability, but I don't see kubelet failures as a big problem at the moment. If it were, we could introduce a node Reachable condition (determined by pinging the node or somesuch; we had this but removed it in #6089 because it wasn't implemented), and use that to change pod readiness in the absence of info from kubelet.

Presenting the current status to users -- see #7843.

**Comment by roackb2** [comment]
Is there any possible way to shorten the time it needs to evict old pod and create new one after a node is marked NotReady?

In my use case, if I `systemctl stop docker` to simulate some unexpected situation, or reboot the machine, I can see that node to be marked as NotReady, but the pod is still marked as running, the endpoint also exists, and it takes about 5 minutes to create a new pod.

However, kube-proxy seems to keep routing traffic to the dead pod and then try another one for every request, which makes my web extremely slow, and is not acceptable in production, so I need a way to shorten the time to create the new pod.

kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"0+", GitVersion:"v1.0.0-891-gc5bffaaf316651", GitCommit:"c5bffaaf3166513da6259c44a5d1ba8e86bea5ce", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0+", GitVersion:"v1.0.0-891-gc5bffaaf316651", GitCommit:"c5bffaaf3166513da6259c44a5d1ba8e86bea5ce", GitTreeState:"clean"}
```

Or any other suggestion to conquer this would be very helpful, thx in advance.

**Comment by bprashanth** [comment]
@roackb2 It's a command line flag (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L123) depending on how you setup your cluster, you can modify that by hand, salt, init file etc. We're also making kube-proxy/loadbalancing layer smarter for 1.1 so you get health checks for such scenarios.

**Comment by bgrant0607** [comment]
The default podEvictionTimeout is [currently 5 minutes](https://github.com/GoogleCloudPlatform/kubernetes/blob/bed0e1e1b0c6791b810b5f233ae80688e162e7a4/cmd/kube-controller-manager/app/controllermanager.go#L102), though we're discussing how to reduce that without evicting pods too eagerly in the case of network partition or kubelet being too busy to phone home. Set --pod-eviction-timeout (Go duration var) on the controller-manager.

cc @gmarek

**Comment by bprashanth** [comment]
Just fixing this bug should remove the pod from the service endpoint.

**Comment by roackb2** [comment]
Thank you guys very much.

**Comment by gmarek** [comment]
My 2c in it is that we shouldn't make timeout shorter than Monit period (2m30s) + Kubelet startup time (0m30s) + at least two Kubelet "ping periods" (0m20s) + some offset (20%?). This gives roughly 4 minutes, and I'm not certain we can do much better.

To make it noticeably shorter we need to:
* decrease Monit period
* improve Kubelet startup time

**Comment by wojtek-t** [comment]
FYI: Monit period is 2m (not 2m30s).

**Comment by gmarek** [comment]
Isn't it the case, that we have this additional 30s when Monit detects that something's down? On the other hand I underestimated Kubelet startup time by ~5-10s.

**Comment by bnprss** [comment]
@gmarek  Monit is not relevant in that situation :
- if node is down, it's gone, bye bye local checks, local remediation and whatever things coming from local actions.
- If node is out of network, pods should start elsewhere, and iptables are then redirecting network to healthy pods, when network is up again, kubelet is killing lasts pods, monit role? nothing.
- If kubelet has gone, then monit has to restart it by checking it's health each 2m.

The last case is a special one, expectation are that kubelet has just exited for whatsoever reason. And because of that it'll be valuable to keep the pods as is.

External health checks came from kube-controller-manager, let them here, they are almost safe.

**Comment by gmarek** [comment]
@bnprss you're right, but we have no way of determining which of the three happened. We can have another daemon other than Kubelet that's responding on healthz checks, but it'd have exactly the same problem it this daemon dies. Kubelet can die for various reasons: bug in the code and segfault, sys OOM, you take it.

**Comment by bnprss** [comment]
@gmarek kube-proxy for example is already able to provide health ckecks. So you can consider that failure on kubelet + kube-proxy = host down _or_ out of network.

But I don't thing it does really matter for your pod or production as soon has the three case are covered up. My initial bug report was that after an hour (!) the pods weren't relocated, seen ok from management soft while host was long enough out of sight.

**Comment by gmarek** [comment]
Yup - this thing was certainly a bug, but many things changed since then. We certainly have a bug with similar effects, but I'm not sure if causes are the similar (#11631)

**Comment by bnprss** [comment]
I admit that I didn't test again the pod eviction after time out on purpose, but I remembered seen it working on some tests. Oh yes, many parts changed and mostly for the good! :)

To detect host down vs temporarily out of network is somehow an impossible task to conduct with automation on the cloud, you must have some way to check through console link, here it is not so appropriate. 
I see there one option that can handle that nicely : 
- Two way check, kube-controller is checking for node presence and on the node part if no check occurred since a while, kubelet try to reach neighborhood, on failure kubelet assume then it is isolated and must kill pods and *release persistent disks*.

**Comment by gmarek** [comment]
Yeah - I don't think we want to get this fancy. It'll likely end up completely different on various cloud providers (it's hard, if not impossible, to say what 'a neighborhood is). As for PDs - I don't think that they care if one of the readers is unresponsive, and if it was a single writer it's unlikely that Kubelet can release anything on it's own (as it has no connection to cloud whatsoever)

**Comment by bnprss** [comment]
Oh you're right, I'm not using network file systems so I completely missed them. For attached not shareable disks like gce_pd there might be an external dissociation through API? :) It seems over-complicated but cover a need. I saw many times pods just waiting for ever it's gce_pd, sadly I had no time to get on this.

In case of network related issue there is a nice list of neighbor already check-able: the other nodes of the cluster for example or svc endpoint (but it's a really bad idea).

**Comment by gmarek** [comment]
I believe this is solved by #12962 and things around this.

**Comment by mtbbiker** [comment]
I believe this is still Issue. Just tested this, when I shutdown the VM (I am running CoreOS on VMWare)

My Pods on that Node (in NotReady state) still show Running and the after 10min it is not yet re-created at a different Node (Pods are create from a ReplicationController)

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+coreos.0", GitCommit:"3ed7d0f453a5517245d32a9c57c39b946e578821", GitTreeState:"clean", BuildDate:"2017-01-13T00:23:19Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by gmarek** [comment]
If it was only Node then yes - NC won't evict anything if all Nodes are not ready (you can look into controller-manager's logs to see what's happening).

Another option is that those Pods were daemons - NC doesn't touch DaemonSets.

**Comment by pytimer** [comment]
Hi, i am a beginner in kubernetes.
I met the similar question in my kubernetes cluster on the five vms.

- Kubernetes version: `v1.11.0`
- OS: CentOS Linux release 7.5.1804 (Core)

Cluster have three masters and two nodes, when i shutdown master3 and two nodes, some pods status  `NodeLost`, but other pods still `Running`,  Why? 

I describe one pod, Conditions Ready is `False`, and service endpoint already delete this pod ip.

`kubectl get nodes`

```
NAME                 STATUS     ROLES     AGE       VERSION
master1              Ready      master    6d        v1.11.0
master2              Ready      master    6d        v1.11.0
master3              NotReady   master    6d        v1.11.0
node.9cb7            NotReady   <none>    21h       v1.11.0
node1                NotReady   <none>    6d        v1.11.0
```
