### ISSUE TITLE
pull-kubernetes-e2e-gce-100-performance fails

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#83493]
**Which jobs are failing**:
pull-kubernetes-e2e-gce-100-performance

**Since when has it been failing**:
Oct 3rd

**Testgrid link**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/83420/pull-kubernetes-e2e-gce-100-performance/1179968141170577408/

**Reason for failure**:
This seems related:
```
W1004 04:13:55.503] ERROR: (gcloud.compute.routers.create) Quota 'ROUTERS' exceeded.  Limit: 10.0 globally.
```

**Comment by harshit2000** [comment]
the label is declared?

**Comment by liggitt** [comment]
see https://github.com/kubernetes/test-infra/issues/14611, fixed in https://github.com/kubernetes/test-infra/pull/14598

**Comment by tedyu** [comment]
The test still fails constantly today:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/83489/pull-kubernetes-e2e-gce-100-performance/1181252864643698688/

**Comment by quinton-hoole** [comment]
Yes, @liggitt it seems that https://github.com/kubernetes/test-infra/pull/14598 did not in fact fix this problem.  See also https://github.com/kubernetes/kubernetes/pull/79264#issuecomment-539150087

cc @BenTheElder

**Comment by BenTheElder** [comment]
> https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/83489/pull-kubernetes-e2e-gce-100-performance/1181252864643698688/

that has no logs which is a different issue, that means the job didn't start (infra flake, not sure what retroactively, we've cleaned up the resources by now...)

if you look at the job history:
https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-100-performance

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce-100-performance

it's definitely having some issues, but not always failing.

> Yes, @liggitt it seems that kubernetes/test-infra#14598 did not in fact fix this problem. See also #79264 (comment)

if fixed it ish, there may be some lingering projects that were in a "clean" state but were cleaned without covering routers. when that happens should fail once and then be fixed.

the new job that was 100% always leaking routers (cluster-api) has also theoretically been fixed to at least try not to do that.

**Comment by tedyu** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/83489/pull-kubernetes-e2e-gce-100-performance/1181280422470881280/

Another instance

**Comment by BenTheElder** [comment]
did some more digging, `pull-kubernetes-e2e-gce-100-performance` does not use boskos to lease projects and instead uses a fixed project name (along with some other presubmits).

this is an anti-pattern. in any case, I've sent a request to triple the quota, but I'm going to say this is a sig-scalability issue, IF we are going to continue to use a special project then it should have quota matching the limits placed on concurrency of jobs using it.

/sig scalability

**Comment by BenTheElder** [comment]
the specific project is `k8s-presubmit-scale`, if you search test-infra for this you'll find a number of jobs using this fixed project.

it should have quota for 30 now, but I don't know how many are reasonably required.

**Comment by BenTheElder** [comment]
I'm going to keep an eye on this intermittently for a while the night since I have access to it... we're currently at 13/30 routers in that project.

**Comment by tedyu** [comment]
Thanks, @BenTheElder

**Comment by krzyzacy** [comment]
We are actually cleaning up routers in https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/maintenance-pull-scale-janitor/1181421358874103812/

It's just not enough quota to fit all presubmits

**Comment by BenTheElder** [comment]
yeah, I suspect we weren't using routers at some point and now need them. I don't now how many though.

so far we've peaked at 16/30 across my non-scientific sampling. I expect we'd hit higher numbers during actual peak usage, but I'm not sure how high.

**Comment by krzyzacy** [comment]
(we probably added a test that depend on routers, so, my guess is 1 per presubmit run, also, I suspect the test is not cleaning up after itself :-) )

**Comment by krzyzacy** [comment]
taking it back - this is when we provisioning the cluster

**Comment by mm4tt** [comment]
Thanks, Folks!

Copying what I said on Slack:

Setting the quota to 30 should be enough for now. The max parallelism (# tests running simultaneously) on this project is ~25  and each test creates a single router.
We're actively working on migrating our presubmits to boskos and hopefully will have it done within the next few weeks. Boskos will help us avoiding such issues in the future.

**Comment by spiffxp** [comment]
Ping on this @mm4tt, have we migrated to boskos?

**Comment by mm4tt** [comment]
Sorry, lost this bug from my radar. We have migrated to boskos in https://github.com/kubernetes/perf-tests/issues/650, we can close this one.
