### ISSUE TITLE
CSI VolumeAttachment slows pod startup time as # concurrent attaches increases

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#84169]
**What happened**:

A reporter testing their CSI driver at scale noticed issues:

Specifically they reported that the pod startup time is impacted by the number of concurrent CSI volume attachments in progress across a cluster.

According to the reporter, the pod start up time jumps from order of seconds (when there are a few volume attachments happening concurrently), to 1-2 minutes once there are >1300 concurrent volume attachments for pods using those attachments.

Similarly the reporter indicates that volume detach operations jump from order of seconds (when there are a few volume attach/detach operations happening concurrently), to 3-4 minutes once there are >1300 concurrent volume attachments.

The reporter mentioned that the slowness, once it is encountered, does not go away until the number of concurrent volume attaches is reduced below <500.

**What you expected to happen**:

Ideally, as the number of CSI volume attachments started in parallel increases the time it takes to start pods remains constant. We should identify the bottle necks and remove as many as possible.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

/sig storage
/sig scalability
/priority important-soon
CC @msau42

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by msau42** [comment]
There are a number of different potential bottlenecks to explore:
* K8s attach-detach controller concurrency. The workqueue uses the [default rate limiter](https://github.com/kubernetes/client-go/blob/master/util/workqueue/default_rate_limiters.go#L39:6).  Needs further investigation to understand how that translates into concurrent requests.
* csi-attacher sidecar concurrency: You can try setting "--worker-threads" in the sidecar to increase concurrency
* K8s API server throttling

@kubernetes/sig-storage-feature-requests

**Comment by tedyu** [comment]
It would be helpful to get snapshot of go routines in the controller manager and api server during the long start up.

Thanks

**Comment by cduchesne** [comment]
@msau42 with regards to csi-attacher sidecar, I have not observed any issues with performance here. As soon as a volumeattachment object changes, the csi-attacher sidecar notices and reacts immediately. Average time to complete a request for csi-attacher is under 2 seconds.

When cluster has many volumeattachments objects  (>1300 and not in-flight reqeusts) the time for any attach or detach action to take place is usually over a minute. A new pod created with a PVC may result in a new volumeattachment object not being created for more than a minute after pod is scheduled to a node. When the volumeattachment object shows up, the csi-attacher processes immediately.

When removing existing pods while in this state, the speed of volume detaches is also heavily reduced. If I delete 10 pods with PVCs, the csi-attach controller may only attempt to process 1 request every 30 seconds to a minute.

There is certainly a bottleneck being hit somewhere, with my guess being somewhere in the attach-detach controller itself.

**Comment by cduchesne** [comment]
Looking through [csi_plugin.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_plugin.go#L52), I see that somewhat recently, `csiTimeout` was changed from 15sec to 2min. This could explain why I've noticed in some clusters, very rarely attachments even happening after a while (if there is indeed throttling). Trying to reproduce these issues in 1.14.8, I have noticed that attachments are more likely to succeed, although still very slow when a lot of activity has taken place, especially so if there are many active volumeattachment objects.

For detaches, it is also very slow, and I notice that the timeout is only [10 seconds](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_attacher.go#L396) still.

I'm not suggesting these timeouts should be increased, but without reduced api usage, they certainly volume attaches/detaches make things more successful.

I only looked for a few minutes, however there may be quite a few more places where this adds to the problem.

**Comment by saad-ali** [comment]
@cduchesne did some great debugging on this. Here is what he found:
* Kubernetes volume layer has code to periodically verify that volumes are attached.
* It triggers every minute by default.
* For CSI, the Kubernetes volume code has NOT implemented "bulk verify volume attach", so kubernetes falls back to calling verify volumes attached PER NODE.
* The Kubernetes CSI code fetches a `VolumeAttachment` FOR EVERY ATTACHED VOLUME on the specified node as part of `VolumesAreAttached(...)` to check that it is verified.

https://github.com/kubernetes/kubernetes/blob/037751e7ad2cd18db5b4e2a20ba894314c522b15/pkg/volume/csi/csi_attacher.go#L199

For clusters with many nodes/attached volumes, this results in so many calls to fetch `VolumeAttachment` from the Kubernetes API server, that the kube-controller-manager starts to get throttled (as reported).

If you encounter this, as a short-term work around, try one of the following:
* Set `disable-attach-detach-reconcile-sync` flag on the kube-controller-manager to `true`.
  * This would completely disable the feature where k8s periodically verifies that the volumes that it thinks are attached are actually attached.
  * For now this should be safe because although the k8s side checks the VolumeAttachment, the CSI `external-attacher` object doesn't periodically update the VolumeAttachment object (https://github.com/kubernetes/kubernetes/issues/79743 to fix that.)
* Set the `attach-detach-reconcile-sync-period` value to a longer period (longer then 1 minute).
  * This flag controls the frequency of the verification. The default value is 1 minute. If you find that you really need the feature, you could keep it on and increase the frequency to mitigate this issue.

Longer term, plan:
* Fix https://github.com/kubernetes/kubernetes/issues/79743
  * @davidz627 extended CSI spec in CSI v1.2.0 (see [PR #374](https://github.com/container-storage-interface/spec/pull/374)) so that the `external-attacher` can update the `VolumeAttachment` objects periodically in an efficient manner.
* Fix this issue by, ideally, finding a way to implement `BulkVerifyVolumes` for CSI or, at least, fix the existing `VolumesAreAttached(...)` CSI implementation to "list" instead of "get" for every `VolumeAttachment` object.

**Comment by davidz627** [comment]
> Set disable-attach-detach-reconcile-sync flag on the kube-controller-manager to true.

Would recommend this method since #79743 means that the sync is not actually doing anything. Until this is resolved the VerifyVolumesAttached for CSI is just wasting resources.

**Comment by saad-ali** [comment]
Chris pointed out another bottleneck.

https://github.com/kubernetes/kubernetes/blob/3f402534f303f018f02be15f6f5d8a0add391563/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L586

The A/D controller DSW populator periodically fetches all PV objects. This should be done through an informer as well.

**Comment by msau42** [comment]
I feel like the kubelet DSW populator intentionally doesn't use an informer but don't remember the reason why. cc @gnufied @jsafrane do you remember?

**Comment by cduchesne** [comment]
Is it possibly for security reasons to only request resources it is allowed to access?

**Comment by msau42** [comment]
NodeAuthorizer should restrict kubelet access to PVs to only those used by pods scheduled to that node. https://kubernetes.io/docs/reference/access-authn-authz/node/

**Comment by msau42** [comment]
(also I just answered my own question. NodeAuthorizer prevents kubelet from using informers on those restricted objects, because informers have to List)

**Comment by cduchesne** [comment]
What I've noticed with the kubelet pv.get and pvc.get loops, is that if there are a lot of volumes mounted, pods don't start for 1-3 minutes because the kubelet is waiting to have processed required PVCs before starting the pod. The kubelet will even report an error because it was waiting so long in some cases:

```
  Normal   Scheduled               3m14s  default-scheduler        Successfully assigned test/redis062-58d95b9b48-gq2l5 to andromeda
  Normal   SuccessfulAttachVolume  3m11s  attachdetach-controller  AttachVolume.Attach succeeded for volume "usrno1-1fc2de4cf41b11e99b45"
  Normal   SuccessfulAttachVolume  3m10s  attachdetach-controller  AttachVolume.Attach succeeded for volume "usrno1-1f7c5f2cf41b11e99b45"
  Normal   SuccessfulAttachVolume  3m10s  attachdetach-controller  AttachVolume.Attach succeeded for volume "usrno1-1faaf5c6f41b11e99b45"
  Normal   SuccessfulAttachVolume  3m10s  attachdetach-controller  AttachVolume.Attach succeeded for volume "usrno1-1f63c0bcf41b11e99b45"
  Normal   SuccessfulAttachVolume  3m9s   attachdetach-controller  AttachVolume.Attach succeeded for volume "usrno1-1f940170f41b11e99b45"
  Warning  FailedMount             71s    kubelet, andromeda       Unable to mount volumes for pod "redis062-58d95b9b48-gq2l5_test(1b56e92a-f6bc-11e9-aa68-0cc47ac6c23c)": timeout expired wai
ting for volumes to attach or mount for pod "test"/"redis062-58d95b9b48-gq2l5". list of unmounted volumes=[data01 data02 data03 data04 data05 default-token-qjlqx]. list of unattached volumes
=[data01 data02 data03 data04 data05 default-token-qjlqx]
  Normal   Pulling                 4s     kubelet, andromeda       Pulling image "redis"
  Normal   Pulled                  2s     kubelet, andromeda       Successfully pulled image "redis"
  Normal   Created                 2s     kubelet, andromeda       Created container redis062
  Normal   Started                 2s     kubelet, andromeda       Started container redis062
```

**Comment by tedyu** [comment]
For the code Chris pointed out in DSW populator, how about adding a cache (with short TTL) ?
If there is hit in the cache, use the PV object from cache.

**Comment by msau42** [comment]
I think we required kubelet to do an API lookup during admission for StorageInUseProtection feature, to prevent a race with the PV object being stale. But I think the normal volumemanager workflow doesn't periodically reconcile PVs

I think we added a reconciling control loop for online resizing feature. Maybe that is what is causing the issue.

**Comment by davidz627** [comment]
In `v2.1.0` of the `external-attacher` I implemented a check that will actually reconcile backend volume attach state with the expected state in the `VolumeAttachment` object.

I considered removing the csi `VerifyVolumesAttached` check in the in-tree plugin entirely but it continues to serve one purpose of recreating the `VolumeAttachment` object itself if it was accidentally deleted. It's open for debate whether that check is worth the additional load on the API server it generates. To lean on the conservative side I'd say we could keep it since it can be manually disabled for larger clusters - but the default experience is not going to be good. The amount of cluster configs this saves vs the toil on the system may not be worth it. However, it may be worth exploring if changing the `VolumeAttachment` API `GET` call is changed to use an informer is able to reduce the apiserver load to an acceptable level.

Here is the `GET` I am referring to (triggers one API Server GET per attachment across the cluster every minute by default): https://github.com/kubernetes/kubernetes/blob/92f8a31f15aedbdaf957eafcc4b72f234553cf38/pkg/volume/csi/csi_attacher.go#L200



/remove-lifecycle stale

**Comment by dimm0** [comment]
I tried the recent 2.1.1 attacher, and the problem still exists...
Also increased the reconsile time to 10 mins
Is there any solution now?

**Comment by davidz627** [comment]
@dimm0 which CSI driver are you using? Does it implement `LIST_VOLUMES_PUBLISHED_NODES` capability?

**Comment by dimm0** [comment]
https://github.com/cernops/cvmfs-csi

> Does it implement LIST_VOLUMES_PUBLISHED_NODES capability?

It does not. I'll see how to implement one, thanks!
(If you could send some example, that would be helpful)

**Comment by davidz627** [comment]
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/392 :)

**Comment by dimm0** [comment]
🙏

**Comment by pawanpraka1** [comment]
We are also facing this issue. It is taking almost 3hrs to create Volumeattachment  object. Is there any way to solve this? 

@davidz627, How LIST_VOLUMES_PUBLISHED_NODES will help here, coule you please help me understand both whole work flow of this?

**Comment by msau42** [comment]
I don't think LIST_VOLUMES_PUBLISHED_NODES helps reduce API load. One possible scaling problem that was pointed out earlier is that we do a Get() on every VolumeAttachment every minute. We should change that to use an informer instead. This should greatly reduce API load.

**Comment by msau42** [comment]
@yuga711 is going to work on a fix

**Comment by pawanpraka1** [comment]
thanks @msau42. For now increasing the attach-detach-reconcile-sync-period to 300s helped me. but not sure how as I did not see any log which says that apiserver is throttling the request.

**Comment by jisnardo** [comment]
Hi @saad-ali, **disable-attach-detach-reconcile-sync** still works with kubernetes 1.16.10? I have tried without success.

**Comment by shalini-b** [comment]
@saad-ali Seeing this issue in k8s 1.19 version as well. For now, it got resolved by increasing the `attach-detach-reconcile-sync-period` to `300s`.
