### ISSUE TITLE
Deleted pods may remain in scheduler cache and cause scheduling exception

### ISSUE THREAD

**Issue by renjian52** [kubernetes/kubernetes#85726]
**What happened**:
pod can't be removed from scheduler cache when be deleted,  logs in kube-scheduler is below:

I1128 16:41:50.819639   31593 leaderelection.go:344] lock is held by shaphicpra14907_64ccb0c5-aaa1-435d-a4b4-ead4bb3de63b and has not yet expired
I1128 16:41:50.819678   31593 leaderelection.go:240] failed to acquire lease kube-system/kube-scheduler
I1128 16:41:53.740234   31593 leaderelection.go:344] lock is held by shaphicpra14907_64ccb0c5-aaa1-435d-a4b4-ead4bb3de63b and has not yet expired
I1128 16:41:53.740365   31593 leaderelection.go:240] failed to acquire lease kube-system/kube-scheduler
I1128 16:41:57.734692   31593 leaderelection.go:245] successfully acquired lease kube-system/kube-scheduler
I1128 16:41:57.834958   31593 shared_informer.go:176] caches populated
E1128 16:42:11.731020   31593 eventhandlers.go:226] scheduler cache UpdatePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not added to scheduler cache, so cannot be updated
E1128 16:42:12.339189   31593 eventhandlers.go:226] scheduler cache UpdatePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not added to scheduler cache, so cannot be updated
E1128 16:42:12.345323   31593 eventhandlers.go:226] scheduler cache UpdatePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not added to scheduler cache, so cannot be updated
E1128 16:42:20.628894   31593 eventhandlers.go:226] scheduler cache UpdatePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not added to scheduler cache, so cannot be updated
E1128 16:42:20.632578   31593 eventhandlers.go:254] scheduler cache RemovePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not found in scheduler cache, so cannot be removed from it

**What you expected to happen**:

pod in scheduler cache can be deleted successfully when pod is deleted

**How to reproduce it (as minimally and precisely as possible)**:

main steps to reproduce this bug is these:
1. two scheduler run in leader-elect=true mode，schedulerA is the leader scheduler, and schedulerB is an assistant.
2. create pod1 with "namespace1/name1" and it runs on Node1
3. break down the network between schedulerB and kube-apiserver
4. delete pod1 and create pod2 with same name, ie "namespace1/name1" and pod2 been assigned to Node1 by schedulerA again.
5. turn off schedulerA and recover the network between schedulerB and kube-apiserver, and then schedulerB become the leader scheduler.
6. delete pod2. this time log in schedulerB will print this: 

E1128 16:42:11.731020   31593 eventhandlers.go:226] scheduler cache UpdatePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not added to scheduler cache, so cannot be updated
E1128 16:42:20.632578   31593 eventhandlers.go:254] scheduler cache RemovePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not found in scheduler cache, so cannot be removed from it

7. At this time, if I create a new pod3 with podAntiAffinity to pod1. the result is pod3 can't been assigned to Node1 because pod1 is still in schedulerB's scheduler cache.

**Anything else we need to know?**:

the reason of this bug is below:

since PR(https://github.com/kubernetes/kubernetes/pull/61069), podKey in scheduler cache use pod's UID instead of namespace/name
however, the key in SharedIndexInformer still use namespace/name
in this upper case, delete the pod and create a same name pod may be delivered as one update notification.( see disscusion： https://github.com/kubernetes/kubernetes/issues/83810)
scheduler received pod update notification and then print below log.

E1128 16:42:11.731020   31593 eventhandlers.go:226] scheduler cache UpdatePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not added to scheduler cache, so cannot be updated
 

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Huang-Wei** [comment]
@renjian52 Since #83810 has been marked resolved (fix available in 1.17), does that mean this issue is expected to go away in 1.17? Could you please give a try?

**Comment by renjian52** [comment]
@Huang-Wei , fix for https://github.com/kubernetes/kubernetes/issues/83810 just resolved the case add event may be lost after deletion event. It doesn't solve the problem that  a delete followed by an add may be delivered as one update notification and it's thought normal from MikeSpreitzer's comment. The main cause of this problem is scheduler cache use Pod UID as key while sharedInformer use namespace/name. 
Still, I also test with the latest kubernetes code. The bug of this issue reappeared.

**Comment by Huang-Wei** [comment]
Thanks @renjian52. I added a comment in the PR, and a test is necessary to reproduce the issue and verify the fix.

**Comment by renjian52** [comment]
I signed it

**Comment by Huang-Wei** [comment]
/remove-lifecycle stale

ping @renjian52 there is an unresolved comment in the PR, would you got a chance to take a look?
