### ISSUE TITLE
[Failing Test] capg-conformance-stable-k8s-master (ci-cluster-api-provider-gcp-make-conformance-stable-k8s-ci-artifacts)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#87782]
**Which jobs are failing**:

`capg-conformance-stable-k8s-master (ci-cluster-api-provider-gcp-make-conformance-stable-k8s-ci-artifacts)`

**Which test(s) are failing**:

`Overall`

**Since when has it been failing**:

`3rd Feb 03:07 PST`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-stable-k8s-master

**Reason for failure**:
```
cluster.cluster.x-k8s.io "test1" deleted
Error from server (NotFound): clusters.cluster.x-k8s.io "test1" not found
kind delete cluster --name=clusterapi || true
{"component":"entrypoint","file":"prow/entrypoint/run.go:164","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","time":"2020-02-03T07:04:41Z"}
Deleting cluster "clusterapi" ...
ERROR: (gcloud.compute.forwarding-rules.delete) Could not fetch resource:
 - The resource 'projects/k8s-jkns-gci-gce-reboot-1-2/global/forwardingRules/test1-apiserver' was not found
```

**Anything else we need to know**:
/cc @kubernetes/ci-signal
/cc @justinsb @timothysc

/milestone v1.18
/sig cluster-lifecycle
/priority critical-urgent

**Comment by neolit123** [comment]
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cluster-api-provider-gcp-make-conformance-stable-k8s-ci-artifacts/1224332673900613638/build-log.txt

```
# Apply addons on the target cluster, waiting for the control-plane to become available.
bin/clusterctl \
	alpha phases apply-addons -v=3 \
	--kubeconfig=./kubeconfig \
	-a examples/addons.yaml
...
F0203 14:38:34.999628   16913 alpha_phase_apply_addons.go:50] unable to create cluster client: failed to acquire new client: timed out waiting for the condition
make: *** [Makefile:278: create-cluster] Error 1
```

unless i'm wrong clusterctl is built from the master of the k-sigs/cluster-api repo, so this could be a regression in the tool:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cluster-api-provider-gcp-make-conformance-stable-k8s-ci-artifacts/1224332673900613638/clone-log.txt

**Comment by ncdc** [comment]
That's not clusterctl from master

**Comment by ncdc** [comment]
The workload cluster's apiserver didn't come up / wasn't reachable...

**Comment by ncdc** [comment]
cloud init output shows it couldn't pull the CI images. https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cluster-api-provider-gcp-make-conformance-stable-k8s-ci-artifacts/1224378227712069633/artifacts/logs/test1-controlplane-0/cloud-init-output.log

```
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image gcr.io/kubernetes-ci-images/kube-apiserver:v1.18.0-alpha.2.353_4c3aa3f26b8492: output: time="2020-02-03T17:29:43Z" level=fatal msg="pulling image failed: rpc error: code = NotFound desc = failed to pull and unpack image \"gcr.io/kubernetes-ci-images/kube-apiserver:v1.18.0-alpha.2.353_4c3aa3f26b8492\": failed to resolve reference \"gcr.io/kubernetes-ci-images/kube-apiserver:v1.18.0-alpha.2.353_4c3aa3f26b8492\": gcr.io/kubernetes-ci-images/kube-apiserver:v1.18.0-alpha.2.353_4c3aa3f26b8492: not found"
, error: exit status 1
...
```

**Comment by neolit123** [comment]
> That's not clusterctl from master

oddly, i see it fetching k-sigs/cluster-api from master and no branch or commit checkouts after that.

**Comment by ncdc** [comment]
This failure was the same for the 2 most recent runs

**Comment by ncdc** [comment]
While it does fetch cluster-api master, it builds clusterctl using the version of cluster-api in capg's go.mod file, which is from v1alpha2

**Comment by ncdc** [comment]
I assume this issue will auto resolve once the test isn't trying to use CI artifacts that are missing.

@dims do you know why https://dl.k8s.io/ci/latest-green.txt sometimes yields a version from CI that either doesn't exist or at least the docker images aren't there?

**Comment by neolit123** [comment]
most of the labels seem to point at 355, but this api-server image is not there yet:
https://console.cloud.google.com/gcr/images/kubernetes-ci-images/GLOBAL/kube-apiserver?gcrImageListsize=30

the only reliable label seems to be:
https://storage.cloud.google.com/kubernetes-release-dev/ci/k8s-master.txt

**Comment by neolit123** [comment]
the issue is logged here: https://github.com/kubernetes/release/issues/897

**Comment by ncdc** [comment]
Do we need to update the capa & capg jobs to use the URL you listed?

**Comment by neolit123** [comment]
ci/latest.txt and the rest of the "latest" labels used to work, therefore this is a regression in the build tooling.

but yes, i do recommend for the time being:
https://storage.cloud.google.com/kubernetes-release-dev/ci/k8s-master.txt

**Comment by ncdc** [comment]
@neolit123 it looks like the URL you gave isn't something you can just `curl`. I think you have to be logged in to gcloud to get it?

**Comment by neolit123** [comment]
should be accessible with this too:
https://dl.k8s.io/ci/k8s-master.txt

**Comment by ncdc** [comment]
CAPA master PR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1515
CAPA 0.4 PR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1516

GCP master PR: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/282
GCP 0.2 PR: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/283

**Comment by ncdc** [comment]
@hasheddan this should be resolved now

**Comment by hasheddan** [comment]
Thanks for the quick resolution @ncdc! Looks like we are still seeing some flakes on this test, but not related to this problem. I’ll open a separate issue to track that.

/close
