### ISSUE TITLE
"SHOULD NOT HAPPEN" should not happen

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#88182]
Seen in the KIND e2e test: 

```
2020-02-14T23:57:17.149523077Z stderr F E0214 23:57:17.145040       1 structuredmerge.go:102] [SHOULD NOT HAPPEN] failed to create typed new object of type apps/v1, Kind=Deployment: .spec.template.spec.containers[name="httpd"].env: duplicate entries for key [name="A"]
2020-02-14T23:57:17.166960149Z stderr F E0214 23:57:17.166281       1 structuredmerge.go:102] [SHOULD NOT HAPPEN] failed to create typed new object of type apps/v1, Kind=Deployment: .spec.template.spec.containers[name="httpd"].env: duplicate entries for key [name="A"]
2020-02-14T23:57:17.182220465Z stderr F E0214 23:57:17.181242       1 structuredmerge.go:102] [SHOULD NOT HAPPEN] failed to create typed new object of type apps/v1, Kind=Deployment: .spec.template.spec.containers[name="httpd"].env: duplicate entries for key [name="A"]
```

a) maybe we shouldn't log this more than 1x per second or something?
b) maybe the error could make it clearer that the problem is the user's data?
c) maybe we could fix the test triggering this?

/sig api-machinery
/wg apply

Logs that I saw this in: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/88177/pull-kubernetes-e2e-kind/1228463295606820865/artifacts/logs/kind-control-plane/pods/kube-system_kube-apiserver-kind-control-plane_08a7fd62a1b3bb0f98714e7546afd587/kube-apiserver/0.log

**Comment by lavalamp** [comment]
@jennybuckley

**Comment by tedyu** [comment]
The 'duplicate entries for key' error came from validatingObjectWalker#visitListItems.

**Comment by apelisse** [comment]
Yeah, they have multiple environment variables with the same name. I don't think that should be an error though ...

**Comment by apelisse** [comment]
At the same time, it's not really useful to have multiple times the same variable and is probably a recipe for trouble.

**Comment by lavalamp** [comment]
It's definitely user error. Spamming apiserver logs about it doesn't help things, though.

**Comment by apelisse** [comment]
> a) maybe we shouldn't log this more than 1x per second or something?

I don't want to hide it, it's really not supposed to happen :-)

> b) maybe the error could make it clearer that the problem is the user's data?

it's not really user-data though. The fact that the error triggers here rather than in the actual validation means that there is a discrepancy between our validation and the regular validation. That's probably a problem that *we* have to fix. In that specific example, we can see that Kubernetes  allows multiple environment variable with the same name, while *we* have assumed that it's not OK. It's a very legitimate error and we have to think about it to fix it.

> c) maybe we could fix the test triggering this?

I think the test is relevant, and people out there are doing that. We could consider doing ratcheting if we want to stop allowing multiple variables, but I don't think that's how we want to fix that problem.

**Comment by php-coder** [comment]
> a) maybe we shouldn't log this more than 1x per second or something?

For history: #88600 should fix that.

**Comment by apelisse** [comment]
We've definitely improved that, maybe let's close it for now.

**Comment by sttts** [comment]
/reopen

We still see this happening. Kube users get nervous, I would too. Please fix the root cause.
