### ISSUE TITLE
No new tags on staging repos after v0.18.0-alpha.2

### ISSUE THREAD

**Issue by ibuildthecloud** [kubernetes/kubernetes#88376]
I'm not seeing any tags on staging repos like github.com/kubernetes/api newer than v0.18.0-alpha.2.  Specifically I'm looking for v0.18.0-beta.0.

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/issues/56876 https://github.com/kubernetes/publishing-bot/issues/217

**Comment by liggitt** [comment]
This is now resolved

**Comment by ibuildthecloud** [comment]
/reopen

Thanks, but it's seems to be partially fixed.  There are more tags, but v1.18.0-beta.0 is still missing https://github.com/kubernetes/api/tree/v0.18.0-beta.0

**Comment by liggitt** [comment]
Ah. The bot is fixed, but the 1.18 branch was created in the meantime, and https://github.com/kubernetes/kubernetes/blob/master/staging/publishing/rules.yaml hasn't been updated to sync those branches yet (which is where the 1.18 beta tags are)

**Comment by liggitt** [comment]
https://github.com/kubernetes/api/releases/tag/v0.18.0-beta.0 is now published

**Comment by ibuildthecloud** [comment]
Thanks!
