### ISSUE TITLE
3 e2e tests are currently flaky - debug what's happening

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#9312]
Run from the master head (but see https://github.com/GoogleCloudPlatform/kubernetes/issues/9312#issuecomment-110383138 below for more general flakyness stats):
```
Summarizing 5 Failures:

[Fail] Pod Disks [It] should schedule a pod w/ a readonly PD on two hosts, then remove both. 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:170

[Fail] Density [BeforeEach] [Performance suite] should allow starting 30 pods per node 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/density.go:63

[Fail] Pod Disks [It] should schedule a pod w/ a RW PD, remove it, then schedule it on another host 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:105

[Fail] Docker Containers [It] should be able to override the image's default command and arguments 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:645

[Fail] Density [BeforeEach] [Performance suite] should allow starting 3 pods per node 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/density.go:63
```

@quinton-hoole

**Comment by brendandburns** [comment]
for PD there is a known bug:

https://github.com/GoogleCloudPlatform/kubernetes/issues/9190

That can definitely cause the PD tests to fail.

**Comment by quinton-hoole** [comment]
The following 18 e2e tests are currently flaky:

1. Cluster level logging using Elasticsearch should check that logs from pods on all nodes are ingested into Elasticsearch (Failed 5 times in the last 30 runs. Stability: 83 %)
2. Density [Performance suite] should allow starting 30 pods per node (Failed 13 times in the last 30 runs. Stability: 56 %)
3. Etcd failure should recover from SIGKILL (Failed 5 times in the last 30 runs. Stability: 83 %)
4. Pod Disks should schedule a pod w/ a RW PD, remove it, then schedule it on another host (Failed 10 times in the last 30 runs. Stability: 66 %)
5. Pod Disks should schedule a pod w/ a readonly PD on two hosts, then remove both. (Failed 10 times in the last 30 runs. Stability: 66 %)
6. Services should be able to change the type and nodeport settings of a service (Failed 2 times in the last 30 runs. Stability: 93 %)
7. Services should be able to create a functioning external load balancer (Failed 1 times in the last 30 runs. Stability: 96 %)
8. Services should correctly serve identically named services in different namespaces on different external IP addresses (Failed 1 times in the last 30 runs. Stability: 96 %)
9. Services should release the load balancer when Type goes from LoadBalancer -> NodePort (Failed 1 times in the last 30 runs. Stability: 96 %)
10. DNS should provide DNS for the cluster (Failed 1 times in the last 30 runs. Stability: 96 %)
11. Density [Performance suite] should allow starting 3 pods per node (Failed 2 times in the last 30 runs. Stability: 93 %)
12. Docker Containers should be able to override the image's default commmand (docker entrypoint) (Failed 1 times in the last 30 runs. Stability: 96 %)
13. Docker Containers should use the image defaults if command and args are blank (Failed 1 times in the last 30 runs. Stability: 96 %)
14. Etcd failure should recover from SIGKILL (Failed 12 times in the last 30 runs. Stability: 60 %)
15. Networking should function for intra-pod communication (Failed 1 times in the last 30 runs. Stability: 96 %)
16. Nodes Network should survive network partition. (Failed 4 times in the last 20 runs. Stability: 80 %)
17. Services should be able to create a functioning NodePort service (Failed 1 times in the last 30 runs. Stability: 96 %)
18. hostDir should support r/w on tmpfs (Failed 1 times in the last 30 runs. Stability: 96 %)

**Comment by quinton-hoole** [comment]
@brendandburns FYI, as per discussion yesterday.

**Comment by brendandburns** [comment]
For the PD issue, at least part of it is that we're over-scheduling the cluster:
```
Giving up; pod went into failed status: 
    (*api.Pod){TypeMeta:(api.TypeMeta){Kind:(string) APIVersion:(string)} ObjectMeta:(api.ObjectMeta){Name:(string)pd-test-a4915905-0f6b-11e5-b83a-42010af01555 GenerateName:(string) Namespace:(string)default SelfLink:(string)/api/v1/namespaces/default/pods/pd-test-a4915905-0f6b-11e5-b83a-42010af01555 UID:(types.UID)a491d93b-0f6b-11e5-a7de-42010af0d8b1 ResourceVersion:(string)251 CreationTimestamp:(util.Time)2015-06-10 05:24:30 -0700 PDT DeletionTimestamp:(*util.Time)<nil> Labels:(map[string]string)<nil> Annotations:(map[string]string)<nil>} Spec:(api.PodSpec){Volumes:([]api.Volume)[{Name:(string)testpd VolumeSource:(api.VolumeSource){HostPath:(*api.HostPathVolumeSource)<nil> EmptyDir:(*api.EmptyDirVolumeSource)<nil> GCEPersistentDisk:(*api.GCEPersistentDiskVolumeSource){PDName:(string)e2e-flaky-a01b8f10-0f6b-11e5-b83a-42010af01555 FSType:(string)ext4 Partition:(int)0 ReadOnly:(bool)false} AWSElasticBlockStore:(*api.AWSElasticBlockStoreVolumeSource)<nil> GitRepo:(*api.GitRepoVolumeSource)<nil> Secret:(*api.SecretVolumeSource)<nil> NFS:(*api.NFSVolumeSource)<nil> ISCSI:(*api.ISCSIVolumeSource)<nil> Glusterfs:(*api.GlusterfsVolumeSource)<nil> PersistentVolumeClaimVolumeSource:(*api.PersistentVolumeClaimVolumeSource)<nil> RBD:(*api.RBDVolumeSource)<nil>}} {Name:(string)default-token-d1017 VolumeSource:(api.VolumeSource){HostPath:(*api.HostPathVolumeSource)<nil> EmptyDir:(*api.EmptyDirVolumeSource)<nil> GCEPersistentDisk:(*api.GCEPersistentDiskVolumeSource)<nil> AWSElasticBlockStore:(*api.AWSElasticBlockStoreVolumeSource)<nil> GitRepo:(*api.GitRepoVolumeSource)<nil> Secret:(*api.SecretVolumeSource){SecretName:(string)default-token-d1017} NFS:(*api.NFSVolumeSource)<nil> ISCSI:(*api.ISCSIVolumeSource)<nil> Glusterfs:(*api.GlusterfsVolumeSource)<nil> PersistentVolumeClaimVolumeSource:(*api.PersistentVolumeClaimVolumeSource)<nil> RBD:(*api.RBDVolumeSource)<nil>}}] Containers:([]api.Container)[{Name:(string)testpd Image:(string)gcr.io/google_containers/pause Command:([]string)<nil> Args:([]string)<nil> WorkingDir:(string) Ports:([]api.ContainerPort)<nil> Env:([]api.EnvVar)<nil> Resources:(api.ResourceRequirements){Limits:(api.ResourceList)map[cpu:100m] Requests:(api.ResourceList)<nil>} VolumeMounts:([]api.VolumeMount)[{Name:(string)testpd ReadOnly:(bool)false MountPath:(string)/testpd} {Name:(string)default-token-d1017 ReadOnly:(bool)true MountPath:(string)/var/run/secrets/kubernetes.io/serviceaccount}] LivenessProbe:(*api.Probe)<nil> ReadinessProbe:(*api.Probe)<nil> Lifecycle:(*api.Lifecycle)<nil> TerminationMessagePath:(string)/dev/termination-log ImagePullPolicy:(api.PullPolicy)IfNotPresent SecurityContext:(*api.SecurityContext)<nil>}] RestartPolicy:(api.RestartPolicy)Always TerminationGracePeriodSeconds:(*int64)<nil> ActiveDeadlineSeconds:(*int64)<nil> DNSPolicy:(api.DNSPolicy)ClusterFirst NodeSelector:(map[string]string)<nil> ServiceAccount:(string)default NodeName:(string)e2e-flaky-minion-u3kz HostNetwork:(bool)false ImagePullSecrets:([]api.LocalObjectReference)<nil>} Status:(api.PodStatus){Phase:(api.PodPhase)Failed Conditions:([]api.PodCondition)<nil> Message:(string)Pod cannot be started due to exceeded capacity HostIP:(string) PodIP:(string) StartTime:(*util.Time)2015-06-10 05:24:30 -0700 PDT ContainerStatuses:([]api.ContainerStatus)<nil>}}
not to have occurred
```

As a stop the bleeding, we should drop the CPU resource requirement from the PD test, it doesn't contribute one way or the other.

However, we should also see why we are apparently over-committing a Node, that should only happen in really rare race conditions.

--brendan

**Comment by quinton-hoole** [comment]
Updated status:

The following 23 e2e tests are currently flaky (in increasing order of stability):

1. Pod Disks should schedule a pod w/ a RW PD, remove it, then schedule it on another host (Failed 30 times in the last 30 runs. Stability: 0 %) #7972 
1. Pod Disks should schedule a pod w/ a readonly PD on two hosts, then remove both. (Failed 30 times in the last 30 runs. Stability: 0 %) #7972 
1. Nodes Network should survive network partition. (Failed 30 times in the last 30 runs. Stability: 0 %) #9487 
1. Reboot each node by dropping all inbound packages for a while and ensure they function afterwards (Failed 7 times in the last 30 runs. Stability: 76 %) #9062 
1. Reboot each node by dropping all outbound packages for a while and ensure they function afterwards (Failed 6 times in the last 30 runs. Stability: 80 %) #9062 
1. Reboot each node by ordering unclean reboot and ensure they function upon restart (Failed 4 times in the last 30 runs. Stability: 87 %)
1. Services should release the load balancer when Type goes from LoadBalancer -> NodePort (Failed 4 times in the last 30 runs. Stability: 87 %)
1. Services should be able to change the type and nodeport settings of a service (Failed 3 times in the last 30 runs. Stability: 90 %) #8892 
1. Reboot each node by triggering kernel panic and ensure they function upon restart (Failed 1 times in the last 30 runs. Stability: 97 %) #9062 
1. Cluster level logging using Elasticsearch should check that logs from pods on all nodes are ingested into Elasticsearch (Failed 2 times in the last 30 runs. Stability: 93 %) #9486 
1. Reboot each node by switching off the network interface and ensure they function upon switch on (Failed 2 times in the last 30 runs. Stability: 93 %) #9062 
1. Reboot each node by ordering clean reboot and ensure they function upon restart (Failed 1 times in the last 30 runs. Stability: 97 %) #9062

**Comment by quinton-hoole** [comment]
Updated status:

The following 11 e2e tests are currently flaky (in increasing order of stability):

1. Service endpoints latency should not be very high (Failed 15 times in the last 22 runs. Stability: 31 %)
1. Reboot each node by dropping all outbound packages for a while and ensure they function afterwards (Failed 8 times in the last 30 runs. Stability: 73 %) #9062 
1. Reboot each node by dropping all inbound packages for a while and ensure they function afterwards (Failed 5 times in the last 30 runs. Stability: 83 %) #9062 
1. Cluster level logging using Elasticsearch should check that logs from pods on all nodes are ingested into Elasticsearch (Failed 4 times in the last 30 runs. Stability: 86 %) #9486 
1. Addon update should propagate add-on file changes (Failed 3 times in the last 30 runs. Stability: 90 %)
1. Shell should pass tests for services.sh (Failed 3 times in the last 30 runs. Stability: 90 %)
1. Pod Disks should schedule a pod w/ a readonly PD on two hosts, then remove both. (Failed 3 times in the last 30 runs. Stability: 90 %) #7972  #9830
1. Reboot each node by ordering unclean reboot and ensure they function upon restart (Failed 3 times in the last 30 runs. Stability: 90 %)
1. Reboot each node by triggering kernel panic and ensure they function upon restart (Failed 3 times in the last 30 runs. Stability: 90 %) #9062 
1. Reboot each node by switching off the network interface and ensure they function upon switch on (Failed 3 times in the last 30 runs. Stability: 90 %) #9062 
1. Reboot each node by ordering clean reboot and ensure they function upon restart (Failed 3 times in the last 30 runs. Stability: 90 %) #9062 

Failed only once:
 
1. Etcd failure should recover from SIGKILL (Failed 2 times in the last 30 runs. Stability: 93 %)
1. Services should release the load balancer when Type goes from LoadBalancer -> NodePort (Failed 1 times in the last 30 runs. Stability: 96 %)
1. Docker Containers should use the image defaults if command and args are blank (Failed 1 times in the last 30 runs. Stability: 96 %)
1. EmptyDir volumes should support r/w (Failed 1 times in the last 30 runs. Stability: 96 %)
1. Networking should function for intra-pod communication (Failed 1 times in the last 30 runs. Stability: 96 %)
1. Pods should be restarted with a /healthz http liveness probe (Failed 1 times in the last 30 runs. Stability: 96 %)
1. Proxy version v1beta3 should proxy to cadvisor (Failed 1 times in the last 30 runs. Stability: 96 %)

Formerly Unstable, now stable:

1. Pod Disks should schedule a pod w/ a RW PD, remove it, then schedule it on another host ( (No known failures. Stability 100 %) #7972 #9830
1.Nodes Network Uncontactable nodes, have their pods recreated by a replication controller, and can host new pods after rejoining. (No known failures. Stability 100 %) #9487 
1. Services should be able to change the type and nodeport settings of a service (No known failures. Stability 100 %) #8892

**Comment by quinton-hoole** [comment]
Updated status:

The following 6 e2e tests are currently flaky (in increasing order of stability):

1. Service endpoints latency should not be very high (Failed 24 times in the last 30 runs. Stability: 20 %) #9592
1. Reboot each node by dropping all outbound packets for a while and ensure they function afterwards (Failed 10 times in the last 30 runs. Stability: 66 %) #9062 
1. Reboot each node by dropping all inbound packets for a while and ensure they function afterwards (Failed 4 times in the last 30 runs. Stability: 86 %) #9062 
1. Addon update should propagate add-on file changes (Failed 4 times in the last 30 runs. Stability: 86 %) #10136
1. Shell should pass tests for services.sh (Failed 4 times in the last 30 runs. Stability: 86 %) #10127
1. EmptyDir volumes should support r/w (Failed 2 times in the last 30 runs. Stability: 93 %)

Failed only once:
 
1. Reboot each node by triggering kernel panic and ensure they function upon restart (Failed 1 times in the last 30 runs. Stability: 97 %) #9062 
1. Services should release the load balancer when Type goes from LoadBalancer -> NodePort (Failed 1 times in the last 30 runs. Stability: 96 %)

Formerly Unstable, now stable:

1. Pod Disks should schedule a pod w/ a RW PD, remove it, then schedule it on another host ( (No known failures. Stability 100 %) #7972 #9830
1.Nodes Network Uncontactable nodes, have their pods recreated by a replication controller, and can host new pods after rejoining. (No known failures. Stability 100 %) #9487 
1. Services should be able to change the type and nodeport settings of a service (No known failures. Stability 100 %) #8892 
1. Cluster level logging using Elasticsearch should check that logs from pods on all nodes are ingested into Elasticsearch (Failed 0 times in the last 30 runs. Stability: 100 %) #9486 
1. Pod Disks should schedule a pod w/ a readonly PD on two hosts, then remove both. (Failed 0 times in the last 30 runs. Stability: 100 %) #7972  #9830
1. Reboot each node by ordering unclean reboot and ensure they function upon restart (Failed 0 times in the last 30 runs. Stability: 100 %) #9062 
1. Reboot each node by switching off the network interface and ensure they function upon switch on (Failed 0 times in the last 30 runs. Stability: 100 %) #9062 
1. Reboot each node by ordering clean reboot and ensure they function upon restart (Failed 0 times in the last 30 runs. Stability: 100 %) #9062 
1. Etcd failure should recover from SIGKILL (Failed 0 times in the last 30 runs. Stability: 100 %) #10144
1. Docker Containers should use the image defaults if command and args are blank (Failed 0 times in the last 30 runs. Stability: 100 %)
1. Networking should function for intra-pod communication (Failed 0 times in the last 30 runs. Stability: 100 %)
1. Pods should be restarted with a /healthz http liveness probe (Failed 0 times in the last 30 runs. Stability: 100 %)
1. Proxy version v1beta3 should proxy to cadvisor (Failed 0 times in the last 30 runs. Stability: 100 %)

**Comment by wojtek-t** [comment]
I will look into "Proxy version v1 should proxy logs on node" - this failed twice during last 10 runs.

**Comment by wojtek-t** [comment]
The "Proxy version v1 should proxy logs on node" failures were caused by running the just after "should be able to delete nodes" test which didn't clean up properly after itself. Will send a PR for it in few minutes.

**Comment by wojtek-t** [comment]
#10739 sent out for review.

Also, all the "Reboot each node ..." test failures should be fixed by #10703 which is also under review.

**Comment by wojtek-t** [comment]
I started looking into "should be able to override the image's default arguments (docker cmd)" failures, but so far I didn't find anything worth noting.

**Comment by zmerlynn** [comment]
"Proxy version v1 should proxy logs on node *" failed again on build 3400, after this went in. I don't think this is fixed yet.

**Comment by wojtek-t** [comment]
Thanks @zmerlynn - I think the problem is very similar here - the test run just after "recreates pods scheduled on the unreachable minion node AND allows scheduling of pods on a minion after it rejoins the cluster" which also makes one of the nodes not ready. 
I will look into it tomorrow.

**Comment by zmerlynn** [comment]
Hrm, maybe we need a general "leaving e2e cluster state checker" fixture that could check for these kinds of things.

**Comment by quinton-hoole** [comment]
Yes, agreed, a standard precondition check before every check seems sensible.  We could add it to e2e/util/Framework (or where-ever that stuff lives these days).

**Comment by wojtek-t** [comment]
+1 - this would be very useful - I can look into it after debugging the test itself.

**Comment by quinton-hoole** [comment]
Assigning to @davidopp to report on test status in my vacation absence.

**Comment by wojtek-t** [comment]
Updated status

The following tests are still flaky:

1. Pod Disks should schedule a pod w/ a readonly PD on two hosts, then remove both. 
(Failed 6 times in the last 30 runs. Stability: 80 %) - #11302 
2. Nodes Resize should be able to add nodes 
(Failed 2 times in the last 19 runs. Stability: 89 %) - #11442
3. Proxy version v1 should proxy logs on node
(Failed 2 times in the last 30 runs. Stability: 93 %) - #10792
4. Cluster level logging using Elasticsearch should check that logs from pods on all nodes are ingested into Elasticsearch (Failed 1 times in the last 20 runs. Stability: 95 %) - #9486
5. Shell should pass tests for services.sh
(Failed 2 times in the last 30 runs. Stability: 93 %) - I looked into it and it was due to #11215

**Comment by zmerlynn** [comment]
The `release-1.0` branch has seen consistent flakes of `Kubernetes e2e
suite.Services should release the load balancer when Type goes from
LoadBalancer -> NodePort`.

**Comment by gmarek** [comment]
I think we don't need this umbrella bug any more. @quinton-hoole ?

**Comment by quinton-hoole** [comment]
@gmarek, agreed.  I'll replace this with a label to group all flaky/broken test issues.
