### ISSUE TITLE
kubeadm upgrade plan fails on missing configmap kubelet-config-1.19

### ISSUE THREAD

**Issue by stephan2012** [kubernetes/kubernetes#94524]
**What happened**:

`kubeadm upgrade plan v1.19.0` fails because it does not find configmap `kubelet-config-1.19` (which will be created during `apply`):

```
# kubeadm upgrade plan v1.19.0 
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[preflight] Running pre-flight checks.
[upgrade] Running cluster health checks
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.18.8
[upgrade/versions] kubeadm version: v1.19.0
[upgrade/versions] Latest stable version: v1.19.0
[upgrade/versions] Latest version in the v1.18 series: v1.19.0

[upgrade/versions] FATAL: configmaps "kubelet-config-1.19" not found
To see the stack trace of this error execute with --v=5 or higher
```

However, `kubeadm upgrade apply` creates the new configmap and succeeds:

```
# kubeadm upgrade apply v1.19.0 --etcd-upgrade --certificate-renewal  -y
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
W0904 15:25:49.084631    5644 kubelet.go:205] detected "systemd" as the Docker cgroup driver, the provided value "cgroupfs" in "KubeletConfiguration" will be overrided
[preflight] Running pre-flight checks.
[upgrade] Running cluster health checks
[upgrade/version] You have chosen to change the cluster version to "v1.19.0"
[upgrade/versions] Cluster version: v1.18.8
[upgrade/versions] kubeadm version: v1.19.0
[upgrade/prepull] Pulling images required for setting up a Kubernetes cluster
[upgrade/prepull] This might take a minute or two, depending on the speed of your internet connection
[upgrade/prepull] You can also perform this action in beforehand using 'kubeadm config images pull'
[upgrade/apply] Upgrading your Static Pod-hosted control plane to version "v1.19.0"...
Static pod: kube-apiserver-n0201 hash: 625fc74237a91f55b2f6e6e08b713af8
Static pod: kube-controller-manager-n0201 hash: 3fa548d809e9f8c09c591642fd54ed15
Static pod: kube-scheduler-n0201 hash: 16a506fb7af80006f5249e9e06cb176d
[upgrade/etcd] Upgrading to TLS for etcd
Static pod: etcd-n0201 hash: 4603b7fe1c65fd3be258e5e75c63bc5a
[upgrade/staticpods] Preparing for "etcd" upgrade
[upgrade/staticpods] Renewing etcd-server certificate
[upgrade/staticpods] Renewing etcd-peer certificate
[upgrade/staticpods] Renewing etcd-healthcheck-client certificate
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/etcd.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2020-09-04-15-25-52/etcd.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s)
Static pod: etcd-n0201 hash: 4603b7fe1c65fd3be258e5e75c63bc5a
Static pod: etcd-n0201 hash: 9b0f91af0b007ed01541d0a3dc6737d0
[apiclient] Found 3 Pods for label selector component=etcd
[upgrade/staticpods] Component "etcd" upgraded successfully!
[upgrade/etcd] Waiting for etcd to become available
[upgrade/staticpods] Writing new Static Pod manifests to "/etc/kubernetes/tmp/kubeadm-upgraded-manifests232020735"
[upgrade/staticpods] Preparing for "kube-apiserver" upgrade
[upgrade/staticpods] Renewing apiserver certificate
[upgrade/staticpods] Renewing apiserver-kubelet-client certificate
[upgrade/staticpods] Renewing front-proxy-client certificate
[upgrade/staticpods] Renewing apiserver-etcd-client certificate
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/kube-apiserver.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2020-09-04-15-25-52/kube-apiserver.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s)
Static pod: kube-apiserver-n0201 hash: 625fc74237a91f55b2f6e6e08b713af8
Static pod: kube-apiserver-n0201 hash: 75a68334d14fabcb5146e4a9a0cb3ba0
[apiclient] Found 3 Pods for label selector component=kube-apiserver
[upgrade/staticpods] Component "kube-apiserver" upgraded successfully!
[upgrade/staticpods] Preparing for "kube-controller-manager" upgrade
[upgrade/staticpods] Renewing controller-manager.conf certificate
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/kube-controller-manager.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2020-09-04-15-25-52/kube-controller-manager.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s)
Static pod: kube-controller-manager-n0201 hash: 3fa548d809e9f8c09c591642fd54ed15
Static pod: kube-controller-manager-n0201 hash: 2133c4ee12b6506279e17be9d04e0c4a
[apiclient] Found 3 Pods for label selector component=kube-controller-manager
[upgrade/staticpods] Component "kube-controller-manager" upgraded successfully!
[upgrade/staticpods] Preparing for "kube-scheduler" upgrade
[upgrade/staticpods] Renewing scheduler.conf certificate
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/kube-scheduler.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2020-09-04-15-25-52/kube-scheduler.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s)
Static pod: kube-scheduler-n0201 hash: 16a506fb7af80006f5249e9e06cb176d
Static pod: kube-scheduler-n0201 hash: c6c30d6ecf104efab67858c77d223047
[apiclient] Found 3 Pods for label selector component=kube-scheduler
[upgrade/staticpods] Component "kube-scheduler" upgraded successfully!
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config-1.19" in namespace kube-system with the configuration for the kubelets in the cluster
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[bootstrap-token] configured RBAC rules to allow Node Bootstrap tokens to get nodes
[bootstrap-token] configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstrap-token] configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstrap-token] configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
W0904 15:26:15.620541    5644 dns.go:282] the CoreDNS Configuration will not be migrated due to unsupported version of CoreDNS. The existing CoreDNS Corefile configuration and deployment has been retained.
[addons] Applied essential addon: CoreDNS
[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
[addons] Applied essential addon: kube-proxy

[upgrade/successful] SUCCESS! Your cluster was upgraded to "v1.19.0". Enjoy!

[upgrade/kubelet] Now that your control plane is upgraded, please proceed with upgrading your kubelets if you haven't already done so.
```

**What you expected to happen**:

`kubeadm upgrade plan` should not fail on objects that are created during upgrade.

**How to reproduce it (as minimally and precisely as possible)**:

1. Have a kubeadm Kubernetes cluster (v1.18)
2. Run `kubeadm upgrade plan v1.19.0`

**Anything else we need to know?**:

`kubeadm` did not fail for `v1.15`, `v1.16`, `v1.17`, and `v1.18`

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.18.8`, kubeadm version `v1.19.0`
- Cloud provider or hardware configuration: Bare metal, kubeadm
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): `Linux n0201 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: `kubeadm`
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by neolit123** [comment]
hi, this should be fixed in 1.19.1.
https://github.com/kubernetes/kubeadm/issues/2274

/close

**Comment by geotransformer** [comment]
> @neolit123: Closing this issue.

Seems not fixed or happened again

$ sudo kubeadm upgrade plan --config=/etc/kubernetes/kubeadmin-config.yaml
[upgrade/config] Making sure the configuration is correct:
W0907 09:19:49.862338   19491 common.go:94] WARNING: Usage of the --config flag with kubeadm config types for reconfiguring the cluster during upgrade is not recommended!
[preflight] Running pre-flight checks.
[upgrade] Running cluster health checks
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.20.0
[upgrade/versions] kubeadm version: v1.21.0
[upgrade/versions] Target version: v1.21.0
[upgrade/versions] Latest version in the v1.20 series: v1.21.0

[upgrade/versions] FATAL: configmaps "kubelet-config-1.21" not found
To see the stack trace of this error execute with --v=5 or higher

**Comment by neolit123** [comment]
passing --config to upgrade is not recommended, you should just pass a version as flag.
what are the contents of the file?

**Comment by ak2766** [comment]
The same thing for me trying to go from `v1.21.7` to `v1.22.4`:

```
# kubeadm upgrade plan
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[preflight] Running pre-flight checks.
[upgrade] Running cluster health checks
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.21.7
[upgrade/versions] kubeadm version: v1.22.4
[upgrade/versions] Target version: v1.22.4
[upgrade/versions] Latest version in the v1.21 series: v1.21.7

[upgrade/versions] FATAL: configmaps "kubelet-config-1.21" not found
To see the stack trace of this error execute with --v=5 or higher
```

**Comment by ak2766** [comment]
So, today I tried something.  I did this:
```
# kubectl -n kube-system get cm kubelet-config-1.20 -oyaml | sed 's/1.20/1.21/' | kubectl apply -f -
configmap/kubelet-config-1.21 created
```

I then tried the `kubeadm upgrade plan` command again and what do you know:

<details>
<summary>Upgrade Plan</summary>

```
# kubeadm upgrade plan
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[preflight] Running pre-flight checks.
[upgrade] Running cluster health checks
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.21.7
[upgrade/versions] kubeadm version: v1.22.4
[upgrade/versions] Target version: v1.22.4
[upgrade/versions] Latest version in the v1.21 series: v1.21.7

Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT        TARGET
kubelet     10 x v1.21.7   v1.22.4

Upgrade to the latest stable version:

COMPONENT                 CURRENT   TARGET
kube-apiserver            v1.21.7   v1.22.4
kube-controller-manager   v1.21.7   v1.22.4
kube-scheduler            v1.21.7   v1.22.4
kube-proxy                v1.21.7   v1.22.4
CoreDNS                   1.7.0     v1.8.4

You can now apply the upgrade by executing the following command:

        kubeadm upgrade apply v1.22.4

_____________________________________________________________________


The table below shows the current state of component configs as understood by this version of kubeadm.
Configs that have a "yes" mark in the "MANUAL UPGRADE REQUIRED" column require manual config upgrade or
resetting to kubeadm defaults before a successful upgrade can be performed. The version to manually
upgrade to is denoted in the "PREFERRED VERSION" column.

API GROUP                 CURRENT VERSION   PREFERRED VERSION   MANUAL UPGRADE REQUIRED
kubeproxy.config.k8s.io   v1alpha1          v1alpha1            no
kubelet.config.k8s.io     v1beta1           v1beta1             no
_____________________________________________________________________
```

</details>

I'm going to destroy the cluster again and detail the steps I'm having to take manually that `kubeadm` is no longer doing.  The one that is very annoying is that on upgrade, the static pod manifests aren't being updated contrary to the messages spewed out during the upgrade.  I have to go to the `/etc/kubernetes/manifests` directory move the files somewhere, manually change the `image:` key to point to the proper version, then move them back.

This was annoying twice then I created a bash script to sort this out.  Sometimes it's just easier to take matters into ones hands and make your own destiny.  Life's too short...

**Comment by ak2766** [comment]
I've created a new issue: #106767
