### ISSUE TITLE
Rejection of a waiting pod in scheduler may cause delay of its rescheduling

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#96478]
In the discussion of https://github.com/kubernetes/kubernetes/pull/82222#issuecomment-719100360, we found a glitch that rejecting a waiting Pod triggers `sched.deletePodFromSchedulingQueue(`) instead of `sched.deletePodFromCache()`. The minor difference results in the preemptor pod lost the immediate chance to be moved back to activeQ/backoffQ - it has to wait for the next flushOff tick to be re-scheduled.

This is not a big issue due to we have flushOff mechanics. But be ware of this issue when writing tests, and also this can be a blocker issue if we want to totally remove the flushOff mechanism when building a more generic "moving pods back to queue" way.

/sig scheduling
/kind backlog

**Comment by Huang-Wei** [comment]
cc/ @cwdsuzhou @denkensk @yuanchen8911

**Comment by denkensk** [comment]
```go
waitOnPermitStatus := fwk.WaitOnPermit(bindingCycleCtx, assumedPod)
if !waitOnPermitStatus.IsSuccess() {
    var reason string
    if waitOnPermitStatus.IsUnschedulable() {
        metrics.PodUnschedulable(fwk.ProfileName(), metrics.SinceInSeconds(start))
        reason = v1.PodReasonUnschedulable
    } else {
        metrics.PodScheduleError(fwk.ProfileName(), metrics.SinceInSeconds(start))
        reason = SchedulerError
    }
    // trigger un-reserve plugins to clean up state associated with the reserved Pod
    fwk.RunReservePluginsUnreserve(bindingCycleCtx, state, assumedPod, scheduleResult.SuggestedHost)
    if forgetErr := sched.SchedulerCache.ForgetPod(assumedPod); forgetErr != nil {
        klog.Errorf("scheduler cache ForgetPod failed: %v", forgetErr)
    }
    sched.recordSchedulingFailure(fwk, assumedPodInfo, waitOnPermitStatus.AsError(), reason, "")
    return
}
```

I find that Rejecting a waiting Pod will trigger `sched.SchedulerCache.ForgetPod` to delete Pod From Cache.

**Comment by Huang-Wei** [comment]
That's true, otherwise it's a huge issue... What I was referring to is that the rejected Pod don't have an immediate chance to be rescheduled.

**Comment by denkensk** [comment]
Yes. Can we add some mechanism to trigger `MoveAllToActiveOrBackoffQueue` after a waiting Pod is rejected ? 
It seems that we've discussed similar issues before.

**Comment by Huang-Wei** [comment]
Yes, it belongs to the "Efficient Rescheduling" context.

Ref:

- https://docs.google.com/document/d/1Dw1qPi4eryllSv0F419sKVbGXiPvSv6N_mJd6AVSg74/edit#
- https://github.com/kubernetes/kubernetes/pull/92206#issuecomment-662609698

@alculquicondor may have already created an umbrella issue, but I cannot find it.

@denkensk feel free to roll this forward.

**Comment by alculquicondor** [comment]
#94009

Worth discussing what we can do in the next release.

**Comment by alculquicondor** [comment]
@Huang-Wei I seem to remember that we fixed this somehow. Is it not the case?

**Comment by Huang-Wei** [comment]
@alculquicondor I think this problem still exists - suppose Pod1 gets permitted (and thus assumed), and then waited there. Now Pod2 and Pod3 come in but cannot be schedulable because resources have been occupied by Pod1. Then here comes Pod4 which has a higher priority than Pod1 and thus preempt Pod1. Preempting Pod1 will trigger `deletePodFromSchedulingQueue()` which doesn't signal an event to trigger `MoveAllToActiveOrBackoffQueue()`, which means Pod2/Pod3 don't have an immediate chance to be retried.

A simple solution is to introduce a return value for `RejectWaitingPod()`:

https://github.com/kubernetes/kubernetes/blob/33aba7ee025dfddcc140d20e9ca353ffd425f1ae/pkg/scheduler/eventhandlers.go#L177

If rejecting succeeds, it indicates a waiting Pod gets removed from the internal _assumedPods_ struct - it should be treated as a **PodDelete** event so as to immediately moving relevant pods (in the above example, Pod2 & Pod3)

**Comment by alculquicondor** [comment]
I see. The solution sounds reasonable to me.

Why is it a delete, given that Pod1 was never actually scheduled? Shouldn't Pod1 be tried again?

**Comment by Huang-Wei** [comment]
> Why is it a delete, given that Pod1 was never actually scheduled? 

A waiting Pod is assumed, and hence occupied a certain amount of resources, so pretty work like other scheduled pods. So IMO a waiting Pod's deletion is best treated as a PodDelete event.

> Shouldn't Pod1 be tried again?

It will - upon its new entity that's created by its controller. As preemption will physically delete the current Pod entity.

**Comment by Huang-Wei** [comment]
Hmm, some explanation in https://github.com/kubernetes/kubernetes/issues/96478#issuecomment-882740031 and https://github.com/kubernetes/kubernetes/issues/96478#issuecomment-882811368 is not accurate because of #100325 - now the default preemption plugin doesn't physically delete a waiting pod anymore.

So in terms of fix, we have to cover two cases:

- a waiting pod is physically deleted by external components.
- a waiting pod is rejected (but not physically deleted) by the default preemption plugin.

**Comment by alculquicondor** [comment]
Both should call `MoveAllToActiveOrBackoffQueue(queue.AssignedPodDelete, nil)`, right?

**Comment by Huang-Wei** [comment]
> Both should call `MoveAllToActiveOrBackoffQueue(queue.AssignedPodDelete, nil)`, right?

That's correct. I created PR #103805 to address this.
