### ISSUE TITLE
OVS Bridge obr0 fails when running a cluster with PROVIDER=Vagrant

### ISSUE THREAD

**Issue by perljedi** [kubernetes/kubernetes#9861]
After the update to Fedora-21 and Docker 1.6 in the vagrant set up, I am not able to access any kubernetes service ip addresses from a pod.  This appears to be the result of a problem with the settings for the obr0 bridge created by ovs. 

```bash
[root@kubernetes-master ~]# ovs-ofctl show obr0
2015-06-16T14:18:38Z|00001|vconn|WARN|unix:/var/run/openvswitch/obr0.mgmt: version negotiation failed (we support version 0x01, peer supports version 0x04)
ovs-ofctl: obr0: failed to connect to socket (Broken pipe)
```

**Comment by perljedi** [comment]
if it helps, I have a one line patch ready that will fix this.

**Comment by rajatchopra** [comment]
Need to use 'ovs-vsctl show obr0', or 'ovs-ofctl -O OpenFlow13 dump-flows obr0'
Another error with multi-host networking fixed by #10073

**Comment by thockin** [comment]
Is this still an issue?  What is the one-line fix?

**Comment by perljedi** [comment]
#10073 Did not fix it in my environment, but I am only using the Vagrant/Fedora/OVS set up for my dev instance, so I I just switched to Vagrant/CoreOS/Weave.

The one line I suggested was:
https://github.com/GoogleCloudPlatform/kubernetes/pull/10025

but there is some disagreement about whether that actually fixes it.

**Comment by thockin** [comment]
I have no basis on which to evaluate this issue - should I leave it open?
 close it?  bother somebody (who?) to do something (what?)

**Comment by rajatchopra** [comment]
I tried the setup again today and it works for me. To be sure whether kube2sky can see apiserver properly, I checked that there is active connection maintained inside the container (running on one of the nodes).

```
[root@kubernetes-minion-1 ~]# docker ps | grep kube2sky
81030a232acd        gcr.io/google_containers/kube2sky:1.9            "/kube2sky -domain=c   3 hours ago         Up 3 hours                              k8s_kube2sky.2f4e64af_kube-dns-v3-kgaoa_default_8e5dedd2-1ad8-11e5-a3e6-0800279dd272_9f8a1959
[root@kubernetes-minion-1 ~]# docker inspect 81030a232acd | grep Pid
        "PidMode": "",
        "Pid": 3710,
[root@kubernetes-minion-1 ~]# docker exec 81030a232acd /bin/sh -c netstat -utan | grep kube
tcp        0      0 kube-dns-v3-kgaoa:34190 10.247.0.1:https        ESTABLISHED 
tcp        0      0 kube-dns-v3-kgaoa:34192 10.247.0.1:https        ESTABLISHED 
udp        0      0 kube-dns-v3-kgaoa:41703 10.0.2.3:domain         ESTABLISHED 

```

May I suggest @derekwaynecarr try once too (sorry for dragging you here :))? And if there is another instance of time-out error then we need to investigate.
@perljedi Please do not think I am against the one line fix, we just need a good explanation of how it fixes the problem (an OVS bug? Fedora issue? OpenFlow protocol non-compliance?)

**Comment by derekwaynecarr** [comment]
I will try the same tomorrow.  I want to get all E2E passing this week.

**Comment by thockin** [comment]
@derekwaynecarr Any word on this?  I want to understand if this is actually a critical issue or a misconfig or something.  I'm going to have to close it if I don't hear back soon :)

**Comment by rajatchopra** [comment]
Two fixes have gone in since:  #10562 and #10568 by @derekwaynecarr which hopefully fix the vagrant issues.

**Comment by derekwaynecarr** [comment]
@thockin - per the IRC discussion we had yesterday, this is all part of getting skydns fixed up.  I am hoping to get the core issues closed today.

**Comment by thockin** [comment]
status here?

**Comment by thockin** [comment]
This is the last v1-candidate issue in this category.  At this point if it is not fixed, it's probably not in v1.  If it is fixed, please close.  Thanks!
