### ISSUE TITLE
Failing kubelet /stats/summary API and ResourceMetricsAPI tests on cgroup v2

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#99230]
#### Which jobs are failing:
pull-kubernetes-node-crio-cgrpv2-e2e

#### Which test(s) are failing:
E2eNode Suite: [k8s.io] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api
E2eNode Suite: [k8s.io] ResourceMetricsAPI [NodeFeature:ResourceMetrics] when querying /resource/metrics should report resource usage through the resource metrics api

#### Since when has it been failing:
From what I have observed these tests have always failed on cgroup v2 host.

#### Testgrid link:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/99110/pull-kubernetes-node-crio-cgrpv2-e2e/1361561789094957056/

#### Reason for failure:
cgroup v2 has a different set of files compared to cgroup v1 to report the metrics. A lot of places in cadvisor, where the metrics end up getting read from, still assume cgroup v1 paths and files. 

#### Anything else we need to know:
Some of the following PRs end up addressing the issue partially, but not completely. 

https://github.com/google/cadvisor/pull/2801
https://github.com/google/cadvisor/pull/2800

**Comment by fromanirh** [comment]
still working my way towards a reproducer.

**Comment by giuseppe** [comment]
I've opened https://github.com/google/cadvisor/pull/2837 to fix one issue I've seen.

I think we will also need to modify libcontainer to return memory stats from `/proc/meminfo` for the root cgroup

/cc @kolyshkin

**Comment by giuseppe** [comment]
another fix for cadvisor: https://github.com/google/cadvisor/pull/2839

**Comment by giuseppe** [comment]
for completeness, the patch for runc/libcontainer: https://github.com/opencontainers/runc/pull/2873

**Comment by giuseppe** [comment]
this should be fixed with https://github.com/kubernetes/kubernetes/pull/102483

**Comment by giuseppe** [comment]
@harche can we close now?

**Comment by odinuge** [comment]
> @harche can we close now?

Test is still failing. See testgrid: https://testgrid.k8s.io/sig-node-cri-o#pr-crio-cgrpv2-gce-e2e

**Comment by giuseppe** [comment]
hm.. it is failing on:

```
Expected
    <string>: Summary
to match fields: {
.Node.SystemContainers[pods].Memory:
	Expected
	    <string>: MemoryStats
	to match fields: {
	.MajorPageFaults:
		Expected
		    <uint64>: 198
		to be <=
		    <int>: 10
	}
	
}
```

not sure how to deal with this test.

Should we handle it differently for cgroup v2?  Or just enable it for cgroup v1?

@kolyshkin @odinuge what do you think?

**Comment by odinuge** [comment]
I don't know _how_ changes in conformance test should be done. The issue in this case is that for cgroup v1, `pageFaults` and `majorPageFaults` will always be `0` on `kubepods.slice` due to how the hierarchy stuff works there. Not sure why the conformance test is doing `<= 0` instead of just `0`.... For v2 these value will sum all the page faults in all descendant processes below it.

Updating the value in the test is the "simplest" fix, but it doesn't solve the underlying difference in metrics when switching to cgroup v2 (eg. if this cause someones cluster to go wilde du to the "extreme" increase in this value).

Who is responsible for these metrics/stats, and who should decide what to do? sig-node? I don't really know what to do..

Maybe @ehashman has some thoughts?

**Comment by giuseppe** [comment]
I am not sure how that metric was used on cgroup v1.  We could hardcode it to 0 for cgroup v2, but I don't think it is a good idea as it finally seems to make sense  :-)  Is it just something that should be documented?

**Comment by odinuge** [comment]
> I am not sure how that metric was used on cgroup v1. We could hardcode it to 0 for cgroup v2, but I don't think it is a good idea as it finally seems to make sense :-) Is it just something that should be documented?

No idea myself. 

A quick test on my rpi using cgroup v1 I get this:

```
$ kubectl proxy &
$ curl localhost:8001/api/v1/nodes/k8s-006/proxy/stats/summary -s | jq | grep pageFaults
          "pageFaults": 0,
          "pageFaults": 11041941570, 
      "pageFaults": 889020,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
        "pageFaults": 0,
```

Where the first non-null value is `kubelet.slice` and the other one is the root control group; and that is pretty much expected based on the fact that the value is not hierarchical for cgroup v2.

Not sure who "own" this.. :thinking:

**Comment by giuseppe** [comment]
Thanks for trying that.

Opened a PR for comments: https://github.com/kubernetes/kubernetes/pull/102726

If that is not the right approach, the only alternative I see is to hardcode the value to 0.

**Comment by odinuge** [comment]
The git blame shows that this was introduced here: https://github.com/kubernetes/kubernetes/pull/57802

Do you have any thoughts about this @dashpole?

**Comment by odinuge** [comment]
Also, the structs were introduced here: https://github.com/kubernetes/kubernetes/pull/18544

/cc @tallclair

**Comment by dashpole** [comment]
I think changing the test is the right thing to do.  It is a breaking change to change the metric, but it wasn't particularly useful before.  Also, we won't be able to hide the change to the metric for pod cgroup metrics, so we might as well change it for system containers as well.

**Comment by odinuge** [comment]
> I think changing the test is the right thing to do. It is a breaking change to change the metric, but it wasn't particularly useful before. Also, we won't be able to hide the change to the metric for pod cgroup metrics, so we might as well change it for system containers as well.

Ahh, sounds good. Thanks!

**Comment by borgerli** [comment]
@harche, I'm trying to port the PR to 1.20 version which we're using with cgroups v2. Could you please give more information about the  failing tests? such as detailed failure messages. Thanks very much!

**Comment by harche** [comment]
@borgerli I see no failures in [cgroup v1](https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-conformance) and [cgroup v2](https://testgrid.k8s.io/sig-node-cri-o#pr-crio-cgrpv2-gce-e2e) jobs with the stats summary test.
