### ISSUE TITLE
ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]

### ISSUE THREAD

**Issue by chewong** [kubernetes/kubernetes#99470]
#### Which jobs are failing:

aks-engine-azure-windows-master-staging

#### Which test(s) are failing:

ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]

#### Testgrid link:

https://testgrid.k8s.io/sig-windows-azure#aks-engine-azure-windows-master-staging

#### Reason for failure:

```log
[BeforeEach] [sig-auth] ServiceAccounts
  /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:185
ï¿½[1mSTEPï¿½[0m: Creating a kubernetes client
Feb 25 05:02:27.267: INFO: >>> kubeConfig: /root/tmp027536234/kubeconfig/kubeconfig.southcentralus.json
ï¿½[1mSTEPï¿½[0m: Building a namespace api object, basename svcaccounts
ï¿½[1mSTEPï¿½[0m: Binding the e2e-test-privileged-psp PodSecurityPolicy to the default service account in svcaccounts-1159
ï¿½[1mSTEPï¿½[0m: Waiting for a default service account to be provisioned in namespace
[It] ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]
  /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:640
Feb 25 05:02:27.709: INFO: created pod
Feb 25 05:02:27.709: INFO: Waiting up to 5m0s for pod "oidc-discovery-validator" in namespace "svcaccounts-1159" to be "Succeeded or Failed"
Feb 25 05:02:27.745: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 36.061638ms
Feb 25 05:02:29.782: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 2.073066085s
Feb 25 05:02:31.820: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 4.110821092s
Feb 25 05:02:33.857: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 6.148285424s
Feb 25 05:02:35.895: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 8.185556908s
Feb 25 05:02:37.932: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 10.222762671s
Feb 25 05:02:39.970: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 12.260916438s
Feb 25 05:02:42.007: INFO: Pod "oidc-discovery-validator": Phase="Pending", Reason="", readiness=false. Elapsed: 14.298424022s
Feb 25 05:02:44.044: INFO: Pod "oidc-discovery-validator": Phase="Failed", Reason="", readiness=false. Elapsed: 16.335007708s
Feb 25 05:03:14.044: INFO: polling logs
Feb 25 05:03:14.100: INFO: Pod logs: 
2021/02/25 05:02:37 OK: Got token
2021/02/25 05:02:37 OK: got issuer https://kubernetes.default.svc.cluster.local
2021/02/25 05:02:37 Full, not-validated claims: 
openidmetadata.claims{Claims:jwt.Claims{Issuer:"https://kubernetes.default.svc.cluster.local", Subject:"system:serviceaccount:svcaccounts-1159:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1614229947, NotBefore:1614229347, IssuedAt:1614229347, ID:""}, Kubernetes:openidmetadata.kubeClaims{Namespace:"svcaccounts-1159", ServiceAccount:openidmetadata.kubeName{Name:"default", UID:"673f1367-44d6-4d18-8b06-45aa3e94d57b"}}}
2021/02/25 05:02:37 Get "https://kubernetes.default.svc.cluster.local/.well-known/openid-configuration": dial tcp: lookup kubernetes.default.svc.cluster.local: no such host
```

#### Anything else we need to know:

/sig windows
/cc @jsturtevant

**Comment by liggitt** [comment]
cc @mtaufen

**Comment by chewong** [comment]
/assign @jsturtevant 
Let me know if you want to pair on this

**Comment by jsturtevant** [comment]
We took a look at this for docker case and we believe it is happening due to Windows DNS networking limitations.  DNS can be available _sometime_ after the container starts due to the way networking is set up with docker.  In containerd the setup steps are  different so the network will be available when the container starts.  

In this case the test image does a lookup before the DNS is finished coming online and fails.

**Comment by nilo19** [comment]
it fails in linux as well https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-aks-engine-azure/1368758016026873856

**Comment by mtaufen** [comment]
From the link @nilo19 posted, it looks like the test cluster issuer might be misconfigured (--service-account-issuer is missing https, I'm not sure why this even passed kube-apiserver validation, double-checking that also):

```
Mar  8 03:21:48.894: INFO: Pod logs: 
2021/03/08 03:21:08 OK: Got token
2021/03/08 03:21:08 OK: got issuer kubernetes.default.svc
2021/03/08 03:21:08 Full, not-validated claims: 
openidmetadata.claims{Claims:jwt.Claims{Issuer:"kubernetes.default.svc", Subject:"system:serviceaccount:svcaccounts-1656:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1615174267, NotBefore:1615173667, IssuedAt:1615173667, ID:""}, Kubernetes:openidmetadata.kubeClaims{Namespace:"svcaccounts-1656", ServiceAccount:openidmetadata.kubeName{Name:"default", UID:"47524b80-c9c4-4e7b-b49c-8f887b1392d4"}}}
2021/03/08 03:21:08 Get "kubernetes.default.svc/.well-known/openid-configuration": unsupported protocol scheme ""
```

Try setting `--service-account-issuer=https://kubernetes.default.svc.cluster.local` on kube-apiserver.

**Comment by mtaufen** [comment]
@liggitt reminded me we couldn't actually add that validation, because we weren't  previously validating schemes and it would've broken existing clusters with bad issuers set...

So as far as fixing the tests make sure issuers have schemes, at least.

**Comment by jsturtevant** [comment]
Thanks! The failures on the Linux tests are a separate issue from the Windows failures on docker.  I opened  kubernetes-sigs/cloud-provider-azure#542 to resolve the Linux failures (we have already done this for Windows: https://github.com/kubernetes-sigs/windows-testing/pull/247)

**Comment by jsturtevant** [comment]
/reopen
This is still an issue for windows docker. https://github.com/kubernetes/kubernetes/pull/99860  fixes it

**Comment by chewong** [comment]
We use aks-engine (self-managed cluster instead of managed AKS cluster) to run the tests. For aks-engine, I opened a PR (https://github.com/Azure/aks-engine/pull/4262) to fix the service account issuer. For AKS, I can confirm that the service account issuer does not any scheme in the URL at all.

Tagging @jackfrancis, who works on aks-engine.
Tagging @weinong, who works on AKS.

**Comment by jsturtevant** [comment]
We confirmed that is being fixed in AKS.

**Comment by nilo19** [comment]
Our ipv6 test is still failing:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-azure-conformance-ipv6/1385049259778248704

The service issuer has been set to `https://kubernetes.default.svc.cluster.local`.

**Comment by jsturtevant** [comment]
@nilo19 that seems to be a different issue than Windows. could you open a new issue and tag @chewong and me?
